### PR TITLE
front : fix rounding budget in a study and a scenario

### LINKED ISSUE #3170: rounding of the budget of a Study and a Project.
### What happened?

When I enter a budget value other than a round number, the application automatically rounds the value. This can lead to differences of several thousand or even millions of euros.

Capture d’écran 2023-02-13 à 14 38 31
Capture d’écran 2023-02-13 à 14 38 45

### What did you expect to happen?

I would like the price I enter when I create or modify a study or project to be the one displayed. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Project in "etudes d'exploitation"
2. Choose a budget (do not use a value that ends in zero) 
3. See error

### What operating system and browser are you using? (if applicable)

- Macbook Pro M1
- Google Chrome 22

### OSRD version

3dbd56326a0bf67d9b2902f1017295ec17c19250

### PR DESCRIPTION
**Pull request by younesschrifi**
Close #3170

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Project.jsx [hunk 1]
```diff
@@ -194,7 +193,7 @@ export default function Project() {
                 </div>
                 <div className="project-details-financials-amount">
                   <span className="project-details-financials-amount-text">{t('totalBudget')}</span>
-                  {budgetFormat(project.budget)}
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/views/Project.jsx]: you need to fix the `budgetFormat` function.

can you create a unit test for each of the cases you want work ?
you can create a file `utils/__tests__/numbers.spec.ts` for the tests

**Review by anisometropie — CHANGES_REQUESTED** [review]

**Review by anisometropie — APPROVED** [review]
