### PR TITLE
front: review length field on editor

### LINKED ISSUE #7489: front: update tracksection length
### What happened?

Sometimes in the editor, when you update a track section length and save it, it has no effect ...
The json patch send to the back is empty

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

I don't have a clear scenario to reproduce it everytime ...

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

fd6a65c

### PR DESCRIPTION
**Pull request by sim51**
fix #7489

On the editor, the length field directly impacts curves & slopes. 

When changing from `10800` to `11000`, you need to pass through the value `1` ,which trigger a re-computation of curves, and you lost all the data from `1` to `10800`.

To avoid that, a debounce of 1.5sec has been set on this field, but it introduces  a new bug : if you change the value and press enter in less than 1.5sec, the new value is not send to the backend.

So to fix those issues, this commit : 
- put the length on the top of the form with a separator
- add a user validation mechanism  via a button

The design has been done Thibaut.

### CODE REVIEW

File: front/src/applications/editor/components/LinearMetadata/FormLineStringLength.tsx [hunk 1]
```diff
@@ -1,78 +1,52 @@
...
+        value={length}
+        onChange={(e) => {
+          setLength(e.target.valueAsNumber);
+        }}
+      />
+      <div className="my-1 d-flex justify-content-end">
+        <button
+          type="button"
+          disabled={!hasChanged}
+          className={cx('btn btn-sm btn-secondary', !hasChanged && 'disabled')}
```
Comment (SharglutDev) [inline front/src/applications/editor/components/LinearMetadata/FormLineStringLength.tsx]: For conditional classnames with cx, we use this syntax : 

```suggestion
          className={cx('btn btn-sm btn-secondary', { disabled: !hasChanged })}
```

File: front/src/applications/editor/components/LinearMetadata/FormLineStringLength.tsx [hunk 2]
```diff
@@ -1,78 +1,52 @@
...
+          onClick={() => setLength(toNumber(value))}
+        >
+          {t('common.cancel')}
+        </button>
+        <button
+          type="button"
+          disabled={!hasChanged}
+          className={cx('ml-1 btn btn-sm btn-primary', !hasChanged && 'disabled')}
```
Comment (SharglutDev) [inline front/src/applications/editor/components/LinearMetadata/FormLineStringLength.tsx]: same here

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for this PR and the nice comment history in the issue.

Left just a syntax comment. 

And regarding your comments in the issue, it seems we can still press "enter" in the length field, resulting to saving the form with an empty payload.

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested. Thank your for the changes :)
