### PR TITLE
Fix add via on Map

### LINKED ISSUE #6642: Adding a via between 2 existing vias throws an error
### What happened?

When adding a train, in the itinerary tab, if we try to add a via between two existing vias, it sometimes results wuth this error : 
Capture d’écran 2024-02-14 à 16 36 25

It seems that the new via is added after the existing one in the path list so the train can't go backwards.

### What did you expect to happen?

Adding a via between two existing vias should add it with the correct index/order in the list.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Launch a pathfinding and add 2 vias
3. Add a third via between the 2 others

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: macOS Sonoma
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev f00b337

### LINKED ISSUE #6700: Reordering Failure in via insertion form After Successful Drag and Drop
### What happened?

On the form that lists via points along the itinerary, the first reorder works perfectly, but any attempts to reorder again after the initial success don't work—the items don't move to their new spots.

### What did you expect to happen?

Users should be able to move any stop point to a new position at any time, with the list updating to reflect the new order of stop points after each move.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open any scenario within the operational studies application.
2. Add a new train or modify an existing one.
3. Create an itinerary for the selected train.
4. Add several stop points (vias) to the itinerary.
5. Attempt to reorder the stop points by using the drag and drop feature.

### What operating system, browser and environment are you using?

- **Browser**: Chromium 
- **OS**: 121.0.6167.184
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

fe945c3

### PR DESCRIPTION
**Pull request by kmer2016**
Fixed #6642 - Now, in most cases, you can place stop points (vias) exactly where they should be.
Fixed #6700 - Made dragging and dropping stop points (vias) work right.

### CODE REVIEW

File: front/src/utils/physics.ts [hunk 1]
```diff
@@ -19,3 +19,47 @@ export function msToKmh(v: number) {
...
+ * @example
+ * const paris = { lat: 48.8566, long: 2.3522 };
+ * const london = { lat: 51.5074, long: -0.1278 };
+ * const distance = haversineDistance(paris, london);
+ * console.log(distance); // Display distance between Paris and London in kilometers.
+ *
+ * For more information on the Haversine formula, see:
+ * https://en.wikipedia.org/wiki/Haversine_formula
+ */
+export const birdFlyDistanceInKm = (
```
Comment (anisometropie) [inline front/src/utils/physics.ts]: we have turf that already does this for us.

https://turfjs.org/docs/#distance

**Review by anisometropie — CHANGES_REQUESTED** [review]

File: front/src/reducers/osrdconf/helpers.ts [hunk 2]
```diff
@@ -70,3 +75,31 @@ export const computeLinkedOriginTimes = (
...
   };
 };
+
+export const insertVia = (
+  vias: PointOnMap[],
+  origin: PointOnMap,
+  destination: PointOnMap,
+  newVia: PointOnMap
+): PointOnMap[] => {
+  const res = [...vias];
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/helpers.ts]:
```suggestion
  const updatedVias = [...vias];
```

File: front/src/reducers/osrdconf/helpers.ts [hunk 3]
```diff
@@ -70,3 +75,31 @@ export const computeLinkedOriginTimes = (
...
+  const fullRouteCoordinates = [
+    origin.coordinates!,
+    ...vias.map((v) => v.coordinates!),
+    destination.coordinates!,
+  ];
+  const newViaPoint = point(newVia.coordinates!);
+
+  const nearestPoint = nearestPointOnLine(lineString(fullRouteCoordinates), newViaPoint);
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/helpers.ts]:
```suggestion
  const nearestPointOnPath = nearestPointOnLine(lineString(fullRouteCoordinates), newViaPoint);
```

File: front/src/reducers/osrdconf/helpers.ts [hunk 4]
```diff
@@ -70,3 +75,31 @@ export const computeLinkedOriginTimes = (
...
+
+  const insertIndex = fullRouteCoordinates.findIndex((_, index) => {
+    if (index === 0) return false;
+    if (index === fullRouteCoordinates.length - 1) return true;
+    const segmentToPoint = lineString(fullRouteCoordinates.slice(0, index + 1));
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/helpers.ts:99]:
```suggestion
    // Makes the function imperfect as insert might fail in a curvy path
    const segmentToPoint = lineString(fullRouteCoordinates.slice(0, index + 1));
```

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts [hunk 5]
```diff
@@ -358,16 +358,75 @@ const testCommonConfReducers = (slice: OperationalStudiesConfSlice | StdcmConfSl
     expect(state.vias).toBe(newVias);
   });
 
-  it('should handle addVias', () => {
-    const via1 = testDataBuilder.buildPointOnMap({ id: 'via-1' });
-    const via2 = testDataBuilder.buildPointOnMap({ id: 'via-2' });
-    const store = createStore(slice, {
-      vias: [via1],
+  describe('should handle addVias', () => {
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts:361]: Is it worth to test both the action and the function as they do the same thing ? Maybe the action is enough ?

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Great job for fixing these bugs ! Just left some comments to improve maintainability and one on tests.

Also you can squash all commits into one as most of the code of the two firsts is removed

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts (hunk 5 above)
Comment (kmer2016) [reply front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts:361]: Testing both helps us catch more mistakes. The action test checks integration with Redux and state updates, while the function test focuses on specific business logic. This way, we make our code stronger and find problems easier.

File: front/src/reducers/osrdconf/helpers.ts (hunk 3 above)
Comment (kmer2016) [reply front/src/reducers/osrdconf/helpers.ts]: done !

File: front/src/reducers/osrdconf/helpers.ts (hunk 4 above)
Comment (kmer2016) [reply front/src/reducers/osrdconf/helpers.ts:99]: Done!

File: front/src/reducers/osrdconf/helpers.ts (hunk 2 above)
Comment (kmer2016) [reply front/src/reducers/osrdconf/helpers.ts]: Done !

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts:361]: Ok fine by me :)

**Review by SharglutDev — APPROVED** [review]
Lgtm !

**Review by Math-R — APPROVED** [review]
lgtm

**Review by anisometropie — APPROVED** [review]
