### PR TITLE
Fixes rolling stock import command and a bunch of definition errors

### LINKED ISSUE #6989: Migration was not done for tests/data/rolling_stocks
### What happened?

Loading any JSON files from : https://github.com/osrd-project/osrd/tree/dev/tests/data/rolling_stocks doesn't work - ends up in error! 

..... /osrd$ ./scripts/load-railjson-rolling-stock.sh tests/data/rolling_stocks/short_fast_rolling_stock.json
Loading example rolling stock
Successfully copied 3.58kB to osrd-editoast:tmp/stock.json
2024-03-27T06:44:19.446503Z ERROR editoast: invalid type: string "G1", expected i16 at line 11 column 23

### What did you expect to happen?

The file have to be loaded when calling :  ./scripts/load-railjson-rolling-stock.sh 

### How can we reproduce it (as minimally and precisely as possible)?

**The JSON files in loading_gauge is 'G1' instead of integer value (e.g. 0)**

see : https://github.com/osrd-project/osrd/blob/dev/editoast/migrations/2024-03-18-141345_change_loading_gauge_to_smallint/up.sql

UPDATE rolling_stock
SET loading_gauge = CASE
        loading_gauge
        WHEN 'G1' THEN 0
        WHEN 'G2' THEN 1
        WHEN 'GA' THEN 2
        WHEN 'GB' THEN 3
        WHEN 'GB1' THEN 4
        WHEN 'GC' THEN 5
        WHEN 'FR3.3' THEN 6
        WHEN 'FR3.3/GB/G2' THEN 7
        WHEN 'GLOTT' THEN 8
    END;
     

**Next missing Meta data - metadata ** --> https://github.com/osrd-project/osrd/blob/ce982622116cbeff3d6b045b0d60eda4cdb6f2d8/editoast/src/schema/rolling_stock/mod.rs#L112
Example:
 metadata: {
    detail: 'BB 64700',
    family: 'LOCOMOTIVES',
    type: 'Locomotives thermiques',
    grouping: 'Locomotives diesel',
    series: 'BB 64700',
    subseries: '',
    unit: 'US',
    number: '1',
    reference: '',
  },

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

ce98262

### PR DESCRIPTION
**Pull request by leovalais**
fixes #6989 

# Editoast

- Fixes the rolling stock import command that broke after the DB type of the loading gauge became an int
  by changing the rolling stock deserialization type to `editoast_schemas::RollingStock`
- Removes fields that have no place in the RS schema (id, locked)
- Makes `{Light,}RollingStock.metadata` optional again
- Adds a bunch of defaults where needed in both the RS schema and model
- Fixes `RollingStockModel` derived properties
- Rewrites `PATCH /rolling_stock/<id>`
- Corrects the tests where needed

> [!NOTE]
> In the OpenApi, `RollingStockModel` has been aliased to `RollingStock`.
> 1. This prevents from changing the name of the type the frontend uses.
> 2. We'll remove the `Model` suffix soon.

# Front

`RollingStock.metadata` becomes nullable.

# Tests

Removes empty `metadata` in tests that was only there to make deserialization succeed.

### CODE REVIEW

**Review by shenriotpro — APPROVED** [review]
LGTM for tests/

File: editoast/editoast_schemas/src/lib.rs [hunk 1]
```diff
@@ -3,6 +3,11 @@ pub mod primitives;
 pub mod rolling_stock;
 pub mod train_schedule;
 
+pub use infra::*;
+pub use primitives::*;
+pub use rolling_stock::*;
+pub use train_schedule::*;
```
Comment (woshilapin) [inline editoast/editoast_schemas/src/lib.rs]: Can we explode this item by item instead of using `*`? By reading this, it's not straightforward what get exposed and in general, `*` imports are sometimes bringing surprises with them (for example, if you define a `struct` with the same name in this file, it will shadow one from a `*` import, or if 2 `*` import brings the same `struct` name, etc.).

File: editoast/src/main.rs [hunk 2]
```diff
@@ -1014,8 +1008,9 @@ mod tests {
         let result = import_rolling_stock(args, db_pool.clone()).await;
 
         // THEN
-        // import should not fail, as raise_panto and startup are not required for non electric
-        assert!(result.is_ok());
+        result.expect(
+            "import should succeed, as raise_panto and startup are not required for non electric",
+        );
```
Comment (woshilapin) [inline editoast/src/main.rs]: In test, I find that `assert` make all line relative to assertion explicit (`expect` does not). If you want a custom message for panic, you can also give it to `assert`.

```rust
        assert!(result.is_ok(), "import should succeed, as raise_panto and startup are not required for non electric");
```

File: editoast/src/views/rolling_stocks/mod.rs [hunk 3]
```diff
@@ -237,41 +228,33 @@ async fn update(
     Json(rolling_stock_form): Json<RollingStockForm>,
 ) -> Result<Json<RollingStockWithLiveries>> {
     rolling_stock_form.validate()?;
-    let mut db_conn = db_pool.get().await?;
+    let mut conn = db_pool.get().await?;
 
     let rolling_stock_id = path.into_inner();
+    let name = rolling_stock_form.name.clone();
```
Comment (woshilapin) [inline editoast/src/views/rolling_stocks/mod.rs:275]: Do we want to check that `assert!(path.into_inner() == rolling_stock_form.id)`? Or does DB/`diesel` will take care of that? Even if it does, don't we want to avoid calling the DB by doing a quick check before?

File: editoast/src/views/rolling_stocks/mod.rs [hunk 4]
```diff
@@ -354,6 +337,7 @@ async fn update_locked(
     let rolling_stock_locked_update_form = data.into_inner();
     let rolling_stock_id = rolling_stock_id.into_inner();
 
+    // FIXME
```
Comment (woshilapin) [inline editoast/src/views/rolling_stocks/mod.rs]: Not sure what to fix here 😅 Can you add a comment explaining what is the problem?

**Review by woshilapin — APPROVED** [review]
Nice PR and will bring some peace in the heart of our CI 😄 Only made a few minor comments, nothing blocking from merging.
Maybe aed2233417cfe7260f2c4fc03dafe9c92fff5e5b (commit 3) and 029386a939db782aaa200ace9c4abccc2bc754d5 (commit 4) should be squashed together are they tightly related to the nullability of the rolling stock metadata.

File: editoast/editoast_schemas/src/lib.rs (hunk 1 above)
Comment (leovalais) [reply editoast/editoast_schemas/src/lib.rs]: Oops! I changed my mind about that this morning but forgot to drop the commit 😅. thanks!

File: editoast/src/main.rs (hunk 2 above)
Comment (leovalais) [reply editoast/src/main.rs]: My goal here is to be explicit about why things fail, and I figured this is a nice way to trigger the panic while staying concise (which is important in tests). Admittedly the `assert!` message is less opinionated, I'll use that.

File: editoast/src/views/rolling_stocks/mod.rs (hunk 3 above)
Comment (leovalais) [reply editoast/src/views/rolling_stocks/mod.rs:275]: There's no `id` in `RollingStockForm`. We also don't check the name equality since the PATCH may rename the rolling stock.

**Review by flomonster — APPROVED** [review]
Thanks for the fix. Tested and reviewed.

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
