### PR TITLE
front: fix selected track display

### LINKED ISSUE #10372: Inconsistency between the selected track and the track displayed
### What happened?

Inconsistency between the selected track and the track displayed : 
Image

### What did you expect to happen?

Consistency between the track selected and the one displayed

### How can we reproduce it (as minimally and precisely as possible)?

Go to scenario
add a via with a click on the map
add train 
see the difference

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

-

### LINKED ISSUE #10414: Itinerary marker not always defined
### What happened?

In some cases, vias information is not displayed
Image

### What did you expect to happen?

This information should be displayed

### How can we reproduce it (as minimally and precisely as possible)?

Go to scenario
Edit one train
Go to itinerary section
See the bug

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

b1036ac

### PR DESCRIPTION
**Pull request by theocrsb**
fix #10372
fix #10414

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 1]
```diff
@@ -246,15 +247,19 @@ const StdcmConfig = ({
...
-            id="stdcm-map-config"
-            hideAttribution
-            hideItinerary
-            preventPointSelection
-            pathGeometry={pathfinding?.geometry}
-            showStdcmAssets
-            simulationPathSteps={markersInfo}
-          />
+          {infra && (
+            <ScenarioContextProvider infraId={infra.id}>
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: I don't think it's a good idea to depend on something from another app (operational studies).

We could remove this and in `ItineraryMarkers` use the custom hook instead : 
`const { getTrackSectionsByIds } = useCachedTrackSections(infraId);`

If it works, and as `useCachedTrackSections` will be used in both operational studies and stdcm, you can move this hook in `src/utils/hooks` (in a separate commit probably, before the main one).

Then you should be able to remove `ScenarioContextProvider` from here and `StdcmResults`

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 2]
```diff
@@ -65,49 +71,88 @@ const formatPointWithNoName = (
...
+  showStdcmAssets: boolean,
+  suggestedOP: SuggestedOP[]
+): MarkerProperties[] =>
+  pathSteps
+    .map((pathStep, index): MarkerProperties | null => {
+      const matchingOp = suggestedOP.find((op) =>
+        matchPathStepAndOp(pathStep as PathItemLocation, op)
+      );
+
+      if (!matchingOp) return null;
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Can't me keep `reduce` which should allow to handle that case instead of having to do a `map` and then a `filter` ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 3]
```diff
@@ -65,49 +71,88 @@ const formatPointWithNoName = (
...
+
+      if (pathStep && pathStep.coordinates) {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: `pathStep` is always defined

```suggestion
      if (pathStep.coordinates) {
```

**Comment by RomainValls** [comment]
Nice fix ! It also closes #10299, there were duplicates :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 4]
```diff
@@ -31,7 +35,8 @@ enum MARKER_TYPE {
 }
 
 type MarkerProperties = {
-  marker: MarkerInformation;
+  op: SuggestedOP;
+  pathStep: MarkerInformation;
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx:33]: Doesn't come from you but I still don't like to see a `pathStep` associated with a `MarkerInformation` type.

In a separate commit, you could rename and update the type `MarkerInformation` like this : 
```
type PathStepMarker = Pick<PathStep, 'name' | 'coordinates' | 'metadata'>
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 5]
```diff
@@ -65,49 +71,88 @@ const formatPointWithNoName = (
...
+        if (index > 0 && index < pathSteps.length - 1) {
+          return {
+            coordinates: pathStep.coordinates,
+            type: MARKER_TYPE.VIA,
+            imageSource: showStdcmAssets ? stdcmVia : viaSVG,
+            index,
+            op: matchingOp,
+            pathStep,
+          };
+        }
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Not from your PR, but you could remove the `if` and move the return at the end since if it's not the first or last index, it can only be a via
```suggestion
          return {
            coordinates: pathStep.coordinates,
            type: MARKER_TYPE.VIA,
            imageSource: showStdcmAssets ? stdcmVia : viaSVG,
            index,
            op: matchingOp,
            pathStep,
          };
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 6]
```diff
@@ -65,49 +71,88 @@ const formatPointWithNoName = (
...
-        });
+const extractMarkerInformation = (
+  pathSteps: MarkerInformation[],
+  showStdcmAssets: boolean,
+  suggestedOP: SuggestedOP[]
+): MarkerProperties[] =>
+  pathSteps
+    .map((pathStep, index): MarkerProperties | null => {
+      const matchingOp = suggestedOP.find((op) =>
+        matchPathStepAndOp(pathStep as PathItemLocation, op)
```
Comment (emersion) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Hm, this is dangerous… What is the reason why we can't replace or update `MarkerInformation`?

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx [hunk 7]
```diff
@@ -176,14 +181,18 @@ const StcdmResults = ({
...
-          <NewMap
-            id="stdcm-map-result"
-            hideAttribution
-            showStdcmAssets
-            isFeasible={!hasConflictResults}
-            pathGeometry={outputs?.pathProperties?.geometry}
-            simulationPathSteps={markersInfo}
-          />
+          {infraId && (
+            <ScenarioContextProvider infraId={infraId}>
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: Does the new code require a scenario context? It seems a bit weird to use something specific to operational studies in STDCM.

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 8]
```diff
@@ -117,70 +162,60 @@ const ItineraryMarkers = ({ map, simulationPathSteps, showStdcmAssets }: Itinera
         return formatPointWithNoName(markerLineCode, markerLineName, markerTrackName, markerType);
       }
 
-      if (!markerCoordinates) return null;
+      const { op } = markerInfo;
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx:162]: Can't we move this logic (no `markerMetaData`) directly in `extractMarkerInformation` ? In the function, we can check if the `pathStep` has no `name` and no `metadata` and add a `metadata` to it.
This will allow us not to add this extra `op` property in `MarkerProperties` and not to have some code duplication `getMarkerDisplayInformation`

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 2 above)
Comment (emersion) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Personally I find `map` + `filter` more readable than `reduce`.

Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: I was sure you had something to do with it 😏

Comment (emersion) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Most I did was nod when Theo suggested to get rid of the reduce :P

Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: I also find it easier to read

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 6 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: I just removed the cast

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx (hunk 7 above)
Comment (theocrsb) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: As you suggested, I use `useCachedTrackSections` instead

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 1 above)
Comment (theocrsb) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Done :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 3 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 5 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 4 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx:33]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 8 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx:162]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Ok I give up on this

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 9]
```diff
@@ -300,15 +300,17 @@ const StdcmConfig = ({
...
+            <NewMap
+              id="stdcm-map-config"
+              hideAttribution
+              hideItinerary
+              preventPointSelection
+              pathGeometry={pathfinding?.geometry}
+              showStdcmAssets
+              simulationPathSteps={markersInfo}
+            />
+          )}
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]:
```suggestion
            <NewMap
              id="stdcm-map-config"
              hideAttribution
              hideItinerary
              preventPointSelection
              pathGeometry={pathfinding?.geometry}
              showStdcmAssets
              simulationPathSteps={markersInfo}
            />
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 10]
```diff
@@ -65,122 +66,164 @@ const formatPointWithNoName = (
...
+
+const ItineraryMarkers = ({
+  map,
+  simulationPathSteps,
+  pathStepsAndSuggestedOPs,
+  showStdcmAssets,
+}: ItineraryMarkersProps) => {
+  const { getInfraID } = useOsrdConfSelectors();
+  const infraId = useSelector(getInfraID);
+  if (!infraId) return;
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: A component shouldn't return `undefined`, you can return `null` instead.
If yo also add `if (!markersInformation) return null;` before the component return, you will be able to remove your eslint comment and the `?` in `markersInformation?.map`
```suggestion
  if (!infraId) return null;
```

Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 9 above)
Comment (theocrsb) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 11]
```diff
@@ -47,7 +47,9 @@ type MarkerProperties = {
 type ItineraryMarkersProps = {
   map: Map;
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Now that we don't use `map` anymore. There are also some unused imports.
```suggestion
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 12]
```diff
@@ -65,122 +67,157 @@ const formatPointWithNoName = (
...
+  showStdcmAssets,
+  infraId,
+}: ItineraryMarkersProps) => {
+  const { getTrackSectionsByIds } = useCachedTrackSections(infraId);
 
-const ItineraryMarkers = ({ map, simulationPathSteps, showStdcmAssets }: ItineraryMarkersProps) => {
   const markersInformation = useMemo(
-    () => extractMarkerInformation(simulationPathSteps, showStdcmAssets),
+    () =>
+      pathStepsAndSuggestedOPs &&
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: There is one issue. As we don't pass this prop in stdcm, `markersInformation` isn't defined and there is one no marker in the stdcm maps.

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 11 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 12 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx [hunk 13]
```diff
@@ -333,11 +335,12 @@ const Map = ({
           showStdcmAssets={showStdcmAssets}
           isFeasible={isFeasible}
         />
-        {mapRef.current && (
+        {mapRef.current && infraID && (
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx]: We don't need it anymore (same in NewMap)
```suggestion
        {infraID && (
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job ! You can resolve the last comment yourself

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx (hunk 13 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx]: Done

**Review by Caracol3 — APPROVED** [review]
LGTM and tested !

File: front/src/applications/stdcm/utils/index.ts [hunk 14]
```diff
@@ -17,6 +17,7 @@ export const extractMarkersInfo = (pathSteps: StdcmPathStep[]) =>
   pathSteps.reduce((acc, step) => {
     if (step.location) {
       acc.push({
+        uic: step.location.uic,
```
Comment (emersion) [inline front/src/applications/stdcm/utils/index.ts]: Nit: should we add `secondary_code` as well here?

Comment (theocrsb) [reply front/src/applications/stdcm/utils/index.ts]: Done
