### PR TITLE
front: train set selector to display only sets from current scenario

### LINKED ISSUE #15107: Train packages : the options presented when moving a train from a package to another in a scenario are wrong
### What happened?

When I am in a scenario, and want to move one or multiple trains from one package to another, a selector is opened. 
It presents all the sets existing in the application : BUG
Then once a set is selected, in presents all the packages FROM THIS SCENARIO that correspond to this set : CORRECT

### What did you expect to happen?

I expect to be presented only the sets from this scenario

Check the ACs from this [issue](https://github.com/osrd-project/osrd-confidential/issues/758), section "Manipulations avec les missions et les trains"

### How can we reproduce it (as minimally and precisely as possible)?

Create 1 set in a scenario
Then go to another scenario, create a train and try to move it : the set from the other scenario is presented but it shouldn't

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

08f0865

### PR DESCRIPTION
**Pull request by theocrsb**
closes https://github.com/OpenRailAssociation/osrd/issues/15107

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/Timetable.tsx [hunk 1]
```diff
@@ -270,7 +270,11 @@ const Timetable = ({
           trainScheduleSets={timetableItemsByTrainScheduleSets.map((tss) => tss.trainScheduleSet)}
           setTrainScheduleSetIdSelected={setTrainScheduleSetIdSelected}
           trainScheduleSetIdSelected={trainScheduleSetIdSelected}
-          catalogEntries={catalogEntries}
+          catalogEntries={catalogEntries.filter((entry) =>
+            timetableItemsByTrainScheduleSets.some(
+              (tss) => tss.trainScheduleSet.catalog_entry_id === entry.id
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/Timetable/Timetable.tsx:275]: nit
```suggestion
              ({ trainScheduleSet }) => trainScheduleSet.catalog_entry_id === entry.id
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅ 

You can close the comment when fixed (or not)

**Review by Pivouane — APPROVED** [review]
LGTM
