### PR TITLE
front: fix graou schedules import

### LINKED ISSUE #10501: Error during import - Failed to parse duration
### What happened?

When importing data  from open data with PLY as origin and LYD as destination for 23/01/2025, I received an error in the console: 
"Failed to deserialize the JSON body into the target type: [6].schedule[0].arrival: Failed to parse duration: -PT30S at line 1 column 2584."
This error seems to mainly affect TER trains, where a negative duration (-PT30S) was not parsed correctly.

### What did you expect to happen?

I expected the import to complete successfully without any errors.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to scenario page.
2. Select PLY as origin and LYD as destination.
3. Set the date and time range to 23/01/2025 from 00:00 to 23:59.
4. Click the magnifying glass to fetch the data.
5. Click "Démarrer l'importation"
6. The error will appear in the console.

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8d71c730

### PR DESCRIPTION
**Pull request by Synar**
Close #10501

### CODE REVIEW

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx [hunk 1]
```diff
@@ -53,6 +53,20 @@ const ImportTrainScheduleConfig = ({
   const dispatch = useAppDispatch();
   const { openModal, closeModal } = useContext(ModalContext);
 
+  function filterInvalidSteps(
+    importedTrainSchedules: ImportedTrainSchedule[]
+  ): ImportedTrainSchedule[] {
+    return importedTrainSchedules.map((trainSchedule) => ({
+      ...trainSchedule,
+      steps: trainSchedule.steps.filter(
```
Comment (emersion) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: Should we really completely drop these steps? Or should we drop only the `arrival` field?

Comment (Synar) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: Good question. In the graou import it seems that the issue is not with the arrival times themselves, but with repeated or malformed, extraneous steps. We could also instead try and detect that, but the acceptance criteria would not be clear (do we start rejecting any step with empty uic for example?). We could also just skip the train entirely, since it clearly contains bad data. At the end of the day the bug comes from bad data from Graou's side, so I don't see a perfect fix on our end.

In any case, maybe we should display a warning for the users to know that some trains/steps needed to be modified/discarded?

Comment (clarani) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: Yes displaying a warning may be a good thing in any case.
Deleting problematic steps is okay IMHO

**Review by clarani — APPROVED** [review]
Code LGTM :white_check_mark:

**Review by RomainValls — APPROVED** [review]
Lgtm, tested ✅

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx (hunk 1 above)
Comment (emersion) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: Works for me!

Comment (Synar) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: Warning added!

Comment (Synar) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleConfig.tsx]: (Also technically we could try to recover bad data by looking at similar schedules in the same import and extrapolating from them, it may be worth doing if this is a critical feature, but otherwise...)

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
