### PR TITLE
Sba/front/fix pathfinding error after inversion

### LINKED ISSUE #5719: Pathfinding fails when inverting origin/destination with intermediate waypoints specified
### What happened?

I started with a properly working pathfinding on a single track:
image

And i reversed origin/destination :
image

The order of the waypoints kept the same, which lead to the pathfinding failing.

### What did you expect to happen?

Intermediate steps should be inverted too

### How can we reproduce it (as minimally and precisely as possible)?

1. Find a single track and try to reproduce this

### What operating system, browser and environment are you using?

- dev

### OSRD version (top right corner `Account` button > `Informations`)

c482536c

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #5719 

In this PR ⬇️ 

- The button to invert an itinerary has been moved out of the ModalSuggeredVias component.
- I added a function to clear the vias list in the store when we remove the origin / destination points to avoid an error after relaunching the pathfinding.

Actual behavior :

https://github.com/osrd-project/osrd/assets/103027832/40301127-c73b-45ef-abba-69fc81e5f6b4

New behavior : 

https://github.com/osrd-project/osrd/assets/103027832/5345bd85-8815-4089-bc34-b9d871608918

### CODE REVIEW

**Comment by nicolaswurtz** [comment]
Thx for the work ! 
I've got one problem: imagine station as A B C D E F
If I put F "before" E it erases all intermediates points, I think it's a bit rude :D
We could let pathfinding fail, and let the user remove vias that are "outside" path, no?

**Comment by nicolaswurtz** [comment]
image

Inversion button should be invisible when no path exists/is found

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Destination.tsx [hunk 1]
```diff
@@ -62,6 +63,7 @@ function Destination(props: DestinationProps) {
               className="btn btn-sm btn-only-icon btn-white ml-auto"
               type="button"
               onClick={() => {
+                dispatch(clearVias());
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Destination.tsx]: Why clear vias ? I don't think so, we should be able to change destination without clear all the settings of the path !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Origin.tsx [hunk 2]
```diff
@@ -104,6 +105,7 @@ function Origin(props: OriginProps) {
               className="btn btn-sm btn-only-icon btn-white"
               type="button"
               onClick={() => {
+                dispatch(clearVias());
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/DisplayItinerary/Origin.tsx]: Why clear vias ? I don't think so, we should be able to change origin without clear all the settings of the path !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx [hunk 3]
```diff
@@ -64,9 +77,8 @@ function Itinerary() {
 
   const inverseOD = () => {
     if (origin && destination) {
-      const newOrigin = { ...origin };
       dispatch(updateOrigin(destination));
-      dispatch(updateDestination(newOrigin));
+      dispatch(updateDestination(origin));
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx]: You can't be sure that `origin` will not change, you have to use a third party variable to exchange values, here !
It'll be safer to keep old code.

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/ModalSuggeredVias.tsx [hunk 4]
```diff
@@ -1,7 +1,7 @@
 import React, { useContext } from 'react';
 import { useSelector, useDispatch } from 'react-redux';
 import { useTranslation } from 'react-i18next';
-import { FaLongArrowAltUp, FaLongArrowAltDown, FaTrash, FaMinus } from 'react-icons/fa';
+import { FaTrash, FaMinus } from 'react-icons/fa';
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/ModalSuggeredVias.tsx]: It will be no cost to use octicons already ! Use `react-icons/go` from https://react-icons.github.io/react-icons/icons/go/

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx [hunk 5]
```diff
@@ -103,15 +122,40 @@ function Itinerary() {
...
+            >
+              <span className="mr-1">{t('addVias')}</span>
+              <GoPlus />
+            </button>
+          )}
+          <button className="col ml-1 my-1 btn bg-warning btn-sm" type="button" onClick={inverseOD}>
+            <span className="mr-1">{t('inverseOD')}</span>
+            <GoArrowSwitch />
+          </button>
+          <Tipped mode="left">
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx]: right

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx [hunk 6]
```diff
@@ -103,15 +122,40 @@ function Itinerary() {
         </button>
       </div>
       {displayTypeAndPath && (
-        <div className="mb-2">
+        <div className="mb-1">
           <TypeAndPath zoomToFeature={zoomToFeature} />
         </div>
       )}
+      {origin && destination && (
+        <div className="d-flex flex-row rounded-top">
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/Itinerary.tsx]: why `rounded-top` ?

**Review by nicolaswurtz — CHANGES_REQUESTED** [review]

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/ModalSuggeredVias.tsx [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import React, { useContext } from 'react';
 import { useSelector, useDispatch } from 'react-redux';
 import { useTranslation } from 'react-i18next';
-import { FaLongArrowAltUp, FaLongArrowAltDown, FaTrash, FaMinus } from 'react-icons/fa';
+import { FaMinus } from 'react-icons/fa';
```
Comment (nicolaswurtz) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Itinerary/ModalSuggeredVias.tsx]: Use octicons !

**Review by nicolaswurtz — APPROVED** [review]
Perfect, thx a lot! GG!
