### PR TITLE
front: fix study dates

### LINKED ISSUE #5479: Inconsistent dates can be entered
### What happened?

It is possible to enter inconsistent dates in the study form. end can be before start

### What did you expect to happen?

The application have to check the consistency of the dates

### How can we reproduce it (as minimally and precisely as possible)?

Create a project
Create a study
Enter inconsistent dates and see that there is no verification

### What operating system, browser and environment are you using?

- **Browser**: Version 118.0.5993.96
- **OS**: Sonoma 14.0
- **Env**: rec-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

### PR DESCRIPTION
**Pull request by Akctarus**
closes #5479 for the front part

### CODE REVIEW

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 1]
```diff
@@ -155,6 +155,19 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
     }
   }, [isCreateStudyError, isPatchStudyError, isDeleteStudyError]);
 
+  const isInvalidDate = () => {
+    if (currentStudy.start_date) {
+      const startDate = new Date(currentStudy.start_date);
+      if (currentStudy.expected_end_date && new Date(currentStudy.expected_end_date) < startDate) {
```
Comment (Wadjetz) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: You can use days.js for dates manipulation https://day.js.org/docs/en/query

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 2]
```diff
@@ -155,6 +155,19 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
...
+        return true;
+      }
+      if (currentStudy.actual_end_date && new Date(currentStudy.actual_end_date) < startDate) {
+        return true;
+      }
+    }
+    return false;
+  };
```
Comment (SarahBellaha) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: You can directly compare the string values :) 

```suggestion
 const isInvalidDate = () => {
    if (currentStudy.start_date) {
      const startDate = currentStudy.start_date;
      if (currentStudy.expected_end_date && currentStudy.expected_end_date < startDate) return true;
      if (currentStudy.actual_end_date && currentStudy.actual_end_date < startDate) return true;
    }
    return false;
  };
```

**Review by SarahBellaha — APPROVED** [review]
LGTM :)
Just left a tiny suggestion

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 2 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: Ty, fixed

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: Didn't need it anymore since we can just compare the string values

**Review by Wadjetz — APPROVED** [review]

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 3]
```diff
@@ -155,6 +155,15 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
     }
   }, [isCreateStudyError, isPatchStudyError, isDeleteStudyError]);
 
+  const isInvalidDate = () => {
```
Comment (clarani) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Use a useMemo instead of a function
```suggestion
  const isInvalidDate = useMemo(() => {...}, [currentStudy.start_date, currentStudy.end_date]);
```

Also, I think it would be nice to have 3 const (use useMemo for the 3):
- isExpectedEndDateValid
- isActualEndDateValid
- areEndDatesValid = isExpectedEndDateValid && isActualEndDateValid

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 3 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: Fixed ! Ty for the suggestions :)

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 4]
```diff
@@ -397,6 +420,7 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
               className="btn btn-warning"
               type="button"
               onClick={updateStudy}
+              disabled={!areEndDatesValid}
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Should there be a message for the user in case he doesn't understand why he can't validate the form ?

Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: after a discussion with the ux designer, we've made it impossible to select incorrect dates, so there's no need for messages or to disable the button

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 5]
```diff
@@ -155,6 +156,18 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
...
+    actual_end_date: string | number | undefined
+  ) {
+    if (expected_end_date && actual_end_date) {
+      return expected_end_date < actual_end_date ? expected_end_date : actual_end_date;
+    }
+    if (expected_end_date) {
+      return expected_end_date;
+    }
+    return actual_end_date;
+  }
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: You could simplify the function like that. 
```suggestion
 function getEarliestDate(date1: string | null | undefined, date2: string | null | undefined) {
    const formatedDate1 = formatDateForInput(date1);
    const formatedDate2 = formatDateForInput(date2);
    if (formatedDate1 && formatedDate2) {
      return formatedDate1 < formatedDate2 ? formatedDate1 : formatedDate2;
    }
    return formatedDate1 || formatedDate2;
  }
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Tested in local, left a suggestion to simplify the code.

According the front guidelines, you could also move this function, the `formatDateForInput` and `createSelectOptions` in a utils file in the study folder.

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 6]
```diff
@@ -26,6 +26,7 @@ import {
   studyTypes,
 } from 'applications/operationalStudies/consts';
 import { isEmpty, sortBy } from 'lodash';
+import { Number } from '../../../stories/IntervalsEditor.stories';
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: warning here

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 5 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: Ty it's prettier ! Fixed

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 6 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: fixed ;)

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 7]
```diff
@@ -381,6 +373,7 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
               className="btn btn-outline-danger mr-auto"
               type="button"
               onClick={deleteStudy}
+              disabled={isDateValid}
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Why should we need to disable the delete button ?

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 8]
```diff
@@ -155,6 +133,15 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
...
 
+  const isDateValid = useMemo(() => {
+    const startDate = currentStudy?.start_date;
+    const earliestDate = getEarliestDate(
+      currentStudy?.expected_end_date,
+      currentStudy?.actual_end_date
+    );
+    return !!(startDate && startDate > earliestDate);
+  }, [currentStudy?.start_date, currentStudy?.expected_end_date, currentStudy?.actual_end_date]);
+
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Should this const be invalid also if end date is earlier than start date ?

**Review by SharglutDev — CHANGES_REQUESTED** [review]
image

Here both dates are underlined in red but only one is invalid.
I think it should be only the date responsible for the invalidity that gets the red underline

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: Fixed, ty for the review :)

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 8 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: The back only handle the case where we enter a start date and no expected/actual end date.

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 9]
```diff
@@ -409,6 +408,7 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
               className="btn btn-primary"
               type="button"
               onClick={createStudy}
+              disabled={isStartDateValid || !isExpectedEndDateValid || !isActualEndDateValid}
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Missed the "!" here. Form is never valid for now :)
```suggestion
              disabled={!isStartDateValid || !isExpectedEndDateValid || !isActualEndDateValid}
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 9 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: fixed !

**Review by SharglutDev — APPROVED** [review]
Lgtm, great job :)

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
