### PR TITLE
front: ui: fix std vertical padding

### LINKED ISSUE #13619: STD : Graduations at the top of the STD don't match the model
### What happened?

The graduations at the top of the STD extend over the rest of the STD instead of being above it as on the model

Currently : 

Image

Model : 

Image

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario and create a train
2. Check the STD

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

be76a49

### PR DESCRIPTION
**Pull request by Akctarus**
closes #13619 

Should be good now, we have enough padding on top and bottom to : display well the path train + its name, and to display the time cursor on bottom 
Capture d’écran 2025-10-29 à 14 32 12

### CODE REVIEW

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx [hunk 1]
```diff
@@ -161,10 +161,10 @@ const useManchetteWithSpaceTimeChart = ({
...
     setState((prev) => ({ ...prev, timeOrigin: newTimeOrigin }));
   }, []);
-
-  const canvasDrawingHeight = Math.max(1 + BASE_WAYPOINT_HEIGHT, height - FOOTER_HEIGHT); // 521
-  const drawingHeightWithoutTopPadding = canvasDrawingHeight - BASE_WAYPOINT_HEIGHT / 2; // 505
-  const drawingHeightWithoutBothPadding = canvasDrawingHeight - BASE_WAYPOINT_HEIGHT; // 489
+  const canvasDrawingHeight = Math.max(1 + BASE_WAYPOINT_HEIGHT, height - FOOTER_HEIGHT);
+  const drawingHeightWithoutTopPadding = canvasDrawingHeight - verticalPadding;
+  const drawingHeightWithoutBothPadding =
+    canvasDrawingHeight - (verticalPadding + BASE_WAYPOINT_HEIGHT);
```
Comment (theocrsb) [inline front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: Maybe we can leave the values commented out

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx [hunk 2]
```diff
@@ -103,7 +103,7 @@ const useManchetteWithSpaceTimeChart = ({
   defaultTimeOrigin = 0,
   defaultSpaceOrigin = 0,
   defaultXOffset = 0,
-  verticalPadding = BASE_WAYPOINT_HEIGHT / 2,
+  verticalPadding = BASE_WAYPOINT_HEIGHT + BASE_WAYPOINT_HEIGHT / 2,
```
Comment (theocrsb) [inline front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: Why do we have to enter the same value twice here?

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx [hunk 3]
```diff
@@ -537,7 +537,7 @@ const useManchetteWithSpaceTimeChart = ({
                 //   the top) are aligned with SpaceTimeChart's space lines
                 // - Split points are positioned so that their top is aligned with SpaceTimeChart's
                 //   space lines
```
Comment (kmer2016) [inline front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx:539]: I think the comment must be updated

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx (hunk 2 above)
Comment (kmer2016) [reply front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: Nit: Consider simplifying to `verticalPadding = BASE_WAYPOINT_HEIGHT * 1.5`, to avoid repeating the variable name.

Comment (Akctarus) [reply front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: done

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx (hunk 1 above)
Comment (Akctarus) [reply front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: fixed

**Review by kmer2016 — APPROVED** [review]
LGTM
