### PR TITLE
front: fix deleted trainrun

### LINKED ISSUE #8688: NGE: deleting a trainrun doesn't delete the corresponding trainSchedule
### What happened?

When you delete a train in nge tab, you get a console error and the corresponding train schedule is not deleted.

Screenshot from 2024-09-02 12-03-24

### What did you expect to happen?

No error in the console and the corresponding train schedule is deleted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Macroscopic tab with trainrun
2. Deleted a trainrun
3. Go tu Microscopic tab, the corresponding train schedule is always present

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

local

### PR DESCRIPTION
**Pull request by Uriel-Sautron**
When deleting trainrun skips getTrainrunSectionsByTrainrunId function, as this function searches for sections according to trainrun id.
When deleting a trainrun, no sections are found which returns an error and cancels the deletion.

close #8688

### CODE REVIEW

**Review by emersion — APPROVED** [review]
LGTM

(I wouldn't mind duplicating the `getTrainrunSectionsByTrainrunId()` call in both cases FWIW, or even moving that call into `createTrainSchedulePayload()`)

**Comment by Uriel-Sautron** [comment]
> LGTM
> 
> (I wouldn't mind duplicating the getTrainrunSectionsByTrainrunId() call in both cases FWIW, or even moving that call into createTrainSchedulePayload())

I've also considered doing it.

File: front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts [hunk 1]
```diff
@@ -147,16 +147,20 @@ const handleTrainrunOperation = async ({
...
+        trainrun.id
+      );
       const newTrainSchedules = await dispatch(
         osrdEditoastApi.endpoints.postV2TimetableByIdTrainSchedule.initiate({
           id: timeTableId,
           body: [
             {
               ...DEFAULT_PAYLOAD,
-              ...createTrainSchedulePayload(trainrunSectionsByTrainrunId, nodes, trainrun),
+              ...createTrainSchedulePayload(trainrunSectionsByTrainrunId!, nodes, trainrun),
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts]: Do we really need non-null assertion here ?

File: front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts [hunk 2]
```diff
@@ -188,7 +196,7 @@ const handleTrainrunOperation = async ({
           id: trainrunIdToUpdate,
           trainScheduleForm: {
             ...trainSchedule,
-            ...createTrainSchedulePayload(trainrunSectionsByTrainrunId, nodes, trainrun),
+            ...createTrainSchedulePayload(trainrunSectionsByTrainrunId!, nodes, trainrun),
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts]: same here ?

File: front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts (hunk 1 above)
Comment (Uriel-Sautron) [reply front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts]: Oups done, thanks

File: front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts (hunk 2 above)
Comment (Uriel-Sautron) [reply front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts]: Done

**Review by kmer2016 — APPROVED** [review]
LGTM and tested

**Review by louisgreiner — APPROVED** [review]
Working fine, thanks :)
