### PR TITLE
front:timestops: fix operational point removal

### LINKED ISSUE #8079: Margin/stop time remains after deleting waypoint
### What happened?

When deleting a waypoint, margins and stop times remain in the table. This is just a UI bug: they are properly removed when saving the edited train.

out

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Edit a train
2. Go to "Times and stops"
3. Add a 5% margin for a waypoint
4. Save
5. Edit train again
6. Click the red cross to delete the waypoint

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

e725429b688bf44edb8c7c8001b212c16903716d

### PR DESCRIPTION
**Pull request by SharglutDev**
When an operational point in the timestops table was removed from via, it was removed from the store but not updated in the op list

close #8079

### CODE REVIEW

File: front/src/modules/timesStops/utils.ts [hunk 1]
```diff
@@ -28,7 +28,13 @@ export const formatSuggestedViasToRowVias = (
...
   return formattedOps.map((op, i) => {
     const pathStep = pathSteps.find((step) => matchPathStepAndOp(step, op));
-    const { arrival, onStopSignal, name, stopFor, theoreticalMargin } = pathStep || op;
+    const { arrival, onStopSignal, name, stopFor, theoreticalMargin } = pathStep || {
+      ...op,
+      stopFor: undefined,
+      arrival: undefined,
+      onStopSignal: false,
+      theoreticalMargin: undefined,
+    };
```
Comment (emersion) [inline front/src/modules/timesStops/utils.ts]: Ah! If we don't want to grab some props from `op` then maybe we can split into two assignments?

```js
const { name } = pathStep || op;
const { arrival, onStopSignal, stopFor, theoreticalMargin } = pathStep || {};
```

**Review by theocrsb — APPROVED** [review]
LGTM and tested !

**Review by achrafmohye — APPROVED** [review]
LGTM :)

File: front/src/modules/timesStops/utils.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/utils.ts]: Done

**Review by kmer2016 — APPROVED** [review]
LGTM !
