### PR TITLE
front: change margin logic

### LINKED ISSUE #7950: TSV2 : incorrect standard margin distribution in case of specified passing point
### What happened?

When we put a value of standard margin in the input table, the correspondent margin with this value is inserted till the following passing point 

### What did you expect to happen?

When we put a value of standard margin in the input table, the correspondent margin with this value should be inserted till the following point where a new value of standard margin is specified  

### How can we reproduce it (as minimally and precisely as possible)?

Go to a scenario TSV2
Chose the rolling stock and a path with a passing point 
Put 5% value of standard margin
Look the margin distribution in to the speed space graph

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging 4698a66

### PR DESCRIPTION
**Pull request by theocrsb**
close #7950

### CODE REVIEW

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 1]
```diff
@@ -1,20 +1,44 @@
...
+    // for the last step, if the origin has a margin and there isn't any via with one,
+    // we add 'none' add the end of the values because we need N+1 values compared to boundaries
+    else if (index === pathSteps.length - 1 && pathSteps[0].theoreticalMargin && !viaWithMargin) {
+      margins.boundaries.push(step.id);
+      margins.values.push('none');
     }
   });
+
+  // check if all margins are 'none'
+  if (!margins.values.some((value) => value !== 'none')) {
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: A bit easier without the 2 negations

```suggestion
  if (margins.values.every((value) => value === 'none')) {
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 2]
```diff
@@ -1,20 +1,44 @@
...
+    ) {
+      viaWithMargin = true;
       margins.boundaries.push(step.id);
-      margins.values.push(step.theoreticalMargin || 'none');
+      margins.values.push(step.theoreticalMargin);
+    }
+
+    // for the last step, if the origin has a margin and there isn't any via with one,
+    // we add 'none' add the end of the values because we need N+1 values compared to boundaries
+    else if (index === pathSteps.length - 1 && pathSteps[0].theoreticalMargin && !viaWithMargin) {
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: you probably don’t need `viaWithMargin`, you never enter this `else if` if you went in the first `else if`

**Review by anisometropie — CHANGES_REQUESTED** [review]

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 2 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Yes, that works too. Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 1 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

**Review by Uriel-Sautron — APPROVED** [review]
Tested nice !! Thank you

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 3]
```diff
@@ -1,20 +1,40 @@
 import type { Margin } from 'modules/trainschedule/components/ManageTrainSchedule/types';
 import type { PathStep } from 'reducers/osrdconf/types';
 
-const formatMargin = (pathSteps: PathStep[]): Margin => {
+const formatMargin = (pathSteps: PathStep[]): Margin | undefined => {
   const margins: Margin = {
     boundaries: [],
     values: [],
   };
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: You can do this, I think it's more elegant :)
```suggestion
  const boundaries: string[] = [];
  const values: string[] = [];
```
Then you just have to update `boundaries` or `values`, and not `margins.boundaries` or `margins.values`

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 4]
```diff
@@ -1,20 +1,40 @@
...
-      margins.values.push(step.theoreticalMargin || 'none');
+      margins.values.push(step.theoreticalMargin);
+    }
+
+    // for the last step, if the origin has a margin and there isn't any via with one,
+    // we add 'none' add the end of the values because we need N+1 values compared to boundaries
+    else if (index === pathSteps.length - 1 && pathSteps[0].theoreticalMargin) {
+      margins.boundaries.push(step.id);
+      margins.values.push('none');
     }
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Move the case of last element just below the case `index === 0`, and instead of testing that the first pathSteps has a theoreticalMargin, you can check that `value` has only 1 element and that it is not 'none'
```suggestion
   else if (index === pathSteps.length - 1) {
      if (values.length === 1 && values[0] !== 'none') {
        boundaries.push(step.id);
        values.push('none');
      }
    }
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 5]
```diff
@@ -1,20 +1,40 @@
...
       margins.values.push(step.theoreticalMargin || 'none');
-    } else if (step.theoreticalMargin !== pathSteps[index - 1].theoreticalMargin) {
+    }
+
+    // for the other steps, we add the margin if it's different from the previous one
+    else if (
+      step.theoreticalMargin &&
+      step.theoreticalMargin !== pathSteps[index - 1].theoreticalMargin &&
+      index !== pathSteps.length - 1
+    ) {
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: - since you moved the case of the last element above, you can remove the test `index !== pathSteps.length - 1`
- you should compare `step.theoreticalMagin` with the last value, and not the theoreticalMargin of the last pathStep (it could be undefined)
```suggestion
     else if (step.theoreticalMargin && step.theoreticalMargin !== values[values.length - 1]) {
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 6]
```diff
@@ -1,20 +1,40 @@
...
+    // for the last step, if the origin has a margin and there isn't any via with one,
+    // we add 'none' add the end of the values because we need N+1 values compared to boundaries
+    else if (index === pathSteps.length - 1 && pathSteps[0].theoreticalMargin) {
+      margins.boundaries.push(step.id);
+      margins.values.push('none');
     }
   });
+
+  // check if all margins are 'none'
+  if (margins.values.every((value) => value === 'none')) {
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: You can simply check if the `values.length !== 1`
```suggestion
  if (values.length === 1) {
```

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: It's easier to read but I think the point was not to have to iterate in the whole array to check this condition (as soon as we see a not "none" value, we can stop the loop)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 3 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 4 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 5 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 6 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

**Review by clarani — APPROVED** [review]
LGTM, approved :white_check_mark:

**Review by anisometropie — APPROVED** [review]
