### PR TITLE
front: fix-bug: remove updateSwitch request if infraID is undefined

### LINKED ISSUE #3106: Front: 404 on launching app, something looks for infra in redux store
image

Front: 404 on launching app, something looks for infra in redux store

To reproduce: refresh the page with the console opened
Bug still present on 16/02 (3dbd56326a0bf67d9b2902f1017295ec17c19250)

### PR DESCRIPTION
**Pull request by clarani**
Fixes #3106

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Nice !

File: front/src/reducers/osrdconf/index.ts [hunk 1]
```diff
@@ -320,11 +320,13 @@ export function updateInfraID(infraID: any) {
...
-      const newSwitchTypes = await getSwitchTypes(infraID);
-      dispatch(updateSwitchTypes(newSwitchTypes));
-    } catch (e) {
-      console.log('error on switch type retrieval', e);
+    if (infraID) {
+      try {
+        const newSwitchTypes = await getSwitchTypes(infraID);
+        dispatch(updateSwitchTypes(newSwitchTypes));
+      } catch (e) {
+        /* empty */
```
Comment (bloussou) [inline front/src/reducers/osrdconf/index.ts:328]: not sure to get why we have to swallow the error here, shouldn't the log still be there or just the error be thrown if it fails ?

Comment (clarani) [reply front/src/reducers/osrdconf/index.ts:328]: Actually, I think we should change our error catching system: the error is already catch in getSwitchType() and printed in the console automatically (because if there is an error, it's a network error, the request has failed), but in the catch of getSwitchType, we throw a new error again, which is the reason why we need a new try/catch loop here.

I think we should remove the second error, but as we are going to change our call to the api  system soon (RTK), it may be not relevant to make this change now...

Comment (bloussou) [reply front/src/reducers/osrdconf/index.ts:328]: okk, lets go for this then :smile:

**Review by Math-R — APPROVED** [review]
