### PR TITLE
front: fix macro trainruns frequencies

### LINKED ISSUE #10389: nge: frequency feature is broken
### What happened?

Image

It seems we've lost the frequency feature : only 60' is remaining, and even if we set freq from OSRD it is not working

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. try change freq in NGE

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### LINKED ISSUE #10552: nge: stop_for calculation is inverted
### What happened?

When a stop is set, here from minute 26 to 28:

Image

The `stop_for` value is wrong for the first intermediary node (the second being null is fine):

Image

### What did you expect to happen?

28-26=2, not -2

### How can we reproduce it (as minimally and precisely as possible)?

1. create train schedule and set arrival and departure time from a waypoint

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by louisgreiner**
After https://github.com/OpenRailAssociation/osrd/pull/9105, we've lost the feature the [macro trainrun frequencies](https://github.com/OpenRailAssociation/osrd/pull/8917)

This way of handling macro train frequencies will be revamp during https://github.com/osrd-project/osrd-confidential/issues/779

Closes https://github.com/OpenRailAssociation/osrd/issues/10389
Closes https://github.com/OpenRailAssociation/osrd/issues/10552

### CODE REVIEW

**Comment by louisgreiner** [comment]
Depends on https://github.com/OpenRailAssociation/osrd/pull/10486

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 1]
```diff
@@ -303,16 +303,39 @@ export const loadAndIndexNge = async (
...
+      if (trainSchedule.labels) {
+        trainSchedule.labels.forEach((label) => {
+          if (!label.match(/^frequency::(?!30$|60$|120$)\d+$/)) {
+            const frequency = parseInt(label.split('::')[1], 10);
+            const trainrunFrequencyFound = DEFAULT_TRAINRUN_FREQUENCIES.find(
+              (freq) => freq.frequency === frequency
+            );
+            if (
+              trainrunFrequencyFound &&
+              (!trainrunFrequency || trainrunFrequencyFound.frequency < trainrunFrequency.frequency)
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: Probably a lack of nge knowledge but what is the reason to keep the last lower frequency (and not any frequency) ?

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 2]
```diff
@@ -303,16 +303,39 @@ export const loadAndIndexNge = async (
...
-      labelIds: (trainSchedule.labels || []).map((l) =>
-        labels.findIndex((e) => e.label === l && e.labelGroupId === TRAINRUN_LABEL_GROUP.id)
-      ),
-    }));
+    .map((trainSchedule) => {
+      // NGE trainrun frequency is stored as OSRD labels ('frequency::30' or 'frequency::120')
+      let trainrunFrequency: TrainrunFrequency | undefined;
+      if (trainSchedule.labels) {
+        trainSchedule.labels.forEach((label) => {
+          if (!label.match(/^frequency::(?!30$|60$|120$)\d+$/)) {
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: nit : since it is used two times, we could maybe extract `/^frequency::(?!30$|60$|120$)\d+$/` in a `const`.

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 3]
```diff
@@ -303,16 +303,39 @@ export const loadAndIndexNge = async (
...
+        });
+      }
+
+      return {
+        id: trainSchedule.id,
+        name: trainSchedule.train_name,
+        categoryId: DEFAULT_TRAINRUN_CATEGORY.id,
+        frequencyId: trainrunFrequency?.id || DEFAULT_TRAINRUN_FREQUENCY.id,
+        trainrunTimeCategoryId: DEFAULT_TRAINRUN_TIME_CATEGORY.id,
+        labelIds: (trainSchedule.labels || [])
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: Maybe it could help to know why we want to store other frequencies than 30/60/120 (and why we don't want to keep the other regular labels)

**Review by SharglutDev — COMMENTED** [review]
Works great just some questions :)

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts (hunk 1 above)
Comment (louisgreiner) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: As a trainrun can have only 1 frequency, we intend to keep the most restrictive one

**Comment by emersion** [comment]
It seems like this feature got lost in https://github.com/OpenRailAssociation/osrd/pull/9105.

I think this PR still creates `frequency::` labels in NGE (without using them in any trainrun)?

**Comment by louisgreiner** [comment]
`frequency::` labels should be shared in NGE if they are not either `frequency::30`, or `frequency::60` or `frequency::120`.

The former feature allowed, for instance, `frequency::10` to be shared in NGE, even tho we don't match this frequency with an actual NGE frequency

@emersion

**Comment by emersion** [comment]
Yeah, what I meant was that I think `frequency::30` and friends show up as a regular label in NGE with this PR.

**Comment by emersion** [comment]
I'm not a huge fan of the RegExp-based label parsing. (BTW, it's also used in `ngeToOsrd`.)

Maybe this can all be consolidated in a single function, used everywhere instead of the RegExp and string checks?

```ts
const frequencyIdFromLabel = (label: string) => {
  if (!label.startsWith('frequency::')) return null;
  const n = parseInt(label.split('::', 2)[1], 10);
  const frequency = DEFAULT_TRAINRUN_FREQUENCIES.find((freq) => freq.frequency === n);
  return frequency?.id ?? null;
};
```

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts (hunk 2 above)
Comment (emersion) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: This `if` matches labels such as `asdf::60`.

Comment (louisgreiner) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: this regex and the use of it was not great indeed, it has been changed

Comment (louisgreiner) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: I decided not to (miss-)use this regex anymore

**Comment by louisgreiner** [comment]
Because I found this bug on the way, i'm also fixing it in a separate commit : https://github.com/OpenRailAssociation/osrd/issues/10552

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job :)

**Review by Uriel-Sautron — APPROVED** [review]
LGTM, tested.

**Review by Uriel-Sautron — APPROVED** [review]
LGTM, tested.
