### PR TITLE
front/editor-form: fix undefined values in formdata

### LINKED ISSUE #5480: front: editor: no next_signaling_systems when adding a logical system
### What happened?

When editing a signal, if I add a logical system and save, I encounter the error : `{"status":400,"data":{"status":400,"type":"editoast:JsonError","context":{"cause":"Json deserialize error: missing field "next_signaling_systems" at line 1 column 583"},"message":"Json deserialize error: missing field "next_signaling_systems" at line 1 column 583"}}`

image

### What did you expect to happen?

No error, I should be able to save my signal

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. Select an infra and display the signals layer
3. Click on the switch button to create a new switch
4. Complete all the required fields
5. Click on add a logical system
  image
6. click on save 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

74fc2523

### LINKED ISSUE #5487: front: editor: can not save a created signal once it has been saved
### What happened?

I created a signal, and directly after that edited it and tried to save. I encounter this error: `{"status":404,"data":{"status":404,"type":"editoast:operation:ObjectNotFound","context":{"obj_id":"osrd/editor/new-signal-id","infra_id":1},"message":"Object 'osrd/editor/new-signal-id', could not be found in the infrastructure '1'"}}`

image

I think it happens because the id of the object has changed (it is not the new-signal-id anymore, we should get the new id from the object returned by the backend)

### What did you expect to happen?

I should be able to edit it

### How can we reproduce it (as minimally and precisely as possible)?

1. Open the editor and select an infra
2. Display the signals layer
3. Click on the signal tool
4. Create a signal: edit it and click on save
5. Once you see the success notification, edit a field and try to save again

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

74fc2523

### LINKED ISSUE #5556: front: infra-editor: cannot create a signal
### What happened?

When trying to create a new signal, the request fails with 400: 
```
{"status":400,"data":{"status":400,"type":"editoast:JsonError","context":{"cause":"Json deserialize error: unknown field `is_in_service`, expected one of `label`, `side`, `kp` at line 1 column 487"},"message":"Json deserialize error: unknown field `is_in_service`, expected one of `label`, `side`, `kp` at line 1 column 487"}}
```

### What did you expect to happen?

We should be able to create a new signal

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor, select an infra
2. Display the signals, try to create a new one

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

b6936d6f

### PR DESCRIPTION
**Pull request by SarahBellaha**
closes #5480
closes #5487 
closes #5556

### CODE REVIEW

File: front/src/applications/editor/tools/pointEdition/utils.ts [hunk 1]
```diff
@@ -1,4 +1,10 @@
-import { BufferStopEntity, DetectorEntity, NULL_GEOMETRY, SignalEntity } from '../../../../types';
+import {
+  BufferStopEntity,
+  DetectorEntity,
+  NULL_GEOMETRY,
+  SignalEntity,
+  SignalingSystem,
+} from '../../../../types';
```
Comment (alexandredamiron) [inline front/src/applications/editor/tools/pointEdition/utils.ts]: please use absolute paths

File: front/src/applications/editor/tools/pointEdition/components.tsx [hunk 2]
```diff
@@ -328,7 +308,20 @@ export const PointEditionLeftPanel: FC<{ type: EditoastType }> = <Entity extends
             additionalUpdate.geometry = point.geometry;
           }
 
-          setState({ ...state, entity: { ...(entity as Entity), ...additionalUpdate } });
+          if (entity.objType === 'Signal' && entity.properties.logical_signals) {
+            additionalPropertiesUpdate.logical_signals = formatSignalingSystems(
+              entity as unknown as SignalEntity
+            );
+          }
+
```
Comment (alexandredamiron) [inline front/src/applications/editor/tools/pointEdition/components.tsx:319]: entity cannot be typed as EditorEntity ?

**Review by alexandredamiron — CHANGES_REQUESTED** [review]

File: front/src/applications/editor/tools/pointEdition/components.tsx (hunk 2 above)
Comment (clarani) [reply front/src/applications/editor/tools/pointEdition/components.tsx:319]: No because we know we have a signal, and we need to give a SignalEntity to the function `formatSignalingSystems`

**Review by clarani — APPROVED** [review]
LGTM, tested in local :white_check_mark:

**Review by alexandredamiron — APPROVED** [review]
