### PR TITLE
editoast: fix bug on editoast (dupplicate key during update or create)

### LINKED ISSUE #2073: editoast: updating a track section
##  Describe the bug

When updating a track section, the editoast API crashed (error 500), even when we I sent a body with no changes.
For creation and deletion, there is no issue.

### HTTP Call : 

```
curl 'http://localhost:8090/infra/2' \
  --data-raw '[{"operation_type":"UPDATE","obj_id":"605472cc-6667-11e3-81ff-01f464e0362d","obj_type":"TrackSection","railjson_patch":[]}]' \
 ```

### Log result : 

```
POST /infra/2 application/json:
osrd-editoast        |     => Matched: POST /infra/<infra> (edit)
osrd-chartos         | INFO:     127.0.0.1:56248 - "POST /layer/track_sections/invalidate_bbox/?infra=2 HTTP/1.1" 204 No Content
osrd-chartos         | INFO:     127.0.0.1:56260 - "POST /layer/signals/invalidate_bbox/?infra=2 HTTP/1.1" 204 No Content
osrd-postgres        | 2022-10-11 12:01:07.338 UTC [339] ERROR:  duplicate key value violates unique constraint "osrd_infra_speedsectionlayer_infra_id_obj_id_41f9ec33_uniq"
osrd-postgres        | 2022-10-11 12:01:07.338 UTC [339] DETAIL:  Key (infra_id, obj_id)=(2, a38750e0-256e-11e9-96ff-0110b2273146) already exists.
osrd-postgres        | 2022-10-11 12:01:07.338 UTC [339] STATEMENT:  WITH track_ranges AS (
osrd-postgres        |      SELECT obj_id AS speed_id,
osrd-postgres        |          (
osrd-postgres        |              jsonb_array_elements(data->'track_ranges')->'begin'
osrd-postgres        |          )::float AS slice_begin,
osrd-postgres        |          (
osrd-postgres        |              jsonb_array_elements(data->'track_ranges')->'end'
osrd-postgres        |          )::float AS slice_end,
osrd-postgres        |          jsonb_array_elements(data->'track_ranges')->>'track' AS track_id
osrd-postgres        |      FROM osrd_infra_speedsectionmodel
osrd-postgres        |      WHERE infra_id = $1
osrd-postgres        |          AND obj_id = ANY($2)
osrd-postgres        |  ),
osrd-postgres        |  sliced_tracks AS (
osrd-postgres        |      SELECT track_ranges.speed_id,
osrd-postgres        |          ST_Transform(
osrd-postgres        |              ST_LineSubstring(
osrd-postgres        |                  ST_GeomFromGeoJSON(tracks.data->'geo'),
osrd-postgres        |                  GREATEST(
osrd-postgres        |                      LEAST(
osrd-postgres        |                          track_ranges.slice_end / (tracks.data->'length')::float,
osrd-postgres        |                          track_ranges.slice_begin / (tracks.data->'length')::float,
osrd-postgres        |                          1.
osrd-postgres        |                      ),
osrd-postgres        |                      0.
osrd-postgres        |                  ),
osrd-postgres        |                  LEAST(
osrd-postgres        |                      GREATEST(
osrd-postgres        |                          track_ranges.slice_begin / (tracks.data->'length')::float,
osrd-postgres        |                          track_ranges.slice_end / (tracks.data->'length')::float,
osrd-postgres        |                          0.
osrd-postgres        |                      ),
osrd-postgres        |                      1.
osrd-postgres        |                  )
osrd-postgres        |              ),
osrd-postgres        |              3857
osrd-postgres        |          ) AS geo,
osrd-postgres        |          ST_Transform(
osrd-postgres        |              ST_LineSubstring(
osrd-postgres        |                  ST_GeomFromGeoJSON(tracks.data->'sch'),
osrd-postgres        |                  GREATEST(
osrd-postgres        |                      LEAST(
osrd-postgres        |                          track_ranges.slice_end / (tracks.data->'length')::float,
osrd-postgres        |                          track_ranges.slice_begin / (tracks.data->'length')::float,
osrd-postgres        |                          1.
osrd-postgres        |                      ),
osrd-postgres        |                      0.
osrd-postgres        |                  ),
osrd-postgres        |                  LEAST(
osrd-postgres        |                      GREATEST(
osrd-postgres        |                          track_ranges.slice_begin / (tracks.data->'length')::float,
osrd-postgres        |                          track_ranges.slice_end / (tracks.data->'length')::float,
osrd-postgres        |                          0.
osrd-postgres        |                      ),
osrd-postgres        |                      1.
osrd-postgres        |                  )
osrd-postgres        |              ),
osrd-postgres        |              3857
osrd-postgres        |          ) AS sch
osrd-postgres        |      FROM track_ranges
osrd-postgres        |          INNER JOIN osrd_infra_tracksectionmodel AS tracks ON tracks.obj_id = track_ranges.track_id
osrd-postgres        |          AND tracks.infra_id = $1
osrd-postgres        |  )
osrd-postgres        |  INSERT INTO osrd_infra_speedsectionlayer (obj_id, infra_id, geographic, schematic)
osrd-postgres        |  SELECT speed_id,
osrd-postgres        |      $1,
osrd-postgres        |      St_Collect(geo),
osrd-postgres        |      St_Collect(sch)
osrd-postgres        |  FROM sliced_tracks
osrd-postgres        |  WHERE GeometryType(sliced_tracks.geo) = 'LINESTRING'
osrd-postgres        |      AND GeometryType(sliced_tracks.sch) = 'LINESTRING'
osrd-postgres        |  GROUP BY speed_id
osrd-editoast        | thread '<unnamed>' panicked at 'Update generated data failed: DieselError(DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"osrd_infra_speedsectionlayer_infra_id_obj_id_41f9ec33_uniq\""))', src/views/infra.rs:162:14
osrd-core            | [12:01:08,974] [INFO]                [TkSlf4j] [GET http://localhost:8080/health] returned "HTTP/1.1 200 OK" in 1 ms
osrd-editoast        | GET /health:
osrd-editoast        |     => Matched: GET /health (health)
osrd-api             | [11/Oct/2022 12:01:09] "GET /health/ HTTP/1.1" 200 0
osrd-postgres        | 2022-10-11 12:01:09.305 UTC [339] ERROR:  current transaction is aborted, commands ignored until end of transaction block
osrd-postgres        | 2022-10-11 12:01:09.305 UTC [339] STATEMENT:  SELECT 1
osrd-editoast        | Error: current transaction is aborted, commands ignored until end of transaction block
osrd-editoast        |     => Outcome: Success
osrd-editoast        |     => Response succeeded.
```

### PR DESCRIPTION
**Pull request by Tguisnet**
close #2073

### CODE REVIEW

File: editoast/src/layer/mod.rs [hunk 1]
```diff
@@ -43,7 +43,17 @@ pub trait Layer {
...
 
     /// Insert or update some objects of the layer object
-    fn insert_update_list(
+    fn update_list(
+        conn: &PgConnection,
+        infra: i32,
+        obj_ids: HashSet<&String>,
+    ) -> Result<(), Error> {
+        Self::insert_list(conn, infra, obj_ids)?;
+        Ok(())
```
Comment (flomonster) [inline editoast/src/layer/mod.rs]:
```suggestion
        Self::insert_list(conn, infra, obj_ids)
```

File: editoast/src/schema/catenary.rs [hunk 2]
```diff
@@ -49,6 +53,17 @@ impl Layer for Catenary {
...
+
+    /// Delete and Insert for update some objects of the layer object
+    fn update_list(
+        conn: &PgConnection,
+        infra: i32,
+        obj_ids: HashSet<&String>,
+    ) -> Result<(), Error> {
+        Self::delete_list(conn, infra, obj_ids.clone())?;
+        Self::insert_list(conn, infra, obj_ids)?;
+        Ok(())
```
Comment (flomonster) [inline editoast/src/schema/catenary.rs]: same

File: editoast/src/schema/operational_point.rs [hunk 3]
```diff
@@ -81,6 +85,17 @@ impl Layer for OperationalPoint {
...
+
+    /// Delete and Insert for update some objects of the layer object
+    fn update_list(
+        conn: &PgConnection,
+        infra: i32,
+        obj_ids: HashSet<&String>,
+    ) -> Result<(), Error> {
+        Self::delete_list(conn, infra, obj_ids.clone())?;
+        Self::insert_list(conn, infra, obj_ids)?;
+        Ok(())
```
Comment (flomonster) [inline editoast/src/schema/operational_point.rs]: same

File: editoast/src/schema/route.rs [hunk 4]
```diff
@@ -51,6 +55,17 @@ impl Layer for Route {
...
+
+    /// Delete and Insert for update some objects of the layer object
+    fn update_list(
+        conn: &PgConnection,
+        infra: i32,
+        obj_ids: HashSet<&String>,
+    ) -> Result<(), Error> {
+        Self::delete_list(conn, infra, obj_ids.clone())?;
+        Self::insert_list(conn, infra, obj_ids)?;
+        Ok(())
```
Comment (flomonster) [inline editoast/src/schema/route.rs]: same

File: editoast/src/schema/speed_section.rs [hunk 5]
```diff
@@ -52,6 +55,17 @@ impl Layer for SpeedSection {
...
+
+    /// Delete and Insert for update some objects of the layer object
+    fn update_list(
+        conn: &PgConnection,
+        infra: i32,
+        obj_ids: HashSet<&String>,
+    ) -> Result<(), Error> {
+        Self::delete_list(conn, infra, obj_ids.clone())?;
+        Self::insert_list(conn, infra, obj_ids)?;
+        Ok(())
```
Comment (flomonster) [inline editoast/src/schema/speed_section.rs]: same

**Review by flomonster — CHANGES_REQUESTED** [review]

**Review by flomonster — APPROVED** [review]
