### PR TITLE
editoast: the `SimulationEnv` should not fail on missing path items

### LINKED ISSUE #16348: Simulation summary crashes for invalid trains
### What happened?

Something is wrong with the new task `SimulationTrain`. Invalid trains (tains that have not found path steps), crashes the simulation.

```
thread 'tokio-rt-worker' (80) panicked at src/views/timetable/simulation.rs:645:10:
the path item cache should be built out from all the input path items of the train occurrence: PathfindingInputError(InvalidPathItems { items: [InvalidPathItem { index: 0, path_item: OperationalPointPartReference(OperationalPointPartReference { operational_point: Trigram { trigram: NonBlankString("WS"), secondary_code: Some("BV") }, local_track_name: None }) }, InvalidPathItem { index: 1, path_item: TrackOffset(TrackOffset { track: Identifier("TA6"), offset: 4272270 }) }, InvalidPathItem { index: 2, path_item: OperationalPointPartReference(OperationalPointPartReference { operational_point: Trigram { trigram: NonBlankString("MWS"), secondary_code: Some("BV") }, local_track_name: None }) }, InvalidPathItem { index: 3, path_item: OperationalPointPartReference(OperationalPointPartReference { operational_point: Trigram { trigram: NonBlankString("MES"), secondary_code: Some("BV") }, local_track_name: None }) }] })
```

This expect fails: https://github.com/OpenRailAssociation/osrd/blob/28980e43cdd178bf8c57bf86e53a2f0a10a508fc/editoast/src/views/timetable/simulation.rs#L643-L645

### What did you expect to happen?

Trains that have invalid path steps should be marked as "SimulationFailed" like before.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with an empty infra
2. Import this train: [timetable_test_tableau.json](https://github.com/user-attachments/files/26890845/timetable_test_tableau.json)
3. Check call to `simulation_summary`

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

28980e4

### PR DESCRIPTION
**Pull request by woshilapin**
Previous version of the code was returning a pathfinding failure when using non-existing path items in the query (for example, an operational point not present on the infrastructure). With the integration of `SimulationEnv`, a non-existing path item crashes the entire endpoint. The current fix brings back the previous smoother behavior.

Fixes #16348.

### CODE REVIEW

File: editoast/src/views/timetable/simulation.rs
Comment (hamz2a) [inline editoast/src/views/timetable/simulation.rs]: this comment is outdated, we should remove it.

**Review by hamz2a — APPROVED** [review]
LGTM, thanks!

File: editoast/src/views/timetable/simulation.rs [hunk 1]
```diff
@@ -640,9 +650,8 @@ pub fn build_simulation_train(
         .iter()
         .map(|path_item| &path_item.location)
         .collect_vec();
-    let track_offsets = operational_point_cache
-        .extract_location_from_path_items(&path_item_locations)
-        .expect("the path item cache should be built out from all the input path items of the train occurrence");
+    let track_offsets =
+        operational_point_cache.extract_location_from_path_items(&path_item_locations)?;
```
Comment (leovalais) [inline editoast/src/views/timetable/simulation.rs:653]: `extract_location_from_path_items` returns a pathfinding failure... 🤯

**Review by leovalais — APPROVED** [review]
Another untested case, thanks for fixing this.

**Review by flomonster — APPROVED** [review]
Thanks for the bug fix.
