### PR TITLE
front: refactor useOutputTableData(), fix missing hook deps

### LINKED ISSUE #13767: front: output time table is not updated after macro update
### What happened?

Note : the list of train is well updated, only the output table is not updated

https://github.com/user-attachments/assets/0db3924d-5c1d-4be4-80dd-e00212bd1d77

### What did you expect to happen?

keep all the elements up to date

### How can we reproduce it (as minimally and precisely as possible)?

video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

19cdb22

### PR DESCRIPTION
**Pull request by emersion**
_See individual commits._

Closes: https://github.com/OpenRailAssociation/osrd/issues/13767

CC'ing @aschantraine because https://github.com/OpenRailAssociation/osrd/pull/13771 touches the same function, and @Synar because she's familiar with this code.

### CODE REVIEW

File: front/src/modules/timesStops/hooks/useOutputTableData.ts [hunk 1]
```diff
@@ -45,10 +45,7 @@ const useOutputTableData = (
   // Format input path step rows
   useEffect(() => {
     const formatPathStepRows = async (train: Train): Promise<Map<string, TimesStopsRow>> => {
-      const trackIds = train.path.reduce<string[]>((ids, step) => {
-        if ('track' in step) ids.push(step.track);
-        return ids;
-      }, []);
+      const trackIds = train.path.flatMap((step) => 'track' in step ? [step.track] : []);
```
Comment (SharglutDev) [inline front/src/modules/timesStops/hooks/useOutputTableData.ts]: Don't feel like it's more readable (giving array in the condition only to flatten it at the end) but it is not very important :)

File: front/src/modules/timesStops/hooks/useOutputTableData.ts [hunk 2]
```diff
@@ -36,6 +36,20 @@ const useOutputTableData = (
...
+  }, [selectedTrain?.path]);
+
+  const [trackSections, setTrackSections] = useState<Record<string, TrackSection>>({});
+  useEffect(() => {
+    const fetchTrackSections = async () => {
+      const sections = await getTrackSectionsByIds(trackIds);
+      setTrackSections(sections);
+    };
+    fetchTrackSections();
+  }, [trackIds]);
```
Comment (SharglutDev) [inline front/src/modules/timesStops/hooks/useOutputTableData.ts]: You find it more readable to separate these 2 logics instead of inserting the `useMemo` logic inside the `useEffect` directly ?

**Review by SharglutDev — APPROVED** [review]
Reviewed with @aschantraine.
Lgtm and tested, it works great ! Just some minor comments

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 1 above)
Comment (emersion) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts]: I originally went with `.map(…).filter((trackId) => trackId !== null)`, would be fine with that as well. But the `.reduce()` I really find unnecessary here.

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 2 above)
Comment (emersion) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts]: I prefer to move logic out of `useEffect()` as much as possible. Ideally `getTrackSectionsByIds()` would be a hook instead of an async function.

`useEffect()` should only be used when we're not given the choice.

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts]: Fine by me :)

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts]: Agreed with first part :+1: 
Ok for the `useEffect` make sense.

**Review by Synar — APPROVED** [review]

**Comment by Synar** [comment]
(Not sure I love the idea of inlining the formatting functions, but I don't have a strong opinion on it either. The other changes seem both more important and quite positive though. Thanks for this work!)
