### PR TITLE
front: fix operational points names display in itinerary

### LINKED ISSUE #10117: Name of waypoints not properly displayed afterViriato import
### What happened?

I import this train [train_schedules.19.json](https://github.com/user-attachments/files/19587265/train_schedules.19.json)

Then I open it and put a rolling stock on it. Then I go the itinerary tab. The names of waypoints are not displayed :  
Image

Then if I save the train and reopen it, I have the correct names :  
Image

### What did you expect to happen?

I expect to have the correct names at the first step, without having to save and reopen my train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Import the json file
2. Open the MSCAXP06-1 train
3. Put a rolling stock on it
4. Go to the itinerary tab -> observe the problem
5. Save and reopen the train and go to the itinerary tab -> observe the expected behavior from the beginning

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

fe3b339

### PR DESCRIPTION
**Pull request by RomainValls**
close #10117 

The title says the issue happened after a viriato import. 
In fact, it was happening with all types of files during import when the name wasn't given in the file.

### CODE REVIEW

**Review by clarani — COMMENTED** [review]
Thank you for your PR @RomainValls :pray: 

It's exactly what should be done, but I think it might be better to move this code in usePathfinding, what do you think ?
If there is no pathfindingInput, then we should call your code to retrieve the additional data of the path steps, even if we can't launch a pathfinding

File: front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx [hunk 1]
```diff
@@ -19,6 +28,74 @@ const Vias = ({ zoomToFeaturePoint }: ViasProps) => {
...
+    const validPathSteps = pathSteps.filter(
+      (step): step is PathStep & { uic: number; secondary_code?: string } =>
+        step !== null && 'uic' in step
+    );
+
+    if (!validPathSteps.length) return [];
+
+    const uicChConditions = validPathSteps.map(({ uic, secondary_code }) => [
+      'and',
+      ['=', ['uic'], uic],
```
Comment (emersion) [inline front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx]: This handles the UIC case, but not other cases. Other cases might be used, e.g. trigram.

`buildOpSearchQuery()` already handles all of the cases, maybe we could just use that?

File: front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx [hunk 2]
```diff
@@ -19,6 +28,74 @@ const Vias = ({ zoomToFeaturePoint }: ViasProps) => {
...
+  const [postSearch] = osrdEditoastApi.endpoints.postSearch.useMutation();
+  const dispatch = useAppDispatch();
+
+  const hasUpdatedNames = useRef(false);
+
+  const searchOperationalPointsByUIC = useCallback(async () => {
+    if (!infraId || !pathSteps.length) return [];
+
+    const validPathSteps = pathSteps.filter(
+      (step): step is PathStep & { uic: number; secondary_code?: string } =>
```
Comment (Synar) [inline front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx]: I would prefer something like 'step is Extract<PathStep, { uic: number }>' to assume as little as possible from what we actually check, but in this case I believe the cast is entirely unnecessary and typescript will do the correct assumptions by itself.
```suggestion
      (step) =>
```

File: front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx [hunk 3]
```diff
@@ -19,6 +28,74 @@ const Vias = ({ zoomToFeaturePoint }: ViasProps) => {
...
+      const opMap = results.reduce(
+        (acc, op) => {
+          acc[`87${op.ci}`] = op.name;
+          return acc;
+        },
+        {} as Record<string, string>
+      );
+
+      const updatedSteps = pathSteps
+        .filter((step): step is PathStep => step !== null)
```
Comment (Synar) [inline front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/Vias.tsx]:
```suggestion
      (step) =>
```

**Review by Synar — COMMENTED** [review]
Nice work, this was an annoying issue indeed ^^

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 4]
```diff
@@ -66,6 +68,58 @@ const usePathfinding = ({
...
+        } else if ('operational_point' in step && step.operational_point) {
+          name = opMap[step.operational_point];
+        }
+
+        return {
+          ...step,
+          name,
+        };
+      });
+      dispatch(updatePathSteps(updatedSteps));
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts:112]: As a more general comment: I don't really like the pattern where a `useEffect()` listens for `pathSteps` changes, then transforms the data and overwrites path steps again by calling `updatePathSteps()`. It's very complicated to reason about the data flow (since `pathSteps` may be mutated basically anywhere in the app) and it might result in infinite feedback loops.

In fact, doesn't this PR make the app search for OPs in an infinite loop?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 5]
```diff
@@ -66,6 +68,58 @@ const usePathfinding = ({
   const [postPathProperties] =
     osrdEditoastApi.endpoints.postInfraByInfraIdPathProperties.useLazyQuery();
 
+  const [postSearch] = osrdEditoastApi.endpoints.postSearch.useMutation();
+
+  const fetchOperationalPoints = useCallback(async () => {
+    if (!infraId || !pathSteps.length) return;
+
+    const searchPayload = buildOpSearchQuery(infraId, [
+      { path: pathSteps.filter((step): step is PathStep => step !== null) } as TrainScheduleResult,
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: I think instead of casting (and sending a value which isn't actually a `TrainScheduleResult`), we can adapt `buildOpSearchQuery()` to take as input a list of path steps instead of `TrainScheduleResult[]` (ideally in a separate commit before this call is added here).

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 6]
```diff
@@ -66,6 +68,58 @@ const usePathfinding = ({
...
+        pageSize: 101,
+      }).unwrap()) as SearchResultItemOperationalPoint[];
+
+      if (!results.length) return;
+
+      const opMap = results.reduce(
+        (acc, op) => {
+          acc[`87${op.ci}`] = op.name;
+          acc[op.trigram] = op.name;
+          acc[op.obj_id] = op.name;
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: This can result in conflicts: OP IDs might collide with trigrams and UICs.

Moreover, the input list may contain multiple path steps with the same trigram/UIC, but with a different `secondary_code`.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 4 above)
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts:112]: I see a useCallback, not a useEffect, so it should be fine, beyond redefining the function often. Unless you're talking about a different useEffect deeper in the code.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 7]
```diff
@@ -66,6 +68,58 @@ const usePathfinding = ({
...
+        return {
+          ...step,
+          name,
+        };
+      });
+      dispatch(updatePathSteps(updatedSteps));
+    } catch (error) {
+      console.error('Error fetching operational points:', error);
+    }
+  }, [infraId, pathSteps]);
```
Comment (Synar) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: The caller of this function takes pathSteps as an argument, not a dependency. I believe we should either do the same (using the functional form of set state if we really want to be cautious), or update the dependency array of the caller.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 6 above)
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: I agree that having 3 dicts/a struct of dicts would be cleaner to avoid collisions, though I'm unsure they're possible in practice.

For the same primary identifier but different secondary code case, won't these steps share the same name though?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 8]
```diff
@@ -66,6 +68,58 @@ const usePathfinding = ({
...
+      const results = (await postSearch({
+        searchPayload,
+        pageSize: 101,
+      }).unwrap()) as SearchResultItemOperationalPoint[];
+
+      if (!results.length) return;
+
+      const opMap = results.reduce(
+        (acc, op) => {
+          acc[`87${op.ci}`] = op.name;
```
Comment (Synar) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: Feel free to ignore, but I'm curious, is the 87 in front of a ci to give an uic a sncf thing? Is it something general?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 4 above)
Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts:112]: I thought the callback was invoked from a `useEffect()`, but it seems like that's not the case.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 6 above)
Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: They're maybe not happening with the France infrastructure, but may happen if another country decides to use numerical IDs for OP IDs for instance.

> For the same primary identifier but different secondary code case, won't these steps share the same name though?

I don't believe that's guaranteed by the data model. Each OP object is independent in the database and has its own name.

Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: (I don't think we need any kind of map/record here. We can just iterate over all results instead. The number of results should be low™: it cannot exceed the number of path steps.)

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 8 above)
Comment (clarani) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Yes it's a sncf thing :/ the pr's uic is 87 + the pr's ci in France (87 is an id for SNCF, see https://fr.wikipedia.org/wiki/Liste_des_codes_pays_UIC)

Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Thanks! So ideally we would need to know the op's country in order to correctly match with a path step, but that seems painful.

Another stupid question way beyond this pr, but why do we use a ci to identify each op and not directly an uic in the first place?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 4 above)
Comment (RomainValls) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts:112]: Should I change anything or is keeping the useCallback ok for you ?

Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts:112]: I'm still not a fan of how we overwrite `pathSteps` in a lot of places in osrd, but fixing that would require a much larger refactoring and is out of scope for your PR. Let's track this separately in https://github.com/OpenRailAssociation/osrd/issues/11217.

File: front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts [hunk 9]
```diff
@@ -1,17 +1,16 @@
...
-const buildOpSearchQuery = (
-  infraId: number,
-  trainSchedules: TrainScheduleResult[]
-): SearchPayload | null => {
-  const pathItems = trainSchedules.map((schedule) => schedule.path).flat();
+const buildOpSearchQuery = (infraId: number, pathSteps: PathStep[]): SearchPayload | null => {
   const pathItemQueries = [];
   const pathItemSet = new Set<string>();
 
+  const pathItems = pathSteps.map((step) => step).flat();
```
Comment (emersion) [inline front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts]: This `.map()` seems to be a no-op: it creates a new array identical to the previous one. I don't think we need the `flat()` anymore.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 10]
```diff
@@ -205,6 +269,7 @@ const usePathfinding = ({
 
       if (!pathfindingInput) {
         setIsMissingParam();
+        await fetchOperationalPoints(pathSteps.filter((step): step is PathStep => step !== null));
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: Why do we need the `step is PathStep`?

I think this is dangerous in case the type of `pathSteps` is changed to something else.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 11]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+          }
+
+          return {
+            ...step,
+            name: matchedOp?.name,
+          };
+        });
+
+        dispatch(updatePathSteps(updatedSteps));
+      } catch (error) {
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts:85]: I think we only need to wrap the `postSearch()` in the `try`/`catch` block:

```ts
let results: SearchResultItemOperationalPoint[];
try {
  results = (await postSearch({
    searchPayload,
    pageSize: 101,
  }).unwrap()) as SearchResultItemOperationalPoint[];
} catch (error) {
  console.error('Error fetching operational points:', error);
  return;
}

// rest of the code
```

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 12]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
 
+  const [postSearch] = osrdEditoastApi.endpoints.postSearch.useMutation();
+
+  const fetchOperationalPoints = useCallback(
+    async (steps: PathStep[]) => {
+      if (!infraId || !steps.length) return;
+
+      const searchPayload = buildOpSearchQuery(
+        infraId,
+        steps.filter((step) => step !== null)
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: This filter shouldn't be required since the type of `steps` is `PathStep[]`.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 13]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+      try {
+        const results = (await postSearch({
+          searchPayload,
+          pageSize: 101,
+        }).unwrap()) as SearchResultItemOperationalPoint[];
+
+        if (!results.length) return;
+
+        const updatedSteps = steps.map((step) => {
+          if (!step) return step;
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: Same here: `step` cannot be null here.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 14]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+
+          let matchedOp: SearchResultItemOperationalPoint | undefined;
+
+          const stepUICString = 'uic' in step && step.uic ? String(step.uic) : null;
+
+          if (stepUICString) {
+            matchedOp = results.find(
+              (op) =>
+                `87${op.ci}` === stepUICString &&
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: I'd prefer to avoid hardcoding French-specific assumptions if we can. We should be able to use `op.uic` here instead.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 15]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+                'secondary_code' in step &&
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: I think `'secondary_code' in step` is always true when `'uic' in step`?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 16]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+                (!step.secondary_code || op.ch === step.secondary_code)
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: So, in case the step is missing a secondary code, things are a bit tricky… Let's say for instance the path steps are:

```ts
[
  { uic: 87042, secondary_code: "TR" },
  { uic: 87042, secondary_code: null }
]
```

and then the backend returns this:

```ts
[
  { uic: 87042, ch: "TR", name: "Romain Triage" },
  { uic: 87042, ch: "BV", name: "Romain-Ville" }
]
```

Then we'd pick "TR" for both path steps, even if the pathfinding algorithm may pick "TR" for the first one and "BV" for the second one.

(Note, maybe instead of BV it could be something else entirely… technically when a path step doesn't specify a `secondary_code` it matches any `ch`.)

I'd be fine leaving this as a TODO for later. Ideally we'd get a new API endpoint to get OPs or OP IDs from path steps and all of these issues would be resolved.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 17]
```diff
@@ -66,6 +67,69 @@ const usePathfinding = ({
...
+            );
+          }
+
+          if (!matchedOp && 'trigram' in step && step.trigram) {
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: If we use `else if`, we don't need to repeat `!matchedOp` each time.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 8 above)
Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Not a stupid question at all! I've come to the same conclusion as you it seems: https://github.com/OpenRailAssociation/osrd/pull/10949#discussion_r2007387063

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 16 above)
Comment (RomainValls) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Good point !
I agree on leaving this as a TODO, I see you created a ticket mentioning this one , thanks 👍

Comment (emersion) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: https://github.com/OpenRailAssociation/osrd/issues/11217 is unrelated to the problem described in this comment. I'd suggest leaving a TODO comment.

File: front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts (hunk 9 above)
Comment (emersion) [reply front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts]: It seems like the `map()` call is still there? Does removing it cause issues?

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 18]
```diff
@@ -66,6 +67,52 @@ const usePathfinding = ({
...
+
+      if (!searchPayload) return;
+      let results: SearchResultItemOperationalPoint[];
+      try {
+        results = (await postSearch({
+          searchPayload,
+          pageSize: 101,
+        }).unwrap()) as SearchResultItemOperationalPoint[];
+      } catch (error) {
+        console.error('Error fetching operational points:', error);
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts:86]: We should `return` after printing the error, or else we `results` is left undefined and will cause a runtime error below when calling `results.find()`.

I'm actually surprised TypeScript doesn't complain about this.

**Review by emersion — COMMENTED** [review]
Overall looks like this is almost good to go, thanks for bearing with me :)

File: front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts (hunk 9 above)
Comment (RomainValls) [reply front/src/modules/operationalPoint/helpers/buildOpSearchQuery.ts]: My bad ! Removed it :)

**Review by emersion — APPROVED** [review]
LGTM, thanks!
