### PR TITLE
Fix missing order by in paginated endpoints

### LINKED ISSUE #13430: Requirements retrieval endpoint is random 🎲
### What happened?

STDCM does not load the full timetable requirements; it loads one random part of it.

When retrieving requirements of a timetable, the paginated response is unordered and contains duplicates.
With a huge timetable running the following python script I found multiple intersections:

```python
import requests

ids = set()
for page in range(1, 285):
    url = f"http://localhost:4000/api/timetable/2/requirements?page={page}&infra_id=2"

    payload = {}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)
    new_ids = set([train['train_id'] for train in response.json()['results']])
    intersection = ids & new_ids
    if len(intersection ) > 0:
        print("Intersection:", len(intersection))
        print(intersection)

    ids = ids | new_ids
    print(f"Debug: current trains: {len(ids)}")
```

> [!CAUTION]
> We should ensure that this is the case only for the requirements endpoint and not for all paginated endpoints. 

### What did you expect to happen?

This endpoint should not return the requirements of the same train twice in different pages.

### How can we reproduce it (as minimally and precisely as possible)?

Run the above python script with a huge timetable.

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

d0367d1d650bea985b250dfbade170a1f056c210

### PR DESCRIPTION
**Pull request by flomonster**
close https://github.com/OpenRailAssociation/osrd/issues/13430

List of found occurrences:
- requirements
- round trips
- infra
- macro nodes
- sub categories

### CODE REVIEW

**Review by leovalais — APPROVED** [review]

File: editoast/src/views/scenario/macro_nodes.rs [hunk 1]
```diff
@@ -171,7 +171,9 @@ pub(in crate::views) async fn list(
     let settings = pagination_params
         .into_selection_settings()
         .filter(move || MacroNode::SCENARIO_ID.eq(scenario_id));
-    let (result, stats) = MacroNode::list_paginated(&mut conn, settings).await?;
+    let (result, stats) =
+        MacroNode::list_paginated(&mut conn, settings.order_by(move || MacroNode::ID.asc()))
```
Comment (bougue-pe) [inline editoast/src/views/scenario/macro_nodes.rs:175]: Could we fix the trait so that it requires a sorting key instead?

I'm also thinking of something on PG's side to default to a correct behavior, like using a view which would also ensure an index? 🤔

Comment (flomonster) [reply editoast/src/views/scenario/macro_nodes.rs:175]: We thought about ensuring that the user configured an order. It will be done in a following PR.
