### PR TITLE
editoast: match train_schedule with simulation_output

### LINKED ISSUE #5206: Some info on the timetable are displayed on the wrong train
### What happened?

When you have more than one train in your timetable, and you want to add an allowance for example, you will see it applied to another train than the one you just edited. But it's not always the case, we have to find the "logic" behind it. 
Same for the stops, the arrival time and the path duration. 

This bug is only on the TimeTable. SimulationResults works well and display good info. 

### What did you expect to happen?

I expect that all the info are well displayed to the train I selected. 

### How can we reproduce it (as minimally and precisely as possible)?

Go to "Scenario"
Add some trains
"Play" with a train by adding and modifying recovery margin for example
The bug will occurs 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v118.0.1
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

cb78a63b

### PR DESCRIPTION
**Pull request by Akctarus**
closes #5206 , #5140

### CODE REVIEW

File: editoast/src/models/timetable.rs [hunk 1]
```diff
@@ -212,9 +212,15 @@ pub async fn get_timetable_train_schedules_with_simulations(
...
         .load::<SimulationOutput>(&mut conn)
         .await?;
-    let result = train_schedules
+    let result: Vec<(TrainSchedule, SimulationOutput)> = train_schedules
         .into_iter()
-        .zip(simulation_outputs)
+        .flat_map(|schedule| {
+            let matching_output = simulation_outputs
+                .iter()
+                .find(|output| output.train_schedule_id == schedule.id);
```
Comment (flomonster) [inline editoast/src/models/timetable.rs]: We could improve the complexity from $\mathcal{O}(n^2)$ to $\mathcal{O}(n)$. We could create a hashmap to avoid iterate on the `simulation_outputs` for each train schedule.

**Review by flomonster — CHANGES_REQUESTED** [review]
Thanks. We could improve the performance of this endpoint.

**Review by hamz2a — COMMENTED** [review]
LGTM

**Review by hamz2a — APPROVED** [review]

File: editoast/src/models/timetable.rs [hunk 2]
```diff
@@ -212,9 +214,19 @@ pub async fn get_timetable_train_schedules_with_simulations(
     let simulation_outputs = SimulationOutput::belonging_to(&train_schedules)
         .load::<SimulationOutput>(&mut conn)
         .await?;
-    let result = train_schedules
+    let mut output_map: HashMap<Option<i64>, SimulationOutput> = HashMap::new();
+
+    for output in &simulation_outputs {
+        output_map.insert(output.train_schedule_id, output.clone());
+    }
```
Comment (flomonster) [inline editoast/src/models/timetable.rs]: This suggestion avoid to `clone()`
```suggestion
    let mut output_map: HashMap<_, _> = simulation_outputs
        .into_iter()
        .map(|o| (o.train_schedule_id.unwrap(), o))
        .collect();
```

File: editoast/src/models/timetable.rs [hunk 3]
```diff
@@ -212,9 +214,19 @@ pub async fn get_timetable_train_schedules_with_simulations(
...
+
+    let result: Vec<(TrainSchedule, SimulationOutput)> = train_schedules
         .into_iter()
-        .zip(simulation_outputs)
+        .filter_map(|schedule| {
+            output_map
+                .get(&schedule.id)
+                .map(|output| (schedule.clone(), output.clone()))
+        })
```
Comment (flomonster) [inline editoast/src/models/timetable.rs]: Same here
```suggestion
        .filter_map(|schedule| {
            schedule
                .id
                .and_then(|id| output_map.remove(&id))
                .map(|output| (schedule, output))
        })
```

**Review by flomonster — APPROVED** [review]
I suggest some changes to avoid cloning objects.
