### PR TITLE
fixes remove the white backound in the search bar for the rolling stock modal …

### LINKED ISSUE #5717: Search field appears white on white background when selecting a rolling stock
### What happened?

image

### What did you expect to happen?

It should be the same grey as here
image

### How can we reproduce it (as minimally and precisely as possible)?

1. Select a rolling stock in the train creation modal

### What operating system, browser and environment are you using?

dev

### OSRD version (top right corner `Account` button > `Informations`)

c482536c

### PR DESCRIPTION
**Pull request by tykayn**
fixes the white background in the search for rolling stock modal
fixes https://github.com/osrd-project/osrd/issues/5717

### CODE REVIEW

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx [hunk 1]
```diff
@@ -192,7 +192,6 @@ const SearchRollingStock = ({
           noMargin
           unit={<i className="icons-search" />}
           sm
-          whiteBG
```
Comment (Yohh) [inline front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx:195]: we need this whit background in the rollingStock editor, could you add a condition to enable it?

**Review by Yohh — CHANGES_REQUESTED** [review]

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx (hunk 1 above)
Comment (tykayn) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx:195]: ah yes i guess i should make it conditionnal to have it regular only in the modal. shouldn't it be looking alike everywhere ?

Comment (Yohh) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx:195]: I guess we only use it in RollingStockEditor and RollingStockModal, and the bakground is different in those components, which is why we need a condition

Comment (tykayn) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx:195]: ok, i updated with a conditionnal prop to have the white bg only on the modal

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx [hunk 2]
```diff
@@ -192,6 +192,7 @@ export default function RollingStockEditor({ rollingStocks }: RollingStockEditor
           setIsLoading={setIsLoading}
           mustResetFilters={isDuplicating}
           setMustResetFilters={setIsDuplicating}
+          hasWhiteBackround={true}
```
Comment (Yohh) [inline front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: g is missing, where is g?

**Review by Yohh — CHANGES_REQUESTED** [review]

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx (hunk 2 above)
Comment (tykayn) [reply front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: damned, i fixed it

File: front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx [hunk 3]
```diff
@@ -91,6 +91,7 @@ function RollingStockModal({ ref2scroll }: RollingStockModal) {
             filteredRollingStockList={filteredRollingStockList}
             isSuccess={isSuccess}
             setIsLoading={setIsLoading}
+            hasWhiteBackground={true}
```
Comment (Yohh) [inline front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx]: almost done, whiteBG has to be enabled in RollingStockEditor, and you don't have to set a value, just `hasWhiteBackground` to avoid the warning

**Review by Yohh — CHANGES_REQUESTED** [review]

File: front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx (hunk 3 above)
Comment (tykayn) [reply front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx]: ok fixed to attribute without any value

File: front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx [hunk 4]
```diff
@@ -91,6 +91,7 @@ function RollingStockModal({ ref2scroll }: RollingStockModal) {
             filteredRollingStockList={filteredRollingStockList}
             isSuccess={isSuccess}
             setIsLoading={setIsLoading}
+            hasWhiteBackground
```
Comment (Yohh) [inline front/src/modules/rollingStock/components/RollingStockSelector/RollingStockModal.tsx]:
```suggestion
```

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx [hunk 5]
```diff
@@ -192,6 +192,7 @@ export default function RollingStockEditor({ rollingStocks }: RollingStockEditor
           setIsLoading={setIsLoading}
           mustResetFilters={isDuplicating}
           setMustResetFilters={setIsDuplicating}
+
```
Comment (Yohh) [inline front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]:
```suggestion
hasWhiteBackground
```

**Review by Yohh — CHANGES_REQUESTED** [review]

**Review by Akctarus — APPROVED** [review]
I was wrong, there are still changes to be made

**Review by nicolaswurtz — APPROVED** [review]

**Review by Yohh — APPROVED** [review]

**Review by Akctarus — COMMENTED** [review]
LGTM
