### PR TITLE
front: fix track step names in input table

### LINKED ISSUE #12115: path input : requested points get the wrong name
### What happened?

When adding a requested point (click on the map), it gets some weird names.

When creating a train, it's displayed as "waypoint id<n>" (and not "requested point (1)".
When editing a train, it seems to take the name of the first waypoint in the path...

https://github.com/user-attachments/assets/1cc98923-6c0b-40eb-b788-1deff4466bf5

### What did you expect to happen?

I expect requested points to always have "request point (<n>)" names.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train, with a waypoint that's a requested point

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

d7ff4a7

### PR DESCRIPTION
**Pull request by Synar**
Close #12115

### CODE REVIEW

File: front/src/modules/pathfinding/utils.ts [hunk 1]
```diff
@@ -109,7 +115,9 @@ export const upsertPathStepsInOPs = (ops: SuggestedOP[], pathSteps: PathStep[]):
         arrival,
         receptionSignal,
         theoreticalMargin,
+        name: t('simulationResults.requestedPoint', { count: waypointCounter }),
```
Comment (SharglutDev) [inline front/src/modules/pathfinding/utils.ts]: very nitty but as we now use this translation not only for simulation results, should we move it somewhere in the translation file ? (it won't be an issue a few month when we will merge both tables)

**Review by SharglutDev — APPROVED** [review]
Thank you for the fix :)

File: front/src/modules/pathfinding/utils.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/pathfinding/utils.ts]: I don't have any strong opinions on this. We could duplicate the key to also add it in the manageTrainSchedule section. We could also move it in some other section, but I'm not sure which, do you have any suggestion?

Comment (SharglutDev) [reply front/src/modules/pathfinding/utils.ts]: We could move it to the `"main"` section maybe ?

Comment (Synar) [reply front/src/modules/pathfinding/utils.ts]: Done, thx ^^

**Comment by Synar** [comment]
@clarani deleted the useSpeedSpaceChart hook in #12177, and prepare properties is no longer behind a useEffect/useMemo but instead computed at every render, so the second commit is no longer needed and has been dropped.

(If we do decide to put it back in a useX later we would need to add the language to the dependecy array again, which is what the second commit was doing.)

**Comment by Synar** [comment]
The only real new part to review is in front/src/applications/operationalStudies/__tests__/upsertMapWaypointsInOperationalPoints.spec.ts @SharglutDev ^^

The test assumed the exact namespace of translation keys in its mocked t function, I generalized it a bit.

(I wanted to do a fixup but amended instead, sorry!)

**Review by SharglutDev — APPROVED** [review]
