### PR TITLE
front: fix gesico modal latency

### LINKED ISSUE #14758: LMR : GESICO modal is not responding smoothly
### What happened?

When the "send to GESICO" modal is open, it does not respond smoothly on actions. It takes a little time between the click and the effect (especially when you click on the send button to see the animation when it's sending, on when it doesn't work).

https://github.com/user-attachments/assets/81995e88-fbef-43eb-acc4-21bc1a165f06

It seems to be like this when the simulation is on a long path

https://github.com/user-attachments/assets/a93c5ab7-672f-49c7-91ff-5aee98132c3a

### What did you expect to happen?

The app should respond on click

### How can we reproduce it (as minimally and precisely as possible)?

1. Open LMR
2. Find a simulation
3. Retain it
4. Open the GESICO modal and try to click on buttons

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

a3d2b0c

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #14758 

This PR fixes a performance issue causing noticeable latency when opening the request submission modal.
The cause was an unnecessary multiple generation of the simulation result PDF, which is now generated only once.

In addition, this PR includes a few minor bug fixes:
- CSS fix: ensure `<section />` elements correctly display bold text where expected

- Fix DatePicker initialization issue that prevented selecting a date other than the simulation date

- Fix typo in component name: StcdmResults → StdcmResults

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx [hunk 1]
```diff
@@ -73,6 +67,8 @@ const SendToRailwayManagerModal = ({
 
   const DEFAULT_TRAIN_CATEGORY = { value: '', label: t('modal.noCategory') };
 
+  console.info('Opened ! ');
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx]: Remnant from a debugging session?

Comment (SarahBellaha) [reply front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx]: Indeed, thanks !

File: front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx [hunk 2]
```diff
@@ -376,30 +354,21 @@ const SendToRailwayManagerModal = ({
...
-                      <span className="pdf-badge">{t('modal.pdf')}</span>
-                    </div>
-                  );
+              <div
+                className="pdf-download"
+                style={{ cursor: 'pointer' }}
+                onClick={() => {
+                  if (!pdfBlob) return;
+                  const url = URL.createObjectURL(pdfBlob);
+                  window.open(url, '_blank');
```
Comment (Caracol3) [inline front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx:370]: After `URL.createObjectURL` we can use `URL.revokeObjectURL` (with a short delay).

**Review by Caracol3 — APPROVED** [review]
LGTM

**Review by kmer2016 — APPROVED** [review]
Well done!
