### PR TITLE
core: fix intermediate points in the pathfinding

### LINKED ISSUE #925: bug: when adding a pathfinding step, it is instantly removed
I *suspect* this comes from the recent pathfinding changes in the back so I'll investigate first, but it it still unclear

### PR DESCRIPTION
**Pull request by eckter**
fix #925

### CODE REVIEW

**Comment by multun** [comment]
Please add a comment description:
```
The result of the pathfinding should have both waypoint suggestions and actual input waypoints.
Before this change, suggestions worked properly, but input waypoints were not returned back to the client.
This caused user requested waypoints to vanish after the first pathfinding.
```

File: core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java [hunk 1]
```diff
@@ -19,7 +19,8 @@
             Step<EdgeT> prev, // Previous step (to construct the result)
             double totalDistance, // Total distance from the start
             double weight, // Priority queue weight (could be different from totalDistance to allow for A*)
-            int nReachedTargets // How many targets have been passed
+            int nReachedTargets, // How many targets have been passed
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java]: How many targets we found by this path

File: core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java [hunk 2]
```diff
@@ -19,7 +19,8 @@
...
+            List<EdgeLocation<EdgeT>> waypoints // The waypoints reached in this step
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java]: s/waypoints/targets/

The list of targets found within this step

File: core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java [hunk 3]
```diff
@@ -165,23 +180,25 @@ private boolean hasReachedEnd(
...
-        var res = new ArrayList<EdgeRange<EdgeT>>();
-        for (var range : ranges) {
-            var lastIndex = res.size() - 1;
-            if (res.isEmpty() || res.get(lastIndex).edge != range.edge)
-                res.add(range);
+        var ranges = new ArrayList<EdgeRange<EdgeT>>();
+        var waypoints = new ArrayList<EdgeLocation<EdgeT>>();
+        for (var step : orderedSteps) {
+            var lastIndex = ranges.size() - 1;
+            if (ranges.isEmpty() || ranges.get(lastIndex).edge != step.range.edge)
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java]: if we changed edge, add a new range

File: core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java [hunk 4]
```diff
@@ -165,23 +180,25 @@ private boolean hasReachedEnd(
...
+                ranges.add(step.range);
             else {
-                var newRange = new EdgeRange<>(range.edge, res.get(lastIndex).start, range.end);
-                res.set(lastIndex, newRange);
+                var newRange = new EdgeRange<>(step.range.edge, ranges.get(lastIndex).start, step.range.end);
+                ranges.set(lastIndex, newRange);
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/utils/graph/Pathfinding.java:199]: otherwise, coalesce with the previous range

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java [hunk 5]
```diff
@@ -30,30 +32,77 @@ public class PathfindingResult {
...
         return res;
     }
 
+    /** Adds all missing waypoints and sorts them */
+    private static void setAllWaypoints(PathfindingResult res, Pathfinding.Result<SignalingRoute> path) {
+        for (var waypoint : path.waypoints())
+            res.addStep(convertLocation(waypoint));
+        var waypointsPerTrack = HashMultimap.<String, PathWaypointResult>create();
+        for (var waypoint : res.pathWaypoints)
+            waypointsPerTrack.put(waypoint.track.id.id, waypoint);
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java]: add to waypointsPerTrack user provided waypoints

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java [hunk 6]
```diff
@@ -86,15 +135,8 @@ private static RoutePathResult makeRouteResult(
...
-                var firstLocation = truncatedRange.offsetLocation(0);
-                pathfindingResult.addStep(
-                        new PathWaypointResult(firstLocation.track().getID(), firstLocation.offset())
-                );
-            }
 
-            // Add waypoints: OP as suggestions, and start / end locations
+            // Add operational points as optional waypoints
             for (var op : truncatedRange.getOperationalPoints())
                 pathfindingResult.addStep(new PathWaypointResult(op.element(), trackSection));
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java]: can you add a static method "suggested" and "userDefined" to make clear what kind of waypoint is created by this constructor?

Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java]: this is unrelated to the makeRoute method, it should really be moved to a more meaningful place

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java [hunk 7]
```diff
@@ -30,30 +32,77 @@ public class PathfindingResult {
...
+            for (var trackRange : routeRange.edge().getInfraRoute().getTrackRanges()) {
+                for (var waypoint : waypointsPerTrack.get(trackRange.track.getEdge().getID())) {
+                    if (trackRange.containsOffset(waypoint.position)) {
+                        waypoint.pathOffset = trackOffset + trackRange.offsetOf(waypoint.position);
+                    }
+                }
+                trackOffset += trackRange.getLength();
+            }
+            routeOffset += routeRange.end() - routeRange.start();
+        }
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java]: Here's an idea: iterate on all the waypoints in the path, and add them in order. When doing that, you can determine if the waypoint was added by the user or if it's a suggestion. this way, no need to compute the path offset or to sort, as the result if guaranteed to be sorted by the way we iterate over waypoints.

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java [hunk 8]
```diff
@@ -30,30 +32,77 @@ public class PathfindingResult {
...
+
+        // Remove duplicates
+        for (int i = 1; i < res.pathWaypoints.size(); i++) {
+            if (res.pathWaypoints.get(i - 1).isDuplicate(res.pathWaypoints.get(i))) {
+                res.pathWaypoints.get(i - 1).merge(res.pathWaypoints.get(i));
+                res.pathWaypoints.remove(i);
+                i--;
+            }
+
+        }
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java]: if my above suggestion works, this is not needed anymore, as addstep already deduplicates

**Review by multun — DISMISSED** [review]

**Review by multun — APPROVED** [review]
