### PR TITLE
front: allowances: fix allowances components

### LINKED ISSUE #5223: Error undefined when mareco allowance is defined in the interval interface
## Reproduction step

Create a train with 60% of mareco margin. If the margin is entered in the bar to define different values for different intervals this error is displayed :  

Image

When the same margin is entered in the first line (not in the different intervals bar) the train is correctly added. 

Image

Error message:
```json
{"type":"editoast:coreclient:Forward","context":{"status":400,"core_error":{"cause":null,"message":"We could not go slow enough in this setting to match the given allowance time","trace":null,"type":"allowance_convergence"},"url":"http://"},"message":"We could not go slow enough in this setting to match the given allowance time"}
```

Version `cb78a63b`

### LINKED ISSUE #5484: UX of `Recovery allowance` is very strange
A value must be set in this field :

Image

To access the interval editor:

Image

And the value is not taken into account on all the path :

Image

### Expected behavior

Have only the interval editor ? By default you can set a value on the all path so IMO it's ok.
Must fix [#5223](https://github.com/osrd-project/osrd/issues/5223) before dropping the first input field

Version: `1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0`

### PR DESCRIPTION
**Pull request by clarani**
closes #5223
closes #5484

### CODE REVIEW

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 1]
```diff
@@ -88,11 +90,12 @@ export default function InputGroupSNCF({
         title={placeholder}
         placeholder={placeholder}
         onChange={(e) => handleType({ type: selected.id, value: e.target.value })}
-        value={value}
+        value={value !== undefined ? value : ''}
```
Comment (alexandredamiron) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: you can use the nullish coalescent operator
```suggestion
        value={value ?? ''}
```

**Review by alexandredamiron — CHANGES_REQUESTED** [review]

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: I've added a new test, so I think I can't use the nullish coalescent operator now

Comment (alexandredamiron) [reply front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: ok closing

**Review by alexandredamiron — APPROVED** [review]

**Review by nicolaswurtz — APPROVED** [review]
