### PR TITLE
front: fetch path step names when pathfinding fails

### LINKED ISSUE #11953: front: OP are shown with their id instead of their name
### What happened?

When I edit a train schedule (with a pathfinding error, but I don't know if this is a mandatory condition).

https://github.com/user-attachments/assets/68b43211-4454-4e40-ac3b-d6695053c3a9

### What did you expect to happen?

I would expect the name of the Operational Point to be displayed, the UUID is useless for an end-user. 

### How can we reproduce it (as minimally and precisely as possible)?

I'm able to reproduce the problem by loading the following timetable in a France infrastructure

[timetable.json](https://github.com/user-attachments/files/20490730/timetable.2.json)

Then:
- edit the train
- go in the routing tab
- observe the weird UUID

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

41533ee

### PR DESCRIPTION
**Pull request by Synar**
Close [#11953](https://github.com/OpenRailAssociation/osrd/issues/11953)

Extension of  #10949 ^^

### CODE REVIEW

**Comment by JulesPeignier** [comment]
:heart_eyes:

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 1]
```diff
@@ -68,7 +68,16 @@ const usePathfinding = ({
 
   const [postSearch] = osrdEditoastApi.endpoints.postSearch.useMutation();
 
-  const fetchOperationalPoints = useCallback(
+  /**
+   * Fetches operational point data for the given path steps using a search API call
+   * and updates each step with the matched operational point's name (if found).
+   *
+   * This is useful when the pathfinding can not be ran or fails.
+   * If pathfinding is succesful, calling this function is unnecessary.
```
Comment (SharglutDev) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]:
```suggestion
   * If pathfinding is successful, calling this function is unnecessary.
```

File: front/src/modules/pathfinding/hooks/usePathfinding.ts
Comment (SharglutDev) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts:1]: Not sure if it's coming from my currently laggy computer but I have this behavior : 
[Capture vidéo du 10-06-2025 15:16:17.webm](https://github.com/user-attachments/assets/5f655117-d4df-4d0d-aab7-c32f2a771146)

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Thanks for the catch!

File: front/src/modules/pathfinding/hooks/usePathfinding.ts
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts:1]: Nice catch, fixed ^^

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: Fixed ^^

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ! Thank for the fix :)
