### PR TITLE
core: log file describing why no solution was found

### LINKED ISSUE #15371: core: stdcm: in case of failure, generate a file that describes the main conflicts
Identifying why a simulation failed can be quite tedious (I struggled when investigating https://github.com/osrd-project/osrd-confidential/issues/1427).

But now that we have:

* An s3 that can log some extra json data per request
* Metadata (train names) included with the timetable requirements

It *should* be possible to log the main conflicts encountered during the search. 

It's also required for the research work on timetable changes, the previous workflow has been broken since https://github.com/OpenRailAssociation/osrd/pull/13044

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/15371.

It should make it a lot easier to investigate negative results, and it would restore the ability to work on timetable changes in case of failure (the research project external to OSRD). We keep track of two lists of conflicts to make sure we keep the most relevant ones: the ones that add the largest amount of delays, and the ones that interfere with the path when we're the closest to the destination. 

Eventually it may also be forwarded back to the user. 

It requires some mildly "intrusive" change and a little bit of extra processing, but running a benchmark doesn't result in any measurable performance diff.

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/tracing/FailureExplainer.kt [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+                    .adapter(Report::class.java)
+        }
+    }
+
+    /** Describes a given conflict in JSON format. Infinite values are converted into -1. */
+    data class ConflictReport(
+        val at: ZonedDateTime,
+        @Json(name = "time_lost") val timeLost: Double,
+        @Json(name = "best_remaining_time") val bestRemainingTime: Double,
+        @Json(name = "past_travel_time") val pastTravelTime: Double,
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/tracing/FailureExplainer.kt]: Maybe `currentTravelTime`?

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt [hunk 2]
```diff
@@ -258,9 +267,15 @@ class BlockAvailability(
                         infraExplorer,
                         conflictProperties.firstConflictTime - pathStartTime,
                     )
+                val causedBy =
+                    requirementsWithMetadata
+                        ?.metadata[conflictProperties.conflictingZone]
+                        ?.firstOrNull { it.from <= endTime && it.to >= startTime }
+                        ?.trainName
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:273]: Kinda forgot what happens for WorkSchedules. Train name becomes `"WorkSchedule"` or something?

**Review by Erashin — APPROVED** [review]
This looks really clean gj :)

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt (hunk 2 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:273]: Yep. 

Ideally we should import and forward the train schedule identifier, but we don't.

Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:273]: It'd be nice yeah. Maybe a future improvement if needed.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/tracing/FailureExplainer.kt (hunk 1 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/tracing/FailureExplainer.kt]: Fixed in 00a2b3a6c82a53f982f1fb0f25f2c097ffd2ed1e
