### PR TITLE
front: fix simulations still displayed if no train in timetable

### LINKED ISSUE #7588: TSv2: When deleting a train, its not removed from the space time chart
### What happened?

See title. Also when deleting all the trains. The simulation results are still displayed.

### What did you expect to happen?

It should be removed from the chart and the results should disappear if there are no trains in the timetable.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with multiple train
2. Deleted one of them. It should still be displayed on the space time chart.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 625d185

### LINKED ISSUE #7590: TSv2: When adding a train, the space time chart is created but remains empty
### What happened?

image

The only way to display the chart is to press on the left button on the cart (the one to resize on trains)

### What did you expect to happen?

The chart should be displayed when adding a train or opening a scenario.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with trains and see the empty chart
2. or Go to an empty scenario, add a train and see the empty chart

### What operating system, browser and environment are you using?

- **Browser**: Firefox v116
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 625d185

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7588 

seems to have fixed #7590 as well

This PR : 
- fix both related bugs
- remove the else condition in `getSpaceTimeChartData` so we can properly benefit to the "not fetching train space time data" feature when deleting one or several trains and `setTrainResultsToFetch([])`
- refacto the way to change the path projection > allows to remove one useEffect in `ScenarioV2`

### CODE REVIEW

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx [hunk 1]
```diff
@@ -156,6 +156,7 @@ const ScenarioV2 = () => {
   }, [timetable, infra]);
 
   useEffect(() => {
+    console.log('timetable', timetable, trainIdUsedForProjection);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: Remnant from a debugging session? 😛

File: front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartV2.tsx [hunk 2]
```diff
@@ -161,6 +161,7 @@ const SpaceTimeChartV2 = (props: SpaceTimeChartV2Props) => {
 
   const redrawChart = () => {
     if (trainSimulations && trainIdUsedForProjection) {
+      console.log('trainSimulations', trainSimulations, trainIdUsedForProjection);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartV2.tsx]: Ditto?

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: The PR wasn't ready for review, sorry :)
We usually post on matrix to ask for review when ready (but you right, I should have put it on draft mode)

Comment (emersion) [reply front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: I see, nevermind then!

**Review by kmer2016 — APPROVED** [review]
LGTM !

**Review by clarani — APPROVED** [review]
Not tested

File: front/src/applications/operationalStudies/views/v2/SimulationResultsV2.tsx [hunk 3]
```diff
@@ -102,7 +102,7 @@ const SimulationResultsV2 = ({
     }
   }, [trainSimulation]);
 
-  if (!trainSimulation) return null;
+  if (!trainSimulation || spaceTimeData.length === 0) return null;
```
Comment (Yohh) [inline front/src/applications/operationalStudies/views/v2/SimulationResultsV2.tsx:105]: can you add either a message or a TODO to keep it as clean as possible?
