### PR TITLE
front: ngetoosrd: fix and streamline handle create and update

### LINKED ISSUE #13506: nge : duplicating train does not create the corresponding train in OSRD
### What happened?

I duplicate a train in NGE using the shortcut Ctrl+D (select a train and then do it)
The corresponding train is not created in OSRD (even after refreshing)

### What did you expect to happen?

I expect to have the corresponding train/service created

### How can we reproduce it (as minimally and precisely as possible)?

Create a train in OSRD, duplicate it, observe

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8b235ac

### LINKED ISSUE #14766: Macro mode : transforming a one-way trip to a round trip creates an error
### What happened?

- Create a one way trip in OSRD
- Change it to a round trip in NGE
- You get the following error

https://github.com/user-attachments/assets/db3b91ba-659b-48ae-b508-b358faad9513

### What did you expect to happen?

I expect no error

### How can we reproduce it (as minimally and precisely as possible)?

See above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

aaaa8e1

### PR DESCRIPTION
**Pull request by Synar**
Close [#13506](https://github.com/OpenRailAssociation/osrd/issues/13506)

Depend on https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/pull/687 (bump commit will be added as soon as that pr or one fixing the same issue is merged) -> pr merged, still waiting for the fork to be bumped

~~The code is a bit cumbersome at the moment. It should become much simpler as soon as paced trains and train schedules get merged. I propose we delay further refactoring until that point.~~ Done

Also close [#14766](https://github.com/OpenRailAssociation/osrd/issues/14766). Both changes were done in the same pr to ease testing and avoid conflicts.

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts [hunk 1]
```diff
@@ -436,41 +433,135 @@ const handleCreateTimetableItem = async (
...
+        ...newTimetableItems[1],
+        id: formatEditoastIdToTrainScheduleId(newTimetableItems[1].id),
+      };
+      state.timetableItemIdByNgeId.set(trainrun.id, [
+        newForwardTrainSchedule.id,
+        newReturnTrainSchedule.id,
+      ]);
+      addUpsertedTimetableItems([newForwardTrainSchedule, newReturnTrainSchedule]);
+    }
   }
```
Comment (Math-R) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: My though is that the nested if/else for handling one_way/round_trip and paced/non-paced creates 4 nearly identical branches.
The only things that change are:

- Which endpoint to call (PacedTrains vs TrainSchedules)
- Which ID formatter to use
- Body size ([trip] vs [trip, returnTrip])
- RoundTrips structure (one_ways vs round_trips)
- Expected item count (1 vs 2)

Maybe you should calculated these parameters in first place and then use a single code path, what do you think about this ?

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: Indeed, there's a lot of repeated code here. The main issue with refactoring is typing : paced train and train schedules are incompatible, and so we would need to have ifs at every step in order to pass the type checking (even though we know there won't be issues).

This is why I proposed delaying refactoring this code until paced trains and train schedules are merged, as this hurdle will go away.

I also think it would be nice to refactor the branching paths of update at the same time.

**Review by clarani — COMMENTED** [review]
Code LGTM, but I won't have the time to test today :/ I can test tomorrow !

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts [hunk 2]
```diff
@@ -436,41 +433,135 @@ const handleCreateTimetableItem = async (
...
-      id: timetableId,
-      body: [pacedTrain, returnPacedTrain],
-    })
-  ).unwrap();
-  if (newTimetableItems.length !== 2) {
-    throw new Error('Failed to create paced train with return trip');
+
+  const paced = createPacedAttributesFromTrainrun(trainrun, netzgrafikDto);
+
+  if (trainrun.direction === 'one_way') {
```
Comment (Yohh) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: in this if..else bloc, a lot of things are repeated, I'm not sure to have the time to test anything before monday but I'm pretty sure we can improve this to make conditions in a single bloc, more readable in the end

Comment (Yohh) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: anyway I read the upper comment, sorry I didn't check it before, you can merge if you you have an approve

**Comment by Synar** [comment]
Well now that the train schedules / paced trains merger got merged, I suppose I can refactor this pr now ^^

**Comment by Synar** [comment]
Done! This version is much simpler and shorter, thanks to the aforementioned merging. It can still be simplified further once round trip endpoints get merged (assuming they will).

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts [hunk 3]
```diff
@@ -435,41 +431,54 @@ const handleCreateTimetableItem = async (
...
-  };
-  state.timetableItemIdByNgeId.set(trainrun.id, [newPacedTrain.id, newReturnPacedTrain.id]);
-  addUpsertedTimetableItems([newPacedTrain, newReturnPacedTrain]);
+  const roundTrips: RoundTrips = returnTrip
+    ? { round_trips: [[newTimetableItems[0].id, newTimetableItems[1].id]] }
+    : { one_ways: [newTimetableItems[0].id] };
+
+  const postRoundTripsEndpoint = paced
+    ? osrdEditoastApi.endpoints.postRoundTripsPacedTrains
+    : osrdEditoastApi.endpoints.postRoundTripsTrainSchedules;
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: Hum I think `postRoundTripsTrainSchedules` is going to be dropped, you should always use `postRoundTripsPacedTrains`

**Review by clarani — COMMENTED** [review]
Codes LGTM :white_check_mark:
I will test once it's rebase.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts (hunk 3 above)
Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: But we're still querying from the train schedule endpoint currently, right? Shouldn't we do the switch in an atomic way?

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: But we're still querying from the train schedule endpoint currently, right? Shouldn't we do the switch in an atomic way?

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: Although I suppose it really does not matter much

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: Although I suppose it really does not matter much

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd/trainrun.ts]: These endpoints were dropped in another pr, so done!

**Comment by Synar** [comment]
This keeps getting new conflicts, so I would prefer we don't wait too long to merge it

**Review by Math-R — APPROVED** [review]
looks good to me :)
