### PR TITLE
front: fix exceptions tooltip positioning

### LINKED ISSUE #13438: No more hover information for exceptions
### What happened?

When hovering an exception, the information is not present anymore 

Image

### What did you expect to happen?

I expect to have the information of which attributes are different from the paced train

### How can we reproduce it (as minimally and precisely as possible)?

Just create a service with an exception and hover the icon

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

b9a7cc0

### PR DESCRIPTION
**Pull request by Synar**
Close [#13438](https://github.com/OpenRailAssociation/osrd/issues/13438)

The tooltip was rendered below the viewport, as its top value was too high. Indeed, getBoundingClientRect returned a top position relative to the viewport, but fixed positioning seems to be affected by containing blocks, and not always be directly fixed relative to the viewport. Here, one parent of each exception's occurrence-indicator seems to have contain:strict.

To fix this, renders the tooltip outside of the hijacking containing block through a portal.

As the round trip modal are rendered in the top layer and use OSRDTooltip too, also detect the presence of the toplayer.

Finally, we need to bump the z-index to make sure to get voer the z-index of 9999 of the round trip modal. Since it is already in the top layer, we should also be able to reduce the round trip modal z-index, but I was not confident making that change.

We may also want to explore stopping positioning the tooltip in a fixed way.

Before :
[tooltip_positioning_before.webm](https://github.com/user-attachments/assets/d52a4612-007d-48c8-bf20-2779e20bab97)

After :
[tooltip_positioning.webm](https://github.com/user-attachments/assets/d916e5db-a68f-4460-8161-4625844d3e9d)

### CODE REVIEW

File: front/src/common/OSRDTooltip.tsx [hunk 1]
```diff
@@ -77,14 +84,15 @@ const OSRDTooltip = ({
...
-  return (
+  return createPortal(
     <div
       data-testid="osrd-tooltip"
       className="osrd-tooltip"
       style={{
         top: position?.top ? position.top - window.scrollY : undefined,
         left: position?.left ? position.left - window.scrollX : undefined,
         bottom: position?.bottom ? position.bottom - window.scrollY : undefined,
+        zIndex: 99999,
```
Comment (emersion) [inline front/src/common/OSRDTooltip.tsx]: This should be in the `.osrd-tooltip` rules, which already have another `z-index`.

File: front/src/common/OSRDTooltip.tsx [hunk 2]
```diff
@@ -14,6 +16,11 @@ type OSRDTooltipProps = {
 
 const TOOLTIP_BOTTOM_MARGIN = 24;
 
+const getTopLevelLayer = (container: Element | null): Element => {
+  const topLevelLayer = container?.closest('dialog[open], [popover]:popover-open');
```
Comment (emersion) [inline front/src/common/OSRDTooltip.tsx]: This seems pretty out-of-place.

File: front/src/common/OSRDTooltip.tsx [hunk 3]
```diff
@@ -77,14 +84,15 @@ const OSRDTooltip = ({
     });
   }, [isOpen]);
 
-  return (
+  return createPortal(
```
Comment (emersion) [inline front/src/common/OSRDTooltip.tsx]: IIRC we specifically did not use `createPortal()` when designing this component because of some bad interactions with scroll containers.

Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: Do you know which interactions? It seems to work well when scrolling.

File: front/src/common/OSRDTooltip.tsx (hunk 2 above)
Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: It's a one line helper to portal in the top layer if it exists. Since it's so tiny, it did not feel like it needed to live in an outside file, and it seems reasonable for a tooltip to always be displayed on top.

File: front/src/common/OSRDTooltip.tsx (hunk 1 above)
Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: Sure!

File: front/src/common/OSRDTooltip.tsx (hunk 2 above)
Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: We could also have components pass as a prop where the tooltip should portal, or only conditionally portal based on a prop (so we would portal in the exception case but not in the round trip case).

Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: (I'm not certain about the selectors used either, perhaps we want :modal instead of dialog? Is there a better way to detect  the top layer? And should we add fullscreen too? Or perhaps we can add the tooltip to the top layer directly, without trying to target elements in it already?

> Note that the top layer is an internal browser concept and cannot be directly manipulated from code. You can target elements placed in the top layer using CSS and JavaScript, but you cannot target the top layer itself. [from [mozila](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer)]

This part is annoying =/)

File: front/src/common/OSRDTooltip.tsx (hunk 3 above)
Comment (SharglutDev) [reply front/src/common/OSRDTooltip.tsx]: Don't remember either which interactions. We had some bad effetcs for the `OSRDMenu` in the manchette but that's because the menu is always displayed.

Here for the tooltip but we scroll outside the hover zone of the "container", it disappears so I don't see the harm either.

I encountered a similar issue to display the map layers modal in the new itinerary modal (which is now a dialog, so also a top layer) and ended up using [`createPortal`](https://github.com/OpenRailAssociation/osrd/pull/13331/files#diff-b4997caafbc96d6d7f03b3ce51f97c4f3a0804bc2a8d51b41d203cb8e4c8739aR225) to do the job so I'm personaly fine with that.

File: front/src/common/OSRDTooltip.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/common/OSRDTooltip.tsx]: Agreed that the selector is not perfect. With a better granularity, we could maybe avoid setting the `z-index` of the tooltip.

Would it be better to create a css variable `--round-trips-pairing-column: 9999` in `_roundTripsModal.scss` and add (and same with -1 for the overlay)
```
.osrd-tooltip {
    z-index: calc(var(--round-trips-pairing-column) + 1);
  }
```
at the very end of `.round-trips-modal` style ?

Comment (emersion) [reply front/src/common/OSRDTooltip.tsx]: One way would be to use the [`popover` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/popover). Another way would be to stop using `<dialog>`.

**Comment by SharglutDev** [comment]
This bug is pretty annoying, are you still working on it @Synar ? :)

**Comment by Synar** [comment]
Fully reworked the pr after discussing with @emersion @SharglutDev , using popover.

File: front/src/common/OSRDTooltip.tsx (hunk 2 above)
Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: Done! ^^

File: front/src/common/OSRDTooltip.tsx (hunk 3 above)
Comment (Synar) [reply front/src/common/OSRDTooltip.tsx]: Dropped in favor of popover!

**Review by SharglutDev — COMMENTED** [review]
Looks very nice with minimal changes, good job !

Just seems like firefox has some issues with `hint` :
Image

But tested in this browser and it works great. Maybe because all use cases are with hover and not by click ?

**Comment by Synar** [comment]
Firefox converts hint to manual, which is fine with what we do too. In fact, I'm more scared of strange things happening in chrome, since hint has more built in behavior than manual : opening a hint auto close other hints (but does not close non hint popovers). This behavior should make sense for tooltips though ^^

**Review by emersion — APPROVED** [review]
Nice, thanks!
