### PR TITLE
front: fix stdcm vias

### LINKED ISSUE #7613: Vias are no longer supported on stdcm
### What happened?

When a via is added to STDCM, the simulation crashes.

### What did you expect to happen?

I'd like to be able to create simulations with vias

### How can we reproduce it (as minimally and precisely as possible)?

Go to STDCM, add a via, apply simulation. 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

front : dev 7116d4f

### PR DESCRIPTION
**Pull request by Akctarus**
closes #7613

### CODE REVIEW

File: front/src/applications/stdcm/utils/formatStdcmConfV2.ts [hunk 1]
```diff
@@ -137,9 +138,36 @@ export const checkStdcmConf = (
...
+        location = step;
+      } else if (isOperationalPoint(step)) {
+        location = { operational_point: step.operational_point };
+      } else if (isTrigramType(step)) {
+        location = { secondary_code: ch ?? null, trigram: step.trigram };
+      } else if (isUicType(step)) {
+        location = { secondary_code: ch ?? null, uic: step.uic };
+      } else {
+        location = { ...path, secondary_code: ch };
+      }
```
Comment (clarani) [inline front/src/applications/stdcm/utils/formatStdcmConfV2.ts]: Actually, you can do it more simply :) You can remove all the unwanted props from step l140 (you need to add theoreticalMargin, kp and onStopSignal) and then you can just define secondary code if the path step location has trigram or uic.
```suggestion
const secondary_code = 'trigram' in path || 'uic' in path ? ch : undefined;
```
You can also rename path by stepLocation or location

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/applications/stdcm/utils/formatStdcmConfV2.ts (hunk 1 above)
Comment (Akctarus) [reply front/src/applications/stdcm/utils/formatStdcmConfV2.ts]: Nice catch ! done

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
