### PR TITLE
front: fix-bug: set default standard allowance type to percentage instead of time

### LINKED ISSUE #3151: front: stdcm: standard allowance parameter is set to "flat time" by default, which is an invalid input for the back-end
When the STDCM tab is opened from a fresh environment and the standard allowance parameters aren't modified, the front sends a request with a standard allowance of "0 seconds". This is invalid because it's a flat time. It should be either unspecified or set to a percentage value.

The flat time option can't be manually selected anymore, but it's still the default value.

### PR DESCRIPTION
**Pull request by clarani**
Fixes #3151 

When the STDCM tab is opened from a fresh environment and the standard allowance parameters aren't modified, the front sends a request with a standard allowance of "0 seconds". This is invalid because it's a flat time. It should be either unspecified or set to a percentage value.

The flat time option can't be manually selected anymore, but it's still the default value.

I have modified the default valut to 0%.

### CODE REVIEW

File: front/src/applications/stdcm/formatStcmConf.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ export default function formatStdcmConf(
 
   if (!error) {
     const standardAllowanceType: string =
-      (osrdconf.standardStdcmAllowance?.type as string) || 'time';
+      (osrdconf.standardStdcmAllowance?.type as string) || ALLOWANCE_UNIT_TYPES.PERCENTAGE;
```
Comment (anisometropie) [inline front/src/applications/stdcm/formatStcmConf.ts:111]: why does `time` become `percentage `?

Comment (clarani) [reply front/src/applications/stdcm/formatStcmConf.ts:111]: Because the standard allowance type cannot be time, it must be either percentage or time_per_distance. That's the origin of the bug :)

Comment (anisometropie) [reply front/src/applications/stdcm/formatStcmConf.ts:111]: oh I see :)

**Review by alexandredamiron — APPROVED** [review]
