### PR TITLE
front: lmr fix intermediate op id collision

### LINKED ISSUE #10375: front: multiple intermediate OP are changed together
### What happened?

When I modify the second intermediate OP, the first intermediate OP is also modified with the same values at the same time.

### What did you expect to happen?

Each intermediate OP should be independently changed and isolated from one another.

### How can we reproduce it (as minimally and precisely as possible)?

1. Add a first intermediate OP and fill in some values
2. Add a second intermediate OP
3. Fill in some values in the second, and observe that the first one changed

See also the following video.

https://github.com/user-attachments/assets/44e6547a-7658-498d-9f24-a3b480f036b1

### On which environments the bug occurs?

Other

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

fdfd8ac

### PR DESCRIPTION
**Pull request by Wadjetz**
fix #10375

Use UUID instead of react-id-generator. The latter is a sequential ID generator with a global counter that can reset when the page is refreshed and data is restored from localStorage or the window object, potentially resulting in duplicated IDs.

- [ ] Fix tests

### CODE REVIEW

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested (you probably need to rebase)

**Review by woshilapin — APPROVED** [review]
Looks fine although, I'm pretty sure I don't understand it in the details 😄

File: front/src/utils/react-id.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { v4 as uuidV4 } from 'uuid';
+
+/**
+ * Generate a unique id for react components
+ * @returns a unique id
+ */
+export default function nextId() {
+  // return `id-${uuidV4()}`;
+  return uuidV4();
```
Comment (emersion) [inline front/src/utils/react-id.ts]: I think we can use `uuidV4()` directly in places where it makes sense, rather than introduce a wrapper function. (Note, the name "react-id" is slightly confusing, since these IDs aren't used in anything React-related.)

**Review by emersion — APPROVED** [review]
Very nice, thanks!

**Review by Maymanaf — APPROVED** [review]
LGTM for e2e tests
