### PR TITLE
front: fix editing a train add stops at timed points

### LINKED ISSUE #8291: TSV2 : Editing a train with a point with time constraint (but no stopping time) creates a 0s stopping time constraint
### What happened?

1.I created a train with a time constraint (but no stopping time constraint) in Lantenay
image
2. The train is created, and there is no stop in Lantenay (correct)
image
3. I click on "edit" to open the edition mode and then on "edit train" (without changing anything) -> The train now stops in Lantenay : a 0s stopping time was added (problem)
image

If I reopen the editition mode, I can see that a 0s stop was indeed added : 
image

### What did you expect to happen?

I expected no stop to be added

### How can we reproduce it (as minimally and precisely as possible)?

as above

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

### PR DESCRIPTION
**Pull request by clarani**
closes #8291

### CODE REVIEW

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatSchedule.ts [hunk 1]
```diff
@@ -32,9 +32,10 @@ const formatSchedule = (
         arrival: formatArrival ?? undefined,
         locked: step.locked,
         on_stop_signal: step.onStopSignal,
-        stop_for: isNaN(Number(step.stopFor))
-          ? undefined
-          : formatDurationAsISO8601(Number(step.stopFor)),
+        stop_for:
+          isNil(step.stopFor) || isNaN(Number(step.stopFor))
```
Comment (theocrsb) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatSchedule.ts:36]: Maybe you can just add this condition ?

```suggestion
          !step.stopFor
```

Comment (Uriel-Sautron) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatSchedule.ts:36]: I think we should keep `isNaN`

Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatSchedule.ts:36]: I think we should keep the isNan, it's to prevent bad behaviours from the user (if he tries to enter 'abc' in the cell for instance)

**Comment by clarani** [comment]
I added some details in the commit message :+1:

**Review by theocrsb — APPROVED** [review]
LGTM and tested !

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested

**Review by Uriel-Sautron — APPROVED** [review]
LGTM, tested !!!
