### PR TITLE
Fix track projection for train schedule :timer_clock: 

### LINKED ISSUE #14857: STD is empty on scenario loading
### What happened?

The STD of this scenario is (sometimes, but often) empty. Refreshing the page seems not to help

Also, the x axis is not defined

https://rec-osrd.reseau.sncf.fr/operational-studies/projects/128/studies/1024/scenarios/2413?selected_train=paced_16770156&projection=paced_16770156

https://github.com/user-attachments/assets/2f7c1f3f-9268-445d-8467-564bbff8f9b3

### What did you expect to happen?

Project the trains and have the axis defined

### How can we reproduce it (as minimally and precisely as possible)?

open the above scenario

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 2945256

### PR DESCRIPTION
**Pull request by flomonster**
When train schedule does not respect times we can project them as not simulated.

Fix: https://github.com/OpenRailAssociation/osrd/issues/14857

> [!NOTE]
> Commits can be reviewed independently. 

> [!IMPORTANT]
> For trains that did not have a specified time at the end of path it was easier to complete using the real simulation curve instead of cutting it (like we do in non-simulated). I based this decision on the fact that simulax should display as much information as possible.
> ~The resulted curve is a mix of simulated and non simulated.~ -> We have segment also at the end but using the simulation to have the time.
> If validated we could do the exact same thing in inter-op.
> @maelysLeratRosso @Tguisnet What do you think? 

--------------

Examples: 

- First curve does not have schedule points (so it "respects" its schedule).
- Second curve has two schedule points, middle one can not be respected, last one is fine.
- Third curve is like the second one but without the last schedule point.

**Before:**

We had nothing when projecting a train that does not respect times.

**After:**

We project the train as "non simulated".

Sans titre
Sans titre
Sans titre

> [!NOTE]
> As we can see in op projection the result still weird, this is because simulax was not yet implemented for this mode.
> @hhirtz @ppitou I don't know if this is a work in progress or if we need to implement it (in a follow-up PR).

### CODE REVIEW

**Comment by hhirtz** [comment]
So editoast needs to fake space-time curves for invalid trains? I thought it was on the front to display such trains correctly. @Math-R what do you think?

**Comment by flomonster** [comment]
Note: Time information in the table won't match the space time diagram.

File: editoast/src/views/projection.rs [hunk 1]
```diff
@@ -121,6 +119,30 @@ impl SpaceTimeCurve {
...
         )
     }
+
+    /// Find the time at a given position
+    /// Panics if the curve is empty
+    fn linear_interpolate_position(&self, position: u64) -> u64 {
+        assert!(!self.is_empty(), "Space time curve is empty");
+        if position > self.positions[self.positions.len() - 1] {
+            // If the position is greater than the last position, return the last time
+            return self.positions[self.times.len() - 1];
```
Comment (hhirtz) [inline editoast/src/views/projection.rs]:
```suggestion
            return self.times[self.times.len() - 1];
```

Comment (flomonster) [reply editoast/src/views/projection.rs]: Good catch I made the linear_interpolate function generic. So it's fixed :smile:

File: editoast/src/views/projection.rs [hunk 2]
```diff
@@ -98,28 +96,39 @@ impl SpaceTimeCurve {
...
 
-    /// Find the position at a given time
-    /// Panics if the curve is empty
-    fn linear_interpolate(&self, time: u64) -> u64 {
-        assert!(!self.is_empty(), "Space time curve is empty");
-        if time > self.times[self.times.len() - 1] {
-            // If the time is greater than the last time, return the last position
-            return self.positions[self.positions.len() - 1];
+    /// Generic linear interpolation function
+    /// Panics if the curve is empty or if x and y have different lengths
```
Comment (hhirtz) [inline editoast/src/views/projection.rs:105]: froze for a minute trying to find what this function entails

```suggestion
    /// Generic linear interpolation function
    /// For a segmented curve going through the points `(x[i],y[i])` find its Y
    /// coordinate at the given X coordinate `value`. If `value` is out of bounds
    /// return the first or the last point of the curve.
    /// Expects `x` to be sorted.
    /// Panics if the curve is empty or if x and y have different lengths
```

File: editoast/src/views/projection.rs [hunk 3]
```diff
@@ -98,28 +96,39 @@ impl SpaceTimeCurve {
...
+    fn linear_interpolate(x: &[u64], y: &[u64], value: u64) -> u64 {
+        assert!(
+            x.len() == y.len(),
+            "Curve x and y must have the same length"
+        );
```
Comment (hhirtz) [inline editoast/src/views/projection.rs]: nit

```suggestion
        assert_eq!(
            x.len(), y.len(),
            "Curve x and y must have the same length"
        );
```

File: editoast/src/views/projection.rs [hunk 4]
```diff
@@ -98,28 +96,39 @@ impl SpaceTimeCurve {
...
+        assert!(!x.is_empty(), "Curve can't be empty");
+
+        if value > x[x.len() - 1] {
+            // If the value is greater than the last x, return the last y
+            return y[y.len() - 1];
         }
-        // Find the index of the first time greater than or equal to the given time
-        let index = find_index_upper(&self.times, time);
+        // Find the index of the first x greater than or equal to the given value
+        let index = find_index_upper(x, value);
```
Comment (hhirtz) [inline editoast/src/views/projection.rs:115]: It's not the first `x` greater than.., it's the last `x` equal to the first element greater than or equal to `value`. i was wondering if it's what causing tests to fail or if it caused the STD to be printed wrong but it doesn't seem to be the case...

**Review by hhirtz — APPROVED** [review]
seems to work fine on my end, i don't know why tests fail though

so the space time diagram only shows the curve from the simulation at the end, not at the begining i guess?

screen-20260127151914

above the leftmost train's simulation can surely respect the times on the first half but is displayed as input (for obvious reasons looking at the code but i was wondering with regards to the mockups)

File: editoast/src/views/projection.rs (hunk 2 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:105]: Done [here](https://github.com/OpenRailAssociation/osrd/pull/14863/changes/e62f0d65c3e8a6d0ee7789e020602e69325ba0a5)

File: editoast/src/views/projection.rs (hunk 3 above)
Comment (flomonster) [reply editoast/src/views/projection.rs]: Done [here](https://github.com/OpenRailAssociation/osrd/pull/14863/changes/e62f0d65c3e8a6d0ee7789e020602e69325ba0a5)

File: editoast/src/views/projection.rs (hunk 4 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:115]: Done [here](https://github.com/OpenRailAssociation/osrd/pull/14863/changes/e62f0d65c3e8a6d0ee7789e020602e69325ba0a5)

I'm investigating the test issue.

**Review by Wadjetz — APPROVED** [review]
lgtm

**Comment by hhirtz** [comment]
Fixed the operational point projection in this PR: https://github.com/OpenRailAssociation/osrd/pull/14928

**Review by hhirtz — COMMENTED** [review]
This comment should be also removed

https://github.com/OpenRailAssociation/osrd/blob/ce351cdf5e9665ebcacb7d1a8c2da415a1c053ad/editoast/src/views/timetable/paced_train.rs#L733

File: editoast/src/views/projection.rs [hunk 5]
```diff
@@ -777,6 +767,52 @@ pub fn compute_projected_train_path_op_without_simulation<T: TrainScheduleLike>(
...
+/// These trains have path and simulation information that we can use.
+fn extract_curve_for_invalid_train_with_sim<T: TrainScheduleLike>(
+    train_schedule: &T,
+    sim: &SimulationResponseSuccess,
+    path: &PathfindingResultSuccess,
+) -> SpaceTimeCurve {
+    let mut positions = vec![0];
+    let mut times = vec![0];
+
+    for (path_item, path_step_position) in
```
Comment (woshilapin) [inline editoast/src/views/projection.rs]: nitpick: for name coherence


```suggestion
    for (path_item, path_item_position) in
```

**Comment by flomonster** [comment]
> This comment should be also removed
> 
> https://github.com/OpenRailAssociation/osrd/blob/ce351cdf5e9665ebcacb7d1a8c2da415a1c053ad/editoast/src/views/timetable/paced_train.rs#L733

Actually, the documentation of this endpoint was completely off. I fixed it.

File: editoast/src/views/projection.rs [hunk 6]
```diff
@@ -777,6 +767,52 @@ pub fn compute_projected_train_path_op_without_simulation<T: TrainScheduleLike>(
...
+
+    let last_scheduled_position = *positions.last().unwrap();
+    if last_scheduled_position != path.length {
+        // Complete with real simulation information
+        let sim_curve = SpaceTimeCurve {
+            positions: sim.final_output.report_train.positions.clone(),
+            times: sim.final_output.report_train.times.clone(),
+        };
+        let last_sim_time = sim_curve.linear_interpolate_position(last_scheduled_position);
+        let diff_time = *times.last().unwrap() as i64 - last_sim_time as i64;
```
Comment (woshilapin) [inline editoast/src/views/projection.rs]: Might need a comment about we are trying to do here (offseting the real simulation curve). Maybe an ASCII art 😅

File: editoast/src/views/projection.rs [hunk 7]
```diff
@@ -777,6 +767,52 @@ pub fn compute_projected_train_path_op_without_simulation<T: TrainScheduleLike>(
...
+        sim_curve
+            .positions
+            .into_iter()
+            .enumerate()
+            .filter(|(_, position)| *position > last_scheduled_position)
+            .for_each(|(index, position)| {
+                positions.push(position);
+                times.push((sim_curve.times[index] as i64 + diff_time) as u64);
+            });
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:831]: minor: You should be able to keep the index of the latest inserted position to avoid iterating on the entire list of positions and remove the `.filter` by doing something like

```rust
sim_curve.positions[last_position_index..].iter()
```

Not entirely sure that it’s worth it, it might clutter the code a bit more to keep the index around. I’ll let you resolve either way.

File: editoast/src/views/projection.rs [hunk 8]
```diff
@@ -777,6 +767,52 @@ pub fn compute_projected_train_path_op_without_simulation<T: TrainScheduleLike>(
...
+            .find(|schedule| schedule.at == path_item.id)
+            .and_then(|schedule| schedule.arrival)
+        {
+            positions.push(*path_step_position);
+            times.push(arrival.num_milliseconds() as u64);
+        }
+    }
+
+    let last_scheduled_position = *positions.last().unwrap();
+    if last_scheduled_position != path.length {
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:812]: I’m not entirely convince of the advantage of keeping the entire curve of the simulation on the last part of the rain. The train is invalid so showing this level of detail feels weird.

Instead, I would have used the simulation to estimate only ONE point: the estimated arrival at the last path item, considering the time delay. It would draw a straight line in the Space-Time-Diagram. So it’s basically almost the same code that you have, but instead of adding a list of points in this `if` branch, I would only add the latest of these points.

I heard this particular proposition might already have been discussed with @Tguisnet, but I’d be curious to understand what led to reject this solution?

File: editoast/src/views/projection.rs (hunk 7 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:831]: `index` is in `sim.final_output.report_train.positions`, while inserted positions are from `path.path_item_positions`. Since positions are sorted we could use a binary search (it's a bunch of extra code even with the functions from std because we need the strict inequality), but i don't think it possible to know the first value of `index` (?)

File: editoast/src/views/projection.rs [hunk 9]
```diff
@@ -777,6 +768,65 @@ pub fn compute_projected_train_path_op_without_simulation<T: TrainScheduleLike>(
...
+        // Complete with real simulation information
+        let sim_curve = SpaceTimeCurve {
+            positions: sim.final_output.report_train.positions.clone(),
+            times: sim.final_output.report_train.times.clone(),
+        };
+        let last_sim_time = sim_curve.linear_interpolate_position(last_scheduled_position);
+        // Can't use times.last() because of possible stops at the end
+        let diff_time = last_scheduled_time as i64 - last_sim_time as i64;
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:819]: Should we also take into account the duration of the optional `stop_for` here?

File: editoast/src/views/projection.rs (hunk 7 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:831]: Indeed, I will make a binary search since I already have the function here. it's not much work and can make the iterator more readable.

File: editoast/src/views/projection.rs (hunk 8 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:812]: @Tguisnet is not available today, but we have already discussed this behavior and he agreed with it. The problem with taking the last simulated point into account is that we lose the stop information. We could add all the stops and the last point, but that would make the code more complex.

We based our decision on the idea that “the user wants the most accurate information possible” (even if we're not very good at it yet).

File: editoast/src/views/projection.rs (hunk 6 above)
Comment (flomonster) [reply editoast/src/views/projection.rs]: I tried to make some ASCII art, but it wasn't very successful (note that I'm not very good at it 😅).

File: editoast/src/views/projection.rs [hunk 10]
```diff
@@ -787,26 +837,30 @@ pub async fn extract_train_details<T: TrainScheduleLike>(
...
         .zip(train_schedules)
         .map(|((sim, pathfinding_result), train_schedule)| {
-            let simulation::Response::Success(sim) = sim.as_ref() else {
+            let PathfindingResult::Success(pathfinding_result) = pathfinding_result.as_ref() else {
                 return None;
             };
-            let PathfindingResult::Success(pathfinding_result) = pathfinding_result.as_ref() else {
+            let simulation::Response::Success(sim) = sim.as_ref() else {
                 return None;
             };
```
Comment (hhirtz) [inline editoast/src/views/projection.rs:851]: Sorry for this late comment but in the case where the simulation fails we still want to display the input curve? or is this only for the operational point projection?

With this core patch to make all simulations fail:

```diff
diff --git a/core/src/main/kotlin/fr/sncf/osrd/api/standalone_sim/SimulationEndpoint.kt b/core/src/main/kotlin/fr/sncf/osrd/api/standalone_sim/SimulationEndpoint.kt
index 14f1f6b33e..185f6be3b2 100644
--- a/core/src/main/kotlin/fr/sncf/osrd/api/standalone_sim/SimulationEndpoint.kt
+++ b/core/src/main/kotlin/fr/sncf/osrd/api/standalone_sim/SimulationEndpoint.kt
@@ -8,6 +8,7 @@
 import fr.sncf.osrd.cli.RsWithBody
 import fr.sncf.osrd.cli.RsWithStatus
 import fr.sncf.osrd.cli.Take
+import fr.sncf.osrd.reporting.exceptions.ErrorType
 import fr.sncf.osrd.reporting.exceptions.OSRDError
 import fr.sncf.osrd.standalone_sim.runStandaloneSimulation
 import fr.sncf.osrd.utils.*
@@ -42,6 +43,7 @@
 
     fun run(request: SimulationRequest): Response {
         try {
+            throw OSRDError(ErrorType.ImpossibleSimulationError)
             // load infra
             val infra = infraManager.getInfra(request.infra, request.expectedVersion)

```

and running the app with

```
docker compose -f docker-compose.yml -f docker/docker-compose.host.yml -f docker/docker-compose.single-worker.yml up --scale core=0 -d
cd ./core && ALL_INFRA=true ./gradlew run --args='worker --editoast-url http://localhost:8090/'
cd ./editoast && EDITOAST_CORE_SINGLE_WORKER=true cargo run -- runserver
```

then editoast rightfully returns "simulation fail" errors on both `/simulation` and `/simulation_summary` endpoints, but then the front hides the curves of all trains...

Since we want trains for which simulation fails to have their input displayed[^1], does that mean editoast has to return no errors on those endpoints?? feels really weird

[^1]: https://github.com/osrd-project/osrd-confidential/issues/1263#:~:text=Exemple%20du%20workflow%20non%20calcul

Comment (flomonster) [reply editoast/src/views/projection.rs:851]: ### For the track projection mode

- If: Trains that does not have pathfinding 
  - They're hidden cause it's impossible to do the projection
- Else if: Trains that does not have a simulation (really rare cases)
  - We could project them as "input mode". Out of scope for now
- Else if: Trains does not honor their schedule:
  - We project them as "input mode" with the end of the simulation if last point not scheduled.
- Else:
  - We project using the simulation information
 
> [!NOTE]
> The "Input mode" is not avaible in the frontend for this type of projection. 

### For the operational point projection

- If: Trains that does not have pathfinding
  - Projection using scheduled points only
- Else if: Trains that does not have a simulation (really rare cases)
  - Projection using scheduled points only
  - This projection can be forced by the frontend when using "Input Mode"
- Else if: Trains does not honor their schedule:
  - We project them as "input mode" with the end of the simulation if last point not scheduled.
- Else:
  - We project using the simulation information

----------


Overall this logic is not transparent when reading the code, we could use a refacto here :grimacing:.

File: editoast/src/views/projection.rs (hunk 9 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:819]: `last_sim_time` returns the time before shutdown, which is why we need to obtain `last_scheduled_time` before shutdown so that the difference between the two is consistent.

**Review by hhirtz — APPROVED** [review]
can confirm the track projection still works 👍

File: editoast/src/views/projection.rs (hunk 7 above)
Comment (woshilapin) [reply editoast/src/views/projection.rs:831]: Can `find_index_upper` be used?

Comment (woshilapin) [reply editoast/src/views/projection.rs:831]: Ah, my comment is a bit late, you already used it!

File: editoast/src/views/projection.rs (hunk 8 above)
Comment (woshilapin) [reply editoast/src/views/projection.rs:812]: Finally, after discussion, we settled on keeping only a straight line.

**Review by woshilapin — APPROVED** [review]
