### PR TITLE
front: fix power restrictions get reset on editing a train

### LINKED ISSUE #10494: Power restrictions get reset on first opening of train schedule
### What happened?

When a train has some power restrictions set, when you hard reload the page (ctrl + R) and you edit it, without changing anything the power restrictions are reset

https://github.com/user-attachments/assets/f146c40d-069a-4089-9d4e-16f2dba34d4c

### What did you expect to happen?

I expect the power restrictions not be reset if we didn't change any parameter of the path

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train with power restrictions
2. Hard reload your browser (I guess it's emptying the cache)
3. Click on the edit button for this train
4. Witness the toast

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c9066aa

### PR DESCRIPTION
**Pull request by clarani**
closes #10494 

~After a hard refresh, the pathfinding was relaunched by the useEffect depending on the rolling stock in usePathfinding. Indeed, the trick with `isInitialized` did not work because it was set to true before the fetch of the rolling stock. Thus, when the rolling stock was received, the useEffect was triggered and the power restrictions reset.~

~Now, the hook usePathfinding is considered initialized only if there is no rollingStock selected or if the selected rolling stock has been already received.~

See commits

### CODE REVIEW

**Review by RomainValls — APPROVED** [review]
LGTM, tested ✅

**Review by emersion — COMMENTED** [review]
Hmm, I'm not a fan of adding even more workarounds to the current workaround…

Why does the workaround exist in the first place? What are we trying to achieve with `isInitialized`?

If we want to launch pathfinding when the hook is mounted and when the infra state is cached and when the rolling stock is loaded, I don't think we need this `isInitialized` state?

Or do we want a different behavior?

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx [hunk 1]
```diff
@@ -86,15 +81,14 @@ const ManageTrainSchedule = ({ trainIdToEdit }: ManageTrainScheduleProps) => {
...
-
-  const onSelectRollingStock = useCallback((_rollingStockId: number, comfort: Comfort) => {
-    dispatch(updateRollingStockID(_rollingStockId));
-    dispatch(updateRollingStockComfort(comfort));
-  }, []);
+  const onSelectRollingStock = useCallback(
+    (_rollingStockId: number, comfort: Comfort) => {
+      dispatch(updateRollingStockID(_rollingStockId));
+      dispatch(updateRollingStockComfort(comfort));
+      launchPathfinding(pathSteps);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Hm, `dispatch()` runs asynchronously so `launchPathfinding()` might get called before the rolling stock ID has actually been updated in the store… We might want to either pass a rolling stock ID to `launchPathfinding()` (the same way we pass `pathSteps`?), or `await` these two `dispatch()` calls?

Comment (clarani) [reply front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Done :white_check_mark:

**Review by emersion — APPROVED** [review]
LGTM :)
