### PR TITLE
front: ensures the edit only applies to a specific occurrence

### LINKED ISSUE #16033: New table : after editing an occurrence of a service, the paced train and the other occurrences show the same update (before refresh)
### What happened?

I use the new table here 
- I have a service with several occurrences (no exception)
- I change the stopping time at one point of one of my exceptions (let's say from 1min to 5min)
- When I go to the table of the paced train or of one of the other occurrences, et 5min stop is displayed. Only a 1min stop should be displayed, since I only updated an occurrence.
- When I refresh, everything becomes normal : 5min stop on the occurrence I edited, 1min on the other occurrences and on the paced train.

### What did you expect to happen?

I expect to have the edition only on the occurrence I edited

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

5df99d8

### PR DESCRIPTION
**Pull request by Akctarus**
closes #16033

### CODE REVIEW

File: front/src/modules/timesStops/TimesStopsOutput.tsx [hunk 1]
```diff
@@ -179,7 +186,11 @@ const TimesStopsOutput = ({
     arrival: Date | null,
     propagationMode: PropagationMode
   ) => {
-    const singleEdit: PendingEdit = { rowId: row.id, field: 'requestedArrival', value: arrival };
+    const singleEdit: PendingEdit = {
+      rowId: row.id,
+      field: 'requestedArrival',
+      value: arrival,
+    };
```
Comment (Signez) [inline front/src/modules/timesStops/TimesStopsOutput.tsx]: Nit: to reduce the diff of your pull request, feel free to revert this part of your change that is a purely syntactic change (adding a comma after the last property "pin" the whole object as one that should formatted on multiple lines).

**Review by Signez — APPROVED** [review]
LGTM and makes sense 👍

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅
