### PR TITLE
Fix editoast batch simulation reducing DB queries

### LINKED ISSUE #7867: stdcm: DieselError connection closed on a STDCM request with a day of circulations
### What happened?

I get a 
```json
{"status":500,"type":"editoast:DieselError","context":{},"message":"connection closed"}
```
when running an STDCM request on a timetable with 2000 trains on the rec-osrd.reseau.sncf.fr environment

### What did you expect to happen?

I expect it to work properly

### How can we reproduce it (as minimally and precisely as possible)?

1. create a stdcm requests between LYD and MAS on a basic timetable with 1900 trains

### What operating system, browser and environment are you using?

- **Browser**: Firefox 

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

### LINKED ISSUE #7907: editoast: fail to answer livenessProbe checks in less than 10s on a big scenario and get killed
### What happened?

Everything is in the title

### What did you expect to happen?

Editoast to answer queries in less than the liveness probe check and avoid being killed for such reason
image

### How can we reproduce it (as minimally and precisely as possible)?

1. [scenario](https://rec-osrd.reseau.sncf.fr/operational-studies/projects/4/studies/50/scenarios/131)

### What operating system, browser and environment are you using?

- **Browser**: Firefox 

### OSRD version (top right corner `Account` button > `Informations`)

c6498a4

### PR DESCRIPTION
**Pull request by flomonster**
We reduce the number of queries executed by the batch simulation function. 
Previously, for `N` trains, we executed `Nx4` postgres queries. 
Now we run ~4 batch queries.

close #7867 

close #7907

> [!NOTE]
> In my test in local the health check takes no more than 500ms to respond, compared with 6s before 

## Benchmark

I tested with a timetable of 823 trains

### Before

**Summary**:

- No cache: 20.96s
- Redis cache: 1.66s

**Project path**:

- No cache: 27.25s
- Redis cache: 3.69s

### After

**Summary**:

- No cache: 22s
- Redis cache: 964ms

**Project path**:

- No cache: 26s
- Redis cache: 3s

### CODE REVIEW

File: editoast/src/views/v2/train_schedule/cache.rs [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+        self
+    }
+
+    /// Returns the cached value given a timetable ID.
+    /// If the value is not cached, it will retrieve it and cache it.
+    pub async fn get_timetable(
+        &self,
+        id: i64,
+        conn: &mut DbConnection,
+    ) -> Result<Option<Timetable>> {
```
Comment (woshilapin) [inline editoast/src/views/v2/train_schedule/cache.rs]: A cache, taking a DB connection as input, looks like a weird pattern. Maybe `Cache` is not the right term, maybe it's more of a `Proxy`.

File: editoast/src/views/v2/train_schedule/cache.rs [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    }
+
+    /// Initialize the cache with a list of timetables
+    pub fn init_timetables(mut self, timetables: &[Timetable]) -> Self {
+        self.timetables = timetables
+            .iter()
+            .map(|timetable| (timetable.id, timetable.clone()))
+            .collect();
+        self
+    }
```
Comment (woshilapin) [inline editoast/src/views/v2/train_schedule/cache.rs]: How about a unique constructor that takes both list at once? This would replace `TrainScheduleCache::default().init_rolling_stocks(&rs).init_timetables(&tt)` with `TrainScheduleCache::new(&rs, &tt)`?

**Review by woshilapin — APPROVED** [review]
