### PR TITLE
front: fix translation of the GET Linear axis

### LINKED ISSUE #14930: Missing translation for linear space axis in STD component
### What happened?

Image

### What did you expect to happen?

translate "Linéaire"

### How can we reproduce it (as minimally and precisely as possible)?

-

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by ppitou**
Closes #14930

### CODE REVIEW

File: front/ui/ui-charts/src/manchette/components/Manchette.tsx [hunk 1]
```diff
@@ -102,7 +104,7 @@ const Manchette = ({
               className={cx({ 'text-grey-30': isProportional })}
               data-testid="linear-mode-button"
             >
-              Linéaire
+              {translations?.linearMode}
```
Comment (emersion) [inline front/ui/ui-charts/src/manchette/components/Manchette.tsx]: Other osrd-ui components provide default translations when the user doesn't provide them. Here the HTML element will end up being empty. Shouldn't we add `|| 'Linear'`?

File: front/ui/ui-charts/src/manchette/components/Manchette.tsx [hunk 2]
```diff
@@ -102,7 +104,7 @@ const Manchette = ({
               className={cx({ 'text-grey-30': isProportional })}
               data-testid="linear-mode-button"
             >
-              Linéaire
+              {translations?.linearMode} || 'Linear'
```
Comment (emersion) [inline front/ui/ui-charts/src/manchette/components/Manchette.tsx]: This will print the literal `|| 'Linear'` string to the user, without being interpreted as JavaScript. It needs to be inside the braces to be interpreted by JS.

**Review by emersion — APPROVED** [review]

**Comment by Pivouane** [comment]
LGTM 🚀 🍼

**Review by Pivouane — APPROVED** [review]
