### PR TITLE
editoast: fix projection with empty secondary_code

### LINKED ISSUE #14307: Project path operational point does not work properly
### What happened?

I have a train Paris -> Avignon. It takes only a part of the space time diagram which not right.

Image

### What did you expect to happen?

Something similar of the track projection.

Image

### How can we reproduce it (as minimally and precisely as possible)?

1. Use this timetable: [timetable.json](https://github.com/user-attachments/files/23963845/lol.json)
2. Try operational point projection

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

371393a60817f99733a66cdbf3f22302dc36296a

### PR DESCRIPTION
**Pull request by aschantraine**
Refactors how operational points are filtered by their secondary codes in the /project_path_op endpoint.

This change ensures deterministic behavior when filtering operational points:

- When `secondary_code` is null, it now matches only operational points with `extensions.sncf` being null
- When `secondary_code` has a value, it matches operational points where `extensions.sncf.ch` equals that value

This corrects the previous non-deterministic behavior where a null secondary_code could match any operational point with SNCF extensions, leading to random selection among multiple candidates.

Note: To fully ensure deterministic behavior across the infrastructure, we should enforce that the tuple `(operational_point, ch)` is unique within an infra (including the case where ch is null).

### CODE REVIEW

File: editoast/schemas/src/train_schedule/path_item.rs [hunk 1]
```diff
@@ -1,11 +1,21 @@
...
 use crate::primitives::NonBlankString;
 use serde::Deserialize;
+use serde::Deserializer;
 use serde::Serialize;
 use utoipa::ToSchema;
 
 use crate::infra::TrackOffset;
 
+/// Deserialize an Option<String>, treating empty strings as None
+fn deserialize_empty_as_none<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
```
Comment (emersion) [inline editoast/schemas/src/train_schedule/path_item.rs]: Do we really want to conflate no secondary codes with empty secondary codes? What is the motivation for this new behavior?

Comment (aschantraine) [reply editoast/schemas/src/train_schedule/path_item.rs]: I have modified the behavior: now, a null secondary_code matches with extension.sncf being null, and an empty string secondary_code ("") matches with extension.sncf.ch equal to "" so we don't need to do that anymore.

File: editoast/src/views/path/operational_point_cache.rs [hunk 2]
```diff
@@ -412,19 +402,19 @@ pub async fn retrieve_op_from_ids(
...
 
-/// Filter operational points by secondary code
-/// If the secondary code is not provided, the original list is returned
+/// Filter operational points by secondary code to return one unique OP.
+/// If secondary_code is None, filters for OPs without sncf extensions.
+/// If secondary_code is Some, filters for OPs matching that secondary code.
 fn secondary_code_filter<'a>(
     secondary_code: Option<&String>,
     ops: Vec<&'a OperationalPointModel>,
-) -> Vec<&'a OperationalPointModel> {
```
Comment (woshilapin) [inline editoast/src/views/path/operational_point_cache.rs]: I find the change of API really weird.

Before, we were giving a `Vec` to a filter’s function, and were getting back a `Vec`: I find this rather logical, expected.

Now, we give a `Vec` and get only one value or none in returns: I don’t know how to interpret this API.

And when I read the implementation, I’m not sure that I can make sense of the first `match` arm: why returning only the first element on a `filter` method.

Wild idea (because, at this point, I’m sure I don’t have the entire problem you’re trying to solve and there is probably a good reason you ended up with this design): what if `Option` is not what you need? What if you need a new `enum` like the following (I’m brainstorming here, so please, the names are probably bad, maybe there is something else better, etc.):

```rust
enum OperationalPoints<'o> {
    Many(Vec<&'a OperationalPointModel>),
    Unique(&'a OperationalPointModel),
    None
}
```

Available to discuss it.

File: editoast/src/views/path/operational_point_cache.rs [hunk 3]
```diff
@@ -412,19 +402,19 @@ pub async fn retrieve_op_from_ids(
...
-    if let Some(secondary_code) = secondary_code {
-        ops.into_iter()
-            .filter(|op| &op.extensions.sncf.as_ref().unwrap().ch == secondary_code)
-            .collect()
-    } else {
-        ops
-    }
+) -> Option<&'a OperationalPointModel> {
+    ops.into_iter()
+        .find(|op| match (secondary_code, &op.extensions.sncf) {
```
Comment (emersion) [inline editoast/src/views/path/operational_point_cache.rs]: Nit: `&secondary_code == &op.extensions.sncf` doesn't work here?

File: editoast/src/views/path/operational_point_cache.rs (hunk 2 above)
Comment (aschantraine) [reply editoast/src/views/path/operational_point_cache.rs]: The (operational_point, ch) tuple is supposed to be unique, so this function should not find more than one result, since we changed the behavior for a null secondary_code. As discussed, I’ve kept the logic as is, but I’ve added a comment and renamed the function to make it more explicit.

File: editoast/src/views/path/operational_point_cache.rs (hunk 3 above)
Comment (aschantraine) [reply editoast/src/views/path/operational_point_cache.rs]: Done

**Review by woshilapin — APPROVED** [review]
