### PR TITLE
front: fix map marker offset

### LINKED ISSUE #9633: Visual offset between the pointers and the track on the map
### What happened?

The pins are above the track with a not-negligeable distance
Image

### What did you expect to happen?

They should stick to the tracks.

### How can we reproduce it (as minimally and precisely as possible)?

1. Get a train in operationnal studies
2. Scroll to the map on the result pages

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

e9f3b96

### PR DESCRIPTION
**Pull request by emersion**
Set the `offset` prop to define the image "hotspot" (ie, pixel coordinate where the sign is planted on).

Closes: https://github.com/OpenRailAssociation/osrd/issues/9633

### CODE REVIEW

File: front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx [hunk 1]
```diff
@@ -38,18 +38,18 @@ export default function RenderItinerary({
 
   return (
     <Source type="geojson" data={geojsonPath}>
-      <Marker longitude={originLongitude} latitude={originLatitude} anchor="bottom">
+      <Marker longitude={originLongitude} latitude={originLatitude} anchor="bottom" offset={[0, 8]}>
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx]: Note, I've duplicated the offset 3 times because there's no real reason why these all need to match up (ie, they are the same "by chance"). If you prefer to store the offset in a `const` or something, that's fine by me as well.

**Review by Caracol3 — APPROVED** [review]
lgtm (tested)

File: front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx (hunk 1 above)
Comment (kmer2016) [reply front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx]: Good work! Since offset [0, 8]  is used to adjust visual alignment with the path, it might seem logical to extract it in a const like `const markerAlignmentOffset = [0, 8];`. However, if these offsets could diverge in the future (e.g., specific adjustments for start vs. intermediate points), keeping them separate as they are might actually make sense.

Comment (emersion) [reply front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx]: So, what is your preference?

Comment (kmer2016) [reply front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx]: store the offset in a const

Comment (emersion) [reply front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx]: Done. Had to explicitly make the const a `[number, number]` other TypeScript treats it as a `number[]`.

File: front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx
Comment (SharglutDev) [inline front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx:1]: Should we pass these consts outside of the function ? (to avoid redefine them for when we zoom for example)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested. Feel free to solve the comment whether you fix it or not :)

File: front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx
Comment (emersion) [reply front/src/modules/simulationResult/components/SimulationResultsMap/RenderItinerary.tsx:1]: It shouldn't make any difference, and some other consts were there already.
