### PR TITLE
editoast: fix stdcm types

### LINKED ISSUE #5546: editoast: types for stdcm are not compatible with front and core definitions
### What happened?

Some fields in editoast stdcm objects (STDCMCoreRequest mainly) are nullable when they shouldn't, or not nullable when they should. Check front and model in core (STDCMRequest.java).
- margin_after (should be nullable)
- margin_before (should be nullable)
- standard_allowance (should be nullable)
- maximum_run_time (should not be nullable -> update comment in core STDCMRequest.java, should not have a default value)

:warning: this bug blocks the adding of placeholer in stdcm inputs in front (#5221)

### What did you expect to happen?

Types should be the same in all the services

### How can we reproduce it (as minimally and precisely as possible)?

Read code

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

a6d0b364

### PR DESCRIPTION
**Pull request by clarani**
- make margin_before, magin_after and standard_allowance nullable
- make maximum_run_time not nullable
+ fix a comment in core

closes #5546

### CODE REVIEW

**Review by eckter — APPROVED** [review]

File: editoast/src/core/stdcm.rs [hunk 1]
```diff
@@ -23,12 +23,14 @@ pub struct STDCMCoreRequest {
...
     pub maximum_departure_delay: Option<f64>,
-    #[serde(skip_serializing_if = "Option::is_none")]
-    pub maximum_run_time: Option<f64>,
+    pub maximum_run_time: f64,
     pub speed_limit_tags: Option<String>,
-    pub margin_before: f64,
-    pub margin_after: f64,
-    pub standard_allowance: AllowanceValue,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub margin_before: Option<f64>,
```
Comment (flomonster) [inline editoast/src/core/stdcm.rs]:
```suggestion
    #[serde(default)]  // I guess we expect 0 as default value (should check with core)
    pub margin_before: f64,
```

We also need to update the openapi.

**Review by flomonster — APPROVED** [review]
LGTM (review back only). Just one small comment.
