### PR TITLE
editoast: fix light rolling stock order

### LINKED ISSUE #5376: editoast: paginated results for /light_rolling_stock/ have duplicates and are missing some rolling stocks
### What happened?

After loading some rolling stocks, I noticed one was missing from the /light_rolling_stock/ results. There are duplicates as well.

looks normal up to page 11

page 11
251 8500P100
252 9200
253 9600UM
254 9600US
255 9700REV etc.

then weirdness happens

page 12
44 1Z84506
401 Z215001
235 67200UM
82 2Z83506
119 1TGVOSE etc.

### What did you expect to happen?

I expect all rolling stocks to be listed, possibly in order.

### How can we reproduce it (as minimally and precisely as possible)?

1. load some rolling stocks (from a dump?)
2. start editoast
3. query /light_rolling_stock/ repeatedly, starting from page 1 (default size is 25)
4. look at listed rolling stock and their ids

### What operating system, browser and environment are you using?

WSL (Ubuntu)

### OSRD version (top right corner `Account` button > `Informations`)

commit a6b9322ea5408b7b54f444888771caceb0041d43

### PR DESCRIPTION
**Pull request by ppitou**
closes #5376

### CODE REVIEW

File: editoast/src/schema/rolling_stock/light_rolling_stock.rs [hunk 1]
```diff
@@ -51,11 +51,12 @@ pub struct LightRollingStock {
     #[diesel(sql_type = Jsonb)]
     pub energy_sources: DieselJson<Vec<EnergySource>>,
     #[serde(skip_serializing)]
+    #[serde(skip_deserializing)]
```
Comment (leovalais) [inline editoast/src/schema/rolling_stock/light_rolling_stock.rs]:
```suggestion
    #[serde(skip)]
```

File: editoast/src/views/light_rolling_stocks.rs [hunk 2]
```diff
@@ -89,4 +91,35 @@ mod tests {
...
+
+    #[rstest]
+    async fn list_light_rolling_stock_increasing_ids(){
+        let mut app = create_test_service().await;
+        let req = TestRequest::get()
+            .uri("/light_rolling_stock/")
+            .to_request();
+        let response: PaginatedResponse<LightRollingStockWithLiveries> = call_and_read_body_json(&mut app, req).await;
+        let count = response.count;
+        let uri = format!("{}{}","/light_rolling_stock/?page_size=",count.to_string());
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs]:
```suggestion
        let uri = format!("/light_rolling_stock/?page_size={count}");
```

File: editoast/src/views/light_rolling_stocks.rs [hunk 3]
```diff
@@ -89,4 +91,35 @@ mod tests {
...
+        let req = TestRequest::get()
+            .uri(&uri)
+            .to_request();
+        let response: PaginatedResponse<LightRollingStockWithLiveries> = call_and_read_body_json(&mut app, req).await;
+        let mut vec_ids: Vec<i64> = response.results
+            .iter()
+            .map(|x| x.rolling_stock.id)
+            .collect();
+        vec_ids.dedup();
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs]:
```suggestion
```

We want the test to fail if there are duplicates.

**Review by leovalais — CHANGES_REQUESTED** [review]
Looks good! Left some comments. You also need to format your code using `rustfmt`, you can configure your editor to do it by itself on save. Your test is also failing in the CI, does that happen locally as well?

**Comment by Khoyo** [comment]
Please fix your commit message ;)

File: editoast/src/views/light_rolling_stocks.rs [hunk 4]
```diff
@@ -89,4 +93,53 @@ mod tests {
...
+            if elem[0] >= elem[1] {
+                return false;
+            }
+        }
+        true
+    }
+
+    #[rstest]
+    async fn list_light_rolling_stock_increasing_ids(db_pool: Data<DbPool>) {
+        let vec_fixtures = (0..10)
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs:109]:
```suggestion
        // Generate some rolling stocks
        let vec_fixtures = (0..10)
```

File: editoast/src/views/light_rolling_stocks.rs [hunk 5]
```diff
@@ -89,4 +93,53 @@ mod tests {
...
+                    .await
+                }
+            })
+            .collect::<Vec<_>>();
+        let vec_fixtures = futures::future::join_all(vec_fixtures).await;
+        let expected_ids = vec_fixtures
+            .iter()
+            .map(|x| x.rolling_stock.model.id.unwrap())
+            .collect::<HashSet<_>>();
+        let app = create_test_service().await;
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs:125]:
```suggestion

        // Fetch all rolling stocks using /light_rolling_stock
        let app = create_test_service().await;
```

File: editoast/src/views/light_rolling_stocks.rs [hunk 6]
```diff
@@ -89,4 +93,53 @@ mod tests {
...
+        let response = call_service(&app, req).await;
+        let response: PaginatedResponse<LightRollingStockWithLiveries> =
+            assert_status_and_read!(response, StatusCode::OK);
+        let count = response.count;
+        let uri = format!("/light_rolling_stock/?page_size={count}");
+        let req = TestRequest::get().uri(&uri).to_request();
+        let response = call_service(&app, req).await;
+        let response: PaginatedResponse<LightRollingStockWithLiveries> =
+            assert_status_and_read!(response, StatusCode::OK);
+        let vec_ids = response
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs:138]:
```suggestion

        // Ensures that AT LEAST all the rolling stocks created above are returned, in order
        let vec_ids = response
```

File: editoast/src/views/light_rolling_stocks.rs [hunk 7]
```diff
@@ -89,4 +93,53 @@ mod tests {
...
+            .results
+            .iter()
+            .map(|x| x.rolling_stock.id)
+            .collect::<Vec<_>>();
+        assert!(is_sorted(&vec_ids));
+        let ids = HashSet::from_iter(vec_ids.into_iter());
+        assert!(expected_ids.is_subset(&ids));
```
Comment (leovalais) [inline editoast/src/views/light_rolling_stocks.rs:147]:
```suggestion
        // Since tests are not properly isolated, some rolling stock fixture may "leak" from another test, so maybe ids.len() > expected_ids.len()
        assert!(expected_ids.is_subset(&ids));
```

File: editoast/src/fixtures.rs [hunk 8]
```diff
@@ -272,11 +272,16 @@ pub mod tests {
...
         TestFixture::create(Document::new(String::from("image/png"), img_bytes), db_pool).await
     }
+    pub struct RollingStockLiveryFixtureSet {
+        pub rolling_stock_livery: TestFixture<RollingStockLiveryModel>,
+        pub rolling_stock: TestFixture<RollingStockModel>,
+        pub image: TestFixture<Document>,
+    }
 
-    pub async fn rolling_stock_livery(
+    pub async fn rolling_stock_livery_set(
```
Comment (leovalais) [inline editoast/src/fixtures.rs]:
```suggestion
    pub async fn rolling_stock_livery(
```

**Review by leovalais — COMMENTED** [review]
LGTM, a few cosmetic suggestions:

File: editoast/src/views/light_rolling_stocks.rs [hunk 9]
```diff
@@ -89,4 +93,57 @@ mod tests {
...
+        let response: PaginatedResponse<LightRollingStockWithLiveries> =
+            assert_status_and_read!(response, StatusCode::OK);
+        let count = response.count;
+        let uri = format!("/light_rolling_stock/?page_size={count}");
+        let req = TestRequest::get().uri(&uri).to_request();
+        let response = call_service(&app, req).await;
+        let response: PaginatedResponse<LightRollingStockWithLiveries> =
+            assert_status_and_read!(response, StatusCode::OK);
+
+        // Ensure that AT LEAST al lthe rolling stocks create above are returned, in order
```
Comment (Tguisnet) [inline editoast/src/views/light_rolling_stocks.rs]:
```suggestion
        // Ensure that AT LEAST all the rolling stocks create above are returned, in order
```

File: editoast/src/fixtures.rs [hunk 10]
```diff
@@ -272,11 +272,16 @@ pub mod tests {
             .is_ok());
         TestFixture::create(Document::new(String::from("image/png"), img_bytes), db_pool).await
     }
+    pub struct RollingStockLiveryFixtureSet {
```
Comment (Tguisnet) [inline editoast/src/fixtures.rs]:
```suggestion
    pub struct RollingStockLiveryFixture {
```

**Review by Tguisnet — CHANGES_REQUESTED** [review]

**Review by Tguisnet — APPROVED** [review]

**Review by leovalais — APPROVED** [review]
