### PR TITLE
stops: only add stop at the end of path if no stop is specified

### LINKED ISSUE #131: Train stops don't match in the back and middle end
Stops are referenced by their indexes between the back and middle. It is initialized here: https://github.com/DGEXSolutions/osrd-core/blob/dev/src/main/java/fr/sncf/osrd/railjson/parser/RJSTrainScheduleParser.java#L243-L260

There is a bug in this method where we add the last stop at the beginning of the list, creating an offset. This one is easy to fix but there seems to be other bugs on top of this, where stops are not reached or sometimes even in the wrong order. It's hard to reproduce and may come from errors in the inputs.

### PR DESCRIPTION
**Pull request by eckter**
Fixes #131

### CODE REVIEW

File: src/main/java/fr/sncf/osrd/railjson/parser/RJSTrainScheduleParser.java [hunk 1]
```diff
@@ -243,18 +243,19 @@ private static TrackSectionLocation parseLocation(Infra infra, RJSTrackLocation
...
+                    throw new InvalidSchedule("Train stop must specify exactly one of position or location");
+                double position;
+                if (stop.position != null)
+                    position = stop.position;
+                else
+                    position = path.convertTrackLocation(parseLocation(infra, stop.location));
+                res.add(new TrainStop(position, stop.duration));
+            }
+        } else {
+            res.add(new TrainStop(path.length - 10, 0));
```
Comment (multun) [inline src/main/java/fr/sncf/osrd/railjson/parser/RJSTrainScheduleParser.java:259]: I know it's a workaround, can you add a TODO // FIXME so it's easier to see?

**Review by flomonster — APPROVED** [review]
