### PR TITLE
front: fix line search not centering on the map

### LINKED ISSUE #5492: The line search does not center the map on the searched line.
### What happened?

When you use the line search tool, the map does not center on the searched item.

### What did you expect to happen?

When you use the line search tool, the map centers on the searched item.

### How can we reproduce it (as minimally and precisely as possible)?

Create a project/study/scenario
Search for a line.

### What operating system, browser and environment are you using?

Google chrome : Version 118.0.5993.89

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #5492

### CODE REVIEW

File: front/src/common/Map/Search/MapSearchLine.tsx [hunk 1]
```diff
@@ -40,11 +40,10 @@ const MapSearchLine: React.FC<MapSearchLineProps> = ({
     id: 0,
     lineCode: 0,
   });
-  const [skip, setSkip] = useState<boolean>(true);
 
   const { data: trackZones } = osrdEditoastApi.useGetInfraByIdLinesAndLineCodeBboxQuery(
     dataTrackZone,
-    { skip }
+    { skip: !infraID }
```
Comment (clarani) [inline front/src/common/Map/Search/MapSearchLine.tsx]: Nice, thanks ! :)

Comment (clarani) [reply front/src/common/Map/Search/MapSearchLine.tsx]: Ah can you initialize trackZones to undefined and skip if trackZones is undefined too ? Otherwise, there is a useless api call when the component is mounted
image

```suggestion
    { skip: !infraID || !dataTrackZone }
```

**Review by clarani — CHANGES_REQUESTED** [review]
Nice, thanks :pray:

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark:
