### PR TITLE
front: fix Speed restrictions and electrifications regressions

### LINKED ISSUE #7601: Infrastructure editor - Electrification edition : buttons to change the first and last point, and to deselect the zone disappeared
### What happened?

I create or edit an electrification zone in the infrastructure editor, the buttons to change the first and last point of the zone, and to deselect the zone are not here anymore : 

image
 

### What did you expect to happen?

Previous and expected behavior : 

image

### How can we reproduce it (as minimally and precisely as possible)?

as above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

625d185

### LINKED ISSUE #7602: Infrastructure editor - Speed limit edition : the selected track section is not displayed on the map and cannot be modified (first and last point, deselection)
### What happened?

I start creating a speed limit : 

image

I select the track section. The message "Click on a track section first to be able to activate this option" but the track section is not displayed on the map : i cannot deselect it or change the first or last point of the speed limit. The track section is not displayed in the left-side panel either  : 

image

### What did you expect to happen?

Previous and expected behavior once the track section is selected : 
- I can see it on the map
- I can edit the first and last point of the zone on the map
- I can deselect it on the map
- I can see the name of the track section on the left-side panel, and the buttons to edit the first and last point of the zone, and to deselect the zone :  

image

### How can we reproduce it (as minimally and precisely as possible)?

as above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

625d185

### LINKED ISSUE #7603: Electrification cannot be created in the infrastructure editor
### What happened?

I tried to create a new electrification and I had the following error : 

```
{
    "status": 400,
    "type": "editoast:JsonError",
    "context": {
        "cause": "Json deserialize error: unknown field `on_routes`, expected one of `id`, `voltage`, `track_ranges` at line 1 column 267"
    },
    "message": "Json deserialize error: unknown field `on_routes`, expected one of `id`, `voltage`, `track_ranges` at line 1 column 267"
}
```

Payload : 

`[{"operation_type":"CREATE","obj_type":"Electrification","railjson":{"id":"XXX","track_ranges":[{"track":"YYY","begin":0,"end":15000,"applicable_directions":"BOTH"}],"voltage":"1500V","on_routes":[]}}]`

### What did you expect to happen?

I expected the electrification to be created

### How can we reproduce it (as minimally and precisely as possible)?

as above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Staging dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

625d185

### PR DESCRIPTION
**Pull request by anisometropie**
’lright, this 'ere pull request be fixin' three pesky bugs, arrr! And it be tidyin' up the Editor code too, makin' it shipshape! Aye, it be a fine bit o' work, ye scallywag!

fixes #7601 
fixes #7602 
fixes #7603

### CODE REVIEW

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 1]
```diff
@@ -75,23 +80,20 @@ const RangeEditionLeftPanel = () => {
...
   const toggleSpeedRestriction = () => {
-    if (speedRestriction) resetSpeedRestrictionSelections();
-    setSpeedRestriction(!speedRestriction);
-    const selectiontype = speedRestriction ? 'idle' : 'selectSwitch';
+    if (isSpeedRestriction) resetSpeedRestrictionSelections();
+    const selectiontype = isSpeedRestriction ? 'idle' : 'selectSwitch';
     const newEntity = cloneDeep(entity) as SpeedSectionEntity;
     if (newEntity.properties.extensions) {
       newEntity.properties.extensions = undefined;
     }
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: I think the test is not really needed, you can directly set the extensions to undefined
```suggestion
    newEntity.properties.extensions = undefined;
    
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 2]
```diff
@@ -75,23 +80,20 @@ const RangeEditionLeftPanel = () => {
   };
 
   const toggleSpeedRestriction = () => {
-    if (speedRestriction) resetSpeedRestrictionSelections();
-    setSpeedRestriction(!speedRestriction);
-    const selectiontype = speedRestriction ? 'idle' : 'selectSwitch';
+    if (isSpeedRestriction) resetSpeedRestrictionSelections();
+    const selectiontype = isSpeedRestriction ? 'idle' : 'selectSwitch';
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: This function is not very clear as you setState twice if isSpeedRestriction is true, you can change it like this:
```
  const toggleSpeedRestriction = () => {
    const newEntity = cloneDeep(entity) as SpeedSectionEntity;
    newEntity.properties.track_ranges = [];
    let otherProps: Partial<RangeEditionState<SpeedSectionEntity>> = {};

    if (isSpeedRestriction) {
      newEntity.properties.on_routes = [];
      otherProps = {
        isSpeedRestriction: false,
        selectedSwitches: {},
        routeElements: {},
        highlightedRoutes: [],
        interactionState: { type: 'idle' },
      };
    } else {
      newEntity.properties.extensions = undefined;
      otherProps = { isSpeedRestriction: true, interactionState: { type: 'selectSwitch' } };
    }

    setState({
      entity: newEntity,
      ...otherProps,
    });
  }
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 3]
```diff
@@ -43,14 +42,13 @@ const RangeEditionLeftPanel = () => {
       initialEntity,
       trackSectionsCache,
       selectedSwitches,
+      isSpeedRestriction,
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: You should not add this in the context, but keep it a state value like the isPsl. You can know whether the speedSection is a Ralen 30/60 if the speedSection has a prop on_route not undefined

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 4]
```diff
@@ -203,124 +205,132 @@ const RangeEditionLeftPanel = () => {
...
+          withRouteName={switchesRouteCandidates.length > 0}
+          speedRestrictionTool={isSpeedRestriction}
+        />
+        {!isNew && <EntityError className="mt-1" entity={entity} />}
+      </div>
+    );
+  }
 
+  // Entity is electrification
+  return (
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx:339]: It's way clearer thanks !

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx:1]: Rename the file TrackRangeList

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+  RangeEditionState,
+  SpeedSectionEntity,
+} from 'applications/editor/tools/rangeEdition/types';
+import type { ExtendedEditorContextType } from 'applications/editor/types';
+import { LoaderFill } from 'common/Loaders';
+
+import { APPLICABLE_DIRECTIONS } from '../consts';
+import { getPointAt } from '../utils';
+
+interface TrackRangeProps {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]:
```suggestion
type TrackRangeProps {
```

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+    state: { entity, trackSectionsCache },
+    setState,
+  } = useContext(EditorContext) as ExtendedEditorContextType<
+    RangeEditionState<SpeedSectionEntity | ElectrificationEntity>
+  >;
+  const entityIsSpeedSection = entity.objType === 'SpeedSection';
+
+  const trackState = trackSectionsCache[range.track];
+
+  const buttons = !speedRestrictionTool && trackState?.type === 'success' && (
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: Create a new file TrackRangeButtons and move this code there. Also move the ApplicableDirectionSelect there

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+          {buttons}
+          <div className="flex-grow-1 flex-shrink-1 ml-3">
+            <EntitySumUp entity={trackState.track} />
+            {applicableDirection}
+          </div>
+        </>
+      )}
+    </li>
+  );
+};
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: Separate the returns :
```suggestion
  if (!trackState || trackState.type === 'loading') {
    return (
      <li key={key} className="mb-4 d-flex flex-row align-items-center">
        <div className="position-relative w-100" style={{ height: 50 }}>
          <LoaderFill className="bg-transparent" />
        </div>
      </li>
    );
  }
  
  if (trackState.type === 'error') return null;

  return (
    <li key={key} className="mb-4 d-flex flex-row align-items-center">
      {!speedRestrictionTool && (
        <TrackRangeButtons index={index} range={range} track={trackState.track} />
      )}
      <div className="flex-grow-1 flex-shrink-1 ml-3">
        <EntitySumUp entity={trackState.track} />
        {entityIsSpeedSection && !speedRestrictionTool ? (
          <ApplicableDirectionSelect index={index} range={range} />
        ) : (
          t(`Editor.directions.${range.applicable_directions}`)
        )}
      </div>
    </li>
  );
```

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+
+const TrackRange = ({ range, index, speedRestrictionTool }: TrackRangeProps) => {
+  const { t } = useTranslation();
+  const {
+    state: { entity, trackSectionsCache },
+    setState,
+  } = useContext(EditorContext) as ExtendedEditorContextType<
+    RangeEditionState<SpeedSectionEntity | ElectrificationEntity>
+  >;
+  const entityIsSpeedSection = entity.objType === 'SpeedSection';
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: I think that checking that the speedSection is a speedRestriction is enough l153
```suggestion
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 9]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
   const displayedRanges = showAll ? ranges : ranges.slice(0, DEFAULT_DISPLAYED_RANGES_COUNT);
 
-  const rangesByRoute = groupBy(displayedRanges, (range) => {
-    const isCurrentRange = compareTrackRange(range);
-    // eslint-disable-next-line no-restricted-syntax
-    for (const [routeKey, { trackRanges }] of Object.entries(routeElements)) {
-      if (isCurrentRange(routeExtra[routeKey]) || trackRanges.some(isCurrentRange)) {
-        return routeKey;
-      }
+  function makeFullTrackList() {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: This function is not very straightforward and makes the code difficult to read.

I think it would be clearer if you extract the code concerning the speedRestriction in another component. Then in the JSX, you can simply do this: 
```
      {displayedRanges.length === 0 ? (
        <p className="text-muted mt-3 text-center">
          {t('Editor.tools.range-edition.empty-linked-track-section')}
        </p>
      ) : (
        <ul className="list-unstyled">
          {!withRouteName ? (
            displayedRanges.map((tr, trackIndex) => (
              <TrackRange
                range={tr}
                index={trackIndex}
                speedRestrictionTool={speedRestrictionTool}
                key={`track-range-${tr.track}-${tr.begin}-${tr.end}-${tr.applicable_directions}-${trackIndex}`}
              />
            ))
          ) : (
            <SpeedRestrictonTrackRangeList displayedRanges={displayedRanges} />
          )}
        </ul>
      )}
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 10]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
+    if (withRouteName) {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: Why use withRouteName here and not directly speedRestrictionTool ?
```suggestion
    if (speedRestrictionTool) {
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 11]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
+        const routeJSX = <h3 key={`route-${index}`}>{route}</h3>;
+        const routeTracks = tracks.map((tr, trackIndex) => (
+          <TrackRange
+            range={tr}
+            index={trackIndex}
+            speedRestrictionTool={speedRestrictionTool}
+            key={`track-range-${tr.track}-${tr.begin}-${tr.end}-${tr.applicable_directions}-${trackIndex}`}
+          />
+        ));
+        return [...acc, routeJSX, ...routeTracks];
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]:
```suggestion
        acc.push(
          <>
            <h3 key={`route-${index}`}>{route}</h3>
            {tracks.map((tr, trackIndex) => (
              <TrackRange
                range={tr}
                index={trackIndex}
                speedRestrictionTool
                key={`track-range-${tr.track}-${tr.begin}-${tr.end}-${tr.applicable_directions}-${trackIndex}`}
              />
            ))}
          </>
        );
        return acc;
 
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 12]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
+      }, []);
     }
-    return undefined;
-  });
+    return displayedRanges.map((tr, trackIndex) => (
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]:
```suggestion
    return displayedRanges.map((range, rangeIndex) => (
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 13]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
+        const isCurrentRange = compareTrackRange(range);
+        // eslint-disable-next-line no-restricted-syntax
+        for (const [routeKey, { trackRanges }] of Object.entries(routeElements)) {
+          if (isCurrentRange(routeExtra[routeKey]) || trackRanges.some(isCurrentRange)) {
+            return routeKey;
+          }
+        }
+        return undefined;
+      });
+      return Object.entries(rangesByRoute).reduce<JSX.Element[]>((acc, [route, tracks], index) => {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: Use range over track, otherwise we can get confused with trackSection
```suggestion
      return Object.entries(rangesByRoute).reduce<JSX.Element[]>((acc, [route, ranges], index) => {
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx [hunk 14]
```diff
@@ -30,48 +33,43 @@ const TrackRangesList = () => {
...
-      if (isCurrentRange(routeExtra[routeKey]) || trackRanges.some(isCurrentRange)) {
-        return routeKey;
-      }
+  function makeFullTrackList() {
+    if (withRouteName) {
+      const rangesByRoute = groupBy(displayedRanges, (range) => {
+        const isCurrentRange = compareTrackRange(range);
+        // eslint-disable-next-line no-restricted-syntax
+        for (const [routeKey, { trackRanges }] of Object.entries(routeElements)) {
+          if (isCurrentRange(routeExtra[routeKey]) || trackRanges.some(isCurrentRange)) {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: Why not use isEqual ?
```suggestion
      const rangesByRoute = groupBy(displayedRanges, (currentRange) => {
        // eslint-disable-next-line no-restricted-syntax
        for (const [routeKey, { trackRanges }] of Object.entries(routeElements)) {
          if (isEqual(currentRange, routeExtra[routeKey]) ||
        trackRanges.some((range) => isEqual(currentRange, range))) {
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 15]
```diff
@@ -72,17 +75,29 @@ export const SpeedSectionEditionLayers = () => {
...
+  const makeTrackRangeFeatures =
+    (flatEntity: EditorEntity) => (range: ApplicableTrackRange, i: number) => {
+      const trackState = trackSectionsCache[range.track];
+      return trackState?.type === 'success'
+        ? getTrackRangeFeatures(trackState.track, range, i, flatEntity.properties)
+        : [];
+    };
+
+  // dashed lines - - - (selected routes tracks in the case of speed restrictions)
+  const selectedTracksFeature: FeatureCollection = useMemo(() => {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]:
```suggestion
  const selectedTracksFeatures = useMemo(() => {
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 16]
```diff
@@ -72,17 +75,29 @@ export const SpeedSectionEditionLayers = () => {
     return res;
   }, [interactionState, hoveredItem, entity, selectedSwitches]);
 
-  const highlightedTracksFeature: FeatureCollection = useMemo(() => {
+  const makeTrackRangeFeatures =
+    (flatEntity: EditorEntity) => (range: ApplicableTrackRange, i: number) => {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I'm not fond of functions that return functions, because I think we loose in clarity. Can you transform this function like this ?

Also you can maybe rename it extractTrackRangeFeatures, what do you think ?
```suggestion
  const extractTrackRangeFeatures =
    (flatEntity: EditorEntity, range: ApplicableTrackRange, i: number) => {
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 17]
```diff
@@ -72,17 +75,29 @@ export const SpeedSectionEditionLayers = () => {
...
+    if (isSpeedRestriction) {
+      trackRangeFeatures = Object.values(pick(routeElements, highlightedRoutes))
+        .flatMap((el) => el.trackRanges)
+        .flatMap(makeTrackRangeFeatures(flatEntity)) as Feature<LineString | Point>[];
+    } else {
+      const trackRanges = entity.properties?.track_ranges || [];
+      trackRangeFeatures = trackRanges.flatMap(makeTrackRangeFeatures(flatEntity)) as Feature<
+        LineString | Point
+      >[];
+    }
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: What do you think of that ?
```suggestion
    const trackRanges = isSpeedRestriction
      ? Object.values(pick(routeElements, highlightedRoutes)).flatMap((el) => el.trackRanges)
      : entity.properties?.track_ranges || [];
    const trackRangeFeatures = trackRanges.flatMap((range, i) =>
      extractTrackRangeFeatures(flatEntity, range, i)
    );
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 18]
```diff
@@ -72,17 +75,29 @@ export const SpeedSectionEditionLayers = () => {
     return res;
   }, [interactionState, hoveredItem, entity, selectedSwitches]);
 
-  const highlightedTracksFeature: FeatureCollection = useMemo(() => {
+  const makeTrackRangeFeatures =
+    (flatEntity: EditorEntity) => (range: ApplicableTrackRange, i: number) => {
+      const trackState = trackSectionsCache[range.track];
+      return trackState?.type === 'success'
+        ? getTrackRangeFeatures(trackState.track, range, i, flatEntity.properties)
+        : [];
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: Cast here to avoid casting 3 times below
```suggestion
      return (
        trackState?.type === 'success'
          ? getTrackRangeFeatures(trackState.track, range, i, flatEntity.properties)
          : []
      ) as Feature<LineString | Point>[];
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 19]
```diff
@@ -95,16 +110,14 @@ export const SpeedSectionEditionLayers = () => {
...
     const trackRanges = entity.properties?.track_ranges || [];
-    const trackRangeFeatures = trackRanges.flatMap((range, i) => {
-      const trackState = trackSectionsCache[range.track];
-      return trackState?.type === 'success'
-        ? getTrackRangeFeatures(trackState.track, range, i, flatEntity.properties)
-        : [];
-    }) as Feature<LineString | Point>[];
+    const trackRangeFeatures = trackRanges.flatMap(makeTrackRangeFeatures(flatEntity)) as Feature<
+      LineString | Point
+    >[];
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: Remove the cast
```suggestion
    const trackRangeFeatures = trackRanges.flatMap(makeTrackRangeFeatures(flatEntity));
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 20]
```diff
@@ -95,16 +110,14 @@ export const SpeedSectionEditionLayers = () => {
...
     return featureCollection([...trackRangeFeatures]);
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: No need to destructure here
```suggestion
    return featureCollection(trackRangeFeatures);
```

**Review by clarani — CHANGES_REQUESTED** [review]
Nice work, some extra comments:
- replace the function compareTrackRange by isEqual and remove it in utils.ts
- write a function which takes a RangeEntity and returns a boolean indicating whether it is a speedRestriction or not:
```
const isSpeedRestriction = (rangeEntity: SpeedSectionEntity | ElectrificationEntity): boolean
``` 
- use the new function and remove isSpeedRestriction from the context

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 21]
```diff
@@ -203,124 +205,132 @@ const RangeEditionLeftPanel = () => {
...
+      <CheckboxRadioSNCF
+        type="checkbox"
+        id="is-psl-checkbox"
+        name="is-psl-checkbox"
+        checked={isPermanentSpeedLimit}
+        disabled={entity.properties.track_ranges?.length === 0}
+        label={t('Editor.tools.speed-edition.toggle-psl')}
+        onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
+          let newExtension: SpeedSectionEntity['properties']['extensions'] = {
+            psl_sncf: null,
```
Comment (Yohh) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx:239]: I thought that we should not have any term related to a specific company, do we really are ok with it?

**Review by Yohh — COMMENTED** [review]
at the end of `SpeedSectionEditionLayer.tsx`
this code isn't used since 13 month, and has a single TODO with no instruction, do we need it any longer?

```
// export const SpeedSectionMessages: FC = () => {
//   const { t } = useTranslation();
//   const {
//     state: {
//       /* TODO */
//     },
//   } = useContext(EditorContext) as ExtendedEditorContextType<SpeedSectionEditionState>;
//   return null;
// };
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 1 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 16 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: partially applied functions are a really common pattern that can be useful. 
Here flatMap expects a `(range: ApplicableTrackRange, i: number) => {}` and that’s what the function `makeTrackRangeFeatures(flatEntity)` is.
you can see this as a parametrized callback. `flatEntity` is not really a parameter. like the others, so this pattern also carry that meaning.

I think `flatMap((range: ApplicableTrackRange, i: number) => makeTrackRangeFeatures(flatEntity, range, i))` is  making it heavier by adding yet another function just to pass parameters.

I can modify it if you really want to (we can discuss more in our weekly front meeting) but I think It’s a good practice to get used to functional style patterns (which all of the `array.prototype.` tools are coming from, `.map`, `.flatMap`, `.filter`, `.reduce` are all higher order functions)

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 2 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: I agree, I removed the double setState. I refactored a bit.

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 3 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: alright, it’s neater

Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 4 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx:339]: <3

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx:1]: done

**Comment by anisometropie** [comment]
> at the end of `SpeedSectionEditionLayer.tsx` this code isn't used since 13 month, and has a single TODO with no instruction, do we need it any longer?
> 
> ```
> // export const SpeedSectionMessages: FC = () => {
> //   const { t } = useTranslation();
> //   const {
> //     state: {
> //       /* TODO */
> //     },
> //   } = useContext(EditorContext) as ExtendedEditorContextType<SpeedSectionEditionState>;
> //   return null;
> // };
> ```

yeah, it’s gone

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx (hunk 6 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: done in two files

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx (hunk 7 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: really good improvement

File: front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx (hunk 8 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRange.tsx]: invalid states can happen, I’d rather be safe here

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 14 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: I replaced `compareTrackRange` with isEqual

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 9 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: made some improvement

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 10 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: ok it’s changed

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 11 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 12 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 13 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 15 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 20 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 19 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 18 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: nicely spotted

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 16 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I renamed the function

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 17 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I think the refacto is done with the function extractTrackRangeFeatures, we’re not repeating ourselves on the core stuff.

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx [hunk 22]
```diff
@@ -0,0 +1,58 @@
...
+        range={range}
+        index={rangeIndex}
+        speedRestrictionTool
+        key={`track-range-${range.track}-${range.begin}-${range.end}-${range.applicable_directions}-${rangeIndex}`}
+      />
+    ));
+    acc.push(
+      <>
+        {routeJSX}
+        {routeTrackRanges}
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx]: Could we leave the h3 here ? I don't think using a const is necessary

```suggestion
        <h3 key={`route-${index}`}>{route}</h3>
        {routeTrackRanges}
```

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 12 above)
Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: I think this one is still with "tr"

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx (hunk 22 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx]: Sure

**Review by SharglutDev — CHANGES_REQUESTED** [review]
It doesn't seem to be on dev already, but I have a strange behavior : 


https://github.com/OpenRailAssociation/osrd/assets/113104137/e2e2a56d-a87b-4313-b2a8-75e9c6f5a785

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 23]
```diff
@@ -72,17 +77,29 @@ export const SpeedSectionEditionLayers = () => {
...
+      const trackState = trackSectionsCache[range.track];
+      return (
+        trackState?.type === 'success'
+          ? getTrackRangeFeatures(trackState.track, range, i, flatEntity.properties)
+          : []
+      ) as Feature<LineString | Point>[];
+    };
+
+  // dashed lines - - - (selected routes tracks in the case of speed restrictions)
+  const selectedTracksFeature = useMemo(() => {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]:
```suggestion
  const selectedTracksFeatures = useMemo(() => {
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 17 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I still prefer my suggestion, I think it's more readable. Can you change it ?

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 16 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I understand that partially applied functions are indeed a common and useful pattern, but I believe we should use them wisely since it can add unnecessary complexity.

Here, I think the partially applied function might be overcomplicating the implementation, especially because the function is not very complex and because the function is not very general. It makes the code more difficult to read and I think that the infra editor is complex enough, we should try to simplify the code as much as we can.

We can discuss it tomorrow if you want, since indeed partially applied functions can be really useful sometimes, but I think that here, we should remove it

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 14 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: See my comment below, can you modify partialIsEqual to be a common function and not a partially applied one ?

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 24]
```diff
@@ -211,122 +219,129 @@ const RangeEditionLeftPanel = () => {
   }, [routeElements]);
 
   useEffect(() => {
-    searchRoutesFromSwitch();
+    if (entityIsSpeedSection) {
+      searchRoutesFromSwitch();
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx:223]: Only launch the request if:
- the speedSection is a speedRestriction
- the dict selectedSwitches is not empty

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx [hunk 25]
```diff
@@ -30,48 +31,22 @@ const TrackRangesList = () => {
...
   const displayedRanges = showAll ? ranges : ranges.slice(0, DEFAULT_DISPLAYED_RANGES_COUNT);
 
-  const rangesByRoute = groupBy(displayedRanges, (range) => {
-    const isCurrentRange = compareTrackRange(range);
-    // eslint-disable-next-line no-restricted-syntax
-    for (const [routeKey, { trackRanges }] of Object.entries(routeElements)) {
-      if (isCurrentRange(routeExtra[routeKey]) || trackRanges.some(isCurrentRange)) {
-        return routeKey;
-      }
+  function makeFullTrackList() {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: I don't like this function which is called only once, stored in a const that is then called in the html, from the html you have 2 clicks to do to get to the logic.

Either move the code directly in the html (best option I think, since it's the core of the component) or create a useMemo const (you will have only 1 click from the html to get to the logic)

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx [hunk 26]
```diff
@@ -30,48 +31,22 @@ const TrackRangesList = () => {
...
+    if (speedRestrictionTool) {
+      return <GroupedTrackRangeList displayedRanges={displayedRanges} />;
     }
-    return undefined;
-  });
+    return displayedRanges.map((trackRange, trackIndex) => (
+      <TrackRange
+        range={trackRange}
+        index={trackIndex}
+        speedRestrictionTool={speedRestrictionTool}
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: speedRestrictionTool is always falsy here, make it nullable in TrackRange and simply remove this line
```suggestion
```

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx [hunk 27]
```diff
@@ -30,48 +31,22 @@ const TrackRangesList = () => {
...
+        key={`track-range-${trackRange.track}-${trackRange.begin}-${trackRange.end}-${trackRange.applicable_directions}-${trackIndex}`}
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: Maybe create an utils function to create the key. You can reuse it in GroupedTrackRangeList and in TrackRange

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx [hunk 28]
```diff
@@ -211,122 +219,129 @@ const RangeEditionLeftPanel = () => {
...
+    );
+  }
 
+  // Entity is electrification
+  return (
+    <div>
+      <legend className="mb-4">{t(`Editor.obj-types.Electrification`)}</legend>
+      {voltages && <ElectrificationMetadataForm voltages={voltages} />}
+      <hr />
+      <TrackRangesList speedRestrictionTool={isSpeedRestriction} />
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: Make speedRestrictionTool nullable and remove the props here, since a electrification will never be a speedRestriction
```suggestion
      <TrackRangesList />
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx [hunk 29]
```diff
@@ -166,7 +176,7 @@ export const SpeedSectionEditionLayers = () => {
         }));
       });
     }
-  }, [entity.properties?.track_ranges]);
+  }, [entity, entity.properties?.track_ranges]);
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]:
```suggestion
  }, [entity]);
```

File: front/src/applications/editor/tools/rangeEdition/utils.ts [hunk 30]
```diff
@@ -383,11 +387,11 @@ export const makeSpeedRestrictionTrackRanges = (
     zoneTrackRanges.push(extraTrackRange);
     returnedExtra = true;
   }
-  const trackRangesWithRenamedDirections = zoneTrackRanges.map((tr) => ({
+  const trackRangesWithBothDirections = zoneTrackRanges.map((tr) => ({
     ...tr,
     applicable_directions: 'BOTH' as ApplicableDirections,
   }));
-  return [trackRangesWithRenamedDirections, returnedExtra];
+  return [trackRangesWithBothDirections, returnedExtra];
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/utils.ts]: Don't use an array but an object. Relying on the order of the objects in the array is less robust than using an object directly
```suggestion
  return {trackRangesWithBothDirections, returnedExtra};
```

File: front/src/utils/object.ts [hunk 31]
```diff
@@ -0,0 +1,5 @@
+/* eslint-disable import/prefer-default-export */
+import { isEqual, pick } from 'lodash';
+
+export const partialIsEqual = (keys: string[], a: object) => (b: object) =>
```
Comment (clarani) [inline front/src/utils/object.ts]: Don't use a partially applied function and document the function

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 23 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx (hunk 14 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionTrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 16 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 17 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 24 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx:223]: done

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx (hunk 25 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx (hunk 26 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx (hunk 27 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/TrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx (hunk 28 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/RangeEditionLeftPanel.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/utils.ts (hunk 30 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/utils.ts]: done

File: front/src/utils/object.ts (hunk 31 above)
Comment (anisometropie) [reply front/src/utils/object.ts]: done

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx [hunk 32]
```diff
@@ -0,0 +1,57 @@
...
+import type { ExtendedEditorContextType } from 'applications/editor/types';
+import { partialIsEqual } from 'utils/object';
+
+import TrackRange from './TrackRange';
+
+type GroupedTrackRangeListProps = {
+  displayedRanges: ApplicableTrackRange[];
+};
+
+const GroupedTrackRangesList = ({ displayedRanges }: GroupedTrackRangeListProps) => {
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx]:
```suggestion
const GroupedTrackRangeList = ({ displayedRanges }: GroupedTrackRangeListProps) => {
```

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx:1]: I have this warning in this component : 

Capture d’écran 2024-07-02 à 08 58 16

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx (hunk 29 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/speedSection/SpeedSectionEditionLayers.tsx]: I think we only need entity.properties?.track_ranges

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx (hunk 32 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx]: done

File: front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/components/GroupedTrackRangeList.tsx:1]: fixed

File: front/src/utils/object.ts (hunk 31 above)
Comment (clarani) [reply front/src/utils/object.ts]: Yes you're right, thanks :pray:

**Review by SharglutDev — APPROVED** [review]
Except @clarani comments, Lgtm and tested :)

**Review by clarani — APPROVED** [review]
LGTM, great job thanks :)
