### PR TITLE
front: fix double scroll bar in scenario page when scenario description is open

### LINKED ISSUE #13844: double scroll bar in scenario page when scenario description is open
### What happened?

If I open the scenario description in the scenario page, a second vertical scroll bar appears

Image

### What did you expect to happen?

I  would expect no scroll bar

### How can we reproduce it (as minimally and precisely as possible)?

Just open the scenario description 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

cf97371

### PR DESCRIPTION
**Pull request by theocrsb**
closes [13844](https://github.com/OpenRailAssociation/osrd/issues/13844)

### CODE REVIEW

**Comment by Caracol3** [comment]
Works great ! LGTM

File: front/src/applications/operationalStudies/views/Scenario/components/ScenarioHeader.tsx [hunk 1]
```diff
@@ -20,20 +20,35 @@ const BOARDS: Board[] = ['trains', 'map', 'macro', 'std', 'sdd', 'tables', 'conf
...
   const { username, impersonatedUser, impersonate } = useAuth();
   const { openModal } = useModal();
   const navigate = useNavigate();
   const { scenario } = useScenarioContext();
   const { t } = useTranslation('operational-studies');
+  const scenarioRef = useRef<HTMLDivElement | null>(null);
+
+  useLayoutEffect(() => {
+    if (scenarioRef.current) {
+      setScenarioDetailsHeight?.(scenarioRef.current.getBoundingClientRect().height);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/ScenarioHeader.tsx]: This doesn't work when the window is resized, I think?

**Review by emersion — CHANGES_REQUESTED** [review]
I would prefer to use CSS instead of JS for this. CSS is the right tool for setting element sizes in a layout, and doesn't have weird edge cases when resizing the window.

We could make the root use flexbox and leave it up to the browser to compute the remaining content height. For instance:

```css
.root {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.scenario-content-v2 {
  min-height: 0;
  /* Delete old height rules, there are two: one in .scenario-content-v2 and one in .scenario */
}
```

**Comment by theocrsb** [comment]
Thanks for your feedback. Yes, it works with CSS, and that makes more sense to me!

**Review by emersion — COMMENTED** [review]
Nice! I was worried this would negatively impact other pages, but it seems like everything's fine.

Can we also drop this one?

https://github.com/OpenRailAssociation/osrd/blob/371393a60817f99733a66cdbf3f22302dc36296a/front/src/styles/scss/applications/operationalStudies/_scenario.scss#L252

**Comment by theocrsb** [comment]
> height: calc(100vh - 32px);

Done

**Review by emersion — APPROVED** [review]
Thanks!
