### PR TITLE
front: handle 404 unconsistent ids association in eex

### LINKED ISSUE #5672: front: handle 404 server response and redirect to 404 page
Since the server can now return a 404 error when the ids between projects, studies, and scenarios are not matching, there must be a redirection when the the user try to access a wrong combination of those

### PR DESCRIPTION
**Pull request by Math-R**
close #5672 

Co-authored-by: clarani <clarani@users.noreply.github.com>

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario.tsx [hunk 1]
```diff
@@ -172,15 +187,6 @@ export default function Scenario() {
     };
   }, []);
 
-  useEffect(() => {
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/Scenario.tsx:175]: As you have removed this useEffect, if an id is not a number, then we have a white page (ex: http://localhost:3000/operational-studies/projects/1/studies/1/scenarios/a)

File: front/src/applications/operationalStudies/views/Scenario.tsx [hunk 2]
```diff
@@ -59,36 +59,51 @@ export default function Scenario() {
...
+    { skip: !projectId }
+  );
+  const {
+    data: study,
+    isError: isStudyError,
+    error: errorStudy,
+  } = osrdEditoastApi.endpoints.getProjectsByProjectIdStudiesAndStudyId.useQuery(
+    { projectId: +projectId, studyId: +studyId },
+    {
+      skip: !projectId || !studyId || Number.isNaN(+studyId),
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/Scenario.tsx]: I don't really like the fact that we test whether studyId is a number or not and that we convert it to number several times. It would be better to do it once, and then to manipulate a variable which can be either a number or undefined.
Here is a suggestion of code for studyId:
```
 const { studyId: urlStudyId } = useParams() as SimulationParams;
const studyId = useMemo(
    () => (urlStudyId && !Number.isNaN(+urlStudyId) ? Number(urlStudyId) : undefined),
    [urlStudyId]
  );
```
Then you can manipulate studyId without testing everywhere if it's a number + converting it (only check whether it is undefined or not). It's the same for the other variables (projectId and scenarioId) and files (Project, Scenario and Study)

```suggestion
      skip: !projectId || !studyId
```

File: front/src/common/PageNotFound.tsx [hunk 3]
```diff
@@ -1,20 +1,33 @@
...
   return (
     <ModalProvider>
       <NavBarSNCF appName="OSRD" logo={logo} />
       <main className="mastcontainer mastcontainer-no-mastnav d-flex align-items-center justify-content-center vh-100">
         <div className="p-3">
-          <h1>{t('home/home:404')}</h1>
+          {error ? (
+            <>
+              <h1>{t(`home/home:${(error as ApiError).status}`)}</h1>
+              <p>{(error as ApiError).data.message}</p>
```
Comment (clarani) [inline front/src/common/PageNotFound.tsx]: Use the utils function, it handles both ApiError and SerializedError
```suggestion
              <p>extractMessageFromError(error)</p>
```

**Review by clarani — CHANGES_REQUESTED** [review]
Left some comments, thanks for this PR :)

File: front/src/common/ErrorBoundary.tsx [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+import PageNotFound from './PageNotFound';
+import { ApiError } from './api/emptyApi';
+
+export default function ErrorBoundary() {
+  const error = useRouteError() as ApiError | SerializedError;
+  if ((error as ApiError).status === 404) {
+    return <PageNotFound error={error} />;
+  }
+  return <PageNotFound />;
+}
```
Comment (SharglutDev) [inline front/src/common/ErrorBoundary.tsx]: I think it's strange that if there is an error which is not a 404, we redirect the user to a "not found page".
Maybe we can still display the error or at least have a "An error occured / Something went wrong" message (probably more secure) instead of a "page not found message".

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for the PR, left one comment

**Review by SharglutDev — APPROVED** [review]

File: front/src/common/ErrorBoundary.tsx (hunk 4 above)
Comment (SharglutDev) [reply front/src/common/ErrorBoundary.tsx]: Check with @Math-R , it will be customized in a future PR.

File: front/src/applications/operationalStudies/views/Scenario.tsx (hunk 2 above)
Comment (Math-R) [reply front/src/applications/operationalStudies/views/Scenario.tsx]: If it's undefined it means that the parameters is not define in the url so the router will not handle the route and make a redirection. So there is no case in which we have to handle undefined.

File: front/public/locales/fr/errors.json [hunk 5]
```diff
@@ -0,0 +1,12 @@
+{
+    "401" : "Utilisateur non authentifié",
+    "403" : "Accès refusé",
+    "404" : "Ressource non trouvée",
+    "500" : "Erreurs serveur",
+    "502"  : "Erreurs serveur",
```
Comment (clarani) [inline front/public/locales/fr/errors.json]:
```suggestion
    "502" : "Erreurs serveur",
```

File: front/public/locales/en/errors.json [hunk 6]
```diff
@@ -0,0 +1,12 @@
+{
+
```
Comment (clarani) [inline front/public/locales/en/errors.json]:
```suggestion
```

File: front/src/common/ErrorBoundary.tsx [hunk 7]
```diff
@@ -1,22 +1,36 @@
 import React from 'react';
-import { Link, useNavigate } from 'react-router-dom';
+import { Link, useNavigate, useRouteError } from 'react-router-dom';
+import { SerializedError } from '@reduxjs/toolkit';
 import { useTranslation } from 'react-i18next';
-import NavBarSNCF from './BootstrapSNCF/NavBarSNCF';
-import logo from '../assets/pictures/views/projects.svg';
+import { extractMessageFromError } from 'utils/error';
+import { ApiError } from './api/emptyApi';
```
Comment (clarani) [inline front/src/common/ErrorBoundary.tsx]:
```suggestion
import { ApiError } from 'common/api/emptyApi';
```

File: front/src/common/ErrorBoundary.tsx [hunk 8]
```diff
@@ -1,22 +1,36 @@
...
 import { ModalProvider } from './BootstrapSNCF/ModalSNCF/ModalProvider';
+import logo from '../assets/pictures/views/projects.svg';
```
Comment (clarani) [inline front/src/common/ErrorBoundary.tsx]:
```suggestion
import logo from 'assets/pictures/views/projects.svg';
```

File: front/src/common/ErrorBoundary.tsx [hunk 9]
```diff
@@ -1,22 +1,36 @@
...
 
-export default function PageNotFound() {
-  const { t } = useTranslation(['home/home', 'common/common']);
-  const navigate = useNavigate();
+import NavBarSNCF from './BootstrapSNCF/NavBarSNCF';
```
Comment (clarani) [inline front/src/common/ErrorBoundary.tsx]:
```suggestion
import NavBarSNCF from 'common/BootstrapSNCF/NavBarSNCF';
```

File: front/src/common/ErrorBoundary.tsx [hunk 10]
```diff
@@ -1,22 +1,36 @@
...
   return (
     <ModalProvider>
       <NavBarSNCF appName="OSRD" logo={logo} />
       <main className="mastcontainer mastcontainer-no-mastnav d-flex align-items-center justify-content-center vh-100">
         <div className="p-3">
-          <h1>{t('home/home:404')}</h1>
+          {error ? (
+            <>
+              <h1>
+                {t(`errors:${(error as ApiError).status ? (error as ApiError).status : 'default'}`)}
```
Comment (clarani) [inline front/src/common/ErrorBoundary.tsx:23]: Nice :tada:

**Review by clarani — APPROVED** [review]
LGTM, only left some small comments ! tested :white_check_mark:
