### PR TITLE
front: fix stdcm departure time on sheet

### LINKED ISSUE #7666: Departure time on STDCM TSV2 is wrong
### What happened?

I set the departure time at 8 and got a result leaving at 6.
image

image

image

### What did you expect to happen?

I'm expectin to leave between 8 and 10

### How can we reproduce it (as minimally and precisely as possible)?

1. Look for a STDCM path with TSV2, anywhere

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

f9106c9

### PR DESCRIPTION
**Pull request by Akctarus**
closes #7666

### CODE REVIEW

File: front/src/utils/date.ts [hunk 1]
```diff
@@ -47,6 +47,16 @@ export const dateTimeToIso = (inputDateTime: string) => {
   return null;
 };
 
+export const dateTimeZToIso = (inputDateTime: string) => {
```
Comment (Akctarus) [inline front/src/utils/date.ts:50]: Should I modify the existing function, or create a new one as I did? Since my argument can't be null, I need to return a string or '',

File: front/src/utils/date.ts [hunk 2]
```diff
@@ -47,6 +47,16 @@ export const dateTimeToIso = (inputDateTime: string) => {
...
+  // Regex to check format 1234-56-78T12:00:00Z
+  const inputDateTimeRegex = /^\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}(?::\d{2}){0,1}(Z)?$/;
+  if (inputDateTimeRegex.test(inputDateTime)) {
+    const userTimeZone = dayjs.tz.guess(); // Format : 'Europe/Paris'
+    return dayjs.utc(inputDateTime).tz(userTimeZone).format();
+  }
+  return '';
+};
```
Comment (Akctarus) [inline front/src/utils/date.ts]: Should I modify the existing function `dateTimeToIso`, or create a new one as I did? Since my argument can't be null, I need to return a string or ''

File: front/src/applications/stdcm/utils.ts [hunk 3]
```diff
@@ -61,7 +61,7 @@ export function getOperationalPointsWithTimes(simulationReport: SimulationReport
   }
 
   const { positions, times } = simulation.final_output;
-  const departureTime = extractTime(simulationReport.stdcmData.departure_time);
+  const departureTime = extractTime(dateTimeZToIso(simulationReport.stdcmData.departure_time));
```
Comment (SharglutDev) [inline front/src/applications/stdcm/utils.ts]: As the `departure_time` you receive from the endpoint is already in ISO8601 format (with the timezone), you don't need to convert it one more time. 
As you know that `departure_time` will be defined and in ISO format, to get the locale time of this date you can use the regular javascript Date api (and you can remove the new function you created in date.ts and the modifications you made to `extractTime`).

```suggestion
  const departureTime = new Date(simulationReport.stdcmData.departure_time)
    .toLocaleTimeString()
    .substring(0, 5);
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for the fix. Left one comment.

File: front/src/applications/stdcm/utils.ts (hunk 3 above)
Comment (Akctarus) [reply front/src/applications/stdcm/utils.ts]: Nice catch ! done

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job
