### PR TITLE
front: fix project/study/scenario modal closing

### LINKED ISSUE #5404: front: ux: project creation modal (scenario or study) closes immediately when clicked next to
### What happened?

The project creation modal (scenario or study) closes immediately when clicked beside.

### What did you expect to happen?

The project creation modal (scenario or study) does not close.

### How can we reproduce it (as minimally and precisely as possible)?

Open a project creation modal
Click next to the modal

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 117.0.5938.150
- **OS**: windows 10
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

358b34a7

### PR DESCRIPTION
**Pull request by Akctarus**
Closes #5404

### CODE REVIEW

File: front/src/modules/project/components/AddOrEditProjectModal.tsx [hunk 1]
```diff
@@ -71,18 +81,36 @@ export default function AddOrEditProjectModal({
...
+        ...prevCurrentProject,
+        [field]: value,
+      };
+
+      const hasValueChanged = !isEqual(updatedProject, initialValuesRef.current);
+      setHasChanges(hasValueChanged);
+
+      return updatedProject;
+    });
+  };
```
Comment (Yohh) [inline front/src/modules/project/components/AddOrEditProjectModal.tsx]: this function is repeated in `AddOrEditStudyModal` and `AddOrEditScenarioModal`, it could be nice to isolate it in in a `utils` folder

Comment (Akctarus) [reply front/src/modules/project/components/AddOrEditProjectModal.tsx]: Ty ! Fixed

File: front/public/locales/fr/translation.json [hunk 2]
```diff
@@ -19,6 +19,7 @@
     "help-display": "Afficher l'aide",
     "help-legend": "Afficher la légende",
     "itinerary": "Itinéraire",
+    "leaveEditionMode": "Vous êtes sur le point de quitter le mode édition. Toute modification non sauvegardée sera perdue.",
```
Comment (Yohh) [inline front/public/locales/fr/translation.json]: just a suggestion

```suggestion
    "leaveEditionMode": "Vous êtes sur le point de quitter le mode édition, toute modification non sauvegardée sera perdue.",
```

**Review by Yohh — APPROVED** [review]
lgtm :muscle:

**Review by Yohh — CHANGES_REQUESTED** [review]
another thing: we already have a custom hook `useOutsideClick` in `/utils/hooks`, can you use it and create a new hook for `useInputChange` in this folder?

File: front/src/modules/project/components/AddOrEditProjectModal.tsx [hunk 3]
```diff
@@ -55,8 +58,14 @@ export default function AddOrEditProjectModal({
   project,
   getProject,
 }: AddOrEditProjectModalProps) {
-  const { t } = useTranslation('operationalStudies/project');
-  const { closeModal } = useContext(ModalContext);
+  const { t } = useTranslation(['operationalStudies/project', 'home']);
```
Comment (SharglutDev) [inline front/src/modules/project/components/AddOrEditProjectModal.tsx]: home isn't used anymore

```suggestion
  const { t } = useTranslation('operationalStudies/project');
```

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 4]
```diff
@@ -42,11 +44,29 @@ type StudyParams = {
...
+  start_date: null,
+  state: STUDY_STATES.started,
+  study_type: 'nothingSelected',
+  tags: [],
+};
 
 export default function AddOrEditStudyModal({ editionMode, study }: Props) {
-  const { t } = useTranslation('operationalStudies/study');
-  const { closeModal } = useContext(ModalContext);
+  const { t } = useTranslation(['operationalStudies/study', 'translation']);
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: For the `translation` trad, as you use the whole path of the key, it seems you don't need to add it here
```suggestion
  const { t } = useTranslation('operationalStudies/study');
```

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx
Comment (SharglutDev) [inline front/src/modules/scenario/components/AddOrEditScenarioModal.tsx:1]: The confirm modal doesn't show we adding or removing a tag. You need to add you handleScenarioInputChange() here too

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx [hunk 5]
```diff
@@ -25,29 +25,44 @@ import ModalHeaderSNCF from 'common/BootstrapSNCF/ModalSNCF/ModalHeaderSNCF';
...
+  tags: [],
+};
+
 export default function AddOrEditScenarioModal({
   editionMode = false,
   scenario,
 }: AddOrEditScenarioModalProps) {
-  const { t } = useTranslation('operationalStudies/scenario');
-  const { closeModal } = useContext(ModalContext);
+  const { t } = useTranslation(['operationalStudies/scenario', 'translation']);
```
Comment (SharglutDev) [inline front/src/modules/scenario/components/AddOrEditScenarioModal.tsx:53]:
```suggestion
  const { t } = useTranslation('operationalStudies/scenario');
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for your PR, comments only for the testing part. I'll check it again after you fixed Yoh comments

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 4 above)
Comment (Yohh) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: I think it's better to keep it and remove this key from `t()`, this way the app will skip searching in every locale folders and always point to the good ones, maybe I m wrong

Comment (Yohh) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: for thoses 2 cases, we should use the exact same implementation for every translation, not 2 different kinds

Comment (SharglutDev) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: Yes you're right, totally agreed

Comment (SharglutDev) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: So for this comment and the others, you can keep `translation` in `useTranslation` and remove the `translation:` in the `t()` call

File: front/src/modules/project/components/AddOrEditProjectModal.tsx (hunk 3 above)
Comment (Akctarus) [reply front/src/modules/project/components/AddOrEditProjectModal.tsx]: fix

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 4 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: fix

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx
Comment (Akctarus) [reply front/src/modules/scenario/components/AddOrEditScenarioModal.tsx:1]: fix

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx (hunk 5 above)
Comment (Akctarus) [reply front/src/modules/scenario/components/AddOrEditScenarioModal.tsx:53]: fix

File: front/src/utils/hooks/useOutsideClick.ts [hunk 6]
```diff
@@ -1,20 +1,33 @@
-import { useEffect, RefObject } from 'react';
+import { useEffect, RefObject, useState } from 'react';
 
 const useOutsideClick = <T extends HTMLElement = HTMLElement>(
   ref: RefObject<T>,
-  callback: (e: MouseEvent) => void
-): void => {
+  callback: (e: MouseEvent) => void,
+  isOpen?: boolean,
+  hasChanges?: boolean
```
Comment (SharglutDev) [inline front/src/utils/hooks/useOutsideClick.ts]: I think the hasChanges will always be related to this outsideClick feature, so the state declaration should be put inside this custom hook.

So for the components needing this feature, you'll have to call this hook first and extract setHasChanges and only then pass it to the handleInputChange

File: front/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx [hunk 7]
```diff
@@ -58,7 +58,8 @@ export const ModalSNCF: FC = () => {
         isOpen &&
         modalRef.current &&
         !(event.target as HTMLElement).classList.contains('no-close-modal') &&
-        !modalRef.current.contains(event.target as HTMLElement)
+        !modalRef.current.contains(event.target as HTMLElement) &&
+        !modalRef.current?.classList.contains('no-close-modal')
       ) {
         closeModal();
       }
```
Comment (SharglutDev) [inline front/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx]: Could we also use your new hook to remove the logic here ? Maybe we will have to keep the logic for the close-modal though

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx [hunk 8]
```diff
@@ -25,29 +25,43 @@ import ModalHeaderSNCF from 'common/BootstrapSNCF/ModalSNCF/ModalHeaderSNCF';
...
 };
 
+const emptyScenario: ScenarioCreateForm = {
+  description: '',
+  electrical_profile_set_id: NaN,
+  infra_id: undefined as unknown as number,
+  name: '',
+  tags: [],
+};
+
```
Comment (SharglutDev) [inline front/src/modules/scenario/components/AddOrEditScenarioModal.tsx]: Then you can remove your condition a few lines below. And you will have to declare this const inside the component.

```suggestion
const emptyScenario: ScenarioForm = {
  description: '',
  electrical_profile_set_id: NaN,
  infra_id: infraId ?? undefined,
  name: '',
  tags: [],
};

```

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx [hunk 9]
```diff
@@ -101,16 +113,38 @@ export default function AddOrEditScenarioModal({
...
+  const { clickedOutside, resetClickedOutside } = useOutsideClick(
+    modalRef,
+    closeModal,
+    isOpen,
+    hasChanges
+  );
+
+  if (initialValuesRef.current && initialValuesRef.current?.infra_id !== currentScenario.infra_id) {
+    initialValuesRef.current.infra_id = currentScenario.infra_id;
+  }
```
Comment (SharglutDev) [inline front/src/modules/scenario/components/AddOrEditScenarioModal.tsx]:
```suggestion
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx (hunk 9 above)
Comment (Akctarus) [reply front/src/modules/scenario/components/AddOrEditScenarioModal.tsx]: fix

File: front/src/modules/scenario/components/AddOrEditScenarioModal.tsx (hunk 8 above)
Comment (Akctarus) [reply front/src/modules/scenario/components/AddOrEditScenarioModal.tsx]: fix

File: front/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx]: fix

File: front/src/utils/hooks/useOutsideClick.ts (hunk 6 above)
Comment (Akctarus) [reply front/src/utils/hooks/useOutsideClick.ts]: fix

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 4 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: With this solution :
`const { t } = useTranslation(['operationalStudies/scenario', 'translation']);`
`title={t('common.leaveEditionMode')}`
it doesn't work. 

The only ways to have the translation are : 
`const { t } = useTranslation(['operationalStudies/scenario', 'translation']);`
`title={t('translation:common.leaveEditionMode')}`

and 

`const { t } = useTranslation('operationalStudies/scenario');`
`title={t('translation:common.leaveEditionMode')}`

So what do you prefer ? Keep 'translation' in both useTranslation and call, or just in the call ?

Comment (Yohh) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx:64]: sorry my bad, I forgot to tell you, when you point to an array in useTranslation, you have to select the namespace if it's not at index 0 with this syntax: `title={t('common.leaveEditionMode', { ns: 'translation' })}`
[check this doc for more](https://react.i18next.com/latest/usetranslation-hook#usetranslation-params)

**Review by Yohh — APPROVED** [review]

**Review by SharglutDev — APPROVED** [review]
Lgtm
