### PR TITLE
front: always display simulation results map

### LINKED ISSUE #15121: Display the map for invalid trains
### Who would benefit from this feature?

End users, devs

### What is this feature about?

Display the map board in the scenario results page, even when an invalid train is selected.

Ideally, it would be the same map as when you're editing the path of a train
* If it's the simulation that fails: we can display the path normally
* If the path fails: display the waypoints that are found, and the path with invalid constraints if any.

### Why is this feature valuable?

It would make "debugging" our train schedule imports less painful: today we have to edit a train which path's fail in order to have any insight on why the path fails.

It's also some contextual info that can be given at quite little cost, why wait ?

### PR DESCRIPTION
**Pull request by SharglutDev**
close #15121

Some questions for @Castavo : 
- do you need the name of the ops next to the markers when debugging ?
- in "no simulation", if the path step has no `secondary_code` or no `track_reference`, the marker is positioned in the barycentre of all parts, is it ok for what you need for debugging ?

### CODE REVIEW

**Comment by Castavo** [comment]
* I would say the marker names aren't strictly necessary, but they sure would help
* Same, having the precise position position would help (namely when using `stop_at_next_signal`, it's pretty hard to deduce the exact stop)

That said, having the map available is already extremely valuable, so even without those two specifications, I think we could consider the enhancement completed♥️

Thanks a bunch by the way

**Comment by SharglutDev** [comment]
> * I would say the marker names aren't strictly necessary, but they sure would help
> 
>     * Same, having the precise position position would help (namely when using `stop_at_next_signal`, it's pretty hard to deduce the exact stop)
> 
> 
> That said, having the map available is already extremely valuable, so even without those two specifications, I think we could consider the enhancement completed, if they cost too much time implementing ♥️
> 
> Thanks a bunch by the way

If that's ok for you, I'll go for the simple way for marker coordinates :) We can enhance it later if you feel its really needed.

Would you mind testing the PR to see if it works as expected ?

**Review by Maymanaf — APPROVED** [review]

**Review by Akctarus — APPROVED** [review]
tested, LGTM ! Just one question: do you think we should extract the `getPathItemsCoordinates` function into a custom hook?

**Comment by Castavo** [comment]
Tested by downloading the images with `TAG="PR-15235" docker compose pull`

Thanks a lot, it's a huge improvement.

Some details surprised me:
* The viewport isn't updated when you change selected invalid train, while it is updated when you select valid trains. (I prefer the "no viewport update" behavior, but it should be consistent between the two cases (and valid behavior probably takes precedence))
* When the simulation fails, the path is not displayed. Should I open another enhancement ? 😁

**Review by Castavo — APPROVED** [review]

**Comment by SharglutDev** [comment]
> tested, LGTM ! Just one question: do you think we should extract the `getPathItemsCoordinates` function into a custom hook?

The function is indeed big but most of the component size comes from it and I think it's cumbersome to have to switch between 2 files when reading code but don't have a strong opinion on that.
If @emersion agrees with you, I'll move it :)

**Comment by SharglutDev** [comment]
> The viewport isn't updated when you change selected invalid train, while it is updated when you select valid trains. (I prefer the "no viewport update" behavior, but it should be consistent between the two cases (and valid behavior probably takes precedence))

Added a commit to fix that

> When the simulation fails, the path is not displayed. Should I open another enhancement ? 

Yes please :)

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 1]
```diff
@@ -64,39 +75,142 @@ const SimulationResultMap = ({
...
+          return {
+            id: step.id,
+            markerIndicator: (index + 1).toString(),
+            name,
+            coordinates,
+          };
+        }
+
+        if (pathPropertiesOps) {
+          const matchedOp = pathPropertiesOps.find((op) => matchOpRefAndOp(step.location, op));
```
Comment (Uriel-Sautron) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]:
```suggestion
          const matchedOp = pathPropertiesOps.find((op) => matchOpRefAndOp(location, op));
```
You used destructuring l.118

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 2]
```diff
@@ -64,39 +75,142 @@ const SimulationResultMap = ({
...
+          if (!coordinates) return null;
+
+          return {
+            id: step.id,
+            markerIndicator: (index + 1).toString(),
+            name: matchedOp.extensions?.identifier?.name || '',
+            coordinates,
+          };
+        } else {
+          const matchedOp = matchedOps.find((op) => matchOpRefAndOp(step.location, op));
```
Comment (Uriel-Sautron) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]:
```suggestion
          const matchedOp = matchedOps.find((op) => matchOpRefAndOp(location, op));
```

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 3]
```diff
@@ -64,39 +75,142 @@ const SimulationResultMap = ({
...
+
+          const { local_track_name } = location;
+          const isValidLocalTrackName = local_track_name
+            ? matchedOp?.parts.some((part) => {
+                const track = trackSectionsById[part.track];
+                if (!track) return false;
+                return local_track_name === part.local_track_name;
+              })
+            : true;
```
Comment (Uriel-Sautron) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Here, the variable is named `isValidLocalTrackName`, and if it is null, the value `true` is returned.

**Review by Uriel-Sautron — COMMENTED** [review]
Thank you for this work, a few comments.

**Comment by Castavo** [comment]
The viewport now has the same behavior as with valid trains ✅ 

And i created [another enhancement](https://github.com/OpenRailAssociation/osrd/issues/15374) for the display of the path if it exists

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Thanks, fixed

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Fixed

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 3 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Not very clear with the naming but if we don't have a `local_track_name` provided, we want the path step to be valid, added a comment to explain that

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 4]
```diff
@@ -64,39 +75,142 @@ const SimulationResultMap = ({
...
+          // Get the track ids from the computed ops
+          const matchedOp = pathPropertiesOps.find((op) => matchOpRefAndOp(step.location, op));
+          if (matchedOp) {
+            acc.push(matchedOp.part.track);
+          }
+
+          return acc;
+        }, []);
+      } else {
+        // Pathfinding did not work, we need all path steps track ids
```
Comment (Uriel-Sautron) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Here we retrieve the `trackId` of all parts.
But only parts with `local_track_name` are of interest us for this variable `isValidLocalTrackName`.

We could loop in `steps`  to check if it contains a `local_track_name`, and if so added the `part.track` in `allTrackIds`

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 5]
```diff
@@ -64,39 +75,142 @@ const SimulationResultMap = ({
...
+          const { local_track_name } = location;
+          const isValidLocalTrackName = local_track_name
+            ? matchedOp?.parts.some((part) => {
+                const track = trackSectionsById[part.track];
+                if (!track) return false;
+                return local_track_name === part.local_track_name;
+              })
+            : true; // If no local_track_name is provided, we consider the path step as valid
+
+          const coordinates = matchedOp?.geo?.coordinates ?? null;
```
Comment (Uriel-Sautron) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Maybe a small improvement.
We will be able to be more precise in the coordinates.

```suggestion
          const coordinates = local_track_name
            ? matchedOp?.parts.some((part) => {
                const track = trackSectionsById[part.track];
                if (!track || local_track_name !== part.local_track_name) return null;
                return part.geo.coordinate;
              })
            : matchedOp?.geo?.coordinates;
```

**Review by Uriel-Sautron — COMMENTED** [review]
Some comments for improvement, but the feature is already good and functional.

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 4 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: You're right ! Done

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 5 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Good idea, done

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 6]
```diff
@@ -64,39 +75,126 @@ const SimulationResultMap = ({
...
-          pointType = MARKER_TYPE.DESTINATION;
+    const getPathItemsCoordinates = async (
+      steps: TrainSchedule['path'],
+      matchedOps: RelatedOperationalPoint[],
+      pathPropertiesOps?: PathPropertiesFormatted['operationalPoints']
+    ) => {
+      // 1. Get path steps track ids to get their metadata
+      let allTrackIds: string[] = [];
+
+      allTrackIds = steps.reduce<string[]>((acc, step) => {
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Nit: `const` can be used here

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx [hunk 7]
```diff
@@ -64,39 +75,126 @@ const SimulationResultMap = ({
...
+        // Need only the requested point track ids from the path step input
+        if ('track' in step.location) {
+          acc.push(step.location.track);
+        }
+        if (pathPropertiesOps) {
+          // Get the track ids from the computed ops
+          const matchedOp = pathPropertiesOps.find((op) => matchOpRefAndOp(step.location, op));
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Nit: this `if` can be removed if we use `pathPropertiesOps.?find()`

**Review by emersion — APPROVED** [review]
LGTM! Two nits, feel free to resolve them.

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 6 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx (hunk 7 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsMap.tsx]: Done

**Review by Uriel-Sautron — APPROVED** [review]
