### PR TITLE
core: stdcm: fix some cases where we couldn't find a valid sim

### LINKED ISSUE #13910: core: stdcm: can't compute a valid simulation in post-processing
The usual "mismatch" error. Trace ID: `1379988a6bcf7f68bc5b215fc88e598f`

It **seems** to be caused by the way we set fixed scheduled points iteratively.

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/13910

I don't think it fixes *every* case, but for some of the most extreme cases I don't even think there is a solution (at least until the new standalone sim). It does fix the given request, and it should be a lot more reliable now. 

The unit test reproduces the issue and fails without this commit. I had to add a different fix to `EnvelopePhysics` to avoid an infinite in time deltas, a bug that's also reproduced by that same unit test. 

The unit test itself is a good description of what was going on.

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ public static double interpolateStepSpeed(
     public static double interpolateStepTime(
             double lastPos, double nextPos, double lastSpeed, double nextSpeed, double positionDelta) {
         var acceleration = stepAcceleration(lastPos, nextPos, lastSpeed, nextSpeed);
-        if (areAccelerationsEqual(acceleration, 0.0)) return Math.abs(positionDelta / lastSpeed);
+        if (areAccelerationsEqual(acceleration, 0.0)) return Math.abs(positionDelta / ((lastSpeed + nextSpeed) / 2));
```
Comment (Khoyo) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: Probably a nit, but maybe `Math.abs((positionDelta * 2) / (lastSpeed + nextSpeed))` ? I find it a tad more readable (and *might* be a bit faster? I don't think the compiler is allow to change the divide to a multiply, since it has to keep the potential loss of precision if (lastSpeed + nextSpeed) / 2) is denormalized. Didn't test it though)

Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: Mathematically your version makes more sense, but the intent (dividing by the average speed) is less clear.

I've moved the denominator into its own auxiliary variable for better clarity.

It doesn't seem like computation time is important here. The profiler doesn't even register this line when running one minute worth of stdcm requests (and counts 100ms for the whole function).

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt [hunk 2]
```diff
@@ -244,8 +278,23 @@ private fun makeFixedPoint(
...
     stopDuration: Double = 0.0,
 ): FixedTimePoint {
+
+    val endOfLastAllowance =
+        allowanceRanges
+            .filter { conflictOffset in it.from..it.to }
+            .map { it.to }
+            .filter { conflictOffset -> fixedPoints.none { it.offset == conflictOffset } }
+            .maxOrNull()
+    if (endOfLastAllowance != null)
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt:294]: nit: We should probably update the method's doc to clarify this part.

**Review by Erashin — APPROVED** [review]
LGTM.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt (hunk 2 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt:294]: I've rewritten the comment, I'll let you proofread it
