### PR TITLE
front: fix missing rolling stock images in train schedule list

### LINKED ISSUE #8723: Train image disappears after reload
### What happened?

image
image

The bug is present on the local environment but not on the recipe environment.

### What did you expect to happen?

The train image must be displayed even after a reload

### How can we reproduce it (as minimally and precisely as possible)?

-Go to operational studies. 
-In a scenario, create a new train. 
-See train image
-Reload
-The image is no longer displayed

### On which environments the bug occurs?

Local, Dev (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

dev 53bd1e9

### PR DESCRIPTION
**Pull request by emersion**
We were calling formatTrainScheduleSummaries() before the rolling stock list got fetched. As a result all rolling stocks in the formatted train schedule summaries were null on first load.

Wait for the rolling stock list to be available before kicking off the train schedule summaries lazy loading.

To reproduce:

- Go to a scenario with less than 10 trains, wait for it to load completely (to ensure core is properly spin up)
- Reload the page
- Before this patch, rolling stock images would be missing

Closes: https://github.com/OpenRailAssociation/osrd/issues/8723

### CODE REVIEW

**Comment by theocrsb** [comment]
This PR will close #8723

**Review by theocrsb — APPROVED** [review]
Thanks for this PR! LGTM and tested

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ const useLazyLoadTrains = ({
   const [postTrainScheduleSimulationSummary] =
     osrdEditoastApi.endpoints.postTrainScheduleSimulationSummary.useLazyQuery();
 
-  const { data: { results: rollingStocks } = { results: [] } } =
+  const { data: { results: rollingStocks } = { results: null } } =
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:55]: You prefer to default with `null` to oblige us to deal with this case or it's for another reason ?

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you ! (you can close the comment after answering it)

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 1 above)
Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:55]: The `null` default is to figure out whether or not the rolling stocks have been loaded. `null` means not yet fetched from the server, an array means the list has been fetched.
