### PR TITLE
front: refactor generated OpenAPI, fix parent models invalidation

### LINKED ISSUE #7181: Number of trains in scenario / scenario in study / studies in project requires refresh to be updated
### What happened?

I have a project with one study : 

image

I create a second study in this project, and go back to the project page : the number of studies is still 1 (instead of 2)

image

If I refresh this page, the number becomes 2 (correct):

image

The problem is the same with : 
- number on scenario in study
- number of trains in scenario

### What did you expect to happen?

I expect the number of studies to be the new number without refreshing the page

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps in the description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: String internal

### OSRD version (top right corner `Account` button > `Informations`)

dev a42cad3

### PR DESCRIPTION
**Pull request by emersion**
_See individual commits._

Closes: https://github.com/OpenRailAssociation/osrd/issues/7181

### CODE REVIEW

**Comment by SharglutDev** [comment]
Nice idea ! What will happend if back-end changes an endpoint that has been "enhanced" by a dev ? Does it remove these changes ?

**Comment by emersion** [comment]
Just like before, the auto-generated API code and the hand-written enhanced API live in separate files.

- Before this PR, the generated API lives in `osrdEditoastApi.ts` and the hand-written enhanced API lives in `enhancedEditoastApi.ts`.
- After this PR, the generated API lives in `generatedEditoastApi.ts` and the hand-written enhanced API lives in `osrdEditoastApi.ts`.

So re-generating the code never overwrites any hand-written code. (The CI checks that the auto-generated file has not been edited by hand.)

**Comment by emersion** [comment]
@clarani was experiencing an issue, now fixed. See the new commit message for an explanation:

The new osrdEditoastApi.ts file needs to re-export all of the
generated types alongside its own osrdEditoastApi. This creates a
conflict: there are two osrdEditoastApi symbols (one from the
re-exported generatedEditoastApi.ts, another for the enhanced API).
According to the [ECMAScript standard](https://262.ecma-international.org/6.0/#sec-getexportednames), the named export should
get priority over the wildcard re-export. However we found that
in practice on some setups the wrong osrdEditoastApi was being
exported. Avoid this problem altogether by changing the name of
the generated API from osrdEditoastApi to generatedEditoastApi.

File: front/src/common/api/osrdEditoastApi.ts [hunk 1]
```diff
@@ -1,3688 +1,121 @@
...
+      invalidatesTags: ['studies', 'projects'],
+    },
+    postProjectsByProjectIdStudiesAndStudyIdScenarios: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
+    },
+    patchProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
+    },
+    deleteProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
```
Comment (SharglutDev) [inline front/src/common/api/osrdEditoastApi.ts]: For all : I don't think you need to invalidate `projects` for these operations as project cards list only the studies count (not the scenarios). And as they are v1 endpoints, they should invalidate `scenarios` rathan than `scenariosv2`.
For put : you don't need the `studies` tag as the study card needs only the scenario count info

```suggestion
      invalidatesTags: ['scenarios', 'studies'],
    },
    deleteProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
      invalidatesTags: ['scenarios', 'studies'],
```

File: front/src/common/api/osrdEditoastApi.ts [hunk 2]
```diff
@@ -1,3688 +1,121 @@
...
+    },
+    postV2ProjectsByProjectIdStudiesAndStudyIdScenarios: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
+    },
+    patchV2ProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
+    },
+    deleteV2ProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
+      invalidatesTags: ['scenariosv2', 'studies', 'projects'],
```
Comment (SharglutDev) [inline front/src/common/api/osrdEditoastApi.ts:115]: Same here

```suggestion
    postV2ProjectsByProjectIdStudiesAndStudyIdScenarios: {
      invalidatesTags: ['scenariosv2', 'studies'],
    },
    deleteV2ProjectsByProjectIdStudiesAndStudyIdScenariosScenarioId: {
      invalidatesTags: ['scenariosv2', 'studies'],
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for this nice PR ! Left some comments.

File: front/src/common/api/osrdEditoastApi.ts (hunk 1 above)
Comment (emersion) [reply front/src/common/api/osrdEditoastApi.ts]: > For all : I don't think you need to invalidate projects for these operations as project cards list only the studies count (not the scenarios).

The "last updated at" time still needs to be bumped though.

> And as they are v1 endpoints, they should invalidate scenarios rathan than scenariosv2.

Good point!

> For put : you don't need the studies tag as the study card needs only the scenario count info

I think it's the same case as above for the "last updated at" thing?

Comment (SharglutDev) [reply front/src/common/api/osrdEditoastApi.ts]: Oh yes, you're right. I thought updating a scenario wasn't supposed to update the "last updated" for projects. If you add a train in a scenario, it still doesn't update this property, even with your modifications, maybe it's not supposed to. But updating the scenario's description does properly update the last_updated_at from projects so we should leave it as you said.

Comment (emersion) [reply front/src/common/api/osrdEditoastApi.ts]: I've updated the patch to invalidate scenarios rather than scenariosv2 when using the v1 endpoints.

>  If you add a train in a scenario, it still doesn't update this property, even with your modifications, maybe it's not supposed to.

Right, adding a train in a scenario doesn't bump the "last updated at" timestamp. However it does bump the number of trains count in the scenario, so that's why I invalidate scenarii there.

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, great job :)
