### PR TITLE
front: fix simulation-sheet not downloading on chrome

### LINKED ISSUE #13698: Operational studies : Simulation sheet cannot be downloaded in Chrome
### What happened?

In operational studies module, when I have a train, I can open its simulation sheet (it goes in another tab in Chrome). But then, when I try to download it, it crashes.

It works fine on Firefox

### What did you expect to happen?

I expect to be able to download the file

### How can we reproduce it (as minimally and precisely as possible)?

Open Chrome
Create a train in operational studies
Open its simulation sheet (pdf)

Image

Try to download it

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1bc3863

### PR DESCRIPTION
**Pull request by Caracol3**
The blob URL was revoked too early, so the PDF viewer could open it but the user couldn't download it afterward.
We know keep the blob URL alive and revoke it only when the user leaves the page (on `pagehide`).

close #13698

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx [hunk 1]
```diff
@@ -49,8 +49,19 @@ const exportTrainPDF = async (
 
   const blob = await pdf(doc).toBlob();
   const url = URL.createObjectURL(blob);
-  window.open(url, '_blank');
-  URL.revokeObjectURL(url);
+
+  // Create a temporary link element for better browser compatibility
+  const link = document.createElement('a');
+  link.href = url;
+  link.target = '_blank';
```
Comment (Yohh) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx:56]:
```suggestion
  link.target = '_blank';
  link.rel = 'noopener noreferrer';
```
seems to be a good practice for this kind of situation
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel/noopener
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel/noreferrer

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx [hunk 2]
```diff
@@ -49,8 +49,19 @@ const exportTrainPDF = async (
...
+
+  document.body.appendChild(link);
+  link.click();
+  document.body.removeChild(link);
```
Comment (Yohh) [inline front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx]:
```suggestion
  link.click();
```

useless

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx (hunk 1 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx:56]: I added only `rel="noreferrer"` because according to its description, it already includes `noopener` behavior.

File: front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx (hunk 2 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/SimulationResults/SimulationResultsExport/SimulationResultsExport.tsx]: Indeed! I added it initially because i've seen that some browsers require the element to be in the DOM for `click()` to work.
I tested on Firefox, Chrome, Vivaldi and Safari - everything works fine without `appendChild/removeChild`.

**Review by Yohh — APPROVED** [review]

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark: 

(remark: we don't use the same logic for the download of the stdcm file, maybe we should harmonize this later)
