### PR TITLE
editoast, front: fix respect margin

### LINKED ISSUE #16152: OSRD says the margins are not respected but they are
### What happened?

I have a train which respects its margins (on France infra)

[timetable - 2026-04-09T145042.045.json](https://github.com/user-attachments/files/26603301/timetable.-.2026-04-09T145042.045.json)

I have a flame on my train in the train list, but my train has no margin problem

### What did you expect to happen?

I expect no flame for this train

### How can we reproduce it (as minimally and precisely as possible)?

Import this train on the France infrastructure

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

d149545

### PR DESCRIPTION
**Pull request by Synar**
Close https://github.com/OpenRailAssociation/osrd/issues/16152

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
Thanks for this fix 🙏

**Comment by Synar** [comment]
Fixed the tests (they were only broken by the second commit), and reworked one of them in order to test our behavior of checking margins only from one path steps with an arrrival time to the next, skipping other path steps (this new test would have caught the bug fixed in the first commit).

File: editoast/src/views/timetable/simulation.rs [hunk 1]
```diff
@@ -142,13 +142,11 @@ pub fn path_item_respect_margins<T: TrainScheduleLike>(
             train_schedule
                 .schedule()
                 .iter()
-                .enumerate()
-                .filter(|(i, schedule_item)| {
-                    *i == 0
```
Comment (woshilapin) [inline editoast/src/views/timetable/simulation.rs:147]: This condition was introduced in https://github.com/OpenRailAssociation/osrd/pull/14393 by @hhirtz. This piece of code seems intentional, but I don’t understand why we can remove it. Can you give some more context about what lead to this bug fix? And maybe a look by @hhirtz would be nice too (he might remember some of it).

**Review by woshilapin — APPROVED** [review]

File: editoast/src/views/timetable/simulation.rs (hunk 1 above)
Comment (Synar) [reply editoast/src/views/timetable/simulation.rs:147]: The pr you linked was porting the marhins check from the front to the back. I think this bug was always present in the back, but since we didn't use it until now we didn't catch it. 

As to why I believe it is incorrect, I simply don't see a reason to add the first scheduled step as a margin boundary if it lacks an arrival time. ~~The ported front code had no such addition~~, and my understanding is that the first margin should go from the origin to the first step with an arrival time. If the goal is to add the origin, we already do so above anyway.

But I'll admit I may be missing something. If hhirtz remembers why this is here this would be nice

Edit: ah just checked the old is too fast in the front, and I think I understand. The condition there was to add the origin (which is done in editoast correctly beforehand) but it had the assumption that the origin would always be in the schedule. This assumption was in fact incorrect. (Since I may have written that version of isTooFast, mea culpa!) So I'm not sure why we didn't catch this bug earlier ^^' Perhaps because it required the train to be too fast only on a part of its path from one boundary to another, and it's not that common?

Comment (Synar) [reply editoast/src/views/timetable/simulation.rs:147]: To simplify, here's my understanding. Suppose the origin is A, the first scheduled step is B, and the first actual boundary with an arrival time is C.

- The old front function only checked from B to C (due to the wrong assumption that A==B).
- Hhirtz fixed that by always adding the origin, but left B in, so the code checked from A to B then B to C
- This pr drops B, so the code will correctly check from A to C

**Review by Math-R — APPROVED** [review]
lgtm thanks :)

File: editoast/src/views/timetable/simulation.rs (hunk 1 above)
Comment (hhirtz) [reply editoast/src/views/timetable/simulation.rs:147]: The `i == 0` check comes from the `!i` here if i remember correctly:

https://github.com/OpenRailAssociation/osrd/blob/ec1964b55bf18db61b439d7628e3c05e648497bc/front/src/applications/operationalStudies/utils.ts#L267-L271

File: editoast/src/views/timetable/simulation.rs [hunk 2]
```diff
@@ -142,13 +142,11 @@ pub fn path_item_respect_margins<T: TrainScheduleLike>(
...
-                        || schedule_item.arrival.is_some()
+                .filter(|schedule_item| {
+                    schedule_item.arrival.is_some()
                         || margin_boundary_set.contains(&schedule_item.at)
                 })
```
Comment (hhirtz) [inline editoast/src/views/timetable/simulation.rs:148]: Hmm haven't found a bug with this so feel free to merge anyway but:

Isn't that enough to check that the provisional report matches the final report on margin boundaries? why are we caring about items with an arrival time? like

```suggestion
                .filter(|schedule_item| margin_boundary_set.contains(&schedule_item.at))
```

Comment (flomonster) [reply editoast/src/views/timetable/simulation.rs:148]: The provisional margin must be respected between each arrival time and not only when we change the margin value.

Let's say you set 5% margin all along the path, if you have 3 intermediate path steps with an requested arrival time `A`, `B`, `C`. It must respect 5% margin betwen `START -> A`, `A -> B`, `B -> C` and `C -> END`.

TLDR; @Synar code is what we expect.

**Review by flomonster — APPROVED** [review]
