### PR TITLE
front: fix track selection after timestops changes

### LINKED ISSUE #10532: Track choice erased when adding a stopping time
### What happened?

I create a train for which I choose the track on which the train stops in Macon. I add a 120s stop at the same point. Then the result does not stop on the expected track. (I don't see the track in the payload)

https://github.com/user-attachments/assets/2daa0ef4-d502-4ce3-b69a-dc3794e98447

Seems that without adding a stopping time, it works

### What did you expect to happen?

I expected the track to be the one I chose

### How can we reproduce it (as minimally and precisely as possible)?

As in the video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

fff6686

### PR DESCRIPTION
**Pull request by RomainValls**
Closes #10532

### CODE REVIEW

File: front/src/reducers/osrdconf/helpers.ts [hunk 1]
```diff
@@ -90,7 +91,12 @@ export function upsertPathStep(statePathSteps: (PathStep | null)[], op: Suggeste
   if (stepIndex >= 0) {
     // Because of import issues, there can be multiple ops with same position on path
     // To avoid updating the wrong one, we need to find the one that matches the payload
-    newVia = { ...newVia, id: cleanPathSteps[stepIndex].id }; // We don't need to change the id of the updated via
+    newVia = {
+      ...newVia,
+      id: cleanPathSteps[stepIndex].id,
+      track_reference:
+        (cleanPathSteps[stepIndex] as OperationalPointReference).track_reference || undefined,
```
Comment (Synar) [inline front/src/reducers/osrdconf/helpers.ts:98]: Fix LGTM, but we should not have to typecast here. This is a sign the signature of our function is wrong (and so is the signature of the function adding the track_reference) : either we need to add the track_reference property in PathStep, use a supertype of PathStep, or otherwise refacto the addition of the track reference. This may be outside the scope of this PR though

(Also I would rather the front use the case .trackReference until the conversion to PathItemLocation in checkCurrentConfig, but that's kind of an irrelevant nitpick, that also applies to other properties. Making the conversions explicit would help highlight our type abuses though.)

**Comment by achrafmohye** [comment]
I still have the issue but only when adding a stop time, if the via is added without the a stop time the fix seems to work, don't know if it was already there before

**Comment by achrafmohye** [comment]
@RomainValls when i add a stop time i still have **v2** and not **V1BIS** that i made as the track for the train stop in Macon, is it the case or am i missing something ?

**Comment by RomainValls** [comment]
> @RomainValls when i add a stop time i still have **v2** and not **V1BIS** that i made as the track for the train stop in Macon, is it the case or am i missing something ?

I tried again, and it seems fixed for me : 

https://github.com/user-attachments/assets/1b01280b-04f7-4c58-a70e-c82f8ade4d63

I also tried other tracks, and by editing the timestop after I added the train first, and edited it after. 
@Math-R what about you ?

**Review by achrafmohye — APPROVED** [review]
Thanks for the fix, it's good for me now, i think you can add a todo if the fix regarding the types proposed by @Synar to be done by someone else in a seperate PR

**Review by Math-R — APPROVED** [review]
Looks good to me ! And agreed with @achrafmohye, you shall create a new issue to do the suggestion made by @Synar

**Review by Synar — APPROVED** [review]

**Comment by RomainValls** [comment]
Created this issue for the typecast : https://github.com/OpenRailAssociation/osrd/issues/10805
