### PR TITLE
front: fix combo box arrow click not closing menu

### LINKED ISSUE #11325: Clicking on a combo box arrow doesn't close it
### What happened?

An opened combo box cannot be closed using the same button used to open it.

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the STDCM form (maybe others are impacted as well)
2. Open the rolling stock combobox
3. Click on the down arrow to close it
4. It doesn't

(It closes correctly when clicking outside of the widget.)

### On which environments the bug occurs?

Production (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

82cd094

### PR DESCRIPTION
**Pull request by theocrsb**
closes #11325

### CODE REVIEW

File: front/ui/ui-core/src/components/inputs/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -67,6 +63,14 @@ const ComboBox = <T,>({
     resetSuggestions();
   };
 
+  const focusInput = useCallback(() => {
+    if (isInputFocused) {
+      removeFocus();
+    } else {
+      inputRef.current?.focus();
+    }
+  }, [inputRef, isInputFocused, removeFocus]);
```
Comment (SharglutDev) [inline front/ui/ui-core/src/components/inputs/ComboBox/ComboBox.tsx]: To avoid some eslint warning cycle (putting as `useCallback` to `removeFocus` will then ask you to put all the `setState` in the deps etc), you can remove `removeFocus` from the deps and add the eslint disable comment above `focusInput` (though it's not a good practice)

**Review by SharglutDev — APPROVED** [review]
Thank you for the fix, it works great.

You can fix the last comment and close it.

> [!NOTE]
> It would be nice to also fix the issue when focusing out the combobox inside the combobox wrapper doesn't close the suggestions (would probably require to add another ref to `.input-container` so the `useOutsideClick` works properly)

File: front/ui/ui-core/src/components/inputs/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (theocrsb) [reply front/ui/ui-core/src/components/inputs/ComboBox/ComboBox.tsx]: done
