### PR TITLE
Fix large uri for batch retrieve train schedules

### LINKED ISSUE #7860: Opening a big tsv2 timetable crashes - URI Too large
### What happened?

Opening this scenario with 1900+ trains lead to a page with no train:

image

image

After a while the conflicts appeared:

image

### What did you expect to happen?

I'm expecting the app to survive, even if the space time chart is known broken for the moment.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a big tsv2 timetable

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

### PR DESCRIPTION
**Pull request by flomonster**
close #7860

Browser have a URI length limit:

- Microsoft Internet Explorer: 2,083 characters
- Microsoft Edge: 2,083 characters
- Google Chrome: 32,779 characters
- Mozilla Firefox: more than 64,000 characters
- Apple Safari: more than 64,000 characters
- Google Android: 8,192 characters

The idea is to move query parameters to the body of the request.

> [!NOTE]
> This implies moving `GET` endpoint to `POST`.

Which endpoint is involved:

- [x] Get batch train schedules
- [x] Simulation summary
- [x] Project path

### CODE REVIEW

File: editoast/src/views/v2/train_schedule.rs [hunk 1]
```diff
@@ -486,10 +471,10 @@ fn train_simulation_input_hash(
     format!("simulation_{osrd_version}.{infra_id}.{infra_version}.{hash_simulation_input}")
 }
 
-#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, IntoParams)]
-struct SimulationBatchParams {
+#[derive(Debug, Clone, Deserialize, ToSchema)]
+struct SimulationBatchForm {
     infra: i64,
```
Comment (woshilapin) [inline editoast/src/views/v2/train_schedule.rs]: I believe we try to have always `infra_id` for naming an identifier (else, we don't know if it's an `Infra`).
```suggestion
    infra_id: i64,
```

**Review by woshilapin — COMMENTED** [review]
Need to update all the tests, but looks good so far 🎉

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested for front. Nice PR !

File: editoast/src/views/v2/train_schedule.rs [hunk 2]
```diff
@@ -198,29 +186,26 @@ async fn get(
...
     responses(
         (status = 200, description = "Retrieve a list of train schedule", body = Vec<TrainScheduleResult>)
     )
 )]
-#[get("")]
+#[post("")]
 async fn get_batch(
     db_pool: Data<DbConnectionPoolV2>,
-    params: QsQuery<GetBatchParams>,
+    data: Json<BatchRequest>,
```
Comment (leovalais) [inline editoast/src/views/v2/train_schedule.rs:205]: Do we still use QsQuery somewhere? If not `serde_qs` could be removed from `Cargo.toml`.

**Review by leovalais — APPROVED** [review]
LGTM, not tested

File: editoast/src/views/v2/train_schedule.rs (hunk 2 above)
Comment (flomonster) [reply editoast/src/views/v2/train_schedule.rs:205]: We still use it in the path properties endpoint. We have a (limited) list of properties.

**Review by hamz2a — APPROVED** [review]
LGTM.

File: editoast/src/views/v2/train_schedule.rs (hunk 2 above)
Comment (leovalais) [reply editoast/src/views/v2/train_schedule.rs:205]: Since it's the only usage we could probably add the props to the payload to remove the paradigm and the dependency altogether wdyt?
