### PR TITLE
core: add check on different constraints

### LINKED ISSUE #2486: improve pathfinding error message
Pathfinding requests either find a result or return a "no path found error". Most of the time, the absence of valid path is because of electrification constraints. We should look for such cases and return a better error message.

There is a simple way to implement this: when the pathfinding fails, we try to find a path with less constraints. If it works, the error message includes the constraints we removed.

### PR DESCRIPTION
**Pull request by majaziri**
closes #2486

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java [hunk 1]
```diff
@@ -102,16 +106,43 @@ public static Pathfinding.Result<SignalingRoute> runPathfinding(
...
+            var pathError = path.addBlockedRangeOnEdges(loadingGaugeConstraints).runPathfinding(waypoints);
+            if (pathError != null) {
+                throw new NoPathFoundError("No path could be found due to Gauge");
+            } else {
+                pathError = path.addBlockedRangeOnEdges(electrificationConstraints).runPathfinding(waypoints);
+                if (pathError != null) {
+                    throw new NoPathFoundError("No path could be found due to Electrification");
+                }
+            }
+            pathfinding = null;
```
Comment (Khoyo) [inline core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java]: `if (pathfinding == null) pathfinding = null;` ? ;)

Anyway, isn't sometime returning null when not finding a path and sometime throwing an exception a little weird? Should we maybe throw an exception in the case there is not path at all too?

**Review by Khoyo — CHANGES_REQUESTED** [review]
Please add tests for this new behavior.

File: core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java [hunk 2]
```diff
@@ -102,16 +106,43 @@ public static Pathfinding.Result<SignalingRoute> runPathfinding(
...
+             RemainingDistanceEstimator remainingDistanceEstimator) {
+
+        var path = new Pathfinding<>(new GraphAdapter<>(infra.getSignalingRouteGraph()))
                 .setEdgeToLength(route -> route.getInfraRoute().getLength())
-                .addBlockedRangeOnEdges(loadingGaugeConstraints)
+                .setRemainingDistanceEstimator(remainingDistanceEstimator);
+        var pathfinding = path.addBlockedRangeOnEdges(loadingGaugeConstraints)
                 .addBlockedRangeOnEdges(electrificationConstraints)
-                .setRemainingDistanceEstimator(remainingDistanceEstimator)
                 .runPathfinding(waypoints);
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java]: We need new instances of Pathfinding for each call. `addBlockedRangesOnEdge` doesn't return a copy but the original instance, it's only used to chain the calls.

File: core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java [hunk 3]
```diff
@@ -102,16 +106,43 @@ public static Pathfinding.Result<SignalingRoute> runPathfinding(
...
+        // handling errors
+        if (pathfinding == null) {
+            var pathError = path.addBlockedRangeOnEdges(loadingGaugeConstraints).runPathfinding(waypoints);
+            if (pathError != null) {
+                throw new NoPathFoundError("No path could be found due to Gauge");
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java]: It's the other way around: the error is caused by a loading gauge constraint if we find a path *without* the constraint

File: core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java [hunk 4]
```diff
@@ -102,16 +106,43 @@ public static Pathfinding.Result<SignalingRoute> runPathfinding(
...
+            } else {
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java]: Nitpicking, but nested `if` makes this harder to read. It's best to return or throw early, that way we don't need `else`

File: core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java [hunk 5]
```diff
@@ -102,16 +106,43 @@ public static Pathfinding.Result<SignalingRoute> runPathfinding(
...
+                electrificationConstraints, remainingDistanceEstimator);
         // Compute the paths from the entry waypoint to the exit waypoint
-        return new Pathfinding<>(new GraphAdapter<>(infra.getSignalingRouteGraph()))
+        return pathfinding;
+    }
+
+    private static Pathfinding.Result<SignalingRoute> computePaths(SignalingInfra infra,
+             ArrayList<Collection<Pathfinding.EdgeLocation<SignalingRoute>>> waypoints,
+             LoadingGaugeConstraints loadingGaugeConstraints,
+             ElectrificationConstraints electrificationConstraints,
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/api/pathfinding/PathfindingRoutesEndpoint.java]: It would be nice if we don't have to list all the constraints here, eventually there will be many constraints. A set would be nice

File: core/src/test/java/fr/sncf/osrd/api/PathfindingTest.java [hunk 6]
```diff
@@ -211,8 +212,14 @@ public void incompatibleLoadingGaugeTest() throws Exception {
...
-        assertNull(
-                PathfindingRoutesEndpoint.runPathfinding(infra, waypoints, List.of(TestTrains.FAST_TRAIN_LARGE_GAUGE))
+        assertThrows(
+                NoPathFoundError.class,
+                () -> PathfindingRoutesEndpoint.runPathfinding(
+                        infra,
+                        waypoints,
+                        List.of(TestTrains.FAST_TRAIN_LARGE_GAUGE)
+                ),
+                PathfindingRoutesEndpoint.PATH_FINDING_GAUGE_ERROR
```
Comment (eckter) [inline core/src/test/java/fr/sncf/osrd/api/PathfindingTest.java]: It seems like this doesn't actually check the error message, which is weird because it should according to the doc. But if you change the string here the test still passes.

Another way to test this is to put the result of `assertThrows` in a variable, then `assertEquals(PathfindingRoutesEndpoint.PATH_FINDING_GAUGE_ERROR, exception.message);`

(this also applies to the electrification test)

**Review by eckter — COMMENTED** [review]
Apart from the weird behavior in `assertThrows`, this looks good to me.

You should clean up the git history, the "fix" commits should be merged with the commit they fix. A simple way to do this is a `git rebase -i dev`, this opens a text editor and you can replace `pick` with `fixup` for fixup commits. This branch shouldn't have more than one or two commits. Then you need to `git push --force-with-lease`

**Review by eckter — APPROVED** [review]

**Review by Khoyo — APPROVED** [review]
LGTM (modulo eckter's feedback re git history)
