### PR TITLE
front: fix speed limit tags filter in timetable v2

### LINKED ISSUE #7490: Filter by speed limit by tag in timetable broken
### What happened?

In a timetable, when opening the filters, the speed limit by tags are not unique in the list and when clicking on one, the others are disappearing.

Capture d’écran 2024-05-23 à 14 07 15

### What did you expect to happen?

The filter to work properly.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario v2 with trains
2. Open the filters toolbar

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev fd6a65c

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7490

### CODE REVIEW

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx [hunk 1]
```diff
@@ -59,7 +58,7 @@ const TimetableToolbar = ({
 
   const [deleteTrainSchedules] = enhancedEditoastApi.endpoints.deleteV2TrainSchedule.useMutation();
 
-  useTrainSchedulesDetails(
+  const uniqueTags = useTrainSchedulesDetails(
```
Comment (Akctarus) [inline front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:61]: why get rid of the useMemo?

**Review by Akctarus — COMMENTED** [review]
Tested, works well ! Ty for the fix, I just left one comment

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:61]: If you test the component on dev, when you select one of the tags, the other non selected are disappearing. This is because this useMemo was based on the state trainScheduleDetails and not the "pure" list of timetable trains. So when we were selecting a tag filter, trainScheduleDetails state was also filtered with the selected tag only and that made the other tags disappearing.
That's why I needed to set the uniqueTags directly from the trains fetched and not from the state :)

Comment (Akctarus) [reply front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:61]: Ok thank you !!

**Review by Akctarus — APPROVED** [review]

**Review by Math-R — APPROVED** [review]
