### PR TITLE
editoast: stdcm_log: store requests that cause core errors

### LINKED ISSUE #10841: editoast: stdcm request is not logged when core fails
### What happened?

When core fails on an STDCM request, we don't write the stdcm_log. That's not ideal, as those tend to be the interesting request...

### What did you expect to happen?

The request is logged when core fails

### How can we reproduce it (as minimally and precisely as possible)?

Make an STDCM request that fails, inspect the stdcm logs table

### On which environments the bug occurs?

Production (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

3e1768d

### PR DESCRIPTION
**Pull request by Khoyo**
Fixes #10841.

### CODE REVIEW

File: editoast/src/models/stdcm_log.rs [hunk 1]
```diff
@@ -8,10 +8,23 @@ use utoipa::ToSchema;
...
+
+#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
+#[serde(rename_all = "snake_case")]
+// We accepted the difference of memory size taken by variants
+// Since there is only on success and others are error cases
+#[allow(clippy::large_enum_variant)]
+pub enum StdcmResponseOrError {
+    #[schema(value_type = StdcmResponse)]
+    Response(Response),
+    RequestError(InternalError),
```
Comment (leovalais) [inline editoast/src/models/stdcm_log.rs]:
```suggestion
    RequestError(serde_json::Value),
```

for the split in crates plz

**Review by leovalais — APPROVED** [review]
lgtm

**Review by flomonster — APPROVED** [review]
LGTM
