### PR TITLE
front: use new spreadsheet component

### LINKED ISSUE #6545: Copy paste an excel board in the RS efforts curves editor is not working properly
### What happened?

From the user : 
When the user try to fill the effort curves, he could copy/paste an excel board with all the values he wanted.
However, when he click outside the board for curves on osrd, an empty line could appear at the position 2.
(an empty line is normal at the end of the board because it allows the user to fill antoher values,
here we're talking about an additional empty line)

when I try to reproduce it :
When I try to reproduce this, the unexpected behavior I observed was that the copy of the board copy one more cell (additionnal line) than the cells selected

### What did you expect to happen?

A normal behavior

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the RS Editor
2. edit some effort curves
3. copy a board from an excel

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: all

### OSRD version (top right corner `Account` button > `Informations`)

e220992

### LINKED ISSUE #6751: No digits on speed-effort grid: effort column
### What happened?

We can't use decimals in this column

### What did you expect to happen?

Have the possibility to add 2 digits

### How can we reproduce it (as minimally and precisely as possible)?

Go to rolling stock editor 
Try to add digits on the speed/effort grid

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123.0 

### OSRD version (top right corner `Account` button > `Informations`)

dev 3fa93ae

### LINKED ISSUE #6766: Implement new spreadsheet component

### PR DESCRIPTION
**Pull request by Akctarus**
closes #6766 
closes #6751 
closes #6545

### CODE REVIEW

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 1]
```diff
@@ -33,28 +34,25 @@ const CurveSpreadsheet = ({
...
+    return filledMatrix;
   }, [selectedCurve]);
 
-  const updateRollingStockCurve = (e: Matrix<{ value: string }>) => {
+  const columns = [
+    { ...keyColumn('speed', intColumn), title: t('speed') },
+    { ...keyColumn('effort', floatColumn), title: t('effort') },
+  ];
+
+  const updateRollingStockCurve = (newCurve: { speed: string; effort: string }[][]) => {
```
Comment (SharglutDev) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: You probably should create a type for the curves as you use it in multiple files

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 2]
```diff
@@ -30,45 +35,43 @@ const CurveSpreadsheet = ({
   isDefaultCurve,
 }: CurveSpreadsheetProps) => {
   const { t } = useTranslation('rollingstock');
+  const columns = [
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: use useMemo here (dependencies : [t])

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done !

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 3]
```diff
@@ -30,45 +35,43 @@ const CurveSpreadsheet = ({
...
-            // Effort needs to be displayed in kN
-            { value: effort !== undefined ? Math.round(effort / 1000).toString() : '' },
-          ])
-        : [];
-    const numberOfRows = filledMatrix.length < 8 ? 8 - filledMatrix.length : 1;
-    return filledMatrix.concat(createEmptyMatrix<CellBase<string>>(numberOfRows, 2));
-  }, [selectedCurve]);
+  const [needsSort, setNeedsSort] = useState<boolean>(false);
+
+  const handleBlur = () => {
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Use useCallback here

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 4]
```diff
@@ -30,45 +35,43 @@ const CurveSpreadsheet = ({
...
+    setNeedsSort(true);
+  };
 
-  const updateRollingStockCurve = (e: Matrix<{ value: string }>) => {
+  const updateRollingStockCurve = (newCurve: DataSheetCurve[]) => {
     if (!selectedTractionMode || !effortCurves) return;
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Change the type in the props of selectedTractionMode and effortCurves to make them non nullable (you can add a `&& effortCurves` in RollingStockEditorCurves l215 to check effortCurves are not null).

Then remove this test

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 5]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
...
+      }));
+    }
+
+    // Add an empty line for input only if last line is not already empty
+    if (
+      filledDataSheet.length === 0 ||
+      filledDataSheet[filledDataSheet.length - 1].speed !== '' ||
+      filledDataSheet[filledDataSheet.length - 1].effort !== ''
+    ) {
+      filledDataSheet.push({ speed: '', effort: '' });
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: With the new librairy, the cell can be nullable (before, if the cell was empty, then its value was `''`). We should take advantage of what the librairy gives us:
- [x] change every time you test if a value is `''` to test if it is `null`
- [x] in formatCurve, test whether a cell is null
- [x] in the type DataSheetCurve, the type should be `number | null` instead of `number | string` for both speed and effort
- [x] also change the type in EffortCurveForm, `number | null` instead of `number | undefined`
- [x] in spreadsheetCurve (l94), test whether the speed and effort are null instead of undefined (and set them to null instead of `''`)
- [x] update the function `filterUndefinedValueInCurve` and rename it `filterNullValueInCurve`
- [x] change the initialization of a new row like this
```suggestion
      filledDataSheet.push({ speed: null, effort: null });
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 6]
```diff
@@ -30,45 +35,43 @@ const CurveSpreadsheet = ({
...
-  const updateRollingStockCurve = (e: Matrix<{ value: string }>) => {
+  const updateRollingStockCurve = (newCurve: DataSheetCurve[]) => {
     if (!selectedTractionMode || !effortCurves) return;
-    const formattedCurve = formatCurve(e);
 
+    // Sort and format the curve for display
+    const sortedSpreadsheetValues = newCurve.map((item) => ({
+      speed: item.speed === null ? '' : item.speed,
+      effort: item.effort === null ? '' : item.effort,
+    }));
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: It's not needed anymore if you use `null` everywhere instead of `''` and `undefined`
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 7]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
         ...(isDefaultCurve ? { default_curve: formattedCurve } : {}),
       },
     };
+
+    // Set the updated effort curves
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Not necessary, since the code is quite straightforward
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 8]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
...
+    const { speeds, max_efforts } = selectedCurve.curve;
+    let filledDataSheet: DataSheetCurve[] = [];
+
+    if (speeds && max_efforts) {
+      filledDataSheet = max_efforts.map((effort, index) => ({
+        speed: speeds[index] !== undefined ? Math.round(msToKmh(speeds[index]!)) : '',
+        // Effort needs to be displayed in kN
+        effort: effort !== undefined ? effort / 1000 : '',
+      }));
+    }
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: max_efforts and speeds are always defined, so no need for the test :+1: 
```suggestion
    let filledDataSheet: DataSheetCurve[] = max_efforts.map((effort, index) => ({
      speed: speeds[index] !== null ? Math.round(msToKmh(speeds[index]!)) : null,
      // Effort needs to be displayed in kN
      effort: effort !== null ? effort / 1000 : null,
    }));
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 9]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
...
+  useEffect(() => {
+    if (needsSort) {
+      const sortedSpreadsheetValues = spreadsheetCurve
+        // Filter out the last line if speed and effort are not filled
+        .filter((item, index, array) => {
+          if (index === array.length - 1) {
+            return item.speed !== '' && item.effort !== '';
+          }
+          return true;
+        })
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: I'm not sure this is very useful, the row will be filtered line 123 no ? :thinking_face:
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 10]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
...
+        .filter((item) => item.speed !== null || item.effort !== null)
+        .filter((item) => item.speed !== '' || item.effort !== '')
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Not needed now than you use only null
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx [hunk 11]
```diff
@@ -77,30 +80,69 @@ const CurveSpreadsheet = ({
...
+        .sort((a, b) => {
+          if (a.speed === '' && b.speed === '') return 0;
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: This case should not happen
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts [hunk 12]
```diff
@@ -1,39 +1,22 @@
...
- * - remove rows which have at least 1 empty cell
- * - remove non digit characters in each cell
  * - convert rows data to EffortCurve
  */
-export default function formatCurve(sheetValues: Matrix<{ value: string }>) {
-  const validRows = filterUnvalidRows(sheetValues);
-  const numericRows = removeNonDigitCharacters(validRows);
-  return formatToEffortCurve(numericRows);
-}
+const formatCurve = (sheetValues: DataSheetCurve[]) => formatToEffortCurve(sheetValues);
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts]: Rename `formatToEffortCurve` => `formatCurve` and move the comment :) 
```suggestion
```

File: front/src/modules/rollingStock/types.ts [hunk 13]
```diff
@@ -122,6 +122,11 @@ export type ElectricalProfileByMode = {
   thermal: null[];
 };
 
+export type DataSheetCurve = {
+  speed: number | string;
+  effort: number | string;
```
Comment (clarani) [inline front/src/modules/rollingStock/types.ts]:
```suggestion
  speed: number | null;
  effort: number | null;
```

**Review by clarani — CHANGES_REQUESTED** [review]
Very nice PR, nice job :muscle:

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 2 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done !

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 3 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 4 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Done

File: front/src/modules/rollingStock/types.ts (hunk 13 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/types.ts]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts (hunk 12 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 11 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 10 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 8 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 6 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 5 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Done

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx (hunk 9 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveSpreadsheet.tsx]: Done

File: front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts [hunk 14]
```diff
@@ -1,22 +1,27 @@
...
+        result.speeds.push(null);
+      }
+
+      // Test whether the effort cell is null before converting
+      if (row.effort !== null) {
+        // Back-end needs effort in newton
+        result.max_efforts.push(Number(row.effort) * 1000);
+      } else {
+        result.max_efforts.push(null);
+      }
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts]: I think this is enough :)
```suggestion
      result.speeds.push(row.speed !== null ? kmhToMs(Number(row.speed)) : null);
      // Back-end needs effort in newton
      result.max_efforts.push(row.effort !== null ? Number(row.effort) * 1000 : null);
```

**Review by clarani — APPROVED** [review]
LGTM, tested and everything works well :white_check_mark:

File: front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts (hunk 14 above)
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/formatSpreadSheetCurve.ts]: Ty, fixed :)
