### PR TITLE
front: fix fetching of path steps ch and uic when pathinfinding fails

### LINKED ISSUE #15648: front: itinerary modal: ch and uic are no longer displayed when pathfinding fails
### What happened?

When the pathfinding fails, we still fetch the name, coordinates, uic and ch of all path steps in order to display as much information as possible. This information used to be displayed in the itinerary modal for all valid path steps.

However, while this information is still displayed when the pathfinding is succesful, it is no longer displayed when the pathfinding fails.

This is probably linked to the many changes in the format of path steps in the last 6 months (for example https://github.com/OpenRailAssociation/osrd/pull/13057 )

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Import a failed train with path steps using locations of type id. (For example failed imports from basic.)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev

### PR DESCRIPTION
**Pull request by Synar**
Close https://github.com/OpenRailAssociation/osrd/issues/15648

### CODE REVIEW

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 1]
```diff
@@ -111,8 +111,16 @@ const usePathfinding = ({
...
           ...step,
           ...(op.extensions?.identifier?.name && { name: op.extensions.identifier.name }),
-          ...(op.extensions?.identifier?.uic && { uic: op.extensions.identifier.uic }),
-          ...(op.extensions?.sncf?.ch && { ch: op.extensions.sncf.ch }),
+          ...(op.extensions?.identifier?.uic &&
+            op.extensions?.sncf?.ch && {
+              location: {
+                operational_point: {
+                  uic: op.extensions.identifier.uic,
+                  secondary_code: op.extensions.sncf.ch,
```
Comment (emersion) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: Some infras have UICs without a secondary code. Could we leave secondary code unset in that case?

**Review by emersion — COMMENTED** [review]
I wonder why TypeScript isn't complaining here… I would've expected an "object literal can only specify known properties" error.

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: We could indeed also set uic even without a ch present. I wanted to be conservative here, as unlike before we have to erase the id based location, so I was wary of losing information - although I don't think it's ever an actual issue.

**Comment by Synar** [comment]
> object literal can only specify known properties

I think the spreading operator unfortunately bypasses this check

**Comment by Synar** [comment]
image
image

**Comment by Synar** [comment]
Perhaps we should reduce our usage of the spreading operator then?

**Review by emersion — APPROVED** [review]
