### PR TITLE
editoast: add enabled window for stdcm search env table

### LINKED ISSUE #10838: lmr: time window for possible simulations is incorrect
### What happened?

Now : one can start a simulation with a departure between J+1 17h and J+7 (anytime), no matter when the simulation is done.

### What did you expect to happen?

The expected behavior is : 
Before 17h, one can start a simulation between J+1 and J+7 (anytime for both)
After 17h, one can start a simulation between J+2 and J+7 (anytime for both)

### How can we reproduce it (as minimally and precisely as possible)?

-

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8aaefd4

### PR DESCRIPTION
**Pull request by flomonster**
close #10838

### CODE REVIEW

File: editoast/editoast_models/src/tables.rs [hunk 1]
```diff
@@ -671,6 +671,8 @@ diesel::table! {
         search_window_begin -> Timestamptz,
         search_window_end -> Timestamptz,
         temporary_speed_limit_group_id -> Nullable<Int8>,
+        enabled_from -> Timestamptz,
+        enabled_to -> Timestamptz,
```
Comment (Castavo) [inline editoast/editoast_models/src/tables.rs]: We could solve our problem with only an expiration date, I don't know if that was considered in the refinement

Comment (flomonster) [reply editoast/editoast_models/src/tables.rs]: We didn't think of that. But would the criterion be to take all environments that haven't expired and take the one with the expiration date closest to `now()`?

Comment (Castavo) [reply editoast/editoast_models/src/tables.rs]: ~~You could use the same criterion as today: the one that hasn't expired with the largest id~~

Yes, taking the one closest to now() would be necessary, I didn't think of that, that feels flaky for some reason.

In our use of the current model, the `enabled_to` would be equal to the `enabled_from` of the next search env right ?
We could acknowledge this redundancy  ?

It might not actually be that flaky... when thinking about those dates simply as points along the timeline it seems okay.

I don't really know, the idea of the single date crossed my mind, I don't know if it's better, it was simply to make sure it had been considered, the current model is okay

File: editoast/src/views/stdcm_search_environment.rs [hunk 2]
```diff
@@ -250,27 +284,19 @@ pub mod tests {
...
     }
 
     #[rstest]
     async fn retrieve_stdcm_search_env_not_found() {
+        use editoast_models::tables::stdcm_search_environment::dsl::*;
         // GIVEN
         let app = TestAppBuilder::default_app();
-
-        let _ = StdcmSearchEnvironment::delete_all(&mut app.db_pool().get_ok()).await;
+        diesel::delete(stdcm_search_environment)
```
Comment (Castavo) [inline editoast/src/views/stdcm_search_environment.rs]: Isn't using diesel in the `views` crate frowned upon these days ?

File: editoast/src/models/stdcm_search_environment.rs [hunk 3]
```diff
@@ -30,46 +28,54 @@ pub struct StdcmSearchEnvironment {
...
+    /// The end of the search time window.
     pub search_window_end: DateTime<Utc>,
     #[schema(nullable = false)]
     #[serde(skip_serializing_if = "Option::is_none")]
     pub temporary_speed_limit_group_id: Option<i64>,
+    /// The time window start point where the environment is enabled.
+    pub enabled_from: DateTime<Utc>,
+    /// The time window end point where the environment is enabled.
+    /// This value is usually lower than the `search_window_begin`, since a search is performed before the train rolls.
+    pub enabled_to: DateTime<Utc>,
```
Comment (Castavo) [inline editoast/src/models/stdcm_search_environment.rs]: `enabled_until` seems more idiomatic

**Review by Castavo — APPROVED** [review]
`diesel migration redo` ✅ 
Tested sending several envs and retrieving them ✅ 
The front behaves correctly ✅ 
When adding a new env, reloading the front does pull the new env.

File: editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql [hunk 4]
```diff
@@ -0,0 +1,3 @@
+ALTER TABLE stdcm_search_environment
+ADD COLUMN enabled_from TIMESTAMP WITH TIME ZONE DEFAULT '1970-01-01 00:00:00' NOT NULL,
+    ADD COLUMN enabled_to TIMESTAMP WITH TIME ZONE DEFAULT '1970-01-02 00:00:00' NOT NULL;
```
Comment (woshilapin) [inline editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql]: Should we index these new columns?

File: editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql
Comment (woshilapin) [inline editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql:1]: Formatting of the file looks weird. Maybe the second line can end with a `;` instead?

File: editoast/src/models/stdcm_search_environment.rs [hunk 5]
```diff
@@ -30,46 +28,54 @@ pub struct StdcmSearchEnvironment {
...
+        // Search for the most recent env
+        tracing::warn!("No STDCM search environment enabled");
         stdcm_search_environment
-            .order_by((search_window_end.desc(), search_window_begin.asc()))
+            .order_by((enabled_to.desc(), id.desc()))
             .first::<Row<StdcmSearchEnvironment>>(conn.write().await.deref_mut())
             .await
             .map(Into::into)
             .ok()
     }
```
Comment (woshilapin) [inline editoast/src/models/stdcm_search_environment.rs]: nitpick: Maybe this would be more idiomatic?

```rust
enabled_env.or_else(|| {
    tracing::warn!("No STDCM search environment enabled");
    stdcm_search_environment
        .order_by((enabled_to.desc(), id.desc()))
        .first::<Row<StdcmSearchEnvironment>>(conn.write().await.deref_mut())
        .await
        .map(Into::into)
        .ok()
})

File: editoast/src/views/stdcm_search_environment.rs [hunk 6]
```diff
@@ -106,7 +121,7 @@ impl From<StdcmSearchEnvironmentCreateForm> for Changeset<StdcmSearchEnvironment
         (status = 201, body = StdcmSearchEnvironment),
     )
 )]
-async fn overwrite(
+async fn create(
```
Comment (woshilapin) [inline editoast/src/views/stdcm_search_environment.rs:124]: Does this mean that we're going to create data that will never be deleted anymore?

File: editoast/src/views/stdcm_search_environment.rs (hunk 2 above)
Comment (flomonster) [reply editoast/src/views/stdcm_search_environment.rs]: Yeah true. I'll fix it

File: editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql (hunk 4 above)
Comment (flomonster) [reply editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql]: Yeah, this could avoid a full scan when retrieving an env.

File: editoast/src/views/stdcm_search_environment.rs (hunk 6 above)
Comment (flomonster) [reply editoast/src/views/stdcm_search_environment.rs:124]: We could add a delete endpoint so the user can handle and clean the history.

File: editoast/editoast_models/src/tables.rs (hunk 1 above)
Comment (flomonster) [reply editoast/editoast_models/src/tables.rs]: IMO, even if it's okay semantically, It makes the sql more flaky

File: editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql
Comment (flomonster) [reply editoast/migrations/2025-02-19-173042_adapt_search_environment_adding_enabled_window/up.sql:1]: I did format this file (I'm using the default vs code formatter). Ending with a `;` won't be valid sql.

File: editoast/src/models/stdcm_search_environment.rs (hunk 5 above)
Comment (flomonster) [reply editoast/src/models/stdcm_search_environment.rs]: It requires an async closure. So IMO it's simpler as it is.

File: editoast/editoast_models/src/tables.rs (hunk 1 above)
Comment (Castavo) [reply editoast/editoast_models/src/tables.rs]: Okay 😁

File: editoast/src/models/stdcm_search_environment.rs [hunk 7]
```diff
@@ -30,25 +29,50 @@ pub struct StdcmSearchEnvironment {
...
-            .order_by((search_window_end.desc(), search_window_begin.asc()))
+            .order_by((enabled_until.desc(), id.desc()))
             .first::<Row<StdcmSearchEnvironment>>(conn.write().await.deref_mut())
             .await
             .map(Into::into)
             .ok()
     }
 
+    /// Delete all existing search environments.
     pub async fn delete_all(conn: &mut DbConnection) -> Result<(), model::Error> {
```
Comment (leovalais) [inline editoast/src/models/stdcm_search_environment.rs:78]:
```suggestion
	#[cfg(test)]
    pub async fn delete_all(conn: &mut DbConnection) -> Result<(), model::Error> {
```

**Review by leovalais — APPROVED** [review]
LGTM

File: editoast/src/views/stdcm_search_environment.rs (hunk 6 above)
Comment (flomonster) [reply editoast/src/views/stdcm_search_environment.rs:124]: We also require an endpoint to list search environments. I suggest we do this in another PR.

**Review by Maymanaf — APPROVED** [review]
