### PR TITLE
Fix timestops margins

### LINKED ISSUE #8066: Cannot add a margin of 0%
### What happened?

When adding a 0% or 0min/100km in a margin, right now we get an editoast error : 

Capture d’écran 2024-07-16 à 11 30 40

### What did you expect to happen?

- It should be possible to add a 0% margin to reset any previous margin.
- Remove "none" from possible value in margin values (and so editoast now accepts 0% or 0min/100km)
- set the origin default's margin to 0% after a pathfinding

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to "Times and stop" tab
2. Add a 0% margin

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

65e7f5b2411c04690f5457712de980b68d842a22

### LINKED ISSUE #8067: Cannot set margin on origin
### What happened?

When setting a margin on the origin point, it disappears after saving.

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to "Times and stops"
2. Add a margin of 5% to the origin
3. Save
4. Open again the "Times and stops" tab
5. Witness the disappearance of the margin

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

65e7f5b2411c04690f5457712de980b68d842a22

### PR DESCRIPTION
**Pull request by SharglutDev**
See commits for details

close #8066 
close #8067

### CODE REVIEW

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 1]
```diff
@@ -6,16 +6,18 @@ const formatMargin = (pathSteps: PathStep[]): Margin | undefined => {
...
-        boundaries.push(step.id);
+        boundaries.push(id);
         values.push('none');
       }
-    } else if (step.theoreticalMargin) {
-      boundaries.push(step.id);
-      values.push(step.theoreticalMargin);
+    } else if (theoreticalMargin) {
+      boundaries.push(id);
+      values.push(theoreticalMargin.startsWith('0') ? 'none' : theoreticalMargin);
```
Comment (emersion) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Seems safer to use `=== '0%'` here, I think? The user may enter e.g. `05%`.

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts [hunk 2]
```diff
@@ -6,16 +6,18 @@ const formatMargin = (pathSteps: PathStep[]): Margin | undefined => {
   const values: string[] = [];
 
   pathSteps.forEach((step, index) => {
+    const { id, theoreticalMargin } = step;
```
Comment (emersion) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: We can destructure the object directly in the function arguments here:

```js
pathSteps.forEach(({ id, theoreticalMargin }, index) => {
```

File: front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts [hunk 3]
```diff
@@ -24,6 +24,8 @@ import { ISO8601Duration2sec } from 'utils/timeManipulation';
 
 import type { ManageTrainSchedulePathProperties } from '../types';
 
+const checkMarginValue = (margin: string) => (margin !== 'none' ? margin : '0%');
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts]: Suggestion: maybe `normalizeMarginValue` would be a better name?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: I thought about that but if we do that we need also to check `=== '0km/100km'`

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Oh yes, good point

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 1 above)
Comment (emersion) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Yeah, I think I'd prefer to tighten up the checks and hit editoast errors in weird cases like `000%`, instead of silently changing the value the user entered in weird cases like `05%`.

Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatMargin.ts]: Done

File: front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts (hunk 3 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/hooks/useSetupItineraryForTrainUpdate.ts]: Done

**Comment by emersion** [comment]
Seems like there is a strange side-effect of this PR: when no margin is set, clicking on the margin cell for the origin in the table prefills with "none":

out

**Comment by emersion** [comment]
Also, after saving a margin on the origin and re-editing the train, there is a "0%" one showing up on the destination:

out

**Comment by SharglutDev** [comment]
Thank you for spotting these. Should be fixed.

**Review by emersion — APPROVED** [review]
LGTM!

editoast throws an error when setting a 0% margin on origin but this is being discussed separately.

**Review by shenriotpro — APPROVED** [review]
LGTM for tests/

**Review by leovalais — APPROVED** [review]
LGTM (editoast; not tested)

**Review by Math-R — DISMISSED** [review]
lgtm & tested

**Review by flomonster — APPROVED** [review]
Go :tada:

**Review by Math-R — APPROVED** [review]
Find a bug unrelated to this PR, lgtm
