### PR TITLE
editoast: fix stdcm trace disconnect

### LINKED ISSUE #16262: stdcm: datadog spans are disconnected at the transition from editoast to core
When looking at a trace for a given stdcm request, we *used to* have one span that goes all the way from editoast to core. And that trace_id is used for logging and debugging.

Since the live progress feature, we now have two disconnected trace. The editoast trace doesn't seem to know what it's waiting for, and the core trace spawns with no context. No way to connect these two. The files generated by core are registered under the "wrong" ID.

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/16262

I moved the lambda into a named variable, otherwise adding the `.instrument` directly to the inlined block would make the linter add an extra indentation over the entire block

Tested locally with jaeger and by checking that core generates s3 data on the ID returned to the front-end

### CODE REVIEW

File: editoast/src/views/timetable/stdcm.rs [hunk 1]
```diff
@@ -487,7 +488,8 @@ pub(in crate::views) async fn stdcm_handler(
                 break;
             }
         }
-    });
+    };
+    spawn(stream_result_lambda.instrument(Span::current()));
```
Comment (leovalais) [inline editoast/src/views/timetable/stdcm.rs]:
```suggestion
    spawn(stream_result_lambda.in_current_span());
```

https://docs.rs/tracing/latest/src/tracing/instrument.rs.html#128

**Review by leovalais — APPROVED** [review]

**Review by woshilapin — APPROVED** [review]
