### PR TITLE
front: fix rollingStockComfort display persistance in simulation

### LINKED ISSUE #2758: No persistance on RollingStockConfort Display
### What happened?

On Simulation config screen, after having a rollingStockConfort Selected, if you reopen this sotck in the rollingStock list, the confort previously selected is not preseclected, whereas it is persistant in the redux store.

### What did you expect to happen?

We should retrieve the previously selected confort

### How can we reproduce it (as minimally and precisely as possible)?

Capture d’écran 2023-01-04 à 10 42 52

(selected heating)

Capture d’écran 2023-01-04 à 10 42 41

(not showed)

### What operating system and browser are you using? (if applicable)

- Windows 10
- Google Chrome 22

### OSRD version

1.0

### PR DESCRIPTION
**Pull request by Yohh**
close #2758

### CODE REVIEW

File: front/src/common/RollingStockSelector/RollingStockCardButtons.js [hunk 1]
```diff
@@ -40,6 +42,10 @@ export default function RollingStockCardButtons(props) {
     return options;
   };
 
+  useEffect(() => {
```
Comment (alexandredamiron) [inline front/src/common/RollingStockSelector/RollingStockCardButtons.js:45]: Please add the rollingStockConmfort dependency in the array

Comment (Yohh) [reply front/src/common/RollingStockSelector/RollingStockCardButtons.js:45]: done

**Review by alexandredamiron — APPROVED** [review]

**Review by alexandredamiron — APPROVED** [review]
