### PR TITLE
core: etcs: make etcs envelope parts strictly monotonic

### LINKED ISSUE #13804: core: ETCS simulation fails with margin
### What happened?

❌ On etcs_infra (on dev, supposedly the same than in code-base), when importing [errorMarginTimetable2.json](https://github.com/user-attachments/files/23169887/errorMarginTimetable2.json) we get an error (no matter the type or the value of the margin).
✅ When removing the margin it works.
✅ The train works fine on small_infra
✅ Moving the start seems to sometime work (at least when using the buffer-stop of the same track)

### What did you expect to happen?

Expected ETCS simulation to work in that case.

### How can we reproduce it (as minimally and precisely as possible)?

Either on dev go to https://dev-osrd.reseau.sncf.fr/operational-studies/projects/101/studies/462/scenarios/1375?projection=trainschedule_9254526&selected_train=trainschedule_10469002 and check "test" train.

Or locally:
* load etcs_infra
* use that infra for an operational study
* import attached file
* observe it break

### On which environments the bug occurs?

Dev (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

eb865d0

### PR DESCRIPTION
**Pull request by Erashin**
Fixes https://github.com/OpenRailAssociation/osrd/issues/13804.

Fix keepBrakingCurveUnderOverlay so it does not combine the entry envelope parts into one, which made it possible for the result to not be strictly monotonous (ex: one of the entry parts is constant). This would break other parts of the code, and in this case, speed interpolation during margin computation, which can't be done on a non-strictly monotonous envelope part.

Integration test uses the train_schedule specified in the bug :)

### CODE REVIEW

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 1]
```diff
@@ -542,29 +539,46 @@ private fun keepBrakingCurveUnderOverlay(
...
+        }
+        // No intersection was found: add full part.
+        newBrakingParts.addFirst(brakingCurvePart)
     }
-    return BrakingCurve(etcsBrakingCurve.brakingType, Envelope.make(partBuilder.build()))
+    return BrakingCurve(
+        etcsBrakingCurve.brakingType,
+        Envelope.make(*newBrakingParts.toTypedArray()),
+    )
 }
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt:566]: Adding a test would be nice

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 2]
```diff
@@ -542,29 +539,46 @@ private fun keepBrakingCurveUnderOverlay(
...
+                    brakingCurvePart.getStepTime(i),
+                )
+            ) {
+                // An intersection was found: new braking curve stops here.
+                newBrakingParts.addFirst(partBuilder.build())
+                break@computeCurveUnderOverlayLoop
+            }
+        }
+        // No intersection was found: add full part.
+        newBrakingParts.addFirst(brakingCurvePart)
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: More of a taste: Not fan of imbricated `for`, and a long fn already, so I'd go for extracting to a fn.
Probably naming it `getSectionOfCurvePartUnderOverlay`.

**Review by bougue-pe — APPROVED** [review]
Nice job!
~(although I didn't hand-test it btw)~ Tested since.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 2 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Hmm this won't actually work. l572, there's a break that breaks out of the full for loop (`break@computeCurveUnderOverlayLoop`). It is needed because as soon as we find an intersection with the overlay, we have to discard the rest of the envelope parts.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 1 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt:566]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/14481/commits/a8662753664698d0b876385ed3a175e46f2beb92. Used the rolling_stock given in the bug description :)

**Review by shenriotpro — APPROVED** [review]
thanks

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 2 above)
Comment (Khoyo) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: We ccould use find() instead of the for loop though

File: tests/tests/test_train_schedule.py [hunk 3]
```diff
@@ -1415,6 +1415,65 @@ def test_etcs_stop_at_requirements_eoa(
     assert spacing_req_zone_stop["end_time"] == 842_038
 
 
+def test_etcs_train_schedule_with_margins(
+    etcs_scenario: Scenario, etcs_rolling_stock: int, session: Session
+):
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py:1420]: nit: Adding a little context would be nice when we later come back to it (you may have better idea):
```suggestion
def test_etcs_train_schedule_with_margins(
    etcs_scenario: Scenario, etcs_rolling_stock: int, session: Session
):
    """
    Testing a valid ETCS train-schedule with margin that was failing because of
    a tricky case of braking-curve interpolation
    """
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 2 above)
Comment (bougue-pe) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Hmm, indeed, we could then have a `getSectionOfCurvePartUnderOverlayIfIntersect` that would return `null` if no intersection and we'd know when to break if encapsulating curve.

Just sharing the idea, in case it resonates, feel free to resolve without it for that part (I find it just a little bit better with extra fn).

Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: > We ccould use find() instead of the for loop though

Doesn't really work, as the loop also builds an envelope part which stops at the intersection. If I use find, i'll get the envelope part which has the intersection with the overlay, but I'd need to determine it again to build the needed partial envelope part.



> Hmm, indeed, we could then have a `getSectionOfCurvePartUnderOverlayIfIntersect` that would return `null` if no intersection and we'd know when to break if encapsulating curve.

I had thought about a method that returns the intersecting part or null, and if null we just add the full ennvelope part. Thought it would be a tad too complex for the need. I'll look into it and see if I can manage to make it work :)

File: tests/tests/test_train_schedule.py (hunk 3 above)
Comment (Erashin) [reply tests/tests/test_train_schedule.py:1420]: I'll add it with a slight modification `case of speed interpolation`.

Fixed in https://github.com/OpenRailAssociation/osrd/pull/14481/commits/87ef7c25f4f3826193d11f19dffcca2956f41e3d.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 2 above)
Comment (bougue-pe) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: 🙏 Thanks for the change (little bit better IMO), the "goto" redflag is now gone in my head 😅
