### PR TITLE
Fix wrong propagation and midnight crossing in new schedule sheet

### LINKED ISSUE #16163: New schedule sheet : Propagation value not correctly computed
### What happened?

The propagation values displayed in the menu are sometimes a bit weird

https://github.com/user-attachments/assets/548113d3-8ee7-4a32-9fea-adb6e7e74d05

- Case 1 : It should be -5' for all directions 
- Case 2 : It works well
- Case 3 : It should be -10' for all directions

### What did you expect to happen?
- In particular, it never works for the first line 
- For the other lines, it seems like the algorithm uses the value computed at the previous point. It should rather use last time value REQUESTED before this point

We should ALWAYS use the requested times. Never the computed times

All cases are listed here : 

https://sncf.sharepoint.com/:x:/r/sites/OSRD644GrpO365/Documents%20partages/PO/Horizon/Tableau%20input-output/Cas%20propagation.xlsx?d=wc028e1c102564c1b8f2a99a6a41d2dee&csf=1&web=1&e=nmFozE

### How can we reproduce it (as minimally and precisely as possible)?

Use the video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

d149545

### LINKED ISSUE #16294: Timestops table: D+1 banner in the wrong place
### What happened?

On this train on small infra: [timetable.json](https://github.com/user-attachments/files/26784339/timetable.json)

Image

the banner shows before the last step instead of between steps 2 and 3 (the train starts on april 16th)

### What did you expect to happen?

the banner shows between steps 2 and 3

### How can we reproduce it (as minimally and precisely as possible)?

using the above timetable on small infra

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

ee2f84f

### PR DESCRIPTION
**Pull request by Caracol3**
> [!NOTE]
> This pull resquest is based on the refacto in #16231 

close #16294 
close #16163

### CODE REVIEW

**Comment by SharglutDev** [comment]
Tested some behaviors with @maelysLeratRosso, we have a few weird things :

- On Test 10, we changed the arrival time on MWS from 10:07 to 10:02 propagating to destination and we have this : 
image

We expect to have a D+1 banner before MWS but not after.

- When exporting Test 10, we see this : 
image

We expect the arrival time of path step 2, 3 and 4 to have 24h+ on the times (24h + 2min, 24h + 15min, 24h + 20min).
This means the D+1 banner probably doesn't work exactly with the schedule input which is weird.

- When exporting Test 7,  we changed on MWS from 10:07 to 10h:22 propagating to origin we see this : 
image

We expect the arrival time of path step 3 and 4 to have 24h+ on the times (24h + 5min, 24h + 10min)

Pretty weird that sometimes the 24h+ works on the times and sometimes not

For example on Test 9 where the export works, we changed MWS from 10:07 to 10:02 only at this point.

**Comment by SharglutDev** [comment]
This makes me think we should add unit tests for all the expected behaviors with the 4 propagation types. 
This will be a lot but will ensure this keeps steady. (Can be done in a different PR once we have a stable behavior)

**Comment by Synar** [comment]
Nice! I may have misread the code, but it seems to me you have to check for new days in quite a few places. I wonder if there would be a way to have a single function for this that we would always call after propagateTime (or the atThisWaypoint case) that would add a day whenever requested time goes back in time, to generalize all of this. Feel free to ignore if you disagree ^^

**Comment by Caracol3** [comment]
> This makes me think we should add unit tests for all the expected behaviors with the 4 propagation types. This will be a lot but will ensure this keeps steady. (Can be done in a different PR once we have a stable behavior)

Indeed, given the number of specific cases we have, unit tests are a good idea. I’ll handle that in a dedicated PR.

**Comment by Caracol3** [comment]
> Nice! I may have misread the code, but it seems to me you have to check for new days in quite a few places. I wonder if there would be a way to have a single function for this that we would always call after propagateTime (or the atThisWaypoint case) that would add a day whenever requested time goes back in time, to generalize all of this. Feel free to ignore if you disagree ^^

Totally agree, but I think this deserves its own refactor once the behavior is solid.

**Comment by Caracol3** [comment]
> Tested some behaviors with @maelysLeratRosso, we have a few weird things :
> 
>     * On Test 10, we changed the arrival time on MWS from 10:07 to 10:02 propagating to destination and we have this :
> 
> 
> image
> 
> We expect to have a D+1 banner before MWS but not after.
> 
>     * When exporting Test 10, we see this :
> 
> 
> image
> 
> We expect the arrival time of path step 2, 3 and 4 to have 24h+ on the times (24h + 2min, 24h + 15min, 24h + 20min). This means the D+1 banner probably doesn't work exactly with the schedule input which is weird.
> 
>     * When exporting Test 7,  we changed on MWS from 10:07 to 10h:22 propagating to origin we see this :
> 
> 
> image
> 
> We expect the arrival time of path step 3 and 4 to have 24h+ on the times (24h + 5min, 24h + 10min)
> 
> Pretty weird that sometimes the 24h+ works on the times and sometimes not
> 
> For example on Test 9 where the export works, we changed MWS from 10:07 to 10:02 only at this point.

I tested every cases (twice 😅 ) and the expected behaviors are now really the ones defined in this file:
https://sncf.sharepoint.com/:x:/r/sites/OSRD644GrpO365/_layouts/15/Doc.aspx?sourcedoc=%7BC028E1C1-0256-4C1B-8F2A-99A6A41D2DEE%7D&file=Cas%20propagation.xlsx&action=default&mobileredirect=true

**Comment by SharglutDev** [comment]
Indeed everything is fixed for the scope of your PR !

But some behaviors are not good for the origin, not sure if it was already broken on Alice pr or if the rebase broke something : 

1.
[Capture vidéo du 2026-04-22 09-14-04.webm](https://github.com/user-attachments/assets/b4483d1c-9cf9-4caf-b71d-6ed56171f251)

Here we expect all the arrival times to be affected.

2.
image

Here the origin was at 10:05 and we entered 10:00. If we click, it behaves good without adding a D+1 but it should not display 23:55. 
Another example, if we enter 00:00 (midnight), we expect to see 10:00 everywhere.

File: front/src/modules/timesStops/TimesStopsOutput.tsx [hunk 1]
```diff
@@ -116,12 +116,41 @@ const TimesStopsOutput = ({
...
+                    : null,
+              },
+            ],
+            bumped,
+          ];
+        }
+        return [[...acc, row], row.requestedArrival];
+      },
+      [[], null]
+    )[0];
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimesStopsOutput.tsx]: This `reduce` feels weird. Having `lastArrival` only for computation purposes but not keeping it at the end.

We could rather use a `map` : 
```
let lastArrival: Date | null = null;
  return rows.map((row) => {
    if (row.requestedArrival === null) return row;
    if (lastArrival !== null && row.requestedArrival < lastArrival) {
      const bumped = addDurationToDate(row.requestedArrival, ONE_DAY);
      lastArrival = bumped;
      return {
        ...row,
        requestedArrival: bumped,
        requestedDeparture:
          row.requestedDeparture !== null
            ? addDurationToDate(row.requestedDeparture, ONE_DAY)
            : null,
      };
    }
    lastArrival = row.requestedArrival;
    return row;
  });
```

> [!NOTE]
> React won't allow reassign `lastArrival` inside a `map` in the `useMemo` so you will have to extract this in a function

File: front/src/modules/timesStops/TimesStopsOutput.tsx [hunk 2]
```diff
@@ -206,11 +235,33 @@ const TimesStopsOutput = ({
     update: CellUpdate & { propagationMode: PropagationMode }
   ): PendingEdit[] => {
     const propagationResult = propagateTime(update, selectedTrain);
+    if (!propagationResult) return [singleEdit];
+
+    const propagationEdits = propagationToEdits(propagationResult, newRows);
+
+    // Origin arrival = start_time (not in schedule), so propagationToEdits misses it.
+    const originRow = newRows[0];
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimesStopsOutput.tsx]: nit: this way we can't forget to handle the `undefined` case even if you did it well (we could use a `!` here probably)
```suggestion
    const originRow = newRows.at(0);
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 3]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
+  const startTime = new Date(selectedTrain.start_time);
+  const editedPathIndex = selectedTrain.path.findIndex((step) => step.id === editedPathStepId);
+
+  const itemsAfter = (selectedTrain.schedule ?? [])
+    .map((item) => ({
+      item,
+      pathIndex: selectedTrain.path.findIndex((step) => step.id === item.at),
+    }))
+    .filter(({ item, pathIndex }) => item.arrival != null && pathIndex > editedPathIndex)
+    .sort((a, b) => a.pathIndex - b.pathIndex);
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: nit: not sure this is needed. Editoast returns the scheduled points at the same order than the path steps (but it doesn't hurt if you prefer to keep it).

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 4]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
+ */
+export const adjustFollowingWaypointsForMidnight = (
+  newValue: Date,
+  editedPathStepId: string,
+  selectedTrain: Train
+): ScheduleItem[] => {
+  const startTime = new Date(selectedTrain.start_time);
+  const editedPathIndex = selectedTrain.path.findIndex((step) => step.id === editedPathStepId);
+
+  const itemsAfter = (selectedTrain.schedule ?? [])
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: nit: for clarity
```suggestion
  const itemsAfterUpdatedStep = (selectedTrain.schedule ?? [])
```

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 3 above)
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: nit: it's probably a minor performance win but to avoid extra work for the browser, we could avoid creating intermediate arrays for the `map` and the `filter`. 
This can be done by using `Iterator`.
You can read this interesting [article](https://allthingssmitty.com/2026/01/12/stop-turning-everything-into-arrays-and-do-less-work-instead/?_bhlid=818fb07eaadba15e316b244ddda5fc869f6e4de6) for more details.


```suggestion
  const itemsAfter = Iterator.from(selectedTrain.schedule ?? [])
    .map((item) => ({
      item,
      pathIndex: selectedTrain.path.findIndex((step) => step.id === item.at),
    }))
    .filter(({ item, pathIndex }) => item.arrival != null && pathIndex > editedPathIndex)
    .toArray()
    .sort((a, b) => a.pathIndex - b.pathIndex);
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 5]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
+    }))
+    .filter(({ item, pathIndex }) => item.arrival != null && pathIndex > editedPathIndex)
+    .sort((a, b) => a.pathIndex - b.pathIndex);
+
+  let lastOffset = Duration.subtractDate(newValue, startTime);
+  const adjustments = new Map<string, string>();
+
+  for (const { item } of itemsAfter) {
+    const itemOffset = Duration.parse(item.arrival!);
+    const adjusted = itemOffset.ms < lastOffset.ms ? itemOffset.add(ONE_DAY) : itemOffset;
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]:
```suggestion
    const adjustedArrival = itemOffset.ms < lastOffset.ms ? itemOffset.add(ONE_DAY) : itemOffset;
```

Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: We could maybe check this condition in the `filter` above ? (itemsAfter would contain only the items after the updated step whose offset is smaller than the one of the updated value). This way we could have last iteration loops on the "for loop".

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 6]
```diff
@@ -54,17 +56,22 @@ const formatSignedDelta = (delta: Duration) => {
...
   oldValue: Date | null,
   newValue: Date | null,
-  mode: PropagationMode
+  mode: PropagationMode,
+  isOrigin = false
 ): string => {
-  const delta = computeDeltaForPropagationMode(oldValue, newValue, mode) ?? Duration.zero;
-  return formatSignedDelta(delta);
+  const delta = isOrigin
+    ? computeDelta(oldValue, newValue)
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts:65]: We could add a small doc here to explain why we don't want/need to propagate for the origin

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 7]
```diff
@@ -54,17 +56,22 @@ const formatSignedDelta = (delta: Duration) => {
...
+    : computeDeltaForPropagationMode(oldValue, newValue, mode);
+  return formatSignedDelta(delta ?? Duration.zero);
 };
 
 /**
  * Propagate a time edit along the path.
  * - toDestination: adds delta to arrivals from the edited point and after.
  * - fromDeparture: shifts start_time by +delta and arrivals after by -delta (they cancel out,
  *   so only the edited point and everything before it actually moves).
+ * In both cases, stops are processed in path order and any stop that ends up before the previous
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: I think ?
```suggestion
 * In both cases, steps are processed in path order and any step that ends up before the previous
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 8]
```diff
@@ -78,34 +85,56 @@ const propagateFromEditedPoint = (
...
+      item,
+      pathIndex: selectedTrain.path.findIndex((step) => step.id === item.at),
+    }))
+    .filter(({ item, pathIndex }) => {
+      if (item.arrival == null) return false;
+      return direction === 'fromDeparture'
+        ? pathIndex > editedPathIndex
+        : pathIndex >= editedPathIndex;
+    })
+    .sort((a, b) => a.pathIndex - b.pathIndex);
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: ditto for `Iterator` suggestion

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 9]
```diff
@@ -78,34 +85,56 @@ const propagateFromEditedPoint = (
...
+    direction === 'fromDeparture' ? addDurationToDate(currentStartTime, delta) : currentStartTime;
+
+  // Compute shifted offsets for all affected items, sorted by path order.
+  const affectedItems = (selectedTrain.schedule ?? [])
+    .map((item) => ({
+      item,
+      pathIndex: selectedTrain.path.findIndex((step) => step.id === item.at),
+    }))
+    .filter(({ item, pathIndex }) => {
+      if (item.arrival == null) return false;
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]:
```suggestion
      if (item.arrival === null) return false;
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 10]
```diff
@@ -78,34 +85,56 @@ const propagateFromEditedPoint = (
...
+  // If it falls before, it crossed midnight and gets +24h.
+  // For fromDeparture: the edited item is excluded from the loop, but its offset is the baseline —
+  // any shifted offset that falls before it gets +24h.
+  // For toDestination: the edited item is included in the loop, so start at 0.
+  const editedItem = selectedTrain.schedule?.find((item) => item.at === editedPathStepId);
+  const editedOldOffset = editedItem?.arrival ? Duration.parse(editedItem.arrival) : null;
+  let lastOffset =
+    direction === 'fromDeparture' && editedOldOffset !== null
+      ? editedOldOffset
+      : new Duration({ seconds: 0 });
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts:119]: Maybe I have some ignorance about what we are doing here but if the edited path step doesn't have a arrival already, we don't have the possibility to propagate, do we ?

If yes, the `else` is never met, I think ?

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 11]
```diff
@@ -78,34 +85,56 @@ const propagateFromEditedPoint = (
...
-      direction === 'fromDeparture' ? oldArrival.sub(delta) : oldArrival.add(delta);
-
-    return {
-      ...item,
-      arrival: newArrival.toISOString(),
-    };
-  });
+        ? Duration.parse(item.arrival!).sub(delta)
+        : Duration.parse(item.arrival!).add(delta);
+    const adjusted = shifted.ms < lastOffset.ms ? shifted.add(ONE_DAY) : shifted;
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]:
```suggestion
    const adjustedArrival = shifted.ms < lastOffset.ms ? shifted.add(ONE_DAY) : shifted;
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 12]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
-    return propagateShiftAll(delta, selectedTrain);
+  if (update.propagationMode === 'shiftAllWaypoints') {
+    const delta = computeDelta(oldValue, newValue);
+    return delta !== null ? propagateShiftAll(delta, selectedTrain) : undefined;
+  }
 
   if (update.propagationMode === 'atThisWaypoint' || !update.row.isPathStep) return undefined;
 
+  // For toDestination: use full datetime delta so a midnight-crossing edit correctly
+  // shifts all following stops to the next day.
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]:
```suggestion
  // shifts all following steps to the next day. // or scheduled steps if you prefer
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 13]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
+  // For fromDeparture: use HH:mm:ss only (computeDelta) since start_time absorbs the shift.
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]:
```suggestion
  // For fromDeparture: use hh:mm:ss only (computeDelta) since start_time absorbs the shift.
```

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 14]
```diff
@@ -121,26 +150,72 @@ const propagateShiftAll = (
...
     return undefined;
 
-  const delta = computeDelta(update.row[update.field], update.value);
-  if (delta === null) return undefined;
+  const oldValue = update.row[update.field];
+  const newValue = update.value;
 
   if (isOriginArrivalUpdate(update)) {
-    if (update.propagationMode === 'toDestination') return propagateShiftAll(delta, selectedTrain);
+    const delta = computeDelta(oldValue, newValue);
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/timePropagation.ts]: A bit sad to have to recompute the delta 3 times and lose the early return if it's `undefined`.

To keep the older behavior, we could do something like 
Option 1.
```
const delta = isOriginArrivalUpdate(update) || update.propagationMode === 'shiftAllWaypoints' ? computeDelta(oldValue, newValue) : computeDeltaForPropagationMode(oldValue, newValue, update.propagationMode);
```
Option 2.
We could extract the condition in consts since we use them again below
```
const isOriginArrivalUpdate = isOriginArrivalUpdate(update);
const isShiftAllPropagation = update.propagationMode === 'shiftAllWaypoints';
const delta = isOriginArrivalUpdate || isShiftAllPropagation ? computeDelta(oldValue, newValue) : computeDeltaForPropagationMode(oldValue, newValue, update.propagationMode);
```

Or Option 3., it's not worth the win and we keep as you did.

I let you decide :)

**Review by SharglutDev — COMMENTED** [review]
Thanks for the good work !

All behaviors work as expect 🎉 Except the D+1 popping when reducing the origin with a "toDestination" propagation but I don't think this comes from your PR, it could be dealt with in another PR.

File: front/src/modules/timesStops/TimesStopsOutput.tsx (hunk 1 above)
Comment (Caracol3) [reply front/src/modules/timesStops/TimesStopsOutput.tsx]: Thanks for the sugggestion. Clearer and works fine this way

File: front/src/modules/timesStops/TimesStopsOutput.tsx (hunk 2 above)
Comment (Caracol3) [reply front/src/modules/timesStops/TimesStopsOutput.tsx]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 6 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts:65]: You're right. Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 7 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 9 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 8 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 3 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Indeed. I removed it

Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: I had never used it before, but you're right, it’s harmless. Updated.

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 4 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 11 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 10 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts:119]: Its no clear indeed. Actually the `else` is meet with `atTisWaypoint`at the origin. We use `fromDeparture` direction, but the origin has no arrival in the schedule, so `editedOldOffset` is null. 
I added a comment in `propagateTime`to explain it.

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 5 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: The cascade makes this tricky i think. Bumping item A updates `lastOffset`, which cause item B  to also need bumping. A `filter` on the initial value would exclude B and leave the schedule in an inconsistent order.

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 12 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 13 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: Done

File: front/src/modules/timesStops/helpers/timePropagation.ts (hunk 14 above)
Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts]: We now have 3 const for less duplication.

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅

**Comment by louisgreiner** [comment]
It looks like the midnight banner is still bugged.

Using a timetable on small infra: [initial_timetable (small infra).json](https://github.com/user-attachments/files/27479485/initial_timetable.small.infra.json)

image

Or else on belgium_osm: [missing_midnight (belgium_osm).json](https://github.com/user-attachments/files/27479494/missing_midnight.belgium_osm.json)

image
