### PR TITLE
front: fix stdcm empty ch list in new query

### LINKED ISSUE #10410: stdcm: when creating a request from an accepted simulation, waypoints have no CH Code
### What happened?

When clicking the aforementioned button, a new tab is opened (and at first I have a loader, don't mind it), and then the CH Code drop down menu is empty (I can open it but nothing's in it).

https://github.com/user-attachments/assets/8770c203-8098-4e2a-b93c-005808acb9e5

### What did you expect to happen?

I expect this menu to always be filled when a CI code is selected.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the stdcm page
2. Make a successful simulation
3. Accept it
4. Click on the "make another request from this one" button
5. Witness that the CH code drop down menu is empty

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9151b80

### PR DESCRIPTION
**Pull request by SharglutDev**
fix #10410

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx [hunk 1]
```diff
@@ -23,6 +24,20 @@ function formatChCode(chCode: string) {
   return chCode === '' ? 'BV' : chCode;
 }
 
+const extractChCodes = (searchResults: SearchResultItemOperationalPoint[], selectedCI: CIOption) =>
+  searchResults
+    .filter((pr) => pr.name === selectedCI.name)
```
Comment (Akctarus) [inline front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx]:
```suggestion
    .filter((op) => op.name === selectedCI.name)
```
I think we should use "op" instead of "pr" that is a French acronym

**Review by Akctarus — APPROVED** [review]
tested, left a comment but does not block approval

File: front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx]: Good catch !

**Comment by clarani** [comment]
Related to https://github.com/OpenRailAssociation/osrd/issues/10401

**Review by kmer2016 — APPROVED** [review]
lgtm
