### PR TITLE
core: in LoA case, add maintain curve to indication curve before finding intersection with overlay envelope

### LINKED ISSUE #10443: core: etcs: loa bug: add maintain curve to indication curve before calling keepBrakingCurverUnderOverlay
Image

In this case, with the current behavior, indication does not intersect with the mrsp, and the code will throw an exception. What we should do is concatenate the indication curve AND the maintain curve immediately, then call the method `keepBrakingUnderOverlay`

### PR DESCRIPTION
**Pull request by Erashin**
Fixes #10443.

### CODE REVIEW

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 1]
```diff
@@ -344,21 +341,35 @@ private fun computeIndicationBrakingCurveFromRef(
...
+    if (fullBrakingCurve.endPos <= beginPos)
+        throw IllegalArgumentException(
+            "Expected fullBrakingCurve position range to intersect with [beginPos, +infinity[."
+        )
+    val positions =
+        fullBrakingCurve
+            .map { it.clonePositions() }
+            .reduce { mergedArray, currentArray ->
+                // Remove duplicate part transitions: the last point of the previous array is the
+                // first point of the next array.
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Can you mention that it duplicate points break the addStep of the ConstrainedEnvelopePartBuilder, please? 🙏 

nit: I'd also mutualize the comment.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 2]
```diff
@@ -368,10 +379,11 @@ private fun keepBrakingCurveUnderOverlay(
             EnvelopeConstraint(overlay, EnvelopePartConstraintType.CEILING)
         )
     overlayBuilder.initEnvelopePart(positions[nbPoints - 1], speeds[nbPoints - 1], -1.0)
-    for (i in fullBrakingCurve.pointCount() - 2 downTo 0) {
+    for (i in nbPoints - 2 downTo 0) {
         if (!overlayBuilder.addStep(positions[i], speeds[i], timeDeltas[i])) break
     }
-    if (partBuilder.stepCount() <= 1) return null
+    if (partBuilder.stepCount() <= 1)
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: `stepCount()` is based on `times`, and there is 1 less value than positions:
```suggestion
    if (partBuilder.isEmpty)
```
So this failed when there was a stop close from the start, and a curve with only 2 positions (19 first meters in my test).

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 3]
```diff
@@ -344,21 +341,35 @@ private fun computeIndicationBrakingCurveFromRef(
...
     beginPos: Double
-): EnvelopePart? {
-    if (fullBrakingCurve.endPos <= beginPos) {
-        return null
-    }
-    val positions = fullBrakingCurve.clonePositions()
-    val speeds = fullBrakingCurve.cloneSpeeds()
-    val timeDeltas = fullBrakingCurve.cloneTimes()
-    val nbPoints = fullBrakingCurve.pointCount()
+): EnvelopePart {
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Especially for EoA and LoA, I would check before calling that there is no need to add a curve if no intersection.

Opinionated (so OK to dismiss): From the `keepBrakingCurveUnderOverlay` fn itself, it's a legitimate use IMO to have no intersection.
I would let the responsibility to the caller to check if it is an expected case.
```suggestion
): EnvelopePart? {
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 4]
```diff
@@ -344,21 +341,35 @@ private fun computeIndicationBrakingCurveFromRef(
...
+    if (fullBrakingCurve.endPos <= beginPos)
+        throw IllegalArgumentException(
+            "Expected fullBrakingCurve position range to intersect with [beginPos, +infinity[."
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Why not rejecting already if there is only one position?
```suggestion
    if (fullBrakingCurve.endPos < beginPos)
        throw IllegalArgumentException(
            "Expected fullBrakingCurve position range to intersect with ]beginPos, +infinity[."
```

**Review by bougue-pe — COMMENTED** [review]
We really need some testing on those cases at some point (unit would be better, could be integration).
Anyway, this patch is fine 👍

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 2 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: Nice catch!! I just removed it due to another comment further along.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 3 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: To check whether or not there is an intersection between 2 envelopes is not something so easily done, especially when they're not both continuous and monotonous. However, yeah, as we talked about it, the current flow rn is not to throw exceptions, so I would rather return null here, and log a warning.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 4 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: ~Technically, none, it woulda just thrown later. I'll take it into an account.~
Wait a minute, this is actually correct, what do you mean? If the curve ends at beginPos, the only intersection would be beginPos, which is incorrect. The following check is more of a failsafe. I'd rather keep this one as is, and remove the next one, if that's ok with you.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt [hunk 5]
```diff
@@ -344,21 +346,38 @@ private fun computeIndicationBrakingCurveFromRef(
...
  */
 private fun keepBrakingCurveUnderOverlay(
-    fullBrakingCurve: EnvelopePart,
+    fullBrakingCurve: Envelope,
     overlay: Envelope,
     beginPos: Double
 ): EnvelopePart? {
     if (fullBrakingCurve.endPos <= beginPos) {
+        etcsBrakingCurvesLogger.warn(
+            "The ETCS braking curve ending at ($beginPos, ${fullBrakingCurve.endSpeed}) does not intersect with the overlay envelope."
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: nit (as we had a misunderstanding about that in comments 😅):
```suggestion
            "The position-range of ETCS braking curve ending at ($beginPos, ${fullBrakingCurve.endSpeed}) does not intersect with the overlay envelope's position-range."
```

**Review by bougue-pe — APPROVED** [review]
Thanks!
(You'll need to rebase after some other work on `dev` branch)

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt (hunk 4 above)
Comment (bougue-pe) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingCurves.kt]: As discussed, the code was good, not the comment (and I only read the comment 😅).
And agreed and reviewed to remove the final check 👍

**Review by eckter — APPROVED** [review]
