### PR TITLE
Fix incorrect input saving when switching simulations during a running calculation

### LINKED ISSUE #10480: Wrong inputs saved for the simulation
### What happened?

https://github.com/user-attachments/assets/dbfb038d-d319-4fc4-b92a-25eebc5a2481

If I launch a simulation (simulation 4) and during the loading I switch to another existing one (simulation 2) and the simulation load finishes while I'm on this other simulation (n2), he inputs saved for the n4 will be the one from n2.

### What did you expect to happen?

The saved inputs should be the ones from the simulation I launched, regardless of the simulation I'm visitng.

### How can we reproduce it (as minimally and precisely as possible)?

See description

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by kmer2016**
closes #10480 
When a different simulation is selected while a calculation is still running, the new simulation’s inputs overwrite the inputs of the ongoing calculation. This causes a mismatch between the inputs used for the calculation and the results.

### CODE REVIEW

File: front/src/applications/stdcm/views/StdcmView.tsx [hunk 1]
```diff
@@ -19,13 +19,16 @@ import StdcmResults from '../components/StdcmResults';
...
+import type { StdcmSimulation, StdcmSimulationInputs } from '../types';
 
 const StdcmView = () => {
   // TODO : refacto. state useStdcm. Maybe we can merge some state together in order to reduce the number of refresh
   const currentSimulationInputs = useStdcmForm();
   const stdcmConf = useSelector(getStdcmConf);
   const [simulationsList, setSimulationsList] = useState<StdcmSimulation[]>([]);
+  const [inProgressSimulationInputs, setInProgressSimulationInputs] = useState<
+    StdcmSimulationInputs | undefined
+  >(undefined);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx]:
```suggestion
  const [inProgressSimulationInputs, setInProgressSimulationInputs] = useState<
    StdcmSimulationInputs
  >();
```

File: front/src/applications/stdcm/views/StdcmView.tsx
Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx:1]: If I switch between simulations, it seems like the speed limit tag isn't reset

Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx:1]: If I switch between a simulation with a short form and a long one, the pathfinding loader/success message his hidden between the simulation navigator (probably because it's in position absolute and it needs to stay that way)
https://github.com/user-attachments/assets/af10f021-eced-4bf1-89c6-b15973bf62d7

Maybe you should talk with @thibautsailly for the expected behavior : 
- Remove the banners if we switch between simulation
- Display it somewhere else
- other option

Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx:1]: If I switch between a simulation with a short form and a long one, the viewport changes. I think it should stay as it is when we switch (you can double check with @thibautsailly). Also maybe we should remove the animation for the via in that case, it's a little weird.
https://github.com/user-attachments/assets/0fbadb77-d587-40b3-bd5b-58f828ffeae5

**Review by SharglutDev — COMMENTED** [review]
Thank you for the fix, it works great !

But now that it works, it reveals some strange behaviors that we should correct I think.

**Review by RomainValls — APPROVED** [review]
Code LGTM, tested and it works well. ✅

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 2]
```diff
@@ -107,7 +107,10 @@
         }
 
         .stdcm-vias-bundle {
-          animation: bouncin-in 0.75s cubic-bezier(0.567, -0.475, 0, 1);
+          
+          &.animated {
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss:110]: With this behavior, we have the animation after switching simulation and clearing a via input

https://github.com/user-attachments/assets/7e84627b-49ee-4602-b15e-74a79efe74de

File: front/src/applications/stdcm/views/StdcmView.tsx
Comment (SharglutDev) [reply front/src/applications/stdcm/views/StdcmView.tsx:1]: The last part of the comment is fixed but the first part 

> I think it should stay as it is when we switch

is still there. What did @thibautsailly said about that ?

Comment (SharglutDev) [reply front/src/applications/stdcm/views/StdcmView.tsx:1]: Seems like this bug is still there ?

Comment (kmer2016) [reply front/src/applications/stdcm/views/StdcmView.tsx:1]: confirmed by @thibautsailly

Comment (kmer2016) [reply front/src/applications/stdcm/views/StdcmView.tsx:1]: I can't reproduce the bug
[Capture vidéo du 10-02-2025 18:13:25.webm](https://github.com/user-attachments/assets/2c2d6a8a-b367-4768-ab86-24e1e6afbc03)

Comment (SharglutDev) [reply front/src/applications/stdcm/views/StdcmView.tsx:1]: Me neither :)

File: front/src/reducers/osrdconf/types.ts
Comment (SharglutDev) [inline front/src/reducers/osrdconf/types.ts:1]: There is still a wrong behavior.
In the video, I start a simulation for Paris > Mâcon > Lyon. While simulation in progress, I switch on another existing simulation with Brest > ... > Strasbourg. When the loader finishes, I'm switched on the last simulation but the inputs aren't Paris > ... > Mâcon but the ones from Brest.

https://github.com/user-attachments/assets/d52b9570-c5b8-4fc0-9666-57068af57f5c

File: front/src/applications/stdcm/views/StdcmView.tsx [hunk 3]
```diff
@@ -177,6 +188,20 @@ const StdcmView = () => {
     }
   }, [isRejected]);
 
+  /*
+   * After the new content is rendered, this effect adjusts the scroll to compensate for any shift in the stdcmResult section.
+   * It compares the stdcmResult section position before the change (stored in previousResultSectionOffsetRef)
+   * with its current position after rendering. The calculated difference is used to perform a window.scrollBy,
+   *  ensuring that the section remains at the same relative position in the viewport, thus avoiding any visual jump.
+   */
+  useEffect(() => {
```
Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx]: I think that for DOM behaviors like that, it's better to use a [useLayoutEffect](https://fr.react.dev/reference/react/useLayoutEffect)

File: front/src/reducers/osrdconf/stdcmConf/selectors.ts [hunk 4]
```diff
@@ -32,6 +32,10 @@ const buildStdcmConfSelectors = () => {
     }
   );
 
+  const getStdcmCompletedSimulations = createSelector([getStdcmSimulations], (simulations) =>
+    simulations.filter((simulation) => simulation.outputs !== undefined)
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/stdcmConf/selectors.ts]: Wouldn't it work like that ? 

```suggestion
    simulations.filter((simulation) => simulation.outputs)
```

File: front/src/reducers/osrdconf/stdcmConf/index.ts [hunk 5]
```diff
@@ -232,10 +246,15 @@ export const stdcmConfSlice = createSlice({
       );
       state.stdcmPathSteps = newPathSteps;
     },
-    // temporary solution to add a new simulation, only 1 action should remain after the refactoring
-    addNewStdcmResult(state: Draft<OsrdStdcmConfState>, action: PayloadAction<StdcmSimulation>) {
-      state.simulations.push(action.payload);
-      state.selectedSimulationIndex = state.simulations.length - 1;
+    createStdcmSimulation(
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/stdcmConf/index.ts]: Maybe it's more relevant ?
```suggestion
    addStdcmSimulation(
```

File: front/src/reducers/osrdconf/stdcmConf/stdcmConfReducers.spec.ts [hunk 6]
```diff
@@ -201,58 +222,74 @@ describe('stdcmConfReducers', () => {
...
       creationDate: new Date(),
-      inputs: {
-        pathSteps: stdcmPathSteps,
-        linkedTrains: { anteriorTrain: undefined, posteriorTrain: undefined },
-      },
+      inputs: simulationInputs,
     };
 
-    it('should handle adding new simulations', () => {
+    it('should create new simulation', () => {
```
Comment (SharglutDev) [inline front/src/reducers/osrdconf/stdcmConf/stdcmConfReducers.spec.ts]: If you made the other change
```suggestion
    it('should add a new simulation', () => {
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 7]
```diff
@@ -126,6 +137,7 @@ const StdcmConfig = ({
     const formErrorsStatus = checkStdcmConfigErrors(pathSteps, t, pathfinding?.status);
     if (pathfinding?.status === 'success' && !formErrorsStatus) {
       launchStdcmRequest();
+      dispatch(createStdcmSimulation(currentSimulationInputs));
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Is there any (bad)chance where we could have a sync issue if inputs were updated before/after the same simulation outputs ?

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, great job !
