### PR TITLE
front: fix start time for return trip in NGE 

### LINKED ISSUE #13030: NGE round trips : schedule of backward trip is not correctly updated
### What happened?

When creating/editing a round trip in NGE (with times on all nodes), the schedule of one of the two trains/services is correctly created but not the other one. Actually, both times are the same, which is not consistent with what is displayed in NGE : 

1. I create this round trip in NGE

Image

I would expect the following times : 
- PLY to LYD : Nh10 in PLY, (N+2)h05 in LYD
- LYD to PLY : Nh55 in LYD, (N+2)h50 in PLY
Instead, we have this  : 
- PLY to LYD : Nh10 in PLY, (N+2)h05 in LYD
- LYD to PLY : Nh10 in LYD, (N+2)h05 in PLY

Image

Image

So now, NGE is inconsistent with OSRD

2. If I refresh, NGE becomes consistent with OSRD, but the schedule is not the one expected

Image

> [!NOTE]
>  It should work when creating or updating a round trip in NGE

### What did you expect to happen?

Read above

### How can we reproduce it (as minimally and precisely as possible)?

Read above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8ff664b

### PR DESCRIPTION
**Pull request by emersion**
_See individual commits._

Closes: https://github.com/OpenRailAssociation/osrd/issues/13030

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 1]
```diff
@@ -311,30 +307,29 @@ const generateTrainrunProperties = (
...
+  return { labels, trainrunSections };
 };
 
 /**
- * Generate path and schedule from a trainrun. If the trainrun is backward,
- * the sections are reversed.
+ * Generate start time, path and schedule from a trainrun. If the trainrun is
+ * backward, the sections are reversed.
  */
 const generatePathAndSchedule = (
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:318]: Should the function be renamed as it now also returns a date ?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 2]
```diff
@@ -311,30 +307,29 @@ const generateTrainrunProperties = (
...
   trainrunSections: TrainrunSectionDto[],
   nodes: NodeDto[],
-  startDate: Date,
+  baseDate?: Date,
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:321]: Totally nit but I find it more logic that this param could be `null` instead of `undefined`

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thanks !
You can fix/ignore these 2 nit comments as you want

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 1 above)
Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:318]: To me, the schedule kind of includes the start time, and I didn't want to end up with a long function name. But I'm open to ideas if you have suggestions.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 2 above)
Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:321]: I've contemplated making this `null`, but this forces callers to explicitly pass `null` instead of omitting the parameter altogether (`generatePathAndSchedule(sections, nodes)`).

However, I don't think optional parameters are especially important, and there's an argument to be made that they can be easily forgotten (as was the trainrun direction argument).

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:318]: Yeah works for me, "schedule" for me still rings `schedule` property of a train where we don't include the default start time that's why :) But it's totally logic that a schedule includes it as well.

**Comment by Synar** [comment]
Overall LGTM, I just have one question :

In your commit you say 

> Instead of reversing train run sections before calling calculateStartDate(), pick the last element when appropriate.

However, in the code, we still do

>   if (trainrunDirection === TRAINRUN_DIRECTIONS.BACKWARD) {
>    sections = [...trainrunSections].reverse();
>  }

>  const startDate = calculateStartDate(sections, baseDate ?? new Date(), trainrunDirection);

which looks like reversing train run sections before calling calculateStartDate to me.

**Comment by emersion** [comment]
Ah, sorry. I removed the `reverse()` in an earlier iteration of this patch, then decided to revert that change and keep the old code as-is (because we need the sections in reverse order when generating the path anyways), but I forgot to update the commit message accordingly. I should've dropped that sentence from the commit message.
