### PR TITLE
front: add loader when deleting an infra

### LINKED ISSUE #4967: Wrong button text when deleting an infra
### What happened?

When clicking on the confirmation button after clicking on the bin button in the infra list edition modal, it shows "3s" while its deleting the infra...

[Screencast from 2023-09-05 09-43-21.webm](https://github.com/osrd-project/osrd/assets/47494402/de3119fd-4075-492f-a3c6-65f2ebde5897)

### What did you expect to happen?

It should keep displaying "yes" or even better, "deleting" or a rotating icon

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra list edition modal
2. Click on the bin icon of a large infra
3. Wait for the cooldown and press the "yes button"
4. Look at the text of the button you pressed

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Ubuntu
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

a1c380dd

### PR DESCRIPTION
**Pull request by clarani**
closes #4967

[Capture vidéo du 2023-10-03 11-39-08.webm](https://github.com/osrd-project/osrd/assets/45000526/d5332f3b-adde-451a-b2eb-ec0edf7a9345)

### CODE REVIEW

File: front/src/common/InfraSelector/InfraSelectorEditionActionsBarDelete.tsx [hunk 1]
```diff
@@ -17,12 +18,15 @@ export default function InfraSelectorEditionActionsBarDelete({
   const { t } = useTranslation('infraManagement');
   const dispatch = useDispatch();
 
-  const [deleteInfra] = osrdEditoastApi.useDeleteInfraByIdMutation();
+  const [isDeleting, setIsDeleting] = useState(false);
+
+  const [deleteInfra] = osrdEditoastApi.endpoints.deleteInfraById.useMutation();
```
Comment (SharglutDev) [inline front/src/common/InfraSelector/InfraSelectorEditionActionsBarDelete.tsx]: I think you could directly use the isLoading boolean given by rtk query instead of creating a new state.
I tested with this solution and it seems to work the same
```suggestion
  const [deleteInfra, { isLoading: isDeleting }] = osrdEditoastApi.endpoints.deleteInfraById.useMutation();
```

**Review by SharglutDev — COMMENTED** [review]
lgtm, tested in local :) Just one suggestion

File: front/src/common/InfraSelector/InfraSelectorEditionActionsBarDelete.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/InfraSelector/InfraSelectorEditionActionsBarDelete.tsx]: Wow great idea ! :D Thanks

**Review by nicolaswurtz — APPROVED** [review]

**Review by SharglutDev — APPROVED** [review]
good job :)
