### PR TITLE
front: fix origin arrival update time propagation + refactor time propagation

### LINKED ISSUE #16164: New schedule sheet : Propagation from first line does not work as expected
### What happened?

- Before : 

Image

- Option 1  ❌: After changing to 18:35 using the "at this point" : 

Image

So the next point is changed. I expect the other points not to move : the next point should remain at 19h35 here

- Option 2 ❌ : After changing to 18:35 using the "from this point" :   

Image

The next point moves to 19:40, it is correct. But the first point comes back to 18:30 : it should be 18:35

- Option 3 ✅ : After changing to 18:35 using the "shift all train" : 

Image

Everything is fine ! This point goes to 18h35 and the next point goes to 19:40

### What did you expect to happen?

Overall  : 
- Option 1 : only the value of the first line should change, the others should not change
- Option 2 : all the values (including that of the first line) should be shifted
- Option 3 : already works well : all the values (including that of the first line) should be shifted

### How can we reproduce it (as minimally and precisely as possible)?

As in the example

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

d149545

### PR DESCRIPTION
**Pull request by Synar**
Close https://github.com/OpenRailAssociation/osrd/issues/16164

Edit: I think my last commit was way over engineered, and there is a much simpler way. Pushed as a fixup.

(D -> D+1 changes are still not handled well, but the exact same issue seems to exist for non origin steps)

### CODE REVIEW

**Comment by Caracol3** [comment]
Thanks for the fix !
There is still something weird in the origin behavior.
When editing the origin's arrival time and then validating a requested arrival on another waypoint, the origin reverts to its initial time.


https://github.com/user-attachments/assets/2f347b2d-08a7-4ebd-b0fc-d924450a1007

File: front/src/modules/timesStops/helpers/timePropagation.ts [hunk 1]
```diff
@@ -2,14 +2,17 @@ import type { PathItem, ScheduleItem } from 'common/api/osrdEditoastApi';
...
+import type { ArrivalUpdate, CellUpdate, PropagationMode } from '../types';
 
 export type PropagationResult = {
   updatedPath: PathItem[];
   updatedSchedule: ScheduleItem[];
   updatedStartTime: Date;
 };
 
+const isOriginArrivalUpdate = (update: CellUpdate): update is ArrivalUpdate =>
+  update.field === 'requestedArrival' && update.row.opOnPathIndex === 0;
```
Comment (Caracol3) [inline front/src/modules/timesStops/helpers/timePropagation.ts:14]: With those changes the bug with the origin changing when modifying another cell is gone

```suggestion
const isOriginArrivalUpdate = (update: CellUpdate, selectedTrain: Train): update is ArrivalUpdate =>
  update.field === 'requestedArrival' && update.row.id === selectedTrain.path[0]?.id;
```

Comment (Synar) [reply front/src/modules/timesStops/helpers/timePropagation.ts:14]: Thanks for catching this!

I don't quite understand yet when this issue happens or why your fix fixes it. Do you have an explanation? Could you send the train schedule where you get the bug?

When trying to reproduce on my branch I couldn't

[Screencast_20260415_164448.webm](https://github.com/user-attachments/assets/cf2fbf25-d3ce-42d8-8dc7-0cf2937a1f9c)

Comment (Caracol3) [reply front/src/modules/timesStops/helpers/timePropagation.ts:14]: Very strange. I can't reproduce the bug anymore either.
I was definitely on your branch though.
Sorry for the bother.

Comment (Synar) [reply front/src/modules/timesStops/helpers/timePropagation.ts:14]: No worries and thanks for testing. Maybe your back had an issue, which caused the update request to be dropped? I'll test further to see if I can reproduce.

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, nice clean up !

> [!NOTE]
> Seems like it's orthogonal to this PR but the optimistic update doesn't work well for the start time when propagation "toBeginning". On the video below, we can see a small delay before it's updated.

https://github.com/user-attachments/assets/a2f0f57c-74f8-4c83-b3d6-832e1f931c3f
