### PR TITLE
front: fix projection exception icon in train list

### LINKED ISSUE #13029: Projection on exceptions : icons not always correct
### Case 1 : 
If I project on an occurrence with a different schedule (but the same path steps), I have an icon on the occurrence but I shouldn't (since the projection path does not change).

Image

-> I only want a blue icon on the paced train card in that case

### Case 2 :  
If I project on a occurrence which has a different rolling stock (only difference compared to the paced train) and if this rolling stock changes the path, I have no icon on the occurrence, and a blue icon on the paced train card

Image

-> I want a blue icon on the occurrence and a grey icon on the paced train card

### What did you expect to happen?

See above.

Overall, the AC are : 
- If the projection path is different, there is a blue con on the occurrence and a grey icon on the paced train

Image

- Otherwise, if the projection path is the same (even if the occurrence is an exception), there is no icon on the occurrence, and a blue icon on the paced train

Image

### How can we reproduce it (as minimally and precisely as possible)?

Just create these cases

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8ff664b

### PR DESCRIPTION
**Pull request by Synar**
Close [#13029](https://github.com/OpenRailAssociation/osrd/issues/13029)

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/usePathProjection.ts [hunk 1]
```diff
@@ -15,6 +16,16 @@ import {
   isTrainScheduleId,
 } from 'utils/trainId';
 
+const pathfindingResultsDiffer = (
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/hooks/usePathProjection.ts:23]: nit : could we just add some doc here to explain the business purpose of the function ?

**Review by RomainValls — APPROVED** [review]
Tested, LGTM !

nit: i find the naming a bit confusing at first, for ```projectingOnSimulatedPathException```
i was thinking of something like ```isSimulatedPathDifferent``` (we can let it as is, it doesn't matter so much)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !
You can close the comment when fixed (or not since it's a nit)

File: front/src/applications/operationalStudies/hooks/usePathProjection.ts (hunk 1 above)
Comment (Synar) [reply front/src/applications/operationalStudies/hooks/usePathProjection.ts:23]: Sure good idea, thanks! I could also add a test, but I'm not sure if I should ^^

Comment (SharglutDev) [reply front/src/applications/operationalStudies/hooks/usePathProjection.ts:23]: Indeed, this could help understanding different cases. But imo don't bother :)
