### PR TITLE
front: fix resize/reset buttons overlap

### LINKED ISSUE #2773: GET/GEV: Resize/ Reset buttons overlap
### What happened?

 
While before

Capture d’écran 2023-01-05 à 15 57 03

### What did you expect to happen?

These buttons should not overlap other components.

Maye be set a minimum height through React-Rnd

### How can we reproduce it (as minimally and precisely as possible)?

Capture d’écran 2023-01-05 à 15 57 12

### What operating system and browser are you using? (if applicable)

_No response_

### OSRD version

1.0

### PR DESCRIPTION
**Pull request by Yohh**
close #2773

### CODE REVIEW

File: front/src/applications/osrd/views/OSRDSimulation/OSRDSimulation.tsx [hunk 1]
```diff
@@ -253,6 +253,7 @@ function OSRDSimulation() {
                     width: '100%',
                     height: `${heightOfSpaceTimeChart}px`,
                   }}
+                  minHeight={150}
```
Comment (alexandredamiron) [inline front/src/applications/osrd/views/OSRDSimulation/OSRDSimulation.tsx]: please use a css class or a variable, on two part

Comment (Yohh) [reply front/src/applications/osrd/views/OSRDSimulation/OSRDSimulation.tsx]: done

**Review by alexandredamiron — APPROVED** [review]
