### PR TITLE
front: fix losing round-trip when updating timetable type from nge

### LINKED ISSUE #13498: Change timetableItem type from NGE make lose the round-trip pair information
### What happened?

When switching from service <-> train schedule, we lose the information of a round-trip pair

https://github.com/user-attachments/assets/49896186-dfb3-4a7d-ab3b-43bb03f1d404

### What did you expect to happen?

Keep the round-trip information for both trains

(it should also work for one-ways)

### How can we reproduce it (as minimally and precisely as possible)?

1. video

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### LINKED ISSUE #13620: front: list of train does not update round trip train category after update in macro
### What happened?

https://github.com/user-attachments/assets/be420705-8236-4ddd-8215-cc90565b58d7

### What did you expect to happen?

Have a list of train up to date

### How can we reproduce it (as minimally and precisely as possible)?

video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

be76a49

### PR DESCRIPTION
**Pull request by Caracol3**
close #13498 

close #13620 too

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 1]
```diff
@@ -30,6 +30,7 @@ import { Duration } from 'utils/duration';
 import {
   extractEditoastIdFromTrainScheduleId,
   extractEditoastIdFromPacedTrainId,
+  extractEditoastIdFromTimetableItemId,
```
Comment (Synar) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: I remember implementing extractEditoastIdFromTimetableItemId too when I worked on this component, and I got an earful from emersion for it. I now tend to agree with him. It's a dangerous function to use, as it's inherently less type safe. 

To avoid requiring this function, you could for example have 2 variable instead of `let updatedForwardItem`, like let `updatedForwardTrainScheduleId` and `updatedForwardPacedTrainId`.
(I intended to do this myself at first, but then I got "clever" and thought I could just reuse the old id, as I did not think of the case of going from a train schedule to a paced train or the reverse. My bad!)

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 2]
```diff
@@ -713,10 +718,36 @@ const handleUpdateTimetableItem = async ({
     addUpsertedTimetableItems([newReturnTimetableItem]);
   }
 
-  state.timetableItemIdByNgeId.set(trainrun.id, [
-    oldForwardTimetableItem.id,
-    newReturnTimetableItem.id,
-  ]);
+  // Ensure the round-trip association is kept after updates/conversions
+  if (isPacedTrainId(updatedForwardItem.id)) {
```
Comment (Synar) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: We should either do this in the update case of the code (and perhaps only do it if it's required?), or drop the call to the endpoint in the create case.

**Review by Synar — COMMENTED** [review]
Nice fix thanks! Left a couple comments.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 3]
```diff
@@ -554,15 +555,18 @@ const handleUpdateTimetableItem = async ({
   const paced = createPacedAttributesFromTrainrun(trainrun, netzgrafikDto);
 
   let newForwardPacedTrain: PacedTrain | undefined;
+  // Track the updated forward item to preserve its (potentially new) id when changing type
+  let updatedForwardItem: TimetableItem;
   if (!paced) {
-    await storeTrainSchedule(
+    const updatedTrainSchedule = await storeTrainSchedule(
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:623]: Nit: I don't think we need this intermediate variable, we can store the result directly in `updatedForwardItem`.

**Comment by RomainValls** [comment]
seems to be fixing this issue as well : https://github.com/OpenRailAssociation/osrd/issues/13620

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 3 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:623]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 2 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 1 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Good catch !
I replaced the generic forward item by two typed IDs (`updatedForwardTrainScheduleId`/`updatedForwardPacedTrainId`)

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 4]
```diff
@@ -580,41 +587,48 @@ const handleUpdateTimetableItem = async ({
...
           })
         ).unwrap();
       } else {
         await dispatch(
           osrdEditoastApi.endpoints.postRoundTripsTrainSchedules.initiate({
             roundTrips: {
-              one_ways: [extractEditoastIdFromTrainScheduleId(oldForwardTimetableItem.id)],
+              one_ways: [
+                extractEditoastIdFromTrainScheduleId(
+                  updatedForwardTrainScheduleId as TrainScheduleId
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: This cast should be unnecessary. Was this added because it might be undefined?

It would help TypeScript to use a single variable `let updatedForwardTrainId: TrainScheduleId | PacedTrainId`. That way it would figure out that when it's not a paced train ID, it's necessarily a train schedule ID.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 5]
```diff
@@ -580,41 +587,48 @@ const handleUpdateTimetableItem = async ({
...
             },
           })
         ).unwrap();
       }
       await deleteTimetableItemById(timetableItemIds[1], dispatch, addDeletedTimetableItemIds);
     }
 
-    state.timetableItemIdByNgeId.set(trainrun.id, [oldForwardTimetableItem.id, null]);
+    const forwardId = (updatedForwardPacedTrainId ??
+      updatedForwardTrainScheduleId) as TimetableItemId;
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Ditto: this cast should not be necessary. Casts disable TypeScript type checks so they are dangerous.

(When setting the type of a variable is desirable, the following can be used instead: `const forwardId: TimetableItemId = …`)

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 6]
```diff
@@ -718,10 +734,44 @@ const handleUpdateTimetableItem = async ({
...
+    const newReturnPacedTrainId = isPacedTrainId(newReturnTimetableItem.id)
+      ? newReturnTimetableItem.id
+      : undefined;
+    await dispatch(
+      osrdEditoastApi.endpoints.postRoundTripsPacedTrains.initiate({
+        roundTrips: {
+          round_trips: [
+            [
+              extractEditoastIdFromPacedTrainId(updatedForwardPacedTrainId),
+              extractEditoastIdFromPacedTrainId(newReturnPacedTrainId!),
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Are we sure that this will never be undefined?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 7]
```diff
@@ -718,10 +734,44 @@ const handleUpdateTimetableItem = async ({
     addUpsertedTimetableItems([newReturnTimetableItem]);
   }
 
-  state.timetableItemIdByNgeId.set(trainrun.id, [
-    oldForwardTimetableItem.id,
-    newReturnTimetableItem.id,
-  ]);
+  // Ensure the round-trip association is kept after updates/conversions
+  if (updatedForwardPacedTrainId) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Do we really need to duplicate the round-trip logic? Can't we come up with a way to call `postRoundTripsPacedTrains`/`postRoundTripsTrainSchedules` a single time in this function?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 4 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Yes, it was because of the undefined indeed.
We know have a single variable.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 5 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 7 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: You're right. I refactored duplicated round-trip logic into the function `postRoundTrip()` that handles `postRoundTripsPacedTrains` and `postRoundTripsTrainSchedules` calls based on train type.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 6 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: We don't have this case now with the refacto

**Review by Caracol3 — COMMENTED** [review]
Changes done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 8]
```diff
@@ -504,6 +506,48 @@ const handleDeleteTimetableItem = async (
  * - if the TimetableItem is initially a TrainSchedule and the frequency is now changed to PacedTrain (`paced` time window set to 2 hours and interval to corresponding TrainrunFrequency)
  * Also handles conversion from round trips to one way trips and the inverse.
  */
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: The comment above was linked to `handleUpdateTimetableItem()`, but now it's linked to the new function. The new function should probably be moved above the comment?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 9]
```diff
@@ -504,6 +506,48 @@ const handleDeleteTimetableItem = async (
...
+const postRoundTrip = async (
+  dispatch: AppDispatch,
+  forwardId: TrainScheduleId | PacedTrainId,
+  returnId?: TrainScheduleId | PacedTrainId
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: Hm, here TypeScript is a bit lost because `forwardId` and `returnId` are not tied together. However, we always want these two to be either one or the other, we never want these to have a different type.

Without this, we need these casts inside the function.

I've [tried a bunch of different approaches](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAglC8UDOwBOBLAdgcwNwChRIoAhBKTAVwFsAjCVAo6GMxFDHKAHwpvsb58AM0qYAxsHQB7TFHRIYACgBuALlgkAlBpXyksKAG98UKKgjBKqOc2nCoe+M6gByDlmyuCAXxFjJGTkFElUNVh1HfVJjU3NLa1twCHsol1cqOgZvfD9-CSlZKGFpaQAeABUoCAAPYAhMABMDVgA+VQBGDQqAGkcAJm6tWLN0ByUFZRUO4YAyWf0p-q1hkzMzCysbRw6oAGoBgjMfaoAbJGgxqAmkUOm5hZDVZdW4jYTt6f3DuJOIc+ga3WwAAFqhpAB3CgQKEAUVQ4NQSlcAHlpGAkOhoI0AIYKECuLRHKB+PKiApBRYVShgU4QMJQADaMD6MAAujwmSQ+iQ2ZE9AomSzYBygZtEotVIyAAx8qDzSUqRkdPm+fKBIolaT9BnM1kc3iM7mkOVAq43GDU2n0lQrEbrcSyFA7chK2XEsyOzDOlT9V3Ktke+JbORfA6+4l-AH294hxwyjnhgOR3JCckauRagDMlWqdQazWMO3CfV94RJnKMxdIpcGMR87WktAAVkN7ebJkom82AHT3V7rYMS7t93YHEcR35nC4xofbCdjqAT-opskBQqZ0oAFk6JYG4UirAI6Y3xW3u5r+9Ih5Ix-XlK1O+m4WNZc0A-k407-dn4s+i8nY5p0BN451DACV1+VN1VPLUAFZc1qeomhaY0AFU82Qws2gvXorwwpCCwMKoAH4oAwjRMAgFQGA-DtFE6O0gVjCUwx+ID-hnei7hmD8WP-b5AJJXIgA) and this enforcing this constraint turns out to be quite complicated. I think the best approach would be:

```ts
const isTrainScheduleRoundTrip(
  ids: [TrainSchedule, TrainSchedule?] | [PacedTrain, PacedTrain?]
): ids is [TrainSchedule, TrainSchedule?] {
  return isTrainScheduleId(ids[0]) && (!ids[1] || isTrainScheduleId(ids[1]));
}

const storeRoundTrip = async (
  dispatch: AppDispatch,
  ids: [TrainSchedule, TrainSchedule?] | [PacedTrain, PacedTrain?]
) {
  if (isTrainScheduleRoundTrip(ids)) {
    // ids contains only train schedules
  } else {
    // ids contains only paced trains
  }
}
```

Another option would be to give up on compile-time checks and throw an error at runtime if types are not the same. That would be fine by me as well.

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: This is the reason I suggested 2 variables for the return id. This way you just had to use "!" instead of a full blown cast. It's still casting a bit, but using "!" is something we do throughout the code.

Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: I can revert to using two separate variables (`updatedForwardTrainScheduleId` and `updatedForwardPacedTrainId`) which is more type-safe, and factor out the common logic with two helpers: `postOneWay` and `postRoundTrip` to avoid duplication while maintaining type safety. What do you think of it ?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 10]
```diff
@@ -672,18 +706,7 @@ const handleUpdateTimetableItem = async ({
...
-            round_trips: [
-              [
-                extractEditoastIdFromPacedTrainId(oldForwardTimetableItem.id),
-                extractEditoastIdFromPacedTrainId(newReturnTimetableItem.id),
-              ],
-            ],
-          },
-        })
-      ).unwrap();
+      await postRoundTrip(dispatch, updatedForwardTrainId, newReturnTimetableItem.id);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Seems like this is already done below?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 11]
```diff
@@ -701,27 +724,16 @@ const handleUpdateTimetableItem = async ({
...
-            round_trips: [
-              [
-                extractEditoastIdFromTrainScheduleId(oldForwardTimetableItem.id),
-                extractEditoastIdFromTrainScheduleId(newReturnTimetableItem.id),
-              ],
-            ],
-          },
-        })
-      ).unwrap();
+      await postRoundTrip(dispatch, updatedForwardTrainId, newReturnTimetableItem.id);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Ditto?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 9 above)
Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: > This is the reason I suggested 2 variables for the return id. This way you just had to use "!" instead of a full blown cast. It's still casting a bit, but using "!" is something we do throughout the code.

Yeah, null assertions are safer than casts, because they only strip the null/undefined case and otherwise retain the original type. I'm not exactly sure if that would really help though, since we need to pick between the two function calls anyways? Wouldn't we end up with something like:

```ts
let updatedForwardPacedTrainId: PacedTrainId | undefined;
let updatedForwardTrainScheduleId: TrainScheduleId | undefined;
// … existing logic to update trains
if (updatedForwardPacedTrainId) {
  // store paced train round-trip
} else if (updatedForwardTrainScheduleId) {
  // store train schedule round-trip
} else {
  throw new Error('Expected an updated train ID');
}
```

But, wouldn't the following be better?

```ts
let updatedForwardTrainId: TrainId;
// … existing logic to update trains
if (isPacedTrainId(updatedForwardTrainId)) {
  // store paced train round-trip
} else {
  // store train schedule round-trip
}
```

We can have the type checks either outside or inside the function. Depends whether it creates duplication.

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: The version of the code I had in mind did not involve explicit testing of this id at all. But lets avoid bikeshedding. I don't have strong opinions on this, either way is fine with me.

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: Okay, maybe I don't have a good idea of what you're suggesting then. I would slightly prefer an explicit runtime error over a null assertion, but I'd be fine with two functions/variables too as long as we can avoid type casts.

Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:505]: I added separate typed variables to eliminate all type casts and used explicit runtime error handling as proposed.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 8 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 10 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Removed

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 11 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Removed

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 12]
```diff
@@ -89,7 +92,6 @@ const getTrainrunSectionsByTrainrunId = (
   const sections = netzgrafikDto.trainrunSections.filter(
     (section) => section.trainrunId === trainrunId
   );
-
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:92]: Nit: can we keep this empty newline? It's unrelated to this PR, and I like to keep space between logically separate blocks of code.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 13]
```diff
@@ -496,6 +498,73 @@ const handleDeleteTimetableItem = async (
...
+
+  if (isPacedTrainId(forwardId)) {
+    pacedForwardId = forwardId;
+    if (returnId) {
+      if (!isPacedTrainId(returnId)) {
+        throw new Error('Type mismatch: forward is PacedTrain but return is not');
+      }
+      pacedReturnId = returnId;
+    }
+  } else if (isTrainScheduleId(forwardId)) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Nit: I think this `else if` is unnecessary, TypeScript will understand that if a train ID isn't a `PacedTrainId`, then it's necessarily a `TrainScheduleId`.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 14]
```diff
@@ -496,6 +498,73 @@ const handleDeleteTimetableItem = async (
...
+    scheduleForwardId = forwardId;
+    if (returnId) {
+      if (!isTrainScheduleId(returnId)) {
+        throw new Error('Type mismatch: forward is TrainSchedule but return is not');
+      }
+      scheduleReturnId = returnId;
+    }
+  } else {
+    throw new Error(`Unexpected forward ID type: ${typeof forwardId}`);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Nit: `typeof forwardId` will always say "string", which isn't super useful info. But this error case can be removed with the above comment anyways.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 15]
```diff
@@ -496,6 +498,73 @@ const handleDeleteTimetableItem = async (
...
+  }
+
+  if (pacedForwardId) {
+    await dispatch(
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: Nit: I think this function call could be moved above inside `if (isPacedTrainId(forwardId))`, without impeding on readability. This would remove the need for all of these variables. (Same for `postRoundTripsTrainSchedules`.)

**Review by emersion — COMMENTED** [review]
Nice! I only have nit comments now, feel free to ignore them if you disagree.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 12 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:92]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 13 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Good catch !
removed

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 14 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Removed

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 15 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: I removed intermediate variables to simplify the code. I think the casts here are safe because they're guarded by the `!isPacedTrainId(returnId)` and `!isTrainScheduleId(returnId)` checks above.

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: I'd really prefer to avoid casts :P 

It seems like TypeScript is not smart enough to figure out that `if (returnId && !isTrainScheduleId(returnId))` condition. Would this work better?

```ts
let roundTrips;
if (returnId) {
  if (!isTrainScheduleId(returnId)) {
    throw new Error('Type mismatch: forward is TrainSchedule but return is not');
  }
  roundTrips = {
    round_trips: [
      [
        extractEditoastIdFromTrainScheduleId(forwardId),
        extractEditoastIdFromTrainScheduleId(returnId),
      ],
    ],
  };
} else {
  roundTrips = {
    one_ways: [extractEditoastIdFromTrainScheduleId(forwardId)],
  };
}

await dispatch(
  osrdEditoastApi.endpoints.postRoundTripsTrainSchedules.initiate({ roundTrips });
).unwrap();
```

Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: Indeed, this works well without casts. I just had to add explicit type guards because TypeScript can't infer the types with just `if (returnId)`.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 13 above)
Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Hm, my point is that we can remove the `isTrainScheduleId()` call here too, that way TypeScript will complain if `forwardId` can be something else than a `TrainScheduleId` or a `PacedTrainId` in the future. Does that make sense?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 15 above)
Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: Ah, that's slightly repetitive because with that version we need to repeat the `isPacedTrainId()` checks. We can move the checks inside the `if (returnId)` blocks to avoid this:

```ts
  if (isPacedTrainId(forwardId)) {
    let roundTrips;
    if (returnId) {
      if (!isPacedTrainId(returnId)) {
        throw new Error('Type mismatch: forward is PacedTrain but return is not');
      }
      roundTrips = {
        round_trips: [
          [
            extractEditoastIdFromPacedTrainId(forwardId),
            extractEditoastIdFromPacedTrainId(returnId),
          ],
        ],
      };
    } else {
      roundTrips = {
        one_ways: [extractEditoastIdFromPacedTrainId(forwardId)],
      };
    }
    await dispatch(
      osrdEditoastApi.endpoints.postRoundTripsPacedTrains.initiate({
        roundTrips,
      })
    ).unwrap();
  } else {
    let roundTrips;
    if (returnId) {
      if (!isTrainScheduleId(returnId)) {
        throw new Error('Type mismatch: forward is TrainSchedule but return is not');
      }
      roundTrips = {
        round_trips: [
          [
            extractEditoastIdFromTrainScheduleId(forwardId),
            extractEditoastIdFromTrainScheduleId(returnId),
          ],
        ],
      };
    } else {
      roundTrips = {
        one_ways: [extractEditoastIdFromTrainScheduleId(forwardId)],
      };
    }
    await dispatch(
      osrdEditoastApi.endpoints.postRoundTripsTrainSchedules.initiate({
        roundTrips,
      })
    ).unwrap();
  }
```

**Comment by emersion** [comment]
Sorry for the long back-and-forth, but I think we're pretty close now! :P

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 15 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts:526]: Done

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 13 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Aaah ok ! 
Done now 😇

**Review by emersion — APPROVED** [review]
LGTM, thank you!
