### PR TITLE
front: be able to select a via on the map even when pf failed

### LINKED ISSUE #8117: Waypoint button should be disabled on the map if origin or destination aren't set
### Who would benefit from this feature?

End users

### What is this feature about?

When selecting a path on the map, when you hover a track this popup appears
image

Today, when you click the blue middle button, if you haven't set an origin or a destination, the popup simply closes without anything happening.

It would be great if the button was disabled so it does not look like something should happen when clicking on it

### Why is this feature valuable?

This feature matters because it:
- makes the workflow for path creation clearer

### Anything else people should know?

_No response_

### LINKED ISSUE #8497: Adding a via is impossible when no path was found
### What happened?

I created a train for which no path could be found (using the right track for example) and tried to add a via in the middle (using the map), but nothing happens (no request is sent) 

image

### What did you expect to happen?

I expected to be able to add a via even without any path, since we must be able to create and update invalid trains

### How can we reproduce it (as minimally and precisely as possible)?

Create a train with no path and try to add a via

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

672ec62

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #8497
Closes #8117

### CODE REVIEW

**Review by Caracol3 — APPROVED** [review]
Works fine for me. Good job !

File: front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/v2/ViasV2.tsx [hunk 1]
```diff
@@ -61,7 +63,7 @@ const ViasV2 = ({ zoomToFeaturePoint, shouldManageStopDuration }: DisplayViasV2P
                       >
                         <small className="font-weight-bold text-muted mr-1">{index + 1}</small>
                         <small data-testid="via-dropped-name" className="mr-1 text-nowrap">
-                          {`${via.name || `KM ${via.positionOnPath && (Math.round(via.positionOnPath) / 1000000).toFixed(3)}`}`}
+                          {`${via.name || (via.positionOnPath && `KM ${(Math.round(via.positionOnPath) / 1000000).toFixed(3)}`) || `${t('requestedPoint')} ${index + 1}`}`}
```
Comment (SharglutDev) [inline front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/v2/ViasV2.tsx]: Maybe we can add the via counter inside the trad with a `{{ count }}` ?

**Review by SharglutDev — COMMENTED** [review]
Thank you for the PR, left just one comment. Also it seems there is an issue with the trads in the editoast checks (maybe you can try a rebase).

File: front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/v2/ViasV2.tsx (hunk 1 above)
Comment (SarahBellaha) [reply front/src/modules/pathfinding/components/Itinerary/DisplayItinerary/v2/ViasV2.tsx]: As seen with @thibautsailly, it will now be "distance indisponible" / "unavailable distance" instead of "point demandé" / "requested point"

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested
