### PR TITLE
editoast: paced train exceptions field

### LINKED ISSUE #11453: editoast: add exceptions field to paced train model
Write the migration to add exceptions to Paced Train

part of https://github.com/osrd-project/osrd-confidential/issues/980

```yml
# Type of exception
id: eac43ba6-cfd9-4896-b7c9-987b9d26937b # UUID généré par le front, scoped par mission
disabled: false # only if not created
occurence_index: 3 # only if not created


# Modifications
train_name: # or null
  value: "ABC3615"

rolling_stock: # or null
  rolling_stock_name: R2D2
  comfort: AIR_CONDITIONING # or HEATING, default STANDARD

labels: # or null
  value: ["tchou-tchou", "choo-choo"]

category: # or null
 value: "fast_train"

speed_limit_tag: # or null
  value: "MA100"

start_time: # or null
  value: "2023-12-21T08:51:11.914897+00:00" # or null

constraint_distribution: # or null
  value: MARECO

path_and_schedule: # or null
  path:
  - {id: a, uic: 87210} # Any operational point matching the given uic
  - {id: b, track: foo, offset: 10000} # 10m on track foo
  - {id: c, deleted: true, trigram: ABC} # Any operational point matching the trigram ABC
  - {id: d, operational_point: X} # A specified operational point
  schedule:
  - {at: a, stop_for: PT5M, locked: true} # inferred arrival to be equal to start_time
  - {at: b, arrival: PT10M, stop_for: PT5M}
  - {at: c, stop_for: PT5M}
  - {at: d, arrival: PT50M, locked: true, reception_signal: SHORT_SLIP_STOP}
  margins:
    boundaries: [b, c]
    values: ["5%", "3%", "4.5min/100km"]
  power_restrictions:
  - {from: b, to: c, value: "M1C1"}

initial_speed: # or null
  value: 2.5

options: # or null
  value:
    use_electrical_profiles: true
    use_speed_limits_for_simulation: false
```

// Can be serde(untagged)
```
enum ExceptionType {
  Modified{occurence_index: int, disabled: bool},
  Created,
}
```

Exemple de réponse de l'endpoint /paced_train/simulation_summary

```json
{
  "train_42": {
    "paced_train": {
      "energy_consumption": 0,
      "length": 0,
      "path_item_times_base": [
        0
      ],
      "path_item_times_final": [
        0
      ],
      "path_item_times_provisional": [
        0
      ],
      "status": "success",
      "time": 0
    },
    "exceptions": {
      "42432-234234-243242-23434": {
        "energy_consumption": 0,
        "length": 0,
        "path_item_times_base": [
          0
        ],
        "path_item_times_final": [
          0
        ],
        "path_item_times_provisional": [
          0
        ],
        "status": "success",
        "time": 0
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Wadjetz**
fix #11453

### CODE REVIEW

File: front/src/common/api/generatedEditoastApi.ts [hunk 1]
```diff
@@ -1639,13 +1640,15 @@ export type GetPacedTrainByIdPathApiResponse = /** status 200 The path */ Pathfi
...
   infraId: number;
+  exceptionId: string | null;
 };
 export type GetPacedTrainByIdSimulationApiResponse =
   /** status 200 Simulation Output */ SimulationResponse;
 export type GetPacedTrainByIdSimulationApiArg = {
   id: number;
   infraId: number;
   electricalProfileSetId?: number | null;
+  exceptionId: string | null;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: Can't it be an optional param ?

File: editoast/editoast_schemas/src/paced_train.rs [hunk 2]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+    pub speed_limit_tag: Option<SpeedLimitTagSilo>,
+    pub start_time: Option<StartTimeSilo>,
+    pub constraint_distribution: Option<ConstraintDistributionSilo>,
+    pub initial_speed: Option<InitialSpeedSilo>,
+    pub options: Option<OptionsSilo>,
+    pub path_and_schedule: Option<PathAndScheduleSilo>,
+}
+
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
+#[serde(tag = "type")]
```
Comment (flomonster) [inline editoast/editoast_schemas/src/paced_train.rs]: We should either `#[serde(untagged)]` or set type as lowercase `#[serde(rename_all="lowercase")]`

File: editoast/editoast_schemas/src/paced_train.rs [hunk 3]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
     pub train_schedule_base: TrainSchedule,
     #[schema(inline)]
     pub paced: Paced,
+    #[serde(default = "Vec::new")]
```
Comment (flomonster) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
    #[serde(default)]
```

File: editoast/src/models/fixtures.rs [hunk 4]
```diff
@@ -101,6 +103,10 @@ pub fn simple_paced_train_base() -> PacedTrain {
             .expect("Unable to parse test train schedule");
     PacedTrain {
         train_schedule_base,
+        exceptions: vec![PacedTrainException {
+            id: Uuid::new_v4().to_string(),
```
Comment (flomonster) [inline editoast/src/models/fixtures.rs]: We don't need an uuid.

```suggestion
            id: "exception_id".into(),
```

File: editoast/src/views/paced_train.rs [hunk 5]
```diff
@@ -306,6 +311,9 @@ async fn get_path(
     Extension(auth): AuthenticationExt,
     Path(PacedTrainIdParam { id: paced_train_id }): Path<PacedTrainIdParam>,
     Query(InfraIdQueryParam { infra_id }): Query<InfraIdQueryParam>,
+    Query(ExceptionQueryParam {
+        exception_id: _exception_id,
+    }): Query<ExceptionQueryParam>,
```
Comment (flomonster) [inline editoast/src/views/paced_train.rs]: We don't need to adapt endpoints in this PR. Each endpoint adaptation can be done in its PR where the new query parameter is used.

File: editoast/src/views/timetable.rs [hunk 6]
```diff
@@ -792,10 +792,15 @@ mod tests {
...
-        let list_result = models::PacedTrain::list_paginated(&mut pool.get_ok(), settings)
+        let mut list_result = models::PacedTrain::list_paginated(&mut pool.get_ok(), settings)
             .await
             .expect("Failed to fetch paced trains");
+
         assert!(list_result.0.len() == 2);
+        assert_eq!(
+            list_result.0.pop().map(|train| train.exceptions),
+            Some(paced_train_2.exceptions)
+        );
```
Comment (flomonster) [inline editoast/src/views/timetable.rs]:
```suggestion
        assert_eq!(list_result.0[1].exceptions, paced_train_2.exceptions);
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatTimetableItemPayload.ts [hunk 7]
```diff
@@ -31,5 +31,6 @@ export function formatPacedTrainPayload(validConfig: ValidConfig): PacedTrain {
       time_window: validConfig.timeWindow,
       interval: validConfig.interval,
     },
+    exceptions: [],
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatTimetableItemPayload.ts:49]:
```suggestion
```

**Review by flomonster — APPROVED** [review]
Thanks for this PR.
Small changes are required, and some changes should be moved in follow-up PRs.

File: editoast/editoast_schemas/src/paced_train.rs [hunk 8]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+    pub exceptions: Vec<PacedTrainException>,
+}
+
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct PacedTrainException {
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs:67]: There's no implementation plan in the linked issue. Is exception the name that was retained? If so, this schema should be well documented because "exception" has a technical meaning in pl, but here it's used as a business term. How paced train exceptions are working in the app is also worth documenting.

File: editoast/editoast_schemas/src/paced_train.rs [hunk 9]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+    pub rolling_stock: Option<RollingStockSilo>,
+    pub labels: Option<LabelsSilo>,
+    pub category: Option<CategorySilo>,
+    #[schema(inline)]
+    pub speed_limit_tag: Option<SpeedLimitTagSilo>,
+    pub start_time: Option<StartTimeSilo>,
+    pub constraint_distribution: Option<ConstraintDistributionSilo>,
+    pub initial_speed: Option<InitialSpeedSilo>,
+    pub options: Option<OptionsSilo>,
+    pub path_and_schedule: Option<PathAndScheduleSilo>,
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]: Is "Silo" really the suffix retained? If I remember well from distant paced train design workshops I attended, the "silo" is a french loanword carrying the meaning of an internal proprietary tool used at sncf... It doesn't make any sense for someone not aware of that. I'd really wish another name was chosen. And the "silo"-ted override process should be well documented, especially why paced train properties cannot be overridden individually.

File: editoast/editoast_schemas/src/paced_train.rs [hunk 10]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+}
+
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
+#[serde(tag = "type")]
+pub enum PacedTrainExceptionType {
+    #[default]
+    Created,
+    Modified {
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]: Are we sure this the only modification kind we'll ever support? If not I'd suggest
```suggestion
    Disabled {
```

File: editoast/editoast_schemas/src/paced_train.rs [hunk 11]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+        occurence_index: i32,
+        disabled: bool,
+    },
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
+pub struct TrainNameSilo {
+    pub value: String,
+}
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]: Why not just an `Option<String>` in the `PacedTrainException`?

If we really need the name, there's always newtypes.

File: editoast/editoast_schemas/src/paced_train.rs [hunk 12]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
...
+    pub value: f64,
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct OptionsSilo {
+    pub value: TrainScheduleOptions,
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct PathAndScheduleSilo {
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
pub struct TripSilo {
```

(not sure about this one)

File: editoast/editoast_schemas/src/paced_train.rs [hunk 13]
```diff
@@ -1,11 +1,35 @@
...
+use crate::train_schedule::Margins;
+use crate::train_schedule::PathItem;
+use crate::train_schedule::PowerRestrictionItem;
+use crate::train_schedule::ScheduleItem;
+use crate::train_schedule::TrainSchedule;
+use crate::train_schedule::TrainScheduleOptions;
+
 editoast_common::schemas! {
     PacedTrain,
+    Paced,
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
```

File: editoast/editoast_schemas/src/paced_train.rs
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs:1]: Can you "scope" the silos in the OpenAPI by prefixing them with `PacedTrain-`?

File: editoast/editoast_schemas/src/paced_train.rs [hunk 14]
```diff
@@ -24,4 +48,92 @@ pub struct PacedTrain {
     pub train_schedule_base: TrainSchedule,
     #[schema(inline)]
     pub paced: Paced,
+    #[serde(default = "Vec::new")]
+    pub exceptions: Vec<PacedTrainException>,
+}
+
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct PacedTrainException {
+    pub id: String,
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]: This is obviously not a database ID, why do we need it, what does it represent, why is it a string, etc?

**Review by leovalais — CHANGES_REQUESTED** [review]
Thanks for this PR. The commits should be squashed.
A few comments ⬇️

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatTimetableItemPayload.ts (hunk 7 above)
Comment (Wadjetz) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatTimetableItemPayload.ts:49]: Actually, this field is required; we represent the absence of exceptions with an empty array.

File: editoast/editoast_schemas/src/paced_train.rs (hunk 8 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs:67]: Sorry, the ticket is not very complete. All the discussions and summary from the workshop are in this ticket: https://github.com/osrd-project/osrd-confidential/issues/980. I also added some context in the sub-tickets https://github.com/OpenRailAssociation/osrd/issues/11453.

Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs:67]: The name ‘exceptions’ is widely used in the ticket. Do you have ideas for a better name?

File: editoast/editoast_schemas/src/paced_train.rs (hunk 10 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: I’m not sure about ‘Disabled’, because we have two types of exceptions: one is a newly created exception that is not part of the occurrences, and the other is a modified occurrence that differs from the others. The ‘disabled’ field only represents the state of a specific occurrence.

File: editoast/editoast_schemas/src/paced_train.rs (hunk 11 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: There is a debate about which solution to use for this. I chose this one because I think it’s more explicit, but feel free to challenge it and we can discuss it again.

Capture d’écran 2025-04-28 à 11 06 08

File: editoast/editoast_schemas/src/paced_train.rs (hunk 14 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: The ID will be defined by the frontend, and we might want the frontend to be free to choose it. Maybe @flomonster has a better reason for making it a string? I think we also need an ID to retrieve the path and simulation of this exception.

File: front/src/common/api/generatedEditoastApi.ts [hunk 15]
```diff
@@ -3278,7 +3279,100 @@ export type TrainSchedule = {
...
+  path_and_schedule?: PathAndScheduleSilo | null;
+  rolling_stock?: RollingStockSilo | null;
+  speed_limit_tag?: {
+    value?: string | null;
+  } | null;
+  start_time?: StartTimeSilo | null;
+  train_name?: TrainNameSilo | null;
+};
 export type PacedTrain = TrainSchedule & {
+  exceptions?: PacedTrainException[];
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: What is the difference between a paced train with exceptions == undefined or exceptions == [] ? Could this be a required field and it would be an empty array if no exceptions ?

Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: Yes, sorry it should be required, i will fix that

**Comment by leovalais** [comment]
I've discussed with @flomonster about the feature yesterday. Now that he explained to me how exceptions are precisely supposed to be working, I better understand the choices made about the schema and the model. But just looking at the schemas left me with a lot of questioning.

There are choices that seemed very odd to me at first read, but ultimately justified after some discussion: the `id` as a string that's provided by the frontend, the `Modified` variant and the structure of the "silos". This PR *needs to include thorough documentation* about such justifications – and more generally about how exceptions are supposed to work both at the schema and DB level.

### Here are my propositions:

* Rename `id` to `uid` or `identifier` to prevent confusion with database IDs since those will coexist. I'd also enforce the type to `Uuid` to further mark the distinction.
* I'd move the `disabled: bool` property out of the `ExceptionType` and either:
	1. make it a `PacedTrainException` property
		* pro: the same could be done for train schedules later and we'll have the symmetry
	2. make it a silo
		* pro: more coherent with the exception "silo"-ted framework
* I thought the double nullability problem mentioned in the ticket would be better solved using a 3-state enumeration `Set/Unset/Keep`. However I can find a single advantage to representing that with an optional struct: schema forward-compatibility. We can add new optional fields to an existing single-value silo without migrations. (And JSON symmetry as @flomonster argued for.) Let's keep a struct for each silo.

### About terminology

* I'm perfectly fine with the term "exception" provided some amount of documentation in order to avoid any confusion.
* I still *very confused* by the name "Silo": it's not descriptive of either what the type represents or of what the process behind it is. "Silo" is not a railway nor a technical term. (To me a silo is either where we store grain or a excellent SF book series...) Maybe something in the lines of `Override`, `Patch` or `Changes` could better describe what's going on here? @flomonster @emersion 
* Less important but still: I think we'd be better off renaming the many occurrences of "value" in the silos to what the value actually represent. `name`, `category`, etc. (Unless you're in favor of a 3 state enum @Wadjetz? 👀)

@Wadjetz Wdyt about all this?

**Comment by SharglutDev** [comment]
Agreed for docs :)

File: front/src/common/api/generatedEditoastApi.ts [hunk 16]
```diff
@@ -3278,7 +3279,97 @@ export type TrainSchedule = {
...
+  rolling_stock_name: string;
+};
+export type StartTimeChangeGroup = {
+  value: string;
+};
+export type TrainNameChangeGroup = {
+  value: string;
+};
+export type PacedTrainException = (
+  | (object | null)
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: This is a bit weird

File: front/src/common/api/generatedEditoastApi.ts [hunk 17]
```diff
@@ -3278,7 +3279,97 @@ export type TrainSchedule = {
...
+  labels?: LabelsChangeGroup | null;
+  options?: OptionsChangeGroup | null;
+  path_and_schedule?: PathAndScheduleChangeGroup | null;
+  rolling_stock?: RollingStockChangeGroup | null;
+  speed_limit_tag?: {
+    value?: string | null;
+  } | null;
+  start_time?: StartTimeChangeGroup | null;
+  train_name?: TrainNameChangeGroup | null;
+  uid: string;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: My understanding is that `uuid` is only for added exception

Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: It’s also used for retrieving the exception path and simulation with query string param.

File: front/src/common/api/generatedEditoastApi.ts (hunk 16 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: Yes, it’s generated code from an untagged enum. I think I’ll switch to a tagged enum.

File: editoast/editoast_schemas/src/paced_train.rs [hunk 18]
```diff
@@ -24,4 +47,101 @@ pub struct PacedTrain {
...
+}
+
+/// Represents an exception for a paced train occurrence.
+/// Occurrences are normally generated from a base paced train.
+/// An exception occurs when an occurrence is added or modified
+/// compared to the base model. Each field corresponds to a "ChangeGroup" of attributes
+/// that may deviate from the paced train.
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct PacedTrainException {
+    pub uid: String,
```
Comment (emersion) [inline editoast/editoast_schemas/src/paced_train.rs]: I'd prefer to name this field `id` instead of `uid`, for consistency with `PathItemLocation.id`.

File: editoast/editoast_schemas/src/paced_train.rs (hunk 10 above)
Comment (emersion) [reply editoast/editoast_schemas/src/paced_train.rs]: Indeed, to me "disabled" is a subset of "modified".

File: front/src/common/api/generatedEditoastApi.ts [hunk 19]
```diff
@@ -3310,7 +3311,97 @@ export type TrainSchedule = {
...
+  category?: CategoryChangeGroup | null;
+  constraint_distribution?: ConstraintDistributionChangeGroup | null;
+  initial_speed?: InitialSpeedChangeGroup | null;
+  labels?: LabelsChangeGroup | null;
+  options?: OptionsChangeGroup | null;
+  path_and_schedule?: PathAndScheduleChangeGroup | null;
+  rolling_stock?: RollingStockChangeGroup | null;
+  speed_limit_tag?: {
+    value?: string | null;
+  } | null;
```
Comment (emersion) [inline front/src/common/api/generatedEditoastApi.ts]: Any reason why we don't have a `ChangeGroup` type for this one, given we have one for each other field?

File: editoast/editoast_schemas/src/paced_train.rs (hunk 18 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: This name was suggested to avoid confusion with the database ID

>Rename id to uid or identifier to prevent confusion with database IDs since those will coexist. I'd also enforce the type to Uuid to further mark the distinction.
@leovalais

Comment (emersion) [reply editoast/editoast_schemas/src/paced_train.rs]: Exceptions don't have database IDs, so there is no possible confusion here. (Also, the string isn't necessarily a UUID.)

File: front/src/common/api/generatedEditoastApi.ts (hunk 16 above)
Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts]: Thanks. Now it looks like `type: 'created';` came back

Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: Yes, it avoids some problems

File: front/src/common/api/generatedEditoastApi.ts
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:1]: Not sure if you can do that in Rust but we should also update `PostTimetableByIdPacedTrainsApiArg`.

The type should look like this as we can only have a "created" exception when we `post` a paced train : 
```
export type PostTimetableByIdPacedTrainsApiArg = {
  /** A timetable ID */
  id: number;
  body: Extract<PacedTrain, { type: 'created' }>[];
};
```

File: front/src/common/api/generatedEditoastApi.ts [hunk 20]
```diff
@@ -3310,7 +3311,101 @@ export type TrainSchedule = {
...
+};
+export type StartTimeChangeGroup = {
+  value: string;
+};
+export type TrainNameChangeGroup = {
+  value: string;
+};
+export type PacedTrainException = (
+  | {
+      type: 'created';
```
Comment (emersion) [inline front/src/common/api/generatedEditoastApi.ts]: I don't think this should be exposed in the public REST API. This is strictly internal Rust details.

Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: Yes, but the OpenAPI is generated from Rust types. If I remove the type, it generates weird definitions and causes some tests to fail because the enum can’t be properly inferred. One possible solution would be to avoid using an enum and instead make occurrence_id and disabled optional fields. ? @leovalais @flomonster

Comment (leovalais) [reply front/src/common/api/generatedEditoastApi.ts]: I don't understand the proposition here. Is it having nothing for `Created` and just two fields `disabled` and `occurrence_id` in the `Modiefied` case?

File: editoast/editoast_schemas/src/paced_train.rs (hunk 18 above)
Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs]: > Exceptions don't have database IDs

Yes

> so there is no possible confusion here

No so sure. When returning a paced train, we have the paced train id and a bunch of exception ids. One of them comes from the db, the others are string coming from who knows where. They do not have the same meaning, origin and type: it doesn't seem that unreasonable for them to be named differently imo.

> Also, the string isn't necessarily a UUID

Why wouldn't it?

File: editoast/editoast_schemas/src/paced_train.rs (hunk 10 above)
Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs]: I didn't understand the meaning of the schema, so yes the `Modified` name is fine with me. But by looking at its fields for the first time without context or docuemntation, it screams "which occurence_id do I disable?". ("Disabled" is indeed a subset of "modified", so let's be specific when we can.)

Since the schema is not explicit by itself, imo an even better move than documenting it would be to change it so that its structure explains on its own what the schema means. `enum { Created, Modified { occurrence_id: usize } }` is straightforward. Hence my proposition to move the `disabled` at the `PacedTrain` level.

File: front/src/common/api/generatedEditoastApi.ts (hunk 20 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: > Is it having nothing for Created and just two fields disabled and occurrence_id in the Modiefied case?

it already the case, i'm proposing to not having an enum

```rust
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
#[serde(tag = "type", rename_all="lowercase")]
pub enum PacedTrainExceptionType {
    #[default]
    Created,
    Modified {
        occurence_index: i32,
        disabled: bool,
    },
}
```

and just optional fields (occurence_index, disabled)

```rust
pub struct PacedTrainException {
    occurence_index: Option<i32>,
    disabled: Option<bool>,
   ...
}
```

File: front/src/common/api/generatedEditoastApi.ts
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts:1]: I can’t really do that, since the enum is not in the PacedTrain object itself, but in `PacedTrain.exceptions[].type`.

File: editoast/editoast_schemas/src/paced_train.rs (hunk 18 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: Can't we just force it to `Uuid` ?

File: front/src/common/api/generatedEditoastApi.ts
Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts:1]: Ok we'll find something in front side :)

File: editoast/editoast_schemas/src/paced_train.rs (hunk 18 above)
Comment (SharglutDev) [reply editoast/editoast_schemas/src/paced_train.rs]: > Also, the string isn't necessarily a UUID
>> Why wouldn't it?

For modified exceptions, we (front) plan to use only the paced train id and the occurrence index. Do you (back) need the uuid for some purposes ? (like reference this exception in other endpoints ?)

Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: Ok, let’s keep it as a string and decide between using `id` or `uid`.

Comment (SharglutDev) [reply editoast/editoast_schemas/src/paced_train.rs]: My point was : do we need an `id` at all for a modified exception ? Is it required for the back ? (the back implementation for exceptions doesn't mention that the id is optional so I guess you need it for something)

Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: I think it’s good practice to give a consistent ID to an object to make it easy to identify. Even if another property could be used, having an explicit ID makes things clearer

Comment (SharglutDev) [reply editoast/editoast_schemas/src/paced_train.rs]: I think we can go for `id` then ?

Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: I agree with using the name `id`. Does it really matter whether it comes from the database or not? The goal is simply to identify the object.

File: front/src/common/api/generatedEditoastApi.ts [hunk 21]
```diff
@@ -3310,7 +3311,95 @@ export type TrainSchedule = {
...
+export type TrainNameChangeGroup = {
+  value: string;
+};
+export type PacedTrainException = {
+  disabled?: boolean;
+  occurence_index?: number;
+} & {
+  category?: CategoryChangeGroup | null;
+  constraint_distribution?: ConstraintDistributionChangeGroup | null;
+  id: string;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: Maybe it could be nice to also have here a doc to explain what kind of id is expected depending on the type of the exception ? (added or modified)

**Review by SharglutDev — APPROVED** [review]
Lgtm for front part ✅

File: front/src/common/api/generatedEditoastApi.ts [hunk 22]
```diff
@@ -3310,7 +3311,98 @@ export type TrainSchedule = {
...
+};
+export type StartTimeChangeGroup = {
+  value: string;
+};
+export type TrainNameChangeGroup = {
+  value: string;
+};
+export type PacedTrainException = {
+  disabled?: boolean;
+  occurence_index?: number;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]:
```suggestion
  occurrence_index?: number;
```

File: front/src/common/api/generatedEditoastApi.ts [hunk 23]
```diff
@@ -3310,7 +3311,98 @@ export type TrainSchedule = {
...
+export type PathAndScheduleChangeGroup = {
+  margins: Margins;
+  path: PathItem[];
+  power_restrictions: PowerRestrictionItem[];
+  schedule: ScheduleItem[];
+};
+export type RollingStockChangeGroup = {
+  category?: TrainCategory | null;
+  comfort: Comfort;
+  rolling_stock_name: string;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:3449]: Why do we need this one ?

File: front/src/common/api/generatedEditoastApi.ts [hunk 24]
```diff
@@ -3310,7 +3311,98 @@ export type TrainSchedule = {
...
+};
+export type PathAndScheduleChangeGroup = {
+  margins: Margins;
+  path: PathItem[];
+  power_restrictions: PowerRestrictionItem[];
+  schedule: ScheduleItem[];
+};
+export type RollingStockChangeGroup = {
+  category?: TrainCategory | null;
+  comfort: Comfort;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:3448]: If the occurrence is an exception because of its `category`, we would need the possibility not to put a `comfort` here ?
```suggestion
  comfort?: Comfort;
```

File: front/src/common/api/generatedEditoastApi.ts [hunk 25]
```diff
@@ -3310,7 +3311,98 @@ export type TrainSchedule = {
...
+    If `None`, `reception_signal` must be `Open`.
+    `Some("PT0S")` means the train stops for 0 seconds. */
+  stop_for?: string | null;
+};
+export type PathAndScheduleChangeGroup = {
+  margins: Margins;
+  path: PathItem[];
+  power_restrictions: PowerRestrictionItem[];
+  schedule: ScheduleItem[];
+};
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:3446]: Should all these properties by optional if the exception comes only from one of them ?

File: front/src/common/api/generatedEditoastApi.ts (hunk 23 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts:3449]: I think this is used to change the rolling stock of the exception?

File: front/src/common/api/generatedEditoastApi.ts (hunk 24 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts:3448]: My bad, it should be a new silo/change group for the rolling stock category

File: front/src/common/api/generatedEditoastApi.ts (hunk 25 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts:3446]: They are not optional in the train schedules, and with the silo principle, i think you need to change all of them

File: front/src/common/api/generatedEditoastApi.ts (hunk 23 above)
Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts:3449]: Oh right my bad, forgot we use name and not id now

File: front/src/common/api/generatedEditoastApi.ts (hunk 25 above)
Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts:3446]: Yep you're right

File: front/src/common/api/generatedEditoastApi.ts [hunk 26]
```diff
@@ -3310,7 +3311,95 @@ export type TrainSchedule = {
...
+export type RollingStockChangeGroup = {
+  comfort: Comfort;
+  rolling_stock_name: string;
+};
+export type RollingStockCategoryChangeGroup = {
+  category?: TrainCategory | null;
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts]: We don't use `value` for this one ?

**Review by SharglutDev — APPROVED** [review]
Thanks for the last changes

File: front/src/common/api/generatedEditoastApi.ts [hunk 27]
```diff
@@ -3310,7 +3311,95 @@ export type TrainSchedule = {
...
+export type RollingStockCategoryChangeGroup = {
+  value?: TrainCategory | null;
+};
+export type SpeedLimitTagChangeGroup = {
+  value?: string | null;
+};
+export type StartTimeChangeGroup = {
+  value: string;
+};
+export type PacedTrainNameChangeGroup = {
```
Comment (emersion) [inline front/src/common/api/generatedEditoastApi.ts]: Nit: any reason why this type has the prefix "Paced", while the other change groups don't have it?

**Review by emersion — APPROVED** [review]
Apart from this one nit, LGTM for the OpenAPI/front :)

File: front/src/common/api/generatedEditoastApi.ts (hunk 27 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts]: To avoid confusion with the rolling stock name — but maybe it’s not necessary ?

File: editoast/editoast_schemas/src/paced_train.rs [hunk 28]
```diff
@@ -24,4 +51,120 @@ pub struct PacedTrain {
...
+    pub start_time: Option<StartTimeChangeGroup>,
+    pub constraint_distribution: Option<ConstraintDistributionChangeGroup>,
+    pub initial_speed: Option<InitialSpeedChangeGroup>,
+    pub options: Option<OptionsChangeGroup>,
+    pub path_and_schedule: Option<PathAndScheduleChangeGroup>,
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
+#[serde(untagged)]
+pub enum PacedTrainExceptionType {
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
pub enum ExceptionType {
```

File: editoast/editoast_schemas/src/paced_train.rs [hunk 29]
```diff
@@ -24,4 +51,120 @@ pub struct PacedTrain {
...
+/// that may deviate from the paced train.
+/// - Created: A new occurrence manually added by the user, not originally present in the automatically generated occurrences based on the paced train.
+/// - Modified: An existing occurrence that has been changed
+#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, ToSchema)]
+pub struct PacedTrainException {
+    /// Unique key for the exception within the paced train, required and generated by the frontend.
+    pub key: String,
+    #[serde(flatten, default)]
+    #[schema(inline)]
+    pub exception_type: PacedTrainExceptionType,
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
    #[serde(flatten)]
    #[schema(inline)]
    pub exception_type: PacedTrainExceptionType,
```

shouldn't Created {} be selected automatically when there's no field?

File: editoast/editoast_schemas/src/paced_train.rs [hunk 30]
```diff
@@ -24,4 +51,120 @@ pub struct PacedTrain {
...
+    /// This avoids ambiguity with an empty object `{}`.
+    /// Must be declared after more specific variants, as order matters for untagged enums.
+    Created {},
+}
+
+impl Default for PacedTrainExceptionType {
+    fn default() -> Self {
+        PacedTrainExceptionType::Created {}
+    }
+}
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
```

File: editoast/editoast_schemas/src/paced_train.rs [hunk 31]
```diff
@@ -24,4 +51,120 @@ pub struct PacedTrain {
...
+            .property(
+                "occurrence_index",
+                ObjectBuilder::new().schema_type(SchemaType::Integer),
+            )
+            .build();
+        ("PacedTrainExceptionType", modified_schema.into())
+    }
+}
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, ToSchema)]
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, ToSchema)]
```

or add it to all other changegroups (except the one with an f64)

File: editoast/src/views/timetable.rs [hunk 32]
```diff
@@ -797,7 +797,9 @@ mod tests {
         let list_result = models::PacedTrain::list_paginated(&mut pool.get_ok(), settings)
             .await
             .expect("Failed to fetch paced trains");
+
         assert!(list_result.0.len() == 2);
+        assert_eq!(list_result.0[0].exceptions, paced_train_2.exceptions);
```
Comment (leovalais) [inline editoast/src/views/timetable.rs]:
```suggestion
        let list_result = models::PacedTrain::list(&mut pool.get_ok(), settings)
            .await
            .expect("Failed to fetch paced trains");

        assert!(list_result.len() == 2);
        assert_eq!(list_result[0].exceptions, paced_train_2.exceptions);
```

File: editoast/editoast_schemas/src/paced_train.rs [hunk 33]
```diff
@@ -24,4 +51,120 @@ pub struct PacedTrain {
...
+pub struct TrainNameChangeGroup {
+    pub value: String,
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs:111]: > Less important but still: I think we'd be better off renaming the many occurrences of "value" in the silos to what the value actually represent. name, category, etc.

https://github.com/OpenRailAssociation/osrd/pull/11557#issuecomment-2839381968

That way we won't end up with a weirdly named schema if we add new fields to these change groups.

> [!WARNING]
> I don't want to start yet another round of discussion though... Let's do it if everyone agrees upfront, ping @SharglutDev @emersion (please :+1: or :-1:), otherwise feel free to resolve :)

**Review by leovalais — COMMENTED** [review]
LGTM, thanks (and sorry) for all the back and forth!

File: front/src/common/api/generatedEditoastApi.ts [hunk 34]
```diff
@@ -3309,7 +3310,95 @@ export type TrainSchedule = {
...
+    If `None`, `reception_signal` must be `Open`.
+    `Some("PT0S")` means the train stops for 0 seconds. */
+  stop_for?: string | null;
+};
+export type PathAndScheduleChangeGroup = {
+  margins: Margins;
+  path: PathItem[];
+  power_restrictions: PowerRestrictionItem[];
+  schedule: ScheduleItem[];
+};
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:3446]: Sorry one more thought regarding this change group : it's a little weird if for example, I want to change only the path but don't want to send any margin for the exception, I'll have to do : 
```
path: [
          { id: 'id227', deleted: false, uic: 6, secondary_code: 'BV' },
          { id: 'id228', deleted: false, uic: 5, secondary_code: 'BV' },
        ],
        margins: { boundaries: [], values: [] },
        schedule: [],
        power_restrictions: [],
```
Does editoast handle properly this case instead of receiving undefined for `margins`, `schedule` and `power_restrictions` like we normally can do with the `TrainSchedule` struct ?

File: editoast/editoast_schemas/src/paced_train.rs (hunk 33 above)
Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs:111]: Okay resolving

File: front/src/common/api/generatedEditoastApi.ts (hunk 34 above)
Comment (Wadjetz) [reply front/src/common/api/generatedEditoastApi.ts:3446]: Editoast will need all the data from each change group, since we’re replacing or removing entire logical groups of fields.
The idea behind change groups is to allow full replacement or removal of these blocks.

We could assign each field its own change group, but that would break the “silo” principle and move us closer to a patch-like system — similar to how the HTTP PATCH verb works.

Maybe that’s actually what we want, and “silos” aren’t really necessary? 😂

File: editoast/editoast_schemas/src/paced_train.rs (hunk 30 above)
Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs]: #[default] may only be used on unit enum variants — unfortunately, we’ll have to implement Default manually.

File: front/src/common/api/generatedEditoastApi.ts (hunk 34 above)
Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts:3446]: As long as the example I wrote works, I think we will be good :)

File: editoast/editoast_schemas/src/paced_train.rs (hunk 30 above)
Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs]: https://github.com/OpenRailAssociation/osrd/pull/11557#discussion_r2086933423 'im suggesting to remove the default altogether

File: editoast/editoast_schemas/src/paced_train.rs [hunk 35]
```diff
@@ -24,4 +51,114 @@ pub struct PacedTrain {
...
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
+#[serde(untagged)]
+pub enum ExceptionType {
+    Modified {
+        occurrence_index: i32,
+    },
+    /// Created is a struct variant (not unit) to allow proper deserialization with #[serde(untagged)].
+    /// This avoids ambiguity with an empty object `{}`.
+    /// Must be declared after more specific variants, as order matters for untagged enums.
```
Comment (leovalais) [inline editoast/editoast_schemas/src/paced_train.rs]:
```suggestion
    // Created is a struct variant (not unit) to allow proper deserialization with #[serde(untagged)].
    // This avoids ambiguity with an empty object `{}`.
    // Must be declared after more specific variants, as order matters for untagged enums.
```

not a doc comment

**Review by leovalais — APPROVED** [review]
LGTM, thanks again for the back and forth!

File: editoast/editoast_schemas/src/paced_train.rs
Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs:1]: Not done, but let's merge the PR anyway

Comment (Wadjetz) [reply editoast/editoast_schemas/src/paced_train.rs:1]: Sorry, it tried, but there is some problems with objects references and it break typescript types generation

Comment (leovalais) [reply editoast/editoast_schemas/src/paced_train.rs:1]: No worries but when that happens leave a comment to explain the issue and let know help is needed 😄
