### PR TITLE
editoast: stdcm: make simulation run time a 12h default value when simulation fails

### LINKED ISSUE #14164: STDCM: Technical error for "not enough traction"
### What happened?

Image

[payload-27-11.json](https://github.com/user-attachments/files/23799230/payload-27-11.json)

### What did you expect to happen?

A similar message error is displayed for the user :
`The requested train stopped before reaching its destination (not enough traction)`

### How can we reproduce it (as minimally and precisely as possible)?

1. Launch a simulation between FHS and DN
2. Tonnage = 1800 et legnth = 750 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

d5614a0

### PR DESCRIPTION
**Pull request by Erashin**
Everything's in the title.
Fixes https://github.com/OpenRailAssociation/osrd/issues/14164.

Tested by returning SimulationFailed in core endpoint (fail test result does not fail anymore because the corresponding data problem was probably fixed).
Elected to just make `simulation_run_time` = 12h rather than `maximum_run_time` 'cause it's simpler and makes `maximum_run_time` value even higher (~18h), which is good to make sure we don't fail on the longer paths.

### CODE REVIEW

File: editoast/src/views/timetable/stdcm.rs [hunk 1]
```diff
@@ -276,12 +276,20 @@ pub(in crate::views) async fn stdcm_handler(
...
+        simulation::Response::SimulationFailed { .. } => {
+            // Default 12h value when the simulation fails
+            12 * 3_600_000
+        }
+        simulation::Response::PathfindingFailed { .. } => {
+            return Ok(Json(StdcmResponse::PreprocessingSimulationError {
+                error: virtual_train_run.simulation,
+                core_payload: None,
+            }));
+        }
```
Comment (hamz2a) [inline editoast/src/views/timetable/stdcm.rs]: Thanks for the PR.
Better to handle this in `simulation_run_time`, since we already deal with the success case there.

Comment (Erashin) [reply editoast/src/views/timetable/stdcm.rs]: I don't agree, as this is pure stdcm logic. Handling this in `simulation.rs`'s `simulation_run_time()` method moves this behaviour to a file that only has simulation logic, where we might not want a default value for a simulation when it fails.

However, the code snipped could be otimized, which I did in: https://github.com/OpenRailAssociation/osrd/pull/15184/changes/1777d6b9ca7f6dd56c7e097752cac858621f0c35.

**Review by flomonster — APPROVED** [review]
LGTM

File: editoast/src/views/timetable/stdcm.rs (hunk 1 above)
Comment (flomonster) [reply editoast/src/views/timetable/stdcm.rs]: Agree with @Erashin, this default value should not be part of the `simulation_run_time()` function.

**Review by hamz2a — APPROVED** [review]
LGTM.
