### PR TITLE
core: fix osrd error deserialisation due to missing unit and kotlin adapters

### LINKED ISSUE #6905: TS2: Add core conflict endpoint
## Description

Add an endpoint `POST` /v2/conflicts` which does quite the same thing as the v1 (a few things to adapt in the interface).

- input : Train list, *not flatten*, starting datetime + deltas
- outputs: start and end(in datetimes)

### PR DESCRIPTION
**Pull request by Erashin**

### CODE REVIEW

File: core/osrd-reporting/src/main/java/fr/sncf/osrd/reporting/exceptions/OSRDError.java [hunk 1]
```diff
@@ -1,10 +1,12 @@
 package fr.sncf.osrd.reporting.exceptions;
 
-import com.squareup.moshi.*;
 import com.squareup.moshi.JsonAdapter;
+import com.squareup.moshi.KotlinJsonAdapterFactory;
```
Comment (eckter) [inline core/osrd-reporting/src/main/java/fr/sncf/osrd/reporting/exceptions/OSRDError.java]:
```suggestion
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory;
```

There's one of the two versions that's deprecated

File: core/osrd-reporting/src/main/java/fr/sncf/osrd/reporting/exceptions/OSRDError.java [hunk 2]
```diff
@@ -456,7 +458,11 @@ public String getMessage() {
     public static final JsonAdapter<OSRDError> adapter;
 
     static {
-        Moshi moshi = new Moshi.Builder().build();
+        @SuppressWarnings("deprecation")
```
Comment (eckter) [inline core/osrd-reporting/src/main/java/fr/sncf/osrd/reporting/exceptions/OSRDError.java]:
```suggestion
```

(see other comment)

**Review by eckter — APPROVED** [review]
