### PR TITLE
front: fix invalid step message when query is pending

### LINKED ISSUE #15029: front: new itinerary modal: "Point non reconnu" message appears quickly even when the OP is recognized
### What happened?

https://github.com/user-attachments/assets/69e34d22-7aac-46b3-9b01-3a002c2b60bb

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. go to the new itinerary modal
2. add an OP
3. sometimes the message appears really quickly

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 42e8bca

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15029 

a quick message was shown, displaying the step was invalid, as the step.location hasn't been resolved immediately. 
Added a isFetching to not display the message while fetching locations

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/usePathOps.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ const usePathOps = (
     [path]
   );
 
-  const { data: operationalPoints } =
+  const { data: operationalPoints, isFetching } =
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/usePathOps.ts]: Can we use `currentData` instead of `data`, and remove `isFetching` stuff?

Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: Sure I'll try that !

File: front/src/applications/operationalStudies/hooks/usePathOps.ts [hunk 2]
```diff
@@ -62,6 +62,8 @@ const usePathOps = (
 
     return allValidOps.map((matchingOps) => getStationFromOps(matchingOps)!);
   }, [operationalPoints]);
+
+  return { relatedOperationalPoints, isFetching };
```
Comment (SarahBellaha) [inline front/src/applications/operationalStudies/hooks/usePathOps.ts]: Depending on whether you keep this approch or not, you'll have to adapt the way you call this hook in `useOutputTableData.ts` and `useTimesStopsTableData.ts` to match the new returned structure ⬇️ 

```
const { relatedOperationalPoints: pathStepOps } = usePathOps(infraId, selectedTrain.path);
```

File: front/src/applications/operationalStudies/hooks/usePathOps.ts (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: actually, i'm using isFetching to avoid displaying error messages on the new itinerary modal when a pathstep is invalid. I don't see how I can do the same using currentData and removing isFetching? 
if we don't have currentData yet, then it will be undefined, and will throw the invalid pathstep message as long as we don't have the location data of the pathstep ?

Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: By the way, what is the downside of using isFetching here ? 

And in the case we're dropping it, what would be the plan ? I'm unsure about how to use currentData in order to get the same behavior as now.

File: front/src/applications/operationalStudies/hooks/usePathOps.ts (hunk 2 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: Thanks !

Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: I amended the changes 👍

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅ 

As discussed, the issue is a bit more deep and we should probably not set the metadata as invalid at all when we don't have a location.

Let's discuss the wanted behaviors with @maelysLeratRosso to refacto that part to match the use cases.

File: front/src/applications/operationalStudies/hooks/usePathOps.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: Issue was coming for another part of the code.

`uicPayload` in `usePathStepsMetadata` is computed 2 times. When `pathSteps` changes, `pathStepsOperationalPoints` is not updated yet with the matchOp endpoint data resulting to `matchedOp` (l.168) being briefly `undefined` introducing the `isInvalid` state (l.195) responsible for the warning message in the form.

But we should probably not set the metadata as invalid when no match is found and maybe display this only when submitting the form (let's see with the PO)

File: front/src/applications/operationalStudies/hooks/usePathOps.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: This part is no longer relevant.

See this [comment](https://github.com/OpenRailAssociation/osrd/pull/15047#discussion_r2769302607) for more explanations :)

Comment (SarahBellaha) [reply front/src/applications/operationalStudies/hooks/usePathOps.ts]: Yes, thanks :)
 It was a simple reminder depending on the way chosen to solve this :D
