### PR TITLE
front: fix conflicts not fetched on page load

### LINKED ISSUE #13437: front: operational studies: conflicts not loaded when opening the page
### What happened?

When opening a scenario that has conflict without any modification of the trains, no conflict is shown.

### What did you expect to happen?

Expect the conflicts to be displayed in `STD` as soon as STD component is open + tick to show "Conflicts"
Expect the conflicts to be displayed in `Conflicts` as soon as Conflict is open

### How can we reproduce it (as minimally and precisely as possible)?

The following works for small_infra and fast-rolling-stock (also "successful" for a TGV)
* Prepare a scenario with 2 identical trains so that they conflict.
* ✅ Observe conflicts (STD and Conflict components of the page)
* Go back to "Studies" page (close scenario)
* Open again the scenario
* ❌ Observe absence of conflict
* Edit a train, change nothing, just click "Edit this train"
* ✅ Observe that conflicts are back

### On which environments the bug occurs?

Production (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

065d07e, 1bc8c7a8cb726ef7ffd137fe05a3242021e4d839

### PR DESCRIPTION
**Pull request by Synar**
Close #13437

Conflicts were manually fetched using lazy query, with manual cache invalidation whenever a function updating the timetable was called. This strategy worked, but was missing an initial fetch.

However, we could simply use useQuery and leave the cache invalidation to rtk query, as the query is already dependent on the 'timetable' tag. This would be both simpler and less brittle.

The change from useQuery to useLazyQuery was previously made in #13010 due to issues with manual refetching  (introduced in  #10151) when using useQuery. I do not believe these manual refetches were actually necessary (as cache invalidation is already handled by tags), and I believe we can thus revert to useQuery while dropping the refetching logic.

I hope I'm not overlooking something ^^

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 1]
```diff
@@ -117,14 +117,19 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithStatus) =>
...
+    data: conflicts,
+    isLoading,
+    isFetching,
+  } = osrdEditoastApi.endpoints.getTimetableByIdConflicts.useQuery(
+    {
+      id: scenario.timetable_id,
+      infraId: scenario.infra_id,
+    },
+    {
+      skip: !allTrainsSimulated,
```
Comment (Math-R) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: can you use the skip token ? We talked about it as an enhancement in "point front"

https://redux-toolkit.js.org/rtk-query/usage-with-typescript#skipping-queries-with-typescript-using-skiptoken

Comment (Synar) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Sure, done! I don't believe it makes a difference here.

**Comment by emersion** [comment]
In general, +1 for replacing `useLazyQuery()` with `useQuery()` :)

**Review by Math-R — APPROVED** [review]
lgtm
