### PR TITLE
front: fix scenario explorer behaviour

### LINKED ISSUE #5183: front: can not change selected scenario
### What happened?

When you are on stdcm page and you have a scenario already selected, you can not change the selected scenario.
Indeed, in the modal to select a scenario, the scenarii are not displayed and I can not select one of them, or I can not change the selected study.

image

### What did you expect to happen?

The scenarii should be displayed and I should be able to change scenario

### How can we reproduce it (as minimally and precisely as possible)?

You should have several existing projects, and one of them with at least 2 studies.
1. Go to stdcm
2. Select a scenario if it is not the case
3. Go back to the home page
4. Go back to stdcm
5. Open the modal to select a scenario: the scenarii should not be displayed

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

6fc6ddb1

### PR DESCRIPTION
**Pull request by clarani**
closes #5183

### CODE REVIEW

**Review by Yohh — APPROVED** [review]
:muscle:

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalStudyMiniCard.tsx [hunk 1]
```diff
@@ -1,12 +1,15 @@
...
   return (
     <div
-      className={`scenario-explorator-modal-part-itemslist-minicard study ${
-        isSelected ? 'selected' : ''
-      } ${study.scenarios_count && study.scenarios_count > 0 ? '' : 'empty'}`}
+      className={cx(
+        'scenario-explorator-modal-part-itemslist-minicard study',
+        isSelected && 'selected',
+        study.scenarios_count === 0 && 'empty'
+      )}
```
Comment (anisometropie) [inline front/src/common/ScenarioExplorer/ScenarioExplorerModalStudyMiniCard.tsx]:
```suggestion
      className={cx(
        'scenario-explorator-modal-part-itemslist-minicard study',
        {
          selected: isSelected,
          empty: study.scenarios_count === 0,
         }
      )}
```

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx [hunk 2]
```diff
@@ -9,17 +10,14 @@ export default function ProjectMiniCard({
...
   return (
     <div
-      className={`scenario-explorator-modal-part-itemslist-minicard project with-image ${
-        isSelected ? 'selected' : ''
-      } ${project.studies_count && project.studies_count > 0 ? '' : 'empty'}`}
+      className={cx(
+        'scenario-explorator-modal-part-itemslist-minicard project with-image',
+        isSelected && 'selected',
+        project.studies_count === 0 && 'empty'
+      )}
```
Comment (anisometropie) [inline front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: I find classnames object syntax slightly more readable

```suggestion
      className={cx(
        'scenario-explorator-modal-part-itemslist-minicard',
        'project',
        'with-image',
        {
          selected: isSelected,
          empty: project.studies_count === 0,
        }
      )}
```

Comment (anisometropie) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: or to pass one single object, but slightly meh

```
      className={cx(
       {
         'scenario-explorator-modal-part-itemslist-minicard': true,
         'project': true,
         'with-image': true,
          selected: isSelected,
          empty: project.studies_count === 0,
        }
      )}
```

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalScenarioMiniCard.tsx [hunk 3]
```diff
@@ -30,9 +31,10 @@ export default function ScenarioMiniCard({
   };
   return (
     <div
-      className={`scenario-explorator-modal-part-itemslist-minicard scenario ${
-        isSelected ? 'selected' : ''
-      }`}
+      className={cx(
+        'scenario-explorator-modal-part-itemslist-minicard scenario',
+        isSelected && 'selected'
+      )}
```
Comment (anisometropie) [inline front/src/common/ScenarioExplorer/ScenarioExplorerModalScenarioMiniCard.tsx]: same idea

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx [hunk 4]
```diff
@@ -9,17 +10,14 @@ export default function ProjectMiniCard({
...
       role="button"
       tabIndex={0}
-      onClick={() =>
-        !isSelected &&
-        project.studies_count &&
-        project.studies_count > 0 &&
-        setSelectedID(project.id)
-      }
+      onClick={() => !isSelected && project.studies_count > 0 && setSelectedID(project.id)}
```
Comment (anisometropie) [inline front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: We do not care about the value returned by this arrow function, just that it’s calling another function. 

A more imperative looking syntax makes the intent more obvious at first sight.

```suggestion
      onClick={() => {
        if(!isSelected && project.studies_count > 0) {
          setSelectedID(project.id)
        }
      }
```

File: front/src/common/ScenarioExplorer/ScenarioExplorerModal.tsx [hunk 5]
```diff
@@ -65,8 +66,11 @@ export default function ScenarioExplorerModal({
         .then(({ results }) => setStudiesList(results))
         .catch((error) => console.error(error));
     }
-    setStudyID(undefined);
-    setScenariosList(undefined);
+    if (projectID !== globalProjectId || studyID !== globalStudyId) {
+      // not initialization
```
Comment (anisometropie) [inline front/src/common/ScenarioExplorer/ScenarioExplorerModal.tsx]: not initialized, or no initialization ?

**Review by anisometropie — CHANGES_REQUESTED** [review]

**Review by SharglutDev — APPROVED** [review]
lgtm and tested in local. Nice fix :)

File: front/src/common/ScenarioExplorer/ScenarioExplorerModal.tsx (hunk 5 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModal.tsx]: It stands for "it's not initialization", meaning that the component has already been initialized :+1:

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx (hunk 2 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: Hum I would rather keep it like this, I find it a bit long otherwise 
```
cx(
        'scenario-explorator-modal-part-itemslist-minicard study',
        {
          selected: isSelected,
          empty: study.scenarios_count === 0,
         }
      )}
```

Comment (anisometropie) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: `scenario-explorator-modal-part-itemslist-minicard project with-image`

It’s really difficult to see that we have 3 different classes 
3 lines make it more obvious.
we’re not trying to have less lines, but to be more readable.

Comment (nicolaswurtz) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: I think the problem is to have more specific classnames and not too long.
In a future css oriented refacto we could rename those. The last Clara's proposition looks good to me ;)

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx (hunk 4 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: Done thanks !

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalScenarioMiniCard.tsx (hunk 3 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalScenarioMiniCard.tsx]: I modified it

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalStudyMiniCard.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalStudyMiniCard.tsx]: I modified it

File: front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx (hunk 2 above)
Comment (clarani) [reply front/src/common/ScenarioExplorer/ScenarioExplorerModalProjectMiniCard.tsx]: Agree on the fact that the 3 classes are a bit difficult to read and that the 1st class is especially not readable. I renamed it, do you think it is better now even if the 3 classes are on the same line ?

**Review by anisometropie — APPROVED** [review]

**Review by nicolaswurtz — APPROVED** [review]
