### PR TITLE
front: fix ch suggestions update

### LINKED ISSUE #10033: stdcm: selecting a linked train doesn't set the ch code
### What happened?

Selecting a linked path only sets the CI code, and not the CH code:

Here I select a train which arrives at Lyon-Guillotière EH, but in stdcm it sets the origin to Lyon-Guillotière 27

https://github.com/user-attachments/assets/73edc7e1-4402-437d-acc0-f15db620c56f

### What did you expect to happen?

I expect the CH in stdcm to be set to the same CH of the linked train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Pick a train you know the CI/CH code of the destination in the timetable used for stdcm
2. In the stdcm form, pick it
3. Witness the destination being set to the wrong CH

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9e75ce2

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #10033

### CODE REVIEW

**Review by RomainValls — APPROVED** [review]
LGTM, tested 👍

File: front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx [hunk 1]
```diff
@@ -132,12 +136,22 @@ const StdcmOperationalPoint = ({ location, pathStepId, disabled }: StdcmOperatio
...
       setSearchTerm('');
       setChSuggestions([]);
     }
   }, [location]);
 
+  useEffect(() => {
+    if (location && searchResults.length > 0) {
+      updateChSuggestions(location.name);
+    }
+  }, [searchResults]);
```
Comment (clarani) [inline front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx]: Actually this useEffect introduces a bug...
[Capture vidéo du 2025-01-15 15-47-57.webm](https://github.com/user-attachments/assets/64c5e194-da3b-459e-b94c-7227fa3bc602)

Hum when we update the location from the linkedTrains, we should fetch the ch of the selected ci and update the suggestions, but only at this moment and not each time the searchResults change.

What you can do: 
- in StdcmPathStep location, add a new field `availableSecondaryCodes`

- in StdcmOperationalPoint, when we change the ci, then we update availableSecondaryCodes
- chSuggestions is built from availableSecondaryCodes
- when we select an op in linkedTrain, we also update the available secondaryCodes (either we already have the secondaryCodes available, or we fetch them with `searchOperationalPoints`, see below)
- [optional] in the hook useSearchOperationalPoint, extract from the function searchOperationalPoints the set state and change it so it returns its results and takes in argument the query

If you have another solution, we can discuss it ! I'm not sure mine is the simplest...

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx (hunk 1 above)
Comment (SarahBellaha) [reply front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx]: I've changed the condition in this `useEffect` a bit so that we don't have the bug anymore.
I like your idea, i've created an [issue](https://github.com/OpenRailAssociation/osrd/issues/10401) to do this in another PR :)

**Review by clarani — APPROVED** [review]
:white_check_mark: LGTM because it fixes a major bug: if a user now selects a linked train, then the ci and ch are correctly set.

However, the management of the ch suggestions is still broken. It will be solved by this [issue](https://github.com/OpenRailAssociation/osrd/issues/10401)
