### PR TITLE
front: rolling-stock-editor: fix small bugs

### LINKED ISSUE #4786: Rolling stock editor : 4 small bugs
### What happened?

There are a few small bugs on the current version of the rolling stock editor : 
1. The mass unit is displayed in kg instead of tons:
image
And actually changing the unit does not work, the input will automatically be interpreted as tons

2. Trying to change the unit of drag coefficient lead to this:
image
The choices go under the next input field, and it creates a horizontal scroll because the dropdown list makes the component wider.

3. Changing one of the drag coefficient units make it impossible to update the rolling stock:
image

4. Some speed values are displayed with absurd float precision:
image

### What did you expect to happen?

1. The unit selector must be tons by default, and if the user decides to set a mass in kg it should be interpreted as kg in the backend. If this does not work yet the unit selection should be disabled.
2. There should never be a horizontal scroll on this component. And the dropdown list must come in front of other input fields so that the user can see it entirely
3. It should be possible to update a rollingstock with other units for the drag coefficients. If that's too long to implement for now, the unit selector should be disabled for the moment.
4. No matter the input, the value should not be displayed with more than 2 digits after coma, and 60.00 should be displayed 60.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the rolling stock editor
2. Try to edit an existing rollingstock

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 115.0.5790.171
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 467ea7bc Core 467ea7bc API 467ea7bc Front 467ea7bc

### PR DESCRIPTION
**Pull request by clarani**
closes #4786 

- show mass in tons by default
- add z-index to input group
- fix resistance coefficient inputs
- round values in curve table

### CODE REVIEW

File: front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx [hunk 1]
```diff
@@ -38,10 +38,10 @@ export default function RollingStockEditorCurves(props: {
         }
       | undefined
     )[][] =
-      speedsList !== undefined && effortsList !== undefined
+      speedsList && effortsList
         ? effortsList.map((effort, index) => [
-            { value: (speedsList[index] * 3.6).toString() },
-            { value: (effort / 10).toString() },
+            { value: Math.round(speedsList[index] * 3.6).toString() },
+            { value: Math.round(effort / 10).toString() },
```
Comment (axrolld) [inline front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx:44]: Is it rounded at unit here ?

File: front/src/applications/rollingStockEditor/components/RollingStockEditorFormHelpers.tsx [hunk 2]
```diff
@@ -151,7 +151,7 @@ const RollingStockEditorParameterFormColumn = ({
               handleType={(type) => {
                 setRollingStockValues({
                   ...rollingStockValues,
-                  [property.title]: type.value,
+                  [property.title]: Number(type.value) || 0,
```
Comment (axrolld) [inline front/src/applications/rollingStockEditor/components/RollingStockEditorFormHelpers.tsx:154]: What's this line fixing ? I can't speak front-end :D

**Review by axrolld — APPROVED** [review]
Quick and efficient, thank you !

File: front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx (hunk 1 above)
Comment (clarani) [reply front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx:44]: Currently, it's rounded at unit, but I can allow 2 digits after comma sure :)

File: front/src/applications/rollingStockEditor/components/RollingStockEditorFormHelpers.tsx (hunk 2 above)
Comment (clarani) [reply front/src/applications/rollingStockEditor/components/RollingStockEditorFormHelpers.tsx:154]: Type.value is a string here, we need to convert it to a number, otherwise the backend can not accept the request :) Now, you can edit the resistance fields, and everything should work correctly !

**Review by Math-R — APPROVED** [review]

File: front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx (hunk 1 above)
Comment (axrolld) [reply front/src/applications/rollingStockEditor/components/RollingStockEditorCurves.tsx:44]: I edited my message, i actually don't think it's really necessay to have 2 digits after comma, you can leave it like that :)
