### PR TITLE
ui-core: fix combobox outside click

### LINKED ISSUE #15547: Clicking anywhere in the itinerary modal clear the first path step
### What happened?

In the itinerary modal, when one clicks anywhere in the dialog, the the first path step is cleared.

After some investigations, it seems the `clearStep` function is called in `ItineraryModal.tsx`.
Tracking down the call of the function leads to the ComboBox.tsx component. The useOutsideClick function is fired on each "mousedown" event in the document but should be fired only when the focus is in the combobox.

### What did you expect to happen?

Interacting with the itinerary modal shouldn't clear the first path step.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario and edit a train
2. Go to the itinerary modal
3. Click anywhere in the modal
4. See that the first path step has been cleared

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by SharglutDev**
The outside click event of the combobox had no condition when to be fired resulting to call `closeSuggestions` on every click outside of the combobox even if the suggestions were not opened.

This PR :
- ensures that the listener starts only if the condition is met
- removes the listener as soon as the condition isn't met anymore to avoid keeping it listening for a lot of time for no reason.

> [!NOTE]
> Another way to avoid having to do part 2 would have been to move the suggestion list in its own component and call usOutsideClick inside. This way when the list is unmounted the listener would be removed without any other condition. 

fix #15547

### CODE REVIEW

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx [hunk 1]
```diff
@@ -1,21 +1,26 @@
...
 
-    document.addEventListener('mousedown', handleClickOutside);
+  useEffect(() => {
+    if (eventCondition) {
+      document.addEventListener('mousedown', handleClickOutside);
+    } else {
+      document.removeEventListener('mousedown', handleClickOutside);
+    }
     return () => {
       document.removeEventListener('mousedown', handleClickOutside);
```
Comment (DucNg) [inline front/ui/ui-core/src/hooks/useOutsideClick.tsx]: Isn't the eventListener removed twice when evenCondition false?

**Review by DucNg — COMMENTED** [review]
Tested, it works

Not entirely related: your initial issue (clicking outside the combo box clears the path step) could be a very good candidate for a e2e test to make sure we don't accidentally reintroduce this subtle bug. Do you think we could create a follow up issue?

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: Yes, not sure if it's an issue.

Didn't plan to have the condition initially in the `useEffect` but @Signez pointed out that, since the listener is currently removed only when unmounting the combobox, the listener won't be removed for a while if we are working in a page where a combobox is present (the itinerary modal and in a few weeks the new time stops table header in the simulation results).

**Comment by SharglutDev** [comment]
> Not entirely related: your initial issue (clicking outside the combo box clears the path step) could be a very good candidate for a e2e test to make sure we don't accidentally reintroduce this subtle bug. Do you think we could create a follow up issue?

Totally agreed. The e2e tests for the itinerary modal will probably be implemented on the next PI when dropping the old interface (the best argument for tests / e2e tests can be seen these days when we get a lot of regressions after new features on the modal since nothing is tested yet).
@Maymanaf this behavior could be one step of the new coming e2e tests ?

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx (hunk 1 above)
Comment (Signez) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: I read the [MDN page to be sure](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#:~:text=Calling%20removeEventListener%28%29%20with%20arguments%20that%20do%20not%20identify%20any%20currently%20registered%20event%20listener%20on%20the%20EventTarget%20has%20no%20effect), but yes, removing an already removed EventListener is a no-op.

Comment (DucNg) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: Is the else necessary then? Couldn't we just rely on the call line 21 instead of having both?

Comment (Signez) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: It is: if we don't, it would mean that we would never remove the listener when they we should not listen anymore (i.e. when the condition is `false`), so that would mean it would be executed on any click after the `eventCondition` is `true` (even if it get back to `false`).

**Review by DucNg — APPROVED** [review]

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx (hunk 1 above)
Comment (DucNg) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: Seen together: the first remove is when eventCondition becomes false and the second one is for when the component is unmounted

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx [hunk 2]
```diff
@@ -1,21 +1,26 @@
-import { useEffect } from 'react';
+import { useEffect, useEffectEvent } from 'react';
 
 const useOutsideClick = (
   ref: React.RefObject<HTMLElement | null>,
-  handler: (event: MouseEvent) => void
+  handler: (event: MouseEvent) => void,
+  eventCondition = true
```
Comment (emersion) [inline front/ui/ui-core/src/hooks/useOutsideClick.tsx]: Nit, purely cosmetic change: I think the API would be a bit cleaner if we made `ref` optional instead. A null `ref` would disable the hook.

**Review by emersion — APPROVED** [review]
Overall LGTM

(Really looking forward to dropping this once we switch to `popover`.)

**Comment by Signez** [comment]
After an IRL discussion with @emersion, we were still annoyed by this redundant `removeEventListener`, and that prompted us to search _why_ this made us unsettled.

Look no more: the `else` **is** redundant after all, and we had to double-check the [React documentation](https://react.dev/reference/react/useEffect#useeffect:~:text=After%20every%20commit%20with%20changed%20dependencies%2C%20React%20will%20first%20run%20the%20cleanup%20function%20%28if%20you%20provided%20it%29%20with%20the%20old%20values), as the cleanup function of `useEffect` is run after _any_ change in the dependencies, not only on unmount.


The whole hook body can be simplified like this, using an early `return` when `eventCondition` is `false`:

```typescript
{
  useEffect(() => {
    if (!eventCondition) {
      return;
    }

    const handleClickOutside = (event: MouseEvent) => {
      if (ref.current && !ref.current.contains(event.target as Node)) {
        handler(event);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [ref, handler, eventCondition]);
};
```

Sorry again @DucNg to making you doubt your own gut feeling (that I shared too, to be fair): it was, indeed, useless after all.

**Comment by DucNg** [comment]
> After an IRL discussion with @emersion, we were still annoyed by this redundant `removeEventListener`, and that prompted us to search _why_ this made us unsettled.
> 
> Look no more: the `else` **is** redundant after all, and we had to double-check the [React documentation](https://react.dev/reference/react/useEffect#useeffect:~:text=After%20every%20commit%20with%20changed%20dependencies%2C%20React%20will%20first%20run%20the%20cleanup%20function%20%28if%20you%20provided%20it%29%20with%20the%20old%20values), as the cleanup function of `useEffect` is run after _any_ change in the dependencies, not only on unmount.
> 
> The whole hook body can be simplified like this, using an early `return` when `eventCondition` is `false`:
> 
> ```ts
> {
>   useEffect(() => {
>     if (!eventCondition) {
>       return;
>     }
> 
>     const handleClickOutside = (event: MouseEvent) => {
>       if (ref.current && !ref.current.contains(event.target as Node)) {
>         handler(event);
>       }
>     };
> 
>     document.addEventListener('mousedown', handleClickOutside);
> 
>     return () => {
>       document.removeEventListener('mousedown', handleClickOutside);
>     };
>   }, [ref, handler, eventCondition]);
> };
> ```
> 
> Sorry again @DucNg to making you doubt your own gut feeling (that I shared too, to be fair): it was, indeed, useless after all.

Happy for my gut 😊

File: front/ui/ui-core/src/hooks/useOutsideClick.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/ui/ui-core/src/hooks/useOutsideClick.tsx]: done

**Comment by SharglutDev** [comment]
Thank you for all the feedback !

- Removed the `eventCondition` param in the favor of the `ref` as suggested by @emersion 
- Removed the else to remove the listener (thanks for digging the react docs, I forgot that the callbacl function of the `useEffect` was also called when the deps changed)
- @Signez -> kept the `useEffectEvent` as I feel like it's the modern way of React to combine this with a `useEffect`. This will help us when one day we will turn off the rule for the exhaustive deps not to have to add `handleClickOutside` in it

Let me know if the PR works for both of you.

> (Really looking forward to dropping this once we switch to popover.)

Really looking to as well. It's on my todo list as soon as I have a bit of time to work on it :)

**Review by Signez — APPROVED** [review]
LGTM! 🚀

**Review by emersion — APPROVED** [review]

**Review by DucNg — APPROVED** [review]
