### PR TITLE
editoast: fix the railjson version of rolling stocks created

### LINKED ISSUE #4724: editoast: invalid rolling stock: major version mismatch
### What happened?

I tried to make myself a custom rolling stock, and when trying to use it i had this bug :
image

It's a bit sad if `Alex Roulant` can't roll :(

### What did you expect to happen?

There should be either no error, or if there's something wrong with my inputs i should be warned and unable to save my rolling stock as it is.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Try to find a path with `Alex Roulant` as rolling stock

### What operating system, browser and environment are you using?

- **Browser**: Chrome 115.0.5790.110
- **Env**: dev
- **OS**: Windows 10

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 0a9ca097 Core 0a9ca097 API 0a9ca097 Front 9f61f8fd

### PR DESCRIPTION
**Pull request by flomonster**
fix #4724

### CODE REVIEW

**Review by younesschrifi — APPROVED** [review]
LGTM ! Thanks for this PR :)

File: editoast/src/views/rolling_stocks/mod.rs [hunk 1]
```diff
@@ -74,36 +76,53 @@ async fn get(db_pool: Data<DbPool>, path: Path<i64>) -> Result<Json<RollingStock
 
 #[derive(Debug, Clone, Deserialize, Serialize)]
 pub struct RollingStockForm {
-    #[serde(flatten)]
-    pub common: RollingStockCommon,
```
Comment (Castavo) [inline editoast/src/views/rolling_stocks/mod.rs]: Why not remove the `railjson_version` version field from `RollingStockCommon` instead ?

Comment (leovalais) [inline editoast/src/views/rolling_stocks/mod.rs]: Wouldn't it be better to remove `railjson_version` from `RollingStockCommon` and add it where it's necessary?

File: editoast/src/views/rolling_stocks/mod.rs [hunk 2]
```diff
@@ -74,36 +76,53 @@ async fn get(db_pool: Data<DbPool>, path: Path<i64>) -> Result<Json<RollingStock
...
+    #[serde(default)]
+    pub energy_sources: Vec<EnergySource>,
+    pub electrical_power_startup_time: Option<f64>,
+    pub raise_pantograph_time: Option<f64>,
     pub locked: Option<bool>,
     pub metadata: RollingStockMetadata,
 }
 
 impl From<RollingStockForm> for RollingStockModel {
     fn from(rolling_stock: RollingStockForm) -> Self {
```
Comment (leovalais) [inline editoast/src/views/rolling_stocks/mod.rs:85]: *(Completely subjective remark)* I would've done it the other way around:
* write the conversion in `into_rolling_stock_model`
* call it in `from` with the default values

**Review by leovalais — COMMENTED** [review]
LGTM, a few comments

File: editoast/src/views/rolling_stocks/mod.rs (hunk 2 above)
Comment (flomonster) [reply editoast/src/views/rolling_stocks/mod.rs:85]: Since `into_rolling_stock_model` required an `i64` for the id, it will be weird to provide a fake one to replace it by `None` right after calling the function.

File: editoast/src/views/rolling_stocks/mod.rs (hunk 1 above)
Comment (flomonster) [reply editoast/src/views/rolling_stocks/mod.rs]: Done

Comment (flomonster) [reply editoast/src/views/rolling_stocks/mod.rs]: Done

**Review by leovalais — APPROVED** [review]
LGTM

File: editoast/src/views/rolling_stocks/mod.rs (hunk 2 above)
Comment (leovalais) [reply editoast/src/views/rolling_stocks/mod.rs:85]: Oh good point.

**Review by Math-R — APPROVED** [review]
