### PR TITLE
front: add filter for signaling systems url

### LINKED ISSUE #6348: front: sprites display can fail when we reach an unknown signaling system
### What happened?

When a call to `sprites/{SIGNALING_SYSTEM}/sprites` fails cause the `SIGNALING_SYSTEM` is not found no sprites are loaded.

### What did you expect to happen?

We should be resilient to bugs and be able to load atlases even if one fails.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to https://github.com/osrd-project/osrd/blob/707aafcc9335769781d3ae355cff0ebbd64d9f8a/front/src/common/Map/Layers/blankStyle.ts#L17
2. Make it fail
3. Observe no sprite is imported even the one from `osm.osrd.fr` like buffer stops

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

707aafcc9335769781d3ae355cff0ebbd64d9f8a

### PR DESCRIPTION
**Pull request by Akctarus**
Closes #6348

### CODE REVIEW

File: front/src/common/Map/Layers/blankStyle.ts [hunk 1]
```diff
@@ -1,24 +1,59 @@
...
-      ? [
-          { url: 'https://static.osm.osrd.fr/sprites/sprites', id: 'default' },
-          ...signalingSystems.map((id) => ({
-            url: `${window.location.origin}${baseURL}/sprites/${id}/sprites`,
-            id,
-          })),
-        ]
-      : [];
+    const sprite = validSprites;
+    console.log(sprite, 'sprite');
```
Comment (flomonster) [inline front/src/common/Map/Layers/blankStyle.ts]: I think it needs cleaning

**Review by flomonster — COMMENTED** [review]
Tested, it works.

**Comment by Khoyo** [comment]
@dependabot rebase

**Review by RomainValls — APPROVED** [review]
LGTM

File: front/src/common/Map/Layers/blankStyle.ts [hunk 2]
```diff
@@ -35,7 +69,7 @@ export const useMapBlankStyle = (): MapProps['mapStyle'] => {
         },
       ],
     } as MapProps['mapStyle'];
-  }, [signalingSystems]);
+  }, [validSprites, signalingSystems]);
```
Comment (SharglutDev) [inline front/src/common/Map/Layers/blankStyle.ts]: I think you can keep only this one, as validSprites is already updated when signaling systems changes
```suggestion
  }, [validSprites]);
```

File: front/src/common/Map/Layers/blankStyle.ts [hunk 3]
```diff
@@ -1,24 +1,58 @@
...
 export const useMapBlankStyle = (): MapProps['mapStyle'] => {
   const baseURL = MAIN_API.proxy_editoast;
 
   const { data: signalingSystems } =
     osrdEditoastApi.endpoints.getSpritesSignalingSystems.useQuery();
 
+  const getSpriteData = async () => {
+    if (!signalingSystems) return [];
+
+    const defaultSprite = { url: 'https://static.osm.osrd.fr/sprites/sprites', id: 'default' };
```
Comment (SharglutDev) [inline front/src/common/Map/Layers/blankStyle.ts]: You could create a type for sprites and use it in the rest of the file
```
    type Sprite = { url: string, id: string };
```

``` suggestion
    const defaultSprite: Sprite = { url: 'https://static.osm.osrd.fr/sprites/sprites', id: 'default' };
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for your PR. Left some comments

File: front/src/common/Map/Layers/blankStyle.ts [hunk 4]
```diff
@@ -1,24 +1,63 @@
...
+    const isDefaultSpriteValid = await isValidUrl(ponctualObjectsSprites.url);
+
+    const sprites = await Promise.all([
+      isDefaultSpriteValid ? ponctualObjectsSprites : null,
+      ...signalingSystems.map(async (id) => {
+        const signalingSystemsURL = `${window.location.origin}${baseURL}/sprites/${id}/sprites`;
+        const isValid = await isValidUrl(signalingSystemsURL);
+        return isValid ? { signalingSystemsURL, id } : null;
+      }),
+    ]);
```
Comment (SharglutDev) [inline front/src/common/Map/Layers/blankStyle.ts]: When you changed your consts (you did right, its clearer now), you missed the fact that the Sprite has an `url` property and you are now passing it as a `signalingSystemsURL` property. To avoid that for next times and increase maintainability, we can do this : 

```suggestion
    const sprites: (Sprite | null)[] = await Promise.all([
      isDefaultSpriteValid ? ponctualObjectsSprites : null,
      ...signalingSystems.map(async (id) => {
        const signalingSystemsURL = `${window.location.origin}${baseURL}/sprites/${id}/sprites`;
        const isValid = await isValidUrl(signalingSystemsURL);
        return isValid ? { url: signalingSystemsURL, id } : null;
      }),
    ]);
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for the changes, one more fix to do :)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested
