### PR TITLE
editoast: fix study start before end

### LINKED ISSUE #5479: Inconsistent dates can be entered
### What happened?

It is possible to enter inconsistent dates in the study form. end can be before start

### What did you expect to happen?

The application have to check the consistency of the dates

### How can we reproduce it (as minimally and precisely as possible)?

Create a project
Create a study
Enter inconsistent dates and see that there is no verification

### What operating system, browser and environment are you using?

- **Browser**: Version 118.0.5993.96
- **OS**: Sonoma 14.0
- **Env**: rec-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

### PR DESCRIPTION
**Pull request by Khoyo**
Fixes  #5479

### CODE REVIEW

File: editoast/src/views/study.rs [hunk 1]
```diff
@@ -68,8 +72,11 @@ struct StudyCreateForm {
 }
 
 impl StudyCreateForm {
```
Comment (leovalais) [inline editoast/src/views/study.rs:74]: Could you make this a TryFrom<>?

**Review by leovalais — APPROVED** [review]
LGTM, a suggestion:

File: editoast/src/views/study.rs (hunk 1 above)
Comment (Khoyo) [reply editoast/src/views/study.rs:74]: No, it takes a `project_id: i64` ;)
