### PR TITLE
pathfinding: use speed limit tag to compute speed limits

### LINKED ISSUE #12711: Pathfinding seems to find wrong result
### What happened?

When asking for a train with some waypoints, it gives a train with speed limits quite harsh.

Image

However, when asking for specific tracks on these waypoints, the path exists and the speed limits are way better.

Image

### What did you expect to happen?

I expect the pathfinding to find the fastest path all by itself

### How can we reproduce it (as minimally and precisely as possible)?

1. Ask @Castavo for his infra file
2. Use it on a scenario with [these train schedules](https://github.com/user-attachments/files/21581953/timetable.13.json)
3. Look at the speed space charts for both trains
4. Witness

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

a420e03

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/12711

The pathfinding looks for the shortest path (in terms of travel time at max speed), but we ignored the speed limit tags. That resulted in "wrong" results, where the train is slowed down for no good reason. 

With this PR, core can take a speed limit tag parameter. Editoast fetches it from the train schedule when simulating a train schedule, or exposes it in the API in the pure pathfinding endpoint.

### CODE REVIEW

**Comment by eckter** [comment]
> # ⚠️ API changes
> 
> This Pull Request introduces some changes in the API:
> 
>     * [ ]  please own it: notify or even prepare dedicated PR(s) to consumer projects

As far as I know, the endpoint that only runs a pathfinding and nothing else has no consumer project?

In any case, the parameter is optional and keeps the current behavior if left empty.

**Review by leovalais — APPROVED** [review]

File: core/src/main/kotlin/fr/sncf/osrd/utils/CachedBlockMRSPBuilder.kt [hunk 1]
```diff
@@ -25,20 +32,36 @@ data class CachedBlockMRSPBuilder(
...
+                    rawInfra,
+                    block,
+                    // TODO: change input to infra explorers, and fetch last route there
+                    routes = listOf(),
+                )
+            computeMRSP(
+                pathProps,
+                rsMaxSpeed,
+                rsLength,
+                true,
```
Comment (Khoyo) [inline core/src/main/kotlin/fr/sncf/osrd/utils/CachedBlockMRSPBuilder.kt]:
```suggestion
                useSpeedLimits = true,
```

**Review by Khoyo — APPROVED** [review]
Otherwise LGTM
