### PR TITLE
front: fix format time on arrival time column

### LINKED ISSUE #7619: TSv2: Times and stops tab arrival time column does not support seconds
### What happened?

Times and stops tab arrival time column does not support seconds

### What did you expect to happen?

We should be able to enter the time in the format hh:mm:ss 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Times and stops tab after a  pathfinding
2. Arrival time column format in hh:mm

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Nixos
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

local

### PR DESCRIPTION
**Pull request by Uriel-Sautron**
- disable stop time column for orign and destination
  - disable receotion on close signal column for orign
  - add step attribute to arrival time column input

close #7619

### CODE REVIEW

**Review by Yohh — APPROVED** [review]
LGTM :muscle:

**Review by achrafmohye — APPROVED** [review]
LGTM 🚀

File: front/src/modules/timesStops/TimeColumnComponent.tsx
Comment (SharglutDev) [inline front/src/modules/timesStops/TimeColumnComponent.tsx:1]: We still have an issue (doesn't seem to be reproducible by every one) when the user types the seconds on an empty time cell. When entering the first number of the seconds, as it automatically fills the cell with "04" if we press "4", the lib thinks the time is properly set and we lose the focus.

To avoid this, we can stock the temporary time value in a state and `setRowData` only with `onBlur` event.

Here is a suggestion that seems to fix it : 
1) Add the state :   
`// Allow us to stock a temporary value while the user is typing`
`// The cell is validated only when the user leaves it`
`const [tempTimeValue, setTempTimeValue] = useState(rowData ?? '');`
2) Replace the input value attribute with : `value={tempTimeValue}`
3) Replace onChange with : 
`onChange={(e) => {`
  `setTempTimeValue(e.target.value);`
`}}`
4) Add the logic for onBlur event : 
`onBlur={() => {`
  `setRowData(tempTimeValue);`
`)}`

File: front/src/modules/timesStops/TimesStops.tsx [hunk 1]
```diff
@@ -103,6 +112,10 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
           })
         ),
         title: `${t('stopTime')}`,
+
+        // We should not be edit the stopping time of the origin and destination
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimesStops.tsx]:
```suggestion
        // We should not be able to edit the stopping time of the origin and destination
```

File: front/src/modules/timesStops/TimesStops.tsx [hunk 2]
```diff
@@ -111,8 +124,10 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
           checkboxColumn as Partial<Column<boolean | undefined>>
         ),
         title: t('receptionOnClosedSignal'),
+
+        // We should not be edit the reception on close signal of the origin
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimesStops.tsx]:
```suggestion
        // We should not be able to edit the reception on close signal of the origin
```

File: front/src/modules/timesStops/TimesStops.tsx [hunk 3]
```diff
@@ -111,8 +124,10 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
...
         grow: 0.6,
-        disabled: ({ rowData }) => !rowData.stopFor,
+        disabled: ({ rowData, rowIndex }) => !rowData.stopFor || rowIndex === 0,
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimesStops.tsx]: As we can't edit the stopping time of the origin, we won't be able to edit the "on close "signal" anyway so I don't think we need this condition (if you agree, you can also remove the comment)

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for this PR, left some comments.

As it changes various things on the TimesStops component, maybe it would have been better to have one commit for each fonctionnality fixed or added.

File: front/src/modules/timesStops/TimesStops.tsx (hunk 1 above)
Comment (Uriel-Sautron) [reply front/src/modules/timesStops/TimesStops.tsx]: Done

File: front/src/modules/timesStops/TimesStops.tsx (hunk 2 above)
Comment (Uriel-Sautron) [reply front/src/modules/timesStops/TimesStops.tsx]: Done

File: front/src/modules/timesStops/TimesStops.tsx (hunk 3 above)
Comment (Uriel-Sautron) [reply front/src/modules/timesStops/TimesStops.tsx]: Done

File: front/src/modules/timesStops/TimeColumnComponent.tsx
Comment (Uriel-Sautron) [reply front/src/modules/timesStops/TimeColumnComponent.tsx:1]: Done

**Review by kmer2016 — APPROVED** [review]
LGTM, don't forget to squash

**Review by SharglutDev — COMMENTED** [review]
Lgtm and tested, good job ! Waiting for commis cleaning to approve

File: front/src/modules/timesStops/TimeColumnComponent.tsx [hunk 4]
```diff
@@ -1,37 +1,41 @@
...
-      value={rowData ?? ''}
+      value={tempTimeValue ?? ''}
       onChange={(e) => {
-        const time = e.target.value;
-        setRowData(time);
+        setTempTimeValue(e.target.value);
+      }}
+      onBlur={() => {
+        if (tempTimeValue) setRowData(tempTimeValue);
       }}
```
Comment (SharglutDev) [inline front/src/modules/timesStops/TimeColumnComponent.tsx]:
```suggestion
      // To prevent the operational point to be transformed into a via if we leave the cell empty after focusing it
        if (rowData !== tempTimeValue) {
          setRowData(tempTimeValue);
        }
```

**Review by SharglutDev — APPROVED** [review]
