### PR TITLE
front: fix nodes import in MacroEditor

### LINKED ISSUE #14765: Internal error when moving a node in macro mode
### What happened?

- Open a scenario, with no nodes, with a macro mode closed
- Create a train from an OP to another OP
- Open the macro node, and try to move a node : you get the following error

Image

Note that it seems to happen only the first time you open the macro node. It seems that once the nodes are created, the problem does not appear anymore. 

### What did you expect to happen?

I expect no error

### How can we reproduce it (as minimally and precisely as possible)?

See above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

aaaa8e1

### LINKED ISSUE #15061: Error moving macro nodes, and not saving changes
### What happened?

> [!NOTE]
> Might be a duplicate of : https://github.com/OpenRailAssociation/osrd/issues/14765 

Moved nodes generate an error and are not saved.

> [!IMPORTANT]
> A specific list of actions must be performed to trigger this bug. Please read the steps to reproduce carefully.

Image

Network error:

`POST` `http://localhost:4000/api/macro_nodes` -> `500`

```json
{
  "status": 500,
  "type": "editoast:macro_node:Database",
  "context": {},
  "message": "an error occurred while querying the database: current transaction is aborted, commands ignored until end of transaction block"
}
```

After investigation this error occurs because of the unicity constraint `scenario_id, path_item_key` is violated.

### What did you expect to happen?

We should be able to move nodes without errors.

### How to fix ?

**Editoast**:
- We should return a `400` error when a node is created with an existing `path_item_key`.

**Frontend**:
- After the creation of a `MacroNode` the `PUT` endpoint should be call instead of the `POST` (which is only used for creation).

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with small infra
2. Open Macro tab 
3. Import this [timetable.json](https://github.com/user-attachments/files/25074341/timetable.json)
4. The train should be imported in the train list but not in macro view (first issue :/)
5. Refresh the page
6. Now the train and its two nodes are there
7. Try to move them arround

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6069bc8

### PR DESCRIPTION
**Pull request by aschantraine**
Ensures newly imported nodes are handled correctly:

- Updated `storeTrainPathNodes` to persist new nodes and immediately update their state with the corresponding database IDs (fixes 500 errors when moving newly imported macro nodes).
- Fixed e2e test `Delete a train from train list`
- Merged the language change and macro board activation `useEffects` into a single one to prevent duplicate calls to `refreshNge` (fixes 500 errors when refreshing after an import).

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/utils.ts [hunk 1]
```diff
@@ -122,11 +122,21 @@ export const storeTrainPathNodes = async (state: MacroEditorState, dispatch: App
...
 
-  await dispatch(
+  const result = await dispatch(
     osrdEditoastApi.endpoints.postMacroNodes.initiate({
       macroNodeBatchForm: { macro_nodes: payload, scenario_id: state.scenarioId },
     })
   ).unwrap();
+
+  result.macro_nodes.forEach((createdNode) => {
+    const existingNode = state.getNodeByKey(createdNode.path_item_key);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/utils.ts]: `updateNodeDataByKey()` can be used here instead of `getNodeByKey()` + `indexNodeByKey()`.

**Review by Synar — APPROVED** [review]
Lgtm!

**Comment by emersion** [comment]
Can the PR title be edited to be more explicit what exactly is being fixed? The commit title seems fine to me.

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/utils.ts (hunk 1 above)
Comment (aschantraine) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/utils.ts]: Done

**Review by emersion — APPROVED** [review]
