### PR TITLE
front: fix invalid date handling and disable search button when date is invalid

### LINKED ISSUE #11045: Finding anterior train in invalid date
### What happened?

https://github.com/user-attachments/assets/13e9c587-3233-4ff6-81e6-b01a94692273

In LMR, when you're searching for an anterior train, you can enter manually an invalid date. A red sign shows but you can still search for it. It seems to find paths in the first valid date of the period.

For the posterior train, you can still do the search but it semms not to find any train when you enter an invalid date.

### What did you expect to happen?

I would not be able to search for trains in invalid dates.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to LMR
2. Search for an anterior train in the first date of the period
3. Enter another date manually, outside of the period
4. Search for the same train

### On which environments the bug occurs?

Recette (SNCF), Production (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

3176332

### PR DESCRIPTION
**Pull request by Maymanaf**
Closes #11045

### CODE REVIEW

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts [hunk 1]
```diff
@@ -68,19 +70,21 @@ export default function useDatePicker(datePickerProps: DatePickerProps) {
     if (inputIsDate) {
       const [day, month, year] = newValue.split('/').map(Number);
       const date = new Date(year + 2000, month - 1, day);
+      const isRealDate =
+        !Number.isNaN(date.getTime()) &&
+        date.getFullYear() === year &&
+        date.getMonth() === month - 1 &&
+        date.getDate() === day;
```
Comment (clarani) [inline front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: This test is enough :+1: 
```suggestion
      const isRealDate = !Number.isNaN(date.getTime());
```

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts [hunk 2]
```diff
@@ -68,19 +70,21 @@ export default function useDatePicker(datePickerProps: DatePickerProps) {
...
 
-      if (!isNaN(date.getTime()) && isWithinInterval(date, selectableSlot) && onDateChange) {
-        onDateChange(date);
-      } else {
+      if (!isRealDate && !isWithinInterval(date, selectableSlot)) {
```
Comment (clarani) [inline front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: From what I understant, your logic here is:
- if the date is invalid (not a real date) or is not in the allowed range, then you show the error message
- else you reset the error message and change the date in the parent component
- then, with your useEffect + isValid + lastValidityRef, you can detect if the current date is invalid and dire the callback onValidityChange

I'm not convinced by this approach because it adds complexity and asynchrony (you have to wait for a render loop to complete the useEffect, which will also trigger a callback).

I think it would be simpler to follow this workflow:
- if the date is invalid, then show the error message
- else reset the error message
- in both case, change the date in the parent component
- in the callback onDateChange, check the valid status of the given date and depending on that, update isLinkedTrainDateValid

If you don't want to check again the valid status of the given date, you can change the signature of the callback onDateChange so it can take a second argument (optional) which would indicate the validity status of the new date

**Comment by SharglutDev** [comment]
Don't forget to rename your first commit with `ui-core: ...` instead of `front: ...` :)

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts (hunk 1 above)
Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: Done

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts (hunk 2 above)
Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: Done

**Review by clarani — COMMENTED** [review]
LGTM, could you squash your commits please ? I will test right after that

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts [hunk 3]
```diff
@@ -68,19 +67,19 @@ export default function useDatePicker(datePickerProps: DatePickerProps) {
...
-
-      if (!isNaN(date.getTime()) && isWithinInterval(date, selectableSlot) && onDateChange) {
+      const isRealDate = !Number.isNaN(date.getTime());
+      const isValid = isRealDate && isWithinInterval(date, selectableSlot);
+      if (isValid) {
+        setStatusWithMessage(undefined);
         onDateChange(date);
       } else {
         setStatusWithMessage({ status: 'error', message: errorMessages?.invalidDate });
+        onDateChange(date, { valid: false });
```
Comment (emersion) [inline front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: Is `valid` really useful? Would it make more sense to call `onDateChange(undefined)` on invalid dates instead?

Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: Yes, the `validity `state is used to disable the search button. If it’s not set here, the button remains active

Comment (emersion) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: Why should the search button be enabled when there is no date? In both cases (no date set, or invalid date), the form cannot be submitted, no?

Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: When no date is provided, it is treated as invalid input, which is handled at line 82 with o`nDateChange(undefined, { valid: false });` 
I use the `valid `state in `onDateChange` to explicitly indicate the validity of the new date. If I only call `onDateChange(undefined)`, there is no way to detect new inputs and` isLinkedTrainDateValid` would  always return `true`, since its default value is a valid date.

Comment (emersion) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: What I'm suggesting is replacing `onDateChange(date, { valid: false });` with `onDateChange(undefined);` and `isLinkedTrainDateValid` with `date !== undefined`.

Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts]: I got it 
Done

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts [hunk 4]
```diff
@@ -68,19 +67,19 @@ export default function useDatePicker(datePickerProps: DatePickerProps) {
...
+        setStatusWithMessage(undefined);
         onDateChange(date);
       } else {
         setStatusWithMessage({ status: 'error', message: errorMessages?.invalidDate });
+        onDateChange(undefined);
       }
-      return;
-    }
 
-    if (containsOnlyNumbersAndSlashes(newValue) && newValue.length < 8) {
```
Comment (emersion) [inline front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts:80]: I _think_ this check exists to allow the user to start typing something without showing immediately an error. I'm not in love with the way it was done previously, but wouldn't removing this introduce a regression?

File: front/src/applications/stdcm/components/StdcmForm/StdcmLinkedTrainSearch.tsx [hunk 5]
```diff
@@ -106,6 +110,8 @@ const StdcmLinkedTrainSearch = ({
               className="stdcm-linked-train-button"
               type="button"
               onClick={launchTrainScheduleSearch}
+              disabled={!isLinkedTrainDateValid}
+              aria-disabled={!isLinkedTrainDateValid}
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmForm/StdcmLinkedTrainSearch.tsx]: I don't think `aria-disabled` is necessary when we're setting the `disabled` attribute. `aria-*` attributes should only be used when the standard semantic attributes can't be used.

**Review by emersion — COMMENTED** [review]
Thanks, two more minor comments, LGTM with these addressed!

File: front/src/applications/stdcm/components/StdcmForm/StdcmLinkedTrainSearch.tsx (hunk 5 above)
Comment (Maymanaf) [reply front/src/applications/stdcm/components/StdcmForm/StdcmLinkedTrainSearch.tsx]: Done

File: front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts (hunk 4 above)
Comment (Maymanaf) [reply front/ui/ui-core/src/components/inputs/datePicker/useDatePicker.ts:80]: Not fun either, I reintroduced the check

File: front/src/applications/stdcm/styles/_linkedTrain.scss [hunk 6]
```diff
@@ -38,15 +38,24 @@
...
       }
+
       .stdcm-linked-train-loading {
         color: var(--primary90);
         align-self: center;
       }
     }
 
+    .stdcm-linked-train-button[disabled],
+    .stdcm-linked-train-button[aria-disabled='true'] {
```
Comment (emersion) [inline front/src/applications/stdcm/styles/_linkedTrain.scss]: This line can be removed now I think.

**Review by emersion — APPROVED** [review]
LGTM, feel free to resolve this last comment!
