### PR TITLE
front: fix error msg blinking on pending op search in itinerary modal

### LINKED ISSUE #15715: new itinerary modal: blinking "unrecognized path step" error when adding a path step from a suggestion
### What happened?

Same issue as https://github.com/OpenRailAssociation/osrd/issues/15029

The "unrecognized path step" error appears for a fraction of a second when choosing a suggestion from the list of operational points.

https://github.com/user-attachments/assets/fa8bfeb0-4aae-4efb-a212-61f72bb97aae

### What did you expect to happen?

no error should appear

### How can we reproduce it (as minimally and precisely as possible)?

1. edit a train with the new itinerary modal
2. in the text field for adding a new path step (the last text field in the list)
3. fill it with a valid trigram for the infra
4. a suggestion should appear
5. click on the suggestion

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

347a03d

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15715 

now checking if the op is coming from the ```PathStepItem``` and if its resolution is pending.

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 1]
```diff
@@ -398,6 +398,15 @@ const ItineraryModal = ({
     frameAllPathSteps();
   }, [pathStepsMetadataById, hasInvalidPathStep]);
 
+  useEffect(() => {
```
Comment (hhirtz) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: i don't really understand the fix. shouldn't suggestions carry enough info so that the front doesn't have to fetch anything from the back when choosing one? why is there a pending state? 🤔 

(noob question) shouldn't `useEffect` be only used to interact with the DOM?

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: See also this page: https://react.dev/learn/you-might-not-need-an-effect

Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: The thing is that when we enter a suggestion, the suggestion goes through ```usePathStepMetadata```, that will check if it has a valid location. If it is valid, then we set ```isInvalid``` to false. But during the 1-2 seconds of the resolving metadata, the operational point is invalid, so we need to know when the metadata is pending or if it's just invalid because we don't have a valid location.

Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: About the useEffect, I don't think its use is limited to interact with the DOM, but in the case of this PR, I think I could do the fix without a useEffect also, that could be better.

**Review by hhirtz — APPROVED** [review]
Tested and the error didn't show up when pressing enter or clicking a suggestion

not sure if it's unrelated or could be fixed in the same commit, but there is another glitch in the textfield, you can see the name changes for a fraction of a second:

https://github.com/user-attachments/assets/a4fa4d74-ee4a-4bec-a9a9-6056acc06387

on the video the name goes from "SES South_East_station" to "South_East_station BV" very quickly. also i can't reproduce it on video, but sometimes when accepting a suggestion the name can change from one to the other.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: I removed the useEffect 👍

**Comment by RomainValls** [comment]
> Tested and the error didn't show up when pressing enter or clicking a suggestion
> 
> not sure if it's unrelated or could be fixed in the same commit, but there is another glitch in the textfield, you can see the name changes for a fraction of a second:
> 
>  2026-03-13.15-25-20.mp4 
> on the video the name goes from "SES South_East_station" to "South_East_station BV" very quickly. also i can't reproduce it on video, but sometimes when accepting a suggestion the name can change from one to the other.

good catch thx ! handled it in the fixup

**Review by hhirtz — COMMENTED** [review]
https://github.com/user-attachments/assets/fc747d08-5077-4ad7-92f8-4f0dbac2ce86

the secondary code is shown as "undefined" while pending

**Review by hhirtz — APPROVED** [review]
tested, no blinking found

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅
