### PR TITLE
front: Fix cartography sub windows

### LINKED ISSUE #2831: Cartography sub-windows do not respond as we'd want
### What happened?

Let's take the example of the map settings menu.

The cartography settings menu goes as follow :
image

It has some unwanted behaviors : 
- When clicking outside of the menu, it does not close it
- The close button is located at the bottom right corner, instead of being an X at the top right corner
image

- When opening the settings menu, if an origin/destination menu is already open on the map they overlap each other
image

- When opening another menu, it will also overlap and eventually make a really ugly sandwich
image

### What did you expect to happen?

- When clicking outside of the menu (but still inside the map component), it should close it
- There should be an X at the top right corner of the menu to close it
- When opening the settings menu, if an origin/destination menu is already open on the map it should be closed and replaced by the new menu
- Clicking a button to open another menu should always replace the menu currently open if there's one
- The dot enabling the origin or destination selection should not appear if a menu is open. Hence, clicking on the map has no other effect than closing the menu.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the home page of the time table module
2. Open the map settings menu
3. Try the several behaviors listed above

### What operating system and browser are you using? (if applicable)

- Windows 3.11
- Netscape Explorer

### OSRD version

1.0

### PR DESCRIPTION
**Pull request by Uriel-Sautron**
close #2831

### CODE REVIEW

**Comment by alexandredamiron** [comment]
Even if there is no conflict, could you rebase? It's hard to test. Thank you

**Comment by Uriel-Sautron** [comment]
Rebase done but work to replace eventListener in MapButton.js

**Comment by Uriel-Sautron** [comment]
Create custom hook useOutsideClick to use in MapButtons.

File: front/src/common/Map/MapKey.js [hunk 1]
```diff
@@ -11,7 +11,12 @@ export default function MapSettings(props) {
   const { t } = useTranslation(['translation', 'map-key']);
   return (
     <div className={`map-modal map-modal-dark ${active ? 'active' : ''}`}>
-      <div className="h2 text-light">{t('map-key:keyTitle')}</div>
+      <div className="d-flex justify-content-between align-items-start">
+        <div className="h2 text-light">{t('map-key:keyTitle')}</div>
+        <button type="button" className="close text-light" onClick={toggleMapKey}>
+          ×
```
Comment (clarani) [inline front/src/common/Map/MapKey.js]: Use rather `&times;` instead of the x
```suggestion
          &times;
```

File: front/src/common/Map/Search/MapSearch.js [hunk 2]
```diff
@@ -15,54 +15,55 @@ export default function MapSearch(props) {
...
+
   return (
     <div className={`map-modal${active ? ' active' : ''}`}>
-      <div className="h2">{t('translation:common.search')}</div>
+      <div className="d-flex justify-content-between align-items-start">
+        <div className="h2">{t('translation:common.search')}</div>
+        <button type="button" className="close" onClick={toggleMapSearch}>
+          ×
+        </button>
+      </div>
```
Comment (clarani) [inline front/src/common/Map/Search/MapSearch.js]: As you are adding this piece of code 3 times, you can create a const or a function to factorize the code :)

File: front/src/common/Map/Buttons/MapButtons.js [hunk 3]
```diff
@@ -12,28 +12,71 @@ import ButtonFullscreen from 'common/ButtonFullscreen';
...
+  const featureInfoClick = useSelector(getFeatureInfoClick);
+  const dispatch = useDispatch();
+
+  const mapModalKeywords = {
+    search: false,
+    settings: false,
+    key: false,
+  };
+
+  const [showMapModal, setShowMapModal] = useState(mapModalKeywords);
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.js]: I think it would be better if you keep in the state only the value of the opened modal, and not a dict like this.

You can create a dict which will contain all the possible opened modal names (in TS, you can use enums https://www.typescriptlang.org/docs/handbook/enums.html), and then create a state variable which will store the opened modal.
```
MAP_POPOVERS = { SEARCH: "SEARCH", SETTINGS: "SETTINGS", KEY: "KEY" };

const [openedPopover, setOpenedPopover] = useState(undefined);
```

Then you can show the Popover only if openedPopover has the right value
```
{ openedPopover === MAP_POPOVERS.SEARCH &&
      <MapSearch active={showMapModal.search} toggleMapSearch={() => toggleMapModal('search')} /> }
{ openedPopover === MAP_POPOVERS.SETTINGS &&
      <MapSettings
        active={showMapModal.settings}
        toggleMapSettings={() => toggleMapModal('settings')}
      /> }
{ openedPopover === MAP_POPOVERS.KEY &&
      <MapKey active={showMapModal.key} toggleMapKey={() => toggleMapModal('key')} /> }
```

Of course you will need to adapt the function toggleMapKey. Feel free to call me if you have any question

File: front/src/common/Map/Search/MapSearch.js [hunk 4]
```diff
@@ -15,54 +15,55 @@ export default function MapSearch(props) {
...
+            {tabItems.map((tab, index) => (
+              <li className="navtabs-item pr-4" key={`tab-${tab.title}`}>
+                <a
+                  href={`#tab${index + 1}`}
+                  className={tab.className}
+                  id={`titletab${index + 1}`}
+                  data-toggle="tab"
+                  role="tab"
+                  aria-controls={`tab${index + 1}`}
+                  aria-selected="true"
```
Comment (clarani) [inline front/src/common/Map/Search/MapSearch.js]: All the tabs did not have aria-selected=true before your change (see above)

File: front/src/common/Map/Search/MapSearch.js [hunk 5]
```diff
@@ -15,54 +15,55 @@ export default function MapSearch(props) {
...
+    },
+    {
+      className: '',
+      title: t('map-search:signalbox'),
+    },
+    {
+      className: '',
+      title: t('map-search:signal'),
+    },
+  ];
```
Comment (clarani) [inline front/src/common/Map/Search/MapSearch.js]: Nice factorization :)

File: front/src/common/Map/Settings/MapSettings.js [hunk 6]
```diff
@@ -21,7 +21,12 @@ export default function MapSettings(props) {
   if (active) {
     return (
       <div className={`map-modal${active ? ' active' : ''}`}>
-        <div className="h2">{t('map-settings:mapSettings')}</div>
+        <div className="d-flex justify-content-between align-items-start">
+          <div className="h2">{t('map-settings:mapSettings')}</div>
+          <button type="button" className="close" onClick={toggleMapSettings}>
+            ×
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettings.js]: Same as above ^

**Review by clarani — CHANGES_REQUESTED** [review]
Nice job ! I have left several comments.

I think the modals (or popovers) do not need to have active in their props, since they should not be displayed if they are not active. Some refacto can be done if you remove active of each component (MapSearch, MapSettings, MapKey)

File: front/src/common/Map/MapKey.js (hunk 1 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/MapKey.js]: Done

File: front/src/common/Map/Search/MapSearch.js (hunk 5 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Search/MapSearch.js]: Thank you

File: front/src/common/Map/Settings/MapSettings.js (hunk 6 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Settings/MapSettings.js]: Done

File: front/src/common/Map/Search/MapSearch.js (hunk 2 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Search/MapSearch.js]: Done

File: front/src/common/Map/Search/MapSearch.js (hunk 4 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Search/MapSearch.js]: Done

File: front/src/common/Map/Buttons/MapButtons.js (hunk 3 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Buttons/MapButtons.js]: Done

File: front/src/common/Map/Buttons/MapButtons.js [hunk 7]
```diff
@@ -12,28 +12,68 @@ import ButtonFullscreen from 'common/ButtonFullscreen';
...
 
 export default function MapButtons(props) {
   const { resetPitchBearing, withInfraButton } = props;
-  const [showSearch, setShowSearch] = useState(false);
-  const [showSettings, setShowSettings] = useState(false);
-  const [showMapKey, setShowMapKey] = useState(false);
+  const featureInfoClick = useSelector(getFeatureInfoClick);
+  const dispatch = useDispatch();
+
+  const MAP_POPOVERS = { SEARCH: 'SEARCH', SETTINGS: 'SETTINGS', KEY: 'KEY' };
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.js]: Can you instantiate this dict outside the component ? This way, it won't be re-created each time the component re-render

File: front/src/common/Map/Buttons/MapButtons.js [hunk 8]
```diff
@@ -12,28 +12,68 @@ import ButtonFullscreen from 'common/ButtonFullscreen';
...
+
+  const [openedPopover, setOpenedPopover] = useState(undefined);
+
+  const toggleMapModal = (keyModal) => {
+    if (keyModal === openedPopover) {
+      keyModal = undefined;
+    }
+    setOpenedPopover(keyModal);
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.js]: Can use a ternary condition here
```suggestion
    setOpenedPopover(keyModal !== openedPopover ? keyModal : undefined);
```

File: front/src/common/Map/Buttons/MapButtons.js [hunk 9]
```diff
@@ -12,28 +12,68 @@ import ButtonFullscreen from 'common/ButtonFullscreen';
...
+    // Close the pop up of the map
+    if (featureInfoClick.displayPopup) {
+      dispatch(
+        updateFeatureInfoClickOSRD({
+          displayPopup: false,
+          feature: undefined,
+        })
+      );
+    }
+  };
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.js]: This is not useful anymore, you can remove it

File: front/src/common/Map/Settings/MapSettings.js [hunk 10]
```diff
@@ -18,70 +19,57 @@ export default function MapSettings(props) {
...
+    <div className="map-modal">
+      <HearderPopUp onClick={toggleMapSettings} title={t('map-settings:mapSettings')} />
+      <MapSettingsTrackSources />
+      <div className="my-1" />
+      <MapSettingsMapStyle />
+      <div className="my-1" />
+      <MapSettingsBackgroundSwitches />
+      <div
+        className="mb-1 mt-3 border-bottom d-flex align-items-center sub-section-title"
+        onClick={() => toogleShowSettings(setShowSettingsSignals)}
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettings.js]: Typo in the file
```suggestion
        onClick={() => toggleShowSettings(setShowSettingsSignals)}
```

File: front/src/common/Map/Search/MapSearch.js [hunk 11]
```diff
@@ -14,55 +15,53 @@ export default function MapSearch(props) {
...
+    {
+      className: '',
+      title: t('map-search:signal'),
+      ariaSelected: 'false',
+    },
+  ];
+
+  return (
+    <div className="map-modal">
+      <HearderPopUp onClick={toggleMapSearch} title={t('translation:common.search')} />
```
Comment (clarani) [inline front/src/common/Map/Search/MapSearch.js]: It would be clearer if the function name was `closeMapSearchPopUp`

File: front/src/common/Map/Settings/MapSettings.js [hunk 12]
```diff
@@ -18,70 +19,57 @@ export default function MapSettings(props) {
...
-        </div>
-        {showSettingsSpeedLimits && <MapSettingsSpeedLimits />}
-        <div className="mt-2 d-flex flex-row-reverse w-100">
-          <button className="btn btn-secondary btn-sm" type="button" onClick={toggleMapSettings}>
-            {t('translation:common.close')}
-          </button>
-        </div>
+  return (
+    <div className="map-modal">
+      <HearderPopUp onClick={toggleMapSettings} title={t('map-settings:mapSettings')} />
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettings.js]: It would be clearer if the function name was closeMapSettingsPopup

File: front/src/common/Map/MapKey.tsx [hunk 13]
```diff
@@ -38,8 +39,8 @@ const MapSettings = ({ toggleMapKey }: MapKeyProps) => {
   ));
 
   return (
-    <div className="map-modal map-modal-dark active">
-      <div className="h2 text-light">{t('map-key:keyTitle')}</div>
+    <div className="map-modal map-modal-dark">
+      <HearderPopUp onClick={toggleMapKey} title={t('map-key:keyTitle')} isLight />
```
Comment (clarani) [inline front/src/common/Map/MapKey.tsx]: It would be clearer if the function name was closeMapKeyPopUp

File: front/src/common/Map/Map.scss [hunk 14]
```diff
@@ -21,13 +21,12 @@
...
 .map-modal {
   position: absolute;
-  z-index: 0;
+  z-index: 1;
   min-height: 5rem;
   max-height: 80%;
   overflow: auto;
   top: 4rem;
   right: 3.5rem;
-  opacity: 0;
```
Comment (clarani) [inline front/src/common/Map/Map.scss:30]: Can also remove the code css of .active (just below)

**Review by clarani — CHANGES_REQUESTED** [review]
Some small comments to fix

File: front/src/applications/operationalStudies/components/ManageTrainSchedule/ManageTrainScheduleMap/RenderPopup.js [hunk 15]
```diff
@@ -24,11 +25,8 @@ export default function RenderPopup() {
     const properties = {
       ...featureInfoClick.feature.properties,
       source: featureInfoClick.feature.source,
-      clickLngLat: [
-        featureInfoClick.coordinates[0],
-        featureInfoClick.coordinates[1],
-      ]
-    }
+      clickLngLat: [featureInfoClick.coordinates[0], featureInfoClick.coordinates[1]],
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/components/ManageTrainSchedule/ManageTrainScheduleMap/RenderPopup.js]:
```suggestion
      clickLngLat: featureInfoClick.coordinates.slice(0,2)
```

**Review by anisometropie — CHANGES_REQUESTED** [review]

File: front/src/common/Map/Buttons/MapButtons.js (hunk 7 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Buttons/MapButtons.js]: Done

File: front/src/common/Map/Buttons/MapButtons.js (hunk 8 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Buttons/MapButtons.js]: Done

File: front/src/common/Map/Settings/MapSettings.js (hunk 10 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Settings/MapSettings.js]: Done

File: front/src/common/Map/Search/MapSearch.js (hunk 11 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Search/MapSearch.js]: Done

File: front/src/common/Map/Settings/MapSettings.js (hunk 12 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Settings/MapSettings.js]: Done

File: front/src/common/Map/MapKey.tsx (hunk 13 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/MapKey.tsx]: Done

File: front/src/common/Map/Map.scss (hunk 14 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Map.scss:30]: Done

File: front/src/common/Map/Buttons/MapButtons.js (hunk 9 above)
Comment (Uriel-Sautron) [reply front/src/common/Map/Buttons/MapButtons.js]: I need it to close the origin/destination menu when clicking on the settings menu.

File: front/src/applications/operationalStudies/components/ManageTrainSchedule/ManageTrainScheduleMap/RenderPopup.js (hunk 15 above)
Comment (Uriel-Sautron) [reply front/src/applications/operationalStudies/components/ManageTrainSchedule/ManageTrainScheduleMap/RenderPopup.js]: Done

**Review by clarani — DISMISSED** [review]
Nice job

**Review by anisometropie — APPROVED** [review]
