### PR TITLE
core: fix crash when the path doesn't contain all block zones

### LINKED ISSUE #13845: simulation failed for trains that should not fail
### What happened?

For this train, I have a simulation failure (but pathfinding works) on a stable France infrastructure. It is new because my train was valid on the same infra with this version : 

Can be tested on this scenario 

https://rec-osrd.reseau.sncf.fr/operational-studies/projects/132/studies/969/scenarios/1972?selected_train=trainschedule_7183219&projection=trainschedule_7183219

The json is the following : 

[timetable (95).json](https://github.com/user-attachments/files/23236017/timetable.95.json)

### What did you expect to happen?

I expect my train to be valid

### How can we reproduce it (as minimally and precisely as possible)?

Import this train on France infra 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

cf97371

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/13845

`SignalingSimulator.evaluate` isn't migrated to the new path types yet, while the call site is (`ScheduleMetadataExtractor`).

I wasn't careful enough on this interface: the zone state list is built using only the zones that are part of the path, while `evaluate` expects them to include all zones included in the covered blocks. 

This doesn't properly migrate the method to the new types, it's just an quick fix to avoid the crash. 

Includes a test that did fail without the fix.

### CODE REVIEW

File: core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt [hunk 1]
```diff
@@ -98,4 +104,107 @@ class TestBALtoBAL {
             res[loadedSignalInfra.getLogicalSignals(signalV).first()]!!.getEnum("aspect"),
         )
     }
+
+    @Test
+    fun testBALtoBALPartialBlock() {
+        // All "I" mark the location of detectors, which delimit zones.
+        // Compared to the test above: there's an extra detector with no signal between U and V. The
+        // train path start after that detector, before V.
```
Comment (Erashin) [inline core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt]: `starts`

File: core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt [hunk 2]
```diff
@@ -98,4 +104,107 @@ class TestBALtoBAL {
             res[loadedSignalInfra.getLogicalSignals(signalV).first()]!!.getEnum("aspect"),
         )
     }
+
+    @Test
+    fun testBALtoBALPartialBlock() {
+        // All "I" mark the location of detectors, which delimit zones.
+        // Compared to the test above: there's an extra detector with no signal between U and V. The
```
Comment (Erashin) [inline core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt:111]: nit: I feel like we should probable factorize those tests, they do have almost everything in common. But yeah not the point of the pr.

**Review by Erashin — APPROVED** [review]
Gj!

File: core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt (hunk 2 above)
Comment (eckter) [reply core/kt-osrd-sncf-signaling/src/test/kotlin/fr/sncf/osrd/signaling/bal/TestBALtoBAL.kt:111]: Eh, some duplication doesn't hurt for tests. It's easier to make small changes that way.

**Review by flomonster — APPROVED** [review]
Thanks
