### PR TITLE
front: fix origin and destination are not displayed by default

### LINKED ISSUE #10883: front: manchette origin and destination aren't displayed by default when importing train
### What happened?

I imported 

[2-train_schedules with-speed-limits.json](https://github.com/user-attachments/files/18888273/2-train_schedules.with-speed-limits.json)

 in my scenario and got this manchette.

Image

The origin and destination where not selected by default so only part of my train was displayed.

Image

### What did you expect to happen?

I'm expecting origin and destination to be displayed by default

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce description. 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

776f9b3

### PR DESCRIPTION
**Pull request by theocrsb**
closes #10883

### CODE REVIEW

**Review by Caracol3 — COMMENTED** [review]
Good job. Tested and works fine

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 1]
```diff
@@ -88,8 +88,11 @@ const useGetProjectedTrainOperationalPoints = (
...
           // If the manchette hasn't been saved, we want to display by default only
           // the waypoints with CH BV/00/'' and the path steps (origin, destination, vias)
-          operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter((op) =>
-            op.extensions?.sncf ? isStation(op.extensions.sncf.ch) || op.weight === 100 : true
+          operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter(
+            (op, i) =>
+              i === 0 ||
+              i === operationalPointsWithUniqueIds.length - 1 ||
+              (op.extensions?.sncf ? isStation(op.extensions.sncf.ch) || op.weight === 100 : true)
           );
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hum it's a bit hard to read. Can you write a more explicit function like this ?
```suggestion
           operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter((op, i) => {
            if (i === 0 || i === operationalPointsWithUniqueIds.length - 1) return true;
            // handle waypoints added from the map
            if (!op.extensions?.sncf) return true;
            // handle waypoints added from the pathfinding or operational points on path
            return isStation(op.extensions.sncf.ch) || op.weight === 100;
          });
```

Comment (theocrsb) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 2]
```diff
@@ -88,9 +88,13 @@ const useGetProjectedTrainOperationalPoints = (
...
-          operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter((op) =>
-            op.extensions?.sncf ? isStation(op.extensions.sncf.ch) || op.weight === 100 : true
-          );
+          operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter((op, i) => {
+            if (i === 0 || i === operationalPointsWithUniqueIds.length - 1) return true;
+            // handle waypoints added from the map
+            if (!op.extensions?.sncf) return true;
+            // handle waypoints added from the pathfinding or operational points on path
+            return isStation(op.extensions.sncf.ch) || op.weight === 100;
+          });
```
Comment (Caracol3) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]:
```suggestion
          if (operationalPointsWithUniqueIds.length > 0) {
  const lastIndex = operationalPointsWithUniqueIds.length - 1;

  operationalPointsWithUniqueIds = operationalPointsWithUniqueIds.filter((op, i) => {
    if (i === 0 || i === lastIndex) return true;
    if (!op.extensions?.sncf) return true;
    return isStation(op.extensions.sncf.ch) || op.weight === 100;
  });
}
```

We could maybe use a const like this to avoid recalculation on each iteration of the filter

Comment (theocrsb) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done

**Review by Caracol3 — APPROVED** [review]
lgtm

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
