### PR TITLE
front: rollingstockeditor: fix hidden dupplicated RS when locked filter is checked

### LINKED ISSUE #5005: front: rollingstockeditor: duplicated RS is hidden if "locked" checkbox is checked
### What happened?

if we use the "locked" checkbox, then dupplicate it, the new "unlocked" RS is hidden and the left panel is disabled

### What did you expect to happen?

we should use the filters when using the edit mode

### How can we reproduce it (as minimally and precisely as possible)?

1. got rolling stock editor
2. check "locked" filter
3. dupplicate it

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: MacOS ventura13.5.1
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

0bb2368c

### PR DESCRIPTION
**Pull request by Yohh**
- add rollingstock-editor-filters class in _rollingStockEditor.scss
- set z-index: 110 in rollingstock-editor-filters class

close #5005

### CODE REVIEW

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx [hunk 1]
```diff
@@ -31,6 +31,7 @@ export default function RollingStockEditor({ rollingStocks }: RollingStockEditor
   const [isLoading, setIsLoading] = useState(false);
   const [isEditing, setIsEditing] = useState(false);
   const [isAdding, setIsAdding] = useState(false);
+  const [isDupplicating, setIsDupplicating] = useState(false);
```
Comment (Math-R) [inline front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: duplicating*

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx [hunk 2]
```diff
@@ -84,6 +85,7 @@ export default function RollingStockEditor({ rollingStocks }: RollingStockEditor
                     isCondensed
                     rollingStock={selectedRollingStock}
                     setIsEditing={setIsEditing}
+                    setIsDupplicating={setIsDupplicating}
```
Comment (Math-R) [inline front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: same

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx [hunk 3]
```diff
@@ -160,8 +164,21 @@ const SearchRollingStock = ({
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [filters, rollingStocks]);
 
+  useEffect(() => {
+    if (isDupplicating) {
+      setFilters({
```
Comment (Math-R) [inline front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: Can you set this in a new function resetFilters ?

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx (hunk 1 above)
Comment (Yohh) [reply front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: done

File: front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx (hunk 2 above)
Comment (Yohh) [reply front/src/applications/rollingStockEditor/views/RollingStockEditor.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx (hunk 3 above)
Comment (Yohh) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx [hunk 4]
```diff
@@ -149,6 +153,19 @@ const SearchRollingStock = ({
     setFilteredRollingStockList(newFilteredRollingStock);
   }
 
+  const resetFilters = () => {
+    if (mustResetFilters) {
```
Comment (Math-R) [inline front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: this test must be made in the useEffect hook, because, maybe in further iteration, there will be a button handled by this component to reset all the filter.

`mustResetFilters` come from the props it's why you should test it in the hook

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx [hunk 5]
```diff
@@ -149,6 +153,19 @@ const SearchRollingStock = ({
...
+      setFilters({
+        text: '',
+        elec: false,
+        thermal: false,
+        locked: false,
+        notLocked: false,
+      });
+      if (setMustResetFilters) setMustResetFilters(false);
```
Comment (Math-R) [inline front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: same as above

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx (hunk 4 above)
Comment (Yohh) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx (hunk 5 above)
Comment (Yohh) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx [hunk 6]
```diff
@@ -160,8 +174,15 @@ const SearchRollingStock = ({
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [filters, rollingStocks]);
 
+  useEffect(() => {
+    if (mustResetFilters) {
+      resetFilters();
+      if (setMustResetFilters) setMustResetFilters(false);
```
Comment (Math-R) [inline front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: you can test this function in addition with mustResetFilters in the condition above and just call it here

Comment (Yohh) [reply front/src/modules/rollingStock/components/RollingStockSelector/SearchRollingStock.tsx]: done

**Review by Math-R — APPROVED** [review]
