### PR TITLE
core: sim: ignore missing first chunk in routes

### LINKED ISSUE #9336: core: simulation fails with Unreachable (couldn't find first chunk in route list)
### What happened?

When using [this train schedule](https://github.com/user-attachments/files/17366792/train_schedules.17.json)

We get this in the core logs
```
java.lang.RuntimeException: Unreachable (couldn't find first chunk in route list)
        at fr.sncf.osrd.standalone_sim.SafetySpeedKt.getRoutePathStartOffset(SafetySpeed.kt:99)
        at fr.sncf.osrd.standalone_sim.SafetySpeedKt.makeSafetySpeedRanges(SafetySpeed.kt:31)
        at fr.sncf.osrd.standalone_sim.StandaloneSimulationKt.runStandaloneSimulation(StandaloneSimulation.kt:66)
        at fr.sncf.osrd.api.api_v2.standalone_sim.SimulationEndpoint.act(SimulationEndpoint.kt:56)
        at fr.sncf.osrd.cli.WorkerCommand.run$lambda$3(WorkerCommand.kt:184)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery(AutorecoveringChannel.java:642)
        at io.opentelemetry.javaagent.instrumentation.rabbitmq.TracedDelegatingConsumer.handleDelivery(TracedDelegatingConsumer.java:76)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

And editoast returns a shy 
```json
{"16317":{"status":"simulation_failed","error_type":"core:unknown_error"}}
```
in simulation_summary.

### What did you expect to happen?

I expect no `Unreachable` errors in core.

I also expect a clearer error in editoast...

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario on France infra
2. Import the train schedule in the description
3. Witness

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c0919fa

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/9336

### CODE REVIEW

File: core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/impl/PathPropertiesImpl.kt [hunk 1]
```diff
@@ -17,8 +17,23 @@ import fr.sncf.osrd.utils.units.meters
  * offset on the first chunk, and endOffset on the last chunk. *
  */
 data class ChunkPath(
+    /**
+     * Ordered list of chunks on the path. Chunks that are fully outside the path are trimmed. Note:
+     * when the path starts or end precisely at the border between two chunks, the extra bordering
```
Comment (Erashin) [inline core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/impl/PathPropertiesImpl.kt]:
```suggestion
     * when the path starts or ends precisely at the border between two chunks, the extra bordering
```

File: core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/impl/PathPropertiesImpl.kt [hunk 2]
```diff
@@ -17,8 +17,23 @@ import fr.sncf.osrd.utils.units.meters
...
+     * chunks are included. But code that use this class should ideally work with either version.
```
Comment (Erashin) [inline core/kt-osrd-sim-infra/src/main/kotlin/fr/sncf/osrd/sim_infra/impl/PathPropertiesImpl.kt]:
```suggestion
     * chunks are included. But code that uses this class should ideally work with either version.
```

File: core/src/main/java/fr/sncf/osrd/standalone_sim/SafetySpeed.kt [hunk 3]
```diff
@@ -126,8 +126,18 @@ fun getRoutePathStartOffset(
 ): Offset<Path> {
     var prevChunksLength = Offset<Path>(0.meters)
     val routeChunks = zonePaths.flatMap { infra.getZonePathChunks(it) }
+
+    var firstChunk = chunkPath.chunks[0]
+    var firstChunkLength = infra.getTrackChunkLength(firstChunk.value)
+    if (firstChunkLength == chunkPath.beginOffset && chunkPath.chunks.size > 1) {
+        // If the path start precisely at the end of the first chunk, it may not be present in the
```
Comment (Erashin) [inline core/src/main/java/fr/sncf/osrd/standalone_sim/SafetySpeed.kt]:
```suggestion
        // If the path starts precisely at the end of the first chunk, it may not be present in the
```

**Review by Erashin — APPROVED** [review]
Typo nitpicks. The comments clarify the chunk path and how it should be used, so we'll be able to fix this kind of bug more easily in the future. Gj.
