### PR TITLE
front: fix hovering curves in rollingstock editor

### LINKED ISSUE #5512: Hovering "Unspecified" curve won't show it precisely on the graph
### What happened?

Hoveing `B` leads to this:
image

But hovering `Unspecified` leads to this:
image

### What did you expect to happen?

Hovering Unspecified should only highligh the corresponding curve.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to rs editor and try to hover the different electrical profiles

### What operating system, browser and environment are you using?

dev

### OSRD version (top right corner `Account` button > `Informations`)

a3d8d99c

### PR DESCRIPTION
**Pull request by RomainValls**
closes #5512

### CODE REVIEW

File: front/src/common/SelectorSNCF.tsx [hunk 1]
```diff
@@ -80,7 +80,8 @@ export default function SelectorSNCF<
                     if (onItemSelected) onItemSelected(item);
                   }}
                   onMouseOver={() => {
-                    if (onItemHovered) onItemHovered(item);
+                    const hoverValue = item === null ? 'Unspecified' : item;
+                    if (onItemHovered) onItemHovered(hoverValue);
```
Comment (Akctarus) [inline front/src/common/SelectorSNCF.tsx:84]:
```suggestion
                  return onItemHovered && onItemHovered(hoverValue);
```

Comment (Akctarus) [reply front/src/common/SelectorSNCF.tsx:84]: You can use a ternary statement instead of the "if", and to go a step further, you can even replace the "if" above and below with ternaries too

**Review by Akctarus — COMMENTED** [review]
Tested, just left one comment :)

File: front/src/common/SelectorSNCF.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/SelectorSNCF.tsx:84]: Hum for this, we should not add a return, because here we declare the function which is executed on mouse over :) It's fine like this for me

**Review by clarani — APPROVED** [review]
LGTM and tested :white_check_mark: Nice job !

**Review by Akctarus — APPROVED** [review]
