### PR TITLE
Fix core status tracking

### LINKED ISSUE #13058: The worker core appears ready even though it has not finished loading the timetable.
### What happened?

On the stdcm page we can sometimes see the "Get the simulation" blue button available even if the timetable is not finished to be loaded.

The request to `/worker_load` returns `READY` so the issue comes from here.

### What did you expect to happen?

The endpoint should only return READY when the timetable is cached.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open stdcm page
2. Wait for the infra to be loaded
3. Kill core
4. Refresh the page and see that the endpoints return `READY` even if the new container is still loading

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9486361

### PR DESCRIPTION
**Pull request by Khoyo**
Fixes #13058

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/api/StatusEndpoint.kt [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+class StatusEndpoint : Take {
+    override fun act(req: Request?): Response {
+        val response = HashMap<String?, String?>()
+        response["ready"] = "true"
+        return RsJson(RsWithBody(adapter.toJson(response)))
+    }
+
+    companion object {
+        private val adapter: JsonAdapter<MutableMap<String?, String?>?>
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/api/StatusEndpoint.kt]: Nit: do we need all this nullability? It almost looks like java -> kt conversion artifacts

**Review by eckter — APPROVED** [review]
Is there an issue somewhere to keep track of the context?

Either way, LGTM for core, I haven't checked the rest.

File: core/src/main/java/fr/sncf/osrd/api/StatusEndpoint.kt (hunk 1 above)
Comment (Khoyo) [reply core/src/main/java/fr/sncf/osrd/api/StatusEndpoint.kt]: > It almost looks like java -> kt conversion artifacts

It is, nice catch :p

**Comment by Khoyo** [comment]
The issue is #13058

File: editoast/core_client/src/lib.rs [hunk 2]
```diff
@@ -150,6 +161,16 @@ where
...
+    /// Should this request avoid starting a new worker if none is running?
+    fn no_worker_load(&self) -> bool {
+        false
+    }
+
+    /// Returns the timeout override for this request, if any.
+    fn override_timeout(&self) -> Option<Duration> {
+        None
+    }
+
```
Comment (leovalais) [inline editoast/core_client/src/lib.rs]: nit: associated constants maybe?

File: editoast/core_client/src/status.rs [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+#[derive(Debug, Serialize)]
+pub struct StatusRequest {
+    pub infra: i64,
+    pub timetable: Option<i64>,
+}
+
+impl AsCoreRequest<()> for StatusRequest {
+    const URL_PATH: &'static str = "/status";
+
+    fn worker_id(&self) -> Option<String> {
```
Comment (leovalais) [inline editoast/core_client/src/status.rs]: For later: maybe `enum core_client::WorkerKey` instead of `Option<String>`?

File: editoast/src/views/worker_load.rs [hunk 4]
```diff
@@ -124,15 +126,21 @@ pub(in crate::views) async fn worker_load(
...
-        None => infra_id.to_string(),
+    let status = StatusRequest {
+        infra: infra.id,
+        timetable: timetable_id,
+    }
+    .fetch(core_client.as_ref())
+    .await;
+
+    let status = match status {
+        Ok(_) => WorkerStatus::Ready,
```
Comment (leovalais) [inline editoast/src/views/worker_load.rs]:
```suggestion
        Ok(()) => WorkerStatus::Ready,
```

**Review by leovalais — APPROVED** [review]
LGTM

**Review by flomonster — CHANGES_REQUESTED** [review]
Thanks for this PR. I have not tried it yet, but I think it does not work as expected.

How each element behaves (If I have understood the PR code correctly):
- The status endpoint (core side) returns "ready" and is ack only once the core is ready (infra + cache loaded). 
- Status messages have a timeout set to 10s.
- When the status is not ready, we send another message to load the worker.
- "load_worker" messages are ack only when the core is ready.

How the system behaves (given the previous elements):
- Opening the STDCM page (for the first time) will load a worker only 10seconds after the page is opened -> It's a bit of a waste to lose 10 seconds for ‘nothing’.
- Each `worker_load` editoast endpoint call will take 10s, which is weird from an API user point of view.
- Calling multiple time the `worker_load` endpoint while the worker is loading will accumulate `worker_load` messages in the queue, which might trigger the scale of another worker. Since the frontend is polling the status, it will probably happen.

-----

I don't know how to fix these issues easily:
- Reducing the timeout is problematic when there are many messages in the queue and core is up.
- We must differentiate between when a worker is loading and when there are no workers at all. To call loading only in the second case.

**Comment by Khoyo** [comment]
> Calling multiple time the worker_load endpoint while the worker is loading will accumulate worker_load messages in the queue

The [ttl of the messages](https://www.rabbitmq.com/docs/ttl#per-message-ttl-in-publishers) on the queue is directly linked to the timeout of the messages in editoast

> Opening the STDCM page (for the first time) will load a worker only 10seconds after the page is opened -> It's a bit of a waste to lose 10 seconds for ‘nothing’.

We could call worker load eagerly. If a core worker core is up, and has the correct infra version it would be a no-op. We could also reduce the worker load ttl, or even remove the status endpoint entirely if we never want to know the status of core without loading an infra/timetable

Note that that might be even better, currently the status endpoint doesn't use the infra_version.

> Each worker_load editoast endpoint call will take 10s, which is weird from an API user point of view.

Yeah, that's not ideal, but that the tradeoff of making an actual status check vs trying to track the status. Note that they only take 10s if core isn't responding, otherwise they stay fast.

**Comment by flomonster** [comment]
Discussion conclusion:
- Merge worker_load and status messages
- Remove `osrdyne_client`
- Remove `x-osrdyne-no-start`
- Reduce timeout to 1s

**Review by flomonster — APPROVED** [review]
LGTM ! Thanks for this fix.
