### PR TITLE
core: new exception system

### LINKED ISSUE #557: Add a standardized error system through the api
Any assert or exception result in a 500 despite many being caused by invalid user inputs. We need to find a way to filter those

### PR DESCRIPTION
**Pull request by eckter**
https://github.com/DGEXSolutions/osrd/issues/557

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/OSRDException.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    public final ErrorCause cause;
+
+    public enum ErrorCause {
+        INTERNAL,
+        USER
+    }
+
+    // Placing these fields in the child classes can cause class loading deadlocks
+    protected static final String marecoConvergenceExceptionCode = "core:standalone_sim:mareco_convergence";
+    protected static final String invalidInfraExceptionCode = "core:infra:invalid_infra";
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/OSRDException.java]: wtf

File: front/src/applications/osrd/views/OSRDSimulation/Allowances.js [hunk 2]
```diff
@@ -296,10 +296,11 @@ export default function Allowances(props) {
       }));
       setIsUpdating(false);
     } catch (e) {
+      setIsUpdating(false);
       console.log('ERROR', e);
       dispatch(setFailure({
         name: e.name,
-        message: e.message,
+        message: e.request.responseText,
```
Comment (eckter) [inline front/src/applications/osrd/views/OSRDSimulation/Allowances.js]: This displays all the relevant information in the error box, but it's poorly formatted. Maybe someone more comfortable with JS could eventually improve this

File: core/src/main/java/fr/sncf/osrd/api/InfraManager.java [hunk 3]
```diff
@@ -25,7 +25,7 @@ public void forEach(BiConsumer<String, InfraCacheEntry> action) {
         infraCache.forEach(action);
     }
 
-    public static final class InfraLoadException extends Exception {
+    public static final class InfraLoadException extends RuntimeException {
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/InfraManager.java]: Why doesn't it extend OSRDException?

File: core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java [hunk 4]
```diff
@@ -221,8 +215,7 @@ public Response act(Request req) throws IOException {
             }
             return new RsJson(new RsWithBody(adapterResult.toJson(res)));
         } catch (Throwable ex) {
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java:216]: you can add multiple catch clauses, one for OSRDException, and one catch-all for RuntimeException. this alleviates the need for an auxiliary function

File: core/src/main/java/fr/sncf/osrd/OSRDException.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+        USER
+    }
+
+    protected OSRDException(String message, ErrorCause cause) {
+        this.message = message;
+        this.cause = cause;
+    }
+
+    public static final JsonAdapter<OSRDException> adapter =
+            Reflection.makeJsonAdapterFromSubtypes(OSRDException.class, "type");
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/OSRDException.java]: I don't see the hierarchical error type identifier as discussed in https://github.com/DGEXSolutions/osrd/issues/557#issuecomment-1044311471
my understanding is that the class name is used as the error type identifier, which does not sound like a good idea, as this makes name clashes easier, and renaming the class has direct effect on the public API

File: core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java [hunk 6]
```diff
@@ -67,8 +66,7 @@ public Response act(Request req) throws
             InvalidRollingStock,
             InvalidSchedule,
             InvalidSuccession,
-            SimulationError,
-            InvalidInfraException {
+            SimulationError {
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java]: why aren't all these removed? aren't these unchecked OSRDExceptions now?

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java [hunk 7]
```diff
@@ -33,19 +34,22 @@
     // potential speed limit under which the train would use too much capacity
     public final double capacitySpeedLimit;
 
+    public final int allowanceIndex;
+
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java]: that's a bad idea, as it only makes sense in the context of applying multiple allowances, and is only used for the specific purpose of error reporting.

Instead, I believe location metadata should instead be once errors are thrown. OSRDException would be to have a "source" field to OSRDException, which would be an array of location metadata.

This has the benefit of:
 - not having to pass around an arbitrary amount of context information
 - make this kind of enriched error reporting work regardless of the kind of exception thrown

For example:
```java
for (int i = 0; i < allowances.length; i++) {
    try {
        result = allowances[i].apply(result);
    } catch (OSRDException ex) {
        ex.source.addFirst(String.of(i));
        ex.source.addFirst("allowances");
    }
}
```

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java [hunk 8]
```diff
@@ -498,19 +502,17 @@ private Envelope binarySearchLoop(DoubleBinarySearch search,
             search.feedback(output);
         }
         if (!search.complete())
-            throw makeMarecoError(search);
+            throwMarecoError(search);
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java]: you could return the exception as was done previously

**Review by multun — CHANGES_REQUESTED** [review]

File: core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java (hunk 4 above)
Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java:216]: The idea was to factorize how we handle exceptions, it's the same in all endpoints. It makes it easier if someday we want to change how we log or generally handle errors

File: core/src/main/java/fr/sncf/osrd/OSRDException.java (hunk 5 above)
Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/OSRDException.java]: True, but then the alternative is what made you go "wtf". I assumed this was what you had in mind

File: core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java (hunk 6 above)
Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java]: I'll remove these once the api is finalized and maybe in a different PR, it will add a huge amount of clutter to the diff

File: core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java [hunk 9]
```diff
@@ -92,13 +91,7 @@ public Response act(Request req) throws IOException {
...
 
             // load infra
-            Infra infra;
-            try {
-                infra = infraManager.load(request.infra);
-            } catch (InfraLoadException | InterruptedException e) {
-                return new RsWithStatus(new RsText(
-                        String.format("Error loading infrastructure '%s'%n%s", request.infra, e.getMessage())), 400);
-            }
+            Infra infra = infraManager.load(request.infra);
```
Comment (flomonster) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingRoutesEndpoint.java]:
```suggestion
            var infra = infraManager.load(request.infra);
```

File: core/src/main/java/fr/sncf/osrd/api/PathfindingTracksEndpoint.java [hunk 10]
```diff
@@ -47,13 +46,7 @@ public Response act(Request req) throws IOException {
...
 
             // load infra
-            Infra infra;
-            try {
-                infra = infraManager.load(request.infra);
-            } catch (InfraLoadException | InterruptedException e) {
-                return new RsWithStatus(new RsText(
-                        String.format("Error loading infrastructure '%s'%n%s", request.infra, e.getMessage())), 400);
-            }
+            Infra infra = infraManager.load(request.infra);
```
Comment (flomonster) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingTracksEndpoint.java]:
```suggestion
            var infra = infraManager.load(request.infra);
```

File: core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java [hunk 11]
```diff
@@ -73,13 +74,7 @@ public Response act(Request req) throws
...
 
             // load infra
-            Infra infra;
-            try {
-                infra = infraManager.load(request.infra);
-            } catch (InfraLoadException | InterruptedException e) {
-                return new RsWithStatus(new RsText(
-                        String.format("Error loading infrastructure '%s'%n%s", request.infra, e.getMessage())), 400);
-            }
+            Infra infra = infraManager.load(request.infra);
```
Comment (flomonster) [inline core/src/main/java/fr/sncf/osrd/api/StandaloneSimulationEndpoint.java]:
```suggestion
            var infra = infraManager.load(request.infra);
```

File: core/src/main/java/fr/sncf/osrd/exceptions/OSRDError.java [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+ *     throw e.withContext(new ErrorContext.Train(train.id));
+ * }
+ * }
+ * </pre>
+ */
+public abstract class OSRDError extends RuntimeException {
+
+    private static final long serialVersionUID = 1197516372515951853L;
+
+    public static final String osrdErrorType = "osrd";
```
Comment (flomonster) [inline core/src/main/java/fr/sncf/osrd/exceptions/OSRDError.java]: Should it be `core`?

**Review by flomonster — DISMISSED** [review]
Awesome!

**Review by flomonster — APPROVED** [review]
