### PR TITLE
front: fix timestops output using wrong simulation

### LINKED ISSUE #8280: Output table not always displaying final_output schedules
### What happened?

In the simulation results, the output table is synchronized with the simulation used in the driver trainSchedule but it shouldn't.

### What did you expect to happen?

Output table should always use the final_output simulation

### How can we reproduce it (as minimally and precisely as possible)?

Go to a scenario and add train with margins

### On which environments the bug occurs?

Dev (DgexSol)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev 1ab7fa8

### PR DESCRIPTION
**Pull request by SharglutDev**
close #8280 

- fix the bug
- optimize the switch in driver trainSchedule so it doesn't call the endpoint each time we switch (resulting with a small loading)

### CODE REVIEW

File: front/src/modules/trainschedule/components/DriverTrainScheduleV2/utils.ts [hunk 1]
```diff
@@ -214,21 +220,42 @@ export const formatOperationalPoints = async (
...
+    let finalOutputTime = 0;
+    let finalOutputSpeed = 0;
+    // Get time
+    if (matchingFinalOutPutReportTrainIndex !== -1) {
+      finalOutputTime = final_output.times[matchingFinalOutPutReportTrainIndex];
+      finalOutputSpeed = final_output.speeds[matchingFinalOutPutReportTrainIndex];
+    } else {
+      finalOutputTime = interpolateValue(final_output, op.position, 'times');
+      finalOutputSpeed = interpolateValue(final_output, op.position, 'speeds');
     }
```
Comment (kmer2016) [inline front/src/modules/trainschedule/components/DriverTrainScheduleV2/utils.ts]: Since we applied the same operation to both base and finalOutput, we should consider extracting this logic into a function and applying it to both variables. What do you think?

**Review by kmer2016 — APPROVED** [review]
LGTM

File: front/src/modules/trainschedule/components/DriverTrainScheduleV2/utils.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/DriverTrainScheduleV2/utils.ts]: Done
