### PR TITLE
front: fix wrong origin via position on path

### LINKED ISSUE #7618: TSv2: the path doesn't start at the origin ask
### What happened?

When pathfinding is requested with the rocket button, the path found does not begin with the orignin requested.
Screenshot from 2024-06-05 14-12-59

Also when adding a new via with the suggested via modal, it's not placed on the good track on the path.

Capture d’écran 2024-06-06 à 09 05 51

### What did you expect to happen?

The origin and vias of the path displayed on map must be the one requested

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to route tab
2. Search a pathfinding with rocket button (ex: PNO AS)
3. Zoom in on "Paris Nord"

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Nixos
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

local

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7618 

This PR : 
- fix the related bugs
- add kp property to the store's pathsteps to have one property allowing to distinguish them when they have same uic and ch codes. This enables the vias added by clicking on map to be properly displayed as vias on the modal suggested vias.

### CODE REVIEW

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx [hunk 1]
```diff
@@ -300,19 +300,35 @@ const Pathfinding = ({ pathProperties, setPathProperties }: PathfindingProps) =>
...
+                    'uic' in step &&
+                    suggestedOp.uic === step.uic &&
+                    suggestedOp.ch === step.ch &&
+                    suggestedOp.kp === step.kp
+                );
+
+                return correspondingOp
+                  ? {
+                      ...step,
+                      kp: correspondingOp.kp,
```
Comment (emersion) [inline front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:319]: This one shouldn't be necessary since we check `suggestedOp.kp === step.kp` above I think? (Alternatively, drop the `kp` check above for consistency with `TypeAndPathV2`? I suppose the question here is whether or not two OPs which are technically "the same" also always have the same `kp`?)

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx [hunk 2]
```diff
@@ -300,19 +300,35 @@ const Pathfinding = ({ pathProperties, setPathProperties }: PathfindingProps) =>
...
                 geometry,
                 pathfindingResult.length
               );
 
-              const allVias = upsertViasInOPs(suggestedOperationalPoints, pathStepsWihPosition);
+              // We update existing pathsteps with coordinates, positionOnPath and kp corresponding to the new pathfinding result
+              const updatedPathSteps: PathStep[] = compact(pathSteps).map((step, i) => {
+                const correspondingOp = suggestedOperationalPoints.find(
+                  (suggestedOp) =>
+                    step &&
```
Comment (emersion) [inline front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]: Not sure this one is 100% necessary, can a null `step` ever happen?

**Review by emersion — COMMENTED** [review]
Overall looks good to me, just 2 minor questions. Please note, I am not familiar with this code!

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]: No you're right, as I now compact pathsteps first, the null steps are removed. I'll fix it.

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:319]: I'm not sure why a user would use 2 operational points with same uic and ch but with different kps (it can happen because of imports inconsistencies) but I think we need to keep the condition. 
Maybe we should keep the kp l.323 in case the kp changed between two pathfinding calculation but remove the `suggestedOp.kp === step.kp`, what do you think ?

**Review by emersion — DISMISSED** [review]

**Review by Math-R — DISMISSED** [review]
lgtm ! 😊

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:319]: I removed the filter with `suggestedOp.kp === step.kp` but kept the `kp: correspondingOp.kp,` in case the kp has changed between the recalculation of the pathfinding

Comment (emersion) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:319]: > I'm not sure why a user would use 2 operational points with same uic and ch but with different kps (it can happen because of imports inconsistencies) but I think we need to keep the condition.

If the DB has the "Gare de Lyon" operational point on two tracks, each track will get its own OP sharing the same uic and ch right? In that case the kp may be different for each track's OP. It seems like filtering on kp would be incorrect.

> Maybe we should keep the kp l.323 in case the kp changed between two pathfinding calculation but remove the suggestedOp.kp === step.kp, what do you think ?

I think that would be more consistent with the logic in `TypeAndPathV2`.

Comment (emersion) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:319]: The last commit drops the kp filtering, so looks good!

**Comment by emersion** [comment]
One last question: should we also update the `metadata` field, which contains the `trackName` and `trackNumber`? To accomodate for the case where the pathfinding returns an OP on a different track?

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx [hunk 3]
```diff
@@ -300,19 +300,31 @@ const Pathfinding = ({ pathProperties, setPathProperties }: PathfindingProps) =>
...
-              dispatch(updatePathSteps(pathStepsWihPosition));
-
               const suggestedOperationalPoints: SuggestedOP[] = formatSuggestedOperationalPoints(
                 operational_points,
                 geometry,
                 pathfindingResult.length
               );
 
-              const allVias = upsertViasInOPs(suggestedOperationalPoints, pathStepsWihPosition);
+              // We update existing pathsteps with coordinates, positionOnPath and kp corresponding to the new pathfinding result
```
Comment (emersion) [inline front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:309]: Nit: this comment is outdated, should drop the mention about kp

**Comment by emersion** [comment]
> One last question: should we also update the metadata field, which contains the trackName and trackNumber? To accomodate for the case where the pathfinding returns an OP on a different track?

`metadata` is a TSv1-only thing, so we don't need to care about it in TSv2.

**Review by emersion — APPROVED** [review]
Looks good once again!

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 3 above)
Comment (emersion) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx:309]: Nevermind, this is up-to-date! Got things mixed up.

**Review by Math-R — APPROVED** [review]
