### PR TITLE
core: stdcm: fix priority between stop and departure delay

### LINKED ISSUE #9508: core: stdcm sometimes fails to find a path for no apparent reason
### What happened?

Sometimes, the stdcm search ends almost instantly with no solution found. The response is the "conflict" by default, but there's actually no conflict. Meaning that there was an easy solution available. 

### What did you expect to happen?

A "conflict" response without any conflict doesn't make any sense

### How can we reproduce it (as minimally and precisely as possible)?

I have payloads that reproduce but it's an infra + a schedule + timetables + stdcm request, it's a mess

### On which environments the bug occurs?

Local, dev

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

508ac321f2791dcbb8ca6dfdbee03b4a51261635

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/9508

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/TimeData.kt [hunk 1]
```diff
@@ -27,6 +29,7 @@ data class TimeData(
      * stop has been reached yet.
      */
     val maxDepartureDelayingWithoutConflict: Double,
+    val maxFirstDepartureDelaying: Double,
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/TimeData.kt:39]: Might be worth adding a comment for this value here, just in case people get confused.

**Review by Erashin — COMMENTED** [review]
Unit tests looking good as well.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/TimeData.kt (hunk 1 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/TimeData.kt:39]: I've added a comment there.

I'll probably rename variables and rewrite comments in this class, it's a bit messy. But I'd do it in a PR that has no functional change.

**Review by Erashin — APPROVED** [review]
