### PR TITLE
front: fix added exception with rs change group not displayed

### LINKED ISSUE #12164: Added exception with a different rs not displayed on timetable
### What happened?

When adding an added exception and then modifying its rs so its not the same as its paced train, the exception is no longer displayed in the timetable.

### What did you expect to happen?

The exception should be displayed even when its rs is different thant its paced train

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add a paced train with one added exception
3. Modify the rs of this exception
4. It should no longer be displayed in the timetable

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by SharglutDev**
- Fix the rolling stock image not displayed for added exceptions.
- Use the rolling stock list from the scenario in `useOccurrences` to do the matching instead of an api call
- Remove the rs api call for indexed occurrences in favor of this new list
- Rename `useOccurrences` with .ts extension since it doesn't return any JSX

fix #12164

### CODE REVIEW

**Comment by emersion** [comment]
Ow, doing HTTP requests in a loop like this for each occurrence is not great, and the rtk-query cache isn't used since queries aren't subscribed so each update might cause new HTTP requests to be sent…

We have a list of rolling stocks at hand in the timetable, could we drop all of the async stuff and use that instead?

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx [hunk 1]
```diff
@@ -109,17 +112,13 @@ const useOccurrences = (pacedTrain: PacedTrainWithDetails) => {
...
 
         let occurrenceRollingStock = rollingStock;
-        if (exception.rolling_stock) {
-          const promisedRollingStock = getRollingStockByName({
-            rollingStockName: exception.rolling_stock.rolling_stock_name,
-          });
-          occurrenceRollingStock = await promisedRollingStock.unwrap();
-          // we don't want to subscribe to the endpoint to prevent unnecessary calls
-          promisedRollingStock.unsubscribe();
+        if (exception.rolling_stock && rollingStockList) {
```
Comment (emersion) [inline front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx]: This is inside a `useEffect()`, so I think we need to add this to the dependencies list?

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx [hunk 2]
```diff
@@ -66,13 +63,9 @@ const useOccurrences = (
         const correspondingException = findExceptionWithOccurrenceId(exceptions, occurrenceId);
 
         let occurrenceRollingStock = rollingStock;
-        if (correspondingException?.rolling_stock) {
-          const promisedRollingStock = getRollingStockByName({
-            rollingStockName: correspondingException.rolling_stock.rolling_stock_name,
-          });
-          occurrenceRollingStock = await promisedRollingStock.unwrap();
```
Comment (emersion) [inline front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx:70]: With this change, we no longer need this to be a `useEffect()`, we can turn it back into a `useMemo()`. Do you want to keep this for a follow-up PR, or do you want to do it in this PR?

Comment (SharglutDev) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx:70]: Oh yes, you're right ! Forgot I was the one who added it for this rolling stock fetching. I'll add a commit.

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrences.tsx]: Good catch. Done

**Review by emersion — APPROVED** [review]
LGTM!

Reading this PR commit by commit was very comfortable, thanks for taking the time to do this!

**Comment by SharglutDev** [comment]
> LGTM!
> 
> Reading this PR commit by commit was very comfortable, thanks for taking the time to do this!

Learned from the best 😎
