### PR TITLE
front: fix track_name on timetable for imported train

### LINKED ISSUE #13766: Track_name not always displayed in timetable
### What happened?

When a train_schedule is imported whith a track only identified by track_id, its name is not displayed on the corresponding timetable.

### What did you expect to happen?

We expect the corresponding track_name to be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

Import the file.

[timetable.json](https://github.com/user-attachments/files/23049196/timetable.7.json)

Look at the timetable of the train "Missing track name"

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by aschantraine**
Updates the `getTrackReferenceLabel` function to accept `trackSections` and use the SNCF extension's `track_name` instead of the track ID when available, falling back to "?" otherwise.

### CODE REVIEW

File: front/src/modules/timesStops/hooks/useOutputTableData.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ const useOutputTableData = (
           const trackName =
             'track' in pathStep
               ? trackSections[pathStep.track]?.extensions?.sncf?.track_name
-              : getTrackReferenceLabel(pathStep.track_reference);
+              : getTrackReferenceLabel(trackSections, pathStep.track_reference);
```
Comment (emersion) [inline front/src/modules/timesStops/hooks/useOutputTableData.ts]: Unfortunately I don't think `trackSections` will contain the tracks we're interested in here: `trackIds` above is collected from track-offset path steps. For instance, the following path item:

```json
{
  "track": "foobar",
  "offset": 42
}
```

will result in an entry in `trackSections`, but that one won't:

```json
{
  "uic": 874242,
  "secondary_code": "BV",
  "track_reference": { "track_name": "V2" }
}
```

**Comment by emersion** [comment]
CC'ing @Synar since she's worked on tracks in the output table.

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts]: I believe you are correct, but could we just change that? 

In 
```
const trackIds = train.path.reduce<string[]>((ids, step) => {
        if ('track' in step) ids.push(step.track);
        return ids;
      }, []);
``` 
      
beneath the first push we could add something like `if ('track_reference' in step && 'track_id' in step.track_reference) ids.push(step.track_reference.track_id);`
      
This approach feels slightly clunky, but I think it should work.

**Review by emersion — APPROVED** [review]
Nice!

File: front/src/modules/timesStops/hooks/useOutputTableData.ts [hunk 2]
```diff
@@ -38,7 +38,12 @@ const useOutputTableData = (
 
   const trackIds = useMemo(() => {
     const path = selectedTrain?.path || [];
-    const trackIdsInPathSteps = path.flatMap((step) => ('track' in step ? [step.track] : []));
+    const trackIdsInPathSteps = path.flatMap((step) => [
+      ...('track' in step ? [step.track] : []),
+      ...('track_reference' in step && step.track_reference && 'track_id' in step.track_reference
```
Comment (Synar) [inline front/src/modules/timesStops/hooks/useOutputTableData.ts:44]: Since @emersion 's pr, I don't think adding the trackreferences is needed anymore, since we add the ops' track ids to the id list right after, and we should have an op for each step with a track reference.

The one case where this wouldn't be true would be if the track id was valid but not the rest of the step, I suppose.

I'm not sure we really need to handle that case, but it's not really an issue either, since we deduplicate ids before fetching anyway.

So as you prefer!

**Review by Synar — APPROVED** [review]
Good job!

File: front/src/modules/timesStops/hooks/useOutputTableData.ts (hunk 2 above)
Comment (aschantraine) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts:44]: Right after, we only add the track ids of ops in the pathfinding so we need this to cover the specific case of an invalid train without pathfinding but with tracks provided through track_references in the input.

Comment (Synar) [reply front/src/modules/timesStops/hooks/useOutputTableData.ts:44]: Good point, I think you're right!

File: front/src/modules/timesStops/helpers/utils.ts [hunk 3]
```diff
@@ -368,9 +369,15 @@ export const matchOpRefAndOp = (op: OperationalPoint, opRef: PathItemLocation):
...
-export const getTrackReferenceLabel = (trackReference?: TrackReference | null) => {
+export const getTrackReferenceLabel = (
+  trackSections: Record<string, TrackSection>,
+  trackReference?: TrackReference | null
+) => {
   if (!trackReference) return undefined;
-  return 'track_id' in trackReference ? trackReference.track_id : trackReference.track_name;
+  if ('track_name' in trackReference) return trackReference.track_name;
+  return (
+    trackSections[trackReference.track_id]?.extensions?.sncf?.track_name ?? trackReference.track_id
```
Comment (SharglutDev) [inline front/src/modules/timesStops/helpers/utils.ts]: I wonder if we should also align the behavior here to display "Track identifier" instead of the track id if no match was found. What do you think @maelysLeratRosso ?

But it is not related to this PR it can be done later if you want.

Comment (maelysLeratRosso) [reply front/src/modules/timesStops/helpers/utils.ts]: Hi :) 
Where would it be displayed here ?

Comment (SharglutDev) [reply front/src/modules/timesStops/helpers/utils.ts]: In the output table, on the track column

Comment (SharglutDev) [reply front/src/modules/timesStops/helpers/utils.ts]: We didn't see any case like that until now since there is no possibility to put a `track_id` in a `track_reference` path step input in the UI. Would happen only if the user provided a `track_id` not existing in the infrastructure in a json (so pretty unlikely like the other places where we handle that case).

Comment (maelysLeratRosso) [reply front/src/modules/timesStops/helpers/utils.ts]: Ok ! Then maybe "Track identifier" would be too long compared to the width of the track column ? I see two options : 
- either we put it in the CI column and leave the track column empty in that case
- or we put something shorter in the track column ? Like "?" ? 

Maybe the 1st one is better, what do you think ?

Comment (SharglutDev) [reply front/src/modules/timesStops/helpers/utils.ts]: Currently the CI column is already too short to display most of the whole op names so I'm not sure addind `Track Identifier` at the end would help.

I would vote either for `?` or `Track Identifier` with an ellipsis `Track ...` with a `title` attribute making it possible to see the whole thing on hover.

Comment (maelysLeratRosso) [reply front/src/modules/timesStops/helpers/utils.ts]: Works for me :) Anyway it won't happen very often as you said, and the table will change soon !

Comment (SharglutDev) [reply front/src/modules/timesStops/helpers/utils.ts]: Yes, as I said before @aschantraine, this is already the current behavior so totally optional to fix this behavior on this PR 🙂 Feel free to close the comment and merge the PR if you want.

File: front/src/modules/timesStops/helpers/utils.ts [hunk 4]
```diff
@@ -358,9 +358,7 @@ export const getTrackReferenceLabel = (
 ) => {
   if (!trackReference) return undefined;
   if ('track_name' in trackReference) return trackReference.track_name;
-  return (
-    trackSections[trackReference.track_id]?.extensions?.sncf?.track_name ?? trackReference.track_id
-  );
+  return trackSections[trackReference.track_id]?.extensions?.sncf?.track_name ?? '?';
```
Comment (emersion) [inline front/src/modules/timesStops/helpers/utils.ts:361]: Nit: in general I prefer to handle formatting concerns (in other words, how unknown/missing values should be presented to the user) in the JSX template rather than storing it in the `trackName` field.

Hm, that said, we already use `undefined` to mean "unspecified", so we'd need another value to mean "specified but not found". `null` wouldn't be very explicit and would be easy to confuse with `undefined`…

Comment (aschantraine) [reply front/src/modules/timesStops/helpers/utils.ts:361]: So, what do you suggest ?  Since it’s going to change soon, maybe we should keep `track_reference.id` after all ?

Comment (emersion) [reply front/src/modules/timesStops/helpers/utils.ts:361]: To be honest, I'd be fine with whatever, including: the status quo, track IDs, or an explicit marker for unknown tracks. I mainly wanted to emit a minor warning against formatting data too early in the pipeline and hardcoding user-facing text in the data model. Feel free to resolve this comment.
