### PR TITLE
front: fix deletion of empty pathStepItem in ItineraryModal

### LINKED ISSUE #15949: Itinerary modal: empty lines or lines with only one filled OP cannot be deleted
### What happened?

https://github.com/user-attachments/assets/28cbf430-13c9-4391-98d0-2a5847cff375

### What did you expect to happen?

All added lines can be deleted

### How can we reproduce it (as minimally and precisely as possible)?

1. Click on Add a train
2.  Open Itinerary modal
3. Add empty lines
4. Try to delete them
5. Add an OP in one line
6. 4. Try to delete it

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

8b88601

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15949 

reminder for the review: there should always be at least two lines of pathStepItem : the first and the trailing path step. 

edit : we now only want one pathStepItem at the creation of a new itinerary -> we allow the deletion until theres one pathStepItem left

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 1]
```diff
@@ -126,19 +126,19 @@ const ItineraryModal = ({
...
     if (isEmptyStep(step, getInputForStep(step.id))) return false;
     const meta = pathStepsMetadataById.get(step.id);
     return !meta || meta.isInvalid;
   });
-
   const handleDeletePathStep = (stepId: string) => {
     resetOpSuggestions();
 
     if (activeStepId === stepId) setActiveStepId('');
+    if (pathSteps.length === 2) return;
```
Comment (SarahBellaha) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]:
```suggestion
```
You don't need this early return. You only call this function when `hasSingleStepWithTrailing` is `false`, meaning you'll have at least 3 `pathSteps`.

Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: good catch thanks ! fixed in last fixup 👍

**Review by SarahBellaha — APPROVED** [review]
Lgtm
