### PR TITLE
editoast: fix projection endpoint

### LINKED ISSUE #9534: Path projection endpoint fails
### What happened?

Path projection fails with specific train schedules.

### What did you expect to happen?

The path projection should be successful.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with this [trains_fails.json](https://github.com/user-attachments/files/17589075/trains_fails.json)
2. Observe the path projection call fail

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

### PR DESCRIPTION
**Pull request by flomonster**
close #9534

We found out that this code was broken since the `trains` variable does not have the same length as `trains_details` and `cached_projections`.

### CODE REVIEW

File: editoast/src/views/train_schedule/projection.rs [hunk 1]
```diff
@@ -277,40 +274,40 @@ async fn project_path(
...
+    let trains_hash_values: HashMap<_, _> = trains_details
         .iter()
-        .map(|t| t.id)
+        .map(|t| t.train_id)
         .zip(trains_hash_values)
         .collect();
     let mut new_items = vec![];
-    for id in miss_cache.keys() {
-        let hash = &trains_hash_values[id];
+    for id in miss_cache.iter().map(|t| t.train_id) {
```
Comment (woshilapin) [inline editoast/src/views/train_schedule/projection.rs]: I'd argue that you might want to actually be explicit about which kind of identifier it is (I'm under the impression that it's actually because of that kind of things that the bug exists in the first place?).

```suggestion
    for train_id in miss_cache.iter().map(|t| t.train_id) {
```

File: editoast/src/views/train_schedule/projection.rs [hunk 2]
```diff
@@ -277,40 +274,40 @@ async fn project_path(
...
-    let mut project_path_result = HashMap::new();
     let rolling_stock_length: HashMap<_, _> = rolling_stocks
         .into_iter()
         .map(|rs| (rs.name, rs.length))
         .collect();
 
     // 4.2 Build the projection response
-    for (id, cached) in hit_cache {
+    let mut project_path_result = HashMap::new();
+    for (cached, id) in hit_cache {
```
Comment (woshilapin) [inline editoast/src/views/train_schedule/projection.rs]: Same here, maybe we can be explicit about which kind of `id`?

File: editoast/src/views/train_schedule/projection.rs [hunk 3]
```diff
@@ -277,40 +274,40 @@ async fn project_path(
     let signal_updates = signal_updates?;
 
     // 3. Store the projection in the cache (using pipeline)
-    let trains_hash_values: HashMap<_, _> = trains
+    let trains_hash_values: HashMap<_, _> = trains_details
         .iter()
-        .map(|t| t.id)
+        .map(|t| t.train_id)
```
Comment (woshilapin) [inline editoast/src/views/train_schedule/projection.rs:279]: Am I correct if I say that, should we use a `TrainId` type instead of a `i64` everywhere we need identifiers, we would not have had this bug? Is this something we want to investigate?

File: editoast/src/views/train_schedule/projection.rs
Comment (woshilapin) [inline editoast/src/views/train_schedule/projection.rs:1]: I'm surprised a bug fix doesn't change any test behavior. We probably should add a test which would fail under the old code, and success with the bug fix.

File: editoast/src/views/train_schedule/projection.rs (hunk 3 above)
Comment (flomonster) [reply editoast/src/views/train_schedule/projection.rs:279]: It's not a type issue, so even with a `TrainId` type, we would have the bug.

File: editoast/src/views/train_schedule/projection.rs (hunk 1 above)
Comment (flomonster) [reply editoast/src/views/train_schedule/projection.rs]: Fixed

File: editoast/src/views/train_schedule.rs [hunk 4]
```diff
@@ -1024,4 +1038,143 @@ mod tests {
...
         app.fetch(request).assert_status(StatusCode::OK);
     }
+
+    #[derive(Deserialize)]
+    struct PartialProjectPathTrainResult {
+        departure_time: DateTime<Utc>,
+        // Ignore the rest of the payload
+    }
+
+    fn mocked_core_for_project_path(train_id: i64) -> MockingClient {
```
Comment (flomonster) [inline editoast/src/views/train_schedule.rs]:
```suggestion
    fn mocked_core_pathfinding_sim_projection(train_id: i64) -> MockingClient {
```

File: editoast/src/views/train_schedule.rs [hunk 5]
```diff
@@ -920,8 +922,7 @@ mod tests {
         )
     }
 
-    async fn app_infra_id_train_schedule_id_for_simulation_tests() -> (TestApp, i64, i64) {
-        let db_pool = DbConnectionPoolV2::for_tests();
+    fn mocked_core_pathfinding_and_sim() -> MockingClient {
```
Comment (flomonster) [inline editoast/src/views/train_schedule.rs]: Remove this function and keep only one `MockedClient`.

**Review by woshilapin — APPROVED** [review]
Thanks for adding the test. The improvements look good.
