### PR TITLE
front: fix import train invalid names v2

### LINKED ISSUE #7637: Importing train with opendata results only with invalid trains
### What happened?

When importing train with open data, the rolling stock names (when there is one) returned by the graou endpoint doesn't match the one with have in the database.
In v1, we used to format them with a dictionnary but it's not done in v2. We should use it as well.

Capture d’écran 2024-06-06 à 12 30 09

### What did you expect to happen?

The imported trainwhich have a rolling stock name should not be invalid.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario trainschedule v2
2. Import trains with opendata and add them to timetable and see all invalid trains

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma 14.5
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 5c6be9e

### PR DESCRIPTION
**Pull request by RomainValls**
closes #7637

### CODE REVIEW

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx [hunk 1]
```diff
@@ -49,6 +49,18 @@ const ImportTrainScheduleTrainsListV2 = ({
     [rollingStocks]
   );
 
+  // Format the trains list to match the train names provided by the backend
+  const formattedTrains = useMemo(
+    () =>
+      trainsList.map((train) => {
```
Comment (Yohh) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: trainList would be better?

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx [hunk 2]
```diff
@@ -49,6 +49,18 @@ const ImportTrainScheduleTrainsListV2 = ({
     [rollingStocks]
   );
 
+  // Format the trains list to match the train names provided by the backend
+  const formattedTrains = useMemo(
```
Comment (Yohh) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: what about formattedTrainList ?

Comment (RomainValls) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: Renamed it to formattedTrainsList

Comment (Yohh) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: nice, just about train**s**list, it seems to me better to have trains OR trainList (list refer to an array), but it's only a proposition (and if you agree with it, same thing with formattedTrainList)

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx [hunk 3]
```diff
@@ -49,6 +49,18 @@ const ImportTrainScheduleTrainsListV2 = ({
...
 
+  // Format the trains list to match the train names provided by the backend
+  const formattedTrainsList = useMemo(
+    () =>
+      trainsList.map((train) => {
+        const validTrainName =
+          rollingstockOpenData2OSRD[train.rollingStock as keyof typeof rollingstockOpenData2OSRD];
+
+        return { ...train, rollingStock: validTrainName };
+      }),
```
Comment (SarahBellaha) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]:
```suggestion
     trainsList.map(({ rollingStock, ...train }) => {
        const validTrainName =
          rollingstockOpenData2OSRD[rollingStock as RollingstockOpenData2OSRDKeys];

        return { ...train, rollingStock: validTrainName };
      }),
```

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx
Comment (SarahBellaha) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx:1]: You can add the type somewhere above l.38 :)
```
type RollingstockOpenData2OSRDKeys = keyof typeof rollingstockOpenData2OSRD;
```
And use it l.125
```
 rollingstockOpenData2OSRD[train.rollingStock as RollingstockOpenData2OSRDKeys]
```

**Review by SarahBellaha — APPROVED** [review]
LGTM, just left some suggestions :)

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx [hunk 4]
```diff
@@ -35,6 +35,8 @@ type ImportTrainScheduleTrainsListProps = {
   trainsJsonData: TrainScheduleBase[];
 };
 
+type RollingstockOpenData2OSRDKeys = keyof typeof rollingstockOpenData2OSRD;
+
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: We have a types.ts file for ImportTrainSchedule, you can move the type inside

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsListV2.tsx]: In most of the app, we have an "s" even with a list const, so I think we should keep it with `trainsList`. But I agree that a list can be empty or have just one item inside so the "s" might not be relevant. It can be discuss in a front meeting (even though it will be painfull to rename all the related consts in the app)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested
