### PR TITLE
front: fix and refactor selected train id init

### LINKED ISSUE #12605: Horizon : Projection is done on the wrong train when the page is refreshed or an url is copied
### What happened?

Context : we have multiple trains on a scenario (train A, train B, etc...), by default the projection is done on the train A (the first train of my list).

I decided to switch the projection from train A to train B.

If I refresh my page, the projection go back to train A.
If I copy the url of the page with the id of the train B for the projection, it goes back to train A as well.

### What did you expect to happen?

The projection should stay on the train B (refreshing the page should not change the projection, copying an url should lead to the good projection)

### Example :
test : train from PLY to MSC
test2 : train from PMP to RES

we choose the train test2 for the projection : 

Image

After refreshing or copy paste the url, the train for the projection has changed : 

Image

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with at least 2 trains (it's easier to see with 2 different paths)
2. Do the projection on the 2nd train
3. Refresh the page, or copy paste the url
4. Rrojection is not done on the right train

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

ae1a20d

### LINKED ISSUE #13161: front: selected and projected train id url parameters get overwritten when loading a scenario
### What happened?

When loading a scenario, the selected and projected train id parameters in the url should be used by default.

However, these ids get overwriten by useAutoUpdateProjection, that sets them to undefined as the infra is not yet ready on launch. The ids then automatically get set to the first train.

useScenarioQueryParams is also a bit fragile and could suffer from race conditions, improving the design would be a nice addition too.

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/user-attachments/assets/1c3a9db9-34a4-45e6-8559-5e6b59b37c51

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev

### PR DESCRIPTION
**Pull request by Synar**
Close [#13161](https://github.com/OpenRailAssociation/osrd/issues/13161) 
Close #12605

The hook that read and set url parameters was dropped, and its logic fused with the hook in charge of autoselecting ids. If we ever have more url parameters beyond ids, we may or may not want to review this choice, but it's the most sensical currently.

The logic of setting ids to undefined if the infra is not ready was dropped. If some ids consumers require the infra to be ready, but check whether the selected or projected train ids are defined instead of checking the infra status, their logic should be changed. Indeed, selected/projected ids are user defined parameters that should not be overwritten as a shorthand for loading.

I think the hook could probably get cleaned up a bit further. In particular the code in the final useEffect should be factored into functions, and we should avoid the async logic of settings the ids from the url and retriggering the hook.

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/useAutoSelectTrainIds.ts [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+ * Automatically select the train to be used for the simulation results display and for the projection.
+ *
+ * This hook is executed if:
+ * - the infrastructure has just been loaded
+ * - a train is deleted, added or modified
+ * - new trains have been loaded (if no valid train has been loaded before, selectedTrainId and
+ * currentTrainIdForProjection will still be undefined and must be updated)
+ */
+const useAutoSelectTrainIds = (
+  infra: InfraWithStatus,
```
Comment (Caracol3) [inline front/src/applications/operationalStudies/hooks/useAutoSelectTrainIds.ts]: Do we still need infra here and in the deps ?

**Review by Caracol3 — APPROVED** [review]
Lgtm (tested). Just left one question

File: front/src/applications/operationalStudies/hooks/useAutoSelectTrainIds.ts (hunk 1 above)
Comment (Synar) [reply front/src/applications/operationalStudies/hooks/useAutoSelectTrainIds.ts]: Good catch, thanks! I agree infra now appears useless here, dropping it.

**Review by Math-R — APPROVED** [review]
looks good to me !
