### PR TITLE
front: fix selected items count after macro delete

### LINKED ISSUE #13780: front: train selected is not updated after trains deletion in NGE
### What happened?

https://github.com/user-attachments/assets/d52764b0-c8b3-4ea6-8915-49512f1f59a0

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

delete a train in NGE (using delete key or manual deletion)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

19cdb22

### PR DESCRIPTION
**Pull request by RomainValls**
closes #13780

### CODE REVIEW

**Review by kmer2016 — CHANGES_REQUESTED** [review]
The current fix filters ghost IDs when displaying the count, but `selectedTimetableItemIds` still contains deleted train IDs. This can hide bugs if other code uses this state directly.

**Suggested fix**
Clean up `selectedTimetableItemIds` when trains are deleted, instead of filtering later by calling `setSelectedTimetableItemIds` inside `removeAndUnselectTrains`

```typescript
const removeAndUnselectTrains = useCallback(
  (timetableItemIds: TimetableItemId[]) => {
    removeTimetableItems(timetableItemIds);
    // Remove only deleted items instead of clearing all selection
    setSelectedTimetableItemIds((prevSelected) =>
      prevSelected.filter((id) => !timetableItemIds.includes(id))
    );
  },
  [removeTimetableItems, setSelectedTimetableItemIds]
);
```

Then we can remove the defensive filter (Your suggestion)

**Benefits**
- State stays clean (no ghost IDs)
- Bugs become visible instead of hidden
- Simpler code, less dependencies

What do you think?

**Comment by RomainValls** [comment]
> The current fix filters ghost IDs when displaying the count, but `selectedTimetableItemIds` still contains deleted train IDs. This can hide bugs if other code uses this state directly.
> 
> **Suggested fix** Clean up `selectedTimetableItemIds` when trains are deleted, instead of filtering later by calling `setSelectedTimetableItemIds` inside `removeAndUnselectTrains`
> 
> ```ts
> const removeAndUnselectTrains = useCallback(
>   (timetableItemIds: TimetableItemId[]) => {
>     removeTimetableItems(timetableItemIds);
>     // Remove only deleted items instead of clearing all selection
>     setSelectedTimetableItemIds((prevSelected) =>
>       prevSelected.filter((id) => !timetableItemIds.includes(id))
>     );
>   },
>   [removeTimetableItems, setSelectedTimetableItemIds]
> );
> ```
> 
> Then we can remove the defensive filter (Your suggestion)
> 
> **Benefits**
> 
> * State stays clean (no ghost IDs)
> * Bugs become visible instead of hidden
> * Simpler code, less dependencies
> 
> What do you think?

Thank you for this suggestion. Pushed it in the fixup 👍 😄

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TimetableBoardWrapper.tsx [hunk 1]
```diff
@@ -95,10 +95,19 @@ const TimetableBoardWrapper = ({
     [timetableItemsWithDetails]
   );
 
+  const existingTimetableItemIds = useMemo(
+    () => new Set(timetableItemsWithDetails.map(({ id }) => id)),
+    [timetableItemsWithDetails]
+  );
+
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/Timetable/TimetableBoardWrapper.tsx]: Now that `removeAndUnselectTrains` properly cleans `selectedTimetableItemIds` when trains are deleted, the `existingTimetableItemIds` set and its filtering logic have become redundant.

```suggestion

```

**Comment by kmer2016** [comment]
> The current fix filters ghost IDs when displaying the count, but `selectedTimetableItemIds` still contains deleted train IDs. This can hide bugs if other code uses this state directly.
> 
> **Suggested fix** Clean up `selectedTimetableItemIds` when trains are deleted, instead of filtering later by calling `setSelectedTimetableItemIds` inside `removeAndUnselectTrains`
> 
> ```ts
> const removeAndUnselectTrains = useCallback(
>   (timetableItemIds: TimetableItemId[]) => {
>     removeTimetableItems(timetableItemIds);
>     // Remove only deleted items instead of clearing all selection
>     setSelectedTimetableItemIds((prevSelected) =>
>       prevSelected.filter((id) => !timetableItemIds.includes(id))
>     );
>   },
>   [removeTimetableItems, setSelectedTimetableItemIds]
> );
> ```
> 
> Then we can remove the defensive filter (Your suggestion)
> 
> **Benefits**
> 
> * State stays clean (no ghost IDs)
> * Bugs become visible instead of hidden
> * Simpler code, less dependencies
> 
> What do you think?

Update: After deeper analysis, I realized my initial suggestion was incomplete. I missed that there were two removal paths `removeTimetableItems` define on `useScenarioData` called from parent component of `TimeTableBoardWrapper` and `removeAndUnselectTrains`.

A cleaner solution would be to lift `selectedTimetableItemIds` state up to `useScenarioData` so `removeTimetableItems` can directly clean the selection when trains are deleted (from Timetable or NGE). This removes the need for `existingTimetableItemIds` filtering and the separate removeAndUnselectTrains function.

**Review by kmer2016 — APPROVED** [review]
Good job! Don't forget to fixup

**Comment by SharglutDev** [comment]
> [!NOTE]
> @Akctarus, this PR will conflict with [yours](https://github.com/OpenRailAssociation/osrd/pull/14065)

**Comment by Pivouane** [comment]
I can't test everything right now due to technical difficulties but LGTM !

**Review by Pivouane — APPROVED** [review]
