### PR TITLE
front: fix blank page when train schedule with no arrival date

### LINKED ISSUE #8112: A train schedule breaks the frontend: dateTime.split is undefined
### What happened?

Using a specific train schedules breaks the frontend:

image

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Import this [train_broken.json](https://github.com/user-attachments/files/16283415/train_broken.json)
3. The frontend fails

### On which environments the bug occurs?

Local, Staging (DgexSol), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

580140d

### PR DESCRIPTION
**Pull request by achrafmohye**
Closes #8112

### CODE REVIEW

File: front/src/modules/trainschedule/components/TimetableV2/utils.ts [hunk 1]
```diff
@@ -32,5 +32,8 @@ export const extractTagCode = (tag?: string | null) => {
 export const timetableHasInvalidTrain = (trains: TrainScheduleWithDetails[]) =>
   trains.some((train) => train.invalidReason);
 
-export const transformDateWithoutYear = (dateTime: string): string =>
-  `${dateTime.split('/')[0]}/${dateTime.split('/')[1]} ${dateTime.split('/')[2].slice(5)} `;
+export const transformDateWithoutYear = (dateTime: string): string => {
+  const parts = dateTime.split('/');
+  if (!parts[0] || !parts[1] || !parts[2]) return '';
+  return `${parts[0]}/${parts[1]} ${parts[2].slice(5)}`;
+};
```
Comment (flomonster) [inline front/src/modules/trainschedule/components/TimetableV2/utils.ts]: ## Structure

If I understand correctly, this function takes a date and formats it, ignoring the year.

Weirdly, the input is a string and not a `Date` type. We should use a standard library to do this kind of operation.
Date formatting is complicated and depends on the user's region. Doing it manually is tedious and error-prone.

Examples:
- Canada: `YYYY-MM-DD`
- France: `DD/MM/YYYY`
- Italy: `DD.MM.YY`
- US: `MM-DD-YYYY`

## The fix

- Returning an empty string when the input format is invalid is unpredictable and must be documented
- We should have unit tests to avoid regression

> [!NOTE]
> Ideally, changing the behavior of a function should necessarily lead to a modification of docs and tests.

**Review by flomonster — CHANGES_REQUESTED** [review]
Thanks for your PR. 

I have some structural remarks on this code (before the PR) and on the fix (the PR itself).
It's important to revamp the logic of this code to make it more robust.

File: front/src/modules/trainschedule/components/TimetableV2/utils.ts (hunk 1 above)
Comment (achrafmohye) [reply front/src/modules/trainschedule/components/TimetableV2/utils.ts]: Fixed, can you check behaviour and new implementation :)

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/utils/date.ts [hunk 2]
```diff
@@ -162,3 +164,9 @@ export function convertIsoUtcToLocalTime(isoUtcString: string): string {
 export function addDurationToIsoDate(startTime: string, duration: string) {
   return dayjs(startTime).add(ISO8601Duration2sec(duration), 'second').format();
 }
+
+export function transformDateWithoutYear(dateTime: string) {
```
Comment (flomonster) [inline front/src/utils/date.ts]: > Weirdly, the input is a string and not a Date type.

Means that the function **MUST** take a Date and not a string.

```suggestion
export function serializeDateTimeWithoutYear(dateTime: Date) {
```

> [!NOTE]
> I suggest renaming the function name since this function doesn't transform the given argument but serializes it.

Comment (flomonster) [inline front/src/utils/date.ts]: > Returning an empty string when the input format is invalid is unpredictable and must be documented

Means that the function **MUST** be documented and should not have this unpredictable behavior.

> [!NOTE]
> If you take a `Date` as input you don't have to handle the case where the string is not a formated date.

Comment (flomonster) [inline front/src/utils/date.ts]: > We should have unit tests to avoid regression.

Is there any reason not to test it?
In our case, the affected function is particularly easy to test.

**Review by flomonster — CHANGES_REQUESTED** [review]
Some comments were not taken into account.

**Review by eckter — APPROVED** [review]
LGTM, bug is fixed

**Review by flomonster — APPROVED** [review]
Looks okay.

> [!NOTE]
> The date management requires a code refactoring.
>
> The transformation process is weird, for example the `train.startTime` process is as follows 🤯:
> 1. String ISO8601
> 2. Dayjs obj
> 3. String custom  `DD/MM/YYYY HH:mm:ss`
> 4. Date obj
> 5. Dayjs obj
> 6. String custom `DD/MM HH:mm:ss`

**Review by clarani — APPROVED** [review]
LGTM, I created a enhancement to refacto this later : https://github.com/OpenRailAssociation/osrd/issues/8166
