### PR TITLE
front: fix stdcm origin time panel behaviour

### LINKED ISSUE #4419: STDCM departure time window is acting very strange
### What happened?

Trying to edit the departure time window, with link on, i'm expecting the delta to remain the same (2h), but instead both fields get the same value.
Moreover, i only wrote `1`, then `1` again in the beginning, and the field went from 10 to 23, then 01, instead of 11. Actualy only a few numbers i'm writing properly work.
In the video, i stick for quite a while on 09:00:00, but during this time i'm actively trying to change that value, but none of my inputs change anything, until eventually it works again.

There are plenty of weird behaviors with this component that need to be fixed.

Video : https://github.com/osrd-project/osrd/assets/86296016/60e04659-2640-4bab-8aae-7f886214442d

### What did you expect to happen?

This component should behave as follows : 
- when the link is active, the time delta between both fields mut remain the same, no matter the field we are editing
- every number the user wants to change MUST change when the user writes new numbers

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Try to use the time departure window component as explained above

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 114.0.5735.134
- **OS**: Windows 10 build 19045.2965
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast f7e54dce Core f7e54dce API 511d09c1 Front f7e54dce

### PR DESCRIPTION
**Pull request by clarani**
closes #4419

### CODE REVIEW

File: front/src/reducers/osrdconf/helpers.ts [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+};
+
+export const computeLinkedOriginTimesFromOriginTime = (
+  originDate: string | undefined,
+  originTime: string | undefined,
+  originUpperBoundDate: string | undefined,
+  originUpperBoundTime: string | undefined,
+  newOriginTime: string
+) => {
+  console.log({
```
Comment (Math-R) [inline front/src/reducers/osrdconf/helpers.ts]: Need to remove it

**Review by Math-R — CHANGES_REQUESTED** [review]

File: front/src/reducers/osrdconf/helpers.ts (hunk 1 above)
Comment (clarani) [reply front/src/reducers/osrdconf/helpers.ts]: Done

**Review by Math-R — APPROVED** [review]
LGTM ! nicely done :)
