### PR TITLE
front: use use query for searches

### LINKED ISSUE #11855: stdcm: operational point search: typing at medium speed fails the search
### What happened?

When you type really fast or really slow, you get the search results you'd expect in the operational point search.
However, I you type at medium speed, the results don't appear or only flash.

https://github.com/user-attachments/assets/68534aaa-8928-46aa-8fd0-f9d2593d416a

### What did you expect to happen?

I expect the results to always be displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the stdcm view
2. Search for an operational point by typing at medium-fast speed
3. See the list doesn't appear or flashes

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

629e2cd

### PR DESCRIPTION
**Pull request by Synar**
Close [#11855](https://github.com/OpenRailAssociation/osrd/issues/11855)

- turn postSearch from a mutation to a query (and thus useMutation to useLazyQuery), as we are querying data, not mutating it, despite being a post due to having a body

- turn useLazyQuery to useQuery for users and operational points, to let rtk fully handle the query and cache process, and solve race conditions created from subsequent manual search queries. This is limited to op and users for now as a proof of concept. but if this PR is merged, this work should be extended to other objects.

- also fix an issue where when listing the possible ch for an op in stdcm ch for ops containing the current trigram were also included in the search. There was a second filter later that prevented them being actually displayed to users, but it seemed like a dirty workaround. (Can we drop this filter btw? It seems unnecessary now.) (Also we probably should not be using the search endpoint at all for this, but rather the matching endpoint, using an op reference rather than a trigram. This is out of scope for this pr.)

- finally, add rtk cache tags to the postsearch endpoint depending on the type of object queried

### CODE REVIEW

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx [hunk 1]
```diff
@@ -49,18 +49,17 @@ export default function useSearchOperationalPoint({
...
   }, [stdcmOperationalPoints, isSuperUser, isStdcm]);
 
-  /* Search for operational whose trigrams start with the search query */
-  const searchOperationalPointsByTrigram = useCallback(
-    async (searchQuery: string) => {
-      const shouldSearchByTrigram = !Number.isInteger(+searchQuery) && searchQuery.length < 4;
 
-      if (!shouldSearchByTrigram || !infraID) return [];
+  /* Lazily search for operational whose trigrams exactly match the search query */
+  const lazySearchByExactTrigram = useCallback(
```
Comment (SharglutDev) [inline front/src/common/Map/Search/useSearchOperationalPoint.tsx:53]: Not related to this PR but is it relevant to have `isStdcm` and `isSuperUser` in the deps of this `useCallback` ?
`stdcmPerimeterOperationalpointsFilter` should be enough ?

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx [hunk 2]
```diff
@@ -80,45 +79,72 @@ export default function useSearchOperationalPoint({
...
+    const sortedTrigramResults = trigramResults.sort(sortOperationalPointsFromTrigramSearch);
+    const trigramResultsIds = new Set(sortedTrigramResults.map((op) => op.obj_id));
+
+    const nameAndUicResults = [
+      ...((rawNameAndUicResults ?? []) as SearchResultItemOperationalPoint[]),
+    ];
+    const dedupNameAndUicResults = nameAndUicResults.filter(
+      (item) => !trigramResultsIds.has(item.obj_id)
+    );
+    const sortedNameAndUicResults = [...dedupNameAndUicResults];
```
Comment (SharglutDev) [inline front/src/common/Map/Search/useSearchOperationalPoint.tsx]: Is this necessary ?

**Review by SharglutDev — COMMENTED** [review]
Thanks for the refacto ! Everything seems to be working fine

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx (hunk 1 above)
Comment (Synar) [reply front/src/common/Map/Search/useSearchOperationalPoint.tsx:53]: Indeed ^^

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx (hunk 2 above)
Comment (Synar) [reply front/src/common/Map/Search/useSearchOperationalPoint.tsx]: Not really no, good catch.

Comment (Synar) [reply front/src/common/Map/Search/useSearchOperationalPoint.tsx]: Not really no, good catch.

File: front/src/common/useSearchUsers.ts [hunk 3]
```diff
@@ -15,47 +17,34 @@ export type User = {
...
-      const results = (await postSearch({
-        searchPayload: {
-          object: 'user',
-          query: ['search', ['name'], searchQuery],
-        },
-        pageSize: 101,
-      }).unwrap()) as SearchResultItemUser[];
-
-      return results.map((result) => ({
+  const { data: searchedUsersData } = osrdEditoastApi.endpoints.postSearch.useQuery(
```
Comment (emersion) [inline front/src/common/useSearchUsers.ts:22]: We can use `currentData` here to make it so the results are reset when `debouncedSearchTerm` changes (instead of persisting the old value until we receive a new response).

Comment (emersion) [reply front/src/common/useSearchUsers.ts:22]: Hm, actually, this is not what we want here. `currentData` would reset the list while the user is typing, which isn't nice.

Does `skipToken` result in `data` being reset to null? Or does the old data persist when typing something then emptying the search field?

Comment (emersion) [reply front/src/common/useSearchUsers.ts:22]: (BTW - all of the above is a nit, feel free to ignore/resolve.)

**Comment by emersion** [comment]
Many thanks for this PR, much nicer than what we had before!

> There was a second filter later that prevented them being actually displayed to users

Just to make sure: is this the filter you're referring to?

https://github.com/OpenRailAssociation/osrd/blob/4774cbf76f88be2e56e4b509273922b0170e9a0c/front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx#L29

File: front/src/common/useSearchUsers.ts (hunk 3 above)
Comment (Synar) [reply front/src/common/useSearchUsers.ts:22]: For currentData, I had considered it, but this is one of the cases where I think data makes more sense. For search results I believe smoothness is more important than consistency.

As for skipToken, I believe it sadly does not reset data to undefined. However, we explicitly check whether the searchTerm is truthy in the final search results use memo to handle this case.

Comment (Synar) [reply front/src/common/useSearchUsers.ts:22]: For currentData, I had considered it, but this is one of the cases where I think data makes more sense. For search results I believe smoothness is more important than consistency.

As for skipToken, I believe it sadly does not reset data to undefined. However, we explicitly check whether the searchTerm is truthy in the final search results use memo to handle this case.

**Comment by Synar** [comment]
Yes indeed. Although when writing the summary for this pr I mixed it up with the "temporary" filter below, which seems to serve to prevent users from searching by uic, for some reason. I don't like either of those filters existing.

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅

File: front/src/common/useSearchUsers.ts (hunk 3 above)
Comment (emersion) [reply front/src/common/useSearchUsers.ts:22]: Ah yes, all good then!

**Review by emersion — APPROVED** [review]
\o/
