### PR TITLE
core: avoid blocking multiple threads on timetable load

### LINKED ISSUE #16366: core: possible deadlock on timetable load
I sometimes noticed that core was supposed to load a timetable but nothing was happening. I think I figured out why:

The front-end sends lots of `worker_load` commands (one per second). In some cases they can build up in the queue, if there's no core ready to consume them. So we may receive lots of `worker_load` in a row. 

But core is meant to handle parallelism properly: only one thread is allowed to load a given infra or timetable. But this is done by **blocking the other threads** (`synchronized` and `mutex.withLock`). 

It makes sense for infra loading, as the worker doesn't depend on anything else and can't do anything else anyway. But on timetable loading, on an empty cache we need core to also receive and run simulation requests. Which is impossible when all threads are waiting for the timetable to be loaded.

---

How to reproduce:

Clear valkey and timetable caches for a given timetable.

Before starting a core, spam the `worker_load` endpoint. For example:

```bash
for i in `seq 100`; do curl -X POST http://localhost:4000/api/worker_load -H 'content-type: application/json' --data '{"infra_id": 5,  "timetable_id": 8}'& done
```

Then, start a core and make sure it start by processing `worker_load` endpoints only. On `dev` (`c3ae3fc1164945b8160e32ab883f6147483a50b3`), this results in a deadlock.

---

How to fix:

* When core receives a worker_load that's already being processed, it *must* return immediately.
    * -> We need an actual response for that endpoint, not just 204 with no payload
* Editoast needs to check the response to see if it's actually loaded
* Then core needs a way to restrict the processing to a single worker, without ever blocking the others? I don't know the "good practice" way to do that yet, but it should be easy enough.

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/16366

Note: several threads can still be stuck together *during the infra loading stage*, but it's less of an issue: it has no external dependency (no deadlock), the worker is likely unable to process other requests while an infra is loaded anyway, and it's much shorter.

### CODE REVIEW

File: editoast/src/views/worker_load.rs [hunk 1]
```diff
@@ -122,7 +122,13 @@ pub(in crate::views) async fn worker_load(
...
 
     let status = match status {
-        Ok(()) => WorkerStatus::Ready,
+        Ok(response) => {
+            if response.loaded {
+                WorkerStatus::Ready
+            } else {
+                WorkerStatus::NotReady
+            }
+        }
```
Comment (woshilapin) [inline editoast/src/views/worker_load.rs:131]:
```suggestion
        Ok(WorkerLoadResponse { loaded: true }) => WorkerStatus::Ready,
        Ok(WorkerLoadResponse { loaded: false }) => WorkerStatus::NotReady,
```

or with guard pattern (not sure which version I like best 🤷)


```suggestion
        Ok(response)  if response.loaded => WorkerStatus::Ready,
        Ok(response)  if !response.loaded => WorkerStatus::NotReady,
```

**Review by woshilapin — APPROVED** [review]

File: core/src/main/java/fr/sncf/osrd/api/TimetableCacheManager.kt [hunk 2]
```diff
@@ -101,40 +102,49 @@ class TimetableCacheManager(
...
+    /** Starts loading timetable data in the background. Noop if already loaded or loading. */
+    fun startLoading(infra: FullInfra, timetableId: TimetableId) {
+        if (disableAllCaching) return
+        val cacheKey = getCacheKey(infra, timetableId)
+        if (cache.containsKey(cacheKey)) return
+        val mutex = mutexes.computeIfAbsent(cacheKey) { Mutex() }
+        if (!mutex.tryLock()) return
+        scope.launch {
+            try {
+                if (!cache.containsKey(cacheKey)) fetchAndCache(infra, timetableId, cacheKey)
```
Comment (Erashin) [inline core/src/main/java/fr/sncf/osrd/api/TimetableCacheManager.kt]: You've already tested this condition l129.

File: core/src/main/kotlin/fr/sncf/osrd/api/WorkerLoadEndpoint.kt [hunk 3]
```diff
@@ -52,5 +56,16 @@ class WorkerLoadEndpoint(
                 .addLast(KotlinJsonAdapterFactory())
                 .build()
                 .adapter(WorkerLoadRequest::class.java)
+        @JvmField
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/api/WorkerLoadEndpoint.kt:60]: nit: EoL before `@JvmField`.

**Review by Erashin — APPROVED** [review]
Editoast `worker_load_test` is failing due to changes, should be easy to fix.
Lgtm :)
