### PR TITLE
front: allow submit with invalid pathsteps in itinerary modal

### LINKED ISSUE #15115: itinerary modal: can't submit if form invalid
### What happened?

In the new itinerary modal, if one of the path steps is invalid or if the pathfinding failed, it is not possible to submit the form.

However, we want to be able to create invalid trains and the app handles this case in the simulation results.

### What did you expect to happen?

- [ ] submitting the form works if one of the path steps is invalid
- [ ] submitting the form works if the pathfinding failed
- [ ] submitting the form in an invalid state properly transfer the invalid state in the old UI
- [ ] the old UI should allow as well the submission of the form in an invalid state, even if no RS / invalid RS (this AC is more like an enhancement)

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Import a train with an invalid op or create a train in the new itinerary modal with an invalid pathfinding
3. Try to submit the form

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### LINKED ISSUE #15716: Itinerary modal - can't submit form
### What happened?

Linked with https://github.com/OpenRailAssociation/osrd/issues/15115

It the above issue, the form couldn't be submitted when an error was in it but it seems like the form can't be submitted at all.

### What did you expect to happen?

Be able to submit the form when no errors are in it.
Submitting the form should save all current informations in it so they are displayed in the old UI.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario and create a train via the new itinerary modal
2. Try to submit, nothing happens

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

15330bb

### PR DESCRIPTION
**Pull request by RomainValls**
close #15716
close #15115 

Removed conditions in `submitItinerary` to allow submitting with invalid path steps. 

It was decided it was ok to build the invalid path step on this following format when the user has typed something not recognized in our infra : ` operational_point: {
            type: 'trigram',
            trigram: inputValue,
            secondary_code: null,
          },`

We will later have a specific field for the unrecognized waypoint, but for now it is ok to have it as a trigram.

### CODE REVIEW

**Review by DucNg — APPROVED** [review]

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 1]
```diff
@@ -373,10 +389,7 @@ const ItineraryModal = ({
       i === filledSteps.length - 1 ? { ...step, stopFor: new Duration({ minutes: 0 }) } : step
     );
 
-    const updatedPathSteps = buildPathSteps(stepsWithStopAtDestination, pathStepsMetadataById);
-
-    const compacted = compact(updatedPathSteps);
-
+    const compacted = compact(buildPathSteps(stepsWithStopAtDestination, pathStepsMetadataById));
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Not a big fan of this variable name (and filledSteps).
Could we find a better name or add some doc ?

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 2]
```diff
@@ -313,28 +313,48 @@ const ItineraryModal = ({
...
+        location: {
+          operational_point: {
+            type: 'trigram',
+            trigram: inputValue,
+            secondary_code: null,
+          },
+          local_track_name: null,
+        },
+        isInvalid: true,
       };
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Could you add a note for the purpose of this and say that is is temporary ?

**Review by SharglutDev — COMMENTED** [review]
Thanks for the fix, works great nust some small comments

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 3]
```diff
@@ -313,28 +313,48 @@ const ItineraryModal = ({
...
+          ...step,
+          theoreticalMargin: step.theoreticalMargin ?? undefined,
+          receptionSignal: step.receptionSignal ?? undefined,
+          location: step.location,
+          coordinates:
+            metadata.type === 'trackOffset' ? metadata.coordinates : metadata.parts[0]?.coordinates,
+          name: metadata.type === 'opRef' ? metadata.name : undefined,
+          uic: metadata.type === 'opRef' ? metadata.uic : undefined,
+        };
+      }
```
Comment (SarahBellaha) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]:
```suggestion
         const isOpRef = metadata.type === 'opRef';

        return {
          ...baseStep,
          location: step.location,
          coordinates: isOpRef ? metadata.parts[0]?.coordinates : metadata.coordinates,
          name: isOpRef ? metadata.name : undefined,
          uic: isOpRef ? metadata.uic : undefined,
        };
```
It might be more readable that way ?

Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Thx, done in the fixup 🙂

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: I replaced `filledSteps` with `stepsWithLocationOrInput`, wdyt ? 

Also, I removed `compact()` as I realized it was useless in the actual flow (empty steps are already filtered out). 
I chose `pathStepsFromV2` to make the variable clear, but I added a todo comment saying we should rename it once the legacy `pathSteps` are dropped. 

Is it ok for you ? 🙂

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 4]
```diff
@@ -358,29 +375,27 @@ const ItineraryModal = ({
...
+    //TODO this variable name should be changed when we no longer have to convert from v2 to v1 for path steps
+    const pathStepsFromV2 = buildPathSteps(stepsWithStopAtDestination, pathStepsMetadataById);
 
-    if (compacted.length < 2) return;
+    if (pathStepsFromV2.length < 2) return;
 
-    dispatch(updatePathSteps(compacted));
-    launchPathfinding(compacted, rollingStockId, { isInitialization: true });
+    dispatch(updatePathSteps(pathStepsFromV2));
+    launchPathfinding(pathStepsFromV2, rollingStockId, { isInitialization: true });
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:454]: Orthogonal to this PR but why do we need to launch the legacy pathfinding when submitting ?

Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:454]: The legacy pathfinding isn't launched automatically when coming back to the "old" itinerary modal from the new

Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:454]: ok got it 👍

**Comment by RomainValls** [comment]
pathsteps with no location are now filtered, allowing us to keep the invalid pathsteps from the imports, that contain a location (based on trigram). 

Also removed the logic of compact() in the reverseItinerary as we now filter out pathSteps with no location.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 5]
```diff
@@ -312,48 +312,37 @@ const ItineraryModal = ({
...
-            location: step.location,
-          };
+          return { ...baseStep, isInvalid: true };
         }
 
-        const isOpRef = metadata.type === 'opRef';
+        const coordinates =
+          metadata.type === 'trackOffset' ? metadata.coordinates : metadata.parts[0]?.coordinates;
+
+        const secondary_code = metadata.type === 'opRef' ? metadata.secondaryCode : undefined;
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: nit: a bit weird to have some of the fields pre-computed in a `const` and not for other.
We should either put them all inline in the return or all pre-computed like 
`const metadata = metadata.type === 'opRef' ? {...} : {...}`

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅ 

You can close the last comment when fixed

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx (hunk 5 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Indeed, didn't see that ^^
Chose to do everything inline to reduce the size a bit 👍
