### PR TITLE
front: itinerary modal - allow to submit all the time

### LINKED ISSUE #15445: Itinerary modal - impossible to submit the form
### What happened?

In the new itinerary modal, if a path step is invalid or if the pathfinding failed, it is not possible to submit the form.

Therefore it is impossible to work in "no calcul" mode in the app.

### What did you expect to happen?

- [x] One can submit the form if one of the path step is invalid
- [x] One can submit the form if the pathfinding failed
- [ ] Bonus : it's possible to add/edit a train in the old interface even if the rolling stock is missing

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Edit a train and move to the new itinerary modal
3. Break the pathfinding
4. Try to submit the form

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by SharglutDev**
fix #15445

### CODE REVIEW

**Comment by RomainValls** [comment]
Thx for the PR :) 

I'm wondering, as the title and the conditions in the code differ a bit : 
Do we want to be able to submit "all the time" -> also when we have no steps with location ? 
At the moment in the code, we check if locatedStepsCount > 2 to submit the itinerary, but in the future, do we want to be able to submit an itinerary with no located steps at all ? 

LGTM for the rest of the PR 👍

**Comment by SharglutDev** [comment]
> I'm wondering, as the title and the conditions in the code differ a bit : Do we want to be able to submit "all the time" -> also when we have no steps with location ? At the moment in the code, we check if locatedStepsCount > 2 to submit the itinerary, but in the future, do we want to be able to submit an itinerary with no located steps at all ?

Oh yes my bad the branch name is misleading (the commit is good hough).
I discussed it with @maelysLeratRosso yesterday and she agreed that we could block the submission if we had less than 2 path steps (it's not possible to create a train with one path step).

Maybe as an enhancement we could display some warning/error to explain the user why the submit is blocked when only one path step is provided.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 1]
```diff
@@ -288,8 +286,8 @@ const ItineraryModal = ({
   };
 
   const submitItinerary = () => {
-    if (locatedStepsCount >= 2) {
-      if (hasInvalidPathStep || pathfindingError) return;
+    if (locatedStepsCount < 2) {
```
Comment (Math-R) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:289]: nit : i saw that locatedStepCount is filled because of 
`pathSteps.filter((step) => step.location !== null).length;`

what about using `isEmptyStep` introduce in this [commit](https://github.com/OpenRailAssociation/osrd/pull/14870/changes/f6229e3ab3116cab42c5e4b7f865b1260ff29275) to also test if location is `''`?

Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:289]: Hmm looks like as long as a path step doesn't have a location it won't be counted in `locatedStepCount` so it should be fine don't you think ? The emptiness of the input is not relevant for blocking the form.
Even if one of the form line is filled with "toto", it's location will be null as we didn't select a suggestion from the combobox.
 
`isEmptyStep` looks handy for pathfinding or line management purposes.

Or maybe it didn't understand what you was proposing ?

**Review by Math-R — APPROVED** [review]
