### PR TITLE
front: fix stop_for for non stops in xml import

### LINKED ISSUE #13084: viriato import : adds stops on passing waypoints
### What happened?

When I import this file in Viriato, I see that my DN-LYD has stops everywhere, but in the file, BEA and CSS are not stops

[Bug stops Viriato.xml](https://github.com/user-attachments/files/22174090/Bug.stops.Viriato.xml)

### What did you expect to happen?

I expect no stops when "pass type is used"

### How can we reproduce it (as minimally and precisely as possible)?

Import the file above and observe

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

288b0ab

### PR DESCRIPTION
**Pull request by Synar**
Close #13084

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/helpers/buildStepsFromOcp.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ export const buildSteps = (
       schedule.push({
         at: id,
         arrival: Duration.subtractDate(step.arrivalDate, departureTime).toISOString(),
-        stop_for: `PT${step.stopFor}S`,
+        stop_for: step.stopFor ? `PT${step.stopFor}S` : null,
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/helpers/buildStepsFromOcp.ts]: This makes it so zero is marked as a non-stop. Shouldn't this be `step.stopFor !== undefined`?

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/helpers/buildStepsFromOcp.ts]: Ah indeed, thanks for the catch!

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/helpers/buildStepsFromOcp.ts]: Fixed ^^

**Review by emersion — APPROVED** [review]
LGTM!
