### PR TITLE
front: fix enter keydown to select first suggestion in the list

### LINKED ISSUE #15036: For waypoints, pressing Enter in the new itinerary modal should validate the first option
### What happened?

When I start typing for a waypoint, pressing Enter should validate the first option in the list (if there is an option). Otherwise, if there is no option, it should empty the cell.
For now it does nothing (except if there is only one result left)

### What did you expect to happen?

I expect : 
- If there is at least one proposition, choose the first one
- Otherwise, empty the cell

### How can we reproduce it (as minimally and precisely as possible)?

Try as in the video

https://github.com/user-attachments/assets/bdad6b00-28f5-4d89-82df-7f70f6adb92c

when I type "enter" if there is still multiple possible choice nothing happens. when I type "space" only one result is available, then I can press "enter" to select it.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

42e8bca

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15036

### CODE REVIEW

**Comment by achrafmohye** [comment]
Does this fix empty the cell when clicking enter with no suggestions ?

>   When I start typing for a waypoint, pressing Enter should validate the first option in the list (if there is an option). Otherwise, if there is no option, it should empty the cell.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx [hunk 1]
```diff
@@ -240,6 +240,30 @@ const PathStepItem = ({
     ? visibleSuggestions.length + 1
     : visibleSuggestions.length;
 
+  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
+    if (e.key !== 'Enter') return;
+
+    if (visibleSuggestions.length === 0) return;
+
+    const activeSuggestion = document.querySelector('.suggestion-item.active');
```
Comment (achrafmohye) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: Why not use  `e.currentTarget` instead of `document` if `.suggestion-item` is in the scope
```suggestion
    const activeSuggestion = e.currentTarget.querySelector('.suggestion-item.active');
```

**Comment by Math-R** [comment]
> Does this fix empty the cell when clicking enter with no suggestions ?
> 
> > When I start typing for a waypoint, pressing Enter should validate the first option in the list (if there is an option). Otherwise, if there is no option, it should empty the cell.

look's like not, if I use `pax` in the input, there is no suggestion and when I press enter nothing happens

**Comment by Math-R** [comment]
https://github.com/user-attachments/assets/d2e7dd1e-0360-4a58-9a28-80d3e96484de

Also when I hit "enter" here to select Rouen, you can see an error clipping below

**Comment by RomainValls** [comment]
@achrafmohye @Math-R 

Last fix makes it so when the user types something not recognized, it validates it. 

The flashing message "Not recognized point: " is also fixed by checking if the query is empty in the last return of `
isStepInvalidAndIsEditing`
 

I decided to do [another PR](https://github.com/OpenRailAssociation/osrd/pull/15836) to handle 'Empty the input when user validates and the point isn't recognized', as the issue doesn't come from this PR.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: Thx, I changed it 👍

**Comment by RomainValls** [comment]
Discussed in [this issue ](https://github.com/OpenRailAssociation/osrd/issues/15951) : 

If the user focusses out, no matter whether what is written is recognized or not : it cancels (the input remains empty if it was previously empty, or it keeps the value it had before the edition)
If the user presses enter :
If there at least a suggestion, it chooses the first suggestion
If there is no suggestion, it empties the field

I'll ping when the changes are done

**Review by Math-R — APPROVED** [review]
tested and works well lgtm

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx [hunk 2]
```diff
@@ -102,33 +104,29 @@ const PathStepItem = ({
...
     let message = t('invalidOP');
 
-    if (!pathStepMetadata?.isInvalid || !pathStep.location || inputValue !== undefined)
-      return (message += `${inputValue}
-      `);
-
     const { location } = pathStep;
 
-    if (location.type === 'track_offset') {
+    if (location && 'track' in location) {
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: Probably a rebase error, this has been recently changed and `track_offset` type now exists :)
```suggestion
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx [hunk 3]
```diff
@@ -102,33 +104,29 @@ const PathStepItem = ({
...
 
-    const trackInfo = location.local_track_name
-      ? `, ${t('track')} ${location.local_track_name}`
-      : '';
+    const trackInfo =
+      location && location.local_track_name ? `, ${t('track')} ${location.local_track_name}` : '';
 
-    if (location.operational_point.type === 'id') {
-      return message + t('opId') + trackInfo;
+    if (location && location.operational_point.type === 'id') {
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: This should work I think (same for other conditions)
```suggestion
    if (location?.operational_point.type === 'id') {
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx [hunk 4]
```diff
@@ -412,17 +444,17 @@ const PathStepItem = ({
...
                 narrow
-                onFocus={onOpFocus}
-                onBlur={onOpBlur}
+                onFocusCapture={onOpFocus}
+                onBlurCapture={onOpBlur}
                 onChange={(e) => onOpInputChange(e.target.value)}
               />
             </div>
-            {isTrackOffset ? (
+            {pathStep.location && 'track' in pathStep.location ? (
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: We could keep `IsTrackOffset` I think ?
```suggestion
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 5]
```diff
@@ -606,7 +630,36 @@ const ItineraryModal = ({
                         })
                       );
                     }}
-                    onOpBlur={() => unmarkEditing(pathStep.id)}
+                    onOpBlur={() => {
+                      const valueOnFocus = focusValueRef.current[pathStep.id];
+                      const valueOnBlur = getInputForStep(pathStep.id);
+
+                      if (
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx:638]: nit: we could add some docs here on this event to explain what's happening

**Review by SharglutDev — COMMENTED** [review]
Just passing by, you can resolve the comments when fixed

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx (hunk 2 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/PathStepItem.tsx]: yep, bad rebase 😄
