### PR TITLE
lmr: add messages during pathfinding and when its done

### LINKED ISSUE #9451: `Obtenir la simulation` button doesn't send a request when there's no pathfinding
### What happened?
Part of https://github.com/osrd-project/osrd-confidential/issues/815

Clicking the `Obtenir la simulation` button does nothing, and actually doesn't even send a request. The console shows this:

Image

> [!NOTE]
> Edit: actually core was down so the pathfinding wasn't completed. So the button could not work.
> Edit n°2: same thing happens when no rolling stock is selected, there can't be a pathfinding
> Edit n°3: same when origin, destination, or waypoint is missing

### What did you expect to happen?

- [ ] This message should be displayed when the pathfinding is running:

Image

- [ ] When the path is found, this message should appear for 2 seconds then disappearing with a fading

Image

### How can we reproduce it (as minimally and precisely as possible)?

Inputs are in the screenshot.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

7451939

### PR DESCRIPTION
**Pull request by Caracol3**
close #9451

### CODE REVIEW

**Review by theocrsb — COMMENTED** [review]
image

I have these two messages at the same time

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 1]
```diff
@@ -110,6 +110,7 @@ const StdcmConfig = ({
       maxSpeed: validateMaxSpeed(maxSpeed, rollingStock?.max_speed),
     };
   }, [rollingStock, towedRollingStock, totalMass, totalLength, maxSpeed]);
+  const [validationMessage, setValidationMessage] = useState<string | null>(null);
```
Comment (theocrsb) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: I think we can just use undefined
```suggestion
  const [validationMessage, setValidationMessage] = useState<string>();
```

**Comment by Caracol3** [comment]
> image
> 
> I have these two messages at the same time

This is weird, i never had this. Did you restart the front ?

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 1 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Good catch ! Done

**Review by Math-R — DISMISSED** [review]
Lgtm tested & live reviewed with @Caracol3

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 2]
```diff
@@ -173,6 +174,25 @@ const StdcmConfig = ({
     }
   }, []);
 
+  useEffect(() => {
+    if (origin.location && destination.location & rollingStock?.id) {
```
Comment (Math-R) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: & => &&

**Comment by theocrsb** [comment]
> > image
> > I have these two messages at the same time
> 
> This is weird, i never had this. Did you restart the front ?

Yes, You can try these inputs 

image

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 2 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: done

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 3]
```diff
@@ -87,6 +87,7 @@ const StdcmConfig = ({
   const formRef = useRef<HTMLDivElement>(null);
 
   const [formErrors, setFormErrors] = useState<StdcmConfigErrors>();
+  const [ciChanged, setCiChanged] = useState(false);
```
Comment (theocrsb) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: I think it's better to use a variable name with an `is` because it's a boolean

Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Good catch !
done

**Review by theocrsb — APPROVED** [review]
LGTM and tested :)

**Review by Math-R — APPROVED** [review]
lgtm

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 4]
```diff
@@ -267,7 +271,7 @@
         justify-content: center;
         color: rgb(11, 114, 60);
         padding-top: 23px;
-        font-size: 1.5rem;
+        font-size: 24px;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: font-size is the only style who should remain in rem :) (same in `.validation-message`)

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 5]
```diff
@@ -294,6 +298,35 @@
...
+        display: flex;
+        font-weight: 400;
+        letter-spacing: 0px;
+        text-align: center;
+        justify-content: center;
+        line-height: 32px;
+        height: 80px;
+        border-radius: 8px;
+        color: rgb(33, 100, 130);
+        background-color: rgb(230, 247, 255);
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: We try to directly use the design system theme from `_variables.scss`
```suggestion
        background-color: var(--info5);
```

You can also use `info60` for the text color, add `success5` (in hex unit) for the success background and use `success60` for the success text

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 6]
```diff
@@ -294,6 +298,35 @@
...
         text-align: center;
       }
+
+      .validation-message {
+        width: 450px;
+        display: flex;
+        font-weight: 400;
+        letter-spacing: 0px;
+        text-align: center;
+        justify-content: center;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Are these two necessary ? Maybe `justify-content` is enough (didn't test)

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 7]
```diff
@@ -258,6 +258,10 @@
     .banner-content {
       padding: 0 0 16px 378px;
       background: linear-gradient(180deg, rgba(239, 243, 245) 40px, rgba(233, 239, 242) 40px);
+      &:has(.validation-message) {
+        padding: 0 !important;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: If you need to override something, could you leave a comment here to explain why ?

File: front/src/styles/scss/applications/stdcm/_home.scss
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss:1]: Capture d’écran 2025-01-10 à 11 33 55

Did you add the fade-out effect ? I don't see it

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 8]
```diff
@@ -173,6 +175,30 @@ const StdcmConfig = ({
     }
   }, []);
 
+  useEffect(() => {
+    setIsCiChanged(true);
+  }, [origin.location, destination.location]);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: What about if a via has changed ?

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 4 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 5 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 6 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: indeed, justify-content alone was enough

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 7 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: Good catch. I put it in the beginning of my work but there is no use for the ``` ìmportant ``` now. I removed it.
We still need the padding though.

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 9]
```diff
@@ -110,6 +111,7 @@ const StdcmConfig = ({
       maxSpeed: validateMaxSpeed(maxSpeed, rollingStock?.max_speed),
     };
   }, [rollingStock, towedRollingStock, totalMass, totalLength, maxSpeed]);
+  const [validationMessage, setValidationMessage] = useState<string>();
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Instead of adding a new state, do you think we could use a logic similar of the one in this [PR](https://github.com/OpenRailAssociation/osrd/pull/10292/files) ? When a CI changes (origin, via or destination), the pathfinding is relaunched so we can use its loading state to display the info message.

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 4 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 5 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss:1]: We have it now

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 8 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: The logic is now different, we have the message even when a via is added or removed

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 9 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: done

File: front/src/applications/stdcm/hooks/useStaticPathfinding.ts [hunk 10]
```diff
@@ -84,7 +84,7 @@ const useStaticPathfinding = (infra?: InfraWithState) => {
     [pathfinding, pathProperties]
   );
 
-  return result;
+  return { pathfinding: result, isFetching };
```
Comment (SharglutDev) [inline front/src/applications/stdcm/hooks/useStaticPathfinding.ts]: Better to do that because when we use it on other component it's hard to follow what is actually fetching.
```suggestion
  return { pathfinding: result, isPathfindingLoading: isFetching };
```

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 11]
```diff
@@ -294,6 +298,39 @@
         line-height: 24px;
         text-align: center;
       }
+
+      .validation-message {
+        width: 450px;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]:
```suggestion
        width: 466px;
```

image

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 12]
```diff
@@ -294,6 +298,39 @@
...
+        display: flex;
+        font-weight: 400;
+        letter-spacing: 0px;
+        justify-content: center;
+        line-height: 32px;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]:
```suggestion
        line-height: 24px;
```

image

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 13]
```diff
@@ -294,6 +298,39 @@
...
+        height: 80px;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]:
```suggestion
        height: 72px;
```

image

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 14]
```diff
@@ -294,6 +298,39 @@
...
+        border-radius: 8px;
+        color: var(--info60);
+        background-color: var(--info5);
+        margin-top: 16px;
+        padding-top: 23px;
+        font-size: 1rem;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Since it's 1rem after all, we probably don't need to set this

```suggestion
```

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 15]
```diff
@@ -294,6 +298,39 @@
         line-height: 24px;
         text-align: center;
       }
+
+      .validation-message {
+        width: 450px;
+        display: flex;
+        font-weight: 400;
+        letter-spacing: 0px;
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Since we don't justify the text, I don't think we need to specify this

```suggestion
```

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 16]
```diff
@@ -294,6 +298,39 @@
...
+            0 0 0 4px rgba(255, 255, 255, 1) inset,
+            0 0 0 5px rgb(60, 202, 128) inset,
+            0 3px 7px -3px rgba(11, 114, 60, 0.4);
+        }
+      }
+
+      .fade-out {
+        opacity: 0;
+        transition: opacity 0.3s ease-out;
+      }
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss]: The animation doesn't seem to work. It's because when `isFadingOut` becomes true, the banner is removed from the DOM and the fade-out class does nothing.

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 11 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 15 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: good catch, i removed it

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 12 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 13 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 14 above)
Comment (Caracol3) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 17]
```diff
@@ -294,6 +297,52 @@
...
+        color: var(--info60);
+        background-color: var(--info5);
+        margin-top: 16px;
+        padding-top: 23px;
+        box-shadow:
+          0 0 0 4px rgba(255, 255, 255, 1) inset,
+          0 0 0 5px rgb(112, 193, 229) inset,
+          0 3px 7px -3px rgba(28, 28, 217, 0.4);
+        &-success {
+          color: var(--success60);
```
Comment (SharglutDev) [inline front/src/styles/scss/applications/stdcm/_home.scss:318]: We should add this to prevent for the blinking effect after the fade out
```suggestion
          opacity: 0;
          color: var(--success60);
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 18]
```diff
@@ -173,6 +185,20 @@ const StdcmConfig = ({
...
+    }
+    document.addEventListener('animationend', () => {
+      setShowMessage(false);
+    });
+    return () => {
+      document.removeEventListener('animationend', () => {
+        setShowMessage(false);
+      });
+    };
+  }, [isPathFindingLoading, pathfinding?.status]);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]:
```suggestion
  }, [isPathFindingLoading]);
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 19]
```diff
@@ -138,16 +141,25 @@ const StdcmConfig = ({
...
+    }
+    return t('pathfindingStatus.success');
+  };
+
+  const formErrorsStatus = useMemo(() => {
+    if (pathfinding && origin.location && destination.location) {
+      return checkStdcmConfigErrors(pathfinding.status !== 'success', pathSteps, t);
+    }
+    return undefined;
+  }, [pathfinding, pathSteps, t]);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Not sure why you change the old useEffect for this ?

**Review by SharglutDev — COMMENTED** [review]
Added some comments we discussed (+1 bonus) not to forget them

File: front/src/applications/stdcm/hooks/useStaticPathfinding.ts (hunk 10 above)
Comment (Caracol3) [reply front/src/applications/stdcm/hooks/useStaticPathfinding.ts]: done

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 20]
```diff
@@ -173,6 +185,27 @@ const StdcmConfig = ({
...
+  useEffect(() => {
+    if (isPathFindingLoading) {
+      setShowMessage(true);
+    }
+
+    const handleAnimationEnd = () => {
+      setShowMessage(false);
+    };
+
+    const element = document.querySelector('.pathFinding-status');
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: It's better to use a `ref` when possible in React. You can declare it next to the other `useRef` of the component.
```suggestion
    const pathfindingBannerRef = useRef<HTMLDivElement>(null);
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 21]
```diff
@@ -173,6 +185,27 @@ const StdcmConfig = ({
...
+    if (element) {
+      element.addEventListener('animationend', handleAnimationEnd);
+    }
+
+    return () => {
+      if (element) {
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Don't think you need to put the `if` here. With the ref, you should be able to do 
```suggestion
      pathfindingBannerRef.current?.removedEvent...
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 19 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: It was when we didn’t yet know why there was an infinite loop. The error was pointing to this useEffect. I thought at the time that a useMemo could be a solution to fix it. But I can put it back since the issue was actually elsewhere.

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 21 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Indeed, with the ref, its useless now. I removed it

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 20 above)
Comment (Caracol3) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Good catch ! 
Done !

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 22]
```diff
@@ -173,6 +184,22 @@ const StdcmConfig = ({
     }
   }, []);
 
+  useEffect(() => {
+    if (isPathFindingLoading) {
+      setShowMessage(true);
+    }
+
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx:200]: We need to add this case, otherwise the hidden banner is never removed from the DOM if the pathfinding fails.
```suggestion
    if (pathfinding?.status === 'failure') {
      setShowMessage(false);
    }
```
Also add `pathfinding?.status` in the deps array

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 23]
```diff
@@ -173,6 +184,22 @@ const StdcmConfig = ({
...
+    const handleAnimationEnd = () => {
+      setShowMessage(false);
+    };
+
+    pathfindingBannerRef.current?.addEventListener('animationend', handleAnimationEnd);
+
+    return () => {
+      pathfindingBannerRef.current?.removeEventListener('animationend', handleAnimationEnd);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Sorry to change again but it seems `showBanner` never goes back to false (and the hidden banner is never remove from the dom) if we launch 2 pathfinding in a row : launch a PNO>LEW, clean LEW and then launch a PNO>ARR and watch the element not being removed in the inspector)
```suggestion
    document.addEventListener('animationend', handleAnimationEnd);

    return () => {
      document.removeEventListener('animationend', handleAnimationEnd);
```

Comment (emersion) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: `document` will catch animations from all elements on the page, so I don't think it's a good idea. For instance if a completely unrelated element happens to animate too then we'd mix things up here.

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Yeah that's why we changed it before, but somehow the `showMessage` state is not reset to true (only the first time) if we keep it with the ref on the banner. Do you have any idea about that ?

Comment (emersion) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Have you tried `useLayoutEffect` and putting the ref on the `.pathFinding-status`?

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Yep, didn't work

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: Fixed

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 24]
```diff
@@ -294,6 +297,53 @@
...
+        }
+        74% {
+          opacity: 1;
+        }
+        100% {
+          opacity: 0;
+        }
+      }
+
+      .fade-out {
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss]: This class is unused.

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 25]
```diff
@@ -294,6 +297,53 @@
...
+        margin-top: 16px;
+        padding-top: 23px;
+        box-shadow:
+          0 0 0 4px rgba(255, 255, 255, 1) inset,
+          0 0 0 5px rgb(112, 193, 229) inset,
+          0 3px 7px -3px rgba(28, 28, 217, 0.4);
+        &-success {
+          color: var(--success60);
+          background-color: var(--success5);
+          opacity: 0;
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss:320]: I think this `opacity` can be dropped.

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 26]
```diff
@@ -294,6 +297,53 @@
         line-height: 24px;
         text-align: center;
       }
+
+      .pathFinding-status {
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Nit: we use kebab-case instead of camelCase for CSS classes.

Hm, I suppose the class is used elsewhere so we can't change it?

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 27]
```diff
@@ -294,6 +297,53 @@
...
+        left: -8px;
+        position: absolute;
+        bottom: -95px;
+        width: 466px;
+        display: flex;
+        font-weight: 400;
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss]: This is the default font-weight, so shouldn't be necessary.

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 28]
```diff
@@ -294,6 +297,53 @@
...
+        justify-content: center;
+        line-height: 24px;
+        height: 72px;
+        border-radius: 8px;
+        color: var(--info60);
+        background-color: var(--info5);
+        margin-top: 16px;
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Seems like removing this `margin-top` doesn't change the result.

File: front/src/styles/scss/applications/stdcm/_home.scss [hunk 29]
```diff
@@ -294,6 +297,53 @@
         line-height: 24px;
         text-align: center;
       }
+
+      .pathFinding-status {
+        left: -8px;
+        position: absolute;
+        bottom: -95px;
+        width: 466px;
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_home.scss]: Would be slightly nicer to use `calc(100% + 16px)`: would make it more obvious why there is a `left: -8px`.

**Review by emersion — APPROVED** [review]
Just some nits, feel free to resolve!

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 24 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 25 above)
Comment (emersion) [reply front/src/styles/scss/applications/stdcm/_home.scss:320]: It cannot: when the animation ends the state setter doesn't cause an immediate re-render to remove the element from the DOM, but we want to keep a zero opacity still.

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 26 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 27 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 28 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 29 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss]: done

File: front/src/styles/scss/applications/stdcm/_home.scss (hunk 25 above)
Comment (SharglutDev) [reply front/src/styles/scss/applications/stdcm/_home.scss:320]: we need it
