### PR TITLE
front: fix the timetable stops counter

### LINKED ISSUE #7517: Adding a via when setting a train itinerary doesn't update its schedules
### What happened?

In a scenario, when adding vias by clicking on map, by the suggested vias modal, or via the rocket, it doesn't update the schedule property of the train. On the example below, the St Malo trains have 2 vias each so it should show at least 2 steps in the details (3 if we count the destination ? Ask a PO for that).

Capture d’écran 2024-05-26 à 22 25 45

### What did you expect to happen?

Even if we can't set any duration with this features, it should update the train `schedule` property by setting the `duration` property at null in the PathStep store. This will result to a valid information of the steps in the timetable when opening the train details.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add a train with at least 1 or 2 vias
3. Open the train details by clicking on the eye icon at the top and see that it still shows 1 step.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma 14.5
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 4b0f2d6

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #7517

### CODE REVIEW

**Review by Yohh — APPROVED** [review]
LGTM :muscle:

File: front/src/modules/trainschedule/components/TimetableV2/hooks.ts [hunk 1]
```diff
@@ -151,7 +151,7 @@ const useTrainSchedulesDetails = (
             id: trainSchedule.id,
             trainName: trainSchedule.train_name,
             startTime: dayjs(trainSchedule.start_time).format('D/MM/YYYY HH:mm:ss'), // format to time
-            stepsCount: trainSchedule.schedule?.length ?? 0,
+            stopsCount: (trainSchedule.schedule?.length ?? 0) + 1, // +1 to take the final stop (destination) into account
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/TimetableV2/hooks.ts]: Here we check only if there are trains in trainSchedule.schedule but what about if one of them has (the first schedule for example) trainSchedule.schedule[0].stop_for is null/undefined ? It will still count as a stopCount but we don't want to.
We should probably create a const to count the number of schedules with a stop_for > 0.

**Review by SharglutDev — CHANGES_REQUESTED** [review]

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !
