### PR TITLE
front: GEV - fix bug when resize the chart

### LINKED ISSUE #3574: front: GEV: when resize the panel, the train vanish

### PR DESCRIPTION
**Pull request by clarani**
closes #3574 

[Capture vidéo du 2023-03-20 15-54-33.webm](https://user-images.githubusercontent.com/45000526/226378729-1e0933ad-e5a6-4992-8a31-137a04f90e43.webm)

### CODE REVIEW

**Comment by alexandredamiron** [comment]
Probl après resize sur comportement

File: front/src/applications/operationalStudies/components/SimulationResults/SpeedSpaceChart/SpeedSpaceChart.jsx [hunk 1]
```diff
@@ -101,8 +101,7 @@ export default function SpeedSpaceChart(props) {
     let debounceTimeoutId;
     clearTimeout(debounceTimeoutId);
     debounceTimeoutId = setTimeout(() => {
-      const height = d3.select(`#container-${CHART_ID}`).node().clientHeight;
-      setHeightOfSpeedSpaceChart(height);
+      createChartAndTrain();
```
Comment (alexandredamiron) [inline front/src/applications/operationalStudies/components/SimulationResults/SpeedSpaceChart/SpeedSpaceChart.jsx:104]: I'm not sure It work the same. Not this behavior on dev (Storybook) 

https://user-images.githubusercontent.com/765626/226406192-a04a945d-718f-44fe-8a2d-5d9c9e4646ea.mp4

Comment (clarani) [reply front/src/applications/operationalStudies/components/SimulationResults/SpeedSpaceChart/SpeedSpaceChart.jsx:104]: Thank you very much for spotting this bug ! It was quite tricky, but I think it is fixed now (can have a look at my last commit)  :)

**Review by alexandredamiron — APPROVED** [review]
