### PR TITLE
editoast: ignore disabled occurrences in conflict detection

### LINKED ISSUE #12648: Conflict does not ignore disabled occurences
### What happened?

When an occurrence is disabled, we should not take its requirements into account for conflict detection.

Here I've disabled an occurrence and created the same train schedule:
Image

### What did you expect to happen?

We should not see any conflicts here.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario on small infra
2. Import this [timetable.json](https://github.com/user-attachments/files/21509790/timetable.json)
3. Display conflicts list.

### How to fix

The issue comes from the conflict endpoints `GET` `/timetable/{id}/conflicts`.

https://github.com/OpenRailAssociation/osrd/blob/2ece45f36441412f0d7a05bff7d97acccac16c8e/editoast/src/views/timetable.rs#L632-L635

Here we're retrieving the list of occurrences (modified, created). But we're not skipping disabled once.

Adapt this function https://github.com/OpenRailAssociation/osrd/blob/2ece45f36441412f0d7a05bff7d97acccac16c8e/editoast/src/models/paced_train.rs#L175 
1. If a modified exception disable the train, then it should be skipped and not returned.
1. Add this case in the function documentation
1. Adapt tests

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

2ece45f

### PR DESCRIPTION
**Pull request by Erashin**
When an occurrence was modified to be disabled, it was not ignored in iter_occurrences and hence in conflict detection. Fix this.

### CODE REVIEW

**Review by louisgreiner — APPROVED** [review]
LGTM ✅

File: editoast/src/models/paced_train.rs [hunk 1]
```diff
@@ -181,23 +181,26 @@ impl PacedTrain {
...
+        for (occurrence_index, exception) in modified_exceptions {
             if let Some(occurrence) = base_occurrences.get_mut(occurrence_index as usize) {
-                let train_id = TrainId::PacedTrainModifiedException {
-                    paced_train_id: self.id,
-                    index: occurrence_index as u64,
-                    exception_key: exception.key.clone(),
-                };
-                *occurrence = (train_id, self.apply_exception(exception));
+                if exception.disabled {
+                    base_occurrences.remove(occurrence_index as usize);
```
Comment (flomonster) [inline editoast/src/models/paced_train.rs]: It can be very inefficient. The worst case is when all trains are disabled. `O(n²)`.
For more information check out the documentation of [Vec::remove](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.remove)


To improve this we can define a variable like: `let mut to_remove: vec![false, base_occurrences.len()];`.
Then, for each occurrence to remove, we set the corresponding value to `true`.
At the end of the loop we can do something like:

```rust
let occurences = base_occurrences.into_iter().zip(to_remove).filter_map(|(occ, to_remove)|
  if to_remove { None }
  else { Some(occ) }
).collect_vec();
```

File: editoast/src/models/paced_train.rs [hunk 2]
```diff
@@ -181,23 +181,26 @@ impl PacedTrain {
     pub fn iter_occurrences(&self) -> impl Iterator<Item = (TrainId, TrainSchedule)> {
         let mut base_occurrences = self.get_base_occurrences();
 
-        let enabled_modified_exceptions = self
+        let modified_exceptions = self
```
Comment (flomonster) [inline editoast/src/models/paced_train.rs:184]: I think we don't need this variable anymore since it's just an iterator of `self.exceptions`.

**Review by flomonster — CHANGES_REQUESTED** [review]
Thanks for this PR.

File: editoast/src/models/paced_train.rs (hunk 2 above)
Comment (Erashin) [reply editoast/src/models/paced_train.rs:184]: Uh no it's still used to filter out the created exceptions. Or do you have something else in mind?

File: editoast/src/models/paced_train.rs (hunk 1 above)
Comment (Erashin) [reply editoast/src/models/paced_train.rs]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/12785/commits/5bbebe6f4498646933974dfbc201323cbe9c676e.

File: editoast/src/models/paced_train.rs (hunk 2 above)
Comment (flomonster) [reply editoast/src/models/paced_train.rs:184]: Indeed

File: editoast/src/models/paced_train.rs [hunk 3]
```diff
@@ -181,27 +181,38 @@ impl PacedTrain {
...
+                    *occurrence = (train_id, self.apply_exception(exception));
+                }
             }
         }
+        // Remove disabled occurrences.
+        let occurences = base_occurrences
+            .into_iter()
+            .zip(to_remove)
+            .filter_map(|(occ, disabled)| if disabled { None } else { Some(occ) })
+            .collect_vec();
```
Comment (flomonster) [inline editoast/src/models/paced_train.rs]: We don't need to collect since we're returning an iterator, let's keep things lazy.
```suggestion
            .filter_map(|(occ, disabled)| if disabled { None } else { Some(occ) });
```

**Review by flomonster — APPROVED** [review]
LGMT
