### PR TITLE
front: fix warped map display

### LINKED ISSUE #7587: TSv2: Warpped map not displayed
### What happened?

In the simulation results with trainschedule v2, the warpped man is stuck in with an infinite loader.

image

### What did you expect to happen?

The warpped man should be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. open the warpped map on the left of the space time chart.

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 625d185

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #7587

### CODE REVIEW

File: front/src/common/Map/WarpedMap/SimulationWarpedMap.tsx [hunk 1]
```diff
@@ -242,26 +254,36 @@ const SimulationWarpedMap = ({ collapsed }: { collapsed?: boolean }) => {
...
-          setState({ type: 'pathLoaded', path, pathBBox, warpedBBox, transform });
-        }
-      })
-      .catch((error) => setState({ type: 'error', message: error }));
+
+    // V2
+    if (pathProperties) {
+      updateWarpedMapState(pathProperties.geometry.coordinates);
+    } else {
+      // V1
```
Comment (SharglutDev) [inline front/src/common/Map/WarpedMap/SimulationWarpedMap.tsx]:
```suggestion
      // TODO DROP V1 : remove this condition
```

**Review by SharglutDev — APPROVED** [review]
Thank you for the fix ! Lgtm and tested. Just one comment to help for drop v1 in next PI.

File: front/src/common/Map/WarpedMap/SimulationWarpedMap.tsx [hunk 2]
```diff
@@ -242,26 +254,36 @@ const SimulationWarpedMap = ({ collapsed }: { collapsed?: boolean }) => {
...
-          const pathBBox = bbox(path) as BBox2d;
-          const { warpedBBox, transform } = getWarping(path);
-
-          setState({ type: 'pathLoaded', path, pathBBox, warpedBBox, transform });
-        }
-      })
-      .catch((error) => setState({ type: 'error', message: error }));
+
+    // V2
+    if (pathProperties) {
```
Comment (kmer2016) [inline front/src/common/Map/WarpedMap/SimulationWarpedMap.tsx]: If the core functionality depends on whether Train Schedule V2 is activated, it would be more reliable to use the `getTrainScheduleV2Activated` selector like so: `const trainScheduleV2Activated = useSelector(getTrainScheduleV2Activated);`. 
Relying on the pathProperties prop could potentially mask bugs, such as when it is undefined due to unexpected reasons. In such cases, even if Train Schedule V2 is activated, the V1 code block would be executed, which is not the expected behavior.

**Review by kmer2016 — APPROVED** [review]
LGTM
