### PR TITLE
front: enable occurrence selection for path projection

### LINKED ISSUE #11476: Correctly display occurrences on the Space Time Chart and enable to select an occurrence for the projection (+ tests)
> [!WARNING]
> The ACs are not exactly the same as those on the confidential ticket, the last details will be handled in another PR.

## Implementation plan 
- display exceptions and indexed occurrence that have a different projection than the pacedtrain on the spacetime chart

Project button for a train schedule calls `api/train_schedule/7309/path?infra_id=2`.
we should have the same behavior for 
- paced train conform occurences 
- exceptions

## AC
- [ ] You can project onto an occurrence (see mockup for the icon to indicate that you are projecting onto a mission/occurrence):
  - [ ] If you project onto the model train or onto an occurrence that has the same path or schedule as the model train: blue projection icon on the mission's parent map (folded AND unfolded mode). Nothing on the occurrence
  - [ ] If we project onto an occurrence that does not have the same path or schedule as the model train: gray projection icon on the model train (folded AND unfolded mode) + blue projection icon on the occurrence onto which we are projecting

### PR DESCRIPTION
**Pull request by clarani**
closes #11476

Rework of https://github.com/OpenRailAssociation/osrd/pull/12222 (first part merged in https://github.com/OpenRailAssociation/osrd/pull/12882)

## ACs
- [ ] You can project onto an occurrence (see mockup for the icon to indicate that you are projecting onto a mission/occurrence):
  - [ ] If you project onto the model train or onto an occurrence that has the same path or schedule as the model train: blue projection icon on the mission's parent map (folded AND unfolded mode). Nothing on the occurrence
  - [ ] If we project onto an occurrence that does not have the same path or schedule as the model train: gray projection icon on the model train (folded AND unfolded mode) + blue projection icon on the occurrence onto which we are projecting
- [ ] Nothing special happens if you deactivate the occurrence used for the projection (it does not change the space time chart, except the current occurrence is hidden)

## Screenshots
image

### CODE REVIEW

**Review by RomainValls — APPROVED** [review]
Tested, LGTM 👍

File: front/src/utils/trainId.ts [hunk 1]
```diff
@@ -247,3 +247,12 @@ export const extractExceptionIdFromOccurrenceId = (occurrenceId: OccurrenceId):
   // Handle the case where exceptionId contains "_" itself
   return exceptionId.join('_');
 };
+
+/**
+ * Given a paced train id with a PacedTrainId format (used across the front),
```
Comment (emersion) [inline front/src/utils/trainId.ts]: An occurrence ID is given, not a paced train ID.

File: front/src/utils/trainId.ts [hunk 2]
```diff
@@ -247,3 +247,12 @@ export const extractExceptionIdFromOccurrenceId = (occurrenceId: OccurrenceId):
...
+ * returns the train id in the Editoast format (used for api).
+ */
+export const extractEditoastIdFromOccurrenceId = (occurrenceId: OccurrenceId): number => {
```
Comment (emersion) [inline front/src/utils/trainId.ts]: I find the name of this helper function ambiguous: this makes it sound like it returns an editoast ID representing the occurrence, but it returns an editoast ID representing the paced train.

Maybe we should take inspiration from the existing `extractPacedTrainIdFromOccurrenceId()` function, and call this one e.g. `extractEditoastPacedTrainIdFromOccurrenceId`?

Alternatively, I think this helper isn't really saving that much: calling the two functions one after the other would be perfectly fine.

File: front/src/modules/timetableItem/components/Timetable/types.ts [hunk 3]
```diff
@@ -119,6 +119,7 @@ export type Occurrence = {
   rollingStock?: LightRollingStockWithLiveries;
   startTime: Date;
   stopsCount: number;
+  exceptionKey?: string;
```
Comment (emersion) [inline front/src/modules/timetableItem/components/Timetable/types.ts]: I think adding an `exceptionKey` field here in `Occurrence` is a good idea, but it doesn't seem like this new field is used in this commit?

File: front/src/modules/timetableItem/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts [hunk 4]
```diff
@@ -140,13 +140,13 @@ const useOccurrenceActions = ({
...
+      if (status === 'disabled') {
         const firstEnabledOccurrence = occurrences.find(
           (occ) => occ.id !== occurrence.id && !occ.disabled
         );
-
-        dispatch(updateSelectedTrainId(firstEnabledOccurrence?.id));
-        // TODO exceptions : update projected occurrence id in issue https://github.com/OpenRailAssociation/osrd/issues/11476
+        if (selectedTrainId === occurrence.id) {
+          dispatch(updateSelectedTrainId(firstEnabledOccurrence?.id));
+        }
```
Comment (emersion) [inline front/src/modules/timetableItem/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts]: I don't understand this change. The new code seems completely equivalent to the old one, exception that we do a `occurrences.find()` call unnecessarily?

File: front/src/reducers/simulationResults/types.ts [hunk 5]
```diff
@@ -33,6 +33,9 @@ export type ProjectionType = 'trackProjection' | 'operationalPointProjection';
 export interface SimulationResultsState {
   chart?: Chart;
   selectedTrainId?: TrainId;
-  trainIdUsedForProjection?: TrainScheduleId | PacedTrainId | OccurrenceId;
+  trainUsedForProjection?: {
+    id: TrainScheduleId | PacedTrainId | OccurrenceId;
+    exceptionKey?: string;
```
Comment (emersion) [inline front/src/reducers/simulationResults/types.ts]: I'm not a fan of storing the `exceptionKey` in the `trainUsedForProjection`:

- We need to add special cases when the exception is removed, to clear the `exceptionKey` but keep any potential occurrence index in  `OccurrenceId`.
- This potentially duplicates information and allows for inconsistent state, e.g. `exception_42_foo` in `id` (indicating the "foo" exception key) and `bar` in `exceptionKey`.

Could we instead grab the exception ID from the `Occurrence`?

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 6]
```diff
@@ -155,13 +156,15 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithState) => {
...
-      trainIdUsedForProjection && !isOccurrenceId(trainIdUsedForProjection)
-        ? timetableItemsById.get(trainIdUsedForProjection)
-        : undefined,
-    [trainIdUsedForProjection, timetableItems]
-  );
+  const timetableItemUsedForProjection = useMemo(() => {
+    if (!trainIdUsedForProjection) return undefined;
+
+    const timetableItemId = isOccurrenceId(trainIdUsedForProjection)
+      ? extractPacedTrainIdFromOccurrenceId(trainIdUsedForProjection)
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Hm, here we grab the base paced train and ignore exceptions. This means any changes made by the exception are not reflected in `timetableItemUsedForProjection`. What if an exception has a different path, for instance?

Among other things, in `SimulationResults` we call `useGetProjectedTrainOperationalPoints()` with `projectionData?.timetableItem`. Wouldn't this result in the wrong OP list being computed?

**Review by emersion — COMMENTED** [review]
Here are a few comments!

File: front/src/reducers/simulationResults/types.ts (hunk 5 above)
Comment (clarani) [reply front/src/reducers/simulationResults/types.ts]: I'm not a fan either, but I need the key to then call the path endpoint and I can't get the exception key easily for indexedOccurrences...

The alternative would be to store only the trainId, but that adds processing for indexedOccurrences, since it would be necessary to:
- retrieve the complete pacedTrain with exceptions (from the API or from timetableItems ?)
- check the exceptions to see if this occurrence is one or not
- retrieve the key if it is an exception, otherwise use the pacedTrain

I thought it would be easier to manage the key directly in the store, but we can change that if you want

File: front/src/utils/trainId.ts (hunk 2 above)
Comment (clarani) [reply front/src/utils/trainId.ts]: Done

File: front/src/modules/timetableItem/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts (hunk 4 above)
Comment (clarani) [reply front/src/modules/timetableItem/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts]: Hum you're right, I revert this change

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 6 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Hum yes you're right, this is very confusing...

Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done

File: front/src/modules/timetableItem/components/Timetable/types.ts (hunk 3 above)
Comment (clarani) [reply front/src/modules/timetableItem/components/Timetable/types.ts]: Hum it is used, when selecting the occurrence to be used for projection (in `selectOccurrenceForProjection`, in `useOccurrenceActions`).

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 7]
```diff
@@ -154,10 +160,26 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithState) => {
...
-  );
+  const pathUsedForProjection = useMemo(() => {
+    if (!trainIdUsedForProjection) return undefined;
+    if (!isOccurrenceId(trainIdUsedForProjection)) {
+      return timetableItemsById.get(trainIdUsedForProjection)?.path;
+    }
+
+    const pacedTrainId = extractPacedTrainIdFromOccurrenceId(trainIdUsedForProjection);
+    const pacedTrain = timetableItemsById.get(pacedTrainId);
+    if (!pacedTrain || !isPacedTrainResponseWithPacedTrainId(pacedTrain)) throw new Error();
```
Comment (Math-R) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Maybe you could contextualize the error with a message to be more clearer

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 8]
```diff
@@ -154,10 +160,26 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithState) => {
...
-    [trainIdUsedForProjection, timetableItems]
-  );
+  const pathUsedForProjection = useMemo(() => {
+    if (!trainIdUsedForProjection) return undefined;
+    if (!isOccurrenceId(trainIdUsedForProjection)) {
+      return timetableItemsById.get(trainIdUsedForProjection)?.path;
+    }
+
+    const pacedTrainId = extractPacedTrainIdFromOccurrenceId(trainIdUsedForProjection);
+    const pacedTrain = timetableItemsById.get(pacedTrainId);
```
Comment (Math-R) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: it hink you can group the two `get` by using a ternary

```
const train = timetableItemsById.get(
    isOccurrenceId(trainIdUsedForProjection)
      ? extractPacedTrainIdFromOccurrenceId(trainIdUsedForProjection)
      : trainIdUsedForProjection
  );
```

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 9]
```diff
@@ -154,10 +160,26 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithState) => {
...
+    if (!pacedTrain || !isPacedTrainResponseWithPacedTrainId(pacedTrain)) throw new Error();
+
+    let exception: PacedTrainException | undefined;
+    if (isIndexedOccurrenceId(trainIdUsedForProjection)) {
+      const index = extractOccurrenceIndexFromOccurrenceId(trainIdUsedForProjection);
+      exception = pacedTrain.exceptions.find((e) => e.occurrence_index === index);
+    } else {
+      const key = extractExceptionIdFromOccurrenceId(trainIdUsedForProjection);
+      exception = pacedTrain.exceptions.find((e) => e.key === key);
+    }
```
Comment (Math-R) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I think you could simplify this block by extracting the identifier (index or key) using a ternary expression, and then using a single find() call with a conditional property check.
This would avoid the duplication and make the logic a bit easier to follow.

Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I must admit, I personally find the current version clearer, since there is so little common code between these two branches.

File: front/src/reducers/simulationResults/types.ts (hunk 5 above)
Comment (emersion) [reply front/src/reducers/simulationResults/types.ts]: It shouldn't be necessary to have that much logic: we only need to look up the exception if the ID is a `IndexedOccurrenceId`. Also, we shouldn't need to fetch anything from the API - `timetableItems` from `useScenarioData` should be enough.

The following could be put into a re-usable helper if need be:

```ts
  const occurrenceId: IndexedOccurrenceId;
  const pacedTrain = timetableItemsById.get(extractPacedTrainIdFromOccurrenceId(occurrenceId));
  if (!pacedTrain || !isPacedTrainResponseWithPacedTrainId(pacedTrain)) {
    throw new Error('oops');
  }
  const occurrenceIndex = extractOccurrenceIndexFromOccurrenceId(occurrenceId);
  const exception = pacedTrain.exceptions.find((exception) => exception.occurrence_index === occurrenceIndex);
  const key = exception?.key;
```

File: front/src/modules/timetableItem/components/Timetable/types.ts (hunk 3 above)
Comment (emersion) [reply front/src/modules/timetableItem/components/Timetable/types.ts]: This comment is about the `Occurrence` type. `updateTrainIdUsedForProjection()` updates the store's `trainUsedForProjection` field. These two are separate.

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 9 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I also find my version clearer, can we keep it like this ?

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 7 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done :white_check_mark:

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 8 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I have modified a bit the logic of this useMemo, tell me if it's fine for you

File: front/src/modules/timetableItem/components/Timetable/types.ts (hunk 3 above)
Comment (clarani) [reply front/src/modules/timetableItem/components/Timetable/types.ts]: Hum it was used for the selection of the projection like this:
```
const selectOccurrenceForProjection = useCallback((occurrence: Occurrence) => {
  dispatch(updateTrainIdUsedForProjection({ id: occurrence.id, exceptionKey: occurrence.key }));
}, []);
```

But anyway, I droped the exceptionKey in updateTrainIdUsedForProjection, so I can drop this field too now :+1:

File: front/src/reducers/simulationResults/types.ts (hunk 5 above)
Comment (clarani) [reply front/src/reducers/simulationResults/types.ts]: You were right, it was not as difficult as I thought, it's way cleaner like this. Thanks ! :pray:

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 9 above)
Comment (Math-R) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]:
```
const isIndexed = isIndexedOccurrenceId(trainIdUsedForProjection);
const id = isIndexed
  ? extractOccurrenceIndexFromOccurrenceId(trainIdUsedForProjection)
  : extractExceptionIdFromOccurrenceId(trainIdUsedForProjection);

const exception = pacedTrain.exceptions.find((e) =>
  isIndexed ? e.occurrence_index === id : e.key === id
);
```

i was suggesting something like this. But i'm okay if you prefer to keep your version.

Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Ok, then I'll keep mine :) Thanks

**Review by Math-R — APPROVED** [review]
lgtm
