### PR TITLE
front: Rolling stock modal fixes

### LINKED ISSUE #3272: front: no error message when selecting both electric & thermic rolling stock
### What happened?

When checking both the "Électrique" and "Thermique" boxes in the rolling stock selection, no result is found bu no error message is shown
image

### What did you expect to happen?

An error message should be shown like "Pas de résultat trouvé"

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any page where you can select a rolling stock, such as https://osrd.dev.dgexsol.fr/stdcm
2. Click on "Choisissez un matériel roulant"
3. Check the "Électrique" box
4. Check the "Thermique" box

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.7
- **OS**: Windows 10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

62637c93

### PR DESCRIPTION
**Pull request by anisometropie**
- moved RollingStockModal to .tsx
- refactored rollingstock search/sort functions and wrote unit tests
- rolling stock modal now correctly states that no element was found.
- Editoast: didn’t change the schemas, just added a base schema to be extended, so that LightRollingStock `modes` property is generated correctly by our front tool.

closes #3272

### CODE REVIEW

File: front/src/common/api/osrdMiddlewareApi.ts [hunk 1]
```diff
@@ -831,13 +831,13 @@ export type AllowancePercentValue = {
 };
 export type AllowanceValue =
   | ({
-      value_type: 'AllowanceTimePerDistanceValue';
+      value_type: 'time_per_distance';
```
Comment (clarani) [inline front/src/common/api/osrdMiddlewareApi.ts]: Is this not code from the allowances PR ?

Comment (anisometropie) [reply front/src/common/api/osrdMiddlewareApi.ts]: it is, but it’s already on dev so no worries !

**Review by flomonster — APPROVED** [review]
Reviewed the openapi

File: front/src/common/RollingStockSelector/RollingStockModal.tsx [hunk 2]
```diff
@@ -49,65 +92,39 @@ function RollingStockModal(props) {
...
+        );
+        const passEnergeticModesFilter = rollingStockPassesEnergeticModeFilters(
+          filters.elec,
+          filters.thermal,
+          effortCurves.modes
+        );
+        return passSearchedStringFilter && passEnergeticModesFilter;
+      }
+    );
+    if (newFilteredRollingStock) {
```
Comment (clarani) [inline front/src/common/RollingStockSelector/RollingStockModal.tsx:117]:
```suggestion
```
No need for this test as newFilteredRollingStock is necessarily a LightRollingStock[]

File: front/src/common/RollingStockSelector/RollingStockModal.tsx [hunk 3]
```diff
@@ -1,35 +1,78 @@
...
-  const { ref2scroll } = props;
+interface Filters {
+  text: string;
+  elec: boolean;
+  thermal: boolean;
+}
+function rollingStockPassesSearchedStringFilter(
+  name: string,
+  metadata: LightRollingStock['metadata'],
+  filters: Filters
```
Comment (clarani) [inline front/src/common/RollingStockSelector/RollingStockModal.tsx:29]:
```suggestion
  filters: Filters
```
I think you can either pass the whole Filter to your 2 functions (rollingStockPassesSearchedStringFilter and rollingStockPassesEnergeticModeFilters) or only the needed fields (text for the first one, filterElec and filterThermal for the 2nd one)

It's a detail though :)

**Review by clarani — COMMENTED** [review]
Left 2 comments :) also spotted a bug, see your DMs

File: front/src/common/RollingStockSelector/RollingStockModal.tsx (hunk 3 above)
Comment (anisometropie) [reply front/src/common/RollingStockSelector/RollingStockModal.tsx:29]: great observation :) stringFilter does the first version and energeticFilter does the second.

Comment (anisometropie) [reply front/src/common/RollingStockSelector/RollingStockModal.tsx:29]: fixed

File: front/src/common/RollingStockSelector/RollingStockModal.tsx [hunk 4]
```diff
@@ -48,97 +107,56 @@ function RollingStockModal(props) {
...
+  );
 
-  const searchMateriel = (e) => {
-    setFilters({ ...filters, text: e.target.value.toLowerCase() });
-    setIsFiltering(true);
-  };
+  function handleRollingStockLoaded() {
+    const newFilteredRollingStock = filterRollingStocks(rollingStocks, filters);
+    setFilteredRollingStockList(newFilteredRollingStock);
+  }
```
Comment (clarani) [inline front/src/common/RollingStockSelector/RollingStockModal.tsx:117]: It's a detail, but I don't thing I would have create a new function for this (I would have put everything in the useEffect directly). But I'm fine with this version too :)

File: front/src/common/RollingStockSelector/RollingStockModal.tsx [hunk 5]
```diff
@@ -48,97 +107,56 @@ function RollingStockModal(props) {
...
-          return true;
-        })
-      : rollingStocks;
+    if (filters.text !== '' || filters.elec !== false || filters.thermal !== false) {
+      setOpenRollingStockCardId(undefined);
+    } else {
+      setOpenRollingStockCardId(rollingStockID);
+    }
+    const newFilteredRollingStock = filterRollingStocks(rollingStocks, filters);
+    if (newFilteredRollingStock) {
```
Comment (clarani) [inline front/src/common/RollingStockSelector/RollingStockModal.tsx]:
```suggestion
```
No need for the test here as newFilteredRollingStock is never undefined (by default, it will be `[]`)

**Review by clarani — APPROVED** [review]
LGTM !! :) I just left 2 smalls comments, but you can merge without fixing them if you don't think that they are relevant !

Tested in local, the scroll bug is fixed

File: front/src/common/RollingStockSelector/RollingStockModal.tsx (hunk 5 above)
Comment (anisometropie) [reply front/src/common/RollingStockSelector/RollingStockModal.tsx]: fixed !

**Review by eckter — APPROVED** [review]

File: front/src/common/RollingStockSelector/RollingStockModal.tsx (hunk 4 above)
Comment (anisometropie) [reply front/src/common/RollingStockSelector/RollingStockModal.tsx:117]: I think it’s clearer if it says what’s it’s doing
