### PR TITLE
front: fix suggestion display after clicking the Rocket

### LINKED ISSUE #15958: Itinerary modal: the suggestion remains displayed after selecting the path from the Rocket
### What happened?

https://github.com/user-attachments/assets/9df3d013-75f4-4a84-b65c-692c8c42c15e

### What did you expect to happen?

The search results should disappear

### How can we reproduce it (as minimally and precisely as possible)?

1. From the Itinerary modal 
2. Enter two trigrams in the Rocket
3. Submit the pathfinding search

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

8b88601

### PR DESCRIPTION
**Pull request by Akctarus**
closes #15958

### CODE REVIEW

File: front/src/modules/pathfinding/components/Pathfinding/TypeAndPath.tsx [hunk 1]
```diff
@@ -184,6 +184,8 @@ const TypeAndPath = ({
       setDisplayTypeAndPath?.(false);
       launchPathfinding(pathSteps);
       setInputText('');
+      setSearchResults([]);
```
Comment (Uriel-Sautron) [inline front/src/modules/pathfinding/components/Pathfinding/TypeAndPath.tsx]:
```suggestion
```
This line is not necessary; the searchResult is already cleared

**Review by Uriel-Sautron — APPROVED** [review]
Thanks for this PR, the bug has been fixed.

File: front/src/modules/pathfinding/components/Pathfinding/TypeAndPath.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/pathfinding/components/Pathfinding/TypeAndPath.tsx]: fixed in 3e1a39c5c4968c9849d1d9cbdf434782f239051a

**Review by emersion — APPROVED** [review]
