### PR TITLE
front: OSRD → NGE node fixes

### LINKED ISSUE #8842: PR without "BV" or "00" ch code breaks NGE
### What happened?

image

Related to [this PR](https://github.com/OpenRailAssociation/osrd/pull/8748), OSRD actually recognizes it, but it is bugged in macroscopic mode

### What did you expect to happen?

Do not create a node for every other ch

### How can we reproduce it (as minimally and precisely as possible)?

1. Open macroscopic view
2. Create 2 nodes : DPY and MAS
3. Draw trainrun between them
4. Go back to microscopic
5. Go back to macroscopic
6. Notice bug

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c62c9db

### LINKED ISSUE #8926: Import train schedules from open data creates invalid nodes in NGE
### What happened?

image

it seems that the stations met by the path of imported train schedules from open data breaks NGE

related or potential duplicate of https://github.com/OpenRailAssociation/osrd/issues/8842

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

image

1. import train schedules from open data
2. switch to macro
3. notice

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging fbf8e3e

### PR DESCRIPTION
**Pull request by emersion**
_See individual commits._

Closes: https://github.com/OpenRailAssociation/osrd/issues/8842  
Closes: https://github.com/OpenRailAssociation/osrd/issues/8926

### CODE REVIEW

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 1]
```diff
@@ -384,13 +368,25 @@ const importTimetable = async (
...
     .map((trainSchedule) => {
       // Figure out the node ID for each path item
       const pathNodeIds = trainSchedule.path.map((pathItem) => {
         const op = findOpFromPathItem(pathItem, searchResults);
         if (op) {
-          return nodesByOpId.get(op.obj_id)!.id;
+          let node = nodesByOpId.get(op.obj_id);
+          if (!node) {
+            node = createNode({
+              trigram: op.trigram + (op.ch ? `/${op.ch}` : ''),
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts:381]: How do we difference ops with a CH with actual value `''` and others who will get also `''` but not for the same reasons ?

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested (expect for open data import because of a bug)

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts (hunk 1 above)
Comment (emersion) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts:381]: Yeah, this logic won't be able to make the difference. But last time I asked around, `ch == ''` turned out to be a myth - there are no such OPs in the infra in practice (France or otherwise).

(Note, this is old code which just happens to be moved around, it's not new code.)

Comment (SharglutDev) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts:381]: Wow the ghost ch code :D Ok fine by me :)

**Comment by SharglutDev** [comment]
Tested also with imports :)
