### PR TITLE
front: fix Duration serialization in redux persist

### LINKED ISSUE #11277: Diffrent errors when enabling/disabling paced trains
### What happened?

It's hard to reproduce, but try to follow the video and enable/disable paced trains
https://github.com/user-attachments/assets/1e3658e3-9d7a-4210-bc23-8e8aaeb205b3

### What did you expect to happen?

Can add unique train or paced train without any issue 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the Scenario page

2. Activate paced train

3. Add a paced train

4. Deactivate paced train

5. Add a unique train

6. Activate paced train (duplicate of #2, kept for consistency)

7. Refresh the page

8. Add a unique train / paced train

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

872260c

### PR DESCRIPTION
**Pull request by kmer2016**
closes #11277
The bug occurred because of two conflicting persistence configurations:
- One at root level in persistConfig
- One at slice level with persistReducer

This caused Duration objects to not be properly serialized when stored in localStorage, leading to runtime errors when trying to call Duration methds on non-Duration objects.

Solution:
- Remove slice level persistence
- Keep only root level persistence with transforms

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Thank you for this fix, tested.

**Review by Yohh — APPROVED** [review]

File: front/src/reducers/index.ts [hunk 1]
```diff
@@ -77,7 +76,10 @@ const operationalStudiesDateTransform = createTransform(
     cadence: Duration.parse(cadence),
     timeRangeDuration: Duration.parse(timeRangeDuration),
   }),
-  { whitelist: ['operationalStudiesConf'] }
+  {
+    whitelist: ['operationalStudiesConf'],
+    blacklist: ['usingSpeedLimits'],
```
Comment (SharglutDev) [inline front/src/reducers/index.ts]: Feels weird to have this in `blacklist` in a transform concerning dates

**Review by emersion — COMMENTED** [review]
It seems like `pathStepsTransform` is no longer called.

To reproduce: click "Add" in a scenario, go to the "times and stops" tab, this error pops up:

```
11:24:25.806 Uncaught (in promise) TypeError: stopFor.total is not a function
    formatSuggestedViasToRowVias utils.ts:81
    formatSuggestedViasToRowVias utils.ts:74
    fetchAndFormatRows TimesStopsInput.tsx:153
    TimesStopsInput TimesStopsInput.tsx:163
    React 15
    handleTabClick Tabs.tsx:35
    onClick Tabs.tsx:51
    React 23
    <anonymous> index.tsx:28
utils.ts:81:45
```

**Review by SharglutDev — COMMENTED** [review]
Wow forgot to send the comment sorry

File: front/src/reducers/index.ts (hunk 1 above)
Comment (kmer2016) [reply front/src/reducers/index.ts]: You're right! I've moved the blacklist to its dedicated filter and kept the transform focused on date/duration conversions only.

**Comment by SharglutDev** [comment]
Looks good to me. But I'll leave a better redux specialist than me take a turn on this PR too :)

File: front/src/reducers/index.ts [hunk 2]
```diff
@@ -77,7 +76,10 @@ const operationalStudiesDateTransform = createTransform(
     interval: Duration.parse(interval),
     timeWindow: Duration.parse(timeWindow),
   }),
-  { whitelist: ['operationalStudiesConf'] }
+  {
+    whitelist: ['operationalStudiesConf'],
+    blacklist: ['usingSpeedLimits'],
```
Comment (emersion) [inline front/src/reducers/index.ts]: I'm not sure it ever makes sense to use `whitelist` together with `blacklist`? If `whitelist` is supplied, the filter will never run on anything else?

File: front/src/reducers/index.ts [hunk 3]
```diff
@@ -77,7 +76,10 @@ const operationalStudiesDateTransform = createTransform(
     interval: Duration.parse(interval),
     timeWindow: Duration.parse(timeWindow),
   }),
-  { whitelist: ['operationalStudiesConf'] }
+  {
+    whitelist: ['operationalStudiesConf'],
```
Comment (emersion) [inline front/src/reducers/index.ts]: Could we use a `.name` instead of a hardcoded string here?

Comment (kmer2016) [reply front/src/reducers/index.ts]: Yes, already done.

Comment (emersion) [reply front/src/reducers/index.ts]: Ah right, one commit uses strings but the following one replaces these with constants.

**Review by emersion — APPROVED** [review]
LGTM, thank you for untangling this!

**Review by anisometropie — APPROVED** [review]
looking good

**Review by Yohh — APPROVED** [review]
