### PR TITLE
tests: add tests for new bugs and fix them

### LINKED ISSUE #1381: Fuzzer sometimes trigger error "Discontinuity in allowance section"
Steps to reproduce: run the fuzzer on France and wait a little

### LINKED ISSUE #1400: Fuzzer sometimes trigger a `NullPointerException`
`java.lang.NullPointerException: Cannot invoke "fr.sncf.osrd.envelope.part.EnvelopePart.getEndPos()" because "parts[i]" is null`

To reproduce : run the fuzzer on France and wait a little

### LINKED ISSUE #1597: Allow overlapping speed sections in the backend
**Describe the bug**
The backend rejects overlapping speed sections

**To Reproduce**
Import the latest infra

**Expected behavior**
Overlapping speed sections all are taken into account

### PR DESCRIPTION
**Pull request by eckter**

### CODE REVIEW

**Comment by multun** [comment]
@eckter tell me when you need review

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 1]
```diff
@@ -324,9 +324,17 @@ public Envelope computeIteration(Envelope base,
...
             builder.addPart(leftPart);
-        builder.addParts(coreEnvelope.slice(leftPartEndPos, rightPartBeginPos));
-        if (rightPart != null)
+        if (rightPart != null) {
+            // Forcing the right part begin speed avoids an epsilon difference that would cause errors later on
+            assert abs(coreEnvelope.interpolateSpeed(rightPartBeginPos) - rightPart.getBeginSpeed()) < 1e-8;
+            builder.addParts(coreEnvelope.slice(
+                    leftPartEndPos, Double.NaN,
+                    rightPartBeginPos, rightPart.getBeginSpeed()
+            ));
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: Nice catch! I believe the same issue can occur with the left part.
I would suggest adding two more local variables, leftPartEndSpeed and rightPartBeginSpeed, which can be set along with leftPartEndPos and rightPartBeginPos.
This way, there is a single unconditional coreEnvelope.slice call.

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 2]
```diff
@@ -431,6 +439,12 @@ private Envelope computeEnvelopeWithLeftJunction(Envelope envelopeSection,
     private Envelope intersectLeftRightParts(EnvelopePart leftPart, EnvelopePart rightPart) {
         if (rightPart == null || leftPart == null)
             throw AllowanceConvergenceException.tooMuchTime();
+        if (leftPart.getMaxSpeed() < rightPart.getMinSpeed()) {
+            // The curves don't intersect at all
+            // This sometimes happens when one part is very short compared to the time step
+            // When it happens we have very little margin to add time, so we throw a `tooMuchTime` error
+            throw AllowanceConvergenceException.tooMuchTime();
+        }
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: Okay, that's very odd. I would not have expected this to happen

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java [hunk 3]
```diff
@@ -237,4 +240,57 @@ public void testVeryShortRange() {
...
+                new AllowanceRange(rangesTransitions[0], rangesTransitions[1], value1)
+        );
+        var allowance = new LinearAllowance(
+                testContext, rangesTransitions[0], rangesTransitions[1], 0, ranges
+        );
+        try {
+            allowance.apply(maxEffortEnvelope);
+        } catch (AllowanceConvergenceException e) {
+            assertEquals(OSRDError.ErrorCause.USER, e.cause);
+        }
```
Comment (multun) [inline core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java]: The test passes even if no exception is thrown. I think you meant to use assertThrows

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java [hunk 4]
```diff
@@ -237,4 +240,57 @@ public void testVeryShortRange() {
...
+        var ranges = List.of(
+                new AllowanceRange(rangesTransitions[0], rangesTransitions[1], value1)
+        );
+        var allowance = new LinearAllowance(
+                testContext, rangesTransitions[0], rangesTransitions[1], 0, ranges
+        );
+        try {
+            allowance.apply(maxEffortEnvelope);
+        } catch (AllowanceConvergenceException e) {
+            assertEquals(OSRDError.ErrorCause.USER, e.cause);
```
Comment (multun) [inline core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java:295]: same as above, I think assertThrows should be used

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceTests.java [hunk 5]
```diff
@@ -726,4 +727,38 @@ public void testAllowancesErrors() {
         assert linearException.errorType.equals("too_much_allowance_time");
         assert linearException.cause == OSRDError.ErrorCause.USER;
     }
+
+    @Test
+    @Disabled("see https://github.com/DGEXSolutions/osrd/issues/1401")
```
Comment (multun) [inline core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceTests.java]: Thanks for making a reproducing test case, you rock!

File: tests/README.md [hunk 6]
```diff
@@ -1,24 +1,40 @@
...
-Run `python3 fuzzer/fuzzer.py`, any error will be logged in `fuzzer/errors`.
+Run `python3 fuzzer/fuzzer.py`, any error will be reported in `fuzzer/errors` in a json.
+
+Note: you need a docker running locally *with at least one infra imported*.
+It can be a generated infra, or it can be imported from some other DB.
 
-Note: you need a docker running locally *with a database setup with a real infra*.
-This data isn't publicly available yet. 
+If the test is run on a generated infra, the json containing the error report
+can be copied to `tests/fuzzer_outputs/` to integrate it into the test suite.
```
Comment (multun) [inline tests/README.md]: I'm a bit confused, couldn't these be directly added to the backend test suite?
Usually, reproducing tests of former bugs are called regression tests. fuzzer_outputs is useful to know where these tests are from, yet not very useful to know what their intended purpose is.

**Review by multun — CHANGES_REQUESTED** [review]

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java (hunk 2 above)
Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: If you want to see what's going on here you can put a breakpoint and run the integration tests. It is indeed quite odd.

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java (hunk 3 above)
Comment (eckter) [reply core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java]: That is what I meant, an "impossible range" error is a valid output here. No error is also valid.

When I wrote the test it caused an assert earlier, I didn't even know if the margin was possible.

I'll change the code to make this clearer

File: tests/README.md (hunk 6 above)
Comment (eckter) [reply tests/README.md]: > I'm a bit confused, couldn't these be directly added to the backend test suite?

It's mort effort to adapt those to the backend test suite, one fuzzer test includes several requests to the back

> fuzzer_outputs is useful to know where these tests are from, yet not very useful to know what their intended purpose is.

It's named like that because the test suite expects the folder to contains a specific json format, generated from the fuzzer. But I could rename it to something like `regression_fuzzer_tests`

Comment (multun) [reply tests/README.md]: I like regression_fuzzer_tests better, and agree to keep it separate from the backend

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java [hunk 7]
```diff
@@ -237,4 +241,58 @@ public void testVeryShortRange() {
...
+        var ranges = List.of(
+                new AllowanceRange(rangesTransitions[0], rangesTransitions[1], value1)
+        );
+        var allowance = new LinearAllowance(
+                testContext, rangesTransitions[0], rangesTransitions[1], 0, ranges
+        );
+        applyAllowanceIgnoringUserError(allowance, maxEffortEnvelope);
+    }
+
+    /** Applies the allowance to the envelope. Any user error (impossible margin) is ignored */
```
Comment (multun) [inline core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java:290]: I don't get why user errors should be ignored. Shouldn't we know what the expected result is for this specific case?
Sure, it sometimes fails, but I would expect our tests to be somewhat deterministic

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java (hunk 2 above)
Comment (multun) [reply core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I've moved the discussion to https://github.com/DGEXSolutions/osrd/issues/1535

Comment (axrolld) [reply core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I'm taking care of this, a new commit will arrive shortly

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java (hunk 7 above)
Comment (eckter) [reply core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceRangesTests.java:290]: Now that the bug is fixed we can see what the result is, but it's not what the test is about. I don't want this test to fail if someday we change the way we compute allowances in one way or another, the result is irrelevant

File: docker-compose-mac.yml [hunk 8]
```diff
@@ -68,7 +68,7 @@ services:
     ports: ["8000:80"]
     environment:
       OSRD_DEV: "True"
-      OSRD_BACKEND_URL: "http://osrd-core"
+      OSRD_BACKEND_URL: "http://host.docker.internal:8080"
```
Comment (flomonster) [inline docker-compose-mac.yml]: Why did you have to change it?

File: tests/tests/regression_fuzzer_tests/acceleration_assert.json [hunk 9]
```diff
@@ -0,0 +1 @@
...es.java:129\",\"StandaloneSim.java:95\",\"StandaloneSim.java:58\",\"StandaloneSimulationEndpoint.java:85\",\"FkRegex.java:157\",\"FkRegex.java:228\",\"FkChain.java:72\",\"TkFork.java:98\",\"TkFallback.java:89\",\"TkFallback.java:57\",\"TkFallback.java:69\",\"TkWrap.java:58\",\"TkSlf4j.java:110\",\"BkBasic.java:127\",\"BkBasic.java:102\",\"BkSafe.java:49\",\"BkWrap.java:51\",\"BkParallel.java:87\",\"ThreadPoolExecutor.java:1136\",\"ThreadPoolExecutor.java:635\",\"Thread.java:833\"],\"trace\":[]}", "infra_name": "small_infra", "path_payload": {"infra": 94, "name": "foo", "steps": [{"duration": 0, "waypoints": [{"track_section": "TA1", "offset": 1856.6077154118593}]}, {"duration": 1, "waypoints": [{"track_section": "TA4", "offset": 25.049733930557206}]}]}, "schedule_payload": {"timetable": 74, "path": 16446, "schedules": [{"train_name": "foo", "labels": [], "departure_time": 0, "allowances": [{"allowance_type": "engineering", "begin_position": 86.71793651828453, "end_position": 92.01725738112799, "value": {"value_type": "percentage", "percentage": 19.78715063935094}, "capacity_speed_limit": 0.12096469825170542, "distribution": "LINEAR"}], "initial_speed": 0, "rolling_stock": "253"}]}}
```
Comment (flomonster) [inline tests/tests/regression_fuzzer_tests/acceleration_assert.json:1]: Is it really usefull to keep the error code and the stack trace. We could add a field `description` and explain what this test is doing.

File: docker-compose-mac.yml (hunk 8 above)
Comment (eckter) [reply docker-compose-mac.yml]: It didn't work before when I ran it on my windows laptop

File: tests/tests/regression_fuzzer_tests/acceleration_assert.json (hunk 9 above)
Comment (eckter) [reply tests/tests/regression_fuzzer_tests/acceleration_assert.json:1]: The point is to be able to just cp the error files generated by the fuzzer, in this context the error is relevant. We can remove it manually but I don't think there's any reason to, it can be useful to know what bug this test reproduced. 

We could add a description, but there's not a lot to describe, those are just generated regression tests. "This test reproduces the assertion bug" doesn't add much information.

**Review by flomonster — DISMISSED** [review]

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 10]
```diff
@@ -309,22 +307,55 @@ public Envelope computeIteration(Envelope base,
...
         var coreEnvelopeWithLeft = computeEnvelopeWithLeftJunction(base, coreEnvelope, leftPart);
 
         var rightPart = computeRightJunction(base, coreEnvelopeWithLeft, imposedEndSpeed);
         var rightPartBeginPos = rightPart != null ? rightPart.getBeginPos() : base.getEndPos();
 
-        // if the junction parts touch or intersect, there is no core phase
-        if (rightPartBeginPos <= leftPartEndPos) {
+        if (EnvelopePhysics.areIntersecting(rightPart, leftPart)) {
+            // if the junction parts touch or intersect, there is no core phase
             return intersectLeftRightParts(leftPart, rightPart);
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I think it's pretty janky to attempt to detect intersection first using one method, then use another method to perform it. it's bound to create bugs, and we should either not merge this, or file a bug to fix this, and not forget about it.

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 11]
```diff
@@ -309,22 +307,55 @@ public Envelope computeIteration(Envelope base,
...
+        } else if (rightPartBeginPos < leftPartEndPos)
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: can you move the if out of the else? it's pretty confusing, as all of the code below only runs when there is no intersection anyway

File: core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java [hunk 12]
```diff
@@ -174,4 +174,44 @@ public static double intersectStepWithSpeed(
...
+        if (a == null || b == null
+                || a.getMaxSpeed() < b.getMinSpeed()
+                || b.getMaxSpeed() < a.getMinSpeed()
+                || a.getEndPos() < b.getBeginPos()
+                || b.getEndPos() < a.getBeginPos())
+            return false;
+
+        var beginPos = Math.max(a.getBeginPos(), b.getBeginPos());
+        var aPositions = a.clonePositions();
+        var aSpeeds = a.cloneSpeeds();
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: it feel overkill to clone the whole array just to avoid one or two gets

File: core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java [hunk 13]
```diff
@@ -174,4 +174,44 @@ public static double intersectStepWithSpeed(
             interpolatedPosition = minPos;
         return interpolatedPosition;
     }
+
+    /** Returns if two EnvelopeParts intersect */
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: this function doesn't really have a fair description: it does not detect all intersections, as it iterates on a and interpolates on b. if a has like two far apart points and b is high frequency, it will only detect an intersection if the sign of startSpeedA - b.interpolateSpeed(startPosA) isn't the same as endSpeedA - b.interpolateSpeed(endPosA)

File: core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java [hunk 14]
```diff
@@ -174,4 +174,44 @@ public static double intersectStepWithSpeed(
...
+        while (Math.signum(speedDiff) == initialSpeedDiffSign) {
+            pos = clamp(pos, b.getBeginPos(), b.getEndPos());
+            speedDiff = aSpeeds[stepIndex] - b.interpolateSpeed(pos);
+            stepIndex++;
+            pos = aPositions[stepIndex];
+            if (pos >= endPos) {
+                speedDiff = a.interpolateSpeed(endPos) - b.interpolateSpeed(endPos);
+                return Math.signum(speedDiff) != initialSpeedDiffSign;
+            }
+        }
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: as described above, this approach sometimes but not always works

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 15]
```diff
@@ -309,22 +307,55 @@ public Envelope computeIteration(Envelope base,
...
+                && coreEnvelope.stream().noneMatch(part -> EnvelopePhysics.areIntersecting(part, leftPart))) {
+            // The slowdown section doesn't intersect with the core part
+            // That may happen when the section is too short or consists exclusively of braking / acceleration parts
+            throw tooMuchTime();
+        }
+        if (rightPart != null
+                && coreEnvelope.stream().noneMatch(part -> EnvelopePhysics.areIntersecting(part, rightPart))) {
+            // The speedup section doesn't intersect with the core part
+            // That may happen when the section is too short or consists exclusively of braking / acceleration parts
+            throw tooMuchTime();
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I don't get it, the speedup phase is computed with the code phase as a ceiling. does this code detect when the speedup / slowdown never intersect with the core phase, but rather with the end of the region? if so, this data is very available in a simpler way when computing these envelopes in the first place

Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I changed it to `if (leftPart != null && coreEnvelope.getEndPos() == leftPartEndPos)`, is that what you had in mind or is there something simpler?

**Review by multun — APPROVED** [review]

**Review by axrolld — APPROVED** [review]
Good ! That really simplified the intersections, great job !
