### PR TITLE
front: accept railjson file imports

### LINKED ISSUE #11974: Importing an infra as .railjson not working
### What happened?

The front-end does not allow to import an infrastructure file saved as `.railjson` but only in `.json`, which is not fine, since `.railjson` is our format.

Image

### What did you expect to happen?

Allow `.json` AND `.railjson` files

### How can we reproduce it (as minimally and precisely as possible)?

1. export any infra (small infra)
2. rename it `small_infra.railjson`
3. try import new infra with this file

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #11974

### CODE REVIEW

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx [hunk 1]
```diff
@@ -39,7 +39,11 @@ const InfraSelectorModalBodyEdition = ({
   }, [getUserPrivileges, JSON.stringify(infrasList.map((infra) => infra.id))]);
 
   const validateFile = async (fileToValidate: File) => {
-    if (fileToValidate.type !== 'application/json') {
+    const allowedExtensions = ['.json', '.railjson'];
+    const fileName = fileToValidate.name.toLowerCase();
+    const hasAllowedExtension = allowedExtensions.some((ext) => fileName.endsWith(ext));
```
Comment (woshilapin) [inline front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: Validating a file based on the name of the file is probably a bad idea because the name does not enforce anything about the content. Since it's JSON we're talking about, how about `JSON.parse()` instead?

Comment (SarahBellaha) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: This check is only made to display an error message if we have a wrong file type.
Then there is the `JSON.parse()` in a try / catch just a few lines under it :)

Comment (Synar) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: Thanks for the fix!

It's a very subjective matter, but from the discussion on element it seems that a few people (jean, eloi and khoyo) would prefer we filter only based on content and not on name extension at all.

I personally don't have an opinion on this subject, either way is fine with me.

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx [hunk 2]
```diff
@@ -39,7 +39,11 @@ const InfraSelectorModalBodyEdition = ({
...
+
+    if (!hasAllowedExtension) {
       setErrorMessage(t('jsonUpload.notJSONFormat'));
```
Comment (Synar) [inline front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: If we keep the filtering by name, perhaps we should make the error message clearer and mention we only accept .json and .railjson extensions.

**Review by Synar — APPROVED** [review]
Code lgtm ^^

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx (hunk 1 above)
Comment (woshilapin) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: We already have the `<input type="file" accept="json,railjson" />`, we already do guide users to the correct extensions. I know it can still ingest any extension, but I'd say that at this point, the `JSON.parse()` then the ingestion of RailJSON by the backend will catch that anyway.

Comment (kmer2016) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: @woshilapin, you're right that `accept="json,railjson"` helps guide the user. But it's not a strong restriction as users can still select a .txt or other file type. So we can't rely on it alone.

I agree that checking the file name isn’t a real validation. The actual checks happen later with `JSON.parse()` and the backend. But I still think it’s useful for user experience, just to give a quicker and clearer error before trying to parse the file.

So here’s what I suggest:
    - Keep the check on the file name, but only as a UX help, not real validation.
    - Improve the error message as  [@Synar suggested ](https://github.com/OpenRailAssociation/osrd/pull/11994/files#r2123787523)(e.g: "Only .json and .railjson files are allowed.")
    - Add a short comment in the code to explain that this is just for helping users, not for security or content checks.

Comment (woshilapin) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: In general, I believe we don't think about the problem the right way. We should not focus about extension of the file since it's not relevant at all. We should think about the content of the file. I could totally provide a file `railjson_infra` (without extension) or `infra.js` (JSON is a subset of Javascript I believe 🤔) or even `infra.txt` for that matters, and all these files would contain valid RailJSON.

> @woshilapin, you're right that accept="json,railjson" helps guide the user. But it's not a strong restriction as users can still select a .txt or other file type. So we can't rely on it alone.

Yes, I know we can't rely on it, but we don't need to. A user that deviates from that probably know what he's doing, or at least, expect some more problems down the line, don't you think? And also, if we improve the error message, then debugging the situation for that hypothetical user who send the wrong file will necessarily improve. It's technically not a problem to send a file with `.txt` extension (or no extension for that matter). It's only a problem if the file doesn't contain RailJSON format.

> So here’s what I suggest:
> - Keep the check on the file name, but only as a UX help, not real validation.

I would really drop that part because it's incorrect, I can send a valid file with a different file extension.

> - Improve the error message as [@Synar suggested ](https://github.com/OpenRailAssociation/osrd/pull/11994/files#r2123787523)(e.g: "Only .json and .railjson files are allowed.")

Agreed about improving the message, but disagree about the proposed message. Again, we don't look for an extension, we look for a content. So better say something like "Only RailJSON files are allowed (usually .json or .railjson extensions)".

What do you think?

Comment (kmer2016) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: You're absolutely right: the important part is the content, not the file extension. A `.txt, .js,` or no-extension file can still contain valid RailJSON, and we shouldn't block that.

So let's remove the filename check entirely.

And to avoid confusion for users who might upload the wrong file by mistake, we can improve the error message shown when JSON parsing fails.
Something like:
"Invalid content. Only RailJSON files are supported (usually .json or .railjson extensions)."

This way, we stay focused on real content validation, while still helping users understand what’s expected.

Is that okay for you ?

**Review by woshilapin — APPROVED** [review]

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx (hunk 1 above)
Comment (woshilapin) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx]: Thank you everyone for bearing with me 😍

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx [hunk 3]
```diff
@@ -152,7 +148,7 @@ const InfraSelectorModalBodyEdition = ({
                   <span className="ml-2" title={selectedFile.name}>
                     {selectedFile.name}
                   </span>
-                  <input type="file" onChange={handleSelect} accept=".json" />
+                  <input type="file" onChange={handleSelect} accept=".json,.railjson" />
```
Comment (clarani) [inline front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyEdition.tsx:151]: I think the [accept](https://developer.mozilla.org/fr/docs/Web/HTML/Reference/Attributes/accept) is only used to help the navigator to display relevant files to upload (when I open my files explorer, only the .json and .railjson files are proposed), but it does not validate the uploaded files.
We should keep the validation in the `validateFile` function if we want to restrict the import to railjson and json files

**Review by clarani — COMMENTED** [review]
I can create a infra with a .txt file, is it a problem ?
[Capture vidéo du 2025-06-13 14-51-07.webm](https://github.com/user-attachments/assets/ff4239e4-8501-44f1-8b4d-3609b417aea4)

**Review by clarani — APPROVED** [review]
Ok, I've read the previous conversations and apparently, we stay focused on real content validation :white_check_mark: 

LGTM :white_check_mark:
