### PR TITLE
front: compute isTooFast on each scheduled steps interval

### LINKED ISSUE #13126: output table : no flame icon on some trains/paced trains
### What happened?

I imported this train and one can observe that there is a wrong margin from Lyon Part-Dieu but there is no flame icon on the train

### What did you expect to happen?

I expected a flame icon

### How can we reproduce it (as minimally and precisely as possible)?

Import this train and observe

[timetable (53).json](https://github.com/user-attachments/files/22233024/timetable.53.json)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

78d12da

### PR DESCRIPTION
**Pull request by Synar**
Close #13126

isTooFast used to check the final time at a scheduled step was too low compared to the provisional time at that step, computed from the start to that step.

This was not coherent with the warning indicators displayed in the timetable, as they computed the difference in margins from a scheduled step to the next.

Align isTooFast with the warnings in the table, and compute the time differences on each interval.

Also fix a typo in a comment (theorical -> theoretical).

### CODE REVIEW

File: front/src/applications/operationalStudies/utils.ts [hunk 1]
```diff
@@ -279,24 +280,38 @@ export const isTooFast = (
...
+  timetableItem.schedule?.forEach((schedule, i) => {
+    if (!i || schedule.arrival || marginBoundariesSet.has(schedule.at)) {
+      toCheckPathItemIds.push(schedule.at);
     }
   });
-  toCheckPathItemIds.add(timetableItem.path[timetableItem.path.length - 1].id);
-
-  if (toCheckPathItemIds.size === 0) return false;
+  const lastStepId = timetableItem.path[timetableItem.path.length - 1].id;
+  if (toCheckPathItemIds[toCheckPathItemIds.length - 1] != lastStepId)
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/utils.ts]:
```suggestion
  if (toCheckPathItemIds[toCheckPathItemIds.length - 1] !== lastStepId)
```

**Review by kmer2016 — APPROVED** [review]
LGTM! Very small suggestion about using `!==` instead `!=` just for consistency and to avoid implicit type [coercion](https://developer.mozilla.org/fr/docs/Glossary/Type_coercion).

File: front/src/applications/operationalStudies/utils.ts (hunk 1 above)
Comment (Synar) [reply front/src/applications/operationalStudies/utils.ts]: Thanks for the catch, this was a typo, I'll fix it!

**Comment by Synar** [comment]
Added a test for the new behavior ^^
