### PR TITLE
core: fix EoA and SvL computation for stops, spacing requirements and routing requirements on open/closed signals 

### LINKED ISSUE #12137: core: ETCS: finalize EoA and SvL computation
### Description and goal

Finalize EoA and SvL locations for all the cases:
- [x] spacing req:
  - [x] F: EoA = SvL = detector (= block transition)
  - [x] Nf: EoA = signal, SvL = detector
- [x] routing req (Nf):
  - [x] EoA = signal, SvL = danger point if one found in range [signal, signal + 200m], else on signal
- [x] stops:
  - [x] closed signal: IND - EoA = stop, SvL= danger point if one found in range [stop, stop + 200m], else on stop
  - [x] open signal: PS - EoA=stop, no SvL
- [x] curves:
  - [x] F: 1 curve set (min of curves): spacing (see above)
  - [x] Nf: 2 curve sets:
    - [x] spacing (see above) - modify output so front and editoast know its type
    - [x] routing (see above) - modify output so front and editoast know its type
  - [x] stop:
    - [x] closed signal (see above)
    - [x] open signal (see above)

### PR DESCRIPTION
**Pull request by Erashin**
For more details, see https://github.com/OpenRailAssociation/osrd/issues/12137.

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt [hunk 1]
```diff
@@ -126,9 +127,12 @@ class ETCSBrakingCurvesEndpoint(
                 etcsSignalBlockPathOffsets
                     .map { pathOffsetBuilder.toTravelledPath(it) }
                     .filter { it.distance > Distance.ZERO && it.distance <= chunkPath.length }
-            val etcsSignalStops =
-                etcsSignalOffsets.map { SimStop(it, RJSReceptionSignal.SHORT_SLIP_STOP) }
-            val etcsSignalEoas = etcsSimulator.computeEoaLocations(mrsp, etcsSignalStops)
+            val etcsSignalStops = etcsSignalOffsets.map { SimStop(it, RJSReceptionSignal.STOP) }
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt]: I think it's better to have a simple `STOP` here rather than a `SHORT_SLIP_STOP`. Doesn't change anything in terms of behavior.

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt [hunk 2]
```diff
@@ -67,11 +67,55 @@ fun buildETCSDangerPoints(
     return res.sorted()
 }
 
+/**
+ * Builds the list of ETCS detectors on the path. Goes until the last detector before the end of the
+ * path or, if the last block is ETCS, until the first ETCS detector after the end of the path.
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: If I understood the code correctly and the purpose matches the code (only exit detectors):
```suggestion
 * Builds the offset list of exit detectors for ETCS-blocks on the block-path. Goes until the last block-transition before the end of the
 * travelled-path or, if the last block is ETCS, until the first ETCS-block exit-detector after the end of the travelled-path.
```

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt [hunk 3]
```diff
@@ -67,11 +67,55 @@ fun buildETCSDangerPoints(
...
+ */
+fun buildETCSBlockDetectors(
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt:71]:
```suggestion
fun buildETCSBlockExitDetectors(
```

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt [hunk 4]
```diff
@@ -67,11 +67,55 @@ fun buildETCSDangerPoints(
...
+            .filter { it.distance > Distance.ZERO && it.distance <= chunkPath.length }
+            .toMutableList()
+    // If the last block of the path is ETCS, return its last detector, even if it's after the end
+    // of the path.
+    if (
+        res.isNotEmpty() &&
+            etcsBlockDetectorsPathOffsets.last().distance >= chunkPath.length &&
+            res.last().distance < chunkPath.length
+    )
+        res.add(etcsBlockDetectorsPathOffsets.first { it.distance >= chunkPath.length })
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: I don't get why filtering on the `chunkPath.length` (self-notice: which is equal to travelled-path length) is useful: the last block is part of the path, and we want its exit-detector if ETCS. Maybe I'm missing something, though.
I also think that it wouldn't be a problem to have multiple block-exits after the travelled-path, should it happen.

So it looks like we could simplify to:
```suggestion
    val res =
        etcsBlockDetectorsPathOffsets
            .filter { it.distance > Distance.ZERO }
            .toList()
```

Also, the current code will bug on a single-block path (full ETCS) as `res` would be empty when we want to add back the last detector, no?

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 5]
```diff
@@ -28,19 +29,44 @@ constructor(
          * *after* the end of the path (or right at the end).
          */
         val dangerPointOffsets: List<Offset<TravelledPath>>,
+        /**
+         * List of ETCS detector offsets on the path, up to the first detector *after* the end of
+         * the path (or right at the end).
+         */
+        val detectorOffsets: List<Offset<TravelledPath>>
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]:
```suggestion
         * List of ETCS-block exit-detector offsets on the path, up to the first detector *after* the end of
         * the path (or right at the end).
         */
        val exitDetectorOffsets: List<Offset<TravelledPath>>
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 6]
```diff
@@ -28,19 +29,44 @@ constructor(
...
+            closedSignalOffset: Offset<TravelledPath>
+        ): Offset<TravelledPath> {
+            val dangerPoint = getDangerPoint(closedSignalOffset)
+            return if (dangerPoint == null || dangerPoint - closedSignalOffset > 200.meters)
+                closedSignalOffset
+            else dangerPoint
+        }
+
+        /** Returns the next ETCS detector location. */
+        fun getNextDetector(offset: Offset<TravelledPath>): Offset<TravelledPath>? {
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt:60]:
```suggestion
        /** Returns the next ETCS-block exit-detector location. */
        fun getNextExitDetector(offset: Offset<TravelledPath>): Offset<TravelledPath>? {
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 7]
```diff
@@ -204,14 +217,14 @@ class ETCSBrakingSimulatorImpl(override val context: EnvelopeSimContext) : ETCSB
...
-        stops: Collection<SimStop>
+        stops: Collection<SimStop>,
+        eoaType: EoaType
     ): List<EndOfAuthority> {
         val etcsRanges = context.etcsContext?.applicationRanges ?: return listOf()
         val orderedStops = stops.sortedBy { it.offset }
         val endsOfAuthority = mutableListOf<EndOfAuthority>()
         for (stop in orderedStops) {
             var stopOffset = stop.offset
-            if (stopOffset.distance == Distance.ZERO) continue
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt:214]: Why remove this line?

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 8]
```diff
@@ -62,9 +61,16 @@ interface ETCSBrakingSimulator {
...
+     * present in the envelope. Used to compute EoAs for:
+     * - stops
+     * - spacing requirement locations
+     * - routing requirement locations.
      */
-    fun computeEoaLocations(envelope: Envelope, stops: Collection<SimStop>): List<EndOfAuthority>
+    fun computeEoaLocations(
+        envelope: Envelope,
+        stops: Collection<SimStop>,
+        eoaType: EoaType = EoaType.STOP
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: nit: the code would be more readable without default value IMO (feel free to disregard).
At least I had to go check where it's used to see if it matched.

**Review by bougue-pe — COMMENTED** [review]
Only partial review, as discussed... Good luck for the refactor on F/Nf (instead of closed/open signals)😅

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 7 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt:214]: Redundant with `isBeginPos` check just below.

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 4 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: > I don't get why filtering on the chunkPath.length (self-notice: which is equal to travelled-path length) is useful: the last block is part of the path, and we want its exit-detector if ETCS. Maybe I'm missing something, though.
I also think that it wouldn't be a problem to have multiple block-exits after the travelled-path, should it happen.

I think there's a corner case where the path ends at the transition between the second to last block and the last block. In this case, we don't want the last block path detector. @eckter can you confirm?

> Also, the current code will bug on a single-block path (full ETCS) as res would be empty when we want to add back the last detector, no?

True. I should check `(res.isEmpty() && etcsBlockDetectorsPathOffsets.isNotEmpty()) || (etcsBlockDetectorsPathOffsets.last().distance >= chunkPath.length && res.last().distance < chunkPath.length)`.

See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/7af9ad6e3d7d9fe63a4f903a612488d5ae47b3fe for now, might change according to future comments.

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 2 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: Didn't exactly go for that, only used `-` when there could be a confusion, so at the end of the sentence.
See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/7af9ad6e3d7d9fe63a4f903a612488d5ae47b3fe.
Edit: couple of changes, due to the detectors not being only the exit detectors now.

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 3 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt:71]: ~See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/7af9ad6e3d7d9fe63a4f903a612488d5ae47b3fe.~
Edit: we have all the detectors, not just the exit ones. See https://github.com/OpenRailAssociation/osrd/commit/6fe5130924153b13a8503abce217e4dfdd333912

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 5 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: ~See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/7af9ad6e3d7d9fe63a4f903a612488d5ae47b3fe.~
Edit: we have all the detectors, not just the exit ones. See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/6fe5130924153b13a8503abce217e4dfdd333912

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 6 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt:60]: ~See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/7af9ad6e3d7d9fe63a4f903a612488d5ae47b3fe.~
Edit: we have all the detectors, not just the exit ones. See https://github.com/OpenRailAssociation/osrd/commit/6fe5130924153b13a8503abce217e4dfdd333912

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 8 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Took it into account (trust :D)

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 4 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: Simplified the whole thing. We need the exit AND potentially entry detectors. So now i just return all of the etcs detectors as long as they are after the start of the path. See: https://github.com/OpenRailAssociation/osrd/pull/12457/commits/6fe5130924153b13a8503abce217e4dfdd333912

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 9]
```diff
@@ -28,19 +29,42 @@ constructor(
...
+         */
+        val detectorOffsets: List<Offset<TravelledPath>>
     ) {
         /**
-         * Returns the SVL location: next buffer stop or switch, whichever is closest. If there is
-         * any.
+         * Returns the next danger point location: next buffer stop or switch, whichever is closest.
+         * If there is any.
+         */
+        fun getDangerPoint(offset: Offset<TravelledPath>): Offset<TravelledPath>? {
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: Nit: is it meant to be eventually used outside the class? Otherwise it could be private

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 10]
```diff
@@ -28,19 +29,42 @@ constructor(
...
+            return dangerPointOffsets.firstOrNull { it >= offset }
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt:43]: Can it actually return null? From the documentation of `dangerPointOffsets` I'd expect it to always return something, unless the input is way beyond the end of the path

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 11]
```diff
@@ -28,19 +29,42 @@ constructor(
...
+        }
+
+        /**
+         * On a closed signal of for an interlocking signal, a danger point is always located less
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]:
```suggestion
         * On a closed signal or for an interlocking signal, a danger point is always located less
```

(not 100% sure I interpreted it right, but the current phrasing is wrong either way)

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 12]
```diff
@@ -62,9 +60,17 @@ interface ETCSBrakingSimulator {
 
     /**
      * Compute the ETCS EoAs, only for the stops which are inside an ETCS portion of the path
-     * present in the envelope.
+     * present in the envelope. Used to compute EoAs for:
+     * - stops (offset props are if the signal is OPEN or not)
+     * - spacing requirement locations (offset props are if the signals are interlocking or not)
+     * - routing requirement locations (offset props are if the signals are interlocking or not)
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: I don't really like that a single `List<Boolean>` can contain different values depending on the context. It sounds easy to mess up.

Would there be a way to have, say, different names parameters? Slightly less "efficient" but there's no ambiguity

Or if it's actually used in the exact same way and it doesn't actually matter, a comment could clear that up by explaining how it's used (and not where it's supposed to come from)

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 13]
```diff
@@ -92,21 +98,28 @@ data class LimitOfAuthority(
...
     override fun compareTo(other: EndOfAuthority): Int {
         if (offsetEOA != other.offsetEOA) return offsetEOA.compareTo(other.offsetEOA)
-        if (offsetSVL == null && other.offsetSVL == null) return 0
-        if (offsetSVL == null) return -1
-        if (other.offsetSVL == null) return 1
-        return offsetSVL.compareTo(other.offsetSVL)
+        return if (offsetSVL == other.offsetSVL) {
+            if (usedCurveType == other.usedCurveType && eoaType == other.eoaType) 0 else 1
+        } else if (offsetSVL == null) -1
+        else if (other.offsetSVL == null) 1 else offsetSVL.compareTo(other.offsetSVL)
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: These combined inlined `if` are a bit difficult to read, could they be broken down into some variables? Or maybe add `{}` to force them to be split into several lines

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 14]
```diff
@@ -239,22 +253,104 @@ class ETCSBrakingSimulatorImpl(override val context: EnvelopeSimContext) : ETCSB
...
+
+    /** Compute the EoA for a spacing conflict on a signal. */
+    private fun computeSpacingConflictEoa(
+        signalOffset: Offset<TravelledPath>,
+        isInterlocking: Boolean,
+        eoaType: EoaType,
+        endPos: Double
+    ): EndOfAuthority? {
+        assert(eoaType == EoaType.SPACING)
+        val nextDetector = this.context.etcsContext!!.getNextDetector(signalOffset)!!
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt:317]: The `!!` on next detector seems a bit optimistic. Is there no way it could be null? Like at signaling system transitions, or near a buffer stop?

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 15]
```diff
@@ -239,22 +253,104 @@ class ETCSBrakingSimulatorImpl(override val context: EnvelopeSimContext) : ETCSB
...
         return endsOfAuthority
     }
+
+    /** Compute the EoA for a simple stop. */
+    private fun computeStopEoA(
+        stopOffset: Offset<TravelledPath>,
+        isStopOnClosedSignal: Boolean,
+        eoaType: EoaType
+    ): EndOfAuthority {
+        assert(eoaType == EoaType.STOP)
```
Comment (eckter) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Nit: it feels a bit weird to do pattern matching on the enum, then passing that enum as parameter, just to assert that it's a given value. We could not input it at all there.

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt [hunk 16]
```diff
@@ -67,11 +67,44 @@ fun buildETCSDangerPoints(
...
+            currentOffset += infra.blockInfra.getBlockLength(block).distance
+            // Add exit detector
+            etcsBlockDetectors.add(currentOffset)
+        }
+    }
+    val pathOffsetBuilder =
+        PathOffsetBuilder(
+            trainPathBlockOffset(infra.rawInfra, infra.blockInfra, blockPath, chunkPath).distance
+        )
+    if (etcsBlockDetectors.isEmpty()) return mutableListOf()
```
Comment (eckter) [inline core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]:
```suggestion
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 9 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: I was thinking it could be eventually used outside of the class, but ETCS won't move for a while, so might as well put it in private.
Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/e3ca3fe9ad1ab72dbdb4807beea8957011852d32.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 10 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt:43]: Theoretically no. But there might be a corner case where it does return null. The good thing is that `getMandatoryDangerPoint` manages the null case and is the method used and the only one which will be public.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 12 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Actually yeah, I could just clear it up and say OPEN = F and CLOSED = isInterlocking (Nf) in terms of behavior. And therefore keep one List<Boolean>. Which I could just name `areSignalsRestrictive`.
Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/e3ca3fe9ad1ab72dbdb4807beea8957011852d32.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 14 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt:317]: An ETCS signal is on an ETCS block, and we have the entry and exit detectors of all the blocks on which the train goes through. We should be good :)

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 16 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt]: Right we don't need that anymore with my last prev change.
Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/0afd3d83b1b0a81e2f91450df4c1b04445148416.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 17]
```diff
@@ -28,19 +29,42 @@ constructor(
          * *after* the end of the path (or right at the end).
          */
         val dangerPointOffsets: List<Offset<TravelledPath>>,
+        /**
+         * List of ETCS-block detector offsets for every block on the path. Starts at the start of
+         * the path, can end after the end of the path.
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: Currently we don't have any data with ETCS detectors detached from signal, but we wouldn't consider them, and it's the desired behavior, so I would explicit it a bit more:
```suggestion
         * List of block-delimiting detector (block entry/exit) offsets for every ETCS-block on the path. Starts at the start of
         * the path, can end after the end of the path.
```

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt [hunk 18]
```diff
@@ -67,11 +67,44 @@ fun buildETCSDangerPoints(
     return res.sorted()
 }
 
+/** Builds the offset list of detectors for ETCS blocks on the block path. */
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt:70]:
```suggestion
/** Builds the offset list of delimiting (block entry/exit) detectors for ETCS blocks on the block path. */
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 11 above)
Comment (bougue-pe) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]:
```suggestion
         * On a closed signal stop or for an interlocking signal, a danger point is always located less
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt [hunk 19]
```diff
@@ -28,19 +29,42 @@ constructor(
...
+        fun getDangerPoint(offset: Offset<TravelledPath>): Offset<TravelledPath>? {
+            return dangerPointOffsets.firstOrNull { it >= offset }
+        }
+
+        /**
+         * On a closed signal of for an interlocking signal, a danger point is always located less
+         * than 200m away. This method returns the next danger point location if it is less than
+         * 200m away. If there isn't any, we're probably missing a danger point in the
+         * infrastructure, hence we'll be conservative and place the danger point on the closed
+         * signal.
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: Not sure it's the best phrasing, but on top and bottom parts of the comment we're currently missing the fact that for a closed-signal stop, EoA is at the stop's location, not the signal:
```suggestion
         * infrastructure, hence we'll be conservative and place the danger point on the EoA (stop location or signal)
```

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 12 above)
Comment (bougue-pe) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: They are not used the same way and I'm also not fan of using the same pipe to convey different meanings (depending on the other params).

How about "extracting" the top (common) part of `computeEoaLocations`, and rename it `filterEtcsLocations(envelope, offsets): List<Offset<TravelledPath>>` ?
This way, on each call-site, offsets are first filtered/epsilon-moved based on the envelope and ETCS-ranges, and only after that we apply the dedicated function for each case.

It would also remove the need for `EoaType`, AFAIU.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 20]
```diff
@@ -239,22 +253,104 @@ class ETCSBrakingSimulatorImpl(override val context: EnvelopeSimContext) : ETCSB
...
+    }
+
+    /** Compute the EoA for a spacing conflict on a signal. */
+    private fun computeSpacingConflictEoa(
+        signalOffset: Offset<TravelledPath>,
+        isInterlocking: Boolean,
+        eoaType: EoaType,
+        endPos: Double
+    ): EndOfAuthority? {
+        assert(eoaType == EoaType.SPACING)
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Same remark for the pattern-matching here (and in routing): not inputing `eoaType` looks better IMO.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt (hunk 11 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/EnvelopeSimContext.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/e3ca3fe9ad1ab72dbdb4807beea8957011852d32.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 13 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/e3ca3fe9ad1ab72dbdb4807beea8957011852d32.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 15 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/12457/commits/e3ca3fe9ad1ab72dbdb4807beea8957011852d32.

File: core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt [hunk 21]
```diff
@@ -112,38 +109,98 @@ class ETCSBrakingCurvesEndpoint(
...
-                    signalBrakingCurves.map { buildETCSCurves(it.value) }
+                    conflictBrakingCurves.map { buildETCSCurves(it.value) }
                 )
             RsJson(RsWithBody(etcsBrakingCurvesResponseAdapter.toJson(res)))
         } catch (ex: Throwable) {
             ExceptionHandler.handle(ex)
         }
     }
 
+    private data class InterlockingSignal(
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt]: The current name is misleading IMO: suggesting `TravelledPathSignal`, as `PathSignal` already exists (Not sure that `EtcsPathSignal` would be better).

File: core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt [hunk 22]
```diff
@@ -112,38 +109,98 @@ class ETCSBrakingCurvesEndpoint(
...
+        val offset: Offset<TravelledPath>,
+        val isInterlocking: Boolean
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt]: As discussed, `isRouteDelimiter` is closer to existing code, so I would stick to that if possible (and maybe switch all naming later if we think it's better).

Please ctrl+F `interlocking` in the PR's changes to locate the ~12 cases 🙏

File: core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt [hunk 23]
```diff
@@ -112,38 +109,98 @@ class ETCSBrakingCurvesEndpoint(
...
+        override fun compareTo(other: InterlockingSignal): Int {
+            return offset.compareTo(other.offset)
+        }
+    }
+
+    /**
+     * Returns the sorted list of unique signals on the block path, corresponding to the signaling
+     * system if specified.
+     */
+    private fun getInterlockingSignals(
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/api/etcs/ETCSBrakingCurvesEndpoint.kt]: The name mislead me at first, I'd much prefer `getPathSignals`.

Also, just to be sure: this function would still be better where it was (in `LoadedSignalingInfra`, or even `BlockInfra`) but it's there only to avoid circular deps, right?

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 20 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: Already done :)

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 12 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: I'd still need EoaType to differentiate Eoas in the ETCS endpoint. Personnally don't think it's necessary, as discussed with @bougue-pe, because the renaming/comments already helps. If it's also good for you @eckter, I would keep it likeso.

**Review by eckter — APPROVED** [review]
Nice :+1: 

I agree with PE's comments, but other than that LGTM

File: core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt (hunk 18 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/standalone_sim/etcsContextBuilder.kt:70]: Already changed it to something else, showed you, it's fine as is, I'll ignore this change.

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt [hunk 24]
```diff
@@ -92,21 +102,37 @@ data class LimitOfAuthority(
...
+            } else {
+                1
+            }
+        } else if (offsetSVL == null) {
+            -1
+        } else if (other.offsetSVL == null) {
+            1
+        } else {
+            offsetSVL.compareTo(other.offsetSVL)
+        }
```
Comment (bougue-pe) [inline core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: The comparison is not commutative on `usedCurveType` and `eoaType` (depending if an EndOfAuthority is `this` or `other`):
```suggestion
        if (offsetSVL != other.offsetSVL) {
            if (offsetSVL == null) return -1
            if (other.offsetSVL == null) return 1
            return offsetSVL.compareTo(other.offsetSVL)
        }
        if (usedCurveType != other.usedCurveType) {
            return usedCurveType.compareTo(other.usedCurveType)
        }
        if (eoaType != other.eoaType) {
            return eoaType.compareTo(other.eoaType)
        }
        return 0
```

File: tests/tests/test_train_schedule.py [hunk 25]
```diff
@@ -213,29 +213,29 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
             prev_speed = current_speed
 
     # Check that the uphill brake is shorter than downhill brake.
-    offset_42_ms_brake_uphill = 19_332_051  # first stop is the end of the braking
+    offset_43_ms_brake_uphill = 20_084_083  # first stop is the end of the braking
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]:
```suggestion
    offset_37_mps_brake_uphill = 20_084_083  # first stop is the end of the braking
```

File: tests/tests/test_train_schedule.py [hunk 26]
```diff
@@ -213,29 +213,29 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
...
-                simulation_final_output, offset_42_ms_brake_uphill
+                simulation_final_output, offset_43_ms_brake_uphill
             )
-            - 42
+            - 37
         )
         < 1
     )
-    offset_42_ms_brake_downhill = 27_318_065  # third stop is the end of the braking
+    offset_43_ms_brake_downhill = 28_007_977  # third stop is the end of the braking
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]:
```suggestion
    offset_37_mps_brake_downhill = 28_007_977  # third stop is the end of the braking
```

File: tests/tests/test_train_schedule.py [hunk 27]
```diff
@@ -213,29 +213,29 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
...
+            - 37
         )
         < 1
     )
-    uphill_brake_distance = first_stop_offset - offset_42_ms_brake_uphill
-    downhill_brake_distance = third_stop_offset - offset_42_ms_brake_downhill
-    # make sure that there is at least 100m difference
+    uphill_brake_distance = first_stop_offset - offset_43_ms_brake_uphill
+    downhill_brake_distance = third_stop_offset - offset_43_ms_brake_downhill
+    # make sure that there is at least 70m difference
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]: The comment doesn't match the code 😉

File: core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt (hunk 24 above)
Comment (Erashin) [reply core/envelope-sim/src/main/kotlin/fr/sncf/osrd/envelope_sim/etcs/ETCSBrakingSimulator.kt]: See https://github.com/OpenRailAssociation/osrd/pull/12457/commits/6b8514ecf10e50ab422b409add7975308214ef98

File: tests/tests/test_train_schedule.py [hunk 28]
```diff
@@ -1076,7 +1076,7 @@ def test_etcs_schedule_result_slowdowns_with_stop(
 
     # Strict deceleration to the intermediate stop
     for i in range(start_index + 1, intermediate_index):
-        assert speeds[i] < speeds[i - 1], (
+        assert speeds[i] <= speeds[i - 1], (
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]: I guess this changed because of the release speed, but the point was to check that there is no constant speed part from the safety-speed (VISA).
Maybe check that if constant it's =~40km/h ?

File: tests/tests/test_train_schedule.py [hunk 29]
```diff
@@ -245,34 +245,34 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
...
-    offset_fourth_high_speed = 37_560_933
-    offset_fourth_brake_220_kph_speed = 37_819_833
+    offset_fourth_high_speed = 37_087_326
+    offset_fourth_brake_220_kph_speed = 38_045_352
     _assert_equal_speeds(
         _get_current_or_next_speed_at(
             simulation_final_output, offset_fourth_high_speed
         ),
-        kph2ms(221.94),
+        kph2ms(230.97),
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py:272]: Not sure about the values (and even more the previous ones...), but the target is to check start of the braking curve and switch in GUI at 220 km/h.
The simplifications may explain it though.

File: tests/tests/test_train_schedule.py [hunk 30]
```diff
@@ -1182,16 +1182,16 @@ def test_etcs_spacing_req(
...
     # zone entry DH1_2 (triggered by SH1_2)
     spacing_req_zone_final = simulation_final_output["spacing_requirements"][36]
     assert (
         spacing_req_zone_final["zone"]
         == "zone.[DH1_2:INCREASING, buffer_stop.7:DECREASING]"
     )
-    assert spacing_req_zone_final["begin_time"] == 892060
-    assert spacing_req_zone_final["end_time"] == 1035083
+    assert spacing_req_zone_final["begin_time"] == 899826
+    assert spacing_req_zone_final["end_time"] == 1042849
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py:1197]: Losing 7.766s at all check: the only logical explanation I have about it is the SvL being changed on closed signal.
(just noting it)

File: tests/tests/test_train_schedule.py [hunk 31]
```diff
@@ -1253,7 +1253,7 @@ def test_etcs_schedule_braking_curves_endpoint(
     ]
     start_braking_curves_offsets = [
         [21_467_192, MAX_SPEED_288],
-        [40_663_497, SPEED_LIMIT_142],
+        [34_638_530, MAX_SPEED_288],
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]: I don't get this change quickly.

**Review by bougue-pe — APPROVED** [review]
From the code, LGTM.
Tests only softly challenged, as discussed 🙏

File: tests/tests/test_train_schedule.py (hunk 31 above)
Comment (Erashin) [reply tests/tests/test_train_schedule.py]: With the new stop locations, the svl impacts the braking curve and it skips the train's max envelope curve at 142km/h and intersects with it earlier on the path and higher in the speed limit, at 288km/h.

File: tests/tests/test_train_schedule.py (hunk 29 above)
Comment (Erashin) [reply tests/tests/test_train_schedule.py:272]: Yeh that's what I did. 230 is the highest speed here, and 207 is the first speed below 220 (the previous one is like 221 or something, close but no cigar).

File: tests/tests/test_train_schedule.py (hunk 28 above)
Comment (Erashin) [reply tests/tests/test_train_schedule.py]: Ohhhh good idea. Way better than just sort of hiding it with the `<=`. I'll do that.

File: tests/tests/test_train_schedule.py [hunk 32]
```diff
@@ -245,34 +245,34 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
     #   dodges this limit and starts under "high" MRSP (288 km/h), and the guidance curve change at 220 km/h is also
     #   noticeable.
     # In practice, check noticeable points of the braking curves (with the stops already checked)
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]:
```suggestion
    # In practice, check noticeable points of the braking curves (with the stops already checked):
    # - check high-speed point
    # - check the point closest to the bending-point at 220 km/h (can be above of under: only the "shape" of the curve matters)
    # - stop is already checked
```

File: tests/tests/test_train_schedule.py [hunk 33]
```diff
@@ -245,34 +245,34 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
...
             simulation_final_output, offset_bending_guidance_point_first_brake
         ),
-        kph2ms(217.970),
+        kph2ms(217.971),
     )
 
-    offset_fourth_high_speed = 37_560_933
-    offset_fourth_brake_220_kph_speed = 37_819_833
+    offset_fourth_high_speed = 37_087_326
+    offset_fourth_brake_220_kph_speed = 38_045_352
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]:
```suggestion
    offset_fourth_brake_220_kph_speed = 37_590_127
```

File: tests/tests/test_train_schedule.py [hunk 34]
```diff
@@ -245,34 +245,34 @@ def test_etcs_schedule_stop_brakes_result_never_reach_mrsp(
...
         ),
-        kph2ms(221.94),
+        kph2ms(230.97),
     )
     _assert_equal_speeds(
         _get_current_or_next_speed_at(
             simulation_final_output, offset_fourth_brake_220_kph_speed
         ),
-        kph2ms(215.7),
+        kph2ms(207.67),
```
Comment (bougue-pe) [inline tests/tests/test_train_schedule.py]:
```suggestion
        kph2ms(220.92),
```

File: tests/tests/test_train_schedule.py (hunk 29 above)
Comment (bougue-pe) [reply tests/tests/test_train_schedule.py:272]: OK, I checked it and suggested 3 changes to comment the "spirit" of the test and stay closer to original idea.
The comment would actually matter more than value, though.

File: tests/tests/test_train_schedule.py (hunk 31 above)
Comment (bougue-pe) [reply tests/tests/test_train_schedule.py]: Oh, this is actually an interesting case now: the brake curve is hitting the LoA maintain-speed, but the information curve doesn't.
This is what we could expect from specifications and it looks OK.
But if we ever want to evolve specifications and "integrate LoA maintain-speed to MRSP when computing info-curves", it would be alright to have it change too (and we would have the test for this).

So I would note it:
```suggestion
        [34_638_530, MAX_SPEED_288], # hitting the LoA maintain-speed, but not the actual MRSP
```

**Review by bougue-pe — APPROVED** [review]
Confirm that the tests do look fine 👍 
Thanks for this work !

File: tests/tests/test_train_schedule.py (hunk 32 above)
Comment (Erashin) [reply tests/tests/test_train_schedule.py]: Modified tidbits (stop part was redundant in the parenthesis)
