### PR TITLE
ui-charts: fix max zoom offset

### LINKED ISSUE #11343: front: when zooming with the rect zoom at max level, get is not centered
### What happened?

Remaining AC of https://github.com/osrd-project/osrd-confidential/issues/528

If the selected area corresponds to a zoom level greater than the permitted zoom, it is zoomed to the maximum permitted and centred on the selected area.

### What did you expect to happen?

If the selected area corresponds to a zoom level greater than the permitted zoom, then the chart is not centered on the selected area

### How can we reproduce it (as minimally and precisely as possible)?

1. Zoom on a very small version of the GET

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by anisometropie**
fixes #11343

### CODE REVIEW

**Review by achrafmohye — APPROVED** [review]
LGTM and tested, thanks for the PR :)

File: front/ui/ui-charts/src/spaceTimeChart/utils/scales.ts [hunk 1]
```diff
@@ -284,3 +285,75 @@ export function getSpaceBreakpoints(from: number, to: number, tree: NormalizedSc
...
+    chartSpaceSizePx
+  );
+  if (!swapAxes) {
+    const xOffset = timeOffset;
+    const yOffset = spaceOffset;
+    return { xOffset, yOffset };
+  }
+  const xOffset = spaceOffset;
+  const yOffset = timeOffset;
+  return { xOffset, yOffset };
```
Comment (clarani) [inline front/ui/ui-charts/src/spaceTimeChart/utils/scales.ts]: nit
```suggestion
  return !swapAxes
    ? { xOffset: timeOffset, yOffset: spaceOffset }
    : { xOffset: spaceOffset, yOffset: timeOffset };
```

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx [hunk 2]
```diff
@@ -204,8 +214,20 @@ const useManchetteWithSpaceTimeChart = ({
...
+              newYOffset = Math.abs(
+                sideOffset(
+                  spaceOrigin,
+                  newSpaceScale,
+                  prev.rect.spaceStart,
+                  prev.rect.spaceEnd,
+                  height
+                )
+              );
+            }
```
Comment (clarani) [inline front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: Why not directly use sideOffset ?
```suggestion
            newYOffset = Math.abs(
              sideOffset(
                spaceOrigin,
                newSpaceScale,
                prev.rect.spaceStart,
                prev.rect.spaceEnd,
                height
              )
            );
```

File: front/ui/ui-charts/src/spaceTimeChart/utils/scales.ts (hunk 1 above)
Comment (anisometropie) [reply front/ui/ui-charts/src/spaceTimeChart/utils/scales.ts]: done

File: front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx (hunk 2 above)
Comment (anisometropie) [reply front/ui/ui-charts/src/manchette/hooks/useManchetteWithSpaceTimeChart.tsx]: I had to adapt the sideOffset computation a bit with the padding, but i made the change

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

Do you want to add a commit to fix the bug in OSRD now or can we do this later ?

**Review by clarani — APPROVED** [review]
My bad, it works even on OSRD ! Thanks :pray:
