### PR TITLE
editoast: handle out_of_range error with auto-fix for level crossings and operational points

### LINKED ISSUE #14815: Handle out_of_range error with  🪄
### Who would benefit from this feature?

End users

### What is this feature about?

Out_of_range errors cannot be fixed automatically like other errors for operational points and level crossings.
We want to handle this type of error as well.

### Why is this feature valuable?

Enable the fix of infras.

### Anything else people should know?

_No response_

### PR DESCRIPTION
**Pull request by aschantraine**
Enables fixing `out_of_range` errors in infras with auto-fix:

- Extends the `InfraErrorType::OutOfRange` variant to include a new `reference` field
- Updates level crossings parts position that are out of range with auto-fix
- Updates operational points parts position that are out of range with auto-fix

The interaction between `InvalidRef` and `OutOfRange` errors for level crossings will be fixed in [another PR](https://github.com/OpenRailAssociation/osrd/issues/14854)

### CODE REVIEW

**Review by Wadjetz — APPROVED** [review]
lgtm, tested

File: editoast/src/views/infra/auto_fixes/level_crossing.rs [hunk 1]
```diff
@@ -41,12 +41,13 @@ pub fn fix_level_crossing(
         .filter_map(|infra_error| match infra_error.get_sub_type() {
             InfraErrorType::EmptyObject => Some(OrderedOperation::Delete),
             InfraErrorType::InvalidReference { reference }
+            | InfraErrorType::OutOfRange { reference, .. }
```
Comment (flomonster) [inline editoast/src/views/infra/auto_fixes/level_crossing.rs]: We should not remove the part but move it. 
- In case of invalid ref we don't have choice, the part must be removed
- In case of out of range we can modify the position of the object to clamp it between `[0, track_length]`.

**Review by flomonster — CHANGES_REQUESTED** [review]
Thanks for you PR.

File: editoast/src/views/infra/auto_fixes/level_crossing.rs (hunk 1 above)
Comment (aschantraine) [reply editoast/src/views/infra/auto_fixes/level_crossing.rs]: So we set the position to track_length when it is out of range ?

Comment (flomonster) [reply editoast/src/views/infra/auto_fixes/level_crossing.rs]: As discussed, we have to clamp it: `position.clamp(0, track.length)`.
If position is `u64` we can simply update the position with `track.length` value.

**Review by Wadjetz — APPROVED** [review]

**Review by flomonster — APPROVED** [review]
LGTM
