### PR TITLE
Set editoast `serde_qs` to non strict for simulation summary endpoint

### LINKED ISSUE #7481: editoast: fail using simulation_summary endpoint with python requests
### What happened?

When i call the simulation_summary endpoint using python requests library, i got the following error : 
```
>>> response = requests.get("http://localhost:8090/v2/train_schedule/simulation_summary/?infra=4&ids[]=1&ids[]=2")
>>> response.content
b'Multiple values for one key: "ids%5B%5D"\nInvalid field contains an encoded bracket -- did you mean to use non-strict mode?\n  https://docs.rs/serde_qs/latest/serde_qs/#strict-vs-non-strict-modes'
>>> response.raise_for_status()
HTTPError: 400 Client Error: Bad Request for url: http://localhost:8090/v2/train_schedule/simulation_summary/?infra=4&ids%5B%5D=1&ids%5B%5D=2
```
It's because requests encode `[]` into `%5B%5D`

### What did you expect to happen?

I should not get an error as the given url `http://localhost:8090/v2/train_schedule/simulation_summary/?infra=4&ids[]=1&ids[]=2` works in my browser

Same with `http://localhost:4000/api/v2/train_schedule/simulation_summary/?infra=4&ids[]=1&ids[]=2`

### How can we reproduce it (as minimally and precisely as possible)?

using the commands above (editoast should be running)

### What operating system, browser and environment are you using?

- **Browser**: Chrome version 124.0.6367.202
- **OS**: WSL
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev ad08ba1

### PR DESCRIPTION
**Pull request by flomonster**
close #7481

> [!NOTE]
> Soon we'll be adapting some TS2 endpoints by moving the query parameters into the request body.

### CODE REVIEW

**Review by nicolaswurtz — APPROVED** [review]

File: editoast/src/views/v2/train_schedule.rs [hunk 1]
```diff
@@ -527,10 +532,17 @@ enum SimulationSummaryResult {
 pub async fn simulation_summary(
     db_pool: Data<DbConnectionPool>,
     redis_client: Data<RedisClient>,
-    params: QsQuery<SimulationBatchParams>,
+    req: HttpRequest,
     core: Data<CoreClient>,
 ) -> Result<Json<HashMap<i64, SimulationSummaryResult>>> {
-    let query_props = params.into_inner();
+    // TODO: Stop using serde_qs and move the query params to the body
```
Comment (leovalais) [inline editoast/src/views/v2/train_schedule.rs:538]: We could also make our own extractor that parses in a non-strict mode and keep the same url scheme and serde_qs. But since I recall there was problems with the openapi as well, it's probably a good idea.

**Review by leovalais — APPROVED** [review]
