### PR TITLE
front: fix power restriction selector when rs does not handle electrification mode

### LINKED ISSUE #7157: Error in simulation parameters for rolling stock with power restrictions
### What happened?

When adding/updating a train which rollingstock has power restriction codes, if this train runs on a path which electrification is not supported by its rolling stock, it throws an error.

image

### What did you expect to happen?

No error should appear

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Add a train with a B81500 bimode and a BEH - SAD path with rocket 
3. Try to go to simulation parameters

### What operating system, browser and environment are you using?

- **Browser**: Firefox v123
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 9e784bf

### PR DESCRIPTION
**Pull request by clarani**
closes #7157 

I modified the behaviour of the power restriction selector to handle bimode trains:
- if a mode is not supported by a rs and no power restriction code is selected => no warning
- if a mode is not supported by a rs and a power restriction code is selected => show a warning explaining that the rs does not handle the electrification mode

I also adapted the electrification displayed below the intervals editor.

image

### CODE REVIEW

File: front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+export const countWarnings = (warnings?: PowerRestrictionWarnings): number => {
+  if (!warnings) return 0;
+  const { invalidCombinationWarnings, modeNotSupportedWarnings, missingPowerRestrictionWarnings } =
+    warnings;
+  return (
+    invalidCombinationWarnings.length +
+    modeNotSupportedWarnings.length +
+    missingPowerRestrictionWarnings.length
+  );
+};
```
Comment (Math-R) [inline front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts]:
```
export const countWarnings = (warnings: PowerRestrictionWarnings = { 
  invalidCombinationWarnings: [], 
  modeNotSupportedWarnings: [], 
  missingPowerRestrictionWarnings: [] 
}): number => {
  const { invalidCombinationWarnings, modeNotSupportedWarnings, missingPowerRestrictionWarnings } = warnings;
  return invalidCombinationWarnings.length + modeNotSupportedWarnings.length + missingPowerRestrictionWarnings.length;
};
```

this would be the same and it allow to skip the if check

File: front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+export const getPowerRestrictionsWarnings = (
+  powerRestrictionRanges: RangedValue[],
+  pathElectrificationRanges: RangedValue[],
+  rollingStockModes: RollingStock['effort_curves']['modes']
+): PowerRestrictionWarnings => {
+  const powerRestrictionsByMode = getRollingStockPowerRestrictionsByMode(rollingStockModes);
+  const invalidCombinationWarnings: PowerRestrictionWarnings['invalidCombinationWarnings'] = [];
+  const modeNotSupportedWarnings: PowerRestrictionWarnings['modeNotSupportedWarnings'] = [];
+  const missingPowerRestrictionWarnings: PowerRestrictionWarnings['missingPowerRestrictionWarnings'] =
+    [];
```
Comment (Math-R) [inline front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts]:
```
const powerRestrictionsByMode = getRollingStockPowerRestrictionsByMode(rollingStockModes);
  const warnings: PowerRestrictionWarnings = {
    invalidCombinationWarnings: [],
    modeNotSupportedWarnings: [],
    missingPowerRestrictionWarnings: []
  };
```

il would go for something like this to avoid repetition

File: front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts (hunk 1 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts:96]: Done, it's clearer, thanks :pray:

Comment (clarani) [reply front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts]: I prefer to keep the condition, I think it's more readable than the default value. But it's only a personal preference, is it ok for you ?

File: front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts (hunk 2 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts]: Done, it's clearer, thanks :pray:

File: front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts (hunk 1 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/powerRestrictionWarnings.ts]: Done

**Review by Math-R — APPROVED** [review]
