### PR TITLE
Front: fix stdcm config crash when changing scenario in stdcm debug

### LINKED ISSUE #10973: stdcm: crash when selecting scenario in debug "STDCM conf is not valid"
### What happened?

When I try to select a scenario in STDCM debug mode, it crashes

https://github.com/user-attachments/assets/64df9cc7-3448-474c-9f35-23640bf89cbd

### What did you expect to happen?

not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. video

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by clarani**
closes #10973

Thanks to the first commit, from now on, if a user selects an empty timetable in STDCM, then he will be able to request a train with a departure within the current day.

### CODE REVIEW

File: front/src/modules/scenario/components/ScenarioExplorer/ScenarioExplorer.tsx [hunk 1]
```diff
@@ -89,7 +89,7 @@ const ScenarioExplorer = ({
         })
       );
     }
-  }, [scenario, timetable]);
+  }, [timetable]);
```
Comment (SharglutDev) [inline front/src/modules/scenario/components/ScenarioExplorer/ScenarioExplorer.tsx]: Hmm if we remove `scenario` from the depths, if we switch from a scenario to another, stdcm env won't be updated with the good values no ?

File: front/src/applications/stdcm/views/StdcmView.tsx [hunk 2]
```diff
@@ -266,20 +254,41 @@ const StdcmView = () => {
...
+        <StdcmHeader
+          isDebugMode={isDebugMode}
+          onDebugModeToggle={setIsDebugMode}
+          toggleHelpModule={toggleHelpModule}
+          showHelpModule={showHelpModule}
+        />
+        <LoaderFill />
+        <StdcmHelpModule showHelpModule={showHelpModule} toggleHelpModule={toggleHelpModule} />
+      </div>
+    );
```
Comment (SharglutDev) [inline front/src/applications/stdcm/views/StdcmView.tsx]: Same `StdcmHeader` and `StdcmHelpModule` are used twice here. Could we just have a function which render either `LoaderFill`, `StdcmEmptyConfigError` or `StdcmViewContent` depending on the conditions ?

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you !
