### PR TITLE
Restore margin highlighting in output table when negative diff margins

### LINKED ISSUE #12822: output table: lines with wrong margins are not highlighted anymore
### What happened?

The diff of margins is < 0 here, so the line should be highlighted but it is not

Image

### What did you expect to happen?

I expected the line to be highlighted when diff margin is <0 
Color : orange (warning30, opacity 50%)

### How can we reproduce it (as minimally and precisely as possible)?

Import this train on France :  [timetable (43).json](https://github.com/user-attachments/files/21758266/timetable.43.json) and observe the first line

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

4ed89f0

### PR DESCRIPTION
**Pull request by achrafmohye**
Closes #12822

### CODE REVIEW

**Review by RomainValls — APPROVED** [review]
Tested, LGTM

File: front/src/modules/timesStops/TimesStopsOutput.tsx [hunk 1]
```diff
@@ -52,7 +51,7 @@ const TimesStopsOutput = ({
             ? rowData.calculatedArrival !== rowData.arrival.time
             : false;
         const negativeDiffMargins =
-          rowData.diffMargins && Number(rowData.diffMargins?.split(NO_BREAK_SPACE)[0]) < 0;
+          rowData.diffMargins && Number(rowData.diffMargins?.split(' ')[0]) < 0;
```
Comment (kmer2016) [inline front/src/modules/timesStops/TimesStopsOutput.tsx]: I suggest using `parseInt` instead of` split(' ') + Number` because it directly extracts the integer at the start of the string and ignores any kind of whitespace (including non-breaking spaces). This makes the code simpler and more robust.

```suggestion
          rowData.diffMargins && parseInt(rowData.diffMargins) < 0;
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]

File: front/src/modules/timesStops/TimesStopsOutput.tsx (hunk 1 above)
Comment (achrafmohye) [reply front/src/modules/timesStops/TimesStopsOutput.tsx]: Done :)

**Review by kmer2016 — APPROVED** [review]
