### PR TITLE
front: fix crash when reopening scenario with a projected occurence

### LINKED ISSUE #15945: White page on occurence projection
### What happened?

When projecting on an occurence, i got this white page after leaving then re-entering my scenario ⬇️ 

Image

### What did you expect to happen?

Not having a white page :) 

### How can we reproduce it (as minimally and precisely as possible)?

1. [Timetable to test](https://github.com/user-attachments/files/26265313/timetable.2.json)
2. Project on one of the paced train occurences
3. Leave and re-enter the scenario page

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

008b71a

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15945 

the `trainIdUsedForProjection` is coming from redux -> it was already there when opening the scenario
but the Map `timetableItemsById` wasn't ready yet, which caused the crash. 

now waiting to get the `pacedTrain` before trying to get the `ExceptionKey`. 
Also had to return `undefined` instead of throwing an error -> this I'm not sure if it could be handled in another way, or if it's ok to not throw an error.

### CODE REVIEW

File: front/src/modules/timetableItem/helpers/pacedTrain.ts [hunk 1]
```diff
@@ -159,8 +159,7 @@ export const getExceptionFromOccurrenceId = (
     extractPacedTrainIdFromOccurrenceId(occurrenceId)
   );
   const pacedTrain = timetableItemsById.get(pacedTrainId);
-  if (!pacedTrain || !isPacedTrain(pacedTrain))
-    throw new Error(`No paced train found for id ${pacedTrainId}`);
+  if (!pacedTrain || !isPacedTrain(pacedTrain)) return undefined;
```
Comment (emersion) [inline front/src/modules/timetableItem/helpers/pacedTrain.ts]: Can we keep the error for `!isPacedTrain(pacedTrain)` at least?

File: front/src/applications/operationalStudies/hooks/usePathProjection.ts [hunk 2]
```diff
@@ -118,10 +121,14 @@ const usePathProjection = (
     } else {
       const pacedTrainId = extractPacedTrainIdFromOccurrenceId(trainIdUsedForProjection);
       rawPacedTrainId = extractEditoastIdFromPacedTrainId(pacedTrainId);
-      exceptionKey = getExceptionFromOccurrenceId(
-        timetableItemsById,
-        trainIdUsedForProjection
-      )?.key;
+
+      const pacedTrain = timetableItemsById.get(rawPacedTrainId);
+      if (pacedTrain && isPacedTrain(pacedTrain)) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/usePathProjection.ts]: Do we really need this extra condition? Doesn't `getExceptionFromOccurrenceId()` already check this?

File: front/src/applications/operationalStudies/hooks/usePathProjection.ts [hunk 3]
```diff
@@ -118,10 +121,14 @@ const usePathProjection = (
...
+        exceptionKey = getExceptionFromOccurrenceId(
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/usePathProjection.ts]: Leaving this undefined will fetch data for paced train instead of the exception below, which is not what we want…

File: front/src/applications/operationalStudies/hooks/usePathProjection.ts (hunk 2 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/usePathProjection.ts]: Yes, did both for testing and forgot to remove this 👍

File: front/src/modules/timetableItem/helpers/pacedTrain.ts (hunk 1 above)
Comment (RomainValls) [reply front/src/modules/timetableItem/helpers/pacedTrain.ts]: Done 👍

**Review by emersion — APPROVED** [review]
