### PR TITLE
front: fix longitudinal curve in op studies

### LINKED ISSUE #4312: longitudinal section get out of frame
### What happened?

image

### What did you expect to happen?

The longitudinal section (red line) must stay in the frame 

### How can we reproduce it (as minimally and precisely as possible)?

Create a train and see the gradient, radius and longitudinal section frame

### What operating system, browser and environment are you using?

- **Browser**: Firefox v113
- **OS**: Ventura
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast 	 e5481800 Core 	 e5481800 API 	 e5481800 Front 	 e5481800

### PR DESCRIPTION
**Pull request by RomainValls**
Add one additional Y axis on the right of the chart
Red curve (speed slopes) now stays in the frame

closes #4312

### CODE REVIEW

File: front/src/modules/simulationResult/components/ChartHelpers/defineChartDoubleY.tsx [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+  const height = svgHeight - margin.top - margin.bottom;
+
+  // Container for easy removing
+  const svg = d3select(ref.current)
+    .append('div')
+    .attr('id', id)
+    .style('height', '100%')
+    .append('svg')
+    // .attr('width', width + margin.left + margin.right)
+    // .attr('height', height + margin.top + margin.bottom)
```
Comment (alexandredamiron) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChartDoubleY.tsx]: dead code

File: front/src/modules/simulationResult/components/SpaceCurvesSlopes.tsx [hunk 2]
```diff
@@ -55,6 +57,14 @@ const drawAxisTitle = (chart: Chart) => {
...
     .attr('y', chart.height - 10)
     .text('m');
+  chart.drawZone
+    .append('text')
+    .attr('class', 'axis-unit')
+    .attr('text-anchor', 'end')
+    .attr('transform', 'rotate(0)')
+    .attr('x', chart.width - 10)
+    .attr('y', chart.height - 100)
+    .text('TEST');
```
Comment (alexandredamiron) [inline front/src/modules/simulationResult/components/SpaceCurvesSlopes.tsx]: nowhere text ?

**Review by alexandredamiron — DISMISSED** [review]
Thank you for this request. I am not sure about the whole duplication of behavior logic. Could you expand the capabilities of defineChart and drawCurve instead ?

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 3]
```diff
@@ -77,6 +79,29 @@ const defineChart = (
   const yAxisGrid = svg.append('g').attr('class', 'grid').call(gridY(y, width));
   const originalScaleY = y; // We need to keep a ref on that to not double translation
 
+  // Add Y axis on the right
+  let y2;
+  let y2Axis;
+  let y2AxisGrid;
+  let originalScaleY2;
```
Comment (Yohh) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: can you type those variables?

**Review by Yohh — CHANGES_REQUESTED** [review]
very nice work!

one small issue:
curves start jump to zero when draging speedSpaceChart or slopesChart, maybe should you look to enableInteractivity

**Review by Yohh — APPROVED** [review]

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 4]
```diff
@@ -77,6 +80,33 @@ const defineChart = (
   const yAxisGrid = svg.append('g').attr('class', 'grid').call(gridY(y, width));
   const originalScaleY = y; // We need to keep a ref on that to not double translation
 
+  // Add Y axis on the right
+  let y2: SimulationD3Scale;
+  let y2Axis: d3.Selection<SVGGElement, unknown, null, undefined>;
+  let y2AxisGrid: d3.Selection<SVGGElement, unknown, null, undefined>;
+  let originalScaleY2: SimulationD3Scale;
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: No need for these variables, you can create them when you need them. The only one you need to instantiate outside of the if is the one you will reuse after the end of the if (here rightAxis) :) 
```suggestion
```

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 5]
```diff
@@ -77,6 +80,33 @@ const defineChart = (
...
+  let rightAxis;
+
+  if (defineY2) {
+    y2 = defineY2.range([height, 0]) as SimulationD3Scale;
+    const axisRightY = isSpaceSlopesCurves(keyValues) ? d3.axisRight(y2) : undefined;
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: You can move the condition ` isSpaceSlopesCurves(keyValues) ` line 90 and remove the 2nd if loop
-> `if (defineY2 && isSpaceSlopesCurves(keyValues) ) {...}`
```suggestion
    const axisRightY = d3.axisRight(y2);
```

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 6]
```diff
@@ -77,6 +80,33 @@ const defineChart = (
...
+    if (axisRightY) {
+      y2Axis = svg.append('g').attr('transform', `translate(${width}, 0)`).call(axisRightY);
+      y2AxisGrid = svg
+        .append('g')
+        .attr('class', 'grid')
+        .attr('transform', `translate(${width}, 0)`)
+        .call(gridY2(y2, width));
+      originalScaleY2 = y2;
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: You can set it directly line 105
```suggestion
```

File: front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts [hunk 7]
```diff
@@ -23,22 +23,41 @@ const drawCurve = <
   const xAxis = getAxis(keyValues, 'x', rotate);
   const yAxis = getAxis(keyValues, 'y', rotate);
 
+  const isHeight = yAxis === 'height';
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts]: I think this bool is more relevant, and then you can use it to change the class and the axis used in the drawZone function
```suggestion
  const onY2Axis = yAxis === 'height' && chart.y2;
```

File: front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts [hunk 8]
```diff
@@ -23,22 +23,41 @@ const drawCurve = <
...
+      .attr('stroke-width', 1)
+      .attr(
+        'd',
+        d3
+          .line<T>()
+          .x((d) => chart.x(d[xAxis as Key] as number))
+          .y((d) => chart.y(d[yAxis as Key] as number))
+          .curve(d3[interpolation as keyof d3.CurveFactory])
+      );
+  }
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/drawCurve.ts]:
```suggestion
  drawZone
    .append('path')
    .attr('class', `line zoomable ${onY2Axis && 'additional-y'} ${classes}`)
    .datum(dataSimulation)
    .attr('fill', 'none')
    .attr('stroke-width', 1)
    .attr(
      'd',
      d3
        .line<T>()
        .x((d) => chart.x(d[xAxis as keyof T] as number))
        .y((d) =>
          onY2Axis && chart.y2
            ? chart.y2(d[yAxis as keyof T] as number)
            : chart.y(d[yAxis as Key] as number)
        )
        .curve(d3[interpolation as keyof d3.CurveFactory])
    );
```

It's not very pretty because we have to test twice that chart.y2 exists, as typescript does not detect it alone, but at least it avoids code duplication and you can clearly see what changes between the 2 cases. You can also remove the second test chart.y2 and add a ! if you prefer (`chart.y2!(...)` line 43)

File: front/src/modules/simulationResult/components/ChartHelpers/drawPowerRestriction.ts
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/drawPowerRestriction.ts:1]: I feel like drawPowerRestriction and drawElectricalProfile have a lot of code in common. Maybe we can refacto them later

File: front/src/modules/simulationResult/components/SpaceTimeChart/createSpaceTimeChart.ts [hunk 9]
```diff
@@ -59,7 +61,8 @@ export default function createSpaceTimeChart<T extends number | Date>(
     ref,
     rotate,
     keyValues,
-    chartID
+    chartID,
+    defineY2
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpaceTimeChart/createSpaceTimeChart.ts]: I think spaceTimeChart does not need y2, so it should always be undefined
```suggestion
```

File: front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx [hunk 10]
```diff
@@ -179,18 +169,7 @@ export default function SpeedSpaceChart({
...
-      } else if (chart && setSharedXScaleDomain) {
-        setSharedXScaleDomain((prevState) => ({
-          ...prevState,
-          current: prevState.initial,
-          source: undefined,
-        }));
-      } else {
-        createChartAndTrain();
-      }
+      createChartAndTrain();
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx]: Be careful, you need to keep this, for the case you have zoomed in or out before clicking on reset ;)
```suggestion
       if (chart && setSharedXScaleDomain) {
        setSharedXScaleDomain((prevState) => ({
          ...prevState,
          current: prevState.initial,
          source: undefined,
        }));
      } else {
        createChartAndTrain();
      }
```

File: front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx [hunk 11]
```diff
@@ -237,7 +216,7 @@ export default function SpeedSpaceChart({
    */
   useEffect(() => {
     if (dateIsInRange(timePosition, timeScaleRange)) {
-      traceVerticalLine(chart, CHART_AXES.SPACE_SPEED, positionValues, rotate, timePosition);
+      traceVerticalLine(chart, CHART_AXES.SPACE_SPEED, positionValues, false, timePosition);
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx]: Can you change the order of the parameters of traceVerticalLine to put rotate as the last param and set it by default to false ? Then you can remove it like this. Don't forget to change the param order in the other places where traceVerticalLine is called
```suggestion
      traceVerticalLine(chart, CHART_AXES.SPACE_SPEED, positionValues, timePosition);
```

File: front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts [hunk 12]
```diff
@@ -66,50 +77,48 @@ function createChart(
...
+    .attr('x', chart.width - 10)
+    .attr('y', chart.height - 10)
     .text('M');
+  chart.drawZone
+    .append('text')
+    .attr('class', 'axis-unit')
+    .attr('text-anchor', 'end')
+    .attr('transform', 'rotate(0)')
+    .attr('x', chart.width - 10)
+    .attr('y', 20);
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts]: I think you forgot to remove this
```suggestion
```

File: front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts [hunk 13]
```diff
@@ -119,7 +128,7 @@ function drawTrain(
       'curveLinear',
       CHART_AXES.SPACE_SPEED,
       'speed',
-      rotate
+      false
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpeedSpaceChart/d3Helpers.ts]: Can you make the rotate parameter in drawCurve false by default ? Then you can remove it everywhere in this file
```suggestion
```

File: front/src/modules/simulationResult/components/simulationResultsConsts.ts [hunk 14]
```diff
@@ -21,6 +21,7 @@ export const CHART_AXES = {
 export type ChartAxes = ObjectFieldsTypes<typeof CHART_AXES>;
 export type XAxis = ChartAxes[0];
 export type YAxis = ChartAxes[1];
+export type Y2Axis = ChartAxes[1];
```
Comment (clarani) [inline front/src/modules/simulationResult/components/simulationResultsConsts.ts]: This would be more precise. We could also remove space_height from YAxis
```suggestion
export type Y2Axis = typeof CHART_AXES.SPACE_HEIGHT;
```

File: front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx [hunk 15]
```diff
@@ -118,13 +123,16 @@ const updateChart = <
           .axisLeft<Date>(newY as d3.ScaleTime<number, number>)
           .tickFormat(d3.timeFormat('%H:%M:%S'))
       : d3.axisLeft(newY);
+  const axisRightY = d3.axisRight(newY2 as d3.ScaleTime<number, number>);
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx]: Move this line below:
```suggestion
  if (chart.y2Axis) {
    const axisRightY = d3.axisRight(newY2 as d3.ScaleTime<number, number>);
    chart.y2Axis.call(axisRightY);
  }
```

File: front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx [hunk 16]
```diff
@@ -140,10 +148,28 @@ const updateChart = <
...
+      d3
+        .line<T>()
+        .x((d) => {
+          const key = supplementaryXAxis.find((axis) => d[axis as keyof T] !== undefined) || xAxis;
+          return newX(d[key as keyof T] as number | Date);
+        })
+        .y((d) => {
+          const key = supplementaryYAxis.find((axis) => d[axis as keyof T] !== undefined) || yAxis;
+          return newY2(d[key as keyof T] as number | Date);
+        })
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx]: I think you can even simplify it like this:
```suggestion
        .x((d) => newX(d[xAxis as keyof T]))
        .y((d) => newY2(d['height' as keyof T]))
```

File: front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx [hunk 17]
```diff
@@ -264,16 +290,24 @@ export const enableInteractivity = <
...
     .wheelDelta(wheelDelta)
+    // Allows evenements to be triggered on zoom and drag interactions for all graphs
     .on('zoom', (event) => {
       event.sourceEvent.preventDefault();
       const zoomFunctions = updateChart(chart, keyValues, additionalValues, rotate, event);
-      const newChart = { ...chart, x: zoomFunctions.newX, y: zoomFunctions.newY };
+      // Overide axis with new ones from updated chart
+      const newChart = {
+        ...chart,
+        x: zoomFunctions.newX,
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/enableInteractivity.tsx]: Do you think you can rename `zoomFunctions` ? I think the name is not very appropriate, maybe newAxis would be better ? zoomedAxis ? updatedAxis ?

**Review by clarani — CHANGES_REQUESTED** [review]
Almost there, great work !! :tada: I left some comments

Thanks for the comments on enableInteractivity, it's super clear now :)

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 18]
```diff
@@ -81,23 +81,19 @@ const defineChart = (
...
-  let originalScaleY2: SimulationD3Scale;
   let rightAxis;
 
-  if (defineY2) {
-    y2 = defineY2.range([height, 0]) as SimulationD3Scale;
-    const axisRightY = isSpaceSlopesCurves(keyValues) ? d3.axisRight(y2) : undefined;
+  if (defineY2 && isSpaceSlopesCurves(keyValues)) {
+    const y2 = defineY2.range([height, 0]) as SimulationD3Scale;
+    const axisRightY = d3.axisRight(y2);
     if (axisRightY) {
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: You don't need this test anymore since axisRightY is always defined
```suggestion
```

File: front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts [hunk 19]
```diff
@@ -81,23 +81,19 @@ const defineChart = (
...
-      y2Axis = svg.append('g').attr('transform', `translate(${width}, 0)`).call(axisRightY);
-      y2AxisGrid = svg
+      const y2Axis = svg.append('g').attr('transform', `translate(${width}, 0)`).call(axisRightY);
+      const y2AxisGrid = svg
         .append('g')
         .attr('class', 'grid')
         .attr('transform', `translate(${width}, 0)`)
         .call(gridY2(y2, width));
-      originalScaleY2 = y2;
+      const originalScaleY2 = y2;
```
Comment (clarani) [inline front/src/modules/simulationResult/components/ChartHelpers/defineChart.ts]: You can directly set it in rightAxis:
```
      rightAxis = {
        y2,
        y2Axis,
        y2AxisGrid,
        originalScaleY2: y2,
      };
```

```suggestion
```

File: front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx [hunk 20]
```diff
@@ -168,7 +168,13 @@ export default function SpeedSpaceChart({
...
    */
   useEffect(() => {
-    if (resetChart) {
+    if (chart && setSharedXScaleDomain) {
+      setSharedXScaleDomain((prevState) => ({
+        ...prevState,
+        current: prevState.initial,
+        source: undefined,
+      }));
+    } else {
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpeedSpaceChart/SpeedSpaceChart.tsx]: You also need to keep the if (resetChart)
```suggestion
    if (resetChart) {
      if (chart && setSharedXScaleDomain) {
        setSharedXScaleDomain((prevState) => ({
          ...prevState,
          current: prevState.initial,
          source: undefined,
        }));
      } else {...}
```

File: front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChart.tsx [hunk 21]
```diff
@@ -218,7 +218,7 @@ export default function SpaceTimeChart(props: SpaceTimeChartProps) {
   /* coordinate the vertical cursors with other graphs (GEV for instance) */
   useEffect(() => {
     if (dateIsInRange(timePosition, timeScaleRange)) {
-      traceVerticalLine(chart, CHART_AXES.SPACE_TIME, positionValues, rotate, timePosition);
+      traceVerticalLine(chart, CHART_AXES.SPACE_TIME, positionValues, timePosition);
```
Comment (clarani) [inline front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChart.tsx]: You need to keep the rotate here, SpaceTimeChart is the only chart that can rotate (just change the order of parameters)
```suggestion
      traceVerticalLine(chart, CHART_AXES.SPACE_TIME, positionValues, timePosition, rotate);
```

**Review by clarani — COMMENTED** [review]
Left 4 small comments, and 2 previous comments are still not resolved :)

**Review by clarani — APPROVED** [review]
LGTM and tested !! :white_check_mark: Very nice PR :white_check_mark:
