### PR TITLE
front: update requested_steps sent to the railway manager

### LINKED ISSUE #14417: front: incorrect departure or arrival time sent to the railway manager
Note: duplicate/related to https://github.com/OpenRailAssociation/osrd/issues/14411

### What happened?

When doing a last minute request : 

If the user selects `precise_time `for the origin step, lmr will find a solution, but it may not correspond to the scheduled time. In this case, the tolerances are updated.
Before sending the last-minute request to the railway manager, the user can modify the tolerance and check the departure time of the chosen simulation.

➡️ The frontend should send the departure time of the chosen simulation and not the departure time entered by the user.

For example, I entered 10:00 here, but the simulation found 10:06, so the time (`arrival_time`) of the first step should be 10:06 i.e. `"2025-12-18T09:06:00.000Z"`

Image

Payload :

<details><summary>Details</summary>
<p>

```json
{
    "rolling_stock": "27000US",
    "loading_gauge_type": "GA",
    "speed_limit_tags": "MA100",
    "total_mass": 90000,
    "max_speed": 27.77777777777778,
    "total_length": 20,
    "requested_steps": [
        {
            "duration": 0,
            "location": {
                "uic": 87141077,
                "secondary_code": "BV"
            },
            "timing_data": {
                "arrival_time": "2025-12-18T09:00:00.000Z",
                "arrival_time_tolerance_before": 2160000,
                "arrival_time_tolerance_after": 1440000
            }
        },
        {
            "duration": 300000,
            "location": {
                "uic": 87141044,
                "secondary_code": "BV"
            },
            "type": "DRIVER_SWITCH"
        },
        {
            "duration": 0,
            "location": {
                "uic": 87713875,
                "secondary_code": "TR"
            }
        }
    ],
    "departure_time": "2025-12-18T09:06:00.000Z",
    "user_message": "",
    "similar_train": null,
    "linked_train": null,
    "course_type": "Autre",
    "statistical_category": ////
}
```

</p>
</details> 

The same applies if the user selects `precise_time` for the destination step. The `arrival_time` for the last step must be the one found by the simulation and not the one entered by the user.

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Create a request with LMR and send it to the railway manager, retrieve the payload and check `arrival_time`

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

e2c7b9a

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #14417

### CODE REVIEW

File: front/src/modules/SimulationReportSheet/utils/formatSimulationReportSheet.ts [hunk 1]
```diff
@@ -373,19 +382,30 @@ export const transformStepsToApiFormat = (
...
+        ...baseStep,
+      };
+    }
+
+    let arrival_time = originArrivalTime.toISOString();
+
+    if (
+      index === steps.length - 1 &&
+      destinationArrivalTime &&
+      step.arrivalType === 'preciseTime'
```
Comment (achrafmohye) [inline front/src/modules/SimulationReportSheet/utils/formatSimulationReportSheet.ts]: I think `step.arrivalType === 'preciseTime'` this check is redundant since this part is reachable when the step is already in preciseTime case ?

File: front/src/modules/SimulationReportSheet/utils/formatSimulationReportSheet.ts [hunk 2]
```diff
@@ -354,10 +354,19 @@ export const getStopType = (stopType: StdcmStopTypes | undefined, t: TFunction<'
...
 export const transformStepsToApiFormat = (
   steps: StdcmPathStep[],
-  beforeTolerance: Duration,
-  afterTolerance: Duration
+  {
+    originArrivalTime,
+    destinationArrivalTime,
+    beforeTolerance,
+    afterTolerance,
+  }: {
```
Comment (achrafmohye) [inline front/src/modules/SimulationReportSheet/utils/formatSimulationReportSheet.ts]: nit: can we not inline this and extract it to a dedicated type ?
 ```
type TimingContext = {
  originArrivalTime: Date;
  destinationArrivalTime?: Date;
  beforeTolerance: Duration;
  afterTolerance: Duration;
};
```

Comment (SarahBellaha) [reply front/src/modules/SimulationReportSheet/utils/formatSimulationReportSheet.ts]: Totally forgot to do that, thx

**Review by achrafmohye — COMMENTED** [review]
LGTM :)

**Review by achrafmohye — APPROVED** [review]

**Review by Math-R — APPROVED** [review]
lgtm
