### PR TITLE
core: stdcm: stabilize running time computations

### LINKED ISSUE #5329: core: stdcm: 500 on engineering allowance: `zero timeDeltas`
### What happened?

```json
{
    "type": "",
    "context": {
        "message": "zero timeDeltas",
        "stack_trace": [
            "EnvelopePart.java:175",
            "EnvelopePart.java:79",
            "EnvelopePart.java:91",
            "EnvelopePart.java:104",
            "LinearAllowance.java:62",
            "LinearAllowance.java:47",
            "DelayManager.java:119",
            "DelayManager.java:51",
            "STDCMEdgeBuilder.java:191",
            "STDCMEdgeBuilder.java:183",
            "STDCMEdgeBuilder.java:154",
            "AllowanceManager.java:84",
            "AllowanceManager.java:42",
            "STDCMEdgeBuilder.java:232",
            "ReferencePipeline.java:197",
            "TreeMap.java:3064",
            "AbstractPipeline.java:509",
            "AbstractPipeline.java:499",
            "AbstractPipeline.java:575",
            "AbstractPipeline.java:260",
            "ReferencePipeline.java:616",
            "ReferencePipeline.java:622",
            "ReferencePipeline.java:627",
            "STDCMEdgeBuilder.java:143",
            "STDCMGraph.java:100",
            "STDCMGraph.java:24",
            "Pathfinding.java:197",
            "STDCMPathfinding.java:73",
            "STDCMEndpoint.java:87",
            "FkRegex.java:153",
            "FkRegex.java:217",
            "FkChain.java:72",
            "TkFork.java:98",
            "TkFallback.java:84",
            "TkFallback.java:66",
            "TkWrap.java:58",
            "TkSlf4j.java:110",
            "BkBasic.java:123",
            "BkBasic.java:99",
            "BkSafe.java:46",
            "BkWrap.java:51",
            "BkParallel.java:81",
            "ThreadPoolExecutor.java:1136",
            "ThreadPoolExecutor.java:635",
            "Thread.java:833"
        ]
    },
    "message": "assert check failed"
}
```

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Fuzzer on France would likely reproduce it

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu
- **Env**: Deployed internally

### OSRD version (top right corner `Account` button > `Informations`)

95b96222

### LINKED ISSUE #5372: core: stdcm: running time computations are generally unstable in STDCM context
### What happened?

There's a fairly large amount of 500 errors when running the fuzzer on stdcm, mostly in the form of assertions that fail.

They seem to be intertwined with common root causes, so I won't list all errors. They'll be fixed on the same branch  with regression tests. 

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Run the fuzzer

### What operating system, browser and environment are you using?

- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

74e4c511428bdc78ad6017b75976ea5f5fcd0a6c

### PR DESCRIPTION
**Pull request by eckter**
The changes have been made on the same branch to stabilize everything until the fuzzer is stable. This ensures that we don't have partial fixes (see https://github.com/osrd-project/osrd/pull/5362) and we don't create new bugs with the fixes.

It now seems stable, I've run 2500 tests on a real infra and the only errors reported were unrelated to running time computations (I'll open issues for those).

Changes include:
1. Envelopes can now have zero time delta (may happen in corner cases that are hard to get rid of), we still check that the positions are strictly increasing
2. Align envelope slicing with part transitions when splitting an envelope into different stdcm edges
3. Refine some epsilon tolerance, with a new utility function for comparaisons
4. Remove capacity speed limit for STDCM standard allowance

Fixes https://github.com/osrd-project/osrd/issues/5329 
Fixes #5372

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ private void runSanityChecks() {
         assert checkNaNFree(timeDeltas) : "NaNs in timeDeltas";
         assert checkPositive(speeds) : "negative speeds";
         assert checkPositive(timeDeltas) : "negative timeDeltas";
-        assert checkNonZero(timeDeltas) : "zero timeDeltas";
```
Comment (eckter) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java:175]: We often need an epsilon-long step, and because the time deltas are much smaller than the position deltas we often have zeros there. The constraint has been moved to position instead to still prevent empty steps. (this is explained in the commit message)

**Review by axrolld — APPROVED** [review]
lgtm

File: core/src/main/java/fr/sncf/osrd/stdcm/graph/AllowanceManager.java [hunk 2]
```diff
@@ -78,18 +80,30 @@ private STDCMEdge makeNewEdges(List<STDCMEdge> edges, Envelope totalEnvelope) {
...
+                    .setEnvelope(extractEnvelopeSection(totalEnvelope, previousEnd, end))
                     .setForceMaxDelay(true)
                     .setWaypointIndex(edge.waypointIndex())
                     .findEdgeSameNextOccupancy(edge.timeNextOccupancy());
             if (prevEdge == null)
                 return null;
             previousEnd = end;
         }
-        assert Math.abs(toMeters(previousEnd) - totalEnvelope.getEndPos()) < POSITION_EPSILON;
+        assert Math.abs(previousEnd - totalEnvelope.getEndPos()) < POSITION_EPSILON;
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/stdcm/graph/AllowanceManager.java]: maybe use arePositionsEqual?

Comment (Erashin) [reply core/src/main/java/fr/sncf/osrd/stdcm/graph/AllowanceManager.java]: I'd add that the epsilon values in `TrainPhysicsIntegrator` should be passed from `public` to `private`, so as to enforce the use of the comparison methods you put in place :)

Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/stdcm/graph/AllowanceManager.java]: Agree, but that would be a larger refactoring, for now I've only changed the places that were already edited in this PR

**Review by multun — APPROVED** [review]

**Review by Erashin — APPROVED** [review]
