### PR TITLE
editoast: fix operational point projection

### LINKED ISSUE #14857: STD is empty on scenario loading
### What happened?

The STD of this scenario is (sometimes, but often) empty. Refreshing the page seems not to help

Also, the x axis is not defined

https://rec-osrd.reseau.sncf.fr/operational-studies/projects/128/studies/1024/scenarios/2413?selected_train=paced_16770156&projection=paced_16770156

https://github.com/user-attachments/assets/2f7c1f3f-9268-445d-8467-564bbff8f9b3

### What did you expect to happen?

Project the trains and have the axis defined

### How can we reproduce it (as minimally and precisely as possible)?

open the above scenario

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 2945256

### PR DESCRIPTION
**Pull request by hhirtz**
Closes #14857

See #14863 for the track projection fix

~trains that do not respect times are thus projected as not-simulated. Contrary to #14863 this does not display the segment to the last path item if it doesn't have an arrival time. This could be fixed in another pull request.~

~I tried using `extract_curve_for_invalid_train_with_sim` but ended up with weird visual glitches on the curve when the train schedule has a long stop in the middle of its path... probably because `TrainToProjectOnOperationalPoint.refs` relies on the path item times.~

---

example where "a" is valid:

screen-20260128153940

---

example where "a" is invalid:

screen-20260128152324

### CODE REVIEW

**Comment by hhirtz** [comment]
Made it so the last segment of the curve is from the simulation result:

screen-20260129114018

**Comment by woshilapin** [comment]
I tested and encountered a weird behavior when the arrival is not tenable, but some intermediate stops overlap on this duration (see the fourth train). See the screenshots below and the [timetable.json](https://github.com/user-attachments/files/24938771/timetable.json) on small_infra.

image

image

**Comment by flomonster** [comment]
Found a small issue testing it:

Track projection:

image


OP porjection:

image

If you look closely, we have an issue with stop display. It's darker on the OP projection.
My guess is that the returned curve contains duplicate points for stops.

**Comment by flomonster** [comment]
I also found this train that has a weird behaviour: [bug.json](https://github.com/user-attachments/files/24939128/timetable.1.json)

**Comment by flomonster** [comment]
> If you look closely, we have an issue with stop display. It's darker on the OP projection. My guess is that the returned curve contains duplicate points for stops.

Nevermind, it's a frontend bug (it's also the case on dev).

File: editoast/src/views/projection.rs [hunk 1]
```diff
@@ -519,11 +520,85 @@ impl TrainToProjectOnOperationalPoint {
...
+        let last_scheduled_op_index = ts
+            .path()
+            .iter()
+            .position(|path_item| match &path_item.location {
+                PathItemLocation::OperationalPointPartReference(op_ref) => {
+                    &op_ref.operational_point == last_scheduled_op_ref
+                }
+                _ => false,
+            })
+            .unwrap();
```
Comment (hhirtz) [inline editoast/src/views/projection.rs:570]: Unsure if this is always equal to `last_path_item_index`?

**Review by hhirtz — COMMENTED** [review]
Rebased and added a comment here:

https://github.com/OpenRailAssociation/osrd/pull/14928/changes#diff-d71c1f271c519b4eaf8a44cb924c3c5217428103d7f3c89b747f4701587c12f4R572-R575

File: editoast/src/views/projection.rs (hunk 1 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:570]: nvm, `last_path_item_index` is the index of the very last OP path item, while `last_scheduled_op_index` is the index of the last OP path item with an input arrival time

File: editoast/src/views/projection.rs
Comment (woshilapin) [inline editoast/src/views/projection.rs:1]: I see that you did put some questions inside the commit description. I would say that the Pull Request description in Github is a better place for these. I do enjoy (very much) having details description inside the commit description (thank you for that), but I feel they should be used for what is done in the commit, not what should be discussed.

For the question itself, you could replace `ToCompute` with `ComputeContext` which would allow for a plural form. This plural form could then be used for the `HashMap`: `compute_contexts`. This then solve your question for `e` that can become the singular form `compute_context`.

Or you could keep `ToCompute`, change the name of the `HashMap` into `to_compute_by_simulation`, then replace `e` by `to_compute`.

**Review by flomonster — APPROVED** [review]
LGMT, since I contributed as co-author we should have another maintainer review.

File: editoast/src/views/projection.rs [hunk 2]
```diff
@@ -519,11 +520,85 @@ impl TrainToProjectOnOperationalPoint {
...
+
+        let last_scheduled_op_ref = &res.refs.last().unwrap().op_ref;
+        if last_scheduled_op_ref == &last_path_item_op_ref {
+            // The last operational point is already present
+            return res;
+        }
+
+        let stop_for = ts
+            .schedule()
+            .iter()
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:555]: nitpick: Probably faster since we’re looking at one of the last one, isn’t it?

```suggestion
            .iter()
            .rev()
```

File: editoast/src/views/projection.rs [hunk 3]
```diff
@@ -519,11 +520,85 @@ impl TrainToProjectOnOperationalPoint {
...
+            .find(|schedule_item| schedule_item.at == last_path_item_id)
+            .and_then(|schedule_item| schedule_item.stop_for)
+            .map(|stop_for| stop_for.num_milliseconds() as u64)
+            .unwrap_or_default();
+
+        let last_scheduled_op_index = ts
+            .path()
+            .iter()
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:563]: nitpick: Same here

```suggestion
            .iter()
            .rev()
```

File: editoast/src/views/projection.rs [hunk 4]
```diff
@@ -519,11 +520,85 @@ impl TrainToProjectOnOperationalPoint {
...
+                _ => false,
+            })
+            .unwrap();
+
+        // `last_schedule_op_sim_time - last_schedule_op_time` is how off the simulation is
+        // compared to the time from the input. We use this value to offset the simulated time at
+        // the last operational point `last_op_sim_time`, to align the simulation with the input
+        // curve.
+        let last_op_sim_time = sim.final_output.report_train.path_item_times[last_path_item_index];
+        let last_schedule_op_time = res.refs.last().unwrap().arrival_time;
```
Comment (woshilapin) [inline editoast/src/views/projection.rs]: nitpick: I’m a bit annoyed by the variable name `res` because reading here, I thought it was one of the input of the function (this function basically post-process some results) but then I wonder what was the difference between `sim` and `res`. Of course, scrolling up, I understood, but maybe a better name would help? How about `projected_train` or maybe even `projected_result` would be enough, what do you think?

File: editoast/src/views/projection.rs [hunk 5]
```diff
@@ -519,11 +520,85 @@ impl TrainToProjectOnOperationalPoint {
...
+            .iter()
+            .enumerate()
+            .rev()
+            .find_map(|(path_item_index, path_item)| match &path_item.location {
+                PathItemLocation::OperationalPointPartReference(op_ref) => Some((
+                    path_item_index,
+                    path_item.id.clone(),
+                    op_ref.operational_point.clone(),
+                )),
+                PathItemLocation::TrackOffset(_) => None,
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:541]: I’m not sure that I understand why we do ignore the `TrackOffset` variant?

**Review by woshilapin — APPROVED** [review]
No big problem with the PR, mostly some slight proposition and a question probably due to my lack of knowledge.

File: editoast/src/views/projection.rs
Comment (hhirtz) [reply editoast/src/views/projection.rs:1]: thanks for the suggestions, i went with `ComputeContext`

ill try to avoid questions in commits, i thought someone going through the history in the future might have a better idea

File: editoast/src/views/projection.rs (hunk 2 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:555]: and probably more resilient with regards to future backtracks? went with `rfind`

File: editoast/src/views/projection.rs (hunk 3 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:563]: used `rposition`

File: editoast/src/views/projection.rs (hunk 4 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs]: chose `input_only` to reflect that the variable doesn't involve the simulation until the very end of the function

File: editoast/src/views/projection.rs (hunk 5 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:541]: i think this is because of the following AC:

> Quand on passe au get Inter PR, la liste des points utilisées se base sur la circulation utilisée pour la projection à la voie. (sans prendre en compte les points demandés par l'utilisateur qui ne sont pas des PRs) 
> https://github.com/osrd-project/osrd-confidential/issues/695

? not 100% sure

Comment (woshilapin) [reply editoast/src/views/projection.rs:541]: I got confirmation from @flomonster and it is exactly that. Thank you. I’m wondering if a small comment would help future developers to understand that.

Comment (hhirtz) [reply editoast/src/views/projection.rs:541]: however, because we only use operational points, when the last path item is a track offset, the trick to draw a line between the last scheduled input point and the offseted simulation point visually yields different arrival times to the last OP depending on if you are in track or OP projection mode.

This is because in OP projection mode the arrival time is the actual arrival time from the simulation, while in track projection mode the arrival time is a cross product (because we draw a straight line to the last path item instead of the simulation curve).

If we want to fix this we have several options:
- draw the simulation curve on the last segment instead of a straight line
- in the track projection, draw two segments instead of one: the first between the last scheduled OP and the actual last OP, the second between the actual last OP and the last path item (the track offset)

I don't think it can be fixed in this PR alone though

Ill post an example later

**Comment by flomonster** [comment]
@hhirtz Are we good to merge this one?

**Comment by hhirtz** [comment]
i planned to wait until monday to make sure  https://github.com/OpenRailAssociation/osrd/pull/14928#discussion_r2746638324 or https://github.com/OpenRailAssociation/osrd/pull/14928#discussion_r2746637956 didnt' introduce bugs but feel free to merge anytime

**Comment by flomonster** [comment]
> i planned to wait until monday to make sure [#14928 (comment)](https://github.com/OpenRailAssociation/osrd/pull/14928#discussion_r2746638324) or [#14928 (comment)](https://github.com/OpenRailAssociation/osrd/pull/14928#discussion_r2746637956) didnt' introduce bugs but feel free to merge anytime

Okay I will merge it today since the release candidate is for tonight.

File: editoast/src/views/projection.rs (hunk 5 above)
Comment (hhirtz) [reply editoast/src/views/projection.rs:541]: ~Here's the example: https://github.com/OpenRailAssociation/osrd/issues/14988~ actually this is another issue because in 14988 the train schedule has an arrival time at the track offset

For the fix the plan is to use a third option: draw one straight line, but not between the last scheduled point and the offseted simulated destination, but between the last scheduled point and the offseted simulated arrival at the last OP (and extended to reach the track offset)
