### PR TITLE
front: LMR: fix length, mass and speed reset

### LINKED ISSUE #10106: LMR : Default length, mass and speed don't set when you delete then re-set rolling stock
### What happened?

When you delete the length, mass and speed, if you re-set the rolling-stock, the values doesn't set as default for the rolling stock.

### What did you expect to happen?

When we re-set the rolling stock, we expect the default value to be set at least when the fields are empty.

If the fields were set before by the user with other values, not sure if we expect the values to be keeped or not.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set the rolling stock
2. Delete all entry in the fields length, mass, speed
3. delete the rolling stock
4. set another rolling stock

https://github.com/user-attachments/assets/3d670194-b71e-434e-8164-7b50a7912bd3

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9e75ce2

### LINKED ISSUE #10270: front: changing a convoy value prevents it from being autofilled for all future rolling stock change
### What happened?

I set a value for convoy max speed. I then changed rolling stock, and the value remained. There wasn't any way to know the actual expected rolling stock max speed, or to reset it in any way. The only solution was refreshing the page and losing everything.

### What did you expect to happen?

I expected all values to be updated when changing rolling stock.

At least, I thought that deleting the value entirely would reset it.

### How can we reproduce it (as minimally and precisely as possible)?

Set a max speed value and change rolling stock. 

### On which environments the bug occurs?

Local, Other

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

ef6e28ed5cf068bd874ed7bef9e266b5a8e2e78f

### PR DESCRIPTION
**Pull request by Akctarus**
closes #10106 and fix #10270

should respect the expectations of this: https://github.com/osrd-project/osrd-confidential/issues/903

### CODE REVIEW

**Comment by achrafmohye** [comment]
@Akctarus When i select Traction engine using the combobox above i have these messages on each filled input is it the intended behaviour ? and have to close them manually which is more of a ui-core improvement
image

**Comment by Akctarus** [comment]
> @Akctarus When i select Traction engine using the combobox above i have these messages on each filled input is it the intended behaviour ? and have to close them manually which is more of a ui-core improvement image

yes it is, the user must be informed visually as soon as the app changes a piece of data he had previously changed. To close them, yes maybe we should improve that, but in any case the messages close by themselves, if we change traction engine

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: The tooltip top position seems to be wrong (not like the error one)

Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: If the tooltip is overridden after switching rs, the error tooltip doesn't pop anymore if the value is invalid

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: good catch, I fixed the css

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: fixed !

Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: Seems like it doesn't work when changing the consist field (no info tooltip).
Maybe the conditions in `statusWithMessage` can be put somewhere else, it's starting to get messy.

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: fixed

File: front/src/applications/stdcm/utils/getStatusWithMessage.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    totalMass?: StatusWithMessage;
+    totalLength?: StatusWithMessage;
+    maxSpeed?: StatusWithMessage;
+  },
+  consistErrors: ConsistErrors,
+  statusMessagesVisible: { mass: boolean; length: boolean; speed: boolean },
+  rollingStock: RollingStockWithLiveries | undefined,
+  towedRollingStock: TowedRollingStock | undefined
+): StatusWithMessage | undefined => {
+  const { t } = useTranslation('stdcm');
```
Comment (SharglutDev) [inline front/src/applications/stdcm/utils/getStatusWithMessage.ts]: We should be able to use this only in a custom hook. Since it's not, we should be pass the `t` function as a parameter or change the name of the function to `useConsistFieldStatus`

File: front/src/applications/stdcm/hooks/useStdcmConsist.ts [hunk 2]
```diff
@@ -1,6 +1,8 @@
 import { useState } from 'react';
 
+import type { StatusWithMessage } from '@osrd-project/ui-core/dist/components/inputs/StatusMessage';
```
Comment (SharglutDev) [inline front/src/applications/stdcm/hooks/useStdcmConsist.ts]: We shouldn't import from `/dist/...`, you can keep thd old `InputProps['statusWithMessage']`

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx [hunk 3]
```diff
@@ -94,6 +92,24 @@ const StdcmConsist = ({ isDebugMode, consistErrors = {}, disabled = false }: Std
     dispatchUpdateSpeedLimitByTag(newTag);
   };
 
+  const [statusMessagesVisible, setStatusMessagesVisible] = useState({
+    mass: true,
+    length: true,
+    speed: true,
+  });
+
+  const handleStatusMessage = (key: 'mass' | 'length' | 'speed') => {
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]:
```suggestion
  const handleCloseStatusMessage = (key: 'mass' | 'length' | 'speed') => {
```

File: front/public/locales/en/stdcm.json [hunk 4]
```diff
@@ -22,6 +22,11 @@
         "negative": "Must be positive.",
         "range": "The max speed must be between {{low}} and {{high}}km/h"
       }
+    },
+    "info": {
+      "totalMass": "The weight has been updated to reflect the new traction unit.",
+      "totalLength": "The length has been updated to reflect the new traction unit.",
+      "maxSpeed": "The max speed has been updated to reflect the new traction unit."
```
Comment (SharglutDev) [inline front/public/locales/en/stdcm.json]:
```suggestion
      "totalMass": "The weight has been updated to reflect the new consist data.",
      "totalLength": "The length has been updated to reflect the new consist data.",
      "maxSpeed": "The max speed has been updated to reflect the new consist data."
```

File: front/public/locales/fr/stdcm.json [hunk 5]
```diff
@@ -22,6 +22,11 @@
         "negative": "Doit être positif.",
         "range": "La vitesse max. doit être comprise entre {{low}} et {{high}}km/h"
       }
+    },
+    "info": {
+      "totalMass": "Le poids a été mis à jour en fonction du nouvel engin de traction.",
+      "totalLength": "La longueur a été mise à jour en fonction du nouvel engin de traction.",
+      "maxSpeed": "La vitesse maximale a été mise à jour en fonction du nouvel engin de traction."
```
Comment (SharglutDev) [inline front/public/locales/fr/stdcm.json]:
```suggestion
      "totalMass": "Le poids a été mis à jour en fonction des nouvelles données de convoi.",
      "totalLength": "La longueur a été mise à jour en fonction des nouvelles données de convoi.",
      "maxSpeed": "La vitesse maximale a été mise à jour en fonction des nouvelles données de convoi."
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: When I empty a field and chose another rs or towed, we shouldn't have the info tooltip

Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: If I change the speed limit tag, the length and mass fields are updated when there should be only the vmax one who changes

File: front/src/applications/stdcm/utils/getStatusWithMessage.ts (hunk 1 above)
Comment (Akctarus) [reply front/src/applications/stdcm/utils/getStatusWithMessage.ts]: fixed in : ceafa62a3e037c0f4fc0a3620e3b048f3e0e477b

File: front/src/applications/stdcm/hooks/useStdcmConsist.ts (hunk 2 above)
Comment (Akctarus) [reply front/src/applications/stdcm/hooks/useStdcmConsist.ts]: fixed in : d648c119ebb795d7be3f3e2b47b781b5fb9d023d

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx (hunk 3 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]: fixed in : d3b3477edbcb1a36dc6ca6b4b99de4e0cea0963f

File: front/public/locales/en/stdcm.json (hunk 4 above)
Comment (Akctarus) [reply front/public/locales/en/stdcm.json]: fiex in : ec2d77faa4b999de797e4f080da573907a4db130

File: front/public/locales/fr/stdcm.json (hunk 5 above)
Comment (Akctarus) [reply front/public/locales/fr/stdcm.json]: fixed in : ec2d77faa4b999de797e4f080da573907a4db130

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: fixed by : 6c4c0d80e68c68bc54d3d3fd5df5a6d892d4dcbb

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: fixed by : 79979b746f492ff8cd429303cf7de738a9158378

File: front/src/applications/stdcm/hooks/useStatusWithMessage.ts [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+import { kgToT, kmhToMs, msToKmh } from 'utils/physics';
+
+import type { ConsistErrors } from '../types';
+import {
+  CONSIST_MAX_SPEED_MIN,
+  CONSIST_TOTAL_LENGTH_MAX,
+  CONSIST_TOTAL_MASS_MAX,
+} from '../utils/consistValidation';
+
+const useConsistFieldStatus = (
```
Comment (SharglutDev) [inline front/src/applications/stdcm/hooks/useStatusWithMessage.ts]: This should have the same name of the file

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx [hunk 7]
```diff
@@ -154,7 +154,7 @@ const StdcmConsist = ({ isDebugMode, consistErrors = {}, disabled = false }: Std
           value={totalMass ?? ''}
           onChange={onTotalMassChange}
           disabled={disabled}
-          statusWithMessage={getStatusWithMessage(
+          statusWithMessage={useStatusWithMessage(
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]: It works for now but I'm a bit afraid of using custom hooks directly in the JSX. If later these inputs are render conditionally we could have some white screens because react advises against conditional hooks.
Maybe we could rather call them at the start of the component like this : 
```
const massFieldStatus = useStatusWithMessage(
            'totalMass',
            statusWithMessage,
            consistErrors,
            statusMessagesVisible,
            rollingStock,
            towedRollingStock
          )
```

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: Some of the changes you made here broke some things : 

Uploading Enregistrement de l’écran 2025-01-31 à 09.01.43.mov…

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: Some of the changes you made here broke some things : 

https://github.com/user-attachments/assets/f82c34d2-31ed-42f0-ade5-9b838d5ae1da

Sometimes when I just change the mass after switching a rs, the tooltip pops. Same if I change the speed limit tag.

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx [hunk 8]
```diff
@@ -90,10 +89,30 @@ const StdcmConsist = ({ isDebugMode, consistErrors = {}, disabled = false }: Std
...
+
+  useEffect(() => {
+    const isDefined =
+      totalMass !== undefined && totalLength !== undefined && maxSpeed !== undefined;
+    setStatusMessagesVisible({
+      mass: isDefined,
+      length: isDefined,
+      speed: isDefined,
+    });
+  }, [rollingStock, totalMass, totalLength, maxSpeed]);
```
Comment (SharglutDev) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]: I don't think we need this `useEffect`, we could just `setStatusMessagesVisible` to true in `handleRollingStockSelect`. The rest of the job is done in the `prefillConsist` function (if one of the field is undefined, it won't have a status)
```suggestion
```

File: front/src/applications/stdcm/hooks/useStatusWithMessage.ts (hunk 6 above)
Comment (Akctarus) [reply front/src/applications/stdcm/hooks/useStatusWithMessage.ts]: Oops, fixed

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]: fixed

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx (hunk 8 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx]: nice catch ! fixed

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: It seems to be fixed by this fix : https://github.com/OpenRailAssociation/osrd/pull/10447#discussion_r1939165076

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: Normal behavior : 
- I select a BB 15 000 > the vmax goes to 160
- I put a ME 120 speed limit tag > the vmax goes to 120
- I switch to BB 64700 > the vmax goes to 80 (even with ME 120 as expected) > no message as expected

Same test with one change : 
- I select a BB 15 000 > the vmax goes to 160
- I manually change the vmax to 150
- I put a ME 120 speed limit tag > the vmax goes to 120
- I switch to BB 64700 > the vmax goes to 80 (even with ME 120 as expected) > there is a info tooltip
I don't think we should have one as the vmax I manually entered has already been overridden by the change of the speed limit tag. Maybe when we pass in `onSpeedLimitByTagChange`, we should `setMaxSpeedChanged(false);` ? (didn't test)

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: fixed :)

File: front/src/applications/stdcm/hooks/useConsistFieldStatus.ts [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+import { kgToT, kmhToMs, msToKmh } from 'utils/physics';
+
+import type { ConsistErrors } from '../types';
+import {
+  CONSIST_MAX_SPEED_MIN,
+  CONSIST_TOTAL_LENGTH_MAX,
+  CONSIST_TOTAL_MASS_MAX,
+} from '../utils/consistValidation';
+
+const useConsistFieldStatus = (
```
Comment (achrafmohye) [inline front/src/applications/stdcm/hooks/useConsistFieldStatus.ts:15]: i think it's better to have different names for `useConsistFieldStatus` and `useStatusWithMessage `, was the naming of the two hooks with the same name intentional ?!

**Comment by achrafmohye** [comment]
Can you rebase your branch please, for easier testing :)

File: front/src/applications/stdcm/hooks/useConsistFieldStatus.ts (hunk 9 above)
Comment (Akctarus) [reply front/src/applications/stdcm/hooks/useConsistFieldStatus.ts:15]: good catch it was a duplicate !

**Comment by Akctarus** [comment]
> Can you rebase your branch please, for easier testing :)

done !

File: front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx
Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: Hmm not quite, now when I change the rolling stock for the last step, the max speed isn't updated anymore, see video

https://github.com/user-attachments/assets/2378ec46-342f-4f3e-9b1d-b72331d8cd7b

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConsist.tsx:1]: My bad, everything works as expected

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !

**Review by achrafmohye — APPROVED** [review]
LGTM and tested Thanks :)
