### PR TITLE
front: persist track selection when pathfinding fails

### LINKED ISSUE #15961: Itinerary modal: cannot create invalid trains with a missing block due to the track being removed
### What happened?

Track : 

https://github.com/user-attachments/assets/d27afe05-1b52-48c6-94a4-b6dd519a0dff

### What did you expect to happen?

Submiting the Itinerary modal should save the track even it's created invalid train

### How can we reproduce it (as minimally and precisely as possible)?

1. From the Itinerary modal 
2. Create a valid path
3. Update the track to create 

[timetable (7).json](https://github.com/user-attachments/files/26279553/timetable.7.json)

Missing block

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

8b88601

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15961

### CODE REVIEW

**Review by theocrsb — APPROVED** [review]
tested

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 1]
```diff
@@ -113,6 +113,7 @@ const usePathfinding = ({
           ...(op.extensions?.identifier?.name && { name: op.extensions.identifier.name }),
           ...(op.extensions?.identifier?.uic && {
             location: {
+              ...step.location,
```
Comment (SharglutDev) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: This would be more explicit
```suggestion
              local_track_name: step.location.local_track_name,
```

**Review by SharglutDev — APPROVED** [review]

File: front/src/modules/pathfinding/hooks/usePathfinding.ts (hunk 1 above)
Comment (RomainValls) [reply front/src/modules/pathfinding/hooks/usePathfinding.ts]: True, thanks :)
