### PR TITLE
editoast : add status 500 when core send status 500

### LINKED ISSUE #5058: editoast: core 500 responses are forwarded as 400 responses
### What happened?

`core` crashed, the response was a 400

### What did you expect to happen?

a 500 response

### How can we reproduce it (as minimally and precisely as possible)?

Make `core` crash and check the error code

### What operating system, browser and environment are you using?

- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

04b21aa27c6f5f27c976d43360f5027124b88860

### PR DESCRIPTION
**Pull request by younesschrifi**
Close #5058

### CODE REVIEW

File: editoast/src/core/mod.rs [hunk 1]
```diff
@@ -302,6 +312,14 @@ enum CoreError {
         url: String,
         raw_error: String,
     },
+    /// A internal servor core error was found, so editoast forward a 500 error
```
Comment (leovalais) [inline editoast/src/core/mod.rs]: I'm not a fan of duplicating the variant just to change the status. I've changed EditoastError so that the status doesn't have to be a compile-time constant and can depend on the fields of the variant. You'll be able to write things like:

```rust
#[editoast_error(status = status.unwrap_or(500))]
```

or any other expression (including function calls).

So my suggestion is:

* drop the new variant
* you have core's status in the variant, so compute the expected editoast response status the annotation

File: editoast/src/core/mod.rs [hunk 2]
```diff
@@ -114,12 +115,21 @@ impl CoreClient {
                 )
                 .map_err(|err| {
                     if let Ok(utf8_raw_error) = String::from_utf8(bytes.as_ref().to_vec()) {
-                        CoreError::GenericCoreError {
-                            status: status.as_str().to_owned(),
-                            url: url.clone(),
-                            raw_error: utf8_raw_error,
+                        if status == StatusCode::INTERNAL_SERVER_ERROR {
```
Comment (leovalais) [inline editoast/src/core/mod.rs]: Better match every 5xx instead of 500

**Review by leovalais — CHANGES_REQUESTED** [review]
Thanks for the fix :) A small change to reduce duplication ⬇️

**Review by leovalais — APPROVED** [review]
