### PR TITLE
front: fix psl announcement first value

### LINKED ISSUE #4466: Wrong suggestion for the announcement panel when we edit a LPV
### What happened?

When we edit a LPV, if we want to add an announcement panel, the editor suggested us the position at the end of the LPV (where we could have a R panel).

### What did you expect to happen?

We expect the editor to suggest us the position at the beginning of the LPV.

### How can we reproduce it (as minimally and precisely as possible)?

- Go on the editor
- Try to add a new annoucement panel for a LPV

### What operating system, browser and environment are you using?

- **Browser**: Firefox v114.0.2
- **OS**: Windows 10
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

6d38dfa9

### LINKED ISSUE #5940: front: editor: application crash when we place a panel with a negative value
### What happened?

When we try to edit a PSL, when we place a panel, if the value is under 0, the app crash, if the value is above the length of the track, the position is wrongly saved, but the display is still correct.

### What did you expect to happen?

The application, should continue to run.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor
2. try to edit a PSL
3. change the position of a panel

### What operating system, browser and environment are you using?

- **Browser**: Firefox v120
- **OS**: Windows 11
- **Env**: Dgex Dev

### OSRD version (top right corner `Account` button > `Informations`)

459de94

### PR DESCRIPTION
**Pull request by Tguisnet**
Close #4466
Close #5940

### CODE REVIEW

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx [hunk 1]
```diff
@@ -18,8 +25,8 @@ const getNewAnnouncementSign = (
   return {
     angle_geo: 0,
     angle_sch: 0,
-    position: firstRange.end,
-    side: 'RIGHT',
+    position: firstRange.begin,
+    side: 'LEFT',
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx:29]: Should we leave it to 'RIGHT' ? Because if not it will overlap with the Z panel and the user might think the panel didn't work

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx [hunk 2]
```diff
@@ -43,16 +50,53 @@ const getNewRSign = (
   } as PSLSign;
 };
 
+const getNewValidSign = (sign: PSLSign, tracks: TrackSectionEntity[]) => {
+  const newSign = cloneDeep(sign);
+  const signTrack = tracks.find((track) => track.properties.id === sign.track);
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx:55]: In PSLSign type, maybe we could rename the `track` property with `trackId` or `track_id`?

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx [hunk 3]
```diff
@@ -43,16 +50,53 @@ const getNewRSign = (
   } as PSLSign;
 };
 
+const getNewValidSign = (sign: PSLSign, tracks: TrackSectionEntity[]) => {
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]: maybe the purpose of the function is more clear like that ?
```suggestion
const validateSignPosition = (sign: PSLSign, tracks: TrackSectionEntity[]): PSLSign => {
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx [hunk 4]
```diff
@@ -43,16 +50,53 @@ const getNewRSign = (
...
+  const newSign = cloneDeep(sign);
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]:
```suggestion
  const validSign = cloneDeep(sign);
```

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx [hunk 5]
```diff
@@ -43,16 +50,53 @@ const getNewRSign = (
...
+    () =>
+      compact(
+        signTrackIds.map((trackId) => {
+          const track = trackSectionsCache[trackId];
+          return track?.type !== 'success' ? null : track.track;
+        })
+      ),
+    [signTrackIds]
+  );
+
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]: Should you merge these two useMemo in one ? It results with less memoization. 
```suggestion
  const tracks = useMemo(() => {
    const { psl_sncf: pslExtensionSigns } = entity.properties.extensions;
    const signs = [pslExtensionSigns.z, ...pslExtensionSigns.r, ...pslExtensionSigns.announcement];
    const signTrackIds = removeDuplicates(signs.map((sign) => sign.track));
    return compact(
      signTrackIds.map((trackId) => {
        const track = trackSectionsCache[trackId];
        return track?.type !== 'success' ? null : track.track;
      })
    );
  }, [entity.properties.extensions.psl_sncf]);
```

**Review by SharglutDev — COMMENTED** [review]
Thank you for this PR ! Lgtm and tested and it works great.
Left some suggestions.

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx (hunk 5 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]: I separated into 2 memoized const because otherwise the tracks are recomputed very often and I wanted to reduce the code executed at each modification of the extension, but we can merge it for sure, as you want :)

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx (hunk 2 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx:55]: I didn't want to change that because it comes from the editoast model :/

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx (hunk 1 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx:29]: A question for @Tguisnet :)

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx:55]: oh ok didn't think about that !

File: front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx (hunk 5 above)
Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]: I'm not sure it will work that way. As signTrackIds is an array, it's reference will change each time we change something in the form and tracks will be recomputed anyway. (I'm not 100% sure about the explanation though)
I tried to console.log in both useMemo and both are called each time anything changes in the form.

Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/speedSection/EditPSLSection.tsx]: My bad you're right, since it is an array ! I can change that :) Thanks !

**Review by SharglutDev — APPROVED** [review]
Lgtm o//

**Review by SharglutDev — APPROVED** [review]
