### PR TITLE
Prevent pathfinding from crashing when using manually created rolling stock

### LINKED ISSUE #5315: Fail to create a train with an electrical rolling stock created from scratch
Step to reproduce:
1. Create a new viable electrical rollingstock from scratch
2. Save it
3. Check if you can create a train with this rolling stock, pathfinding should fail with `assertion failed`

version: `e32e129131ada79b92704fc7ca6bf137888e8489`

### PR DESCRIPTION
**Pull request by anisometropie**
Fixes a crash that would happen in a `pathfinding` using a rolling stock that was created manually.

### Front
Rolling stock editor now allows to edit the two values `raise_pantograph_time` and `electrical_power_startup_time`, and enforces the policy that these two values must be defined for a rolling stock that has at least one electrical traction mode.

### Editoast
import_rolling_stock now checks if the two values `raise_pantograph_time` and `electrical_power_startup_time` are defined for an electrical rolling stock.

closes #5315

### CODE REVIEW

File: editoast/src/main.rs [hunk 1]
```diff
@@ -376,8 +377,36 @@ async fn import_rolling_stock(
             "🍞 Importing rolling stock {}",
             rolling_stock.name.clone().unwrap().bold()
         );
+        let is_electric = match &rolling_stock.effort_curves {
```
Comment (flomonster) [inline editoast/src/main.rs]: This check is only done using CLI. We must do the same check when a rolling stock is created or updated using endpoints.

-------

To avoid code duplication we should do this check when deserializing a `RollingStockCommon`. To do so we must implement manually the trait `Deserialize`.

File: editoast/src/main.rs [hunk 2]
```diff
@@ -726,7 +918,7 @@ mod tests {
             .unwrap();
     }
 
-    fn generate_railjson_temp_file(railjson: &RailJson) -> NamedTempFile {
+    fn generate_temp_file<T: Serialize>(railjson: &T) -> NamedTempFile {
```
Comment (flomonster) [inline editoast/src/main.rs]:
```suggestion
    fn generate_temp_file<T: Serialize>(object: &T) -> NamedTempFile {
```

**Review by flomonster — CHANGES_REQUESTED** [review]
I only reviewed the editoast part without testing.

File: editoast/src/views/rolling_stocks/mod.rs [hunk 3]
```diff
@@ -56,6 +56,9 @@ pub enum RollingStockError {
     #[error("Base power class is an empty string")]
     #[editoast_error(status = 400)]
     BasePowerClassEmpty,
+    #[error("Couldn’t import rolling stock")]
```
Comment (Castavo) [inline editoast/src/views/rolling_stocks/mod.rs:59]:
```suggestion
    #[error("Rolling stock was in wrong format")]
```

Comment (Castavo) [inline editoast/src/views/rolling_stocks/mod.rs]:
```suggestion
    #[error("Rolling stock was in wrong format")]
```

File: editoast/src/main.rs [hunk 4]
```diff
@@ -376,8 +377,36 @@ async fn import_rolling_stock(
             "🍞 Importing rolling stock {}",
             rolling_stock.name.clone().unwrap().bold()
         );
+        let is_electric = match &rolling_stock.effort_curves {
+            Some(curves) => curves.modes.values().any(|mode| mode.is_electric),
+            None => false,
+        };
```
Comment (Castavo) [inline editoast/src/main.rs]: This could be a method of the rolling stock model, the is_electric logic could be useful elsewhere in the future

File: editoast/src/main.rs [hunk 5]
```diff
@@ -667,16 +696,179 @@ async fn refresh_search_tables(
...
+        // THEN
+        assert!(result.is_err())
+    }
+
+    #[rstest]
+    async fn import_non_electric_rs_without_startup_and_panto_values(db_pool: Data<DbPool>) {
+        // GIVEN
+        let rolling_stock_name =
+            "fast_rolling_stock_import_non_electric_rs_without_startup_and_panto_values";
+        let mut non_electric_rolling_stock = get_fast_rolling_stock(rolling_stock_name);
```
Comment (Castavo) [inline editoast/src/main.rs:765]: You could wrap the created model in `TestFixture` so it would get cleaned up automatically, even if the test fails
I haven't seen it in many places tho, so I don't know if that's a good practice or not, what do you think @osrd-project/editoast-maintainers ?

File: editoast/src/models/rolling_stock/mod.rs [hunk 6]
```diff
@@ -134,6 +134,17 @@ impl RollingStockModel {
...
+    pub async fn delete_by_name(conn: &mut PgConnection, rs_name: String) -> Result<()> {
+        use crate::tables::rolling_stock::dsl::*;
+        match delete(rolling_stock.filter(name.eq(rs_name)))
+            .execute(conn)
+            .await
+        {
+            Ok(_) => Ok(()),
+            Err(e) => Err(e.into()),
+        }
+    }
```
Comment (Castavo) [inline editoast/src/models/rolling_stock/mod.rs]: I don't think this method is needed, for your use case you already have access to the rolling stock's id

File: editoast/src/main.rs (hunk 2 above)
Comment (anisometropie) [reply editoast/src/main.rs]: done

**Review by Castavo — COMMENTED** [review]
I tested editing RS by removing electrical related times, it does prevent it
Creating brand new RS works, the times are filled in correctly, however, why is it a different behavior from the other mandatory fields, which are only filled in with defaults when we click on "save" ?
Also, the fields appearing while the user is in another view feels a bit unergonomical, have you checked with a PO ?
Pathfinding does work correctly with a brand new electrical rolling stock !

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 7]
```diff
@@ -36,6 +40,28 @@ type RollingStockParametersProps = {
...
+  }
+  if (isElectric(prevRsEffortCurve) && !isElectric(currentRsEffortCurve)) {
+    return {
+      ...currentRollingStockValues,
+      electricalPowerStartupTime: null,
+      raisePantographTime: null,
+    };
+  }
+  return currentRollingStockValues;
+}
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]:
```suggestion
export function modifyRollingStockElectricalValues(
  currentRollingStockValues: RollingStockParametersValues,
  isPrevRsEffortCurveElectrical: boolean,
  isCurrentRsEffortCurveElectrical: boolean
) {
  if (!isPrevRsEffortCurveElectrical && isCurrentRsEffortCurveElectrical) {
    return {
      ...currentRollingStockValues,
      electricalPowerStartupTime: DEFAULT_ELEC_POWER_STARTUP_TIME,
      raisePantographTime: DEFAULT_RAISE_PANTOGRAPH_TIME,
    };
  }
  if (isPrevRsEffortCurveElectrical && !isCurrentRsEffortCurveElectrical) {
    return {
      ...currentRollingStockValues,
      electricalPowerStartupTime: null,
      raisePantographTime: null,
    };
  }
  return currentRollingStockValues;
}
```
We can maybe check if the rs has an electric mode before calling this function to avoid calling `isElectric()` multiple times ?

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 8]
```diff
@@ -66,14 +92,26 @@ const RollingStockEditorForm = ({
...
 
+  useEffect(() => {
+    if (prevRsEffortCurve !== undefined) {
+      setRollingStockValues(
+        modifyRollingStockElectricalValues(
+          rollingStockValues,
+          prevRsEffortCurve,
+          currentRsEffortCurve
+        )
+      );
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]:
```suggestion
      setRollingStockValues(
        modifyRollingStockElectricalValues(
          rollingStockValues,
          isElectric(prevRsEffortCurve),
          isElectric(currentRsEffortCurve)
        )
      );
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+  getRollingStockEditorDefaultValues,
+  makeTractionMode,
+} from 'modules/rollingStock/helpers/utils';
+import {
+  DEFAULT_ELEC_POWER_STARTUP_TIME,
+  DEFAULT_RAISE_PANTOGRAPH_TIME,
+} from 'modules/rollingStock/consts';
+import { modifyRollingStockElectricalValues } from '../RollingStockEditorForm';
+
+const newEmptyRollingStock = getRollingStockEditorDefaultValues(null);
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts:7]:
```suggestion
const newEmptyRollingStock = getRollingStockEditorDefaultValues(null);
const electricRsEffortCurve = getDefaultRollingStockMode('1000');
const thermalRsEffortCurve = getDefaultRollingStockMode('thermal');
```
As you are using the same type of rollingstocks, we could maybe instantiate them outside the tests.

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+describe('getElectricalDefaultValues', () => {
+  it('should add electricalPowerStartupTime and raisePantographTime when an electrical mode is added', () => {
+    const currentRollingStockValues = newEmptyRollingStock;
+    const prevRsEffortCurve = null;
+    const rsEffortCurve = getDefaultRollingStockMode('1000');
+    const result = modifyRollingStockElectricalValues(
+      currentRollingStockValues,
+      prevRsEffortCurve,
+      rsEffortCurve
+    );
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
it('should add electricalPowerStartupTime and raisePantographTime when an electrical mode is added', () => {
    const currentRollingStockValues = newEmptyRollingStock;
    const prevRsEffortCurve = null;
    const result = modifyRollingStockElectricalValues(
      currentRollingStockValues,
      isElectric(prevRsEffortCurve),
      isElectric(electricRsEffortCurve)
    );
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+  });
+  it('should NOT add anything if a thermal mode is added', () => {
+    const currentRollingStockValues = newEmptyRollingStock;
+    const prevRsEffortCurve = null;
+    const rsEffortCurve = getDefaultRollingStockMode('thermal');
+    const result = modifyRollingStockElectricalValues(
+      currentRollingStockValues,
+      prevRsEffortCurve,
+      rsEffortCurve
+    );
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
    const result = modifyRollingStockElectricalValues(
      currentRollingStockValues,
      isElectric(prevRsEffortCurve),
      isElectric(thermalRsEffortCurve)
    );
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 12]
```diff
@@ -0,0 +1,86 @@
...
+    const expected = currentRollingStockValues;
+    expect(result).toEqual(expected);
+  });
+  it('should NOT modify rollingStockValues if previous effort is already electrical', () => {
+    const currentRollingStockValues = {
+      ...newEmptyRollingStock,
+      electricalPowerStartupTime: 123,
+      raisePantographTime: 456,
+    };
+    const prevRsEffortCurve = getDefaultRollingStockMode('1000');
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
    const prevRsEffortCurve = electricRsEffortCurve;
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 13]
```diff
@@ -0,0 +1,86 @@
...
+    prevRsEffortCurve.modes = {
+      ...prevRsEffortCurve.modes,
+      '15000': makeTractionMode('15000'),
+    };
+    const rsEffortCurve = getDefaultRollingStockMode('1000');
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
    const rsEffortCurve = electricRsEffortCurve;
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 14]
```diff
@@ -0,0 +1,86 @@
...
+    const result = modifyRollingStockElectricalValues(
+      currentRollingStockValues,
+      prevRsEffortCurve,
+      rsEffortCurve
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
      isElectric(prevRsEffortCurve),
      isElectric(rsEffortCurve)
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 15]
```diff
@@ -0,0 +1,86 @@
...
+    const expected = currentRollingStockValues;
+    expect(result).toEqual(expected);
+  });
+  it('should remove the electricalPowerStartupTime and raisePantographTime values if we previously had an electrical and it was removed', () => {
+    const currentRollingStockValues = {
+      ...newEmptyRollingStock,
+      electricalPowerStartupTime: 123,
+      raisePantographTime: 456,
+    };
+    const prevRsEffortCurve = getDefaultRollingStockMode('1000');
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
    const prevRsEffortCurve = electricRsEffortCurve;
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 16]
```diff
@@ -0,0 +1,86 @@
...
+    const rsEffortCurve = {
+      ...prevRsEffortCurve,
+      modes: {},
+    };
+    const result = modifyRollingStockElectricalValues(
+      currentRollingStockValues,
+      prevRsEffortCurve,
+      rsEffortCurve
```
Comment (SarahBellaha) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
      isElectric(prevRsEffortCurve),
      isElectric(rsEffortCurve)
```

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 7 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: Ok I can create 2 variables, but I don’t really want to change the function signature, I think it’s better hidden inside the function.

File: editoast/src/main.rs (hunk 1 above)
Comment (anisometropie) [reply editoast/src/main.rs]: done in RollingStockModel

File: editoast/src/views/rolling_stocks/mod.rs (hunk 3 above)
Comment (anisometropie) [reply editoast/src/views/rolling_stocks/mod.rs]: deleted since

File: editoast/src/main.rs (hunk 5 above)
Comment (anisometropie) [reply editoast/src/main.rs:765]: done

File: editoast/src/main.rs (hunk 4 above)
Comment (anisometropie) [reply editoast/src/main.rs]: done

File: editoast/src/main.rs [hunk 17]
```diff
@@ -374,18 +375,40 @@ async fn import_rolling_stock(
...
+                rolling_stock.version = Some(0);
+                let rolling_stock = rolling_stock.create(db_pool.clone()).await?;
+                info!(
+                    "✅ Rolling stock {}[{}] saved!",
+                    rolling_stock.name.clone().unwrap().bold(),
+                    rolling_stock.id.unwrap()
+                );
+            }
+            Err(e) => {
+                warn!("❌ Rolling stock was not created!");
```
Comment (flomonster) [inline editoast/src/main.rs]: Instead of using `warn!` and `println!` we can return a `CliError`.

File: editoast/src/models/rolling_stock/mod.rs (hunk 6 above)
Comment (anisometropie) [reply editoast/src/models/rolling_stock/mod.rs]: deleted

File: editoast/src/models/rolling_stock/mod.rs [hunk 18]
```diff
@@ -129,6 +132,35 @@ pub struct RollingStockModel {
     pub version: Option<i64>,
 }
 
+fn validate_rolling_stock(
+    rolling_stock: &RollingStockModel,
+) -> std::result::Result<(), ValidationError> {
+    let electric = rolling_stock.is_electric();
+    if electric {
```
Comment (flomonster) [inline editoast/src/models/rolling_stock/mod.rs]: One level of indentation can easily be removed.

```suggestion
    if !rolling_stock.is_electric() {
        return Ok(());
    }
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts (hunk 9 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts:7]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts (hunk 12 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]: careful when using the same reference and modifying afterward :)

File: editoast/src/views/rolling_stocks/mod.rs [hunk 19]
```diff
@@ -212,6 +213,9 @@ async fn create(
     query_params: Query<PostRollingStockQueryParams>,
 ) -> Result<Json<RollingStock>> {
     let mut rolling_stock: RollingStockModel = data.into_inner().into();
+    if let Err(e) = rolling_stock.validate() {
+        return Err(e.into());
+    }
```
Comment (flomonster) [inline editoast/src/views/rolling_stocks/mod.rs]:
```suggestion
   rolling_stock.validate()?; 
```

File: editoast/src/views/rolling_stocks/mod.rs [hunk 20]
```diff
@@ -241,6 +245,9 @@ async fn update(
     let version = existing_rolling_stock.version;
 
     let mut rolling_stock = data.into_rolling_stock_model(rolling_stock_id, version);
+    if let Err(e) = rolling_stock.validate() {
+        return Err(e.into());
+    }
```
Comment (flomonster) [inline editoast/src/views/rolling_stocks/mod.rs]:
```suggestion
   rolling_stock.validate()?; 
```

**Review by flomonster — APPROVED** [review]
LGTM. They're a few things to change. You should also run `cargo clippy --fix`.
Note: I only reviewed editoast.

**Review by SarahBellaha — APPROVED** [review]
LGTM 💪

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 21]
```diff
@@ -37,6 +41,30 @@ type RollingStockParametersProps = {
...
+    };
+  }
+  if (isPreviousElectric && !isCurrentElectric) {
+    return {
+      ...currentRollingStockValues,
+      electricalPowerStartupTime: null,
+      raisePantographTime: null,
+    };
+  }
+  return currentRollingStockValues;
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]:
```suggestion
  if (isPreviousElectric === isCurrentElectric) return currentRollingStockValues;
  if (isCurrentElectric) {
    return {
      ...currentRollingStockValues,
      electricalPowerStartupTime: DEFAULT_ELEC_POWER_STARTUP_TIME,
      raisePantographTime: DEFAULT_RAISE_PANTOGRAPH_TIME,
    };
  }
  return {
    ...currentRollingStockValues,
    electricalPowerStartupTime: null,
    raisePantographTime: null,
  };
```

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 22]
```diff
@@ -179,6 +219,16 @@ const RollingStockEditorForm = ({
...
+    } else if (
+      isElectric(currentRsEffortCurve) &&
+      !(rollingStockValues.electricalPowerStartupTime && rollingStockValues.raisePantographTime)
+    ) {
+      dispatch(
+        setFailure({
+          name: t('messages.invalidForm'),
+          message: t('messages.missingElectricStartupAndPantoTime'),
+        })
+      );
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: I would prefer that everything is handle in checkRollingStockFormValidity. Could move the validation there, and also adapt the invalidFields list (add electricalPowerStartupTime and raisePantographTime) ?

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 23]
```diff
@@ -37,6 +41,30 @@ type RollingStockParametersProps = {
...
+  prevRsEffortCurve: RollingStock['effort_curves'] | null,
+  currentRsEffortCurve: RollingStock['effort_curves'] | null
+) {
+  const isPreviousElectric = isElectric(prevRsEffortCurve);
+  const isCurrentElectric = isElectric(currentRsEffortCurve);
+  if (!isPreviousElectric && isCurrentElectric) {
+    return {
+      ...currentRollingStockValues,
+      electricalPowerStartupTime: DEFAULT_ELEC_POWER_STARTUP_TIME,
+      raisePantographTime: DEFAULT_RAISE_PANTOGRAPH_TIME,
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: It's not a good thing to add these values by default, better set the fields to undefined or null so the user doesn't miss them

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 24]
```diff
@@ -238,13 +288,15 @@ const RollingStockEditorForm = ({
         <RollingStockEditorMetadataForm
           rollingStockValues={rollingStockValues}
           setRollingStockValues={setRollingStockValues}
+          currentRsEffortCurve={currentRsEffortCurve}
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: We should not give currentRsEffortCurve to this component, it does not need it
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx [hunk 25]
```diff
@@ -9,29 +9,34 @@ import {
...
   RollingStockSchemaProperties,
 } from 'modules/rollingStock/consts';
+import { RollingStock } from 'common/api/osrdEditoastApi';
 
 type RollingStockMetadataFormProps = {
   rollingStockValues: RollingStockParametersValues;
   setRollingStockValues: (
     rollingStockValue: React.SetStateAction<RollingStockParametersValues>
   ) => void;
+  currentRsEffortCurve: RollingStock['effort_curves'] | null;
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx]: The metadataform does not need the currentRsEffortCurve
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx [hunk 26]
```diff
@@ -272,6 +288,7 @@ export const RollingStockEditorParameterForm = ({
           rollingStockValues={rollingStockValues}
           setOptionValue={setOptionValue}
           setRollingStockValues={setRollingStockValues}
+          currentRsEffortCurve={currentRsEffortCurve}
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx:285]: No need for the currentRsEffortCurve in the parameterFormColumn
```suggestion
```

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx [hunk 27]
```diff
@@ -239,6 +252,7 @@ export const RollingStockEditorParameterForm = ({
   rollingStockValues,
   setOptionValue,
   setRollingStockValues,
+  currentRsEffortCurve,
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx:249]: Do you think it's better to have currentRsEffortCurve or a boolean isElectric ? Maybe isElectric is better ?

File: front/src/modules/rollingStock/helpers/utils.ts [hunk 28]
```diff
@@ -259,5 +245,27 @@ export const sortSelectedModeCurves = (curvesList: ConditionalEffortCurve[]) =>
   return allConds.concat(onlyPR, onlyEP, nulls);
 };
 
-export const isElectric = (rollingStock: RollingStock) =>
-  some(Object.values(rollingStock.effort_curves.modes), (effortCurve) => effortCurve.is_electric);
+export function makeTractionMode(
```
Comment (clarani) [inline front/src/modules/rollingStock/helpers/utils.ts]: I don't really like the name of this function, do you think this function is really necessary ?

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx [hunk 29]
```diff
@@ -37,6 +41,30 @@ type RollingStockParametersProps = {
   isAdding?: boolean;
 };
 
+export function modifyRollingStockElectricalValues(
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx:42]: Maybe it would be better to move this function to a helper file ?

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 30]
```diff
@@ -0,0 +1,90 @@
...
+      raisePantographTime: 456,
+    };
+    const prevRsEffortCurve = {
+      ...rsEffortCurve1000,
+      modes: {
+        ...rsEffortCurve1000.modes,
+        '15000': makeTractionMode('15000'),
+      },
+    };
+    const rsEffortCurve = { ...rsEffortCurve1000 };
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]: Why do you copy the var here ? It's not necessary

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts:1]: Can you remove all the variables duplication without any modification ?

**Review by clarani — COMMENTED** [review]
Thanks, left some comments

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 22 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 21 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 23 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: right, better with your system

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 24 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx]: used for the condition

**Review by Castavo — APPROVED** [review]
Tested it, works fine, still feels weird that the fields are filled silently while others are not
Only read editoast part

File: front/src/modules/rollingStock/helpers/utils.ts (hunk 28 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/helpers/utils.ts]: renamed to makeEffortCurve. It’s needed for the tests

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 29 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx:42]: I don’t think it’s ever going to be used anywhere else. it’s just for this component

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx (hunk 27 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx:249]: I need the effort curve as my system is generic

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx (hunk 29 above)
Comment (clarani) [reply front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorForm.tsx:42]: OK, I just wanted to reduce the number of lines of this component. You can resolve this comment

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 31]
```diff
@@ -0,0 +1,44 @@
...
+      ...newEmptyRollingStock,
+      electricalPowerStartupTime: null,
+      raisePantographTime: null,
+    };
+    expect(result).toEqual(expected);
+  });
+  it('should NOT do anything otherwise (electric)', () => {
+    const currentRollingStockValues = newEmptyRollingStock;
+    const rsEffortCurve = rsEffortCurve1000;
+    const result = modifyRollingStockElectricalValues(currentRollingStockValues, rsEffortCurve);
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]: You didn't answer the previous comment, do you want to remove the duplicated variables in this file ? (it's only a question)
```suggestion
    const result = modifyRollingStockElectricalValues(newEmptyRollingStock, rsEffortCurve1000);
```

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts [hunk 32]
```diff
@@ -0,0 +1,44 @@
...
+    const expected = newEmptyRollingStock;
+    expect(result).toEqual(expected);
+  });
+  it('should NOT do anything otherwise (thermal)', () => {
+    const currentRollingStockValues = newEmptyRollingStock;
+    const rsEffortCurve = rsEffortCurveThermal;
+    const result = modifyRollingStockElectricalValues(currentRollingStockValues, rsEffortCurve);
```
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]:
```suggestion
    const result = modifyRollingStockElectricalValues(newEmptyRollingStock, rsEffortCurveThermal);
```

File: front/src/modules/rollingStock/helpers/__tests__/utils.spec.ts
Comment (clarani) [inline front/src/modules/rollingStock/helpers/__tests__/utils.spec.ts:1]: Nice tests !

File: front/src/modules/rollingStock/helpers/utils.ts [hunk 33]
```diff
@@ -120,84 +106,78 @@ export const getRollingStockEditorDefaultValues = (
...
-        ? [...result, field]
-        : result,
-    [] as string[]
-  );
+  const conditions = RollingStockSchemaProperties.reduce<Conditions>((acc, val) => {
+    if (val.condition) {
+      return { ...acc, [val.title]: val.condition };
+    }
+    return acc;
+  }, {});
```
Comment (clarani) [inline front/src/modules/rollingStock/helpers/utils.ts:163]: I find this quite abstract/ not readable to get only the dict `{electricalPowerStartupTime: isElectric, raisePantographTime: isElectric}`... I don't have any suggestion, it's just a remark, in case you have an idea to improve this

Comment (anisometropie) [reply front/src/modules/rollingStock/helpers/utils.ts:163]: leaving it like this as discussed

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts (hunk 32 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts (hunk 31 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts]: done

File: front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts:1]: done !

**Comment by anisometropie** [comment]
> Tested it, works fine, still feels weird that the fields are filled silently while others are not Only read editoast part

@Castavo changed that behavior too, all fields work the same now !

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark:
