### PR TITLE
front: bump nge (temporary fix unique nodes names)

### LINKED ISSUE #13869: error when creating multiple nodes in macro mode
### What happened?

When I create several macro nodes, I get these errors 

https://github.com/user-attachments/assets/5d460651-9479-4554-8450-28e4ccfd7336

After refreshing, the macro nodes disappear. 
But if I change the name of one of the nodes before refreshing, this node remains

### What did you expect to happen?

I expected to have no error and to keep my nodes

### How can we reproduce it (as minimally and precisely as possible)?

Create multiple nodes without renaming them (keybord shortcut : inser)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

9beb1f1

### PR DESCRIPTION
**Pull request by louisgreiner**
Ref this PR in fork: https://github.com/osrd-project/netzgrafik-editor-frontend/pull/21

Close https://github.com/OpenRailAssociation/osrd/issues/13869 ,https://github.com/OpenRailAssociation/osrd/issues/14386

Enable https://github.com/OpenRailAssociation/osrd/pull/13860

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
LGTM, tested

**Review by clarani — APPROVED** [review]
LGTM, but the e2e tests are failing :/

**Comment by louisgreiner** [comment]
The issue about the e2e tests is related to this: https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/issues/658

A recent change on NGE's side modified this component, making it break this e2e test

**Comment by louisgreiner** [comment]
The failed E2E test might be fixed by https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/issues/658

**Comment by louisgreiner** [comment]
Could also embed this: https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/pull/660#pullrequestreview-3562356774

**Review by Maymanaf — APPROVED** [review]

**Review by Khoyo — CHANGES_REQUESTED** [review]
The test fix should be squashed into the bump, to avoid having failing commit on the dev branch.

**Review by Khoyo — APPROVED** [review]

File: front/tests/pages/operational-studies/nge-page.ts [hunk 1]
```diff
@@ -48,12 +48,11 @@ class NGEPage extends OpSimulationResultPage {
     this.nodeSummaryTitle = this.ngeFrame.getByTestId('summary-title');
     this.deleteNodeButton = this.ngeFrame.getByTestId('delete-button');
     this.confirmDeleteButton = this.ngeFrame.getByTestId('confirm-button');
-    this.closeDialogButton = this.ngeFrame.getByRole('img', { name: 'Close Dialog' });
```
Comment (Synar) [inline front/tests/pages/operational-studies/nge-page.ts:51]: Was there no way to fix the role locator here rather than go for a css one?

Comment (Maymanaf) [reply front/tests/pages/operational-studies/nge-page.ts:51]: The change was made in NGE https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/commit/30fb09ad5b057c5569be844f50ef0b8fd95c669d , which removed the area label. The only way to unblock this PR for now is to fix the locator using the class
We can optimize this later by adding a `data-testid` in the NGE code
