### PR TITLE
Temporarily remove timeline, fix filter bug, fix signals pk

### LINKED ISSUE #5923: Search in project does not work
### What happened?

When we search in the projects nothing happens

### What did you expect to happen?

the search to work

### How can we reproduce it (as minimally and precisely as possible)?

write something in the searchbar --> Nothing happens
Image

### What operating system, browser and environment are you using?

- **Browser**: Chrome v109
- **OS**: MacOS Venture 13.4.1
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

3df6fbc

### PR DESCRIPTION
**Pull request by nicolaswurtz**
- Timeline was faulty, and unusable with too much train. It's just hidden for now, for the time when we'll upgrade it ;)
- close #5923 #5996

### CODE REVIEW

**Review by anisometropie — APPROVED** [review]

File: front/src/applications/operationalStudies/views/SimulationResults.tsx [hunk 1]
```diff
@@ -131,15 +131,15 @@ export default function SimulationResults({
         </div>
       </div>
 
-      {/* SIMULATION : TIMELINE */}
+      {/* SIMULATION : TIMELINE — TEMPORARELY DESACTIVATED
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/views/SimulationResults.tsx]:
```suggestion
      {/* SIMULATION : TIMELINE — TEMPORARELY DEACTIVATED
```

**Review by clarani — APPROVED** [review]
LGTM ! Tested :white_check_mark:

File: front/src/applications/operationalStudies/views/SimulationResults.tsx (hunk 1 above)
Comment (nicolaswurtz) [reply front/src/applications/operationalStudies/views/SimulationResults.tsx]: done !
