### PR TITLE
front: fix via added by map click not updated

### LINKED ISSUE #7929: Can't edit a via that has been selected by map click
### What happened?

https://github.com/OpenRailAssociation/osrd/assets/113104137/6349d2d2-f8cf-4b5b-8c5d-8c7b2c57146d

### What did you expect to happen?

We should be able to edit this kind of via aswell

### How can we reproduce it (as minimally and precisely as possible)?

See video

### What operating system, browser and environment are you using?

- **Browser**: Firefox 126
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev bbab375

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7929

### CODE REVIEW

File: front/src/modules/timesStops/utils.ts [hunk 1]
```diff
@@ -25,11 +25,28 @@ export const formatSuggestedViasToRowVias = (
...
+          theoreticalMargin: correspondingOp.theoreticalMargin,
+        };
+      }
+    }
+    return {
+      ...op,
+      isMarginValid: op.theoreticalMargin ? marginRegExValidation.test(op.theoreticalMargin) : true,
+      onStopSignal: op.onStopSignal || false,
+      arrival: i === 0 ? startTime?.substring(11, 19) : op.arrival,
+    };
```
Comment (Yohh) [inline front/src/modules/timesStops/utils.ts]: instead of nesting condition and give 2 returns, can't you manage `isMarginValid` , `onStopSignal` and `arrival` then return the result?

Comment (SharglutDev) [reply front/src/modules/timesStops/utils.ts]: I could propose you that but I think I prefer the first syntax. Do you have another idea ? 

```
  return formattedOps.map((op, i) => {
    let opToFormat = {
      ...op,
      isMarginValid: op.theoreticalMargin ? marginRegExValidation.test(op.theoreticalMargin) : true,
      onStopSignal: op.onStopSignal || false,
      arrival: i === 0 ? startTime?.substring(11, 19) : op.arrival,
    };
    if (!('uic' in op)) {
      const correspondingOp = pathSteps.find((step) => step.id === op.opId);
      if (correspondingOp) {
        opToFormat = {
          ...opToFormat,
          name: op.name || t('waypoint', { id: op.opId }),
          arrival: i === 0 ? startTime?.substring(11, 19) : correspondingOp.arrival,
          stopFor: correspondingOp.stopFor,
          theoreticalMargin: correspondingOp.theoreticalMargin,
        };
      }
    }

    return opToFormat;
  });
```

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/modules/timesStops/utils.ts (hunk 1 above)
Comment (SarahBellaha) [reply front/src/modules/timesStops/utils.ts]: Maybe something like that ?

```suggestion
    const correspondingOp = pathSteps.find((step) => step.id === op.opId);
    const isMarginValid = op.theoreticalMargin
      ? marginRegExValidation.test(op.theoreticalMargin)
      : true;
    const { arrival } = correspondingOp || op;
    const { onStopSignal } = correspondingOp || op;
    const { name } = correspondingOp || op;

    return {
      ...op,
      isMarginValid,
      arrival: i === 0 ? startTime?.substring(11, 19) : arrival,
      onStopSignal: onStopSignal || false,
      name: name || t('waypoint', { id: op.opId }),
      ...(correspondingOp && {
        stopFor: correspondingOp.stopFor,
        theoreticalMargin: correspondingOp.theoreticalMargin,
      }),
    };
```

Comment (emersion) [reply front/src/modules/timesStops/utils.ts]: Alternatively, keep the current logic with 2 returns, and use a const for the `isMarginValid` field, since that's the only common one between the two cases?

```js
const isMarginValid = op.theoreticalMargin ? marginRegExValidation.test(op.theoreticalMargin) : true;
if (correspondingOp) {
  return {
    ...op,
    name: op.name || t('waypoint', { id: op.opId }),
    isMarginValid,
    // etc
  };
}

return {
  ...op,
  isMarginValid,
  // etc
};
```

Comment (Yohh) [reply front/src/modules/timesStops/utils.ts]: that's the way I was thinking about

Comment (SarahBellaha) [reply front/src/modules/timesStops/utils.ts]: I updated my suggestion ⏫

Comment (SharglutDev) [reply front/src/modules/timesStops/utils.ts]: I think for code readability/maintainability that it is still better with 2 returns. We have only one big condition between "has 'uic'" or not instead of a small condition for each properties which is harder to track which one comes from `op` or from `correspondingOp` . I can add @emersion suggestion to remove the repetition for isMarginValid.
Is that ok for all of you ?

Comment (Yohh) [reply front/src/modules/timesStops/utils.ts]: I disagree with both your readability/maintainability arguments, the solution proposed by @SarahBellaha seems to me cleaner and far more maintainable, anyway your solution and the one from @emersion are both functional, so feel free! it was just a suggestion

**Review by emersion — APPROVED** [review]
Sure, LGTM :)

**Review by Yohh — APPROVED** [review]
nice, LGTM :muscle:

**Review by SarahBellaha — APPROVED** [review]
LGTM :)

**Review by Akctarus — APPROVED** [review]
Tested, LGTM

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
