### PR TITLE
core: prevents path from taking the same track section twice

### LINKED ISSUE #7785: Train path projection fails with a 502
### What happened?

I imported 44 trains from BASIC. I want to visualize the simulation results but got an error 502 : `can not parse "project_path" to a i64` with this api call : http://localhost:4000/api/v2/train_schedule/project_path?infra=4&ids[]=133&ids[]=134&ids[]=135&ids[]=136&ids[]=137&ids[]=138&ids[]=139&ids[]=140&ids[]=141&ids[]=142&ids[]=143&ids[]=144&ids[]=145&ids[]=146&ids[]=147&ids[]=148&ids[]=149&ids[]=150&ids[]=151&ids[]=152&ids[]=153&ids[]=154&ids[]=155&ids[]=156&ids[]=157&ids[]=158&ids[]=159&ids[]=160&ids[]=161&ids[]=162&ids[]=163&ids[]=164&ids[]=165&ids[]=166&ids[]=167&ids[]=168&ids[]=169&ids[]=170&ids[]=171&ids[]=172&ids[]=173&ids[]=174&ids[]=175&ids[]=176

Editoast logs:

```
thread 'actix-rt|system:0|arbiter:2' panicked at src/views/v2/path/projection.rs:40:13:
assertion failed: track_index.insert(&track_range.track_section, index).is_none()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

### What did you expect to happen?

The simulation results should appear when i click on `use this path` button, on a train

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Import the following timetable [timetable_payload.json](https://github.com/user-attachments/files/15913510/timetable_payload.json)
3. We have a 502

### What operating system, browser and environment are you using?

- **Browser**: Chrome version 124.0.6367.202
- **OS**: Windows
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev 3f82d43

### PR DESCRIPTION
**Pull request by flomonster**
This check was already there but not for opposite direction.

close #7785

### CODE REVIEW

**Review by younesschrifi — APPROVED** [review]
LGTM

File: core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt [hunk 1]
```diff
@@ -308,8 +308,8 @@ fun validatePathfindingResponse(
         }
     }
 
-    val dirTracks = HashSet<Pair<String, EdgeDirection>>()
-    for (track in res.trackSectionRanges) dirTracks.add(Pair(track.trackSection, track.direction))
+    val dirTracks = HashSet<String>()
+    for (track in res.trackSectionRanges) dirTracks.add(track.trackSection)
     if (dirTracks.size != res.trackSectionRanges.size)
```
Comment (eckter) [inline core/src/main/kotlin/fr/sncf/osrd/api/api_v2/pathfinding/PathfindingBlocksEndpointV2.kt]: There's a mismatch with the name now

```suggestion
    val trackSet = HashSet<String>()
    for (track in res.trackSectionRanges) trackSet.add(track.trackSection)
    if (trackSet.size != res.trackSectionRanges.size)
```

**Review by eckter — APPROVED** [review]
