### PR TITLE
front: fix itinerary warning and timestops display

### LINKED ISSUE #8832: front: train edition: if the path is invalid but debug mode is available, the rest of the tabs think it's valid
### What happened?

When a train has an invalid path and the debug mode is available, the tab isn't shown in red and the schedule table is present.

In the video, at first, an example of the desired behavior, then the actual behavior

https://github.com/user-attachments/assets/a15e6e7b-da3d-4420-9c41-2b18e5960954

### What did you expect to happen?

I expect the form to behave the same way whether the PF is fully broken or whether the debug mode is available:
* pathfinding tab surrounded by a red border
* schedule table not available

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a train schedule on a path where for example the electrification is incompatible
2. Witness

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6edea6d

### PR DESCRIPTION
**Pull request by RomainValls**
closes #8832 

fix itinerary warning and timestops display when pathfinding error.

### CODE REVIEW

File: front/src/modules/timesStops/TimesStopsInput.tsx [hunk 1]
```diff
@@ -134,6 +137,10 @@ const TimesStopsInput = ({
   );
 
   useEffect(() => {
+    if (pathfindingState.error) {
+      setRows([]);
+      return;
+    }
```
Comment (theocrsb) [inline front/src/modules/timesStops/TimesStopsInput.tsx:143]: We don't want to display the itinerary in the 'schedules and stops' section when there is an incompatibility?

Comment (RomainValls) [reply front/src/modules/timesStops/TimesStopsInput.tsx:143]: I'm not sure about this. On @Castavo 's comment on the issue :  the PF is broken but the tab isn't red and the schedule table is present.

Comment (Castavo) [reply front/src/modules/timesStops/TimesStopsInput.tsx:143]: Yes, we discussed it with @maelysLeratRosso, allowing to set schedules and stops on a path a train can't actually use isn't desirable. 
There should be no difference in behavior whether the pathfinding failed because of the constraints or because the path is impossible.

**Review by theocrsb — APPROVED** [review]
LGTM and tested

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !
