### PR TITLE
front: editor - force reload of EditorSource when data changed

### LINKED ISSUE #5845: Editor : wrong cursor when add an object
## Description
The curson displayed on the map to add a buffer stop is the detector icon.

## How to reproduce 

1. Go to the editor
2. Select the detector editor tool
3. The icon displayed on the map to place the detector is the detector icon
4. Now go to the buffer stop editor tool
5. The icon displayed on the map to place the buffer stop is still the detector icon

## Version

dev b6ead5b

### PR DESCRIPTION
**Pull request by sim51**
Close #5845

### CODE REVIEW

File: front/src/common/Map/Layers/GeoJSONs.tsx [hunk 1]
```diff
@@ -405,17 +405,23 @@ export const EditorSource: FC<{
...
-        <Layer key={layer.id} {...layer} />
-      )
-    )}
-  </Source>
-);
+}> = ({ id, data, layers, layerOrder }) => {
+  const dataFingerPrint =
+    data.type === 'FeatureCollection'
+      ? data.features.map((f) => f.properties?.id).concat()
+      : data.properties?.id;
```
Comment (SharglutDev) [inline front/src/common/Map/Layers/GeoJSONs.tsx:412]: I don't understand the use for this const. data.properties.id is always `osrd/editor/new-signal-id`.
Is it to force to switch of the `key` between that and an empty array ?

**Review by SharglutDev — APPROVED** [review]
Tested in local and it works well. Left one comment

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
