### PR TITLE
front: delete added exceptions

### LINKED ISSUE #11475: Supprimer une occurrence ajoutée (+ tests)
- remove an added occurence after they are created, from the drop down menu

### PR DESCRIPTION
**Pull request by anisometropie**
fixes https://github.com/OpenRailAssociation/osrd/issues/11475

### CODE REVIEW

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts [hunk 1]
```diff
@@ -147,10 +143,29 @@ const useOccurrenceActions = ({
...
+
+    storePacedTrain(
+      pacedTrain.id,
+      updatedPacedTrainPayload,
+      timetableId!,
+      dispatch,
+      upsertTimetableItems,
+      removePacedTrains
+    );
+  }, []);
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts]: We probably should add this in the depths
```suggestion
  }, [pacedTrain.exceptions]);
```

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx [hunk 2]
```diff
@@ -110,6 +121,7 @@ const OccurrenceItem = ({
       title: t('occurrenceMenu.delete'),
       icon: <Trash />,
       onClick: () => {
+        deleteAddedException(occurrenceId);
```
Comment (clarani) [inline front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx]: very nit: what about occurrence.id ?
```suggestion
        deleteAddedException(occurrence.id);
```

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts (hunk 1 above)
Comment (anisometropie) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/hooks/useOccurrenceActions.ts]: done !

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark:

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx (hunk 2 above)
Comment (anisometropie) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx]: yes that’s where it comes from
```
  const {
    id: occurrenceId,
    trainName,
    rollingStock,
    startTime,
    disabled,
    exceptionChangeGroups,
  } = occurrence;
```

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx (hunk 2 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx]: I'm wondering if it's really useful to extract it from the occurrence. Maybe it's simpler to directly call it from the occurrence

Comment (clarani) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx]: Anyway, it's nit, you can close this conversation

Comment (anisometropie) [reply front/src/modules/trainschedule/components/Timetable/PacedTrain/OccurrenceItem.tsx]: ah yes I see, made the change
