### PR TITLE
front: fix markers display

### LINKED ISSUE #10395: Wrong marker for destination
### What happened?

https://github.com/user-attachments/assets/0ceaf07d-b458-412d-82a8-b7ff53023ef2

### What did you expect to happen?

The marker should be the one from destination

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce video

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### LINKED ISSUE #10406: The origin marker appears instead of the destination one
### What happened?

When starting with the destination this happens:

https://github.com/user-attachments/assets/f8268492-f981-493b-afd4-90d356772ed7

The marker is however correct once the origin is set.

### What did you expect to happen?

There should be an orange flag for the destination no matter the order of the actions

### How can we reproduce it (as minimally and precisely as possible)?

1. Only set a destination

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

9151b80

### PR DESCRIPTION
**Pull request by theocrsb**
fix #10406 and fix #10395

### CODE REVIEW

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx [hunk 1]
```diff
@@ -68,29 +69,28 @@ const formatPointWithNoName = (
...
           coordinates: cur.coordinates,
-          type: MARKER_TYPE.VIA,
+          type: MARKER_TYPE.DESTINATION,
           marker: cur,
-          imageSource: showStdcmAssets ? stdcmVia : viaSVG,
-          index,
+          imageSource: showStdcmAssets ? stdcmDestination : destinationSVG,
         });
-      } else if (index === pathSteps.length - 1) {
+      } else if (cur.pointType === MARKER_TYPE.VIA)
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: This last condition is not necessary ;)
```suggestion
      } else {
```

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx [hunk 2]
```diff
@@ -43,6 +46,30 @@ const ManageTrainSchedule = ({ trainIdToEdit }: ManageTrainScheduleProps) => {
   const origin = useSelector(getOrigin);
   const destination = useSelector(getDestination);
   const pathSteps = useSelector(getPathSteps);
+
+  const pathStepWithPointType = useMemo(
+    () =>
+      pathSteps.map((step, index, array) => {
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Instead of using a map and a compact l133, you can directly use a reduce here. Add in `acc` only the steps that are not null
```suggestion
      pathSteps.reduce((acc, step, index) => {
```

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx [hunk 3]
```diff
@@ -43,6 +46,30 @@ const ManageTrainSchedule = ({ trainIdToEdit }: ManageTrainScheduleProps) => {
   const origin = useSelector(getOrigin);
   const destination = useSelector(getDestination);
   const pathSteps = useSelector(getPathSteps);
+
+  const pathStepWithPointType = useMemo(
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]:
```suggestion
  const markersInformation = useMemo(
```

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx [hunk 4]
```diff
@@ -43,6 +46,30 @@ const ManageTrainSchedule = ({ trainIdToEdit }: ManageTrainScheduleProps) => {
...
+    () =>
+      pathSteps.map((step, index, array) => {
+        if (!step) return null;
+
+        let pointType;
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: nit: if you want to save 1 line, you can initiate `pointType` here and remove the last test
```suggestion
        let pointType = MARKER_TYPE.VIA;
```

File: front/src/applications/stdcm/utils/index.ts [hunk 5]
```diff
@@ -13,13 +16,23 @@ export const getTimesInfoFromDate = (date?: Date) =>
...
-  }, [] as MarkerInformation[]);
+export const extractMarkersInfo = (pathSteps: StdcmPathStep[]): MarkerInformation[] =>
+  pathSteps
+    .filter((step) => step.location)
+    .map((step, index, array) => {
+      let pointType;
+
+      if (index === 0) {
+        pointType = MARKER_TYPE.ORIGIN;
+      } else if (index === array.length - 1) {
```
Comment (clarani) [inline front/src/applications/stdcm/utils/index.ts]: Why use array instead of pathSteps here ?
```suggestion
      } else if (index === pathSteps.length - 1) {
```

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: The `reduce` war continues 🔫

File: front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx (hunk 1 above)
Comment (theocrsb) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/ManageTrainScheduleMap/ItineraryMarkers.tsx]: Done

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx (hunk 2 above)
Comment (theocrsb) [reply front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Done

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx (hunk 3 above)
Comment (theocrsb) [reply front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Done

File: front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx (hunk 4 above)
Comment (theocrsb) [reply front/src/applications/operationalStudies/views/ManageTrainSchedule.tsx]: Done

File: front/src/applications/stdcm/utils/index.ts (hunk 5 above)
Comment (theocrsb) [reply front/src/applications/stdcm/utils/index.ts]: Done

File: front/src/applications/stdcm/utils/index.ts [hunk 6]
```diff
@@ -13,13 +16,23 @@ export const getTimesInfoFromDate = (date?: Date) =>
...
-      acc.push({
-        coordinates: step.location.coordinates,
-        name: step.location.name,
-      });
-    }
-    return acc;
-  }, [] as MarkerInformation[]);
+export const extractMarkersInfo = (pathSteps: StdcmPathStep[]): MarkerInformation[] =>
+  pathSteps
+    .filter((step) => step.location)
```
Comment (clarani) [inline front/src/applications/stdcm/utils/index.ts]: As you filter before the map, you don't solve the issue here... It would be better either to filter after the map or to use a reduce

Comment (theocrsb) [reply front/src/applications/stdcm/utils/index.ts]: Done

**Comment by clarani** [comment]
image

Almost good I think. If I add a via in stdcm but no origin, then the icon is correct but the number in it is not correct

**Comment by theocrsb** [comment]
> image
> 
> Almost good I think. If I add a via in stdcm but no origin, then the icon is correct but the number in it is not correct

I just pushed a solution

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Review by Akctarus — APPROVED** [review]
lgtm
