### PR TITLE
front: fix day change banner in times stops table

### LINKED ISSUE #15953: Timestops table: D+1 banner displayed twice using non-simulated train
### What happened?

When using non-simulated train, the banner reacts weirdly

[timetable.json](https://github.com/user-attachments/files/26277453/timetable.json)

Image

### What did you expect to happen?

show the D+1 banner at the right place

@SharglutDev any technical tips?

edit by Sharglut : for now we put the banner based on the computed arrival but when simulation fails, we should fallback on the requested one. (maybe there is more to look for the double banner)

### How can we reproduce it (as minimally and precisely as possible)?

import the above train

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 8b88601

### LINKED ISSUE #15998: Timestops table: D+1 banner is not displayed on the last path step
### What happened?

The banner should be displayed before the last path step, but it isn't
Image

### What did you expect to happen?

D+1 banner should be displayed on the right row

### How can we reproduce it (as minimally and precisely as possible)?

create a train, change the destination arrival time so it pass a day

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev

### PR DESCRIPTION
**Pull request by Akctarus**
closes #15953 
closes #15998

### CODE REVIEW

File: front/src/modules/timesStops/TimesStopsTable.tsx [hunk 1]
```diff
@@ -452,11 +452,17 @@ const TimesStopsTable = ({
...
-  const getRowDayOffset = (row: Row<TimesStopsRowNew>) =>
-    calculateTimeDifferenceInDays(
-      startTime,
-      row.original.computedArrival ?? row.original.requestedArrival ?? undefined
-    ) ?? 0;
+  const getRowDayOffset = (row: Row<TimesStopsRowNew>): number | null => {
+    if (!row.original.isPathStep) return null;
+    const date = row.original.requestedArrival ?? row.original.computedArrival ?? undefined;
+    return calculateTimeDifferenceInDays(startTime, date) ?? null;
+  };
```
Comment (Yohh) [inline front/src/modules/timesStops/TimesStopsTable.tsx:500]: a little suggestion:

this is just a point of view, but I think that `calculateTimeDifferenceInDays()` shouldn't return `undefined`, its arguments shouldn't be optionnal, so we should change it this way:

```js
export function calculateTimeDifferenceInDays(datetime1: Date, datetime2: Date) {
  const date1 = new Date(datetime1.getFullYear(), datetime1.getMonth(), datetime1.getDate());
  const date2 = new Date(datetime2.getFullYear(), datetime2.getMonth(), datetime2.getDate());
  return dayjs.duration(date2.getTime() - date1.getTime()).asDays();
}
```

then change `getRowDayOffset()` this way:


```suggestion
  const getRowDayOffset = (row: Row<TimesStopsRowNew>): number | null => {
    if (!row.original.isPathStep) return null;
    const date = row.original.requestedArrival ?? row.original.computedArrival;
    if (!date) return null;
    return calculateTimeDifferenceInDays(startTime, date) ?? null;
  };
```
this way we avoid running `calculateTimeDifferenceInDays()` and we don't force `undefined` for the `date` const,

File: front/src/modules/timesStops/TimesStopsTable.tsx [hunk 2]
```diff
@@ -452,11 +452,17 @@ const TimesStopsTable = ({
...
+
+  const effectiveDayOffsets = table.getRowModel().rows.reduce<number[]>((acc, row, i) => {
```
Comment (Yohh) [inline front/src/modules/timesStops/TimesStopsTable.tsx]: `table.getRowModel().rows` is used here and l.502, and there is many inline logic in this file, we could extract this in a specific const to lighten the code, also those new blocks should be documented

File: front/src/modules/timesStops/TimesStopsTable.tsx [hunk 3]
```diff
@@ -452,11 +452,17 @@ const TimesStopsTable = ({
...
+    const rawOffset = getRowDayOffset(row);
+    acc.push(rawOffset !== null ? rawOffset : i > 0 ? acc[i - 1] : 0);
+    return acc;
+  }, []);
```
Comment (Yohh) [inline front/src/modules/timesStops/TimesStopsTable.tsx]: nested ternaries are painfull to read, I propose a more readable//maintainable solution:

```suggestion
  const effectiveDayOffsets = table.getRowModel().rows.reduce<number[]>((acc, row, i) => {
    const rawOffset = getRowDayOffset(row);
    if (rawOffset !== null) {
      acc.push(rawOffset);
    } else {
      const prevOffset = i > 0 ? acc[i - 1] : 0;
      acc.push(prevOffset);
    }
    return acc;
  }, []);
```

File: front/src/modules/timesStops/TimesStopsTable.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/timesStops/TimesStopsTable.tsx:500]: Thanks for these comments! all fixed in d0f2bdee7972004b5b267bcdf8cde24498999415

Comment (Yohh) [reply front/src/modules/timesStops/TimesStopsTable.tsx:500]: you forgot to modify `calculateTimeDifferenceInDays()`, also the final `getRowDayOffset()` return should now be `    return calculateTimeDifferenceInDays(startTime, date);`

Comment (Akctarus) [reply front/src/modules/timesStops/TimesStopsTable.tsx:500]: fixed in 5af2f5447d66e32dbb3c3ca7ceccdddbfcbbc3f9 and 731365ab9ae5f29bf55d0414e621bc1c7d9eb92d

File: front/src/modules/timesStops/TimesStopsTable.tsx [hunk 4]
```diff
@@ -452,11 +452,30 @@ const TimesStopsTable = ({
...
   );
 
-  const getRowDayOffset = (row: Row<TimesStopsRowNew>) =>
-    calculateTimeDifferenceInDays(
-      startTime,
-      row.original.computedArrival ?? row.original.requestedArrival ?? undefined
-    ) ?? 0;
+  const getRowDayOffset = (row: Row<TimesStopsRowNew>): number | null => {
+    if (!row.original.isPathStep) return null;
+    const date = row.original.requestedArrival ?? row.original.computedArrival;
```
Comment (SarahBellaha) [inline front/src/modules/timesStops/TimesStopsTable.tsx]: Shouldn't we use the `computedArrival` and fallback on the `requestedArrival` ?

Comment (Akctarus) [reply front/src/modules/timesStops/TimesStopsTable.tsx]: good catch! fixed b029a3bef51c7881e0b3a2e45f6bf3411e5eaf85

**Review by SarahBellaha — APPROVED** [review]
