### PR TITLE
front: fix map markers react warning for duplicate keys

### LINKED ISSUE #10810: React key warning for MapMarkers
### What happened?

Image

### What did you expect to happen?

No warning in console

### How can we reproduce it (as minimally and precisely as possible)?

Go to a scenario with train and open the console

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by SharglutDev**
fix #10810

### CODE REVIEW

File: front/src/common/Map/components/MapMarkers.tsx [hunk 1]
```diff
@@ -38,6 +38,7 @@ const MapMarkers = ({ markers }: MapMarkersProps) =>
         latitude={coordinates[1]}
         anchor="bottom"
         offset={MARKER_OFFSET}
+        key={`${coordinates[0]}-${coordinates[1]}-${index}`}
```
Comment (emersion) [inline front/src/common/Map/components/MapMarkers.tsx]: The index should be enough no?

Comment (SharglutDev) [reply front/src/common/Map/components/MapMarkers.tsx]: Safer the better ? :) Thought we should avoid to use `index` only when possible.

**Review by Synar — APPROVED** [review]
LGTM ^^

(I don't have an opinion on the index vs index+coord key, either choice seems fine to me)

File: front/src/common/Map/components/MapMarkers.tsx (hunk 1 above)
Comment (emersion) [reply front/src/common/Map/components/MapMarkers.tsx]: Why is that?

What if `coordinates` stay the same but other properties change?

Comment (SharglutDev) [reply front/src/common/Map/components/MapMarkers.tsx]: Fair enough :)

Comment (SharglutDev) [reply front/src/common/Map/components/MapMarkers.tsx]: Changed for `key={index}`

**Review by emersion — APPROVED** [review]
Thank you!
