### PR TITLE
editoast: conflicts train id core api communication refactor

### LINKED ISSUE #12086: editoast: paced train conflits endpoint TrainId refactor
### Description and goal

follow up from https://github.com/OpenRailAssociation/osrd/pull/11859#discussion_r2138103590

Improve or replace the way TrainId is transferred to the core. Currently, we rely on parsing a custom string format such as:
- {paced_train_id}@{exception_key}#{occurrence_index}
- {paced_train_id}#{occurrence_index}
- {train_id}

### PR DESCRIPTION
**Pull request by Wadjetz**
fix #12086

This PR refactors the way IDs are communicated to the core API. Instead of parsing a string ID, we generate a new ID and store the mapping in a hash map. We send this ID to the core, receive it back, and resolve the original train id using the hash map. This removes the need for a string-parsing system.

### CODE REVIEW

File: editoast/src/views/timetable.rs [hunk 1]
```diff
@@ -620,39 +625,50 @@ fn build_conflict_core_request(
...
+                    ..
+                } = match Arc::unwrap_or_clone(sim) {
+                    simulation::Response::Success(SimulationResponseSuccess {
+                        final_output,
+                        ..
+                    }) => Some(final_output),
+                    _ => None,
+                }?;
+
+                let train_id_for_core = Uuid::new_v4().to_string();
```
Comment (woshilapin) [inline editoast/src/views/timetable.rs]: Why do we need to `.to_string()` it? We could just have a `HashMap<Uuid, TrainId>`, isn’t it?

File: editoast/src/views/timetable.rs [hunk 2]
```diff
@@ -396,27 +398,30 @@ pub struct Conflict {
...
+        conflict: CoreConflict,
+        trains_map: &HashMap<String, TrainId>,
+    ) -> Result<Self> {
         let (train_schedule_ids, paced_train_occurrence_ids): (Vec<_>, Vec<_>) = conflict
             .train_ids
             .iter()
-            .partition_map(|train_id| match train_id.parse() {
-                Ok(TrainId::TrainSchedule(id)) => Either::Left(id),
-                Ok(TrainId::PacedTrain {
+            .partition_map(|train_id| match trains_map.get(train_id).cloned() {
```
Comment (woshilapin) [inline editoast/src/views/timetable.rs]: Since we’re both dealing with UUID coming back from `core` and `TrainId` from the `HashMap`, I suggest to be more explicit here in the name of the variables.

```suggestion
            .partition_map(|train_uuid| match trains_map.get(train_uuid).cloned() {
```

**Review by woshilapin — APPROVED** [review]

File: editoast/src/views/timetable.rs [hunk 3]
```diff
@@ -646,11 +651,11 @@ fn build_conflict_core_request(
...
                 }?;
 
-                let train_id_for_core = Uuid::new_v4().to_string();
-                trains_map.insert(train_id_for_core.clone(), train_id.clone());
+                let train_id_for_core = Uuid::new_v4();
+                trains_map.insert(train_id_for_core, train_id.clone());
 
                 Some((
-                    train_id_for_core,
+                    train_id_for_core.to_string(),
```
Comment (woshilapin) [inline editoast/src/views/timetable.rs]: Should we also update `ConflictDetectionRequest::trains_requirements` to take UUID (and maybe `Conflict::train_ids` too, for the response)? UUID can easily be serialized, so my guess is that we should be able to have only UUID in `editoast` code.

**Comment by flomonster** [comment]
> This PR refactors the way IDs are communicated to the core API. Instead of parsing a string ID, we generate a new ID and store the mapping in a hash map. We send this ID to the core, receive it back, and resolve the original train id using the hash map. This removes the need for a string-parsing system.

I'm happy to see this change since I wanted it when this was implemented in the first place. But @leovalais was against it, did it change?

**Comment by leovalais** [comment]
> But @leovalais was against it, did it change?

Not really, I still don't see the point of building and moving a map around when all the information is in the key itself. But if everyone likes it fine by me.

**Comment by flomonster** [comment]
> Not really, I still don't see the point of building and moving a map around when all the information is in the key itself. But if everyone likes it fine by me.

@woshilapin does not have a strong opinion on that. So let's merge it once all comments are closed.

File: editoast/src/views/timetable.rs (hunk 3 above)
Comment (woshilapin) [reply editoast/src/views/timetable.rs]: Can you please, next time, when you address a comment, answer to the comment to say:
1. it’s done
2. it’s not done and here is why
3. it’s done but in a different way because...

It would really help the review process. Thank you

Comment (Wadjetz) [reply editoast/src/views/timetable.rs]: I used a thumbs-up to say I’d handle it. I haven’t pushed the final changes to Conflict.train_ids yet

Comment (woshilapin) [reply editoast/src/views/timetable.rs]: Ok, thumbs-up does not generate a notification on Github system. And most other people use thumbs-up to mean « I read it and I agree ». So if you diverge in the semantic of what a thumbs-up is, then it’s not very easy to manage if everyone has a different behavior.

Also, a thumbs-up doesn’t generate a Github notification, a comment does, or a push. But too many times I saw a notification on one of your PR, there was a push, and after spending some time trying to understand what changed, I discover that it was only a rebase. If you were to start responding with comments, it would really ease the process.

And if the process of responding to every comment is too fastidious, you can always respond with one general comment, to just say you addressed all comments (some other developers do that).

Comment (leovalais) [reply editoast/src/views/timetable.rs]: Agreed, emojis are hard to track, also linking a fixup commit hash (or any relevant commit hash), or even a diff from a rebase also help a lot!

**Review by leovalais — APPROVED** [review]
