### PR TITLE
front: fix crash when reloading conflicts

### LINKED ISSUE #14668: front: error when transforming a paced train into a train schedule
### What happened?

Image

https://github.com/user-attachments/assets/35ee8bdf-05f2-4220-8139-cfb111530a80

### What did you expect to happen?

No error 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a mission with added occurence and an updated date
2. Transform the paced train into a train schedule

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

05cd31c

### PR DESCRIPTION
**Pull request by Synar**
Close https://github.com/OpenRailAssociation/osrd/issues/14668

Caused by stale conflicts being incompatible with fresh timetable items (for example when a paced train with exceptions is turned into a train schedule).

In this version we stop displaying conflicts while we are loading new ones. If we want to continue displaying the old conflicts while loading new ones, we can simply replace the useMemo by useState + useEffect (in order to display the old conflicts using the old timetable items). Tell me if you would prefer that.

~~We could also add a loading indication in the conflicts display.~~ -> there already was a loader but its display was broken. Fixed in the second commit.

(This pr has no bearing on https://github.com/OpenRailAssociation/osrd/issues/14504 afaik.)

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ScenarioContent.tsx [hunk 1]
```diff
@@ -74,7 +74,8 @@ const ScenarioContent = ({ activeBoards }: ScenarioContentProps) => {
     displayedConflicts,
   } = useConflictsFilter(
     useMemo(() => timetableItems || [], [timetableItems]),
-    conflicts
+    conflicts,
+    isConflictsLoading
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/ScenarioContent.tsx:78]: Maybe it would be simpler to pass this value instead?

```ts
useMemo(() => isConflictsLoading ? [] : conflicts, [isConflictsLoading, conflicts]),
```

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ScenarioContent.tsx:78]: Sure, that would also work (as long as we don't want to use the useState + useEffect version)!

**Comment by emersion** [comment]
It's not the first time we have this kind a desync issue when we try to mix data coming from multiple endpoints. It would be nice to come up with a better scheme for this. Maybe we could have something like this?

```ts
/**
 * Ensure multiple values are updated in lock-step.
 *
 * While ready is false, this hooks returns the previous value it returned, or
 * an empty array if it's called for the first time. When ready is true, this
 * hook returns its inputs.
 */
function useLockStep<T extends []unknown>(dependencies: T, ready: boolean): T | []

// usage:
const [lockedTrainSchedules, lockedConflicts] = useLockStep(
  [trainSchedules, conflicts],
  !trainSchedulesLoading && !conflictsLoading,
);
```

> we can simply replace the useMemo by useState + useEffect (in order to display the old conflicts using the old timetable items)

That would probably be a slightly better UX for users (maybe we should ask a PO?), especially since conflicts can take a while to load. We need to be careful about all data sources we're using though, maybe there's more than just train schedules?

**Comment by Synar** [comment]
> It's not the first time we have this kind a desync issue when we try to mix data coming from multiple endpoints. It would be nice to come up with a better scheme for this. Maybe we could have something like this?

Yes I think such a pattern could be nice! I fear it may be a typing nightmare though haha, so I would rather keep such a refactor for a later pr.

> maybe we should ask a PO?

Agreed! Maelys isn't here today, but I'll ask her tomorrow.

> since conflicts can take a while to load

Actually I doubled checked and we are supposed to have a loader being displayed while the conflicts are loading! It is however invisible, which looks like a bug. I'll investigate and fix it in this pr.


```ts
          <BoardWrapper
            hidden={!activeBoards.has('conflicts')}
            name={t('main.conflicts.conflictsCount', { count: totalConflictsCount })}
            withFooter
          >
            <div className="conflicts-wrapper">
              {isConflictsLoading ? (
                <Loader
                  msg={t('main.loadingConflicts')}
                  className="scenario-loader"
                  childClass="scenario-loader-msg"
                />
              ) : (
                <Conflicts
                  showOnlySelectedTrain={showOnlySelectedTrain}
                  onToggleFilter={handleToggleConflictsFilter}
                  selectedTrainName={selectedTrainName}
                  conflictsCount={selectedTrainConflictsCount}
                  displayedConflicts={displayedConflicts}
                />
              )}
            </div>
          </BoardWrapper>
```

So if we keep the loader the only thing that should be displayed currently while loading - and thus the only information for which we need to decide what to actually display  - is the conflict count. Although we could also position the loader on top of conflicts (rather than in their place), as is done elsewhere in the scenario page.

**Comment by Synar** [comment]
Loader display fixed in the second commit!

**Comment by emersion** [comment]
> I fear it may be a typing nightmare

I think it should be fine?

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdFwBrMOAdzAG0BdAPgAoAbGEqALkQwCUfLAG8AUIkQAnbFBBSknbgG4xAXzFiICbonoBDADSIARo0QBeZKlb0AjMYBE+kkWCPGA1drC79+vjAQAFsTbClLRH1vHShTEz5uKRgwAHNIk2UgA

Regardless, I'm completely fine with resetting conflicts in this PR and leaving the lockstep stuff for later.

**Comment by Synar** [comment]
> > I fear it may be a typing nightmare
> 
> I think it should be fine?
> 
> https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdFwBrMOAdzAG0BdAPgAoAbGEqALkQwCUfLAG8AUIkQAnbFBBSknbgG4xAXzFiICbonoBDADSIARo0QBeZKlb0AjMYBE+kkWCPGA1drC79+vjAQAFsTbClLRH1vHShTEz5uKRgwAHNIk2UgA

Oh very nice!

**Comment by Synar** [comment]
Seen with @maelysLeratRosso, displaying old conflicts under the loader while loading would be the best outcome ^^

File: front/src/modules/conflict/hooks/useConflictsFilter.ts [hunk 2]
```diff
@@ -68,13 +74,13 @@ const useConflictsFilter = (timetableItems: TimetableItem[], conflicts: Conflict
 
   const totalConflictsCount = useMemo(() => conflicts?.length ?? 0, [conflicts]);
 
-  const enrichedConflicts = useMemo(() => {
-    if (!conflicts) return [];
-    const sortedByStartTime = [...conflicts].sort(
+  useEffect(() => {
```
Comment (emersion) [inline front/src/modules/conflict/hooks/useConflictsFilter.ts:77]: Oh no, more `useEffect()` 😱

Oh well, I hope we can hide it in a shared helper hook in the future…

File: front/src/modules/conflict/hooks/useConflictsFilter.ts [hunk 3]
```diff
@@ -68,13 +74,13 @@ const useConflictsFilter = (timetableItems: TimetableItem[], conflicts: Conflict
...
+    if (isConflictsLoading) return;
+    const sortedByStartTime = [...(conflicts ?? [])].sort(
```
Comment (emersion) [inline front/src/modules/conflict/hooks/useConflictsFilter.ts:79]: Nit: I think this can be `conflicts!`: if conflicts are not loading, we should have something in there.

**Review by emersion — APPROVED** [review]
Feel free to resolve/ignore the nit.

File: front/src/modules/conflict/hooks/useConflictsFilter.ts (hunk 3 above)
Comment (Synar) [reply front/src/modules/conflict/hooks/useConflictsFilter.ts:79]: Sure! ^^

Comment (Synar) [reply front/src/modules/conflict/hooks/useConflictsFilter.ts]: Actually this breaks as isConflictsLoading is false when the request has not yet been initialized, such as while we are still loading the simulations.

To solve this, we can do "const isConflictsLoading = isUninitialized || isFetching;" instead. This will also displays the loader instead of an empty conflicts array in the conflicts widget while we are busy loading simulations, which seems like a good change (validated with Maelys). 

(Also isLoading can only be true if isFetching is true, so it was redundant)

Comment (Synar) [reply front/src/modules/conflict/hooks/useConflictsFilter.ts]: Done in a new commit (as it's an observable behavior change)

Comment (Synar) [reply front/src/modules/conflict/hooks/useConflictsFilter.ts]: (But indeed this proves that your suggestion was good, as doing it unearthed an actual issue ^^)

Comment (emersion) [reply front/src/modules/conflict/hooks/useConflictsFilter.ts]: Oh yeah, good catch!

**Review by emersion — APPROVED** [review]
LGTM!
