### PR TITLE
front: flatten and actually virtualize the train list

### LINKED ISSUE #14908: virtualization not working in train schedule set mode
### What happened?

See this PR [comment](https://github.com/OpenRailAssociation/osrd/pull/14852#discussion_r2731371911).

The virtualizer doesn't handle well the nesting of `CalendarTrainList`. Train schedule set tabs are properly virtualized but not the train schedule inside them.

### What did you expect to happen?

Fix this by reworking the nesting architecture of train schedule set tabs and train schedule inside them

### How can we reproduce it (as minimally and precisely as possible)?

Not really reproducible right now since we can't add new tss in the scenario.

### On which environments the bug occurs?

Recette (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by Signez**
Fixes #14908.

To allow the train list to be virtualized again, we have to respect the Rules Of The Virtualizer™: _the numerous children shall be their direct descendant_.

This pull request is a somewhat naive attempt to do that: this morph the `CalendarTrainList` into a simple `TrainList` that handle both cases, removing complexity from `Timetable` but adding some to that new `TrainList`.

I am not _that_ satisfied with the pack of new props I had to inject… it would really benefit from either lifting up the `TrainScheduleSet` creation to the `Timetable` component (through a function prop) or merging those props into a context-like one, but honestly I feel that it's good enough to be merge _as is_ if we want to, keeping it mind that a clean-up refactoring task later would be appreciated. I defer to the judgment of my fellow reviewers on that, and I am ready to implement either of these solutions, or to take the responsibility for that follow-up if we want to merge this first.

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Thanks for this work, LGTM

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx [hunk 1]
```diff
@@ -138,55 +138,58 @@ const TrainList = ({
     []
   );
 
+  const trainsToItems = (timetableItems: PacedTrainWithDetails[]) =>
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx]: This should probably be memoized with a `useMemo`. 

I'm afraid all the computation needed for the list (even with a working virtualization) might be heavy and we should avoid to rerender it to often (even though it will require a lot of variables in the deps).
For example, switching between calendar and tss mode multiple times is pretty laggy.

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx [hunk 2]
```diff
@@ -40,6 +53,23 @@ type TrainListProps = {
...
+    typeof useScenarioTrainScheduleSet
+  >['publishTrainScheduleSet'];
+  getTrainScheduleSetByCatalogAndName: ReturnType<
+    typeof useScenarioTrainScheduleSet
+  >['getTrainScheduleSetByCatalogAndName'];
+  localCopyTrainScheduleSet: ReturnType<
+    typeof useScenarioTrainScheduleSet
+  >['localCopyTrainScheduleSet'];
+  updateTrainScheduleSet: ReturnType<typeof useScenarioTrainScheduleSet>['updateTrainScheduleSet'];
+  removeTrainScheduleSet: ReturnType<typeof useScenarioTrainScheduleSet>['removeTrainScheduleSet'];
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx:70]: As you said in the PR description, this feels pretty nasty.

Totally agree for a follow up refacto PR :)

**Review by SharglutDev — COMMENTED** [review]
Great job, the virtualization works perfectly now !

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx (hunk 1 above)
Comment (Signez) [reply front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx]: Done! It seems to help, switch times between those modes seems to improve drastically.

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx:70]: Would you mind creating an issue (in the openrail association repo) for this refacto ? (and add it to the enhancement [board](https://github.com/orgs/osrd-project/projects/30/views/1))

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, great job !

File: front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx (hunk 2 above)
Comment (Signez) [reply front/src/applications/operationalStudies/views/Scenario/components/Timetable/TrainList.tsx:70]: [Here we go!](https://github.com/OpenRailAssociation/osrd/issues/15776)
