### PR TITLE
front: allowances: fix display of labels in stdcm

### LINKED ISSUE #4208: front: fix duplicated allowance labels and wrong allowance components variable names
### What happened?

in STDCM allowance's labels are duplicated
in InputGroupSNCF and InputSNCF some variables are directly related to the term STDCM

### What did you expect to happen?

only one label should be displayed
InputSNCF and InputGroupSNCF should not refer to such a kind of term

### How can we reproduce it (as minimally and precisely as possible)?

1. got to STDCM
2. select a scenario

### What operating system, browser and environment are you using?

- **Browser**: Firefox
- **OS**: Ubuntu 23.04
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

?

### PR DESCRIPTION
**Pull request by Yohh**
close #4208

### CODE REVIEW

File: front/src/applications/operationalStudies/components/SimulationResults/Allowances/StandardAllowanceDefault.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ interface StandardAllowanceDefaultProps {
     value: number;
   };
   getAllowanceTypes?: (typeKey: string) => AllowanceType[];
-  isStdcm?: boolean;
+  isCondensed?: boolean;
```
Comment (clarani) [inline front/src/applications/operationalStudies/components/SimulationResults/Allowances/StandardAllowanceDefault.tsx:48]: I think this is better :) What do you think @Math-R ?
```suggestion
  isCondensed: boolean = false;
```

**Review by clarani — APPROVED** [review]
Only one suggestion :) LGTM otherwise !
