### PR TITLE
Fix unrecognized waypoints display in schedule sheet

### LINKED ISSUE #16387: Non recognized waypoint line should be grey
### What happened?

The background of the line of a non recogized waypoint (here Zürich or Basel) should be in grey : 

Image

Here, there is no background

### What did you expect to happen?

I expect a grey background for non recognized waypoints 
See Berlin on mockup : 

Image

### How can we reproduce it (as minimally and precisely as possible)?

Create a train with non recognized waypoints (using the macro editor for example)

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

ee2f84f

### PR DESCRIPTION
**Pull request by Caracol3**
close #16387 

> [!NOTE]
> I had to update `invalidPathStep` in `useTimesStopsTableData` because without it, waypoints added on the map were considered invalid path steps by the table

### CODE REVIEW

File: front/src/modules/timesStops/hooks/useTimesStopsTableData.ts [hunk 1]
```diff
@@ -324,7 +324,7 @@ const useTimesStopsTableData = (
           startDate,
           schedule,
           computedArrival,
-          invalidPathStep: !matchingOp,
+          invalidPathStep: !matchingOp && 'operational_point' in pathStep.location,
```
Comment (SharglutDev) [inline front/src/modules/timesStops/hooks/useTimesStopsTableData.ts]: We now have this new model to avoid using `in` :)
```suggestion
          invalidPathStep:
            !matchingOp && pathStepLocation.type === 'operational_point_part_reference',
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅ 

You can close the comment when fixed.

**Review by achrafmohye — APPROVED** [review]
LGTM and tested

File: front/src/modules/timesStops/hooks/useTimesStopsTableData.ts (hunk 1 above)
Comment (Caracol3) [reply front/src/modules/timesStops/hooks/useTimesStopsTableData.ts]: Done

**Comment by Synar** [comment]
Validated
