### PR TITLE
editoast: provide details when pathfinding failed

### LINKED ISSUE #8038: editoast: error pathfinding_not_found has not the details provided by core
### What happened?

The error is not has precise has the one provided by core

### What did you expect to happen?

We should be able to have this :
image

### How can we reproduce it (as minimally and precisely as possible)?

1. not sure

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging de8ada8

### PR DESCRIPTION
**Pull request by younesschrifi**
Close #8038

### CODE REVIEW

**Review by woshilapin — APPROVED** [review]

File: editoast/src/core/pathfinding.rs [hunk 1]
```diff
@@ -91,18 +95,32 @@ pub enum PathfindingResult {
...
     InvalidPathItems {
-        #[schema(inline)]
         items: Vec<InvalidPathItem>,
     },
     NotEnoughPathItems,
     RollingStockNotFound {
         rolling_stock_name: String,
     },
-    PathfindingFailed {
+    PathfindingCoreError {
```
Comment (woshilapin) [inline editoast/src/core/pathfinding.rs]: `PathfindingCoreResult::PathfindingCoreError` is a bit redundant. Not really necessary to repeat the name of the type in the variant. If we're renaming it, let's make it better? If I understand well, it's a proxy for error we don't understand? Maybe be `UnknownError` or `InternalError` is fine?

**Review by woshilapin — APPROVED** [review]
In general, I realize that every (or almost every) `struct` in the module `pathfinding` are prefixed with `Pathfinding` which is somewhat redundant. We might want to fix that but in another PR (hence I put a comment that don't need to be resolved). cc @leovalais 

Apart from that, thank you for this PR, I'm always amazed by what this application will bring to debuggability of pathfinding (and simulation) errors.

File: editoast/src/core/pathfinding.rs (hunk 1 above)
Comment (leovalais) [reply editoast/src/core/pathfinding.rs]: Agreed. Also, following a discussion we had on the `editoast` channel on matrix we agreed on not including `Core` in the names of definitions in the `core` module as it's redundant. Wdyt of `PathfindingResult::InternalError` instead?

File: editoast/src/core/pathfinding.rs
Comment (leovalais) [inline editoast/src/core/pathfinding.rs:1]: Is `derive(Serialize)` really necessary for all these definitions?

File: editoast/src/core/pathfinding.rs [hunk 2]
```diff
@@ -91,18 +95,32 @@ pub enum PathfindingResult {
...
+}
+
+#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema)]
+#[serde(tag = "failed_status", rename_all = "snake_case")]
+pub enum PathfindingFailed {
+    InputError(PathfindingInputError),
+    NotFound(PathfindingNotFound),
+    CoreError(PathfindingCoreError),
+}
+
```
Comment (leovalais) [inline editoast/src/core/pathfinding.rs]: I feel like these definitions are more related to the endpoints API rather than core. I'd suggest moving these definitions and the conversion in the `views` module.

I'm also a bit weirded out by the past tense here (but maybe it's just me 😅), wdyt about `PathfindingFailure` instead?

File: editoast/src/views/path/pathfinding.rs [hunk 3]
```diff
@@ -278,15 +287,22 @@ pub async fn pathfinding_from_train_batch(
     train_schedules: &[TrainSchedule],
     rolling_stocks: &HashMap<String, RollingStockModel>,
 ) -> Result<Vec<PathfindingResult>> {
-    let mut results = vec![PathfindingResult::NotEnoughPathItems; train_schedules.len()];
+    let mut results = vec![
+        PathfindingResult::Failed(PathfindingFailed::InputError(
+            PathfindingInputError::NotEnoughPathItems
+        ));
+        train_schedules.len()
+    ];
```
Comment (leovalais) [inline editoast/src/views/path/pathfinding.rs]: I believe keeping a `Vec<PathfindingInputError>` and performing the conversion into a `PathfindingResult` just before returning would be easier to read. Wdyt?

**Review by leovalais — CHANGES_REQUESTED** [review]
Thanks for this PR! LGTM on the `views` side, but I think there's too much logic in the `core` module. I agree with @woshilapin about the redundancy of the prefix, and I'm fine with changing that in another PR. I'll test this later.

File: front/public/locales/en/operationalStudies/scenario.json [hunk 4]
```diff
@@ -53,8 +53,8 @@
     "filterLabel": "Name, label",
     "importTrainSchedule": "Import",
     "invalid": {
-      "pathfinding_not_found": "Pathfinding not found",
-      "pathfinding_failed": "Pathfinding failed",
+      "not_found": "Pathfinding not found",
+      "failed": "Pathfinding failed",
```
Comment (Akctarus) [inline front/public/locales/en/operationalStudies/scenario.json]: Why did you rename them ? Since we have `simulation_failed` and `rolling_stock_not_found` below, I think it's more readable to keep the `pathfinding` prefix

File: front/src/modules/pathfinding/hooks/usePathfinding.ts [hunk 5]
```diff
@@ -228,7 +228,9 @@ export const usePathfinding = (
 
           if (
             pathfindingResult.status === 'success' ||
-            pathfindingResult.status === 'incompatible_constraints'
+            (pathfindingResult.status === 'failed' &&
+              pathfindingResult.failed_status === 'not_found' &&
+              pathfindingResult.error_type === 'incompatible_constraints')
```
Comment (Akctarus) [inline front/src/modules/pathfinding/hooks/usePathfinding.ts]: Since you use this condition 2 times, you can create a `const` for it, and use this instead

**Review by Akctarus — COMMENTED** [review]
Tested, left few comments

File: editoast/src/views/path/pathfinding.rs (hunk 3 above)
Comment (leovalais) [reply editoast/src/views/path/pathfinding.rs]: As discussed, it doesn't bring much and adds a new conversion step. Resolving.

**Review by Akctarus — APPROVED** [review]
LGTM for the front part, not tested yet

**Review by Akctarus — APPROVED** [review]
LGTM

File: front/src/common/api/generatedEditoastApi.ts [hunk 6]
```diff
@@ -2449,46 +2433,74 @@ export type PathItemLocation =
...
+      rolling_stock_name: string;
+    };
+export type OffsetRange = {
+  end: number;
+  start: number;
+};
+export type IncompatibleOffsetRangeWithValue = {
+  range: OffsetRange;
+  value: string;
+};
```
Comment (SharglutDev) [inline front/src/common/api/generatedEditoastApi.ts:2458]: Is there any reason why this type can't extend `IncompatibleOffsetRange` with the `value` property ?

File: front/public/locales/fr/operationalStudies/scenario.json [hunk 7]
```diff
@@ -52,10 +52,16 @@
...
+      "not_found_in_tracks": "Voie manquante",
+      "incompatible_constraints": "Contraintes incompatibles",
       "pathfinding_not_found": "Chemin introuvable",
-      "pathfinding_failed": "Calcul non abouti",
+      "pathfinding_failure": "Calcul non abouti",
       "simulation_failed": "Simulation impossible",
-      "rolling_stock_not_found": "MR non trouvé"
+      "rolling_stock_not_found": "MR non trouvé",
+      "not_enough_path_items": "Point(s) de passage(s) manquants",
+      "invalid_path_items": "Point(s) de passage(s) invalides"
```
Comment (SharglutDev) [inline front/public/locales/fr/operationalStudies/scenario.json]: Could you order the keys alphabetically ? :)

Comment (SharglutDev) [inline front/public/locales/fr/operationalStudies/scenario.json]:
```suggestion
      "not_enough_path_items": "Point(s) de passage(s) manquant(s)",
      "invalid_path_items": "Point(s) de passage(s) invalide(s)"
```

File: front/public/locales/en/operationalStudies/scenario.json [hunk 8]
```diff
@@ -53,10 +53,16 @@
...
+      "not_found_in_tracks": "Missing track",
+      "incompatible_constraints": "Incompatible constraints",
       "pathfinding_not_found": "Pathfinding not found",
-      "pathfinding_failed": "Pathfinding failed",
+      "pathfinding_failure": "Pathfinding failed",
       "simulation_failed": "Simulation failed",
-      "rolling_stock_not_found": "RS not found"
+      "rolling_stock_not_found": "RS not found",
+      "not_enough_path_items": "Not enough path items",
+      "invalid_path_items": "Invalid path items"
```
Comment (SharglutDev) [inline front/public/locales/en/operationalStudies/scenario.json]: Same here for key order

File: front/public/locales/en/operationalStudies/manageTrainSchedule.json [hunk 9]
```diff
@@ -104,7 +104,7 @@
     "not_found_in_routes": "Missing route",
     "not_found_in_tracks": "Missing track",
     "not_enough_path_items": "Missing parameters for pathfinding: Departure, Arrival, Rolling stock",
-    "pathfinding_failed": "No path found",
+    "pathfinding_core_error": "No path found",
```
Comment (SharglutDev) [inline front/public/locales/en/operationalStudies/manageTrainSchedule.json]: Do we use this key somewhere ?

File: front/src/modules/trainschedule/components/Timetable/consts.ts [hunk 10]
```diff
@@ -7,8 +7,13 @@ export const specialCodeDictionary: { [key: string]: string } = {
 export const invalidTrainValues: {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/Timetable/consts.ts]: Seems like we don't use that `const` anywhere in the app ? If we don't need it, you can remove it as well with the `InvalidReason` type which is used only here.

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Tested and it works great ! Left some comment

**Review by Erashin — APPROVED** [review]
Core part was very complex, good job navigating through it, thanks for that.. :D

File: front/src/common/api/generatedEditoastApi.ts (hunk 6 above)
Comment (younesschrifi) [reply front/src/common/api/generatedEditoastApi.ts:2458]: We can not do that in editoast.

Comment (SharglutDev) [reply front/src/common/api/generatedEditoastApi.ts:2458]: When you do that, it's the same thing as I'm thinking
image

This could be 
```suggestion
export type IncompatibleOffsetRangeWithValue = IncompatibleOffsetRange & {
  value: string;
};
```

But if it's complicated, it's not very important :slightly_smiling_face:

File: front/public/locales/en/operationalStudies/scenario.json [hunk 11]
```diff
@@ -53,8 +53,14 @@
...
+      "invalid_path_items": "Invalid path items",
+      "not_enough_path_items": "Not enough path items",
+      "not_found_in_blocks": "Missing block",
+      "not_found_in_routes": "Missing route",
+      "not_found_in_tracks": "Missing track",
+      "pathfinding_failure": "Pathfinding failed",
       "pathfinding_not_found": "Pathfinding not found",
-      "pathfinding_failed": "Pathfinding failed",
       "simulation_failed": "Simulation failed",
       "rolling_stock_not_found": "RS not found"
```
Comment (SharglutDev) [inline front/public/locales/en/operationalStudies/scenario.json]: rollingstock before simulation :)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job. You can resolve the last 2 comments when needed :)

File: editoast/src/core/pathfinding.rs [hunk 12]
```diff
@@ -9,15 +9,18 @@ use utoipa::ToSchema;
 
 use crate::core::{AsCoreRequest, Json};
 use crate::error::InternalError;
+use crate::views::path::pathfinding::PathfindingFailure;
+use crate::views::path::pathfinding::PathfindingResult;
```
Comment (leovalais) [inline editoast/src/core/pathfinding.rs]: We want `views` to depend on `core` for the split in crates, can we move the code that uses these definitions in `views` instead?

File: editoast/src/core/pathfinding.rs [hunk 13]
```diff
@@ -73,9 +76,9 @@ pub struct InvalidPathItem {
     pub path_item: PathItemLocation,
 }
 
-#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema)]
+#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
 #[serde(tag = "status", rename_all = "snake_case")]
-pub enum PathfindingResult {
+pub enum PathfindingCoreResult {
```
Comment (leovalais) [inline editoast/src/core/pathfinding.rs:79]: We already in the `core` module ;)

```suggestion
pub enum PathfindingResult {
```

File: editoast/src/views/path/pathfinding.rs [hunk 14]
```diff
@@ -66,6 +72,21 @@ struct PathfindingInput {
     rolling_stock_length: OrderedFloat<f64>,
 }
 
+#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, ToSchema)]
+#[serde(tag = "status", rename_all = "snake_case")]
+pub enum PathfindingResult {
+    Success(PathfindingResultSuccess),
+    Failed(PathfindingFailure),
```
Comment (leovalais) [inline editoast/src/views/path/pathfinding.rs]:
```suggestion
    Failure(PathfindingFailure),
```

for consistency

**Review by leovalais — APPROVED** [review]
LGTM, thanks for the changes! A few last modifications 🙏:

File: front/src/common/api/generatedEditoastApi.ts (hunk 6 above)
Comment (Khoyo) [reply front/src/common/api/generatedEditoastApi.ts:2458]: This is a generated file from Rust code. There are no such things as inheritance or type extensions in Rust. We can use tricks to have utoipa generate the openapi with it, but IMO it's not very useful since typescript doesn't care (and it adds complexity in the rust code)

File: editoast/src/core/pathfinding.rs (hunk 13 above)
Comment (younesschrifi) [reply editoast/src/core/pathfinding.rs:79]: PathfindingResult is already defined :(
