### PR TITLE
core: add a position bound when shifting envelope parts

### LINKED ISSUE #5574: core: assert triggered in `coastFromEnd`
### What happened?

An assertion failed in `CoastingGenerator.coastFromEnd`

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Reproduced on a private regression test 

### What operating system, browser and environment are you using?

- **OS**: Ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

c2b9acd3f56cf945aa77e553b07a21abf9e78a2c

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/osrd-project/osrd/issues/5574

### CODE REVIEW

**Review by Erashin — APPROVED** [review]

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java [hunk 1]
```diff
@@ -637,15 +637,16 @@ public EnvelopePart slice(
...
+     * Resulting positions are limited at maxPosition. */
+    public EnvelopePart copyAndShift(double positionDelta, double maxPosition) {
         var newPositions = new DoubleArrayList();
         var newSpeeds = new DoubleArrayList();
         var newTimeDeltas = new DoubleArrayList();
         newPositions.add(positions[0] + positionDelta);
         newSpeeds.add(speeds[0]);
         for (int i = 1; i < positions.length; i++) {
-            var p = positions[i] + positionDelta;
+            var p = Math.min(maxPosition, positions[i] + positionDelta);
```
Comment (multun) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: are you sure we don't need a lower bound too? If so, can you `assert positionDelta >= 0`?

**Review by multun — CHANGES_REQUESTED** [review]

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java (hunk 1 above)
Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: I added a lower bound

**Review by Khoyo — APPROVED** [review]

**Review by multun — APPROVED** [review]
