### PR TITLE
front: fix invalid category import

### LINKED ISSUE #13075: categories : no label added when importing a train schedule or paced train with a non recognized category
### What happened?

When I import a train schedule or a paced train with a category or sub-category which is not recognized, it should be stored in a label, but it is not currently

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

Import a json with toto category or toto subcategory

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

e45bf0c

### PR DESCRIPTION
**Pull request by Synar**
Close [#13075](https://github.com/OpenRailAssociation/osrd/issues/13075)

Also fix related type issues, see first 2 commits titles and descriptions.

### CODE REVIEW

File: front/src/modules/rollingStock/consts.ts [hunk 1]
```diff
@@ -11,17 +11,19 @@ export const ComfortLevels: Record<Comfort, Comfort> = {
...
-  ['FREIGHT_TRAIN', 'FREIGHT_TRAIN'],
-  ['FAST_FREIGHT_TRAIN', 'FAST_FREIGHT_TRAIN'],
-  ['NIGHT_TRAIN', 'NIGHT_TRAIN'],
-  ['TRAM_TRAIN', 'TRAM_TRAIN'],
-  ['TOURISTIC_TRAIN', 'TOURISTIC_TRAIN'],
-  ['WORK_TRAIN', 'WORK_TRAIN'],
-]);
+// Note that this check works for records, but not maps or enums, as they check that all keys are of the proper type,
+// but not that all possible keys are present.
+export const TrainMainCategoryDict: Record<TrainMainCategory, TrainMainCategory> = {
```
Comment (clarani) [inline front/src/modules/rollingStock/consts.ts:18]: Why not use an array ?

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx [hunk 2]
```diff
@@ -88,15 +88,39 @@ const ImportTimetableItemTrainsList = ({
...
+    if (labels.includes(unrecognizedCategoryLabel)) return labels;
+    return [...labels, unrecognizedCategoryLabel];
+  };
+
   const { pacedTrainsJsonData, trainSchedulesJsonData } = useMemo(
     () => ({
       pacedTrainsJsonData: pacedTrainsFromJsonData.map((pacedTrain) => ({
         ...pacedTrain,
         category: checkCategory(pacedTrain.category),
+        labels: buildLabels(pacedTrain.labels, pacedTrain.category),
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx:121]: Hum `pacedTrain.Category` can be a string here ? With the types, I thought it was only `TrainCategory | null | undefined`

File: front/src/modules/rollingStock/consts.ts (hunk 1 above)
Comment (Synar) [reply front/src/modules/rollingStock/consts.ts:18]: See the comment and the commit description. An array doesn't need to contain all possible values of its type to be valid, so we could have strictly less categories included than in the openapi type. 

Sidenote : I think the most sensible data structure would be an enum here, but then to ensure perfect coherence with the openapi type we need an additional, unused type, which is a bit weird and complex.

We also could allow the type to differ from the open api type and assume we'll realize mistakes through usage, but I would rather enforce open api coherence if it's not too costly.

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx (hunk 2 above)
Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx:121]: Yes, the types are lying a bit (and fixing it would be nice). We've casted the imported json to a type that doesn't allow strings earlier in the code, but we actually allow a fallback for jsons that still use a string here, for retro compatibility.

See this comment :

     // This condition is added for train imports that still use the old format: `category: string`

File: front/src/modules/rollingStock/consts.ts (hunk 1 above)
Comment (clarani) [reply front/src/modules/rollingStock/consts.ts:18]: Ok thanks, I got the nuance :)

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx (hunk 2 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx:121]: Can you add a TODO to correct the types please ?

**Review by clarani — APPROVED** [review]

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx (hunk 2 above)
Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx:121]: Sure!

File: front/src/modules/rollingStock/consts.ts (hunk 1 above)
Comment (emersion) [inline front/src/modules/rollingStock/consts.ts:18]: I don't think using a `Record` is a good idea here. Records don't retain key types, everything is converted to `string`. `Map` doesn't have this issue.

Comment (emersion) [reply front/src/modules/rollingStock/consts.ts:18]: Oh my, I just say the rest of the description. I'm not in love with this approach, but I don't see a better way.

Comment (Synar) [reply front/src/modules/rollingStock/consts.ts:18]: One thing we can do is use a different data structure in practice from the one used to validate api type coherence, either by deriving the practical data structure from the record, or by using a different data structure from the get go and deriving from it a type used only for api type validation. There's added complexity either way though.

File: front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx (hunk 2 above)
Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/ImportTimetableItem/ImportTimetableItemTrainsList.tsx:121]: Actually I just fixed them instead, the type change didn't have the snowball effect I thought it would have ^^
