### PR TITLE
front: fix speedsection extremities inversion

### LINKED ISSUE #6479: Invert the beginning and the end of a speedsection raise an error which break the infra
### What happened?

When we try to edit or create a speedsection, if we invert the beginning and the end of the speedsection, there is an error which break the infra.

### What did you expect to happen?

We should be able to define a speedsection in any direction on a track.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the Editor
2. start to create a new speedsection
3. select a track (it should produce your first and last point for the speedsection)
4. invert the beginning and the end of the speedsection and try to save your speedsection

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

a235b0d

### PR DESCRIPTION
**Pull request by SharglutDev**
close #6479

### CODE REVIEW

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx [hunk 1]
```diff
@@ -101,6 +101,16 @@ function getRangeEditionTool<T extends EditorRange>({
           async onClick({ state, setState, dispatch, infraID }) {
             const { initialEntity, entity } = state;
             if (!isEqual(entity, initialEntity)) {
+              // For each track in the speed section, check if the user dragged an extremity beyond the other one
+              // if he did, switch the values of each extremities
+              const trackRanges = entity.properties.track_ranges;
+              trackRanges?.forEach((track) => {
```
Comment (clarani) [inline front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Can you use a map ? Here you are mutating a object in an array, I'm not a big fan of mutability like this

**Review by clarani — CHANGES_REQUESTED** [review]

**Review by SarahBellaha — COMMENTED** [review]
Tested, it works fine 💪

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx (hunk 1 above)
Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Here you are mutating directly some state, you need to use setState

**Review by anisometropie — CHANGES_REQUESTED** [review]

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Yes, I kept the original logic because we do a cloneDeep() on the entity in the setState at line 140. 

It was to avoid cloning the state 2 times. Do you prefer if a start by cloneDeep() the entity and remove it from the setState at the bottom ?

Comment (anisometropie) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Ok i see what you wanted to do.

But I think you just need to use what’s already on line 120, here he is cloning the whole entity anyway, before feeding it to deepClone

entity.properties is already modified here, so just add your new track range here.

```
const newTrackRanges = track_ranges.map(_=> …)

const savedEntity =
  entityId && entityId !== entity.properties.id
   ? {
    ...entity,
      properties: { ...entity.properties, id: `${entityId}`, track_ranges: newTrackRanges },
   }
    : entity;
```

Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Actually I need to do that before the api call otherwise the infra breaks if the trackranges are bad (that's the point of this issue) but I'll figure something out

**Review by clarani — APPROVED** [review]
LGTM, thanks !! I tested and it works well :white_check_mark:

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx (hunk 1 above)
Comment (clarani) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: It's good for me, @anisometropie you can resolve it's fine for you too :)

**Review by flomonster — APPROVED** [review]
Only tested and it works fine

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx [hunk 2]
```diff
@@ -204,7 +204,25 @@ function getRangeEditionTool<T extends EditorRange>({
...
+        if (interactionState.type === 'moveRangeExtremity' && entity.properties.track_ranges) {
+          // after resizing a track range, check if the user dragged an extremity beyond the other one
+          // if he did, switch the values of each extremities
+          const updatedTrackIndex = interactionState.rangeIndex;
+          const updatedTrack = entity.properties.track_ranges[updatedTrackIndex];
+
+          if (updatedTrack.begin > updatedTrack.end) {
+            const currentBegin = updatedTrack.begin;
+            updatedTrack.begin = updatedTrack.end;
+            updatedTrack.end = currentBegin;
```
Comment (anisometropie) [inline front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: [updatedTrack.begin, updatedTrack.end] = [updatedTrack.end, updatedTrack.begin]

**Review by anisometropie — APPROVED** [review]

File: front/src/applications/editor/tools/rangeEdition/tool-factory.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/editor/tools/rangeEdition/tool-factory.tsx]: Oh didn't think about that, nice !

**Review by clarani — APPROVED** [review]
