### PR TITLE
core: fix identical positions when shifting envelope parts

### LINKED ISSUE #5426: core: assert error: "positions aren't strictly increasing"
### What happened?

This error was triggered when looking for STDCM paths in small_infra. Context: `EnvelopePart.copyAndShift`

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Run stdcm requests on small infra

### What operating system, browser and environment are you using?

- **OS**: Windows
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

205d4fd9722067ea6601d00f0e6678746465b917

### PR DESCRIPTION
**Pull request by eckter**
Fix #5426 

I couldn't quite reproduced it in a regression test, but I found a scenario that reproduced it and it was fixed after this change.

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java [hunk 1]
```diff
@@ -638,10 +639,26 @@ public EnvelopePart slice(
 
     /** Returns a new EnvelopePart, where all positions are shifted by positionDelta */
     public EnvelopePart copyAndShift(double positionDelta) {
-        var newPositions = new double[positions.length];
-        for (int i = 0; i < positions.length; i++)
-            newPositions[i] = positions[i] + positionDelta;
-        return new EnvelopePart(new HashMap<>(attrs), newPositions, speeds, timeDeltas);
+        var newPositions = new ArrayList<Double>();
+        var newSpeeds = new ArrayList<Double>();
+        var newTimeDeltas = new ArrayList<Double>();
```
Comment (multun) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: You can use [hppc's DoubleArrayList](http://carrotsearch.github.io/hppc/releases/0.7.1/api/com/carrotsearch/hppc/DoubleArrayList.html) for better performance and decreased memory usage

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java [hunk 2]
```diff
@@ -638,10 +639,26 @@ public EnvelopePart slice(
...
+                newPositions.add(p);
+                newSpeeds.add(speeds[i]);
+                newTimeDeltas.add(timeDeltas[i - 1]);
+            }
+        }
+        return new EnvelopePart(
+                new HashMap<>(attrs),
+                newPositions.stream().mapToDouble(x -> x).toArray(),
+                newSpeeds.stream().mapToDouble(x -> x).toArray(),
+                newTimeDeltas.stream().mapToDouble(x -> x).toArray()
```
Comment (multun) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: [hppc's DoubleArrayList has a toArray method](http://carrotsearch.github.io/hppc/releases/0.7.1/api/com/carrotsearch/hppc/DoubleArrayList.html#toArray--)

**Review by multun — CHANGES_REQUESTED** [review]

**Review by Erashin — APPROVED** [review]

**Review by multun — APPROVED** [review]
