### PR TITLE
front: fix nge import when there is only one step

### LINKED ISSUE #9610: Macro mode - getSourceNode error
### What happened?

I get this error in the macro node after importing a specific Viriato file (I don't post it here, please ask @maelysLeratRosso the file to work on the bug) : 

Image

or also

Image

Linked to this [bug](https://github.com/OpenRailAssociation/osrd/issues/9594) probably

### What did you expect to happen?

I expected to see the NGE board

### How can we reproduce it (as minimally and precisely as possible)?

1. Import the file
2. Go to macro mode
3. Observe the bug

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

### PR DESCRIPTION
**Pull request by RomainValls**
closes #9610 

When importing a train, it can happen that the train only has 1 step, which was resulting in the origin and destination being the same step. 
We check the length of the steps, if it's less than 2, we skip.

### CODE REVIEW

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 1]
```diff
@@ -244,12 +244,16 @@ const importTimetable = async (
   );
   const trainSchedules = await trainSchedulesPromise.unwrap();
 
+  const filteredTrainSchedules = trainSchedules.filter(
```
Comment (emersion) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: Nit: I think I'd prefer to make `trainSchedules` mutable (with `let`) and overwrite it instead of using a separate `const`, otherwise I'm worried new code would forget about this stuff and use `trainSchedules` instead of `filteredTrainSchedules`.

**Review by emersion — APPROVED** [review]
LGTM!

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: You're right, makes more sense keeping trainSchedules ! modified it 👍

**Review by Caracol3 — APPROVED** [review]
lgtm !
