### PR TITLE
core: stdcm: rely on fixed point to compute final envelope

### LINKED ISSUE #6981: core: stdcm: refactor the post-processing to avoid using envelopes
First step of https://github.com/osrd-project/osrd/issues/6917

We used to rely on the max speed envelope to run the final simulation and apply the standard allowance. With this change, we only rely on fixed time points to apply both standard and engineering allowances. 

The max speed envelope wouldn't be necessary during the post-processing anymore.

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/osrd-project/osrd/issues/6981

We used to rely on the max speed envelope to run the final simulation and apply the standard allowance. With this change, we only rely on fixed time points to apply both standard and engineering allowances.

Includes a couple bugfixes:

1. When computing an allowance with ranges that don't add any time, we set the speed at the start/end of those ranges
2. `BlockAvailabilityInterface.Unavailable.firstConflictOffset` is now an `Offset<TravelledPath>`.

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt [hunk 1]
```diff
@@ -0,0 +1,314 @@
...
+    ranges: List<EdgeRange<STDCMEdge, STDCMEdge>>,
+    offset: Offset<TravelledPath>,
+    departureTime: Double,
+): Double {
+    var remainingDistance = offset.distance
+    for (range in ranges) {
+        assert(range.start.distance == 0.meters)
+        val edge = range.edge
+        if (remainingDistance <= range.end.distance) {
+            val absoluteTime = edge.getApproximateTimeAtLocation(Offset(remainingDistance))
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/PostProcessingSimulation.kt:231]: After discussion with @eckter : might be better to create a `FixedTimePoint` on an edge transition, where we know the exact time, rather than find the approximate time at which the train would be at the edge's offset with a linear interpolation (as done in `getAppoximateTimeAtLocation`).

**Review by Erashin — APPROVED** [review]
LGTM
