### PR TITLE
front: fix drag and drop for services

### LINKED ISSUE #14670: Space-time chart : drag and drop does not work for services
### What happened?

I cannot drag & drop a service in the STD. I can still drag & drop unique trains

### What did you expect to happen?

I expect to be able to drag & drop services

### How can we reproduce it (as minimally and precisely as possible)?

Create a service
Try to drag & drop it

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

05cd31c

### PR DESCRIPTION
**Pull request by theocrsb**
closes https://github.com/OpenRailAssociation/osrd/issues/14670

### CODE REVIEW

**Review by Uriel-Sautron — COMMENTED** [review]
Thank you for this PR, it fixes the bug well. We can drag and drop again  Occurences.
Should we be able to drag and drop exceptions? @maelysLeratRosso

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/createHandleTrainDrag.ts [hunk 1]
```diff
@@ -29,39 +33,43 @@ export default function createHandleTrainDrag({
...
     });
 
     if (stopPanning) {
       // update in the database
-      const draggedItemId = !isOccurrenceId(draggedTrainId)
-        ? draggedTrainId
-        : extractPacedTrainIdFromOccurrenceId(draggedTrainId);
+      const draggedItemId = !isOccurrenceId(trainToDragId)
+        ? trainToDragId
+        : extractPacedTrainIdFromOccurrenceId(trainToDragId);
```
Comment (Uriel-Sautron) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/createHandleTrainDrag.ts:59]: This part of the code is almost identical to lines 36 to 42, so we could find a way to refactor it.

Comment (theocrsb) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/createHandleTrainDrag.ts:59]: Of course, I can do it in a PR if that's okay with you, so as not to block the bug fix

**Comment by maelysLeratRosso** [comment]
> Thank you for this PR, it fixes the bug well. We can drag and drop again Occurences. Should we be able to drag and drop exceptions? @maelysLeratRosso

No, for now we can only drag & drop the occurrences that are not start_time exceptions (all these occurrences are moved at once) : moving one occurrence separately will be done in another feature (for exceptions and non exceptions)

**Comment by Uriel-Sautron** [comment]
> > Thank you for this PR, it fixes the bug well. We can drag and drop again Occurences. Should we be able to drag and drop exceptions? @maelysLeratRosso
> 
> No, for now we can only drag & drop the occurrences that are not start_time exceptions (all these occurrences are moved at once) : moving one occurrence separately will be done in another feature (for exceptions and non exceptions)

Thank you for your clarification.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/createHandleTrainDrag.ts (hunk 1 above)
Comment (Uriel-Sautron) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/createHandleTrainDrag.ts:59]: Ok

**Review by Uriel-Sautron — APPROVED** [review]
Lgtm, tested.

**Review by kmer2016 — APPROVED** [review]
Good job!
