### PR TITLE
front: fix icons in editor, reference map, stdcm

### LINKED ISSUE #5524: Have the same icons in editor and reference maps
Reference map:
image

Editor map:
image

### PR DESCRIPTION
**Pull request by RomainValls**
closes #5524

### CODE REVIEW

File: front/src/applications/editor/nav.tsx [hunk 1]
```diff
@@ -100,7 +99,7 @@ const NavButtons: NavButton[][] = [
     },
     {
       id: 'reset-viewport',
-      icon: FaCompass,
+      icon: FiCompass,
```
Comment (clarani) [inline front/src/applications/editor/nav.tsx]: Use FaRegCompass instead :)

File: front/src/common/Map/Buttons/ButtonMapKey.tsx [hunk 2]
```diff
@@ -1,18 +1,27 @@
 import React from 'react';
+import { useTranslation } from 'react-i18next';
+import { BsQuestionCircle } from 'react-icons/bs';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapKey.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonMapInfras.tsx [hunk 3]
```diff
@@ -4,19 +4,26 @@ import InfraSelector from 'common/InfraSelector/InfraSelector';
 import { useModal } from 'common/BootstrapSNCF/ModalSNCF';
 import { getInfraID } from 'reducers/osrdconf/selectors';
 import { useSelector } from 'react-redux';
+import { useTranslation } from 'react-i18next';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapInfras.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonMapKey.tsx [hunk 4]
```diff
@@ -1,18 +1,27 @@
...
+    <Tipped mode="left">
+      <button
+        type="button"
+        className="btn-rounded btn-rounded-white btn-map-settings"
+        onClick={toggleMapKey}
+      >
+        <span className="sr-only">Key</span>
+        <BsQuestionCircle />
+      </button>
+      <span>{t('common.help-display')} </span>
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapKey.tsx]: I think a better translation would be "legend", can you add new translation keys since help-display is already used somewhere else ?
```suggestion
      <span>{t('common.display-legend')} </span>
```

File: front/src/common/Map/Buttons/ButtonMapSearch.tsx [hunk 5]
```diff
@@ -1,18 +1,27 @@
 import React from 'react';
+import { useTranslation } from 'react-i18next';
+import { FiSearch } from 'react-icons/fi';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapSearch.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonMapSettings.tsx [hunk 6]
```diff
@@ -1,18 +1,28 @@
 import React from 'react';
+import { useTranslation } from 'react-i18next';
+
+import { GoStack } from 'react-icons/go';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapSettings.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonMapSettings.tsx [hunk 7]
```diff
@@ -1,18 +1,28 @@
...
+    <Tipped mode="left">
+      <button
+        type="button"
+        className="btn-rounded btn-rounded-white btn-map-settings"
+        onClick={toggleMapSettings}
+      >
+        <span className="sr-only">Settings</span>
+        <GoStack />
+      </button>
+      <span>{t('Editor.nav.select-infra')}</span>
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonMapSettings.tsx]: You forgot to change the key here ;)
```suggestion
      <span>{t('Editor.nav.toggle-layers')}</span>
```

File: front/src/common/Map/Buttons/ButtonResetViewport.tsx [hunk 8]
```diff
@@ -1,19 +1,29 @@
 import React from 'react';
-import { FaCompass } from 'react-icons/fa';
+import { useTranslation } from 'react-i18next';
+
+import { FiCompass } from 'react-icons/fi';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonResetViewport.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonZoomIn.tsx [hunk 9]
```diff
@@ -0,0 +1,23 @@
+import React from 'react';
+import { useTranslation } from 'react-i18next';
+import { FiZoomIn } from 'react-icons/fi';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonZoomIn.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/ButtonZoomOut.tsx [hunk 10]
```diff
@@ -0,0 +1,23 @@
+import React from 'react';
+import { FiZoomOut } from 'react-icons/fi';
+import { useTranslation } from 'react-i18next';
+import Tipped from '../../../applications/editor/components/Tipped';
```
Comment (clarani) [inline front/src/common/Map/Buttons/ButtonZoomOut.tsx]:
```suggestion
import Tipped from 'applications/editor/components/Tipped';
```

File: front/src/common/Map/Buttons/MapButtons.tsx [hunk 11]
```diff
@@ -6,7 +6,13 @@ import ButtonMapSearch from 'common/Map/Buttons/ButtonMapSearch';
 import ButtonMapSettings from 'common/Map/Buttons/ButtonMapSettings';
 import ButtonMapKey from 'common/Map/Buttons/ButtonMapKey';
 import ButtonResetViewport from 'common/Map/Buttons/ButtonResetViewport';
-import ButtonFullscreen from 'common/ButtonFullscreen';
+// import ButtonFullscreen from 'common/ButtonFullscreen';
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.tsx]:
```suggestion
```

File: front/src/common/Map/Buttons/MapButtons.tsx [hunk 12]
```diff
@@ -65,14 +65,53 @@ export default function MapButtons({
...
     <div ref={mapButtonsRef}>
       <div className="btn-map-container">
+        <ButtonZoomIn zoomIn={() => zoomIn()} />
+        <ButtonZoomOut zoomOut={() => zoomOut()} />
         <ButtonMapSearch toggleMapSearch={() => toggleMapModal('SEARCH')} />
         <ButtonMapSettings toggleMapSettings={() => toggleMapModal('SETTINGS')} />
         <ButtonMapKey toggleMapKey={() => toggleMapModal('KEY')} />
         <ButtonResetViewport updateLocalViewport={resetPitchBearing} />
-        {withFullscreenButton && <ButtonFullscreen />}
+        {/* {withFullscreenButton && <ButtonFullscreen />} */}
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.tsx]: You can also delete ButtonFullscreen, we should avoid keeping dead code
```suggestion
```

File: front/src/common/Map/Buttons/MapButtons.tsx [hunk 13]
```diff
@@ -65,14 +65,53 @@ export default function MapButtons({
...
 
+  const ZOOM_DEFAULT = 5;
+  const ZOOM_DELTA = 1.5;
+  const DEFAULT_VIEWPORT = {
+    latitude: 47.3,
+    longitude: 2.0,
+    zoom: 5.0,
+    bearing: 0,
+    pitch: 0,
+  };
```
Comment (clarani) [inline front/src/common/Map/Buttons/MapButtons.tsx]: You can move all these const outside MapButtons function or even in an other file :) otherwise these const will be re-instantiated at each re-render
```suggestion
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/Allowances/AllowancesStandardSettings.tsx [hunk 14]
```diff
@@ -2,10 +2,10 @@ import React, { useMemo } from 'react';
 import { useTranslation } from 'react-i18next';
 import InputGroupSNCF, { InputGroupSNCFValue } from 'common/BootstrapSNCF/InputGroupSNCF';
 import OptionsSNCF from 'common/BootstrapSNCF/OptionsSNCF';
+import { onlyDigit } from 'utils/strings';
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/Allowances/AllowancesStandardSettings.tsx]: Oups, there is an issue with this onlyDigit, it does not work in this file, can you remove all its usages and remove the import ? Thanks ! :)

**Review by clarani — CHANGES_REQUESTED** [review]
Thanks for this PR, great job !!
Here are some additional specifications:
- [x] use the icons Thibaut chose (sorry, I forgot to write them in the ticket, my bad :disappointed: )
  - layers : BsSliders2
   - compass (boussole) : FaRegCompass
- [x] remove the button to recenter the map in the editor
- [x] reorder the buttons so they are in the same order:
  - zoom-in/zoom-out
  - compass
  - search (only for reference map)
  - layers
  - infra
  - error (only for editor) / legend (only for reference map)
- [x] remove the space between icons in editor (between compass and layers)

File: front/src/common/Map/Buttons/ButtonMapInfras.tsx [hunk 15]
```diff
@@ -4,19 +4,26 @@ import InfraSelector from 'common/InfraSelector/InfraSelector';
...
-      className={`btn-rounded btn-rounded-white ${infraID ? '' : 'btn-map-infras-blinking'}`}
-      onClick={() => openModal(<InfraSelector isModalOnly />, 'lg')}
-    >
-      <span className="sr-only">Infrastructures</span>
-      <GiRailway />
-    </button>
+    <Tipped mode="left">
+      <button
+        type="button"
+        className={`btn-rounded btn-rounded-white ${infraID ? '' : 'btn-map-infras-blinking'}`}
```
Comment (SarahBellaha) [inline front/src/common/Map/Buttons/ButtonMapInfras.tsx]:
```suggestion
        className={cx('btn-rounded', 'btn-rounded-white', { 'btn-map-infras-blinking': !infraID })}
```

File: front/src/common/Map/Buttons/ButtonMapInfras.tsx [hunk 16]
```diff
@@ -4,19 +4,26 @@ import InfraSelector from 'common/InfraSelector/InfraSelector';
 import { useModal } from 'common/BootstrapSNCF/ModalSNCF';
 import { getInfraID } from 'reducers/osrdconf/selectors';
 import { useSelector } from 'react-redux';
+import { useTranslation } from 'react-i18next';
```
Comment (SarahBellaha) [inline front/src/common/Map/Buttons/ButtonMapInfras.tsx:7]:
```suggestion
import { useTranslation } from 'react-i18next';
import cx from 'classnames';
```

File: front/src/applications/editor/Editor.tsx [hunk 17]
```diff
@@ -355,8 +355,7 @@ const Editor: FC = () => {
                     );
                   });
 
-                  if (i < a.length - 1)
-                    return buttons.concat([<div key={`separator-${i}`} className="separator" />]);
+                  if (i < a.length - 1) return buttons;
```
Comment (clarani) [inline front/src/applications/editor/Editor.tsx]: You can simply remove this line, since you will return the same thing :) 
```suggestion
```

**Review by clarani — COMMENTED** [review]
2 last small things:
- [x] the infra button should be above the legend one on the reference map (current app here:)
image
- [x] the pop up text for the infra selector button is "choose infra to edit" even in the reference map, but it should be "choose infrastructure" simply. Can you add a new translation key for that ?
image

**Review by clarani — APPROVED** [review]
LGTM, the buttons are amazing now, thanks ! :tada: :rocket:
