### PR TITLE
front: fix panning over a train path.

### LINKED ISSUE #10725: When panning on the space time, the mouse grabs a train and starts moving it
click and start dragging the chart. if the mouse touches a train it start moving the train instead of panning.

https://github.com/user-attachments/assets/9d982c66-b348-4379-a9e5-cb7750a6eb27

### LINKED ISSUE #11275: GET: Train moves instead of graph when clicking in blank space
### What happened?

https://github.com/user-attachments/assets/0dee0656-f6f8-4b8e-b298-4fc5dd7c883d

If you click briefly on a train, then if you try to move in th grap by clicking in blanck space, it moves the train instead.

It's like the first click selected the train for moving.

### What did you expect to happen?

The train has to move only if clicked. In this situation, the graph has to move.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open a scenario with a train
2. Click briefly on a train
3. Click on a white space of the GET, maintain and drag your mouse

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

872260c

### PR DESCRIPTION
**Pull request by anisometropie**
closes #10725
closes #11275

### CODE REVIEW

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/modules/simulationResult/components/ManchetteWithSpaceTimeChart/ManchetteWithSpaceTimeChart.tsx [hunk 1]
```diff
@@ -301,7 +303,12 @@ const ManchetteWithSpaceTimeChartWrapper = ({
     }
 
     // if not dragging, we check if we should start dragging
+    // Only a mouse hover that starts already over a path should register
+    // if we start panning, and then the mouse hover over the path,
```
Comment (SharglutDev) [inline front/src/modules/simulationResult/components/ManchetteWithSpaceTimeChart/ManchetteWithSpaceTimeChart.tsx]:
```suggestion
    // if we start panning, and then the mouse hovers over the path,
```

File: front/src/modules/simulationResult/components/ManchetteWithSpaceTimeChart/ManchetteWithSpaceTimeChart.tsx [hunk 2]
```diff
@@ -102,6 +102,8 @@ const ManchetteWithSpaceTimeChartWrapper = ({
 
   const [tmpSelectedTrain, setTmpSelectedTrain] = useState(selectedTrainScheduleId);
 
+  const [previousPanning, setPreviousPanning] = useState(false);
```
Comment (SharglutDev) [inline front/src/modules/simulationResult/components/ManchetteWithSpaceTimeChart/ManchetteWithSpaceTimeChart.tsx:105]: Could we use a `useRef` instead to avoid rerender ?
```suggestion
  const previousPanningRef = useRef(false);
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thanks ! You can resolve the comment when fixed
