### PR TITLE
core: stdcm: fix 20s margin bug

### LINKED ISSUE #11186: core: stdcm: properly handle 20s margin before stop end
In France, we consider that when a train restarts after stopping, it must see a green signal at least 20 secondes before departing.

This is something we have in the conflict detection (see [here](https://github.com/OpenRailAssociation/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/standalone_sim/ScheduleMetadataExtractor.kt#L42-L43)). But we haven't properly thought about it for STDCM. It causes *issues*. There's some 500 (such as https://github.com/OpenRailAssociation/osrd/issues/11121).

But it also causes false negatives. When stopping, we check that there's no conflict during the stop duration, and *only then* we check if we should lengthen it to avoid conflicts. But the API can't let us tell appart conflicts caused during the stop by being there and conflicts caused by this margin, so we just drop the solution if there's any conflict. Even when they could have been easily avoided by delaying the departure. 

Fixing this is not easy. There are several options, some more "clean" than others:

1. Refine the incremental spacing resource generator API to tell as input "the train stop for at least this long but the departure isn't planned yet" (may not be enough)
2. Refine the *output* instead of input, to tell apart the resources that come from those 20s (? - unsure)
3. Tweak the inputs/outputs to reach a similar result to 1 or 2, but without changing the spacing resource generator (may lead to confusing and messy pipelines)

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/11186

Fix this issue by:

1. Tweaking inputs for spacing resource requirements: infra explorers that end at stop don't generate requirements for anything after the stop itself
2. Tweaking `BlockAvailability` to account for this margin when identifying conflicts after a stop

I'm not 100% convinced this is the right approach, but it works. I'll leave it there, maybe not merge during the feature freeze, and see if we can come up with something better.

Also add two unit tests: one for STDCM that reproduces this precise case (and fails without the last commit), and another one for spacing ressource generation to properly identify its behavior around partial stops.

Most of the diff comes from new tests, the PR isn't as large as it seems.

### CODE REVIEW

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt [hunk 1]
```diff
@@ -266,6 +266,40 @@ class FullSTDCMTests {
...
+                .setInfra(infra)
+                .setStartTime(0.0)
+                .setStartLocations(start.blockLocations)
+                .addStep(STDCMStep(stop.blockLocations, 5_000.0, true))
+                .setEndLocations(end.blockLocations)
+                .setBlockAvailability(makeBlockAvailability(requirements))
+                .setMaxRunTime(Double.POSITIVE_INFINITY)
+                .setMaxDepartureDelay(0.0)
+                .run()!!
+        assertTrue(res.stopResults.first().duration > 5_000.0)
```
Comment (Erashin) [inline core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: We could test that it's `>= 5_000.0 + CLOSED_SIGNAL_RESERVATION_MARGIN`.

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt [hunk 2]
```diff
@@ -12,6 +12,7 @@ class IncrementalRequirementEnvelopeAdapter(
     private val rollingStock: PhysicsRollingStock,
     private val envelopeWithStops: EnvelopeInterpolate?,
     override var simulationComplete: Boolean,
+    private val infiniteLastStop: Boolean = false,
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt:21]: We probably need a comment here. The name is ok-ish (tbh, i can't find anything better), but we need some context as to what this does exactly from the get-go.

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt [hunk 3]
```diff
@@ -44,6 +45,9 @@ class IncrementalRequirementEnvelopeAdapter(
         if (pastStop > endPos) {
             pastStop = endPos
         }
+        if (pastStop == endPos && infiniteLastStop) {
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt:54]: Probably needs a comment as well.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt [hunk 4]
```diff
@@ -213,14 +214,32 @@ data class BlockAvailability(
...
+            infraExplorer
+                .getStepTracker()
+                .getSeenSteps()
+                .drop(1) // Skip departure step
+                .filter { it.originalStep.stop }
+                .map {
+                    infraExplorer.getIncrementalPath().fromTravelledPath(it.travelledPathOffset)
+                }
+                .contains(startOffset)
+        var minRelevantTime = startTime
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:230]: What do you think about `startTimeWithMargin`?

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt [hunk 5]
```diff
@@ -213,14 +214,32 @@ data class BlockAvailability(
             if (needFullRequirements) infraExplorer.getFullSpacingRequirements()
             else infraExplorer.getSpacingRequirements()
 
+        // Ensures that we account for the 20s margin where a train must see a green signal before
+        // its departure: when the current segment starts at a stop, we want to consider conflicts
+        // up to 20s before the "start time".
+        val startAtStop =
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt]: `startsAtStop`

**Review by Erashin — COMMENTED** [review]
Hmm. Honestly think this solution is fine. Can't think of anything else off the top of my head.

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt (hunk 1 above)
Comment (bougue-pe) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: Not sure I understand correctly:
Should we check that stop departure _time_ is `~= 7000 + MARGIN`?
The check on duration seems a bit pointless: we check that we find a valid solution, but that's all, no?

Comment (eckter) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: The intent for this assert was specifically to test that the stop was lengthened compared to what was initially requested. Otherwise the test wouldn't have actually tested anything.

This assert ensures that the test itself is functional, it doesn't have much to do with the intended behavior itself.

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt (hunk 2 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt:21]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/a9bd554fe497c5a3287ddb47988e47b46d42c7dd

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt (hunk 4 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:230]: The intent for this variable is to bound the results to the relevant range, the margin thing explains how it's computed but I'd prefer it to describe what it actually does

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt (hunk 5 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/a9bd554fe497c5a3287ddb47988e47b46d42c7dd

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt (hunk 3 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt:54]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/a9bd554fe497c5a3287ddb47988e47b46d42c7dd

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt (hunk 1 above)
Comment (eckter) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: Commented in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/b906adf8ac2c3c3cb6649e639775d5b1d9175272

Comment (Erashin) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: Typo: `can be`

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt (hunk 4 above)
Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/preprocessing/implementation/BlockAvailability.kt:230]: Ok, fine for me then

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt [hunk 6]
```diff
@@ -12,6 +12,11 @@ class IncrementalRequirementEnvelopeAdapter(
     private val rollingStock: PhysicsRollingStock,
     private val envelopeWithStops: EnvelopeInterpolate?,
     override var simulationComplete: Boolean,
+
+    // If set to true, we consider that the train doesn't leave its current stop (yet).
+    // Used to evaluate conflicts up to a stop, including the stop itself,
+    // but without considering the reservation margin for what's coming after the stop.
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt]:
```suggestion
    // but without considering the reservation on blocks/routes after the stop (especially avoid being bothered by reservation margin before restarting from a stop on closed signal).
```

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt [hunk 7]
```diff
@@ -44,6 +49,11 @@ class IncrementalRequirementEnvelopeAdapter(
         if (pastStop > endPos) {
             pastStop = endPos
         }
+        if (pastStop == endPos && infiniteLastStop) {
+            // The requested stop is at the end of the path,
+            // and the last stop is flagged as "infinite".
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt]: Not sure:
```suggestion
            // The requested stop is at the end of the simulated path,
            // and the requested behavior is to make that stop "infinite" (pushing next reservation's start-time to "never").
```

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt [hunk 8]
```diff
@@ -266,6 +266,41 @@ class FullSTDCMTests {
...
+                .setStartTime(0.0)
+                .setStartLocations(start.blockLocations)
+                .addStep(STDCMStep(stop.blockLocations, 5_000.0, true))
+                .setEndLocations(end.blockLocations)
+                .setBlockAvailability(makeBlockAvailability(requirements))
+                .setMaxRunTime(Double.POSITIVE_INFINITY)
+                .setMaxDepartureDelay(0.0)
+                .run()!!
+        assertTrue(res.stopResults.first().duration >= 5_000.0) {
+            "if a solution can be found without lengthening the stop, the test itself is broken"
```
Comment (bougue-pe) [inline core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: From the "comment" I expected:
```suggestion
        assertTrue(res.stopResults.first().duration > 5_000.0) {
            "if a solution can be found without lengthening the stop, the test itself is broken"
```

**Review by bougue-pe — APPROVED** [review]
LGTM after your side-explanations (tried to suggest places to report it).
Not so sharp on STDCM, I let you see if @Erashin must approve too 🙂

**Review by Erashin — APPROVED** [review]

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt (hunk 6 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt]: Applied in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/8f2263f3fccd1fde472d3eed77eb90c0c351a928

File: core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt (hunk 7 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/conflicts/IncrementalRequirementEnvelopeAdapter.kt]: Applied in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/8f2263f3fccd1fde472d3eed77eb90c0c351a928

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt (hunk 8 above)
Comment (eckter) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/FullSTDCMTests.kt]: Good catch, I accidentally included a local change I should have reverted. Fixed in https://github.com/OpenRailAssociation/osrd/pull/11271/commits/8f2263f3fccd1fde472d3eed77eb90c0c351a928

**Review by bougue-pe — APPROVED** [review]
