### PR TITLE
Fix accelerating slopes test

### LINKED ISSUE #787: Fix accelerating slopes test
See PR #786

### PR DESCRIPTION
**Pull request by axrolld**
The test had way too short slopes to actually trigger MARECO's accelerating slopes.
I made the slopes longer and a curve shape test.

Closes #787

### CODE REVIEW

File: core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceTests.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
 import fr.sncf.osrd.envelope_sim.allowances.MarecoAllowance;
 import fr.sncf.osrd.envelope_sim.allowances.mareco_impl.MarecoConvergenceException;
 import fr.sncf.osrd.train.TestTrains;
+import org.checkerframework.checker.units.qual.C;
```
Comment (eckter) [inline core/src/test/java/fr/sncf/osrd/envelope_sim/AllowanceTests.java]:
```suggestion
```

**Review by eckter — DISMISSED** [review]

**Review by eckter — APPROVED** [review]
