### PR TITLE
core: stdcm: fix post-processing mismatch

### LINKED ISSUE #12541: core: fail to find a solution in post-processing
### What happened?

In prod, `java.lang.RuntimeException: Failed to compute a simulation that wouldn't cause conflicts: mismatch between exploration and postprocessing (please open a bug report)`

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Prod, trace_id = `d66fdb228a7140501fd21881a26e9d94`

### On which environments the bug occurs?

Production (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

v1.1.4 a01fce5

### PR DESCRIPTION
**Pull request by eckter**
Fix https://github.com/OpenRailAssociation/osrd/issues/12541

There's a couple small bugfixes, but ultimately it seems like we're just too optimistic on the ability to fully stop and restart. Likely because we don't properly account for slopes in previous edges.

I've added some tolerance by lowering the const deceleration value by 10%. It's good enough to fix the issue with the same request as the one reported in the bug, I'll run the fuzzer to see if it's actually enough. **=> fuzzer shows no new error, but we still have timeout outside of the south-east perimeter**

Bench: we find *a little* less solutions (as we were too optimistic on the engineering allowances). It also slows the processing down a little. But there's a second PR in progress for that: https://github.com/OpenRailAssociation/osrd/pull/12586 (I figured out while debugging this issue that we spend a lot of time computing redundant allowances).

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/Utils.kt [hunk 1]
```diff
@@ -26,6 +27,28 @@ fun runSimplifiedSimulation(
...
+/**
+ * Similar function as above, computes a simplified simulation using basic kinetic equations. Here
+ * we compute the travel time over some known distance, with first a speed plateau and then a
+ * deceleration. The exact transition isn't known, but we know the start/end speed and acceleration.
+ */
+fun simplifiedSpeedPlateauThenDeceleration(
+    acceleration: Double,
+    initialSpeed: Double,
+    finalSpeed: Double,
+    distance: Double
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/Utils.kt:39]: `constSpeedDistance` or `speedPlateauDistance`?

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/EngineeringAllowanceManager.kt [hunk 2]
```diff
@@ -51,8 +51,8 @@ class EngineeringAllowanceManager(
         // We still try to roughly guess the maximum length over which to add the time
         var distance = 0.meters
         for (segment in segments) {
+            if (segment.maxAddedDelay <= requiredAdditionalTime) break
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/EngineeringAllowanceManager.kt:54]: +1

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt [hunk 3]
```diff
@@ -62,12 +62,14 @@ fun generatePreviousSimulationSegments(
...
     var currentEdge = initialEdge
+    var alreadyAddedDelay = 0.0
     while (currentEdge != null) {
         if (currentEdge.endAtStop) break
 
         val envelope = currentEdge.originalEnvelope
         val edgeEndTime = currentEdge.timeData.earliestReachableTime + currentEdge.totalTime
-        val maxAddedDelay = currentEdge.timeData.timeOfNextConflictAtLocation - edgeEndTime
+        val maxAddedDelay =
+            currentEdge.timeData.timeOfNextConflictAtLocation - edgeEndTime - alreadyAddedDelay
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt]: I'm wondering if we shouldn't create extra methods in objects such as `STDCMEdge` to do these calculations once and for all. `cause with the number of variables that can potentially impact these calculations, I'm starting to feel lost. And we might forget the correct formula if we want to compute the same value in another part of the code.

**Review by Erashin — APPROVED** [review]
NIce.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/Utils.kt (hunk 1 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/Utils.kt:39]: That's the thing, it's the sum of both :smile: 

The exact transition location isn't known in the inputs, it's (implicitly) computed inside the method from the speed difference and acceleration.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt (hunk 3 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt]: We can't really put it in a single edge as it depends on the context and next edges (which wasn't handled before the change here, hence the bug). 

We could move that out into a specific utils method though, would it be better? It would be a little weird though, like it could return a `Sequence` of (edge, max delay). I don't think it would be called anywhere else.

Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt]: Hmmm. Wouldn't it be possible to create:
```
fun getEdgeEndTime(): Double {
   return this.timeData.earliestReachableTime + this.totalTime
}

fun getMaxAddedDelay(alreadyAddedDelay: Double): Double {
   return this.timeData.timeOfNextConflictAtLocation - this.getEdgeEndTime - alreadyAddedDelay
}
```
? I'm really only talking about the "basic" time operations here, we keep forgetting a variable somewhere.

Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/engineering_allowance/SimulationSegment.kt]: Fixed in a427ecafc8a7339c4d8e05982b8fca6b8da3c60b

Which led me to a bug in another place, fixing it causes an infinite loop in a test. I've added a `TODO`, the real fix will wait for https://github.com/OpenRailAssociation/osrd/pull/12505 (it's related)
