### PR TITLE
front: fix power restriction edition

### LINKED ISSUE #8021: Adding power restrictions sometimes causes pathfinding failure
### What happened?

Paris Montparnasse-Rennes with a 1TGVDUPL and these power restrictions;
image

image

Created an invalid train with pathfinding_not_found error:
image

And when editing it, it saw this path:
image

### What did you expect to happen?

I'm expecting power restrictions not to impact my pathfinding, and especially not making it fail.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce the  description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

de8ada8

### PR DESCRIPTION
**Pull request by clarani**
closes #8021

### CODE REVIEW

**Comment by woshilapin** [comment]
It would be nice to have some tests to avoid regression later. That said, it doesn't fix #8021. The problem is not only about wrong units (millimeters vs meters) but also about the calculation. See, the calculation of the second path item (first power restriction bound) for example, it is 3933000 but as explained in #8021, it should be 1616000.

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 1]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
-  const inferiorSum = tracksLengthCumulativeSums[index];
-  return trackSectionRange.direction === 'START_TO_STOP'
-    ? inferiorSum - position
-    : position - inferiorSum;
+  const index = findTrackSectionIndex(positionOnPath, tracksLengthCumulativeSums);
+  const trackRange = trackRangesOnPath[index];
+  if (index === -1 || !trackRange) return null;
+
+  // compute offset
+  const inferiorSum = (index && tracksLengthCumulativeSums[index - 1]) || 0;
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts]: Subjective nit: I'd personally find it more readable to (1) use `index > 0` instead of `index` to better reflect the intent and (2) use a ternary:

```ts
const inferiorSum = index > 0 ? tracksLengthCumulativeSums[index - 1] : 0;
```

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    const tracksLengthCumulativeSums = [1000, 2000, 3000, 4000, 5000];
+    const trackRanges = [
+      { track_section: 'track_0' },
+      { track_section: 'track_1' },
+      { track_section: 'track_2', begin: 0, end: 1000, direction: 'START_TO_STOP' },
+      { track_section: 'track_3' },
+      { track_section: 'track_4' },
+    ] as TrackRange[];
+
+    const offsetOnPath = 2500;
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: I would recommend using a point which isn't in the middle of the track range for tests. That way, we're more likely to catch issues when operating from the wrong side (`begin + offset` vs. `end - offset` with `offset = (end - begin) / 2`).

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+    expect(result).toEqual({ track: 'track_2', offset: 500 });
+  });
+
+  it('should correctly find the track offset if the track range does not cover the whole track section', () => {
+    const tracksLengthCumulativeSums = [1000, 2000, 3000, 4000, 5000];
+    const trackRanges = [
+      { track_section: 'track_0' },
+      { track_section: 'track_1' },
+      { track_section: 'track_2', begin: 1000, end: 2000, direction: 'START_TO_STOP' },
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Isn't this track range outside of the track section's bounds? According to `tracksLengthCumulativeSums`, each track section has a length of 1000.

Maybe in practice that doesn't matter for the purposes of the test, but would be nicer to have non-bogus test inputs.

Additionally, I'd recommend using `begin`/`end` values which aren't multiples of the track section lengths, to be more likely to catch math mixups between the two.

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+      { track_section: 'track_4' },
+    ] as TrackRange[];
+
+    const offsetOnPath = 2500;
+    const result = findTrackOffset(offsetOnPath, tracksLengthCumulativeSums, trackRanges);
+
+    expect(result).toEqual({ track: 'track_2', offset: 1500 });
+  });
+
+  it('should correctly find the track offset if the track range direction is STOP_TO_START ', () => {
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Nit: extra space at the end of the test description here

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 5]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
-  pathProperties: ManageTrainSchedulePathProperties
-) => {
-  const index = findTrackSectionIndex(position, tracksLengthCumulativeSums);
-  return index !== -1 ? pathProperties.trackSectionRanges[index] : null;
-};
-
-const calculateOffset = (
-  trackSectionRange: TrackRange,
-  position: number, // in mm
-  tracksLengthCumulativeSums: number[] // in meters
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts:33]: Big +1 for not mixing up units in arguments here!

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+      { track_section: 'track_3' },
+      { track_section: 'track_4' },
+    ] as TrackRange[];
+
+    const offsetOnPath = 2500;
+    const result = findTrackOffset(offsetOnPath, tracksLengthCumulativeSums, trackRanges);
+
+    expect(result).toEqual({ track: 'track_2', offset: 2500 });
+  });
+});
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts:83]: Suggestion for a negative test:

```ts
  it('should not find the track offset if past cumulative sums', () => {
    const tracksLengthCumulativeSums = [1000, 2000, 3000];
    const trackRanges = [
      { track_section: 'track_0' },
      { track_section: 'track_1' },
      { track_section: 'track_2' },
    ] as TrackRange[];

    const offsetOnPath = 3001;
    const result = findTrackOffset(offsetOnPath, tracksLengthCumulativeSums, trackRanges);

    expect(result).toEqual(null);
  });
```

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 7]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
+  const trackRange = trackRangesOnPath[index];
+  if (index === -1 || !trackRange) return null;
+
+  // compute offset
+  const inferiorSum = (index && tracksLengthCumulativeSums[index - 1]) || 0;
+  const offsetOnTrackRange = positionOnPath - inferiorSum;
+  const offsetOnTrackSection =
+    trackRange.direction === 'START_TO_STOP'
+      ? trackRange.begin + offsetOnTrackRange
+      : trackRange.begin - offsetOnTrackRange;
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts:40]: Question: should this be `trackRange.end + offsetOnTrackRange` instead for `STOP_TO_START`? Disclaimer, I have no clue how these things work.

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 8]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
-};
-
-const calculateOffset = (
-  trackSectionRange: TrackRange,
-  position: number, // in mm
-  tracksLengthCumulativeSums: number[] // in meters
+/**
+ * Return the track offset corresponding to the given position on path, composed of the track section id
+ * and the offet on this track section in mm*/
+export const findTrackOffset = (
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts]: Maybe this could be named `findTrackSectionOffset`, to make it clear it's the offset in terms of track section (as opposed to track range)?

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 9]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
+
+  // compute offset
+  const inferiorSum = (index && tracksLengthCumulativeSums[index - 1]) || 0;
+  const offsetOnTrackRange = positionOnPath - inferiorSum;
+  const offsetOnTrackSection =
+    trackRange.direction === 'START_TO_STOP'
+      ? trackRange.begin + offsetOnTrackRange
+      : trackRange.begin - offsetOnTrackRange;
+
+  return { track: trackRangesOnPath[index].track_section, offset: offsetOnTrackSection };
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts]: Can be simplified to `track: trackRange.track_section`.

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 10]
```diff
@@ -18,25 +18,27 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
+  trackRangesOnPath: TrackRange[]
 ) => {
-  const index = findTrackSectionIndex(position, tracksLengthCumulativeSums);
-  const inferiorSum = tracksLengthCumulativeSums[index];
-  return trackSectionRange.direction === 'START_TO_STOP'
-    ? inferiorSum - position
-    : position - inferiorSum;
+  const index = findTrackSectionIndex(positionOnPath, tracksLengthCumulativeSums);
+  const trackRange = trackRangesOnPath[index];
+  if (index === -1 || !trackRange) return null;
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts]: Nit: I'd personally find it more readable to move the `index === -1` check above `trackRange = trackRangesOnPath[index]`. Or alternatively change the check to `if (!trackRange)` only. Reason being that we don't need two conditions here, a single one should be enough.

**Review by emersion — COMMENTED** [review]
Here's a first pass of comments. I like the refactoring!

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 1 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts]: Yep, done !

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 8 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts]: Done

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 9 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts]: Nice catch !

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 10 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts]: You're right, I kept `if (!trackRange)`

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts (hunk 3 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Actually `tracksLengthCumulativeSums` is `trackRangesLengthCumulativeSums` so the track range on track_2 is correct.
I can rename `tracksLengthCumulativeSums` and modify the inputs, tell me if you think it's better now :)

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts (hunk 2 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Done

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts (hunk 4 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Nice catch, thanks :)

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts (hunk 6 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts:83]: Nice, done !

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 7 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts:40]: image
Here is a small diagram.

To compute the track range offset in this case, I think we have 2 options:
- `trackRange.end + trackRangeLength - offsetOnTrackRange` with `trackRangeLength = Math.abs(trackRange.end - trackRange.begin)`
- `trackRange.begin - offsetOnTrackRange`

I don't see a more general formula, do you ?
If we don't find any, I still prefer the second option, if it's fine for you

**Comment by clarani** [comment]
Thanks @woshilapin for you review, I have fixed the problems you raised

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 11]
```diff
@@ -127,8 +124,7 @@ export const createCutAtPathStep = (
     id: nextId(),
     positionOnPath: cutAtPosition,
     coordinates: coordinatesAtCut,
-    track: trackSectionRangeAtCut.track_section,
-    offset: offsetAtCut,
+    ...trackOffset,
```
Comment (emersion) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts:127]: No need for `offset: mmToM(trackOffset.offset)` here? Seems like the inputs are the same as in `createPathStep()`, and the result is passed to `cutPowerRestrictionRangesV2()` which may insert the whole thing incl. `offset` into the store?

File: front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts (hunk 3 above)
Comment (emersion) [reply front/src/modules/powerRestriction/helpers/__tests__/createPathStep.spec.ts]: Oh! Makes perfect sense.

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 7 above)
Comment (emersion) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts:40]: Thanks a lot for the explanation, I wasn't sure whether `offsetOnTrackRange` was relative to `begin` or `end` for `STOP_TO_START`. The current formula looks good to me!

File: front/src/modules/powerRestriction/helpers/createPathStep.ts (hunk 11 above)
Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts:127]: Yes you're right, I thought it was a different case, but after a check it was not ! Thanks :pray:

**Review by emersion — APPROVED** [review]
LGTM! :)

File: front/src/modules/powerRestriction/helpers/createPathStep.ts [hunk 12]
```diff
@@ -18,25 +18,28 @@ const findTrackSectionIndex = (position: number, tracksLengthCumulativeSums: num
...
-    : position - inferiorSum;
+  const index = findTrackSectionIndex(positionOnPath, tracksLengthCumulativeSums);
+  const trackRange = trackRangesOnPath[index];
+  if (!trackRange) return null;
+
+  // compute offset
+  const inferiorSum = index > 0 ? tracksLengthCumulativeSums[index - 1] : 0;
+  const offsetOnTrackRange = positionOnPath - inferiorSum;
+  const offsetOnTrackSection =
+    trackRange.direction === 'START_TO_STOP'
```
Comment (Math-R) [inline front/src/modules/powerRestriction/helpers/createPathStep.ts:38]: Is there is several direction it could be nice if we have an enum

Comment (emersion) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts:38]: This field is auto-generated from OpenAPI, so we can't manually define an enum. (I haven't looked whether it's possible to change the Rust counterpart to get an enum on the TypeScript side.)

Comment (clarani) [reply front/src/modules/powerRestriction/helpers/createPathStep.ts:38]: There are only 2 directions, `'START_TO_STOP'` and `'STOP_TO_START'`.
As emersion said, the field is auto-generated, is it ok for you if we report this issue in a new ticket ?

**Review by Math-R — APPROVED** [review]
lgtm :)
