### PR TITLE
core: mareco: rework accelerating slope detection

### LINKED ISSUE #3140: Discontinuity in mareco space caused by accelerating slope differences
When doing the mareco binary search, it's possible to fail to converge because of differences in accelerating slopes.

When looking for accelerating slopes, we iterate using a position step. The positions of the slopes can change by up to this step.
As a result, during the binary search, this adds a little noise and the function isn't strictly monotonic. It can fail to converge.

An easy fix would be to reduce this time step, but it causes other issues where the coasting envelope doesn't intersect with the initial envelope.

### PR DESCRIPTION
**Pull request by eckter**
Rework the methods used to detect accelerating slopes. It is *mostly* a cleanup that moves code around into smaller parts, but there are a few actual changes aiming to fix https://github.com/DGEXSolutions/osrd/issues/3140:

1. Fix a bug where "previous[...]" variables would carry over from one plateau to the next, causing binary search discontinuities
2. Finer interpolation to detect the end of the accelerating slope
3. Rework of the "previous acceleration" estimation: instead of picking the previous value (which caused *several* problems), we find the exact start of the accelerating slope, then get the acceleration a certain distance before that.

Fixes https://github.com/DGEXSolutions/osrd/issues/3140

https://github.com/DGEXSolutions/osrd/issues/2584 now appears in a unit test, and it seems closely related. I'll try to fix this on the same branch (-> draft)

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_utils/DistanceAverage.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+/** This class can be used to compute average values over distances,
+ * adding segments iteratively. */
+public class DistanceAverage {
+    private double totalValue = 0;
+    private double totalLength = 0;
+
+    /** Add a segment of size `length`, with an average value of `value` */
+    public void addSegment(double length, double value) {
+        totalValue += value * length;
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_utils/DistanceAverage.java]: This naming would make more sense to me
```suggestion
        totalWeightedValue += value * length;
```

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 2]
```diff
@@ -1,40 +1,94 @@
...
+    /** Estimates the average acceleration during the part where the train decelerates */
+    private double estimatePreviousAcceleration(EnvelopeSimContext context) {
+        // We look for the natural acceleration an offset before the start of the slope.
+        // The exact offset is arbitrary, we only need an approximation (as long as there is no discontinuity).
+        // If we assume the train starts accelerating when its center is roughly at the highest point, and
+        // we look for the acceleration on the ramp, half of the rolling stock length is a good offset value.
+        // If we need a better approximation than this, the "next step" would be to average over a certain distance.
+        var accelerationStart = findExactStartAcceleratingSlope(context);
+        var offset = context.rollingStock.getLength() / 2;
+        var estimatePosition = Math.max(0, accelerationStart - offset);
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java:66]: So here the head of the train would be `trainLength/2` meters before the beginning of the slope, right ?

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 3]
```diff
@@ -1,40 +1,94 @@
...
+        assert !Double.isNaN(endPos);
+        assert !Double.isNaN(previousAccelerationEstimate);
+        assert !Double.isNaN(speedLimit);
+        return this;
+    }
+
+    /** Estimates the average acceleration during the part where the train decelerates */
+    private double estimatePreviousAcceleration(EnvelopeSimContext context) {
+        // We look for the natural acceleration an offset before the start of the slope.
+        // The exact offset is arbitrary, we only need an approximation (as long as there is no discontinuity).
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java]: Just to make it clearer
```suggestion
        // The exact offset is arbitrary, we only need an approximation (as long as there is no discontinuity in the binary search).
```

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 4]
```diff
@@ -1,40 +1,94 @@
...
+        // If we assume the train starts accelerating when its center is roughly at the highest point, and
+        // we look for the acceleration on the ramp, half of the rolling stock length is a good offset value.
+        // If we need a better approximation than this, the "next step" would be to average over a certain distance.
+        var accelerationStart = findExactStartAcceleratingSlope(context);
+        var offset = context.rollingStock.getLength() / 2;
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java]: I suggest an offset corresponding to one entire rolling stock length, as you said it's arbitrary but in the case the slope difference is so high that the acceleration spot is not at the middle of the train but rather towards the tail
```suggestion
        var offset = context.rollingStock.getLength();
```

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 5]
```diff
@@ -47,6 +101,7 @@ private double computeV(PhysicsRollingStock rollingStock, double v1, double vf)
         // the lowest possible speed that will catch up with target speed at the end
         double wle = rollingStock.getRollingResistance(v1) * v1 * vf / (v1 - vf);
         double accelRatio = previousAccelerationEstimate / slopeAverageAcceleration;
+        accelRatio = Math.min(0, accelRatio);
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java]: That seems like a sane change :D

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 6]
```diff
@@ -91,61 +141,63 @@ public static ArrayList<AcceleratingSlopeCoast> findAll(
...
-                    currentAcceleratingSlope.endPos = previousPosition;
-                    currentAcceleratingSlope.speedLimit = speed;
-                    meanAcceleration /= accelerationLength;
-                    currentAcceleratingSlope.slopeAverageAcceleration = meanAcceleration;
-                    res.add(currentAcceleratingSlope);
-                    // reset meanAcceleration, accelerationLength, and accelerating slope
-                    meanAcceleration = 0;
-                    accelerationLength = 0;
-                    currentAcceleratingSlope = new AcceleratingSlopeCoast(0, 0, 0, 0);
+                    var endPos = interpolateAccelerationSignChange(
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java:162]: I don't know if there's a way improve it but you're looking for the `acceleration = 0` spot twice : here and in `findExactStartAcceleratingSlope`. Do you think it would be possible to refactor this to call this method only once ?

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java [hunk 7]
```diff
@@ -91,61 +141,63 @@ public static ArrayList<AcceleratingSlopeCoast> findAll(
...
-                meanAcceleration /= accelerationLength;
-                currentAcceleratingSlope.slopeAverageAcceleration = meanAcceleration;
-                res.add(currentAcceleratingSlope);
-                // reset meanAcceleration, accelerationLength, and accelerating slope
-                meanAcceleration = 0;
-                accelerationLength = 0;
-                currentAcceleratingSlope = new AcceleratingSlopeCoast(0, 0, 0, 0);
-            }
+            if (currentAcceleratingSlope != null)
+                res.add(currentAcceleratingSlope.build(previousPosition, context));
```
Comment (axrolld) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java:175]: That's way cleaner, goo job !

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java (hunk 5 above)
Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java]: But it *shouldn't* be needed anymore, that was a leftover of our previous investigations. I'm tempted to replace it with an `assert accelRatio <= 0`.

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java (hunk 6 above)
Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java:162]: I don't think it would really work, we don't compute it in the same way, there's a lot more stuff going on in this loop.

Comment (axrolld) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java:162]: Ok

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java (hunk 5 above)
Comment (axrolld) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/mareco_impl/AcceleratingSlopeCoast.java]: You can try that out ! Maybe it will spot some bugs

**Review by axrolld — APPROVED** [review]
🚀

**Review by multun — APPROVED** [review]
