### PR TITLE
front: fix times and stops table

### LINKED ISSUE #7586: front: TSv2: odd behavior of the checkbox of reception on closed signal
### What happened?

Sometimes, when we click on the checkbox, it doesn't work. 

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Go to "horaires et marges"
3. click on the checkbox of "reception sur signal fermé"
4. See the odd behavior

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

625d185

### LINKED ISSUE #7598: Stopping time edition in TSV2 goes on the first line
### What happened?

1. I created a train from PLY to DN in TSV2 
2. I tried to add a 30s stopping time on the first line (departure) -> the 30s disappears (I think it's ok because stopping time means nothing on the departure point)
3. I tried to add a 20s stopping time on the second line -> the 20s disappear from the second line but the 30s appear on the first line
4. I cannot remove this 30s from the first line

image

### What did you expect to happen?

I expected the 20s stop to be added to the second line, and the first line to remain empty

### How can we reproduce it (as minimally and precisely as possible)?

As above

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev dgexsol

### OSRD version (top right corner `Account` button > `Informations`)

625d185

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7598 
close #7586 
deal with one issue in #7585 
deal with issues/enhancements listed in a comment in #7586.

What the PR changes/fix : 
- fix 7598. The issue came from the fact that, with some paths, there could be multiple operational points at position 0. As we used the position on path to find which op to update when changing something in the table, it could result to this issue.
- fix 7586. The issue came from the same thing as above and also the fact that the code wasn't built to update origin or destination in the time and stops table.
- origin is always the first op in the list even if there is multiple ops with position 0
- the arrival time field for the origin is synced with the departure time of the train and can't be updated in the table
- all origin's fields are updatable (except arrival time)
- all destination's fields are updatable except margins
- origin and destination don't have the "remove via" button anymore at the end of the row
- when we change a constraint from an operational point, its id doesn't change anymore

### CODE REVIEW

File: front/src/applications/operationalStudies/views/v2/ManageTrainScheduleV2.tsx [hunk 1]
```diff
@@ -123,7 +124,14 @@ const ManageTrainScheduleV2 = () => {
       </div>
     ),
     label: t('tabs.timesStops'),
-    content: <TimesStops pathProperties={pathProperties} pathSteps={pathSteps} />,
+    // If pathProperties is defined we know that pathSteps won't have any null values
```
Comment (clarani) [inline front/src/applications/operationalStudies/views/v2/ManageTrainScheduleV2.tsx:127]: Nice :+1:

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts [hunk 2]
```diff
@@ -813,7 +813,7 @@ const testCommonConfReducers = (slice: OperationalStudiesConfSlice | StdcmConfSl
       };
 
       const updatedVia: PathStep = {
-        id: 'id2', // nextId() second increments after the one l.764
+        id: 'lemans', // nextId() second increments after the one l.764
```
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts]:
```suggestion
        id: 'lemans',
```

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts [hunk 3]
```diff
@@ -824,6 +824,9 @@ const testCommonConfReducers = (slice: OperationalStudiesConfSlice | StdcmConfSl
         deleted: newVia.deleted,
         name: newVia.name,
         ch: newVia.ch,
+        kp: undefined,
+        onStopSignal: undefined,
+        theoreticalMargin: undefined,
```
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts]: I think it's not needed ? Or maybe I am missing something ?
```suggestion
```

File: front/src/modules/timesStops/TimesStops.tsx [hunk 4]
```diff
@@ -186,18 +209,21 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
...
       stickyRightColumn={{
-        component: ({ rowData }) =>
+        component: ({ rowData, rowIndex }) =>
           createDeleteViaButton({
             removeVia: () => removeVia(rowData),
-            isRowVia: isVia(compact(pathSteps), rowData),
+            isRowVia:
+              rowIndex !== 0 &&
+              rowIndex !== pathProperties.allWaypoints?.length - 1 &&
+              isVia(compact(pathSteps), rowData, true),
```
Comment (clarani) [inline front/src/modules/timesStops/TimesStops.tsx]: Move the condition in the function createDeleteViaButton ;)

File: front/src/modules/pathfinding/utils.ts [hunk 5]
```diff
@@ -131,10 +128,16 @@ export const upsertViasInOPs = (ops: SuggestedOP[], pathSteps: PathStep[]): Sugg
  * Some OPs have same uic so we need to check also the ch (can be still not enough
  * probably because of imports problem).
  * If the vias has no uic, it has been added via map click and we know it has an id.
+ * @param withKP - If true, we check the kp compatibility instead of the name.
+ * It is used in the times and stops table to check if an operational point is a via.
  */
-export const isVia = (vias: PathStep[], op: SuggestedOP) =>
+export const isVia = (vias: PathStep[], op: SuggestedOP, withKP = false) =>
```
Comment (clarani) [inline front/src/modules/pathfinding/utils.ts:134]: Is there some cases where we prefer to check the name instead of the kp ? I think we can even always check the kp
```suggestion
export const isVia = (vias: PathStep[], op: SuggestedOP) =>
```

File: front/src/modules/timesStops/TimesStops.tsx [hunk 6]
```diff
@@ -112,10 +137,6 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
           })
         ),
         title: `${t('stopTime')}`,
-
-        // We should not be able to edit the stopping time of the origin and destination
-        disabled: ({ rowIndex }) =>
-          rowIndex === 0 || rowIndex === pathProperties.allVias?.length - 1,
```
Comment (clarani) [inline front/src/modules/timesStops/TimesStops.tsx:118]: Why do we want to edit the stop time of the origin or destination ?

File: front/src/modules/timesStops/TimesStops.tsx [hunk 7]
```diff
@@ -34,14 +35,33 @@ const marginRegExValidation = /^\d+(\.\d+)?%$|^\d+(\.\d+)?min\/100km$/;
 
 const formatSuggestedViasToRowVias = (
```
Comment (clarani) [inline front/src/modules/timesStops/TimesStops.tsx]: Can you move this function in a new file helpers or utils ?

File: front/src/modules/timesStops/TimesStops.tsx [hunk 8]
```diff
@@ -34,14 +35,33 @@ const marginRegExValidation = /^\d+(\.\d+)?%$|^\d+(\.\d+)?min\/100km$/;
...
+      'ch' in origin &&
+      op.uic === origin.uic &&
+      op.ch === origin.ch &&
+      op.name === origin.name
+  );
+  // If the origin is in the ops and isn't the first operational point, we need to move it to the first position
+  if (originIndexInOps !== (-1 || 0)) {
+    formattedOps = formattedOps.toSpliced(originIndexInOps, 1);
+    formattedOps.unshift(operationalPoints[originIndexInOps]);
+  }
```
Comment (clarani) [inline front/src/modules/timesStops/TimesStops.tsx]: Do you think it is clearer like this ?
```suggestion
  // Check if the origin is in the operational points and move it to the first position
  if (origin && 'uic' in origin && 'ch' in origin) {
    const originIndexInOps = operationalPoints.findIndex(
      (op) =>
        op.uic === origin.uic &&
        op.ch === origin.ch &&
        op.name === origin.name
    );
    if (originIndexInOps !== (-1 || 0)) {
      formattedOps = formattedOps.toSpliced(originIndexInOps, 1);
      formattedOps.unshift(operationalPoints[originIndexInOps]);
    }
  }
```

File: front/src/modules/timesStops/TimesStops.tsx [hunk 9]
```diff
@@ -186,18 +209,21 @@ const TimesStops = ({ pathProperties, pathSteps = [] }: TimesStopsProps) => {
...
           }),
       }}
       lockRows
       height={600}
       rowClassName={({ rowData, rowIndex }) =>
         rowIndex === 0 ||
-        rowIndex === pathProperties.allVias.length - 1 ||
-        isVia(compact(pathSteps), rowData)
+        rowIndex === pathProperties.allWaypoints.length - 1 ||
+        isVia(compact(pathSteps), rowData, true)
```
Comment (clarani) [inline front/src/modules/timesStops/TimesStops.tsx]: As you have changed the type of pathSteps, you can remove all the "compact" of the file I think
```suggestion
        isVia(pathSteps, rowData, true)
```

File: front/src/reducers/osrdconf/osrdConfCommon/index.ts [hunk 10]
```diff
@@ -429,9 +429,27 @@ export function buildCommonConfReducers<S extends OsrdConfState>(): CommonConfRe
...
+              step.name === action.payload.name) ||
+            step.id === action.payload.opId
+        );
+        newVia = { ...newVia, id: pathSteps[stepIndex].id }; // We don't need to change the id of the updated via
+        state.pathSteps = replaceElementAtIndex(state.pathSteps, stepIndex, newVia);
       } else {
-        state.pathSteps = addElementAtIndex(state.pathSteps, index, newVia);
+        // Because of import issues, there can be multiple ops at position 0
+        // To avoid inserting a new via before the origin we need to check if the index is 0
+        state.pathSteps = addElementAtIndex(
```
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/index.ts]: You can compute index here, instead of doing it l405
```suggestion
        const index = pathSteps.findIndex(
          (step) => step.positionOnPath! >= action.payload.positionOnPath
        );
        state.pathSteps = addElementAtIndex(
```

File: front/src/reducers/osrdconf/osrdConfCommon/index.ts [hunk 11]
```diff
@@ -429,9 +429,27 @@ export function buildCommonConfReducers<S extends OsrdConfState>(): CommonConfRe
...
+          state.pathSteps,
+          index !== 0 ? index : index + 1,
```
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/index.ts]:
```suggestion
          index || 1,
```

**Review by clarani — CHANGES_REQUESTED** [review]
Nice work, I left some comments :)

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts]: Done

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts (hunk 3 above)
Comment (SharglutDev) [reply front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts]: Agreed, its strange, in one of the tests launch, it failed because these lines was present in the test results but not anymore when I retry.

File: front/src/modules/timesStops/TimesStops.tsx (hunk 4 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Hmm that would require that I put a lot more parameters in the function (rowIndex, pathProperties, pathSteps, rowData).

If you don't like the logic directly in the function argument, I could do like this : 
```
component: ({ rowData, rowIndex }) => {
          const isRowVia =
            rowIndex !== 0 &&
            rowIndex !== pathProperties.allWaypoints?.length - 1 &&
            isVia(compact(pathSteps), rowData, true);
          return createDeleteViaButton({
            removeVia: () => removeVia(rowData),
            isRowVia,
          });
        },
```

What do you prefer ?

File: front/src/modules/pathfinding/utils.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/utils.ts:134]: I had to do that because of import issues. Sometimes, we want to check isVia for ops which have same uic/ch but different kps (so we pass true as third arg) and sometimes they have same uic/ch/kp so we need to compare them with their names..

File: front/src/modules/timesStops/TimesStops.tsx (hunk 6 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx:118]: That's a request from @bgiuliana. Apparently the users said they can sometimes need to add a stop duration to these steps.

File: front/src/modules/timesStops/TimesStops.tsx (hunk 7 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Done. As it depended on types and consts, I also moved those to types.ts and consts.ts

File: front/src/modules/timesStops/TimesStops.tsx (hunk 8 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Hmm I'm not sure because here I don't only check if origin is in the ops, I check if it's in the ops **_and_** not at the first position

File: front/src/modules/timesStops/TimesStops.tsx (hunk 9 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Good catch ! Done.

File: front/src/reducers/osrdconf/osrdConfCommon/index.ts (hunk 10 above)
Comment (SharglutDev) [reply front/src/reducers/osrdconf/osrdConfCommon/index.ts]: Good idea ! Done.

File: front/src/reducers/osrdconf/osrdConfCommon/index.ts (hunk 11 above)
Comment (SharglutDev) [reply front/src/reducers/osrdconf/osrdConfCommon/index.ts]: Done

File: front/src/modules/timesStops/TimesStops.tsx (hunk 6 above)
Comment (clarani) [reply front/src/modules/timesStops/TimesStops.tsx:118]: Ok but we should check with @flomonster because I think it will break on their side :/

File: front/src/modules/timesStops/consts.ts [hunk 12]
```diff
@@ -0,0 +1,3 @@
+export const marginRegExValidation = /^\d+(\.\d+)?%$|^\d+(\.\d+)?min\/100km$/;
+
+export default marginRegExValidation;
```
Comment (clarani) [inline front/src/modules/timesStops/consts.ts]: Disable the eslint warning here instead of default export the regex
```suggestion
export default marginRegExValidation;
```

File: front/src/modules/timesStops/types.ts [hunk 13]
```diff
@@ -0,0 +1,5 @@
+import type { SuggestedOP } from 'modules/trainschedule/components/ManageTrainSchedule/types';
+
+export type PathWaypointColumn = SuggestedOP & {
```
Comment (clarani) [inline front/src/modules/timesStops/types.ts:3]: I think you will need to deactivate the eslint warning here, because you have only 1 export

File: front/src/modules/timesStops/utils.ts [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+  return formattedOps.map((op, i) => ({
+    ...op,
+    name: op.name || t('waypoint', { id: op.opId }),
+    isMarginValid: op.theoreticalMargin ? marginRegExValidation.test(op.theoreticalMargin) : true,
+    onStopSignal: op.onStopSignal || false,
+    arrival: i === 0 ? startTime?.substring(11, 19) : op.arrival,
+  }));
+};
+
+export default formatSuggestedViasToRowVias;
```
Comment (clarani) [inline front/src/modules/timesStops/utils.ts]: I think you can have an eslint warning if you export and default export the same function/const. Anyway, I think you can remove the default export and disable the eslint warning.
If you want to default export, then you should rename the file into 'formatSuggestedViasToRowVias.ts'
```suggestion
```

File: front/src/modules/timesStops/TimesStops.tsx (hunk 6 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx:118]: We did. For the origin, it's just if we put an `arrival` that it will break. And for the destination, only margin is forbidden.

File: front/src/modules/timesStops/TimesStops.tsx (hunk 4 above)
Comment (clarani) [reply front/src/modules/timesStops/TimesStops.tsx]: I understand that this significantly increases the number of parameters for the function, but I believe it's better to extract the logic into a smaller function. Initially, I suggested this because I found the component already quite difficult to read, and I thought that moving this test into a separate function would simplify the component's code.

What do you think ?

File: front/src/modules/pathfinding/utils.ts (hunk 5 above)
Comment (clarani) [reply front/src/modules/pathfinding/utils.ts:134]: Ok, then can you just add a const so we don't have an argument to true in the code ? Like this for instance
```
const WITH_KP = true;
isVia(pathSteps, rowData, WITH_KP)
```

File: front/src/modules/timesStops/TimesStops.tsx (hunk 8 above)
Comment (clarani) [reply front/src/modules/timesStops/TimesStops.tsx]: I'm ok with that, can you just move the test `'uic' in origin && 'ch' in origin` outside of the findIndex loop ? Also, I think you check if the originIndexInOps position only if the op is an uic, so you can even do it like this:
```
  if ('uic' in origin && 'ch' in origin) {
    const originIndexInOps = operationalPoints.findIndex(
      (op) => op.uic === origin.uic && op.ch === origin.ch && op.name === origin.name
    );
    // If the origin is in the ops and isn't the first operational point, we need to move it to the first position
    if (originIndexInOps !== (-1 || 0)) {
      formattedOps = formattedOps.toSpliced(originIndexInOps, 1);
      formattedOps.unshift(operationalPoints[originIndexInOps]);
    }
  }
```

File: front/src/modules/timesStops/TimesStops.tsx (hunk 4 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Ok I understand. Done.

File: front/src/modules/pathfinding/utils.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/utils.ts:134]: Done

File: front/src/modules/timesStops/TimesStops.tsx (hunk 8 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/TimesStops.tsx]: Done

File: front/src/modules/timesStops/consts.ts (hunk 12 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/consts.ts]: Done

File: front/src/modules/timesStops/types.ts (hunk 13 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/types.ts:3]: eslint doesn't do that for types

File: front/src/modules/timesStops/utils.ts (hunk 14 above)
Comment (SharglutDev) [reply front/src/modules/timesStops/utils.ts]: Done

**Review by achrafmohye — APPROVED** [review]
This looks nice to me :), good job @clarani for the reviews  🥇

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
