### PR TITLE
Fix a few bugs shown by the fuzzer

### LINKED ISSUE #974: Two allowance related asserts can be triggered by the fuzzer
- [x] https://github.com/DGEXSolutions/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/envelope_sim/IntegrationStep.java#L43
- [x] https://github.com/DGEXSolutions/osrd/blob/dev/core/src/main/java/fr/sncf/osrd/envelope/OverlayEnvelopeBuilder.java#L49
  - [x] Reproduce in unit test
  - [x] Fix
 
To reproduce: run the fuzzer on an imported infra

### LINKED ISSUE #975: When running the fuzzer, some requests timeout

### PR DESCRIPTION
**Pull request by eckter**

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/envelope_sim/pipelines/MaxSpeedEnvelope.java [hunk 1]
```diff
@@ -28,7 +28,12 @@ static boolean increase(double prevPos, double prevSpeed, double nextPos, double
     private static Envelope addBrakingCurves(EnvelopeSimContext context, Envelope mrsp) {
         var builder = OverlayEnvelopeBuilder.backward(mrsp);
         var cursor = EnvelopeCursor.backward(mrsp);
+        var lastPosition = mrsp.getEndPos();
         while (cursor.findPartTransition(MaxSpeedEnvelope::increase)) {
+            if (cursor.getPosition() > lastPosition) {
+                cursor.nextPart();
+                continue;
+            }
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/pipelines/MaxSpeedEnvelope.java]: please add a comment: "if a breaking curve starts inside the next breaking curve, it is completely hidden"

**Review by multun — APPROVED** [review]
