### PR TITLE
fix short route reservation

### LINKED ISSUE #128: Route reservation fail when a route is a single TVD section long
As we reserve the next route upon reaching an interaction point, if the only reservation points on a route are its beginning and end, we end up moving to the next route without reserving it first. It happens in some infras. 

It would be best to rework the reservation system entirely, but for now we can reserve several routes if one is too short.

### PR DESCRIPTION
**Pull request by eckter**
Fixes #128

This breaks a test that isn't a high priority at the moment, I disabled it and opened the issue #129

### CODE REVIEW

File: src/main/java/fr/sncf/osrd/train/Train.java [hunk 1]
```diff
@@ -53,10 +53,10 @@ public static Train create(
                 0
         );
 
-        ActivateRoute.trainCreation(sim, initialState);
 
         var trainCreatedChange = new TrainCreatedChange(sim, schedule, initialState);
         var train = trainCreatedChange.apply(sim);
+        ActivateRoute.trainCreation(sim, initialState);
```
Comment (flomonster) [inline src/main/java/fr/sncf/osrd/train/Train.java:58]: This seems weird. Why the route should be activated after creating the train?

Comment (eckter) [reply src/main/java/fr/sncf/osrd/train/Train.java:58]: We need the train to be created to request a reservation here: https://github.com/DGEXSolutions/osrd-core/pull/130/files#diff-8592b45448bfbb047d9f36930ddfc0298530bc3489755028ea72a3b71af1fb48R68

**Review by flomonster — APPROVED** [review]
