### PR TITLE
editoast: model: remove offset-based listing query

### LINKED ISSUE #15852: Paginated database queries consume too much I/O
## What happened?

Loading requirements can be very slow in production (~2min, or even timeout).

> [!CAUTION]
> This issue causes multiple core restarts when it tries to load requirements. At the end the service is never ready to take stdcm queries, which is a critical issue. 

Investigation done by: @bougue-pe @gaetan-osrd @leovalais and @flomonster 
- Traces show that the issue comes from the database, I/O load is too high.
- The query that retrieves train schedules is the one that can take a lot of times and also consuming a lot of I/O.
- We used dalibo to analyze the query: https://explain.dalibo.com/plan/2f7abh81142dg48e#plan
  - We are performing an index scan which seems nice, the issue is that the index scan read a lot of data (see below screen shot)

**IO & Buffers: Original query**
Image

## How to fix 🚧

The principal idea is to stop using `OFFSET`, which requires reading data, but instead use a `WHERE` condition on the last page object id. There is two ways to implement it

### **Solution 1⌛: Adapt pagination API**

When replacing the `OFFSET` by a condition on the id we have amazing results.

Query:
```sql
EXPLAIN (ANALYZE,
         costs,
         VERBOSE,
         buffers,
         format JSON)
SELECT "train_schedule"."id",
       "train_schedule"."train_name",
       "train_schedule"."labels",
       "train_schedule"."rolling_stock_name",
       "train_schedule"."train_schedule_set_id",
       "train_schedule"."start_time",
       "train_schedule"."schedule",
       "train_schedule"."margins",
       "train_schedule"."initial_speed",
       "train_schedule"."comfort",
       "train_schedule"."path",
       "train_schedule"."constraint_distribution",
       "train_schedule"."speed_limit_tag",
       "train_schedule"."power_restrictions",
       "train_schedule"."options",
       "train_schedule"."time_window",
       "train_schedule"."interval",
       "train_schedule"."main_category",
       "train_schedule"."sub_category",
       "train_schedule"."exceptions"
FROM "train_schedule"
WHERE ("train_schedule"."train_schedule_set_id" = ANY(array[1168])
       AND id > 5984736) -- Here 1168 is an example
ORDER BY "train_schedule"."id" ASC
LIMIT 100
```

Dalibo analyze: https://explain.dalibo.com/plan/6e38g6gh9693b73e#plan

Image

### **Solution 2 ✅: Prefetch the id using `OFFSET` and the read full data**

To avoid having to change API and keep using standard pagination we can retrieve the id first using `OFFSET` and inject it to the solution 1 query. This provie great results.

> [!TIP]
> It's surprising that postgresql is not doing it automatically.  

Query:
```sql
EXPLAIN (ANALYZE,
         COSTS,
         VERBOSE,
         BUFFERS,
         FORMAT JSON)
SELECT "train_schedule"."id",
       "train_schedule"."train_name",
       "train_schedule"."labels",
       "train_schedule"."rolling_stock_name",
       "train_schedule"."train_schedule_set_id",
       "train_schedule"."start_time",
       "train_schedule"."schedule",
       "train_schedule"."margins",
       "train_schedule"."initial_speed",
       "train_schedule"."comfort",
       "train_schedule"."path",
       "train_schedule"."constraint_distribution",
       "train_schedule"."speed_limit_tag",
       "train_schedule"."power_restrictions",
       "train_schedule"."options",
       "train_schedule"."time_window",
       "train_schedule"."interval",
       "train_schedule"."main_category",
       "train_schedule"."sub_category",
       "train_schedule"."exceptions"
FROM "train_schedule"
WHERE ("train_schedule"."train_schedule_set_id" = ANY(array[1168])
       AND id >
         (SELECT id
          FROM "train_schedule"
          WHERE ("train_schedule"."train_schedule_set_id" = ANY(array[1168]))
          ORDER BY "train_schedule"."id" ASC
          LIMIT 1
          OFFSET 60000))
ORDER BY "train_schedule"."id" ASC
LIMIT 100
```

Dalibo analyze: https://explain.dalibo.com/plan/1h1he39g683cdc9f#plan

Image

-----------

> [!NOTE]
> Even if the first solution is better (faster), it requires too much changes. So we will go for the second one and keep in mind the first solution if required one day. 

## What did you expect to happen?

Better performances, time response should be better, but more importantly, the database should be less stressed.

## How can we reproduce it (as minimally and precisely as possible)?

You can re-run queries, the most important part is to have a high number of train shcedules within your database.

## On which environments the bug occurs?

Production (SNCF)

## On which browser the bug occurs?

Firefox

## OSRD version (top right corner `Account` button > `Informations`)

1efc54a

### PR DESCRIPTION
**Pull request by leovalais**
fixes https://github.com/OpenRailAssociation/osrd/issues/15852

Scrolling though OFFSET rows wastes a lot of IO and time when there's a
lot of rows. We should instead use cursors. In order to avoid changing
the API right now (though we eventually should) we compute the cursor
using a subquery. IO is wasted, but significantly less.

### CODE REVIEW

File: editoast/editoast_derive/src/model/codegen/list_impl.rs [hunk 1]
```diff
@@ -36,34 +38,80 @@ impl ToTokens for ListImpl {
...
+                        }
+
+                        for sort_fun in &settings.sorts {
+                            let crate::prelude::SortSetting(sort) = (*sort_fun)();
+                            first_pk_query = first_pk_query.order_by(sort);
+                        }
+
+                        if settings.sorts.is_empty() {
+                            first_pk_query = first_pk_query.order_by(dsl::#primary_key.asc());
+                        }
```
Comment (bougue-pe) [inline editoast/editoast_derive/src/model/codegen/list_impl.rs:100]: nit: Can't we mutualize the code with the main query? At least having things done in separately and in the same order (codewise) could help.

Also grouping the "sorts" part may be nice (not sure what's the most idiomatic, though if/else?).

This is also true at a larger level as the modifications are the same on the 3 files.

**Review by bougue-pe — APPROVED** [review]
I'm gonna try to test it locally, but I don't promise anything on that today.

If someone is able to test it vs. a larger db (closer from prod), it's welcome.

Anyway, this shouldn't be blocking IMO, and the next QA session on thrusday should be a good enough challenge.

**Review by woshilapin — APPROVED** [review]

File: editoast/editoast_derive/src/model/codegen/list_impl.rs (hunk 1 above)
Comment (leovalais) [reply editoast/editoast_derive/src/model/codegen/list_impl.rs:100]: The `sort` and `filter` bindings created in each loop are diesel's dsl ast nodes. Those are not clonable, hence the need for factory functions (making the API terrible btw).

I reordered the application of sorting and filters so that things read more easily for both queries. https://github.com/OpenRailAssociation/osrd/compare/e02ec1254ea84ca17070e50108ba5d7b5a75ae84..9b2ee4fd79af13ffb738d40073a345a659257a4b. I'm not sure I can do more in the context/timing of this PR as the rest (if I understand properly) would imply changing `trait List`'s API.

Resolving to merge to reach tomorrow's, uh, "recipe"?

**Comment by leovalais** [comment]
I tried to bench it on my machine but that was underwhelming. I generated 70K train schedules (short json data, I guess that's important here) and measured unrolling 100x100 requirements against dev. I got about 15% increase for SQL queries and nothing significant for the whole queries. I didn't dig more, maybe the issue with prod is PostgreSQL worker being a toaster and I can't replicate it on the same degree on my machine? I cannot test it in prod either since the DB has been wiped. I guess we'll see if the issue comes back 🤷

File: editoast/editoast_derive/src/model/codegen/list_impl.rs (hunk 1 above)
Comment (bougue-pe) [reply editoast/editoast_derive/src/model/codegen/list_impl.rs:100]: 👍
I had "QA session" for "recipe" 😝 

I didn't bench it properly, but had it working locally (SNCF's laptop, 32Gb) for >20500 trains, loading it (already computed beforehand) in ~11 min (vs. also ~11 min without the fix), which seems OK at least ✅.

The point for prod was the limitation on IOPS, which was more important on the last pages (as we retrieve complete rows before just to ditch them): we had to get over the "3000 IOPS" limitation of AWS to start trigger the issue (and start queueing in PG).

Comment (leovalais) [reply editoast/editoast_derive/src/model/codegen/list_impl.rs:100]: I benched on the last 100 pages. Noticed an improvement on individual sql queries, nothing drastic though. On the whole bunch of requirement requests, nothing significant. (Note: I can't remember if I disabled caching...)

Comment (leovalais) [reply editoast/editoast_derive/src/model/codegen/list_impl.rs:100]: Thanks for testing on your side!
