### PR TITLE
front: fix default side value for signals in editor

### LINKED ISSUE #7445: front: on the signal editor, side is filled but marked as missing
### What happened?

When trying to create a signal, the side select is filled, but when I click on save, the form is invalid because side is apparently missing
image

### What did you expect to happen?

Side should no be missing: either initialize it to LEFT or do not fill the select by default

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the editor and select an infra
2. Click on the signal tool
3. Fill the form without modifying the side input
4. Click on save

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev c231679

### PR DESCRIPTION
**Pull request by emersion**
The editor forms are automatically generated by rjsf from the infra JSON Schema. The schema is automatically generated from Python classes by pydantic. The schema contains some unnecessary "allOf" fields (which could just be inlined), and [rjsf chokes on them][1] when handling default values. Unfortunately the "allOf" fields cannot easily be simplified (because of the auto-generation), and rjsf cannot easily be fixed (the logic to handle defaults is quite involved).

As a workaround, manually specify the default for extensions.sncf.side so that the form data always includes this field.

Closes: https://github.com/OpenRailAssociation/osrd/issues/7445

[1]: https://github.com/rjsf-team/react-jsonschema-form/issues/3599

* * *

Let me know if you'd prefer a fix in rjsf instead (would take a tad more time, maybe a few days).

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Thank you for this PR !!
LGTM !!! Review and tested

File: front/src/applications/editor/components/EntitySumUp.tsx [hunk 1]
```diff
@@ -132,14 +132,8 @@ function getSumUpContent(
...
       break;
     }
-    // @ts-expect-error: Here we only deal with the installation_type, the rest is handled with BufferStop and Detector.
-    case 'Signal': {
-      const signal = entity as SignalEntity;
-      if (signal.properties.extensions.sncf.installation_type) {
-        type += ` - ${signal.properties.extensions.sncf.installation_type}`;
-      }
-    }
     // eslint-disable-next-line no-fallthrough
```
Comment (SharglutDev) [inline front/src/applications/editor/components/EntitySumUp.tsx]: I think you can remove this line

File: front/src/applications/editor/components/EntitySumUp.tsx [hunk 2]
```diff
@@ -132,14 +132,8 @@ function getSumUpContent(
...
+    case 'Signal':
     case 'BufferStop':
     case 'Detector': {
       // This cast is OK since both buffer stops and detectors have same
```
Comment (SharglutDev) [inline front/src/applications/editor/components/EntitySumUp.tsx]: Could you merge this comment with the next line ? :)

File: front/src/applications/editor/tools/pointEdition/utils.ts [hunk 3]
```diff
@@ -18,7 +18,9 @@ export function getNewSignal(point?: [number, number]): SignalEntity {
     properties: {
       id: NEW_ENTITY_ID,
       extensions: {
-        sncf: {},
+        sncf: {
+          side: 'CENTER',
```
Comment (SharglutDev) [inline front/src/applications/editor/tools/pointEdition/utils.ts:22]: Should we leave it with "LEFT" by default ?

**Review by SharglutDev — COMMENTED** [review]
Thank you for the fix ! Left some suggestions

File: front/src/applications/editor/components/EntitySumUp.tsx (hunk 1 above)
Comment (emersion) [reply front/src/applications/editor/components/EntitySumUp.tsx]: Indeed, done!

File: front/src/applications/editor/components/EntitySumUp.tsx (hunk 2 above)
Comment (emersion) [reply front/src/applications/editor/components/EntitySumUp.tsx]: Hm, what do you mean?

File: front/src/applications/editor/tools/pointEdition/utils.ts (hunk 3 above)
Comment (emersion) [reply front/src/applications/editor/tools/pointEdition/utils.ts:22]: Both the [JSON schema](https://github.com/OpenRailAssociation/osrd/blob/66b26ab16650cef15baf6a40fa2ed0fba4ed317b/front/src/reducers/osrdconf/infra_schema.json#L1125) and [editoast](https://github.com/OpenRailAssociation/osrd/blob/66b26ab16650cef15baf6a40fa2ed0fba4ed317b/editoast/editoast_schemas/src/infra/side.rs#L16) have CENTER as the default, so I assumed this was the value that made the most sense from a UX point-of-view.

**Review by kmer2016 — APPROVED** [review]
LGTM

File: front/src/applications/editor/components/EntitySumUp.tsx (hunk 2 above)
Comment (emersion) [reply front/src/applications/editor/components/EntitySumUp.tsx]: Resolved this in-person: the comment fits on a single line. While at it, also adjusted the comment to make it clear that signals also have the same props.
