### PR TITLE
Fix bug on mareco high bound

### LINKED ISSUE #628: New version of mareco can have a solution outside of bisect range
If we add a very small allowance value, sometimes the search doesn't converge because the solution is outside of the initial range, the upper bound isn't high enough. I could just raise it but I don't feel comfortable doing so without at least @axrolld input

To reproduce, run the fuzzer

### PR DESCRIPTION
**Pull request by axrolld**
Closes #628 

This PR is renaming and reorganizing MarecoAllowance, as well as fixing a small bug with the initial high bound of the binary search, so lots of changes but acutally only a small part is really relevant (see comment).

### CODE REVIEW

**Review by eckter — DISMISSED** [review]
There's a lot of changes from methods being moved around in the file and github is confused, I assume not much have really changed

File: core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java [hunk 1]
```diff
@@ -64,72 +59,133 @@ private MarecoSpeedLimit() {
...
         // formulas given by MARECO
         var wle = v1 * v1 * context.rollingStock.getRollingResistanceDeriv(v1);
         return wle * v1 / (wle + context.rollingStock.getRollingResistance(v1) * v1);
     }
 
-    private Envelope computeMarecoCore(Envelope coreBase, double v1) {
-        double vf = computeVf(v1);
+    /** Compute the initial high bound for the binary search
+     *  The high bound ensures that the speed vf will be higher than the max speed of the envelope */
+    private double computeInitialHighBound(Envelope section) {
```
Comment (axrolld) [inline core/src/main/java/fr/sncf/osrd/envelope_sim/allowances/MarecoAllowance.java:71]: This is the only relevant change in this PR

**Review by eckter — APPROVED** [review]
