### PR TITLE
front: fix left column width inconsistency with rolling stock

### LINKED ISSUE #13191: front : width of the left column changes depending on the rolling stock
### What happened?

When I edit a paced train or an occurrence and change the rolling stock, the width of the left column changes depending on rolling stock 
What’s strange is that the column size is smaller when the train is long (as in the case of a TGV)
check the video bellow 

https://github.com/user-attachments/assets/2d54625f-9c18-4d75-93b6-fd253d20bf47

### What did you expect to happen?

Keep the same size regardless of the rolling stock

### How can we reproduce it (as minimally and precisely as possible)?

Watch the video above

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

9a71fc8

### PR DESCRIPTION
**Pull request by theocrsb**
closes [#13191](https://github.com/OpenRailAssociation/osrd/issues/13191)

The className `left-column` was not applied.

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/ManageTimetableItemLeftPanel.tsx [hunk 1]
```diff
@@ -87,114 +87,116 @@ const ManageTimetableItemLeftPanel = ({
   };
 
   return (
-    <div className="scenario-timetable-manage-timetable-item left-column">
-      <div className="scenario-timetable-manage-timetable-item-header">
-        {displayTimetableItemManagement === MANAGE_TIMETABLE_ITEM_TYPES.edit &&
-          timetableItemToEditData && (
+    <div className="scenario-content-v2">
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/ManageTimetableItemLeftPanel.tsx]: Seems weird to add this div/class as we already have it in `ScenarioContent.tsx`.

We could rather move the `ManageTimetableItemModal` block inside the `main` block in `ScenarioContent.tsx` and it would achieve the same goal.

Comment (theocrsb) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/ManageTimetableItemLeftPanel.tsx]: Done!

**Review by achrafmohye — APPROVED** [review]
LGTM and tested 👍

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ✅
