### PR TITLE
front: fix stop types in stdcm table results and simulation report sheet

### LINKED ISSUE #9097: STDCM new interface : some stop types bugs
### What happened?

- [x] a blank page may appear when we try to save the simulation (when we select the driver switch without changing the stop time)
- [x] the stop type is not defined on the reloaded page 
- [x] the OP with the stop may appear as “=” if it has the same name as the previous OP. 
- [x] the “passage” stop type does not appear in the results of the simulation table (image 1)
- [x] the “passage” stop type does not appear in blue on the simulation report sheet table (image 2)

Image

Image

### What did you expect to happen?

all work well

### How can we reproduce it (as minimally and precisely as possible)?

Go to the new STDCM interface and add vias 

### On which environments the bug occurs?

Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

a5e9ca2

### PR DESCRIPTION
**Pull request by Akctarus**
closes #9097

### CODE REVIEW

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 1]
```diff
@@ -139,56 +140,62 @@ const SimulationReportSheet = ({
...
+                        <TD style={styles.convoyAndRoute.stopTableItalicColumn}>
+                          {(() => {
+                            if (isLastStep) {
+                              if (step.arrivalType === 'preciseTime') {
+                                return convertDateTimeStringToHHMM(step.arrival);
+                              }
+                              return t('asap');
+                            }
+                            return '';
+                          })()}
```
Comment (Uriel-Sautron) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: This part of the code is repeated below, we could perhaps put it in a variable

Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: done

**Review by Uriel-Sautron — APPROVED** [review]
LGTM, tested !!!

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 2]
```diff
@@ -32,6 +34,16 @@ const SimulationReportSheet = ({
     path_number2: 'n°YYYYYY',
   };
 
+  const getArrivalTime = (step: PathStep, isFirstStep: boolean, isLastStep: boolean) => {
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: Use this syntax. It's more easier to read
```suggestion
  const getArrivalTime = (step: PathStep, { isFirstStep, isLastStep }: { isFirstStep?: boolean; isLastStep?: boolean }) => {
```

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 3]
```diff
@@ -257,6 +259,14 @@ const SimulationReportSheet = ({
                 const isFirstStep = index === 0;
                 const isLastStep = index === operationalPointsList.length - 1;
                 const prevStep = operationalPointsList[index - 1];
+                const simulationPathStepsWithoutFirstAndLast = stdcmData.simulationPathSteps.slice(
+                  1,
+                  -1
+                );
+                const isViaInSimulationPath = simulationPathStepsWithoutFirstAndLast.some(
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: I think you can remove this const since it is used only once
```suggestion
                const isViaInSimulationPath = stdcmData.simulationPathSteps.slice(
                  1,
                  -1
                ).some(
```

File: front/src/utils/timeManipulation.ts [hunk 4]
```diff
@@ -88,3 +88,13 @@ export function secToHoursString(sec: number | null, { withSeconds = false } = {
   const format = withSeconds ? '%H:%M:%S' : '%H:%M';
   return d3.utcFormat(format)(new Date(sec * 1000));
 }
+
+export function convertDateTimeStringToHHMM(dateTimeString: string) {
```
Comment (clarani) [inline front/src/utils/timeManipulation.ts]: I think you can remove this function and reuse `extractHHMM`

**Review by clarani — APPROVED** [review]

File: front/src/utils/timeManipulation.ts (hunk 4 above)
Comment (Akctarus) [reply front/src/utils/timeManipulation.ts]: done

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx (hunk 3 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: done

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx (hunk 2 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: done

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 5]
```diff
@@ -55,6 +56,18 @@ const SimulationReportSheet = ({
     },
     [mapImageUrl]
   );
+  const getArrivalTime = (
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx:60]: You can add an empty line before getArrivalTime :) 
```suggestion
  
  const getArrivalTime = (
```

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 6]
```diff
@@ -55,6 +56,18 @@ const SimulationReportSheet = ({
...
+    step: PathStep,
+    { isFirstStep, isLastStep }: { isFirstStep: boolean; isLastStep: boolean }
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: You can make isFirstStep and isLastStep nullable
```suggestion
    { isFirstStep, isLastStep }: { isFirstStep?: boolean; isLastStep?: boolean }
```

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 7]
```diff
@@ -163,56 +176,46 @@ const SimulationReportSheet = ({
...
+                        <TD style={styles.convoyAndRoute.stopTableOpColumn}>
+                          {step.name || 'Unknown'}
+                        </TD>
+                      </View>
+                      <View style={styles.convoyAndRoute.stopTableChWidth}>
+                        <TD style={styles.convoyAndRoute.stopTableChColumn}>{step.ch}</TD>
+                      </View>
+                      <View style={styles.convoyAndRoute.stopTableEndWidth}>
+                        <TD style={styles.convoyAndRoute.stopTableItalicColumn}>
+                          {getArrivalTime(step, { isFirstStep: false, isLastStep })}
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: Once isFirstStep and isLastStep are nullable, you can simply remove the false:
```suggestion
                          {getArrivalTime(step, { isLastStep })}
```

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx [hunk 8]
```diff
@@ -281,34 +284,55 @@ const SimulationReportSheet = ({
...
+                              ? styles.simulation.opStop
+                              : styles.simulation.td
                         }
                       >
-                        {!isFirstStep &&
-                        !isLastStep &&
+                        {isNotExtremity &&
+                        !isViaInSimulationPath &&
                         step.name === prevStep.name &&
                         step.duration === 0
```
Comment (clarani) [inline front/src/applications/stdcm/components/SimulationReportSheet.tsx]: I think you can remove this condition.
=" will be displayed if the step is not a via or an extremity and if its name the prevStep.name are the same

```suggestion
```

Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: fixed

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: fixed

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx (hunk 6 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx]: fixed

File: front/src/applications/stdcm/components/SimulationReportSheet.tsx (hunk 5 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/SimulationReportSheet.tsx:60]: fixed

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
