### PR TITLE
Avoid crash when selecting paced occurences in TOD

### LINKED ISSUE #14783: Selecting a paced train occurence in track occupancy diagram crashes
### What happened?

Selecting an occurance of a paced train wihtin the track occupancy diagram lead to a crash.

Image

> [!NOTE]
> I think there is other ways to trigger this bug. 

### What did you expect to happen?

Should not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Import these trains [timetable.json](https://github.com/user-attachments/files/24717880/timetable.json)
3. Open a track occupancy diagram
4. Select the `test` occurence.

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

c9d98b6

### PR DESCRIPTION
**Pull request by Caracol3**
Before, selecting a paced train occurrence in the chart could emit a `paced_*` id instead of an occurrence id. This caused the ETCS braking curves hook to crash because the endpoint expects an `OccurrenceId`. Now we normalize the `id` used for ETCS requests to an occurrence id (projection occurrence when available, otherwise occurrence index 0).

close #14783

### CODE REVIEW

**Comment by theocrsb** [comment]
I can't use the ticket timetable because I'm getting an error. Do you have a timetable that works?

**Comment by Caracol3** [comment]
Yes, you can use this one with small infra
[timetable (1).json](https://github.com/user-attachments/files/24772019/timetable.1.json)

**Comment by theocrsb** [comment]
> Yes, you can use this one with small infra [timetable (1).json](https://github.com/user-attachments/files/24772019/timetable.1.json)

image

I get this error when I import

**Comment by Caracol3** [comment]
Weird, have you rebuild recently ?

**Comment by theocrsb** [comment]
> Weird, have you rebuild recently ?

yes :/

**Review by emersion — COMMENTED** [review]
I'm confused:

- Only timetable items without a `paced` attribute and occurrences can be selected. Timetable items with a `paced` attribute cannot. Why are we getting one?
- The train ID used for projection should have no impact on the ETCS braking curves displayed on the speed-space chart, I believe? (More generally, projection only applies to the time-space chart.)

**Comment by Caracol3** [comment]
1 - You’re right. The TOD should only return occurrences (or non‑paced items), but we were sending `paced_*` for “base” occupations. That’s what caused the crash when clicking a paced occurrence. The fix maps “base” occupations to their indexed occurrence IDs for paced trains so selection always stays an `OccurrenceId` when clicking.

2 - Agreed. I removed the fallback to `trainIdUsedForProjection`. ETCS curves now follow only the selected train.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts [hunk 1]
```diff
@@ -276,7 +300,10 @@ const useTrackOccupancy = ({
             operationalPointPosition: op.position,
             operationalPointName: op.extensions?.identifier?.name || undefined,
             zones: opState.zones.data?.map((zone) => {
-              const trainStationLabels = trainsStationLabelsRef.current[zone.trainId];
+              const stationLabelsId = isOccurrenceId(zone.trainId)
+                ? extractPacedTrainIdFromOccurrenceId(zone.trainId)
+                : zone.trainId;
+              const trainStationLabels = trainsStationLabelsRef.current[stationLabelsId];
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: If the occurrence is an exception which changes the train path, I think this will give the wrong result. I think we should keep the old code here.

**Comment by theocrsb** [comment]
The bug is no longer present on dev :/

File: front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts [hunk 2]
```diff
@@ -63,17 +67,31 @@ const useEtcsBrakingCurves = (
...
-      throw new Error(`trainId ${selectedTrainId} should be a occurrence id`);
-    return findExceptionWithOccurrenceId(timetableItem.paced.exceptions, selectedTrainId);
+
+  // ETCS endpoint expects an OccurrenceId for paced trains (chart may emit `paced_*`).
+  const trainIdUsedForEtcsBrakingCurves = useMemo(() => {
+    if (!selectedTrainId) return undefined;
+    if (!timetableItem || !isPacedTrain(timetableItem)) return selectedTrainId;
+    if (isOccurrenceId(selectedTrainId)) return selectedTrainId;
+    return isPacedTrainId(selectedTrainId)
+      ? formatPacedTrainIdToIndexedOccurrenceId(selectedTrainId, 0)
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts]: I'm still not understanding why we're getting a paced train ID here. When clicking on the track occupancy diagram, an occurrence is selected, not the paced train.

**Comment by emersion** [comment]
> The bug is no longer present on dev :/

FWIW, I can reproduce on the `dev` branch (using the timetable linked in the issue).

File: front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts (hunk 2 above)
Comment (Caracol3) [reply front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts]: `selectedTrainId` is a `TrainId` (so a paced or occurrence), and I think it can be set from other entry points than the occupancy chart (e.g. selecting a paced timetable item would store a `paced_* id`). Also, the chart click handler seems to dispatch whatever `pathId` it gets, so we may still end up with a `paced_*` here even when the user intended to select an occurrence.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts (hunk 1 above)
Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: You're right.
I reverted this part to the previous behavior for now, but we can add a TODO to revisit the station labels logic for occurrences/exceptions later.
What do you think ?

File: front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts (hunk 2 above)
Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useEtcsBrakingCurves.ts]: > selecting a paced timetable item would store a paced_* id

A paced train with a `paced` field cannot be selected. Only paced trains without `paced` fields and occurrences can be selected.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts [hunk 3]
```diff
@@ -191,6 +191,29 @@ const useTrackOccupancy = ({
             if (!train) throw new Error(`No train found for id ${pacedId}`);
 
             if (occupation.type === 'base') {
+              if (train.paced) {
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: It seems like very similar code is repeated below. Can we:

- Replace `if (occupation.type === 'base')` with `if (!train.paced)` here?
- Allow the code below to work with a null/undefined `exception`?

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx [hunk 4]
```diff
@@ -364,8 +364,23 @@ const SpaceTimeChartWrapper = ({
         isOccupancyPickingElement(hoveredItem.element))
     ) {
       const clickedTrainId = hoveredItem.element.pathId;
-      if (isTrainId(clickedTrainId) && selectedTrainId !== clickedTrainId) {
-        onTrainClick(clickedTrainId);
+      if (isTrainId(clickedTrainId)) {
+        const trainIdToSelect: TrainId = !isPacedTrainId(clickedTrainId)
+          ? clickedTrainId
+          : (() => {
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx]: Could we avoid using anonymous closures which are immediately invoked? These are hard to read.

The logic here can be rewritten:

```ts
let trainIdToSelect: TrainId;
if (isPacedTrainId(clickedTrainId)) {
  if (selectedTrainId && isOccurrenceId(selectedTrainId) && …) {
    trainIdToSelect = selectedTrainId;
  } else {
    trainIdToSelect = formatPacedTrainIdToIndexedOccurrenceId(clickedTrainId, 0);
  }
} else {
  trainIdToSelect = clickedTrainId;
}
```

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx [hunk 5]
```diff
@@ -364,8 +364,23 @@ const SpaceTimeChartWrapper = ({
...
+              if (
+                selectedTrainId &&
+                isOccurrenceId(selectedTrainId) &&
+                extractPacedTrainIdFromOccurrenceId(selectedTrainId) === clickedTrainId
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx]: I'm not sure I'm following what's going on here. Why do we need to add a special-case when an occurrence is currently selected and we click on its base paced train?

We shouldn't get a paced train here in the first place.

Do you still get a paced train with your `useTrackOccupancy()` changes?

Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx]: Indeed I added this before updating `useTrackOccupancy.ts`. Now TOD zones use occurrence ids, so this special-case is no longer needed. I removed it.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts (hunk 3 above)
Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: - If we replace it with `if (!train.paced)`, wouldn’t we still need a dedicated branch for `occupation.type === 'base'`, since the code below looks up `exception` / `exceptionProjection` using `occupation.exception_key` (and there is no exception context in the base case), so we’d just move the branching ?

- If we allow exception to be nullable, wouldn’t the “non-base” branch need a lot of extra checks, making the code harder to read ?

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx (hunk 4 above)
Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/SpaceTimeChartWrapper.tsx]: With the `useTrackOccupancy` changes, TOD clicks now provide an occurrence id, so we no longer need that extra conversion logic here; I removed it and we now just dispatch `clickedTrainId` directly.

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts (hunk 3 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: I think with the [optional chaining operator `?`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) the non-base branch is almost identical (see diff below). But if you prefer to keep the status quo, I'm fine with that too!

```diff
diff --git a/front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts b/front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts
index c4b00cedac73..a350f1123a0c 100644
--- a/front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts
+++ b/front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts
@@ -190,30 +190,11 @@ const useTrackOccupancy = ({
 
             if (!train) throw new Error(`No train found for id ${pacedId}`);
 
-            if (occupation.type === 'base') {
-              if (train.paced) {
-                const occurrenceId = formatPacedTrainIdToIndexedOccurrenceId(
-                  pacedId,
-                  occupation.index
-                );
-                const occurrenceName = computeOccurrenceName(train.name, occupation.index);
-                const occurrenceStartTime = computeIndexedOccurrenceStartTime(
-                  train.departureTime,
-                  train.paced.interval,
-                  occupation.index
-                );
-                zones.push(
-                  getMovableOccupancyZone(
-                    trackId,
-                    occurrenceId,
-                    occupation,
-                    train.spaceTimeCurves,
-                    occurrenceName,
-                    occurrenceStartTime
-                  )
+            if (!train.paced) {
+              if (occupation.type !== 'base')
+                throw new Error(
+                  `Invalid occupation type ${occupation.type} for train schedule ${train.id}`
                 );
-                continue;
-              }
               zones.push(
                 getMovableOccupancyZone(
                   trackId,
@@ -227,14 +208,12 @@ const useTrackOccupancy = ({
               continue;
             }
 
-            if (!train.paced) throw new Error(`Train with id ${train.id} is not a paced train`);
-
-            const exception = train.paced.exceptions.find(
-              (e) => e.key === occupation.exception_key
-            );
-            const exceptionProjection = train.paced.exceptionProjections.get(
-              occupation.exception_key
-            );
+            let exception, exceptionProjection;
+            if (occupation.type !== 'base') {
+              exception = train.paced.exceptions.find((e) => e.key === occupation.exception_key);
+              exceptionProjection = train.paced.exceptionProjections.get(occupation.exception_key);
+              if (!exception) throw new Error(`Exception not found for train ${train.id}`);
+            }
 
             const { spaceTimeCurves } = exceptionProjection ?? train;
 
@@ -242,10 +221,8 @@ const useTrackOccupancy = ({
             let trainName: string;
             let startTime: Date;
 
-            if (!exception) throw new Error(`Exception not found for train ${train.id}`);
-
             if (occupation.type === 'created') {
-              if (!exception.start_time?.value)
+              if (!exception?.start_time?.value)
                 throw new Error(`Created exceptions should always be a start time exception`);
 
               trainId = formatPacedTrainIdToExceptionId(pacedId, occupation.exception_key);
@@ -254,9 +231,9 @@ const useTrackOccupancy = ({
             } else {
               trainId = formatPacedTrainIdToIndexedOccurrenceId(pacedId, occupation.index);
               trainName =
-                exception.train_name?.value ?? computeOccurrenceName(train.name, occupation.index);
+                exception?.train_name?.value ?? computeOccurrenceName(train.name, occupation.index);
 
-              startTime = exception.start_time?.value
+              startTime = exception?.start_time?.value
                 ? new Date(exception.start_time.value)
                 : computeIndexedOccurrenceStartTime(
                     new Date(train.departureTime),
```

Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: You’re right,  thanks for the suggestion. 
Works great :-)

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts [hunk 6]
```diff
@@ -204,25 +209,24 @@ const useTrackOccupancy = ({
...
-            const exception = train.paced.exceptions.find(
-              (e) => e.key === occupation.exception_key
-            );
-            const exceptionProjection = train.paced.exceptionProjections.get(
-              occupation.exception_key
-            );
+            let exception: (typeof train.paced.exceptions)[number] | undefined;
+            let exceptionProjection:
+              | (typeof train.paced.exceptionProjections extends Map<string, infer V> ? V : never)
+              | undefined;
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: These types are quite complicated - can we simplify them, by using their name instead of inferring them from variables?

In my testing TypeScript was happy without type information. Is your editor using an old TypeScript version?

Comment (Caracol3) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/useTrackOccupancy.ts]: I replaced the inferred types with named types, and this is indeed much clearer. Thanks!

**Review by emersion — APPROVED** [review]
Thanks a lot for bearing with me until the end!

LGTM
