### PR TITLE
front: fix trains not stopping at the end of path

### LINKED ISSUE #7863: tsv2: no more default stops at the end of the train runs
### What happened?

My train does not stop at the end anymore 😢 I'm affraid the passengers won't be able to hop on anymore
image

### What did you expect to happen?

I'm expecting the train to stop automatically at the end as it was the case before.

This implies having a `0` in `Stopping time` on the last line of the times and stop table AND a cross to delete this stop if the user wants to :
image

> [!WARNING]
> Don't do this before [this bug](https://github.com/OpenRailAssociation/osrd/issues/7868) is fixed !

### How can we reproduce it (as minimally and precisely as possible)?

1. Compute any train

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0

### LINKED ISSUE #7868: Add a stop for 0s crashes the application
### What happened?

When a train schedule is created with a stop at `0s`, the front end crashes

image

### What did you expect to happen?

It should create a stop of `0`s and still work.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Add a train
3. Add a stop of `0`s to the last step
4. Create the train 

----------------

Here is what the train schedule payload looks likes (could be use for import):

```json
[
  {
    "train_name": "a",
    "labels": [],
    "rolling_stock_name": "3B81504",
    "start_time": "2024-06-27T09:00:00Z",
    "path": [
      {
        "id": "id1150",
        "deleted": false,
        "track": "6499a8c0-6667-11e3-81ff-01f464e0362d",
        "offset": 1584
      },
      {
        "id": "id1168",
        "deleted": false,
        "uic": 87746412,
        "secondary_code": "00"
      },
      {
        "id": "id589",
        "deleted": false,
        "track": "6499fc54-6667-11e3-81ff-01f464e0362d",
        "offset": 0
      }
    ],
    "schedule": [
      {
        "at": "id1168",
        "arrival": null,
        "stop_for": "P0D",
        "on_stop_signal": false,
        "locked": false
      }
    ],
    "margins": {
      "boundaries": [],
      "values": [
        "none"
      ]
    },
    "initial_speed": 0.0,
    "comfort": "STANDARD",
    "constraint_distribution": "MARECO",
    "speed_limit_tag": null,
    "power_restrictions": [],
    "options": {
      "use_electrical_profiles": true
    }
  }
]
```

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: All

### OSRD version (top right corner `Account` button > `Informations`)

d9655c0f05166faff80f744efe979a921347777f

### PR DESCRIPTION
**Pull request by SharglutDev**
close #7868 

Use dayjs to transform a duration in ISO8601 in seconds so that it's resilient to any format of ISO8601 (not only PTxxx)

close #7863 

By default, we add a 0sec stopFor for the destination when launching the pathfinding

### CODE REVIEW

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx [hunk 1]
```diff
@@ -318,8 +318,13 @@ const Pathfinding = ({ pathProperties, setPathProperties }: PathfindingProps) =>
                       kp: correspondingOp.kp,
                       coordinates: correspondingOp.coordinates,
                       positionOnPath: pathfindingResult.path_items_positions[i],
+                      stopFor: i === pathSteps.length - 1 && !step.stopFor ? '0' : step.stopFor,
```
Comment (kmer2016) [inline front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]: Store this instruction inside a variable stopFor and reuse it line 321 and 326
`const stopFor = i === pathSteps.length - 1 && !step.stopFor ? '0' : step.stopFor;`
```suggestion
                      stopFor,
```

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx [hunk 2]
```diff
@@ -318,8 +318,13 @@ const Pathfinding = ({ pathProperties, setPathProperties }: PathfindingProps) =>
...
                     }
-                  : { ...step, positionOnPath: pathfindingResult.path_items_positions[i] };
+                  : {
+                      ...step,
+                      positionOnPath: pathfindingResult.path_items_positions[i],
+                      stopFor: i === pathSteps.length - 1 && !step.stopFor ? '0' : step.stopFor,
```
Comment (kmer2016) [inline front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]:
```suggestion
                      stopFor
```

**Comment by kmer2016** [comment]
I realize that there are some duplication of code used for starting pathfinding in `PathFindingV2.tsx` and `TypeAndPathV2.tsx`. I think we must fix it just after this [PR](https://github.com/OpenRailAssociation/osrd/pull/7818) will merged, because it extract the logic of start pathfinding in a hook.

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]: Done

File: front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/pathfinding/components/Pathfinding/PathfindingV2.tsx]: Done

**Review by kmer2016 — APPROVED** [review]
Good job !

**Review by Caracol3 — COMMENTED** [review]
lgtm 😀
