### PR TITLE
front, editoast: fix getPacedTrainByIdSimulation tags

### LINKED ISSUE #13085: speed space chart of some occurrences when editing a paced train
### What happened?

I have a service.

Then, I add a stopping time in BEA to decrease the speed at the beginning of the itinerary. 

After that, when I look at the speed space chart of my occurrences, I can see that some occurrences are refreshed and some are not. 

I need to refresh my page to have all the correct SDDs.

### What did you expect to happen?

Import this service and add a 09:00 arrival time in Beaune

[timetable (50).json](https://github.com/user-attachments/files/22174217/timetable.50.json)

### How can we reproduce it (as minimally and precisely as possible)?

I expect all the SDDs to be refreshed without having to refresh my page

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

288b0ab

### PR DESCRIPTION
**Pull request by clarani**
closes #13085

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
Editoast part LGTM

File: front/src/common/api/osrdEditoastApi.ts [hunk 1]
```diff
@@ -185,8 +185,7 @@ const osrdEditoastApi = generatedEditoastApi
           }
           return { data: simulation };
         },
-        // TODO: fix getPacedTrainByIdSimulation tags (it should be paced_train)
-        providesTags: ['train_schedule'],
+        providesTags: ['train_schedule', 'paced_train'],
```
Comment (emersion) [inline front/src/common/api/osrdEditoastApi.ts]: We should set these depending on the type of train ID in the request, instead of providing both tags. See e.g. `getTimetableItemById`.

I'd prefer to keep a TODO until this is done.

Comment (clarani) [reply front/src/common/api/osrdEditoastApi.ts]: Done

**Review by emersion — APPROVED** [review]
LGTM, thanks!
