### PR TITLE
Fix track section length when editing geometry

### LINKED ISSUE #5933: Slopes and curves editor can be stuck in invalid state
### What happened?

When the length of a track section is reduced. Curves and gradients are locked in an invalid state. This is due to the use of geometry length instead of track section length.

### What did you expect to happen?

We should  be able to edit the end offset of the last range

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to editor
2. Select a track section
3. Change its length (reduce)
4. Some errors appear on the slopes and curves (OutOfRange)
5. There is no way to fix it

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

3df6fbc

### PR DESCRIPTION
**Pull request by Akctarus**
Closes #5933 

Implementation of a new behavior: when a track section is created, length can be edited directly on the map, but when a length is already entered, the drag must not affect the length.

### CODE REVIEW

**Review by flomonster — CHANGES_REQUESTED** [review]
I still have a bug. When editing a track section with slopes, changing the geometry results in an invalid position in slopes (negative values).

**Review by flomonster — APPROVED** [review]
LGTM. Thanks for this fix :tada: (Tested, not reviewed)

**Review by Wadjetz — APPROVED** [review]

File: front/src/applications/editor/components/LinearMetadata/FormComponent.tsx [hunk 1]
```diff
@@ -427,4 +423,54 @@ export const FormComponent: React.FC<FieldProps> = (props) => {
...
+            }
+          : {}
+      ),
+    [schema, registry.rootSchema, distance]
+  );
+
+  if (!LINEAR_METADATA_FIELDS.includes(name))
+    return <Fields.ArrayField {...props} schema={jsonSchema} />;
+
+  return <IntervalEditorComponent {...props} />;
```
Comment (clarani) [inline front/src/applications/editor/components/LinearMetadata/FormComponent.tsx]: Can you add some props to avoid duplication ? 
```suggestion
  return (
    <IntervalEditorComponent
      jsonSchema={jsonSchema}
      distance={distance}
      requiredFilter={requiredFilter}
      {...props}
    />
  );
```

File: front/src/applications/editor/components/LinearMetadata/FormComponent.tsx [hunk 2]
```diff
@@ -427,4 +423,54 @@ export const FormComponent: React.FC<FieldProps> = (props) => {
...
+                maximum: distance,
+              },
+            }
+          : {}
+      ),
+    [schema, registry.rootSchema, distance]
+  );
+
+  if (!LINEAR_METADATA_FIELDS.includes(name))
+    return <Fields.ArrayField {...props} schema={jsonSchema} />;
```
Comment (clarani) [inline front/src/applications/editor/components/LinearMetadata/FormComponent.tsx]: Can you switch the conditions ?
If the field is a LINEAR_METADATA_FIELDS, return the IntervalEditorComponent, else return the Fields.ArrayField

File: front/src/applications/editor/components/LinearMetadata/FormComponent.tsx [hunk 3]
```diff
@@ -427,4 +423,54 @@ export const FormComponent: React.FC<FieldProps> = (props) => {
...
 };
 
+export const FormComponent: React.FC<FieldProps> = (props) => {
+  const { name, formContext, schema, registry } = props;
+  const Fields = utils.getDefaultRegistry().fields;
+
+  // Get the distance of the geometry
+  const distance = useMemo(() => {
+    if (!isNil(formContext.length)) {
+      return formContext.length;
```
Comment (clarani) [inline front/src/applications/editor/components/LinearMetadata/FormComponent.tsx]: Add a cast here to specify distance type
```suggestion
      return formContext.length as number;
```

File: front/src/applications/editor/tools/trackEdition/utils.ts [hunk 4]
```diff
@@ -29,3 +30,15 @@ export function injectGeometry(track: EditorEntity): EditorEntity {
...
+
+/**
+ * Remove the invalid ranges when the length of the track section has been modified
+ * - keep ranges if begin is undefined in case we just added a new one or if we deleted the begin input value
+ * - remove ranges which start after the new end
+ * - cut the ranges which start before the new end but end after it
+ */
+export function removeInvalidRanges<T>(values: LinearMetadataItem<T>[], newLength: number) {
+  return values
+    .filter((item) => item.begin < newLength || !item.begin)
```
Comment (clarani) [inline front/src/applications/editor/tools/trackEdition/utils.ts]: Why did you add a condition `|| !item.begin` here ?
```suggestion
    .filter((item) => item.begin < newLength)
```

File: front/src/common/IntervalsDataViz/data.ts [hunk 5]
```diff
@@ -238,6 +238,9 @@ export function fixLinearMetadataItems<T>(
       } as LinearMetadataItem<T>,
     ];
   }
+  const filteredItems = items
+    .filter((item) => item.begin < lineLength)
+    .map((item) => (item.end >= lineLength ? { ...item, end: lineLength } : item));
```
Comment (clarani) [inline front/src/common/IntervalsDataViz/data.ts]: Use the function you defined in the utils files
```suggestion
  const filteredItems = removeInvalidRanges(items, lineLength);
```

File: front/src/common/IntervalsDataViz/data.ts [hunk 6]
```diff
@@ -361,8 +364,10 @@ export function update<T>(
   targetLine: LineString,
   linearMetadata: Array<LinearMetadataItem<T>>
 ): Array<LinearMetadataItem<T>> {
+  if (sourceLine.coordinates.length !== 0) {
+    return linearMetadata;
```
Comment (clarani) [inline front/src/common/IntervalsDataViz/data.ts]: Why did you do this change ?
Why do you return linearMetadata ? (it's only a suggestion, maybe I lack context)
```suggestion
    return [];
```

File: front/src/common/IntervalsDataViz/data.ts [hunk 7]
```diff
@@ -673,8 +678,8 @@ export function entityDoUpdate<T extends EditorEntity>(entity: T, sourceLine: Li
       }
     });
     // eslint-disable-next-line dot-notation
-    newProps['length'] = getLineStringDistance(entity.geometry as LineString);
-
+    if (entity.properties.length === 0)
```
Comment (clarani) [inline front/src/common/IntervalsDataViz/data.ts]: Why did you add this condition ?

File: front/src/common/IntervalsDataViz/data.test.ts [hunk 8]
```diff
@@ -79,7 +79,9 @@ function checkWrapperValidity<T>(
   expect(result[0].begin).toEqual(0);
   // we round due to some approximation that result to a diff (below millimeter)
   if (newLine)
-    expect(Math.round(last(result)?.end || 0)).toEqual(Math.round(getLineStringDistance(newLine)));
+    expect(Math.round(last(result)?.end || 0)).not.toEqual(
+      Math.round(getLineStringDistance(newLine))
```
Comment (clarani) [inline front/src/common/IntervalsDataViz/data.test.ts]: Why did you change this test ?

File: front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx [hunk 9]
```diff
@@ -18,8 +20,10 @@ const DebouncedNumberInputSNCF = ({
   setInput,
   debouncedDelay = 800,
   id = '',
-  max = 100,
+  max,
   min = 0,
+  sm = true,
+  showFlex = true,
```
Comment (clarani) [inline front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx]: It's better to set a boolean to false by default

File: front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx [hunk 10]
```diff
@@ -28,19 +32,27 @@ const DebouncedNumberInputSNCF = ({
...
+      const previousValue = input;
+      setInput(previousValue);
+    }
   };
 
   useDebouncedFunc(value, debouncedDelay, checkChangedInput);
 
   return (
-    <div className="debounced-number-input">
+    <div className={`${showFlex ? 'debounced-number-input' : ''}`}>
```
Comment (clarani) [inline front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx]: You can also use cx :)
```suggestion
    <div className={`${showFlex && 'debounced-number-input' }`}>
```

File: front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx [hunk 11]
```diff
@@ -28,19 +32,27 @@ const DebouncedNumberInputSNCF = ({
...
       <InputSNCF
         type="number"
         id={id}
-        isInvalid={value !== null && (value < min || max < value)}
+        isInvalid={value !== null && (value < min || (max ? max < value : false))}
```
Comment (clarani) [inline front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx]:
```suggestion
        isInvalid={value !== null && (value < min || (max !== undefined && max < value))}
```

**Review by clarani — CHANGES_REQUESTED** [review]
Left some comments

File: front/src/common/IntervalsDataViz/data.ts [hunk 12]
```diff
@@ -673,8 +677,8 @@ export function entityDoUpdate<T extends EditorEntity>(entity: T, sourceLine: Li
...
```
Comment (clarani) [inline front/src/common/IntervalsDataViz/data.ts]: Ok so I took a look to the code and I think it is more relevant to move this test line 668. If the entity is not initialized, we update the data, otherwise we don't.
You can also add a comment to explain that the modification of the linestring modifies the entity real properties only during initialization.

If you do that, you can remove the condition l680 and l366-368 too :)

File: front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx [hunk 13]
```diff
@@ -28,19 +32,27 @@ const DebouncedNumberInputSNCF = ({
...
+      const previousValue = input;
+      setInput(previousValue);
+    }
   };
 
   useDebouncedFunc(value, debouncedDelay, checkChangedInput);
 
   return (
-    <div className="debounced-number-input">
+    <div className={`${showFlex && 'debounced-number-input'}`}>
```
Comment (clarani) [inline front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx:51]:
```suggestion
    <div className={showFlex && 'debounced-number-input'}>
```

Comment (Akctarus) [reply front/src/common/BootstrapSNCF/FormSNCF/DebouncedNumberInputSNCF.tsx:51]: It seems that we can't do this because of a type mismatch

**Review by clarani — APPROVED** [review]
LGTM ! You just need to squash your commits :) Thanks :white_check_mark:
