### PR TITLE
Adapt paced train schema nesting `exceptions` field

### LINKED ISSUE #14220: Group all paced fields related in the field paced
### Description and goal

Currently, fields related to a PacedTrain are flattened at the object level:
```
type PacedTrain = TrainSchedule & {
  exceptions: PacedTrainException[];
  paced: {
    interval: PositiveDuration;
    time_window: PositiveDuration;
  };
};
```

The goal now is to group all fields specific to a PacedTrain (and allowing it to be differentiated from a TrainSchedule) in the `paced` field:
```
type PacedTrain = TrainSchedule & {
  paced: {
    interval: PositiveDuration;
    time_window: PositiveDuration;
    exceptions: PacedTrainException[];
  };
};
```

### Implementation plan
Modify the type in editoast and the front-end and adapt each time the code each time we manipulate a pacedTrain.

### PR DESCRIPTION
**Pull request by flomonster**
Closes #14220 

Nest `exceptions` field into the `paced` field.
First step to merge `TrainSchedule` with `PacedTrain`.

### CODE REVIEW

**Review by Synar — APPROVED** [review]
E2E : LGTM ^^

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/formatTimetableItemPayload.ts [hunk 1]
```diff
@@ -63,14 +63,14 @@ export function formatPacedTrainWithDetailsToPacedTrainPayload(
...
     constraint_distribution: pacedTrainWithDetails.constraint_distribution,
-    exceptions: pacedTrainWithDetails.exceptions,
     initial_speed: pacedTrainWithDetails.initial_speed,
     labels: pacedTrainWithDetails.labels,
     margins: pacedTrainWithDetails.margins,
     options: pacedTrainWithDetails.options,
     paced: {
       time_window: pacedTrainWithDetails.paced.timeWindow.toISOString(),
       interval: pacedTrainWithDetails.paced.interval.toISOString(),
+      exceptions: pacedTrainWithDetails.exceptions,
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/formatTimetableItemPayload.ts:73]: Should we change `PacedTrainWithDetails` type as well ?

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts [hunk 2]
```diff
@@ -178,39 +178,40 @@ export function updatePacedTrainExceptionsList<T extends PacedTrainException>(
  * If the exceptions as no change group after those checks, the exception is removed.
  */
 export function checkChangeGroups(
-  updatedPacedTrain: Omit<PacedTrain, 'exceptions'>,
+  updatedTrain: TrainSchedule,
+  paced: PacedTrain['paced'],
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts:182]: Why do we split it here ? Is it to facilitate an upcoming PR when `paced` will be integrated in `TrainSchedule` directly ?

**Review by SharglutDev — COMMENTED** [review]
Great work !

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts (hunk 2 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts:182]: It's to facilitate the 3rd commit directly ;) otherwise, we would have to do smth like that:
```
updatedPacedTrain: Omit<PacedTrain, 'paced'> & { paced: Omit<PacedTrain['paced'], 'exceptions'>},
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/formatTimetableItemPayload.ts (hunk 1 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/formatTimetableItemPayload.ts:73]: Yes, I'm on it, but it will be in another PR to avoid blocking the backend

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/helpers/buildPacedTrainException.ts:182]: Oh right, didn't review by commit :)

**Review by SharglutDev — APPROVED** [review]
Lgtm (not tested)

**Review by Castavo — APPROVED** [review]

**Review by eckter — APPROVED** [review]
LGTM for tests, didn't review editoast / front.

I assume this breaks the current timetable json files, should we provide a short script snippet to migrate those when we make that kind of change? I could probably write one.

**Review by leovalais — APPROVED** [review]

**Comment by flomonster** [comment]
> I assume this breaks the current timetable json files, should we provide a short script snippet to migrate those when we make that kind of change? I could probably write one.

We are not used to provide migration script for timetable (maybe we should 😬). However here is a jq script to migrate your timetables:


```sh
jq '
  .paced_trains |= map(
    .paced.exceptions = (.exceptions // [])
  )
' timetable.json
```

**Review by woshilapin — APPROVED** [review]
