### PR TITLE
front:  fix adding intermediate points hides the result table and result map

### LINKED ISSUE #10204: stdcm: adding intermediate points hides the result table and result map
### What happened?

https://github.com/user-attachments/assets/f52deb72-560e-4d5b-86df-c1f0534e6221

When adding intermediate points in a new request, the result table of previous requests as well as the accompanying map are hidden

### What did you expect to happen?

The table and the map should stay visible with any number of intermediate points

### How can we reproduce it (as minimally and precisely as possible)?

1. go to stdcm
2. get a first simulation
3. look at the result table
4. start a new simulation with more intermdiate points
5. try to look at the result table or map

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev bf0ab67

### PR DESCRIPTION
**Pull request by kmer2016**
close #10204

### CODE REVIEW

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !

File: front/src/applications/stdcm/components/StdcmForm/StdcmVias.tsx [hunk 1]
```diff
@@ -77,10 +77,9 @@ const StdcmVias = ({ disabled = false }: StdcmConfigCardProps) => {
 
     const cancelListener = () => cancelAnimationFrame(requestId);
 
-    newElement.addEventListener('animationend', cancelListener);
+    newElement.parentElement!.addEventListener('animationend', cancelListener);
     return () => {
-      newElement.removeEventListener('animationend', cancelListener);
-      cancelListener();
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmForm/StdcmVias.tsx:83]: Hm, I think we should still cancel the requested animation frame here?

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmVias.tsx:83]: Oh right, missed that 🫤

Comment (kmer2016) [reply front/src/applications/stdcm/components/StdcmForm/StdcmVias.tsx:83]: Oh, mee too, thank you ! :pray:

**Review by emersion — APPROVED** [review]
