### PR TITLE
core: draft of warning system

### LINKED ISSUE #700: Find a way to show warnings from the core
We have an exception system for critical errors, but we also need something for errors that can be ignored

### PR DESCRIPTION
**Pull request by eckter**

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/infra/implementation/signaling/SignalingInfraBuilder.java [hunk 1]
```diff
@@ -73,12 +89,26 @@ private ImmutableNetwork<DiDetector, SignalingRoute> makeSignalingRouteGraph() {
 
     /** Creates the route multimap, calling each module and merging the results */
     private ImmutableMultimap<ReservationRoute, SignalingRoute> makeRouteMap() {
-        return loadAndMergeMultimap(module -> module.createRoutes(reservationInfra, signalMap));
+        var res = loadAndMergeMultimap(module -> module.createRoutes(reservationInfra, signalMap));
```
Comment (flomonster) [inline core/src/main/java/fr/sncf/osrd/infra/implementation/signaling/SignalingInfraBuilder.java]: `module` is a java keyword

**Review by flomonster — DISMISSED** [review]

**Review by flomonster — APPROVED** [review]
