### PR TITLE
front: editor: fix some missing translation keys

### LINKED ISSUE #13397: front: wrong translation keys in infrastructure editor
### What happened?

Image

Also at some other places

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

open infra editor

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by Synar**
Close #13397

Based on #13491 by @Akctarus 

We drop the "port::" prefix of the port names (of the form "port::A1") as t expects :: to be a namespace indicator, not part of the key. Also we don't want to add these keys to the python schema, as it already has a generic ports property.

Also worth mentioning that while we can't edit Ops yet, we can hover them, which displays a broken translation string currently (as pointed out in the comments of the issue).

### CODE REVIEW

File: front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx [hunk 1]
```diff
@@ -110,7 +110,7 @@ const TrackSectionEndpointSelector = ({
 
   return (
     <div className="mb-4">
-      {schema.title && <h5>{schema.title}</h5>}
+      <h5>{t(`Editor.tools.switch-edition.ports.${name.slice(6)}`)}</h5>
```
Comment (emersion) [inline front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: I would prefer `.replace('port::', '')` instead of `.slice(6)` here. This makes it more obvious what the intent is, and avoids length mistakes.

Actually - we have `FLAT_SWITCH_PORTS_PREFIX` and `portId` already, maybe we can just use `portId` here?

Comment (emersion) [inline front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: I was wondering whether we could improve type safety here: i18n-checker would benefit from a more precise type for the translation key.

We could use TypeScript to strip a prefix from a union type, but that would require `name` to be a union type in the first place. However, as far as I understand, it's a generic/opaque string because it depends on the signalling system?

If that's the case, I don't see any way to improve type safety here, and we just need to deal with it.

File: front/scripts/i18n-checker.ts [hunk 2]
```diff
@@ -12,9 +12,6 @@ const IGNORE_MISSING: RegExp[] = [
   /stdcm-help-section:externalSupport/,
   /stdcm-help-section:sections/,
   /stdcm:stdcmErrors\..*/,
-  /translation:Editor.obj-types.NeutralSection/,
-  /translation:Editor.obj-types.SwitchType/,
-  /translation:Editor.obj-types.OperationalPoint/,
```
Comment (emersion) [inline front/scripts/i18n-checker.ts:17]: Nice, less exceptions!

**Review by emersion — APPROVED** [review]
Overall looks good to me, just one suggestion to simplify the code!

Feel free to resolve comments.

File: front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx (hunk 1 above)
Comment (Synar) [reply front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: It's not dependent on the signaling system, but on the types of switches we have. In practice we always use the same few switches, but osrd is in theory agnostic to the switch schema, we could use other ports.

However thinking about it more, this does imply our translations should be agnostic to the exact ports too. So instead of translating all the variants of "port A1", we should probably just translate "port {port_id}"!

Comment (Synar) [reply front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: Oh I missed the fact we already had portId in this component, good catch!

Comment (Synar) [reply front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: Done ^^

Comment (emersion) [reply front/src/applications/editor/tools/switchEdition/components/TrackSectionEndpointSelector.tsx]: Oh yeah, that makes a lot of sense, good find!

**Review by emersion — APPROVED** [review]
Sweet, thanks!
