### PR TITLE
front: fix rounding times for timetable items cards

### LINKED ISSUE #11337: Time rounding up is different beteween paced trains and train schedules
### What happened?

For a same start time for a paced train and train schedule, it is rounded to the minute under and to the closest minute respectively.
The two in the screenshot have a start time at 14:40:41.

Image

### What did you expect to happen?

I expect the start time to be rounded the same way: to the closest minute (seen with @maelysLeratRosso)

### How can we reproduce it (as minimally and precisely as possible)?

1. Upload [this timetable](https://github.com/user-attachments/files/19586997/timetable.2.json)
2. Witness the different rounding

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

b42f78b

### PR DESCRIPTION
**Pull request by louisgreiner**
Close https://github.com/OpenRailAssociation/osrd/issues/11337

Not sure if I should refactor more the code nearby, I did the minimal changes, I'm open for refactoring if needed

### CODE REVIEW

File: front/src/modules/trainschedule/components/Timetable/TrainScheduleItem.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ type TrainScheduleItemProps = {
 };
 
 const formatFullDate = (d: Date) => dayjs(d).format('D/MM/YYYY HH:mm:ss');
-const formatDateHours = (d: Date) =>
+export const formatDateHours = (d: Date) =>
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/Timetable/TrainScheduleItem.tsx]: We should move this function either in `Timetable/utils.ts` or in `utils/date.ts`

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, just one suggestion

**Review by Akctarus — APPROVED** [review]
LGTM !

**Review by Maymanaf — APPROVED** [review]
