### PR TITLE
front: fix electrical profiles in csv export

### LINKED ISSUE #9345: simulation result as csv export has wrong electrical profiles
### What happened?

The electrical profiles given in the csv do not match what's show in space-speed chart.

For [this train schedule](https://github.com/user-attachments/files/17377027/train_schedules.18.json).
The GEV shows 

Image

But the csv is 
```csv
op;ch;trackName;time;seconds;position;speed;speedLimit;lineCode;electrificationType;electrificationMode;electrificationProfile
;;;16:16:00;1727799360;0;0;300;;;;
point demandé (1);;V2;16:16:00;1727799360;0;0;300;424242;;;
;;V2;16:16:00;1727799360;0;0;300;424242;;;
;;V2;16:16:00;1727799360;0;0;300;424242;electrification;25000V;25000V
;;V2;16:16:00;1727799360,5;0;1,015;300;424242;neutral_section;;
;;V2;16:16:00;1727799360,5;0;1,051;300;424242;electrification;25000V;25000V
;;V2;16:16:02;1727799362;0,001;3,863;300;424242;electrification;25000V;25000V
;;V2;16:16:04;1727799364;0,004;7,724;300;424242;electrification;25000V;25000V
;;V2;16:16:05;1727799365,7;0,009;10,954;300;424242;neutral_section;;
;;V2;16:16:05;1727799365,7;0,009;11,026;300;424242;electrification;25000V;25000V
;;V2;16:16:06;1727799366;0,01;11,582;300;424242;electrification;25000V;25000V
;;V2;16:16:10;1727799370;0,027;19,287;300;424242;electrification;25000V;25000V
;;V2;16:16:12;1727799372;0,039;23,129;300;424242;electrification;25000V;25000V
;;V2;16:16:16;1727799376;0,069;30,777;300;424242;electrification;25000V;25000V
;;V2;16:16:22;1727799382;0,129;42,149;300;424242;electrification;25000V;25000V
;;V2;16:16:26;1727799386;0,18;49,641;300;424242;electrification;25000V;25000V
;;V2;16:16:32;1727799392;0,272;60,724;300;424242;electrification;25000V;25000V
;;V2;16:16:34;1727799394;0,306;61,872;300;424242;electrification;25000V;25000V
;;V2;16:16:42;1727799402;0,46;75,787;300;424242;electrification;25000V;25000V
;;V2;16:16:54;1727799414;0,741;93,108;300;424242;electrification;25000V;25000V
;;V2;16:17:06;1727799426;1,08;110,01;300;424242;electrification;25000V;25000V
;;V2;16:17:18;1727799438;1,475;126,588;300;424242;electrification;25000V;25000V
;;V2;16:17:30;1727799450;1,923;142,609;300;424242;electrification;25000V;25000V
;;V2;16:17:44;1727799464;2,513;160,48;300;424242;electrification;25000V;25000V
;;V2;16:17:58;1727799478;3,17;177,356;300;424242;electrification;25000V;25000V
;;V2;16:18:12;1727799492;3,891;193,175;300;424242;electrification;25000V;25000V
;;V2;16:18:32;1727799512;5,025;215,609;300;424242;electrification;25000V;25000V
;;V2;16:18:38;1727799518;5,39;222,023;300;424242;electrification;25000V;25000V
;;V2;16:18:50;1727799530;6,149;232,98;300;424242;electrification;25000V;25000V
;;V2;16:19:12;1727799552;7,629;250,776;300;424242;electrification;25000V;25000V
;;V2;16:19:28;1727799568;8,765;261,028;300;424242;electrification;25000V;25000V
;;V2;16:19:30;1727799570;8,91;260,969;300;424242;electrification;25000V;25000V
;;V2;16:19:46;1727799586;10,094;271,794;300;424242;electrification;25000V;25000V
Mid_West_station;BV;V1;16:19:55;1727799595,6;10,832;277,561;300;434343;electrification;25000V;25000V
;;V1;16:20:00;1727799600;11,168;280,187;300;434343;electrification;25000V;25000V
;;V1;16:20:20;1727799620;12,754;290,641;300;434343;electrification;25000V;25000V
;;V1;16:20:40;1727799640,7;14,451;299,999;300;434343;electrification;25000V;25000V
Mid_East_station;BV;V1;16:22:50;1727799770,6;25,282;299,999;300;434343;electrification;25000V;25000V
;;V1;16:24:19;1727799859,4;32,676;299,999;300;434343;electrification;25000V;25000V
;;V1;16:24:40;1727799880;34,291;262,8;300;434343;electrification;25000V;25000V
;;V1;16:25:00;1727799900;35,651;226,8;300;434343;electrification;25000V;25000V
;;V1;16:25:10;1727799910;36,256;208,8;300;434343;electrification;25000V;25000V
;;V1;16:25:20;1727799920;36,811;190,8;300;434343;electrification;25000V;25000V
;;V1;16:25:30;1727799930;37,316;172,8;300;434343;electrification;25000V;25000V
;;V1;16:25:42;1727799942;37,856;151,2;300;434343;electrification;25000V;25000V
;;V1;16:25:52;1727799952;38,251;133,2;300;434343;electrification;25000V;25000V
;;V1;16:26:02;1727799962;38,596;115,2;300;434343;electrification;25000V;25000V
;;V1;16:26:12;1727799972;38,891;97,2;300;434343;electrification;25000V;25000V
;;V1;16:26:18;1727799978;39,044;86,4;300;434343;electrification;25000V;25000V
;;V1;16:26:24;1727799984;39,179;75,6;300;434343;electrification;25000V;25000V
;;V1;16:26:34;1727799994;39,364;57,6;300;434343;electrification;25000V;25000V
;;V1;16:26:38;1727799998;39,424;50,4;300;434343;electrification;25000V;25000V
;;V1;16:26:44;1727800004;39,499;39,6;300;434343;electrification;25000V;25000V
;;V1;16:26:48;1727800008;39,539;32,4;300;434343;electrification;25000V;25000V
;;V1;16:26:54;1727800014;39,584;21,6;300;434343;electrification;25000V;25000V
;;V1;16:26:56;1727800016;39,595;18;300;434343;electrification;25000V;25000V
;;V1;16:27:00;1727800020;39,611;10,8;300;434343;electrification;25000V;25000V
;;V1;16:27:02;1727800022;39,616;7,2;300;434343;electrification;25000V;25000V
;;V1;16:27:04;1727800024;39,619;3,6;300;434343;electrification;25000V;25000V
;;V1;16:27:06;1727800026;39,62;0;300;434343;electrification;25000V;25000V
point demandé (2);;V2;16:27:06;1727800026;39,62;0;300;434343;electrification;25000V;25000V
```

### What did you expect to happen?

I expect the csv to contain the actual electrical profiles

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario on small infra, with the small infra electrical profiles
2. Import the aforementioned train schedule
3. Export the csv Image
4. Witness

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

3ac680e

### PR DESCRIPTION
**Pull request by Yohh**
in exportTrainCSV.ts electrical profiles are based on electrificationRanges, which are not the good ones

use simulatedTrain.electrical_profiles instead

close #9345

### CODE REVIEW

File: front/src/modules/simulationResult/SimulationResultExport/exportTrainCSV.ts [hunk 1]
```diff
@@ -126,10 +118,35 @@ const overloadSteps = (
...
+    if (value.electrical_profile_type === 'profile') {
+      return {
+        electrificationProfile: value.profile || '',
+        ...currentTrainRegime,
+      };
+    }
+    return {
+      electrificationProfile: '',
+      ...currentTrainRegime,
+    };
```
Comment (Math-R) [inline front/src/modules/simulationResult/SimulationResultExport/exportTrainCSV.ts:142]: you can minify this doing 
```
return {
      electrificationProfile:
        value.electrical_profile_type === 'profile' ? value.profile || '' : '',
      ...currentTrainRegime,
}
```

Comment (Math-R) [inline front/src/modules/simulationResult/SimulationResultExport/exportTrainCSV.ts]: To simplify you can minify like this 

```suggestion
   return {
      electrificationProfile:
        value.electrical_profile_type === 'profile' ? value.profile || '' : '',
      ...currentTrainRegime,
}
```

File: front/src/modules/simulationResult/SimulationResultExport/exportTrainCSV.ts [hunk 2]
```diff
@@ -126,10 +118,35 @@ const overloadSteps = (
     time: trainRegime.times[index],
   }));
 
+  const formattedElectricalProfiles = electricalProfiles.values.map((value, index) => {
+    const currentTrainRegime = {
+      speed: interpolateValue(
+        trainRegime,
+        mmToM(electricalProfiles.boundaries[index - 1]) || 0,
```
Comment (Math-R) [inline front/src/modules/simulationResult/SimulationResultExport/exportTrainCSV.ts]: Maybe you can put this in a const because it's used twice

**Review by Math-R — APPROVED** [review]
lgtm
