### PR TITLE
front: useLazyQuery for conflicts to avoid refetch errors

### LINKED ISSUE #12919: We encountered an error while quickly duplicating the train.
### What happened?

We encountered an error while quickly duplicating the train : 

Image

```
@reduxjs_toolkit_query_react.js?v=17c73ca1:348 Uncaught (in promise) Error: Cannot refetch a query that has not been started yet.
    at refetchOrErrorIfUnmounted (@reduxjs_toolkit_query_react.js?v=17c73ca1:348:36)
    at refetch (@reduxjs_toolkit_query_react.js?v=17c73ca1:359:24)
    at useScenarioData.ts:194:7
    at useScenarioData.ts:283:7
    at ScenarioContent.tsx:93:7
    at duplicatePacedTrain (PacedTrainItem.tsx:198:5)
refetchOrErrorIfUnmounted @ @reduxjs_toolkit_query_react.js?v=17c73ca1:348
refetch @ @reduxjs_toolkit_query_react.js?v=17c73ca1:359
(anonymous) @ useScenarioData.ts:194
(anonymous) @ useScenarioData.ts:283
(anonymous) @ ScenarioContent.tsx:93
duplicatePacedTrain @ PacedTrainItem.tsx:198
await in duplicatePacedTrain
executeDispatch @ react-dom_client.js?v=17c73ca1:11736
runWithFiberInDEV @ react-dom_client.js?v=17c73ca1:1485
processDispatchQueue @ react-dom_client.js?v=17c73ca1:11772
(anonymous) @ react-dom_client.js?v=17c73ca1:12182
batchedUpdates$1 @ react-dom_client.js?v=17c73ca1:2628
dispatchEventForPluginEventSystem @ react-dom_client.js?v=17c73ca1:11877
dispatchEvent @ react-dom_client.js?v=17c73ca1:14792
dispatchDiscreteEvent @ react-dom_client.js?v=17c73ca1:14773
```

### What did you expect to happen?

No errors during duplication

### How can we reproduce it (as minimally and precisely as possible)?

go to scenario
create train
duplicate it quickly
see error 

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by theocrsb**
closes #12919

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 1]
```diff
@@ -230,7 +224,7 @@ const useScenarioData = (scenario: ScenarioResponse, infra: InfraWithStatus) =>
 
       updateSimulatedTimetableItemDepartureTime(timetableItemId, newDeparture);
       updateProjectedTimetableItemDepartureTime(timetableItemId, newDeparture);
-      refetchConflicts();
+      safeFetchConflicts();
     },
     []
```
Comment (Caracol3) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Shouldn’t we add `safeFetchConflicts` to the const `setTimetableItemDepartureTime’s ` dependencies as well?

**Review by Caracol3 — COMMENTED** [review]
Nice job ! Just left one comment

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 1 above)
Comment (theocrsb) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done !

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 1 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Nice catch :)

**Review by Caracol3 — APPROVED** [review]
LGTM
