### PR TITLE
front: fix type for macro nodes full name

### LINKED ISSUE #10390: nge: nodes have no name
### What happened?

Image

Recognized OP have no name, but we still can set it manually:

Image

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. create train schedule from osrd

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### LINKED ISSUE #10433: nge: full name of OPs recognized in OSRD not displayed
### What happened?

Prevents feature https://github.com/osrd-project/osrd-confidential/issues/597 from being validated

If a node in NGE corresponds to an operational point recognized in the infrastructure, the full_name should be displayed in the name, but it is not : 

Image

### What did you expect to happen?

As a reminder, the ACs of the feature https://github.com/osrd-project/osrd-confidential/issues/597 were :  

- If a node in NGE has a name stored in the nodes table, then it is displayed
- Otherwise, if the node corresponds to a recognized OP in OSRD, then the full_name attribute of the OP is displayed in the name field in NGE (without it being stored in the table)
- Else, nothing is displayed in the name field
- If the user changes the name attribute in NGE, then it is stored in the table and displayed in NGE (even if the node corresponds to a recognized OP in OSRD for which we previously displayed the full_name by default)

Note : the first AC in the previous list seems ok.

### How can we reproduce it (as minimally and precisely as possible)?

Create a train in OSRD going through OPs, and go to NGE, double click on one of the nodes.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

c9066aa

### PR DESCRIPTION
**Pull request by louisgreiner**
Close https://github.com/OpenRailAssociation/osrd/issues/10433
Close https://github.com/OpenRailAssociation/osrd/issues/10390

### CODE REVIEW

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 1]
```diff
@@ -180,8 +180,8 @@ export const loadAndIndexNge = async (
   // Enhance nodes by calling the search API
   const searchResults = await executeSearch(state, dispatch);
   searchResults.forEach((searchResult) => {
-    const macroNode = {
-      fullName: searchResult.name,
+    const macroNode: Partial<NodeIndexed> = {
```
Comment (SharglutDev) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: nit: `Partial` gives all type keys an `undefined` possibility, even the one we used. It's not the case here but this would allow one of the 3 properties we use to accept an `undefined` value. If you think this can lead to a unwanted behavior in the future, you can replace `Partial` by `Pick<NodeIndexed, 'full_name' | 'trigram' | 'geocoord'>` (down side is you have to list all the keys you want)

Comment (louisgreiner) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: Thanks for the explanation, I don't know for now, but it surely could lead to unwanted behavior in the future -> fixed

**Review by emersion — APPROVED** [review]
Good catch!

**Review by Uriel-Sautron — APPROVED** [review]
Nice, thank you
