### PR TITLE
front: fix suggestions filters in itinerary modal

### LINKED ISSUE #15034: front: new itinerary modal OP search is not coherent with map OP search
### What happened?

when searching "bâle" in the OP search map I have these 2 results:
Image

when searching in the OP search in the new itinerary modal I have the following result:
- if the accent is missing, the OP is not found
Image

- with the accent, one of the OP is missing (Bâle St Jean)
Image

### What did you expect to happen?

searching for an OP on the map or on the new itinerary modal should behave identically

### How can we reproduce it (as minimally and precisely as possible)?

1. open the new itinerary modal
2. search the OP "bale" on the map, you should see two results : "bâle" and "bâle st jean"
3. search the OP "bale" on the new itinerary modal, there is no result
4. search the OP "bâle" on the new itinerary modal, one result (bâle st jean) is missing

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 42e8bca

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15034

### CODE REVIEW

File: front/src/applications/operationalStudies/helpers/stringUtils.ts [hunk 1]
```diff
@@ -4,10 +4,10 @@ export const splitTokens = (raw: string) =>
     .split(/[\s/-]+/)
     .filter(Boolean);
 
-export const norm = (s: string) => s.toLowerCase().trim().replace(/-/g, ' ').replace(/\s+/g, ' ');
-export const normalizePhrase = (value: string) =>
-  value
+export const norm = (string: string) =>
+  string
     .normalize('NFD')
+    .replace(/[\u0300-\u036f]/g, '')
```
Comment (DucNg) [inline front/src/applications/operationalStudies/helpers/stringUtils.ts]: What is this doing?

File: front/src/applications/operationalStudies/helpers/stringUtils.ts [hunk 2]
```diff
@@ -4,10 +4,10 @@ export const splitTokens = (raw: string) =>
     .split(/[\s/-]+/)
     .filter(Boolean);
 
-export const norm = (s: string) => s.toLowerCase().trim().replace(/-/g, ' ').replace(/\s+/g, ' ');
```
Comment (DucNg) [inline front/src/applications/operationalStudies/helpers/stringUtils.ts:7]: Why isn't this needed anymore?

File: front/src/applications/operationalStudies/helpers/stringUtils.ts (hunk 1 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/helpers/stringUtils.ts]: It is used to remove Diacritics (Bâle -> Bale)

I also realized we already have a ```normalized``` function in the code, that I know use in this function.

File: front/src/applications/operationalStudies/helpers/stringUtils.ts (hunk 2 above)
Comment (RomainValls) [reply front/src/applications/operationalStudies/helpers/stringUtils.ts:7]: Both are doing almost exactly the same thing, mixing them both to avoid redundancy. I dont think it has impacted the behavior of the ranking / filtering since the change

File: front/src/applications/operationalStudies/helpers/stringUtils.ts
Comment (DucNg) [inline front/src/applications/operationalStudies/helpers/stringUtils.ts:1]: Could this file be merged inside `utils/strings`?

**Review by DucNg — APPROVED** [review]
Nice, tested, it also works with the best cities

Image

File: front/src/applications/operationalStudies/helpers/stringUtils.ts
Comment (RomainValls) [reply front/src/applications/operationalStudies/helpers/stringUtils.ts:1]: Good point, will do !

Comment (RomainValls) [reply front/src/applications/operationalStudies/helpers/stringUtils.ts:1]: I also renamed ```norm``` to ```normalizePhrase``` to differenciate from the ```normalized``` function we already had

**Review by DucNg — APPROVED** [review]

File: front/src/utils/strings.ts [hunk 3]
```diff
@@ -83,6 +83,14 @@ export function normalized(s: string): string {
...
     .replace(/[\u0300-\u036f]/g, '');
 }
+export const splitTokens = (raw: string) =>
+  raw
+    .trim()
+    .split(/[\s/-]+/)
+    .filter(Boolean);
+
+export const normalizePhrase = (string: string) =>
+  normalized(string).split('-').join(' ').split(' ').filter(Boolean).join(' ').trim();
```
Comment (emersion) [inline front/src/utils/strings.ts]: Nit: this could be slightly simplified by using `splitTokens()`:

```ts
splitTokens(normalized(string)).join(' ');
```

File: front/src/utils/strings.ts [hunk 4]
```diff
@@ -83,6 +83,14 @@ export function normalized(s: string): string {
     .normalize('NFD')
     .replace(/[\u0300-\u036f]/g, '');
 }
+export const splitTokens = (raw: string) =>
+  raw
+    .trim()
+    .split(/[\s/-]+/)
+    .filter(Boolean);
+
+export const normalizePhrase = (string: string) =>
```
Comment (emersion) [inline front/src/utils/strings.ts]: Nit: "phrase" is a bit vague here, and usually users won't type in full sentences. Maybe "name" would be a bit better, to reflect the fact that it's meant to be used for OP or rolling stock names?

**Review by emersion — APPROVED** [review]
Two nits, but LGTM even if these aren't addressed!

**Comment by RomainValls** [comment]
> Two nits, but LGTM even if these aren't addressed!

Thanks ! I applied the suggested changes in the commit 👍
