### PR TITLE
front: fix train selection in the anterior or posterior train list

### LINKED ISSUE #10133: STDCM: Can't select train for linked path
### What happened?

Image

### What did you expect to happen?

The train is selected and the designited fields are filled 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM page
2. Search for a train in the "Anterior" or "Posterior" train list
Image
3. Click on the train from the search results

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6580cfe

### PR DESCRIPTION
**Pull request by theocrsb**
closes #10133

### CODE REVIEW

**Review by clarani — CHANGES_REQUESTED** [review]
Actually, the issue is not in this function, it's because we should not receive a string if we're expecting a date.

I let you search a bit, the problem comes from the action `updateLinkedTrainExtremity`, where we update the pathStep :wink:

File: front/src/applications/stdcm/utils/computeOpSchedules.ts [hunk 1]
```diff
@@ -29,12 +29,12 @@ const computeOpSchedules = (startTime: Date, msFromStartTime: number) => {
     origin: {
       date: originDate,
       time: originTime,
-      isoArrivalTime: subtractDurationFromDate(startTime, 1800).toISOString(),
+      isoArrivalTime: new Date(subtractDurationFromDate(startTime, 1800)),
```
Comment (clarani) [inline front/src/applications/stdcm/utils/computeOpSchedules.ts]: `subtractDurationFromDate` already returns a date, so you just need to remove the toISOString()
```suggestion
      isoArrivalTime: subtractDurationFromDate(startTime, 1800),
```

File: front/src/applications/stdcm/types.ts [hunk 2]
```diff
@@ -183,7 +183,7 @@ export type StdcmLinkedTrainExtremity = {
   ch: string;
   date: string;
   geographic: GeoJsonPoint;
-  isoArrivalTime: string;
+  isoArrivalTime: Date;
```
Comment (clarani) [inline front/src/applications/stdcm/types.ts]: Can you rename the field here ? Maybe arrivalDate ?

Comment (theocrsb) [reply front/src/applications/stdcm/types.ts]: Done

File: front/src/applications/stdcm/utils/computeOpSchedules.ts (hunk 1 above)
Comment (theocrsb) [reply front/src/applications/stdcm/utils/computeOpSchedules.ts]: Done

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Review by Akctarus — APPROVED** [review]
tested, LGTM :)
