### PR TITLE
front: fix TSv2 times and stop table input

### LINKED ISSUE #8019: TSV2 : inserted input are not displayed in the table
### What happened?

We create a train. We try to enter some input values (arrival time, stopping time or theoretical margin). These values are not displayed on the table altought they are used in the calculation. If we look at simulation results, the values are taken into account.
If we edit the train, the input table is still empty. Sometimes, we manage to get the values ​​by reloading the page or if we try to create another train.

### What did you expect to happen?

The values should be displayed 

### How can we reproduce it (as minimally and precisely as possible)?

Go to a scenario TSV2
Add a train
Go to times and stops table 
Put a margin value for example

### What operating system, browser and environment are you using?

- **Browser**: Edge
- **OS**: Windows
- **Env**: Recette

### OSRD version (top right corner `Account` button > `Informations`)

staging de8ada8

### PR DESCRIPTION
**Pull request by emersion**
_See individual commits._

Closes: https://github.com/OpenRailAssociation/osrd/issues/8019

### CODE REVIEW

File: front/src/modules/timesStops/utils.ts [hunk 1]
```diff
@@ -20,32 +21,25 @@ export const formatSuggestedViasToRowVias = (
       (op) => op.uic === origin.uic && op.ch === origin.ch && op.name === origin.name
     );
     // If the origin is in the ops and isn't the first operational point, we need to move it to the first position
-    if (originIndexInOps !== (-1 || 0)) {
+    if (originIndexInOps !== -1) {
```
Comment (SharglutDev) [inline front/src/modules/timesStops/utils.ts]: It seems like we should do the same test for destination.

On the screen below, I did a path between St Lazare and Dieppe by selecting both origin/via by map click, and the destination is not the last in the list as they both have the same `positionOnPath`

Capture d’écran 2024-07-12 à 09 00 06

File: front/src/modules/pathfinding/utils.ts [hunk 2]
```diff
@@ -34,6 +34,21 @@ export const formatSuggestedOperationalPoints = (
...
 
+export const matchPathStepAndOp = (step: PathStep, op: SuggestedOP) => {
+  if ('operational_point' in step) {
+    return step.operational_point === op.opId;
+  }
+  if ('uic' in step) {
+    return step.uic === op.uic && step.ch === op.ch;
+  }
+  if ('trigram' in step) {
+    return step.trigram === op.trigram && step.ch === op.ch;
```
Comment (SharglutDev) [inline front/src/modules/pathfinding/utils.ts]: I feel like we should check more thant that. Because of some imports issues, we can sometimes have multiple (2 most of the time) ops with same uic/ch. As it's done in other parts in the app, we could add a check for `kp` as well (between gaia and siph I think, the same op can be present 2 times with same uic/ch but two different `kp`) so we are sure we will edit the good one.

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for this nice fix and very well documented commits ! The fix works great, just left two comments.

**Review by flomonster — COMMENTED** [review]
Tested and it works

File: front/src/modules/pathfinding/utils.ts (hunk 2 above)
Comment (emersion) [reply front/src/modules/pathfinding/utils.ts]: That makes sense to me in general. Question: is there a downside to always check the `kp`? Looking at `isVia()`, it seems like we sometimes check `kp` and sometimes not - in which situation do we want to ignore `kp`?

Comment (emersion) [reply front/src/modules/pathfinding/utils.ts]: Also, should we match the `name`?

Comment (SharglutDev) [reply front/src/modules/pathfinding/utils.ts]: If I remember correctly (should have better documented this), in TimesStops we prefer to check the isVia with kp because some of ops in the list have same uic/ch/name so name is not relevant to compare them.
In SuggestedViaModal, we checked for the name because we decided that the "duplicated" op should add or removed together. But it seems that now it's not iso with TimeStops anymore and it shouldn't be like that.

File: front/src/modules/timesStops/utils.ts (hunk 1 above)
Comment (emersion) [reply front/src/modules/timesStops/utils.ts]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/8037

File: front/src/modules/pathfinding/utils.ts (hunk 2 above)
Comment (emersion) [reply front/src/modules/pathfinding/utils.ts]: Alright, added the `kp` matching!

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you for the fix !
