### PR TITLE
front: fix similar train location name in stdcm report

### LINKED ISSUE #13059: [LMR] OP of the similar trains to duplicate in the simulation sheet are displayed by Id and not by label
### What happened?

In a simulation sheet, we see the Ids of OPs for the similar trains to duplicate.

Image

### What did you expect to happen?

We should see the names of the OPs instead.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open LMR
2. Launch a simulation
3. Retain it
4. Download the simulation sheet

### On which environments the bug occurs?

Recette (SNCF), Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

a67f695

### PR DESCRIPTION
**Pull request by Math-R**
close #13059

### CODE REVIEW

File: front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts [hunk 1]
```diff
@@ -1,30 +1,31 @@
...
+import type { PathOperationalPoint } from 'modules/simulationResult/types';
 
 import type { SimilarTrainWithSecondaryCode } from '../types';
 
 export const addSecondaryCodesToSimilarTrains = (
   similarTrains: PostSimilarTrainsApiResponse['similar_trains'],
-  pathSteps: StdcmPathStep[]
+  pathOP?: PathOperationalPoint[]
 ): SimilarTrainWithSecondaryCode[] => {
   const nameToSecondaryCode = new Map<string, string>();
```
Comment (emersion) [inline front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts]: We have a map to convert OP IDs to secondary codes, and for OP names we iterate over the list with a `.find()`.

We could turn the map into a `Map<string, PathOperationalPoint>` to end up with a single way to find out information about an OP, and avoid the `.find()`.

Comment (Math-R) [reply front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts]: changed it ! thanks

File: front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts [hunk 2]
```diff
@@ -1,31 +1,30 @@
...
 ): SimilarTrainWithSecondaryCode[] => {
-  const nameToSecondaryCode = new Map<string, string>();
-
-  pathSteps.forEach((step) => {
-    const loc = step.location;
-    if (loc?.name && loc?.secondary_code) {
-      nameToSecondaryCode.set(loc.name, loc.secondary_code);
+  const opById = new Map<string, PathOperationalPoint>();
+  pathOP?.forEach((op) => {
+    if (op?.opId) {
```
Comment (emersion) [inline front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts]: `op` cannot be falsy here

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx [hunk 3]
```diff
@@ -138,7 +137,10 @@ const StdcmResults = ({
       const response = await postSimilarTrains({ body: request });
       const rawSimilarTrains = response.data?.similar_trains ?? [];
 
-      const enrichedSimilarTrains = addSecondaryCodesToSimilarTrains(rawSimilarTrains, pathSteps);
+      const enrichedSimilarTrains = addSecondaryCodesToSimilarTrains(
+        rawSimilarTrains,
+        (selectedSimulation.outputs as StdcmResultsOutput).pathProperties.manchetteOperationalPoints
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx:142]: Why do we need a cast here? Ah, we do something similar above :/

Would it help to use `outputs` instead of `selectedSimulation.outputs as StdcmResultsOutput`?

File: front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts (hunk 2 above)
Comment (Math-R) [reply front/src/applications/stdcm/utils/addSecondaryCodesToSimilarTrains.ts]: true

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx (hunk 3 above)
Comment (Math-R) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx:142]: Because of the change relative to conflicts. I'd prefer to handle this in another PR because it's more about changing some types

Comment (emersion) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx:142]: Alright, since there's another identical case above, let's fix this separately.

**Review by emersion — APPROVED** [review]
