### PR TITLE
editoast: fix cropped work schedule times

### LINKED ISSUE #9793: Work schedules start and end time seem cropped by the stdcm research window
### What happened?

Work schedules are announced between 1 and 5am here:
Image

While they actually span from 11pm to ~6am according to the official database.

I'm guessing what's happening here is that the timings are cropped by the stdcm research time window because the departure time is 2am +/- 1h, so the time window starts at 1am:
Image

Image
_sorry about the french text, didn't take time to change that_

### What did you expect to happen?

I'm expecting the entirety of the work schedule to be announced.

### How can we reproduce it (as minimally and precisely as possible)?

It's kinda hard to reproduce cause we need the official database to compare what's displayed and the reality. I suppose it's easier to test by creating work schedules manually.

### On which environments the bug occurs?

Other

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

v0.3.4 cd4cdfb

### PR DESCRIPTION
**Pull request by hamz2a**
Fixes https://github.com/OpenRailAssociation/osrd/issues/9793

### CODE REVIEW

File: editoast/src/views/timetable/stdcm/failure_handler.rs [hunk 1]
```diff
@@ -51,12 +51,13 @@ impl SimulationFailureHandler {
             latest_simulation_end,
             ..
         } = self;
+        let start_time = work_schedules
+            .first()
```
Comment (woshilapin) [inline editoast/src/views/timetable/stdcm/failure_handler.rs:55]: Does this work (taking the first), because you assume that the work schedules are ordered by `start_date_time`? The way I see it is that there is a functionality here that rely on something done in a completely different place of the code. So not so much locality for the behavior, which means we might break that anytime in the future if we decide to remove the `.order_by()` or change it for another field.

That said, I'm not sure that I have a proposition for this? At the very least, we could document the API `get_work_schedules()` which is expected to return a sorted list of work schedules? This way, any future modification would need to take that into account.

What do you think? Any idea?

**Review by woshilapin — APPROVED** [review]
I'm approving since I'm not sure there is an easy solution to the small remark I made. I won't block the merge if we can't find an easy solution (I believe comment would be an ok solution).

File: editoast/src/views/timetable/stdcm/failure_handler.rs (hunk 1 above)
Comment (hamz2a) [reply editoast/src/views/timetable/stdcm/failure_handler.rs:55]: I used the existing `order_by` API because I wanted to avoid redoing the sorting in Rust. But I agree, there’s a risk if the order changes in the future. Documenting the expected sorting behavior for `get_work_schedules()` sounds like a good idea to make this clear.

Comment (hamz2a) [reply editoast/src/views/timetable/stdcm/failure_handler.rs:55]: I’ve added a comment to document the expected sorting behavior for `get_work_schedules()`. Let me know what you think! @woshilapin

**Review by shenriotpro — APPROVED** [review]
LGTM for tests/
