### PR TITLE
front:sdm: align things in sillons menus

### LINKED ISSUE #4481: front: stdcm: some margins are wrong
image

- margin between infra loading & pathfinding is missing (should be `0.5rem`)
- margins of allowances labels are wrong (should be `0.25rem`)

### PR DESCRIPTION
**Pull request by tykayn**
fixes #4481
https://github.com/osrd-project/osrd/issues/4481

changes some margins and padding in elements of the lateral bar of the sillons reservation page
Screenshot 2023-12-07 at 16-19-56 OSRD

### CODE REVIEW

File: front/src/common/SpeedLimitByTagSelector/SpeedLimitByTagSelector.tsx [hunk 1]
```diff
@@ -86,7 +86,7 @@ export function IsolatedSpeedLimitByTagSelector({
           condensed ? 'd-flex align-items-center gap-10' : ''
         }`}
       >
-        <img width="32px" className="mr-2" src={icon} alt="infraIcon" />
+        <img width="32px" src={icon} alt="infraIcon" />
```
Comment (SharglutDev) [inline front/src/common/SpeedLimitByTagSelector/SpeedLimitByTagSelector.tsx]: Alt attribute is wrong here if you could change it, thanks.

Moreover, I'm curious about the hardcoded alt here regardless of the langage. I'm not sure a screen reader would translate this alt if the browser isn't in english. You should ask the UX about that.
```suggestion
        <img width="32px" src={icon} alt="speedometer" />
```

File: front/src/modules/stdcmAllowances/components/StdcmAllowances.tsx [hunk 2]
```diff
@@ -52,8 +52,8 @@ const StdcmAllowances = () => {
   };
 
   return (
-    <div className="d-flex mb-2 osrd-config-item-container">
-      <div className="col-3">
+    <div className="d-flex mb-2 osrd-config-item-container pl-0 pr-0">
```
Comment (SharglutDev) [inline front/src/modules/stdcmAllowances/components/StdcmAllowances.tsx]:
```suggestion
    <div className="d-flex mb-2 osrd-config-item-container px-0">
```

File: front/src/modules/stdcmAllowances/components/StdcmAllowances.tsx [hunk 3]
```diff
@@ -52,8 +52,8 @@ const StdcmAllowances = () => {
...
+      <div className="col-3 ">
```
Comment (SharglutDev) [inline front/src/modules/stdcmAllowances/components/StdcmAllowances.tsx]:
```suggestion
      <div className="col-3">
```

File: front/src/styles/scss/common/components/_typeAndPath.scss [hunk 4]
```diff
@@ -1,15 +1,14 @@
...
   background-color: var(--white);
   padding: 0.5rem;
   border-radius: var(--border-radius);
   .help {
     position: relative;
-    display: flex;
     align-items: center;
     justify-content: center;
     height: 5rem;
-    max-width: 21vw;
```
Comment (SharglutDev) [inline front/src/styles/scss/common/components/_typeAndPath.scss]: Like most of your changes in this PR, they weren't asked on the issue. This component is also used in the manage train schedule module in the itinerary tab so when you change the style here, it affects also this part of the app. 

I think before changing things like this, you should check with our ux, @thibautsailly, what he thinks about that

File: front/src/common/Pathfinding/TypeAndPath.tsx [hunk 5]
```diff
@@ -145,7 +145,7 @@ export default function TypeAndPath({ zoomToFeature }: PathfindingProps) {
 
   return (
     <div
-      className="type-and-path"
+      className="type-and-path w-100"
```
Comment (SharglutDev) [inline front/src/common/Pathfinding/TypeAndPath.tsx]: Does it change something ?

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for your PR. Left some comments.

Even though it wasn't ask in the issue (which seems already solved in both asked parts), I agree with your alignments changes, but you should double check with the UX, @thibautsailly, if all these changes are what he wants.

Also if you could rename your commit with `front: stdcm...` (you missed the 't' in stdcm)

File: front/src/common/Pathfinding/TypeAndPath.tsx (hunk 5 above)
Comment (tykayn) [reply front/src/common/Pathfinding/TypeAndPath.tsx]: ok it does not change anything, i removed it

File: front/src/styles/scss/common/components/_typeAndPath.scss (hunk 4 above)
Comment (SharglutDev) [reply front/src/styles/scss/common/components/_typeAndPath.scss]: I think you should leave the `display: flex` to benefit from the `align-items: center` which feels right.

The max-width needs also to stay otherwise the component grows too much in manage train schedule module. To have more space for the text, you could go to `max-width: 29vw` but I think @nicolaswurtz did it on purpose so you should leave it with 21vw.

The `justify-content: center` doesn't do anything so that's the only thing you can remove.

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/styles/scss/common/components/_typeAndPath.scss (hunk 4 above)
Comment (tykayn) [reply front/src/styles/scss/common/components/_typeAndPath.scss]: ok updated

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested. Just squash your commits into one please.
