### PR TITLE
core: do not try extending neutral sections if thermal

### LINKED ISSUE #4816: Crash on dead sections for rolling stocks without electrical_power_startup_time
### What happened?

```
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "this.electricalPowerStartUpTime" is null
	at fr.sncf.osrd.train.RollingStock.computeDeadSectionRange(RollingStock.java:251)
	at fr.sncf.osrd.train.RollingStock.addNeutralSystemTimes(RollingStock.java:276)
```

When there is a dead section along the train's path, and the train has no defined electrical power startup time, a null dereference and crash occurs.

### What did you expect to happen?

There should be a default `electrical_power_startup_time`.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a rolling stock without `electrical_power_startup_time`, or with the field set to null
2. run a simulation on a path with a dead section (there are multiple ones on `small_infra`)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

834d2877

### PR DESCRIPTION
**Pull request by Castavo**
close: #4816 

This PR adds a test for a thermal train on an infrastructure with neutral sections.
It also fixes the `addNeutralSystemTimes` method

It also adds a django migration that fills in some empty rolling stock attributes if any in the db

### CODE REVIEW

**Review by multun — APPROVED** [review]

File: core/src/test/java/fr/sncf/osrd/api/StandaloneSimulationTest.java [hunk 1]
```diff
@@ -715,4 +715,40 @@ public void testElectrificationRangesThermal() throws IOException {
...
+                "small_infra/infra.json",
+                "1",
+                2,
+                getExampleRollingStocks(),
+                trainSchedules,
+                rjsTrainPath
+        );
+
+        // parse back the simulation result
+
```
Comment (clarani) [inline core/src/test/java/fr/sncf/osrd/api/StandaloneSimulationTest.java]:
```suggestion
```

**Review by clarani — APPROVED** [review]
LGTM :)
Only a typo

**Review by multun — APPROVED** [review]

**Review by leovalais — APPROVED** [review]
