### PR TITLE
editoast: fix `PathItemCache` Indexing

### LINKED ISSUE #13760: path_item_cache
https://github.com/OpenRailAssociation/osrd/pull/13671#discussion_r2444447856

### PR DESCRIPTION
**Pull request by hamz2a**
closes https://github.com/OpenRailAssociation/osrd/issues/13760

Make `PathItemCache` index operational points by `ID`, `UIC`, and `trigram`.
This makes queries consistent, and keeps the cache self-contained.
Added tests to check indexing.

### CODE REVIEW

File: editoast/src/views/path/path_item_cache.rs [hunk 1]
```diff
@@ -42,33 +48,75 @@ impl PathItemCache {
...
+                ids_to_ops.entry(op.obj_id.clone()).or_insert(op);
+            }
+        }
+
+        // Collect from uic_results
+        for ops_vec in uic_results.into_values() {
+            for op in ops_vec {
+                ids_to_ops.entry(op.obj_id.clone()).or_insert(op);
+            }
+        }
```
Comment (woshilapin) [inline editoast/src/views/path/path_item_cache.rs]: Can be written in a more concise way, without mutability of `ids_to_ops` if I'm not mistaken.


```suggestion
        let ids_to_ops: HashMap<String, OperationalPointModel> = ids_results
            .into_values()
            .chain(trigram_results.into_values().flatten())
            .chain(uic_results.into_values().flatten())
            .map(|op| (op.obj_id.clone(), op))
            .collect();
```

File: editoast/src/views/path/path_item_cache.rs [hunk 2]
```diff
@@ -408,3 +461,136 @@ fn secondary_code_filter(
...
+            "OP1 should be findable by UIC even though queried by ID"
+        );
+
+        // Verify it's the same OP
+        let op_by_id = cache.get_from_id("op_1").unwrap();
+        let op_by_trigram = cache.get_from_trigram("ABC").unwrap().first().unwrap();
+        let op_by_uic = cache.get_from_uic(1234).unwrap().first().unwrap();
+        assert_eq!(op_by_id.obj_id, "op_1");
+        assert_eq!(op_by_trigram.obj_id, "op_1");
+        assert_eq!(op_by_uic.obj_id, "op_1");
```
Comment (woshilapin) [inline editoast/src/views/path/path_item_cache.rs]: I believe you can inline and avoid interleaving lines.

```suggestion
        assert!(cache.get_from_id("op_1").unwrap().obj_id, "op_1");
        assert!(cache.get_from_trigram("ABC").unwrap().first().unwrap().obj_id, "op_1");
        assert!(cache.get_from_uic(1234).unwrap().first().unwrap().obj_id, "op_1");
```

File: editoast/src/views/path/path_item_cache.rs [hunk 3]
```diff
@@ -408,3 +461,136 @@ fn secondary_code_filter(
...
+            cache.get_from_id("op_2").is_some(),
+            "OP2 should be findable by ID even though queried by trigram"
+        );
+        assert!(
+            cache.get_from_trigram("DEF").is_some(),
+            "OP2 should be findable by trigram"
+        );
+        let op2_by_id = cache.get_from_id("op_2").unwrap();
+        let op2_by_trigram = cache.get_from_trigram("DEF").unwrap().first().unwrap();
+        assert_eq!(op2_by_id.obj_id, op2_by_trigram.obj_id);
```
Comment (woshilapin) [inline editoast/src/views/path/path_item_cache.rs]: I find the following more explicit on what we are suppose to test: we do not test equality, we test the output value (equality is only a side effect).

```suggestion
        assert_eq!(cache.get_from_id("op_2").unwrap().obj_id, "op_2");
        assert_eq!(cache.get_from_trigram("DEF").unwrap().first().unwrap().obj_id, "op_2");
```

File: editoast/src/views/path/path_item_cache.rs [hunk 4]
```diff
@@ -408,3 +461,136 @@ fn secondary_code_filter(
...
+            cache.get_from_id("op_3").is_some(),
+            "OP3 should be findable by ID even though queried by UIC"
+        );
+        assert!(
+            cache.get_from_uic(5678).is_some(),
+            "OP3 should be findable by UIC"
+        );
+        let op3_by_id = cache.get_from_id("op_3").unwrap();
+        let op3_by_uic = cache.get_from_uic(5678).unwrap().first().unwrap();
+        assert_eq!(op3_by_id.obj_id, op3_by_uic.obj_id);
```
Comment (woshilapin) [inline editoast/src/views/path/path_item_cache.rs]: I find the following more explicit on what we are suppose to test: we do not test equality, we test the output value (equality is only a side effect).

```suggestion
        assert_eq!(cache.get_from_id("op_3").unwrap().obj_id, "op_3");
        assert_eq!(cache.get_from_uic(5678).unwrap().first().unwrap().obj_id, "op_3");
```

**Review by woshilapin — APPROVED** [review]
Seems like an improvement. Only some minor proposition of improvement.

**Review by leovalais — CHANGES_REQUESTED** [review]
Thanks for fixing the weird PathItemCache behavior. A couple comments:

* All OperationalPointModels are now cloned three times. This is unnecessary and adds memory pressure on editoast in parts of the code that sometimes OOM. They could be stored only once in a Vec and have the maps point to indexes instead.
* I don't believe it's worth storing existing_track_ids since it's just the keys of track_ids_to_name. The set can be computed lazily if its construction time isn't an issue where it's used.

File: editoast/src/views/path/path_item_cache.rs (hunk 2 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [8b1448d6](https://github.com/OpenRailAssociation/osrd/compare/8b1448d64c27731e6b0137d1a158bad48118a931..d26c8fa7b335a3d97781ee3edb1beb73fbe52666)

File: editoast/src/views/path/path_item_cache.rs (hunk 3 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [8b1448d6](https://github.com/OpenRailAssociation/osrd/compare/8b1448d64c27731e6b0137d1a158bad48118a931..d26c8fa7b335a3d97781ee3edb1beb73fbe52666)

File: editoast/src/views/path/path_item_cache.rs (hunk 4 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [8b1448d6](https://github.com/OpenRailAssociation/osrd/compare/8b1448d64c27731e6b0137d1a158bad48118a931..d26c8fa7b335a3d97781ee3edb1beb73fbe52666)

File: editoast/src/views/path/path_item_cache.rs (hunk 1 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [d26c8fa7](https://github.com/OpenRailAssociation/osrd/compare/d26c8fa7b335a3d97781ee3edb1beb73fbe52666..1a0deae628bbcad5b1e5bde5f830a899d76321d0)

File: editoast/src/views/path/path_item_cache.rs [hunk 5]
```diff
@@ -23,15 +22,25 @@ type TrackOffsetResult = std::result::Result<Vec<Vec<TrackOffset>>, PathfindingR
...
-    ids_to_ops: HashMap<String, OperationalPointModel>,
-    existing_track_ids: HashSet<String>,
+    /// All operational points are stored here exactly once
+    ops: Vec<OperationalPointModel>,
+    /// Maps UIC code to indices in the ops Vec
+    uic_to_indices: HashMap<u32, Vec<usize>>,
+    /// Maps trigram to indices in the ops Vec
+    trigram_to_indices: HashMap<String, Vec<usize>>,
+    /// Maps obj_id to index in the ops Vec
+    id_to_index: HashMap<String, usize>,
```
Comment (leovalais) [inline editoast/src/views/path/path_item_cache.rs]:
```suggestion
    obj_id_to_index: HashMap<String, usize>,
```

File: editoast/src/views/path/path_item_cache.rs [hunk 6]
```diff
@@ -42,31 +51,68 @@ impl PathItemCache {
...
         }
 
+        // Step 1: Retrieve operational points from database using the requested identifiers
         let (trigrams, ops_uic, ops_id) = collect_path_item_ids(path_items);
-        let uic_to_ops = retrieve_op_from_uic(conn, infra_id, &ops_uic).await?;
-        let trigram_to_ops = retrieve_op_from_trigrams(conn, infra_id, &trigrams).await?;
-        let ids_to_ops = retrieve_op_from_ids(conn, infra_id, &ops_id).await?;
+        let uic_results = retrieve_op_from_uic(conn, infra_id, &ops_uic).await?;
+        let trigram_results = retrieve_op_from_trigrams(conn, infra_id, &trigrams).await?;
+        let ids_results = retrieve_op_from_ids(conn, infra_id, &ops_id).await?;
```
Comment (leovalais) [inline editoast/src/views/path/path_item_cache.rs]: * could be `try_join!`-ed
* no need for these functions to return a map anymore

File: editoast/src/views/path/path_item_cache.rs [hunk 7]
```diff
@@ -42,31 +51,68 @@ impl PathItemCache {
...
+
+        // Step 2: Collect all unique OPs first, deduplicating by obj_id
+        let id_to_op: HashMap<String, OperationalPointModel> = ids_results
```
Comment (leovalais) [inline editoast/src/views/path/path_item_cache.rs]:
```suggestion
        let ops: Vec<OperationalPointModel> = ids_results
```

suggestion: build the OPs vector directly here so you can derive all indexes from it, including `id_to_op`

This way in your loop you can just `for (index, op) in ops.iter().enumerate()`

File: editoast/src/views/path/path_item_cache.rs [hunk 8]
```diff
@@ -79,38 +125,42 @@ impl PathItemCache {
...
     /// Get the operational points associated with an identifier
     pub fn get_from_id(&self, id: &str) -> Option<&OperationalPointModel> {
-        self.ids_to_ops.get(id)
+        self.id_to_index.get(id).map(|&idx| &self.ops[idx])
     }
 
     /// Get the operational points associated with a trigram
-    pub fn get_from_trigram(&self, trigram: &str) -> Option<&Vec<OperationalPointModel>> {
-        self.trigram_to_ops.get(trigram)
+    pub fn get_from_trigram(&self, trigram: &str) -> Option<Vec<&OperationalPointModel>> {
```
Comment (leovalais) [inline editoast/src/views/path/path_item_cache.rs]: wouldn't it be easier to just return the iterator and let the caller decide what to do?


```suggestion
    pub fn get_from_trigram(&self, trigram: &str) -> Option<impl Iterator<Item = &OperationalPointModel>> {
```

File: editoast/src/views/path/path_item_cache.rs [hunk 9]
```diff
@@ -142,16 +190,16 @@ impl PathItemCache {
...
                 secondary_code,
-            } => (self.uic_to_ops.get(uic)?, secondary_code),
+            } => (self.get_from_uic(*uic)?, secondary_code),
         };
-        secondary_code_filter(secondary_code, ops.clone())
+        secondary_code_filter(secondary_code, ops)
             .into_iter()
             .next()
-            .map(|op| op.obj_id)
+            .map(|op| op.obj_id.clone())
```
Comment (leovalais) [inline editoast/src/views/path/path_item_cache.rs:213]:
```suggestion
            .map(|op| op.obj_id)
```

**Review by leovalais — COMMENTED** [review]
Thanks a lot for commenting out the code and adding tests ❤️

File: editoast/src/views/path/path_item_cache.rs (hunk 6 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [ae1017364](https://github.com/OpenRailAssociation/osrd/compare/ae1017364c7e150bfd3de861a4be285227d42395..9342d451d5db7a51f31219e7dde37ebcbbfd0639)

File: editoast/src/views/path/path_item_cache.rs (hunk 5 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [ae1017364](https://github.com/OpenRailAssociation/osrd/compare/ae1017364c7e150bfd3de861a4be285227d42395..9342d451d5db7a51f31219e7dde37ebcbbfd0639)

File: editoast/src/views/path/path_item_cache.rs (hunk 7 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [ae1017364](https://github.com/OpenRailAssociation/osrd/compare/ae1017364c7e150bfd3de861a4be285227d42395..9342d451d5db7a51f31219e7dde37ebcbbfd0639)

File: editoast/src/views/path/path_item_cache.rs (hunk 8 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs]: Done in [ae1017364](https://github.com/OpenRailAssociation/osrd/compare/ae1017364c7e150bfd3de861a4be285227d42395..9342d451d5db7a51f31219e7dde37ebcbbfd0639)

File: editoast/src/views/path/path_item_cache.rs (hunk 9 above)
Comment (hamz2a) [reply editoast/src/views/path/path_item_cache.rs:213]: We need the clone, otherwise, I get an error.

**Review by leovalais — APPROVED** [review]
