### PR TITLE
front: add lazy loading for scenario data

### LINKED ISSUE #7661: Train schedule summary is loaded before the infra
### What happened?

When the infra is not load and the user open a scenario, the train schedule summary request fails (since the infra is not loaded)

> [!NOTE]
> This bug will be fixed when core scalability is implemented.

### What did you expect to happen?

The request should be sent only when the infra is loaded.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with trains
2. Edit the infra of the scenario
3. Go back to the scenario (observe the train list won't load)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

b9c43e47b842aab1d0944945efcd74ab14ed380b

### LINKED ISSUE #8010: Moving a train in space-time chart trigger simulation summary and projection unnecessarily
### What happened?

When a scenario is already open, if the user moves a train in the space-time chart the front re-calls the `simulation_summary` and `project_path` endpoint.

### What did you expect to happen?

The endpoints shouldn't be recalled

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario with multiple trains
2. Open the browser debugger (network tab)
3. Move a train schedule in the space-time chart

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

bea61b1f5cdd3b93bf09c2075329ac0acad89e01

### LINKED ISSUE #8055: Load timetable gradually
### Who would benefit from this feature?

End users

### What is this feature about?

The goal is to avoid loading 2000 train schedule and wait for minutes to render simulation result.
We can load trains gradually and have a resulted page directly.

### Why is this feature valuable?

- Load huge timetable 2000 trains or more

### Refinement
- Modify train list
  - Show all cards only with available information (rollingStock, name, number of steps, departure time) 
    - Loader on left of the card if train not loaded (use info color of the design system )
    - No ghost for now (we'll do it in the next version)
    - disable card action buttons until loaded
  - Loader at top of train list with count of loaded trains and total
  - Block filters during loading
  - Allow user to change the selected train
  - Display warnings about conflicts and invalid trains as soon as information is available
  - Load trains in chronological order of departure
  - Update trains as soon as batch of trains is returned (10 trains)

- GET modification
  - Load trains bit by bit in GET
  - Display a warning message indicating that the GET is not complete in a small frame in the top right-hand corner.

- Optimize the api calls according to the mermaid schema below to reduce the loading time

- Behaviour modifications:
  - when deleting a train, we need to remove it from the data to display on the GET
  - if the train used for the projection is updated, then we need to get its summary and re-project all the trains
  - if the train used for the projection is deleted, then we need to remove it from the data to display on the GET and re-project all the trains
  - when adding a train, we need to get its summary and project it

Other remarks
- No need for a warning box at the bottom to indicate that the timetable is loading
- Display conflicts at the very end (no warning message)
- In the end, no time step is used to display trains

### Workflow

```mermaid
flowchart TB
    InfraLoaded[Check for infra to be loaded]
    RetrieveTimetable[Retrieve Timetable]
    RetrieveTrains[Retrieve TS2 payloads]
    SummarySimulation[[Summary simulation batch N:N+10]]
    TrainProjectionPath[Get selected train projection path]
    Projection[[Projection batch N-10:N]]
    TrainSimulation[Get selected train simulation]
    TrainPath[Get selected train path]
    TrainPathProperties[Get selected train path properties]
    DisplayGev(Display: GEV / Map /\n Driver Schedule/ Linear / Output Table)
    DisplayGet(Display Space Time Chart)
    DisplayTrainList(Display train list)
    Conflicts(Compute and display conflicts)
    InfraLoaded -->|Wait| SummarySimulation
    InfraLoaded -->|Wait| TrainProjectionPath
    InfraLoaded -->|Wait| TrainPath
    TrainPath -->|If found| TrainSimulation
    TrainPath -->|If found| TrainPathProperties
    RetrieveTimetable -->|Get train ids| RetrieveTrains
    RetrieveTrains ==>|Sort trains and chunk it| SummarySimulation
    SummarySimulation ==>|Wait for the previous batch| Projection
    SummarySimulation -->|Gradually fill cards| DisplayTrainList
    TrainPathProperties -->| | DisplayGev
    TrainSimulation -->|If valid simulation| DisplayGev
    TrainProjectionPath -->|Wait for the previous batch| Projection
    SummarySimulation -..->|If no projection train id| TrainProjectionPath
    Projection ==>|Gradually fill| DisplayGet
    SummarySimulation -->|Once everything is simulated| Conflicts
```

### LINKED ISSUE #8202: A new, empty scenario shows the simulation results of an existing scenario
### What happened?

The simulation results are displayed for a new scenario 
image

### What did you expect to happen?

No simulation results should be displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Open an existing Scenario
2. Modify the existing scenario like the rolling stock , route or Times and Stops 
3. Create a new scenario and observe 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

7faec4a

### PR DESCRIPTION
**Pull request by clarani**
closes #8055

Closes the following bugs:
- closes #8010 
- closes #8202
- closes #7661

In this PR, I add new hooks to gradually fetch the data, but I don't change the UI for the moment (I will do it in another PR).

The behaviour should be the same as the existing one:
- the user can see the results if the timetable has some trains
  - [ ] the simulation results of the selected train are displayed (GEV, driver schedule, map, output table)
  - [ ] by default, the train used for the projection and the selected train are the first one of the timetable (ordered by start time)
  - [ ] the GET is displayed and gradually filled
  - [ ] the user can change the train projected and it refetch the GET (which is gradually re-filled)
- in the timetable component:
  - [ ] the trains are ordered by their departure time
  - [ ] the trains are gradually displayed
  - [ ] the invalid trains are still displayed
  - [ ] the trains can be filtered
- if the user delete trains:
  - [ ] if the user deletes the selected train, the first train of the list is selected
  - [ ] if the user deletes the train used for the projection, the first train is used for the projection
  - [ ] if the user deletes the last train of the timetable, the results component disappear
- [ ] if the user creates or updates a train, the new train is displayed in the timetable component, in the GET and is selected by default (but not used for the projection)
- [ ] the user can see no result if the scenario has no train

### CODE REVIEW

**Review by flomonster — DISMISSED** [review]
I tested with:

- 800 trains from a json file
- 12 train from open data

In both cases, I have the following issues:

- ~~When opening the scenario I have an error "An unexpected error occurred"~~
- ~~I see the number of trains loading progressively but we expect to see "N/800 trains" instead of "N trains"~~
- When the projection is loading progressively, the user cannot move in the space-time graph.

> [!NOTE]
> For 800 trains the application is still slow.

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+    trainIdsToProject,
+    path,
+    trainSchedules,
+    moreTrainsToCome: !allTrainsLoaded,
+    setTrainIdsToProject,
+  });
+
+  // gradually fetch the simulation of the trains
+  useEffect(() => {
+    const getTrainScheduleSummaries = async (_infraId: number, _trainToFetchIds: number[]) => {
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:71]: this should be defined outside of the useEffect

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+import useLazyProjectTrains from 'modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains';
+import type { TrainScheduleWithDetails } from 'modules/trainschedule/components/TimetableV2/types';
+import type { Dictionary } from 'utils/types';
+
+import formatTrainScheduleSummaries from '../helpers/formatTrainScheduleSummaries';
+
+const getTrainIdsPackage = (tenIndex: number, trainIds: number[]) => {
+  const upperIndex = (tenIndex + 1) * 10 < trainIds.length ? (tenIndex + 1) * 10 : undefined;
+  return trainIds.slice(tenIndex * 10, upperIndex);
+};
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]:
```suggestion
const BATCH_SIZE = 10;

const getTrainIdsPackage = (tenIndex: number, trainIds: number[]) => {
  const upperIndex = Math.min(tenIndex + BATCH_SIZE, trainIds.length);
  return trainIds.slice(tenIndex, upperIndex);
};
```

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+            duration: 0,
+            pathLength: '',
+            mechanicalEnergyConsumed: 0,
+            invalidReason: trainSummary.status,
+          };
+
+    return {
+      id: trainSchedule.id,
+      trainName: trainSchedule.train_name,
+      startTime: dayjs(trainSchedule.start_time).format('D/MM/YYYY HH:mm:ss'), // format to time
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts:63]: this should be in utils/timeManipulation

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts [hunk 4]
```diff
@@ -0,0 +1,34 @@
+import type { Dispatch, SetStateAction } from 'react';
+
+const selectTrainAndPathForProjection = (
+  trainIds: number[],
+  setSelectedTrainId: Dispatch<SetStateAction<number | undefined>>,
+  setTrainIdUsedForProjection: Dispatch<SetStateAction<number | undefined>>,
+  currentProjection?: number,
+  selectedTrainId?: number
+) => {
+  if (trainIds.length === 0) return;
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: We should stop using one line if statements. We don’t gain anything by saving some space/characters,
it’s easy to miss the return at the end of the line if we skim too quickly.
brackets makes it really obvious to the eyes.

cheap and easy way to simplify reading the code so we should just use brackets.

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+      return;
+    }
+
+    const matchingTrain = trainSchedulesById[trainId];
+    const projectedTrain = {
+      ...currentProjectedTrain,
+      id: +trainId,
+      trainName: matchingTrain?.train_name || 'Train name not found',
+      departure_time:
+        `${convertIsoUtcToLocalTime(currentProjectedTrain.departure_time).slice(0, -6)}Z` || '',
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: make it a named time manipulation function in utils

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+  projectedTrainsToUpsert: Dictionary<ProjectPathTrainResult>,
+  trainSchedulesById: Dictionary<TrainScheduleResult>
+) => {
+  const newProjectedTrains = { ...projectedTrains };
+
+  // For each key (train id) in projectPathTrainResult, we either add it or update it in the state
+  Object.keys(projectedTrainsToUpsert).forEach((trainId) => {
+    const currentProjectedTrain = projectedTrainsToUpsert[trainId];
+    if (!currentProjectedTrain) {
+      console.error(`Train ${trainId} not found in the projectedTrainsToUpsert`);
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: who is going to read this console.error ? why not an error the user can see

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+
+  // gradually fetch the simulation of the trains
+  useEffect(() => {
+    const getTrainScheduleSummaries = async (_infraId: number, _trainToFetchIds: number[]) => {
+      let formattedSummaries: Dictionary<TrainScheduleWithDetails> = {
+        ...trainScheduleSummariesById,
+      };
+      setAllTrainsLoaded(false);
+
+      for (let i = 0; i * 10 <= _trainToFetchIds.length - 1; i += 1) {
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]:
```suggestion
      for (let i = 0; i <= _trainToFetchIds.length - 1; i += BATCH_SIZE) {
```

File: front/src/modules/trainschedule/components/TimetableV2/utils.ts [hunk 8]
```diff
@@ -1,14 +1,10 @@
...
- */
-export const keepTrain = (train: TrainScheduleBase, searchString: string): boolean => {
+/** Filter train schedules by their names and labels */
+export const keepTrain = (train: TrainScheduleWithDetails, searchString: string): boolean => {
   if (searchString) {
-    const searchStringInName = train.train_name.toLowerCase().includes(searchString.toLowerCase());
+    const searchStringInName = train.trainName.toLowerCase().includes(searchString.toLowerCase());
     const searchStringInTags = train.labels
       ? train.labels.join('').toLowerCase().includes(searchString.toLowerCase())
       : false;
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/TimetableV2/utils.ts:10]: a bit outside the scope of the PR, but that’s a lot of toLowerCase().includes()
you can make it an utils
```
function stringIncludes(a: string, b: string) {
  return a.toLowerCase().includes(b.toLowerCase())
}

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts [hunk 9]
```diff
@@ -0,0 +1,111 @@
+import { useEffect, useState } from 'react';
+
+import { uniq } from 'lodash';
+
+import type { TrainScheduleWithDetails } from './types';
+import { extractTagCode, keepTrain } from './utils';
+
+/**
+ * Hook filtering a sorted train schedules array for timetable train cards
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: does the algo required the array to be sorted ?

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+  debouncedFilter: string,
+  debouncedRollingstockFilter: string,
+  validityFilter: string,
+  scheduledPointsHonoredFilter: string,
+  selectedTags: Set<string | null>,
+  setDisplayedTrainSchedules: (trainSchedulesDetails: TrainScheduleWithDetails[]) => void
+) => {
+  const [uniqueTags, setUniqueTags] = useState<string[]>([]);
+
+  const filterTrainSchedules = (trainSchedules: TrainScheduleWithDetails[]) =>
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts:33]: That’s a lot of logic, move this function outside the hook and write some unit tests

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+import type { TrainSpaceTimeData } from 'applications/operationalStudies/types';
+import {
+  osrdEditoastApi,
+  type PathfindingResultSuccess,
+  type TrainScheduleResult,
+} from 'common/api/osrdEditoastApi';
+import { useOsrdConfSelectors } from 'common/osrdContext';
+import type { Dictionary } from 'utils/types';
+
+const getTrainIdsPackage = (tenIndex: number, trainIds: number[]) => {
```
Comment (anisometropie) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: see comments in useLazyLoadTrains

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 2 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: If it’s the exacty same function as in useLazyProjectrains, this can become an utils function utils/arrays.

File: front/src/applications/operationalStudies/hooks/useScenario.ts [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+    projectId: urlProjectId,
+    studyId: urlStudyId,
+    scenarioId: urlScenarioId,
+  } = useParams() as SimulationParams;
+
+  const { projectId, studyId, scenarioId } = useMemo(
+    () => ({
+      projectId: !Number.isNaN(+urlProjectId) ? +urlProjectId : undefined,
+      studyId: !Number.isNaN(+urlStudyId) ? +urlStudyId : undefined,
+      scenarioId: !Number.isNaN(+urlScenarioId) ? +urlScenarioId : undefined,
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useScenario.ts]: utils/string function:
```
function parseId(id) {
    const num = Number(id);
    return !Number.isNaN(num) ? num : undefined;
}
```

also, I think the `Number` function should be preferred over the unary `+` operator.
Number is more explicit, and it’s more consistent with the use of `String()` `Boolean()`

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 13]
```diff
@@ -0,0 +1,155 @@
...
+
+        setProjectedTrainsById((prevTrains) => {
+          const newProjectedTrains = upsertNewProjectedTrains(
+            prevTrains,
+            rawProjectedTrains,
+            trainSchedulesById
+          );
+          return newProjectedTrains;
+        });
+        // console.log('2. package', packageToProject);
```
Comment (anisometropie) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]:
```suggestion
```

File: front/public/locales/fr/operationalStudies/scenario.json [hunk 14]
```diff
@@ -67,9 +68,9 @@
     "validityFilter": "Validité des trains"
   },
   "toggleTimetable": "Basculer l'affichage de la grille horaires",
-  "trainCount_one": "1 train",
-  "trainCount_other": "{{count}} trains",
-  "trainCount_zero": "Aucun train",
+  "trainCount_one": "1/{{ totalCount }} train",
+  "trainCount_other": "{{ count }}/{{ totalCount }} trains",
```
Comment (anisometropie) [inline front/public/locales/fr/operationalStudies/scenario.json:72]: not sure about this one.

I think the plural comes from the total number of train, not what is currently selected. we should display:
1 / 100 trains
10 / 100 trains

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 15]
```diff
@@ -0,0 +1,207 @@
...
+      if (Object.values(trainScheduleSummariesById).length !== trainScheduleSummaries.length)
+        setTrainScheduleSummariesById(trainScheduleSummariesById);
+
+      if (Object.keys(projectedTrainsById).length !== projectedTrains.length)
+        setProjectedTrainsById(projectedTrainsById);
+
+      setTrainIdsToRemove([]);
+    };
+
+    if (trainIdsToRemove.length > 0) removeTrains(trainIdsToRemove);
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: why not just an if statement with the body of the function  ?  why declare a function to call it once

File: front/public/locales/en/operationalStudies/scenario.json [hunk 16]
```diff
@@ -68,9 +69,9 @@
     "validityFilter": "Trains validity"
   },
   "toggleTimetable": "Toggle the timetable",
-  "trainCount_one": "1 train",
-  "trainCount_other": "{{ count }} trains",
-  "trainCount_zero": "No train",
+  "trainCount_one": "1/{{ totalCount }} train",
+  "trainCount_other": "{{ count }}/{{ totalCount }} trains",
```
Comment (anisometropie) [inline front/public/locales/en/operationalStudies/scenario.json:73]: same a fr comment

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 17]
```diff
@@ -0,0 +1,130 @@
...
+          body: {
+            infra_id: _infraId,
+            ids: packageToFetch,
+            electrical_profile_set_id: electricalProfileSetId,
+          },
+        }).unwrap();
+
+        // launch the projection of the trains
+        setTrainIdsToProject((prev) => [...prev, ...packageToFetch]);
+        // console.log('1. package fetched', packageToFetch);
```
Comment (anisometropie) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]:
```suggestion
```

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx [hunk 18]
```diff
@@ -181,13 +180,23 @@ const TimetableToolbar = ({
           )}
         </div>
         <div>
-          {multiSelectOn && <span>{selectedTrainIds.length} / </span>}
-          {t('trainCount', {
-            count: trainSchedulesDetails.length,
-          })}
+          {trainSchedules.length > 0
```
Comment (anisometropie) [inline front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:183]: it’s a bit confusing to have the same box used to display the number of trains that are selected and the number of train loaded.
we Could display the `<Loader /> `component (in really small) while it’s loading to make it clear. and even write (loading 10/156 trains … )

**Review by anisometropie — CHANGES_REQUESTED** [review]
Good job overall, It’s nice to see the chart being populated little by little

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx (hunk 18 above)
Comment (anisometropie) [reply front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:183]: do we display a `<Loader />` on top of the GET aswell ?

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 1 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:71]: Actually, I have read that if a function is only used in a useEffect, it's better to keep it inside the useEffect. We can discuss it if you want and try to read more papers/articles about it

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 2 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: The function is way more elegant, thanks :pray:

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 4 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Done

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 5 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Done

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 7 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Done

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts (hunk 9 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: No it does not. I can remove the comment :+1:

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts (hunk 10 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts:33]: Do you think we can do it later, in another PR ? I didn't not changed the logic of this function and it is not the main purpose of the PR

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 11 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done

File: front/src/applications/operationalStudies/hooks/useScenario.ts (hunk 12 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenario.ts]: Agree with you :+1:

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 13 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: I left this comment on purpose to help the reviewers to test the PR. I will remove it at the end of the review.

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 15 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I thought it was more readable to have a function with a name instead of the code directly under the `if` line 134. I still prefer to have the function, what do you think ?

File: front/src/modules/trainschedule/components/TimetableV2/utils.ts (hunk 8 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/utils.ts:10]: Yes we can refacto this in another PR, I think this one is already big enough :+1:

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts (hunk 3 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts:63]: I created a small utils function in the same file :+1:

File: front/public/locales/fr/operationalStudies/scenario.json (hunk 14 above)
Comment (clarani) [reply front/public/locales/fr/operationalStudies/scenario.json:72]: I prefer to have 1/100 train, but we can see what the other reviewers think :+1:

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts (hunk 10 above)
Comment (anisometropie) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts:33]: sure

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx (hunk 18 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:183]: Yes some UI improvements are planned for a next PR, can I fix your comment in it ?

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts [hunk 19]
```diff
@@ -0,0 +1,111 @@
...
+          return false;
+      }
+
+      return true;
+    });
+
+  useEffect(() => {
+    if (trainSchedulesWithDetails.length === 0) {
+      setUniqueTags([]);
+      return;
```
Comment (SarahBellaha) [inline front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]:
```suggestion
    if (trainSchedulesWithDetails.length === 0) {
      setDisplayedTrainSchedules([]);
      setUniqueTags([]);
      return;
```

Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: Nice catch, thanks :) Done :white_check_mark:

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 7 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Actually, I can't do that because i is the index used to get the correct ten ids to fetch. It has to remain like this

File: front/public/locales/fr/operationalStudies/scenario.json (hunk 14 above)
Comment (kmer2016) [reply front/public/locales/fr/operationalStudies/scenario.json:72]: I tend to agree with @anisometropie

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts [hunk 20]
```diff
@@ -0,0 +1,84 @@
...
+  return relevantTrainSchedules;
+};
+
+const formatTrainScheduleSummaries = (
+  trainIds: number[],
+  rawSummaries: Dictionary<SimulationSummaryResult>,
+  rawTrainSchedules: Dictionary<TrainScheduleResult>,
+  rollingStocks: LightRollingStockWithLiveries[]
+): Dictionary<TrainScheduleWithDetails> => {
+  const relevantTrainSchedules = getRelevantTrainSchedules(rawTrainSchedules, trainIds);
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts]:
```suggestion
  const relevantTrainSchedules = trainIds.map(trainId => rawTrainSchedules[trainId]).filter(Boolean)
```
Since the logic is now more concise, the `getRelevantTrainSchedules` function may no longer be needed.

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 21]
```diff
@@ -0,0 +1,207 @@
...
+    if (trainSchedules && infra?.state === 'CACHED' && trainSchedules.length > 0) {
+      selectTrainAndPathForProjection(
+        trainSchedules.map((trainSchedule) => trainSchedule.id),
+        setSelectedTrainId,
+        setTrainIdUsedForProjection,
+        trainIdUsedForProjection,
+        selectedTrainId
+      );
+    }
+  }, [trainSchedules, infra]);
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: What do you think about migrating this `useEffect` logic along with the `selectTrainAndPathForProjection` function into a custom hook called `useTrainProjection`? This could improve code organization by encapsulating the logic in one place, making this big hook cleaner and more modular.

We can do that in another PR

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts [hunk 22]
```diff
@@ -0,0 +1,39 @@
...
+      id: +trainId,
+      trainName: matchingTrain?.train_name || 'Train name not found',
+      departure_time: formatDatetimeForSpaceTimeChart(currentProjectedTrain.departure_time),
+    };
+
+    newProjectedTrains[trainId] = projectedTrain;
+  });
+
+  return newProjectedTrains;
+};
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: We can improve performance a little bit by using` Object.entries` here instead of `Object.keys` , as it provides both keys and values directly, making the code a bit cleaner and avoiding extra lookups.

```suggestion
  Object.entries(projectedTrainsToUpsert).forEach(([trainId, trainData]) => {
    if (!trainData) {
      console.error(`Train ${trainId} not found in the projectedTrainsToUpsert`);
      return;
    }

    const schedule = trainSchedulesById[trainId];
    const projectedTrain = {
      ...trainData,
      id: Number(trainId),
      trainName: schedule?.train_name || 'Train name not found',
      departure_time: formatDatetimeForSpaceTimeChart(currentProjectedTrain.departure_time),
    };

    newProjectedTrains[trainId] = projectedTrain;
  });

  return newProjectedTrains;
};
```

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 23]
```diff
@@ -0,0 +1,128 @@
...
+import useLazyProjectTrains from 'modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains';
+import type { TrainScheduleWithDetails } from 'modules/trainschedule/components/TimetableV2/types';
+import type { Dictionary } from 'utils/types';
+
+import formatTrainScheduleSummaries from '../helpers/formatTrainScheduleSummaries';
+import { getTrainIdsPackage } from 'modules/simulationResult/components/SpaceTimeChart/utils';
+
+const BATCH_SIZE = 10;
+
+type useLazyLoadTrainsProp = {
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]:
```suggestion
type UseLazyLoadTrainsProp = {
```

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 7 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: that change comes together with removing the ×10 in `getTrainIdsPackage`.
I find it easier to follow to increment by 10 than incrementing by 1 and multiplying by 10 everywhere

File: front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx (hunk 18 above)
Comment (anisometropie) [reply front/src/modules/trainschedule/components/TimetableV2/TimetableToolbar.tsx:183]: sure

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 24]
```diff
@@ -0,0 +1,207 @@
...
+  }, [trainIdUsedForProjection]);
+  useEffect(() => {
+    if (trainIdUsedForProjection !== trainIdUsedForProjectionInStore)
+      setTrainIdUsedForProjection(trainIdUsedForProjectionInStore);
+  }, [trainIdUsedForProjectionInStore]);
+
+  useEffect(() => {
+    dispatch(updateTrainIdUsedForProjection(undefined));
+    dispatch(updateSelectedTrainId(undefined));
+  }, []);
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I'm not sure on why we manage `selectedTrainId` and `trainIdUsedForProjection` in both local state and the store. Having both can complicate things due to duplication and synchronization overhead. Could we simplify by using just one source of truth ? It seems like the store version alone would be sufficient.

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 1 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:71]: adding a function creates a level of abstraction and indirection. we hide details behind a name, but in return we get a simpler flow of code to read.
Here it just looks like we getting the worse of both world, we get a big function declaration in the middle of the code plus the indirection. I don’t really see what we get for that tradeoff.

do you have links ?

Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:71]: Unfortunately, the intermediate function is necessary because it's `async`. It's not possible to pass an `async` function to `useEffect()` directly. See https://github.com/facebook/react/issues/14326#issuecomment-441680293

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts (hunk 3 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts:63]: this is really generic, can’t this can be in utils/date.ts?

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 4 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: perhaps we can do a PR to change that everywhere. to be discussed tuesday

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 15 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: same discussion as https://github.com/OpenRailAssociation/osrd/pull/8271#discussion_r1711663239

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 2 above)
Comment (anisometropie) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: I made the two changes together initially https://github.com/OpenRailAssociation/osrd/pull/8271#discussion_r1711644827

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts (hunk 3 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts:63]: This function is not used anywhere else and is going to be removed when we will send date instead of time string to the chart , so I would rather keep it here

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts [hunk 25]
```diff
@@ -0,0 +1,112 @@
...
+ * @param validityFilter filter on valid train or not
+ * @param scheduledPointsHonoredFilter filter on trains that keep their timetables or not
+ * @param selectedTags filter on train's speed limit tag
+ * @returns trainschedules unique speedlimit tags
+ */
+const useFilterTrainSchedules = (
+  trainSchedulesWithDetails: TrainScheduleWithDetails[],
+  debouncedFilter: string,
+  debouncedRollingstockFilter: string,
+  validityFilter: string,
```
Comment (kmer2016) [inline front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]:
```suggestion
  validityFilter: ValidityFilter,
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]
Thank you for this PR. Extracting logic in hooks makes components clearer. The code is more modulable.

File: front/src/utils/types.ts [hunk 26]
```diff
@@ -15,3 +15,5 @@ export type ArrayElement<ArrayType extends readonly unknown[] | undefined | null
 export type typedEntries<T> = Array<[keyof T, T[keyof T]]>;
 
 export type Unit = 'meters' | 'millimeters';
+
+export type Dictionary<T> = Record<string, T>;
```
Comment (emersion) [inline front/src/utils/types.ts]: Hm, not a huge fan of type definitions like these:

- Dictionaries aren't allowed to have e.g. `number` as keys? (JS objects can't have that as keys, but the concept of a dictionary can...)
- It's small/readable enough to be inlined IMHO, creating an indirection isn't worth saving a few characters.

File: front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts [hunk 27]
```diff
@@ -0,0 +1,6 @@
+/* eslint-disable import/prefer-default-export */
+
+export const getTrainIdsPackage = (tenIndex: number, trainIds: number[], batchSize: number) => {
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts]: ~~`indexInBatch` may be better than `tenIndex`?~~

EDIT: nope, maybe `batchIndex`?

Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts]: Other naming nit: s/Package/Batch/?

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts [hunk 28]
```diff
@@ -0,0 +1,36 @@
...
+  currentProjection?: number,
+  selectedTrainId?: number
+) => {
+  if (trainIds.length === 0) {
+    return;
+  }
+
+  if (selectedTrainId && !currentProjection) {
+    // if a selected train is given, we use it for the projection
+    if (trainIds.includes(selectedTrainId)) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Nit: these two `if`s can be merged together.

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts [hunk 29]
```diff
@@ -0,0 +1,36 @@
...
+      setTrainIdUsedForProjection(selectedTrainId);
+      return;
+    }
+  }
+
+  // if there is already a projection
+  if (currentProjection) {
+    // if the projected train still exists, keep it
+    if (trainIds.includes(currentProjection)) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Ditto

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts [hunk 30]
```diff
@@ -0,0 +1,39 @@
+import type { TrainSpaceTimeData } from 'applications/operationalStudies/types';
+import { type ProjectPathTrainResult, type TrainScheduleResult } from 'common/api/osrdEditoastApi';
+import { convertIsoUtcToLocalTime } from 'utils/date';
+import type { Dictionary } from 'utils/types';
+
+// TODO: feed the spaceTimeChart with date instead of formatted string
+const formatDatetimeForSpaceTimeChart = (departureTime: string) =>
+  `${convertIsoUtcToLocalTime(departureTime).slice(0, -6)}Z`;
```
Comment (emersion) [inline front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Perhaps a better way to write this would be:

```ts
new Date(departureTime).toISOString()
```

(That function always uses UTC.)

Comment (emersion) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Hm, by the way, it seems a bit weird to convert to local time and then force UTC without converting to UTC? (The above suggestion performs the conversion.)

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts [hunk 31]
```diff
@@ -0,0 +1,39 @@
...
+
+const upsertNewProjectedTrains = (
+  projectedTrains: Dictionary<TrainSpaceTimeData> | undefined,
+  projectedTrainsToUpsert: Dictionary<ProjectPathTrainResult>,
```
Comment (emersion) [inline front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Maybe `Map<number, ProjectPathTrainResult>` would be more appropriate here?

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 6 above)
Comment (emersion) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Maybe because it's an assertion-like kind of thing: something which is never expected to happen?

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 32]
```diff
@@ -0,0 +1,128 @@
...
+
+  // gradually fetch the simulation of the trains
+  useEffect(() => {
+    const getTrainScheduleSummaries = async (_infraId: number, _trainToFetchIds: number[]) => {
+      let formattedSummaries: Dictionary<TrainScheduleWithDetails> = {
+        ...trainScheduleSummariesById,
+      };
+      setAllTrainsLoaded(false);
+
+      for (let i = 0; i * BATCH_SIZE <= _trainToFetchIds.length - 1; i += 1) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Nit: in general for-loops are written `foo < bar` instead of `foo <= bar - 1`.

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 33]
```diff
@@ -0,0 +1,128 @@
...
+    trainIdsToProject,
+    path,
+    trainSchedules,
+    moreTrainsToCome: !allTrainsLoaded,
+    setTrainIdsToProject,
+  });
+
+  // gradually fetch the simulation of the trains
+  useEffect(() => {
+    const getTrainScheduleSummaries = async (_infraId: number, _trainToFetchIds: number[]) => {
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts:71]: Hm, that `_infraId` underscore trick is a bit unfortunate. Maybe we should just allow variable shadowing… (Just a random comment on the linter, nothing to be addressed in this PR.)

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 34]
```diff
@@ -0,0 +1,128 @@
...
+      let formattedSummaries: Dictionary<TrainScheduleWithDetails> = {
+        ...trainScheduleSummariesById,
+      };
+      setAllTrainsLoaded(false);
+
+      for (let i = 0; i * BATCH_SIZE <= _trainToFetchIds.length - 1; i += 1) {
+        const packageToFetch = getTrainIdsPackage(i, _trainToFetchIds, BATCH_SIZE);
+
+        const test = await postV2TrainScheduleSimulationSummary({
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: s/test/newSummaries/?

File: front/src/applications/operationalStudies/hooks/useScenario.ts [hunk 35]
```diff
@@ -0,0 +1,75 @@
...
+      dispatch(updateInfraID(scenario.infra_id));
+    } else {
+      dispatch(updateTimetableID(undefined));
+      dispatch(updateInfraID(undefined));
+      dispatch(updateTrainIdUsedForProjection(undefined));
+    }
+  }, [scenario]);
+
+  useEffect(() => {
+    if (isScenarioError && errorScenario) throw errorScenario;
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenario.ts:63]: Hm, we should probably bubble up that error to the user no?

File: front/src/applications/operationalStudies/hooks/useSimulationResults.ts [hunk 36]
```diff
@@ -37,19 +39,25 @@ const useSimulationResults = () => {
...
+    (selectedTrainId && selectedTrainSchedule) || undefined,
+    path,
+    (selectedTrainId && trainSimulation) || undefined,
+    (selectedTrainId && selectedTrainSchedule?.start_time) || undefined
   );
 
+  if (!selectedTrainId)
+    return {
+      selectedTrainPowerRestrictions: [],
+    };
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useSimulationResults.ts:51]: We could move this up a bit, and then get rid of a bunch of `selectedTrainId` tests I think?

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx [hunk 37]
```diff
@@ -18,179 +17,91 @@ import type {
...
 
   const toggleMicroMacroButton = (isMacroMode: boolean) => {
     setIsMacro(isMacroMode);
     setCollapsedTimetable(isMacroMode);
   };
 
-  const handleNGEOperation = (event: NGETrainrunEvent, netzgrafikDto: NetzgrafikDto) =>
-    handleOperation({ event, dispatch, timeTableId: timetableId!, netzgrafikDto });
+  const handleNGEOperation = (event: NGETrainrunEvent, netzgrafikDto: NetzgrafikDto) => {
+    if (scenarioData?.scenario.timetable_id) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: I believe we can just use `scenarioData!` here. If we don't have a scenario, then NGE shouldn't be active at all. (I'd prefer to notice any such unforeseen cases with a hard error, instead of silently dropping/ignoring the NGE events.)

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx [hunk 38]
```diff
@@ -18,179 +17,91 @@ import type {
...
-
-  useEffect(
-    () => () => {
-      dispatch(updateTimetableID(undefined));
-      dispatch(updateInfraID(undefined));
-      dispatch(updateElectricalProfileSetId(undefined));
-      dispatch(updateTrainIdUsedForProjection(undefined));
-    },
-    []
-  );
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx:165]: Yay for the `ScenarioV2` shrink! 😀

**Comment by emersion** [comment]
This seems to regress NGE: switch to macro editor, create a new train there, switch back: it doesn't appear in the list. (Same with all other NGE operations: edit and delete.)

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 39]
```diff
@@ -0,0 +1,207 @@
...
+const useScenarioData = () => {
+  const dispatch = useAppDispatch();
+  const trainIdUsedForProjectionInStore = useSelector(getTrainIdUsedForProjection);
+  const selectedTrainIdInStore = useSelector(getSelectedTrainId);
+
+  const [trainSchedules, setTrainSchedules] = useState<TrainScheduleResult[]>();
+  const [trainIdUsedForProjection, setTrainIdUsedForProjection] = useState<number>();
+  const [selectedTrainId, setSelectedTrainId] = useState<number>();
+  const [trainIdsToFetch, setTrainIdsToFetch] = useState<number[]>();
+  const [trainIdsToRemove, setTrainIdsToRemove] = useState<number[]>([]);
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: It seems a bit strange to have state for this. Is there a reason why we can't pass down a callback which removes train IDs? Something like `removeTrainIds(ids: number[])`?

(It would be a bit similar to `upsertTrainSchedules`, except it removes instead of inserting.)

File: front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts (hunk 20 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/formatTrainScheduleSummaries.ts]: Yes you're right ! Done :white_check_mark:

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 21 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Yes I agree, that's why I added the comment above :)

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 22 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Done

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 23 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 40]
```diff
@@ -0,0 +1,158 @@
...
+      } catch (e) {
+        console.error('error', e);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Should we bubble up this error to the user, since it's coming from the API?

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts (hunk 25 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 41]
```diff
@@ -0,0 +1,158 @@
...
+  const { getElectricalProfileSetId } = useOsrdConfSelectors();
+  const electricalProfileSetId = useSelector(getElectricalProfileSetId);
+
+  const [projectedTrainsById, setProjectedTrainsById] = useState<Dictionary<TrainSpaceTimeData>>(
+    {}
+  );
+  const projectedTrains = useMemo(() => Object.values(projectedTrainsById), [projectedTrainsById]);
+
+  const [nextPackageToProjectIndex, setNextPackageToProjectIndex] = useState(0);
+  const [readyToProjectNextPackage, setReadyToProjectNextPackage] = useState(true);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: It seems like this piece of state is just used to trigger the callback to project the next 10 trains. Can't we use a callback instead of state?

```ts
const projectNextTrains = async () => {
  try {
    // ...
  } finally {
    projectNextTrains();
  }
};
```

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 42]
```diff
@@ -0,0 +1,158 @@
...
+      infraId &&
+      path &&
+      trainIdsToProject &&
+      trainIdsToProject.length > 0
+    ) {
+      projectNextPackage(infraId, path, trainIdsToProject, nextPackageToProjectIndex);
+    }
+  }, [trainIdsToProject, readyToProjectNextPackage]);
+
+  // attention si on a des trains qui sont toujours en cours de projection et qu'on change le chemin ?
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: 🇫🇷🥖🐸

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 24 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: ~I agree, we should simplify, but the best way would be to keep the state version (to me) because I think there is no need to store this in the store (since everything is recomputed at each refresh).
But if I need to implement the state version in this PR, this will involve a lot of change :/ I wanted to do it in another PR :/~

~What do you prefer:~
- ~no state at all for this PR, and we replace the store by the state in another PR~
- ~ok for this version of the code, and we replace the store by the state in another PR (cohabitation of the store and state version for a moment)~
- ~you don't agree and prefer the store, then we can discuss it tomorrow at the front meeting ?~

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts [hunk 43]
```diff
@@ -0,0 +1,112 @@
...
+          )
+        )
+          return false;
+      }
+
+      return true;
+    });
+
+  useEffect(() => {
+    if (trainSchedulesWithDetails.length === 0) {
```
Comment (emersion) [inline front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: I've seen zero length arrays special-cased elsewhere and held back commenting, but this one is a bit bigger than the rest so I'll say it anyways: I don't think we need the special case? If the regular codepath handles empty arrays just fine, I think the code would be simpler/clearer if we could just drop the `if`.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 44]
```diff
@@ -0,0 +1,158 @@
...
+    osrdEditoastApi.endpoints.postV2TrainScheduleProjectPath.useLazyQuery();
+
+  const trainSchedulesById = useMemo(() => keyBy(trainSchedules, 'id'), [trainSchedules]);
+
+  useEffect(() => {
+    // reset the state when all the trains have been projected
+    if (
+      !moreTrainsToCome &&
+      readyToProjectNextPackage &&
+      nextPackageToProjectIndex * 10 > trainIdsToProject.length
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: s/10/BATCH_SIZE/

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 45]
```diff
@@ -0,0 +1,158 @@
...
+    ) {
+      setNextPackageToProjectIndex(0);
+      setTrainIdsToProject([]);
+    }
+  }, [moreTrainsToCome, readyToProjectNextPackage]);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Do we really need to reset the state? Can't we leave `trainIdsToProject` as-is?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 46]
```diff
@@ -0,0 +1,158 @@
...
+}: useLazyLoadTrainsProp) => {
+  const { getElectricalProfileSetId } = useOsrdConfSelectors();
+  const electricalProfileSetId = useSelector(getElectricalProfileSetId);
+
+  const [projectedTrainsById, setProjectedTrainsById] = useState<Dictionary<TrainSpaceTimeData>>(
+    {}
+  );
+  const projectedTrains = useMemo(() => Object.values(projectedTrainsById), [projectedTrainsById]);
+
+  const [nextPackageToProjectIndex, setNextPackageToProjectIndex] = useState(0);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Can't this be a function parameter instead of a state?

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 47]
```diff
@@ -0,0 +1,207 @@
...
+
+  const scenario = useScenario();
+
+  const { infra, isInfraLoaded, reloadCount } = useInfraStatus();
+
+  const { data: timetable } = osrdEditoastApi.endpoints.getV2TimetableById.useQuery(
+    { id: scenario?.timetable_id as number },
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Nit: I'd prefer `scenario?.timetable_id!` instead of a cast, to allow TypeScript to check that `timetable_id` is indeed a `number`.

(Same below)

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 48]
```diff
@@ -0,0 +1,207 @@
...
+  const {
+    trainScheduleSummaries,
+    projectedTrains,
+    setTrainScheduleSummariesById,
+    setProjectedTrainsById,
+  } = useLazyLoadTrains({
+    infraId: scenario?.infra_id,
+    trainIdsToFetch,
+    setTrainIdsToFetch,
+    path: (projectionPath?.status === 'success' && projectionPath) || undefined,
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Nit: `&& projectionPath` is unnecessary here

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 49]
```diff
@@ -0,0 +1,207 @@
...
+    trainSchedules,
+  });
+
+  useEffect(() => {
+    if (!timetable?.train_ids || !rawTrainSchedules) {
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Nit: I think `!timetable?.train_ids` is unnecessary here: the logic inside doesn't need it, and `rawTrainSchedules` can't be set when the timetable is missing.

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 28 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Done

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 29 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts [hunk 50]
```diff
@@ -0,0 +1,6 @@
...
+  const upperIndex = Math.min(tenIndex * batchSize + batchSize, trainIds.length);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts]: We don't actually need `Math.min` here: `slice()` takes all remaining elements if `upperIndex > trainIds.length`.

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 31 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: I used a record :)

Comment (emersion) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: The problem with `Record` is that keys are strings, which we need to convert around to numbers. `Map` doesn't have this issue. (`Map` also fixes a bunch of issues related to JS objects.)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 45 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Here is a suggestion based on what we started to work on together yesterday. It uses references to persist pieces of information across component re-renders (when it's unnecessary to use these as dependencies of `useEffect`), and a sequence number of the currently active projection to prevent multiple from running in parallel.

```ts
/**
 * This hook gradually projects trains of the timetable.
 *
 * It projects the trains by batch of 10 on the path.
 * This optimizes the performance of the application and allow us to display the
 * trains on the space time chart as soon as they are ready.
 */
const useLazyProjectTrains = ({
  infraId,
  trainIdsToProject,
  path,
  trainSchedules,
  moreTrainsToCome = false,
  setTrainIdsToProject,
}: useLazyLoadTrainsProp) => {
  const { getElectricalProfileSetId } = useOsrdConfSelectors();
  const electricalProfileSetId = useSelector(getElectricalProfileSetId);

  const [projectedTrainsById, setProjectedTrainsById] = useState<Dictionary<TrainSpaceTimeData>>(
    {}
  );
  const projectedTrains = useMemo(() => Object.values(projectedTrainsById), [projectedTrainsById]);

  const requestedProjectedTrainIds = useRef<Set<number>>(new Set());
  const projectionSeqNum = useRef<number>(0);

  const [postV2TrainScheduleProjectPath] =
    osrdEditoastApi.endpoints.postV2TrainScheduleProjectPath.useLazyQuery();

  const trainSchedulesById = useMemo(() => keyBy(trainSchedules, 'id'), [trainSchedules]);

  // gradually project the trains on the selected path
  useEffect(() => {
    const projectNextPackage = async (
      _pathfinding: PathfindingResultSuccess,
      packageToProject: number[]
    ) => {
      packageToProject.forEach((trainId) => requestedProjectedTrainIds.current.add(trainId));

      const { blocks, routes, track_section_ranges } = _pathfinding;
      const rawProjectedTrains = await postV2TrainScheduleProjectPath({
        projectPathForm: {
          infra_id: infraId!,
          ids: packageToProject,
          path: { blocks, routes, track_section_ranges },
          electrical_profile_set_id: electricalProfileSetId,
        },
      }).unwrap();

      setProjectedTrainsById((prevTrains) => {
        const newProjectedTrains = upsertNewProjectedTrains(
          prevTrains,
          rawProjectedTrains,
          trainSchedulesById
        );
        return newProjectedTrains;
      });
      // console.log('2. package', packageToProject);
    };

    const projectTrains = async (seqNum: number, path: PathfindingResultSuccess, _trainToProjectIds: number[]) => {
      const shouldProjectIds = _trainToProjectIds.filter(
        (trainId) => !requestedProjectedTrainIds.current.has(trainId)
      );

      for (let i = 0; i * BATCH_SIZE < shouldProjectIds.length; i += 1) {
        // If projection parameters have changed, bail out
        if (projectionSeqNum.current !== seqNum) break;

        const packageToProject = getTrainIdsPackage(i, shouldProjectIds, BATCH_SIZE);
        try {
          await projectNextPackage(path, packageToProject);
        } catch (e) {
          console.error('error', e);
        }
      }
    };

    if (infraId && path) {
      projectionSeqNum.current += 1;
      projectTrains(projectionSeqNum.current, path, trainIdsToProject);
    }
  }, [trainIdsToProject]);

  return {
    projectedTrains,
    setProjectedTrainsById,
  };
};
```

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 24 above)
Comment (kmer2016) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: let's go with the second option. If everything is recalculated each time and the data isn't reused elsewhere or needs to be persisted, it makes sense to keep it in the local state. However, let's add a TODO and create an issue for this. We can link the issue to this discussion thread to keep track of it. Does that sound good?

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 47 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 49 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done, thanks :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts (hunk 50 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts]: Thanks !

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 44 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done :)

File: front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts (hunk 43 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/TimetableV2/useFilterTrainSchedules.ts]: You're right, I removed it :+1:

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx (hunk 37 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: Done :+1:

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 34 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Done

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 32 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts (hunk 27 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/utils.ts]: Done :+1:

File: front/src/utils/types.ts (hunk 26 above)
Comment (clarani) [reply front/src/utils/types.ts]: Done

File: front/public/locales/fr/operationalStudies/scenario.json (hunk 14 above)
Comment (clarani) [reply front/public/locales/fr/operationalStudies/scenario.json:72]: OK then, it's done :)

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 31 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Done, I used Map everywhere I can

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 41 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done, with the refacto of useLazyProjectTrains

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 42 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Removed :+1:

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 45 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done, with the refacto of useLazyProjectTrains.
Thanks for the suggestion !

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 46 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done, with the refacto of useLazyProjectTrains

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 48 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: I modified a bit the code :+1:

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 39 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: You're right, it's done :white_check_mark:

File: front/src/applications/operationalStudies/hooks/useSimulationResults.ts (hunk 36 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useSimulationResults.ts:51]: I'm not sure I can move it up, because otherwise I will create the error "rendered fewer hooks than expected"

File: front/src/applications/operationalStudies/hooks/useScenario.ts (hunk 35 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenario.ts:63]: It is the case here, the user will encounter an error page :+1:

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 40 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: I don't really know how to do this properly right now, I would prefer to leave this for later, when we will refactor the notification system, if it's fine for you

File: front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts (hunk 30 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/upsetNewProjectedTrains.ts]: Yes, it's quite weird, but we have to do so for the spaceTimeChart right now. I would like to fix this weird behaviour right after this PR

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 24 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Sorry, I thought about it again and you're right. I have removed the state and keep the store version :+1:

**Comment by kmer2016** [comment]
When I try to create 200 trains, I encounter an error in the console and it seems that the creation process stops at 50 trains
image
image

**Review by kmer2016 — COMMENTED** [review]
When I try to create 200 trains, I encounter an error in the console and it seems that the creation process stops at 50 trains
image
image

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 2 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Ah yes, done :white_check_mark:

**Review by bloussou — APPROVED** [review]
Tested on the target environment !!! Works as expected thanks a lot !

**Comment by bloussou** [comment]
@kmer2016 I can't reproduce on the target env, you have probably reached the limit of editoast on you computer

**Review by Khoyo — APPROVED** [review]

**Review by Tguisnet — APPROVED** [review]
Can't reproduce the problem that @kmer2016 encountered !

**Review by anisometropie — APPROVED** [review]

File: front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts [hunk 51]
```diff
@@ -119,6 +129,7 @@ const handleTrainrunOperation = async ({
           },
         })
       ).unwrap();
+      upsertTrainSchedules([newTrainSchedule]);
```
Comment (emersion) [inline front/src/applications/operationalStudies/components/MacroEditor/ngeToOsrd.ts]: I believe this triggers a series of pathfinding/simulation requests down the line. I think this is undesirable because it will spam the backend with requests every time a small change is made in NGE.

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 28 above)
Comment (emersion) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Sounds like it's not been pushed or lost in a rebase?

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 29 above)
Comment (emersion) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Ditto

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 52]
```diff
@@ -0,0 +1,145 @@
...
+
+      setProjectedTrainsById((prevTrains) => {
+        const newProjectedTrains = upsertNewProjectedTrains(
+          prevTrains,
+          rawProjectedTrains,
+          trainSchedulesById
+        );
+        return newProjectedTrains;
+      });
+      // console.log('2. package', packageToProject);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Nit: needs to be dropped before merge

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts [hunk 53]
```diff
@@ -0,0 +1,145 @@
...
+
+      for (let i = 0; i < shouldProjectIds.length; i += BATCH_SIZE) {
+        // If projection parameters have changed, bail out
+        if (projectionSeqNum.current !== seqNum) break;
+
+        const packageToProject = getBatchPackage(i, shouldProjectIds, BATCH_SIZE);
+        try {
+          await projectNextPackage(_path, packageToProject);
+        } catch (e) {
+          console.error('error', e);
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts:107]: Can we bubble up this error to the user, instead of keeping it in the console where only developers know where to look? Can be confusing to look at a blank page which never gets populated without any indication that something failed.

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 17 above)
Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: This needs to be addressed before merging as well.

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts [hunk 54]
```diff
@@ -0,0 +1,120 @@
...
+    path,
+    trainSchedules,
+    moreTrainsToCome: !allTrainsLoaded,
+    setTrainIdsToProject,
+  });
+
+  // gradually fetch the simulation of the trains
+  useEffect(() => {
+    const getTrainScheduleSummaries = async (_infraId: number, _trainToFetchIds: number[]) => {
+      let formattedSummaries = deepCloneMap(trainScheduleSummariesById);
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Hm, why is a deep copy necessary here? The map itself is copied over again below. Do we mutate the elements somewhere?

(Note, it's bad practice to mutate some elements contained in the state directly -- elements need to be copied right before being mutated, see https://react.dev/learn/updating-objects-in-state#updating-a-nested-object)

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 47 above)
Comment (emersion) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Seems like this has been lost at some point as well.

File: front/src/utils/types.ts [hunk 55]
```diff
@@ -15,3 +17,33 @@ export type ArrayElement<ArrayType extends readonly unknown[] | undefined | null
...
+
+export const mapBy = <K extends keyof T, T>(items: T[] | undefined, key: K): Map<T[K], T> => {
+  const map = new Map<T[K], T>();
+  if (items) {
+    items.forEach((item) => {
+      map.set(item[key], item);
+    });
+  }
+  return map;
+};
```
Comment (emersion) [inline front/src/utils/types.ts]: A simpler way to write this would be:

```ts
new Map(items.map((item) => [item.key, item]))
```

at which point it's probably trivial enough to be inlined at the call-site.

File: front/src/utils/types.ts [hunk 56]
```diff
@@ -15,3 +17,33 @@ export type ArrayElement<ArrayType extends readonly unknown[] | undefined | null
...
+
+export const concatMap = <K, V>(map1: Map<K, V>, map2: Map<K, V>) => {
+  const result = new Map<K, V>(map1);
+  for (const [key, value] of map2) {
+    result.set(key, value);
+  }
+  return result;
+};
```
Comment (emersion) [inline front/src/utils/types.ts]: A simpler way to write this would be:

```ts
new Map([...map1.entries(), ...map2.entries()])
```

at which point it's probably trivial enough to be inlined at the call-site.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 53 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts:107]: Yes, I added a notification :+1:

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 54 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: You're right, I removed it :+1:

File: front/src/utils/types.ts (hunk 55 above)
Comment (clarani) [reply front/src/utils/types.ts]: Thanks :+1:

File: front/src/utils/types.ts (hunk 56 above)
Comment (clarani) [reply front/src/utils/types.ts]: Thanks :+1:

File: front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts (hunk 52 above)
Comment (clarani) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useLazyProjectTrains.ts]: Done :white_check_mark:

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 28 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Done again :white_check_mark:

File: front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts (hunk 29 above)
Comment (clarani) [reply front/src/applications/operationalStudies/helpers/selectTrainAndPathForProjection.ts]: Done again ✅

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts (hunk 47 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Done again ✅

File: front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts (hunk 17 above)
Comment (clarani) [reply front/src/applications/operationalStudies/hooks/useLazyLoadTrains.ts]: Done :white_check_mark:

File: front/src/applications/operationalStudies/helpers/upsertNewProjectedTrains.ts [hunk 57]
```diff
@@ -0,0 +1,39 @@
...
+// TODO: feed the spaceTimeChart with date instead of formatted string
+const formatDatetimeForSpaceTimeChart = (departureTime: string) =>
+  `${convertIsoUtcToLocalTime(departureTime).slice(0, -6)}Z`;
+
+const upsertNewProjectedTrains = (
+  projectedTrains: Map<number, TrainSpaceTimeData>,
+  projectedTrainsToUpsert: Record<string, ProjectPathTrainResult>,
+  trainSchedulesById: Map<number, TrainScheduleResult>
+) => {
+  const newProjectedTrains = deepCloneMap(projectedTrains);
```
Comment (emersion) [inline front/src/applications/operationalStudies/helpers/upsertNewProjectedTrains.ts]: It should be unnecessary to deep-clone the whole map here. A simple clone (`new Map(projectedTrains)`) should be enough since we copy any projected train we update.

File: front/src/applications/operationalStudies/hooks/useScenarioData.ts [hunk 58]
```diff
@@ -0,0 +1,190 @@
...
+      const sortedTrainSchedulesToUpsert = sortBy(trainSchedulesToUpsert, 'start_time');
+      setTrainIdsToFetch(sortedTrainSchedulesToUpsert.map((trainSchedule) => trainSchedule.id));
+    },
+    [trainSchedules]
+  );
+
+  const removeTrains = (_trainIdsToRemove: number[]) => {
+    const trainSchedulesById = mapBy(trainSchedules, 'id');
+    const newTrainScheduleSummariesById = deepCloneMap(trainScheduleSummariesById);
+    const newProjectedTrainsById = deepCloneMap(projectedTrainsById);
```
Comment (emersion) [inline front/src/applications/operationalStudies/hooks/useScenarioData.ts]: Ditto: a shallow clone should be enough here as well.

**Comment by emersion** [comment]
When switching to NGE, I'm getting a never-ending loop of requests to `POST /api/search?page=1&page_size=100`. Sounds like it could be due to the new `useEffect` dependency on `scenarioData`.

**Comment by emersion** [comment]
Sounds like there is a code style issue in the core patch: https://github.com/OpenRailAssociation/osrd/actions/runs/10473869979/job/29006903332?pr=8271#step:5:9341

**Comment by kmer2016** [comment]
I no longer have the bug mentioned [here](https://github.com/OpenRailAssociation/osrd/pull/8271#pullrequestreview-2238015867)
However, I have a few questions:

- Is it normal to only display 10 trains at a time? I thought we were supposed to fetch the trains in batches of 10 but display them all.
- When I select all trains to delete them, it only deletes the 10 that are currently displayed.
- If I delete the trains one by one, the list only shows 10 minus the number of deleted trains, even if I have more than that in total. Also, the train counter briefly shows "No trains" before refreshing with the correct count.


https://github.com/user-attachments/assets/477206d8-8e99-47e1-90f0-9bf69e5d39f9

**Comment by bloussou** [comment]
@kmer2016 

>  Is it normal to only display 10 trains at a time? I thought we were supposed to fetch the trains in batches of 10 but display them all.

yes, otherwise the user will wait forever on big timetables to see all the trains, the goal is to have something showing it is a work in progress

> When I select all trains to delete them, it only deletes the 10 that are currently displayed.

This is not perfect but I'm ok with it, not sure you want to delete everything before everything is loaded (it is a behavior we can fix later with a proper UX design, feel free to open an issue)

> If I delete the trains one by one, the list only shows 10 minus the number of deleted trains, even if I have more than that in total. Also, the train counter briefly shows "No trains" before refreshing with the correct count.

Same as above, feel free to open an issue, it is not a big problem in my opinion

In another PR we could forbid deletion if loading is not ended to patch your comment before finding a good way to handle it but I don't think it must be done in this one

**Comment by kmer2016** [comment]
> In another PR we could forbid deletion if loading is not ended to patch your comment before finding a good way to handle it but I don't think it must be done in this one.

ok, @bloussou , I created this [issue](https://github.com/OpenRailAssociation/osrd/issues/8508)

**Review by kmer2016 — APPROVED** [review]
LGTM and tested !

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx [hunk 59]
```diff
@@ -18,179 +17,121 @@ import type {
...
-    }
-  }, [scenario]);
-
-  const { data: timetable } = osrdEditoastApi.endpoints.getV2TimetableById.useQuery(
-    { id: timetableId! },
-    {
-      skip: !timetableId,
+    if (!scenarioData || !isMacro || (isMacro && ngeDto)) {
+      if (!isMacro && ngeDto) {
+        setNgeDto(undefined);
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: Isn't this already handled below?

File: front/src/utils/types.ts [hunk 60]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable no-restricted-syntax */
```
Comment (emersion) [inline front/src/utils/types.ts]: Nit: I think this can be dropped now.

**Review by emersion — APPROVED** [review]
Two small nits, apart from these everything LGTM! Feel free to resolve/merge/ignore.

Follow-up issue: NGE updates shouldn't trigger projections/simulations as side effects.

File: front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx (hunk 59 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/v2/ScenarioV2.tsx]: Yes, you're right, thanks :pray:
