### PR TITLE
front: fix macro labels

### LINKED ISSUE #12085: nge: trainrun labels added from nge are not displayed in nge after reload
### What happened?

When a trainrun label is added on a trainrun in NGE, after reloading the macro editor, the label isn't displayed anymore in NGE

Also, when we import a NGE scenario, the trainrun labels are not displayed as well in NGE, like this one:
(need this PR to be merged https://github.com/OpenRailAssociation/osrd/pull/11937)
[reticulaire.json](https://github.com/user-attachments/files/20689017/reticulaire.json)

Even tho, for both cases, the label is stored and displayed in micro mode.

### What did you expect to happen?

Display the labels in both modes

### How can we reproduce it (as minimally and precisely as possible)?

1. either create a trainrun label in NGE
2. or import the NGE scenario linked above (you can see the base scenario on this test environnment : https://schweizerischebundesbahnen.github.io/netzgrafik-editor-frontend/)

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by louisgreiner**
Closes https://github.com/OpenRailAssociation/osrd/issues/12085

### CODE REVIEW

File: front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts [hunk 1]
```diff
@@ -444,20 +444,25 @@ const getNgeTrainrunSectionsWithNodes = (state: MacroEditorState, labels: LabelD
...
+
+  return [
+    ...nodeLabels.map((l, i) => ({
+      id: i,
+      label: l,
+      labelGroupId: NODE_LABEL_GROUP.id,
+      labelRef: 'Node',
+    })),
+    ...trainrunLabels.map((l, i) => ({
+      id: nodeLabels.length + i,
```
Comment (emersion) [inline front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: Maybe we could compute the ID as a second step to avoid any duplicates?

```ts
return […].map((l, i) => { ...l, id: i });
```

Comment (louisgreiner) [reply front/src/applications/operationalStudies/components/MacroEditor/osrdToNge.ts]: True, done

**Review by emersion — APPROVED** [review]
LGTM, thanks for the fix!

**Review by theocrsb — APPROVED** [review]
lgtm
