### PR TITLE
Correct Loader Font, Clear Alternative Simulation Info, and Cancel Alternative Results

### LINKED ISSUE #10572: Alternative Solutions Search and Display for Failed STDCM Simulations
When an STDCM simulation fails, two alternative queries should be triggered in parallel with slight adjustments to the time tolerance parameters (one earlier and one later). During this process, the loader should be updated to inform the user that an alternative solutions search is in progress.

### PR DESCRIPTION
**Pull request by achrafmohye**
Closes #10572

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx [hunk 1]
```diff
@@ -35,6 +35,7 @@ type StcdmResultsProps = {
   onStartNewQueryWithData: () => void;
   buttonsVisible: boolean;
   showStatusBanner: boolean;
+  hasSeenInfoMessage: boolean;
 };
 
 const StcdmResults = ({
```
Comment (Caracol3) [inline front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: NIT : It's probably something that's been inherited for a while, but we could rename StcdmResults to StdcmResults to keep things consistent.

Comment (achrafmohye) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: Nice catch, Done !

**Review by Caracol3 — APPROVED** [review]
lgtm (tested)

**Review by kmer2016 — APPROVED** [review]
LGTM !
