### PR TITLE
front: remove useless requests in Scenario page

### LINKED ISSUE #554: Simulation results: duplication of requests
**Describe the bug**
The front makes the same requests multiple times: `/train_schedule/results/?train_ids=1,2&path=1`

2023-02-16-141235_864x203_scrot

**To Reproduce**
1. Open your browser debuging network panel
2. Go to 'Etudes d'exploitation' -> Open project -> Open study -> Open scenario
3. See multiple query

**Expected behavior**

Only one `GET` `/train_schedule/results/...` query should be done.

**Desktop:**
 - Env: Local and Dev
 - Browser: firefox
 - Version: `3dbd5632`

### PR DESCRIPTION
**Pull request by clarani**
Fixes #554 
Removed 2 useless requests (still have 2, but to reduce to 1, I think we will have to refactor the whole component/store system)

I also removed useless variables in SimulationResults.

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario.jsx [hunk 1]
```diff
@@ -62,6 +64,7 @@ export default function Scenario() {
       setScenario(result);
       dispatch(updateTimetableID(result.timetable));
       dispatch(updateInfraID(result.infra));
+      console.log('hello from Scenario');
```
Comment (nicolaswurtz) [inline front/src/applications/operationalStudies/views/Scenario.jsx]: Nope :P

**Review by nicolaswurtz — CHANGES_REQUESTED** [review]

File: front/src/applications/operationalStudies/views/Scenario.jsx (hunk 1 above)
Comment (clarani) [reply front/src/applications/operationalStudies/views/Scenario.jsx]: Thanks !! ^^

**Review by nicolaswurtz — APPROVED** [review]
