### PR TITLE
front: rolling stock editor too many digits fix

### LINKED ISSUE #5587: Too many digits in rolling stock edition mode, not enough in visualization mode
### What happened?

There are too many digits here compared to the significant ones :
image

And not enough here, in visualization mode (same RS) :
image

### What did you expect to happen?

I don't know if this should be fixed by backend or front end, but i'm not expecting to see 00000001 at the end of a number because it's a float.

Also, if we decide to hide some digits the numbe should be rounded, not just crop the last digits.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to rs editor and either find a rs that has lots of digits on these coefficient, or create one to see the bug.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c39e6996

### PR DESCRIPTION
**Pull request by Wadjetz**
close #5587

### CODE REVIEW

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 1]
```diff
@@ -32,8 +32,29 @@ type Props = {
...
+
+  const parts = value.toString().split('.');
+  if (parts.length === 2) {
+    const stripedDecimal = parts[1].substring(0, decimalPlaces);
+    const result = Number(`${parts[0]}.${stripedDecimal}`);
+    return result;
+  }
+  return value;
+}
+
```
Comment (anisometropie) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: => utils/numbers.ts

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 2]
```diff
@@ -32,8 +32,29 @@ type Props = {
...
+    !Number.isFinite(value) ||
+    !Number.isInteger(decimalPlaces) ||
+    decimalPlaces < 0 ||
+    value === 0
+  ) {
+    return value;
+  }
+
+  const parts = value.toString().split('.');
+  if (parts.length === 2) {
```
Comment (anisometropie) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx:50]: if value is a number, not NaN, finite, how is it ever going to be false?

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 3]
```diff
@@ -32,8 +32,29 @@ type Props = {
   textRight?: boolean;
   disabled?: boolean;
   disableUnitSelector?: boolean;
+  limitDecimal?: number;
 };
 
+export function stripDecimalDigits(value: number, decimalPlaces: number): number {
```
Comment (anisometropie) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: can you justify each use cases with a unit test

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx [hunk 4]
```diff
@@ -167,11 +167,18 @@ export default function RollingStockCardDetail({
                 <td className="text-primary">{t('rollingResistanceB')}</td>
               </tr>
               <tr>
-                <td>
-                  {Math.floor(
+                <td
+                  title={
+                    rollingStock.rolling_resistance?.C
+                      ? ((rollingStock.rolling_resistance.C * 10000) / 10000).toString()
```
Comment (anisometropie) [inline front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: Missing Math.floor.
if you want to have 4 decimals, you might as well use the function you just wrote

**Review by anisometropie — CHANGES_REQUESTED** [review]

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx [hunk 5]
```diff
@@ -167,11 +167,18 @@ export default function RollingStockCardDetail({
...
+                      : undefined
+                  }
+                >
+                  {floor(
```
Comment (anisometropie) [inline front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: really puzzling, 10000 suggests 4 decimals, by `floor` limits to 2 decimals

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 4 above)
Comment (Wadjetz) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: We show the rounded value, but in the title we show the entire value

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 5 above)
Comment (Wadjetz) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: Yes, it useless to do it twice

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 6]
```diff
@@ -76,6 +80,29 @@ export default function InputGroupSNCF({
...
+  );
+
+  const inputValue = useMemo(() => {
+    if (value !== undefined && !disabled) {
+      if (limitDecimal && value !== '') {
+        return stripDecimalDigits(Number(value), limitDecimal);
+      }
+      return value;
+    }
+    return undefined;
```
Comment (clarani) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: Use "" otherwise you will have an error in your console
```suggestion
    return '';
```

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 4 above)
Comment (clarani) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: I don't understand why you multiply by 1000 and then divide by 1000, am I missing smth ? I think it does nothing, you can remove the *1000/1000 if you remove the Math.floor

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 5 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: thanks.
does lodash `floor` do something different than your function stripDecimalDigits

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 4 above)
Comment (anisometropie) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: yeah you can remove it I think

File: front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx (hunk 5 above)
Comment (Wadjetz) [reply front/src/modules/rollingStock/components/RollingStockCard/RollingStockCardDetail.tsx]: Yes, lodash floor have a precision parameter

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark:

File: front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx [hunk 7]
```diff
@@ -164,6 +164,7 @@ const RollingStockEditorParameterFormColumn = ({
                 } as SetStateAction<RollingStockParametersValues>);
                 setOptionValue(type.type as string);
               }}
+              limitDecimal={property.title === 'rollingResistanceC' ? 10 : undefined}
```
Comment (anisometropie) [inline front/src/modules/rollingStock/components/RollingStockEditor/RollingStockEditorFormHelpers.tsx]: as discussed I think we can have this behavior by default (10 digits max) not just for this one field `rollingResistanceC`

File: front/src/common/BootstrapSNCF/InputGroupSNCF.tsx [hunk 8]
```diff
@@ -55,6 +63,7 @@ export default function InputGroupSNCF({
   textRight = false,
   disabled = false,
   disableUnitSelector = false,
+  limitDecimal,
```
Comment (anisometropie) [inline front/src/common/BootstrapSNCF/InputGroupSNCF.tsx]: 10 by default

**Review by anisometropie — CHANGES_REQUESTED** [review]

**Review by anisometropie — APPROVED** [review]
