### PR TITLE
front: stdcm: fix stop time default value

### LINKED ISSUE #9354: Stop time in STDCM is automatically set to zero and triggers warning
### What happened?

Image

### What did you expect to happen?

In case of "relève conducteur", the default stop time should be 3mn so the warning isn't triggered.
In case of "arrêt de service" the default value can remain 0min.
If a stop time is entered, it sould be memorized if the user switches from "arrêt de service" to "relève conducteur" and _vice-versa_.

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

e66e534

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #9354

### CODE REVIEW

**Review by Akctarus — COMMENTED** [review]
Tested, the bug is well fixed, however, when you set a stop time (to 10 minutes for example), and reload the page, the stop type is set to “passage stop”, so its stop time is supposed to be zero, but if you click on “Get simulation”, you end up with a passage stop that stops for 10 minutes. 

The stop type needs to be saved when refreshing the page. But I don't know whether this bug should be fixed on this PR, or on a new one.

**Comment by axrolld** [comment]
I agreee that refreshing should not change the via type, it's something we've noiced during the user tests, i was about to open a bug for that. Idk if it should be done in this PR though, as you prefer

File: front/src/applications/stdcmV2/components/StdcmVias.tsx [hunk 1]
```diff
@@ -62,17 +62,12 @@ const StdcmVias = ({ disabled = false, setCurrentSimulationInputs }: StdcmConfig
...
-      updatePathStepStopTime(defaultStopTime, index, pathStepId);
-
-      return updatedStopTypes;
-    });
+    setStopTypes((prevStopTypes) => ({
+      ...prevStopTypes,
+      [pathStepId]: newStopType,
+    }));
+    const defaultStopTime = newStopType === StdcmStopTypes.DRIVER_SWITCH ? '3' : '';
+    updatePathStepStopTime(defaultStopTime, index, pathStepId);
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmVias.tsx:77]: Nice thank you :)

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 2]
```diff
@@ -9,39 +9,44 @@ import { ISO8601Duration2sec } from 'utils/timeManipulation';
 
 import { StdcmStopTypes } from '../types';
 
+type StdcmInputViaProps = {
+  stopType?: StdcmStopTypes;
+  pathStepStopFor: PathStep['stopFor'];
+  updatePathStepStopTime: (stopTime: string) => void;
+};
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: ❤️

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 3]
```diff
@@ -9,39 +9,44 @@ import { ISO8601Duration2sec } from 'utils/timeManipulation';
...
+
 const StdcmInputVia = ({
   stopType,
-  pathStep,
+  pathStepStopFor,
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: As we don't use `pathStepStopType` for the other prop

```suggestion
  stopDuration,
```

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 4]
```diff
@@ -9,39 +9,44 @@ import { ISO8601Duration2sec } from 'utils/timeManipulation';
...
-  pathStep: PathStep;
-  updatePathStepStopTime: (stopTime: string) => void;
-}) => {
+}: StdcmInputViaProps) => {
   const { t } = useTranslation('stdcm');
 
-  const [pathStepStopTime, setPathStepStopTime] = useState(
-    pathStep.stopFor ? `${ISO8601Duration2sec(pathStep.stopFor) / 60}` : ''
+  const computedStopTime = useMemo(
+    () => (pathStepStopFor ? `${ISO8601Duration2sec(pathStepStopFor) / 60}` : ''),
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: Could you add an util for that ?

```suggestion
    () => (pathStepStopFor ? `${secToMin(ISO8601Duration2sec(pathStepStopFor))}` : ''),
```

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 5]
```diff
@@ -9,39 +9,44 @@ import { ISO8601Duration2sec } from 'utils/timeManipulation';
...
-    () => debounce((value) => updatePathStepStopTime(value), 500),
+    () => debounce((value) => updatePathStepStopTime(value), 300),
     []
   );
 
   useEffect(() => {
-    let newStopTime = pathStepStopTime;
-    const isPassageTime = stopType === StdcmStopTypes.PASSAGE_TIME || stopType === undefined;
-    if (isPassageTime && pathStepStopTime !== '0') {
+    let newStopTime = computedStopTime;
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: I feel a bit confused now. Since we rely on `computedStopTime` which comes from `pathStep.stopFor` which comes form the store (so we do like a round trip between the form and the store), do we still need the state ? It seems to be used only for the condition `if (newStopTime !== pathStepStopTime)` but why do we need this ?  If we need it why not do the same for the `stopType` ?

**Review by SharglutDev — COMMENTED** [review]
I think we can fix the bug mentioned by @Akctarus and @axrolld in another PR.

Could you create an issue @axrolld ? :)

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx (hunk 5 above)
Comment (SarahBellaha) [reply front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: `pathStepStopTime` is used to keep track of user input, as the Input component doesn't handle this internally like other ui-core components do. Otherwise the pathStep will just be updated with the last caracter entered.
`stopType` is just here to determine the default value of the `computedStopTime`, we don't need to do the same for it as we don't need to update it.
I didn't want to spend a lot of time on analysing the component as it was just a small bug fix and not a refacto but i made some additional changes and it also resolved the issue mentionned above by @axrolld & @Akctarus :)

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 6]
```diff
@@ -1,51 +1,54 @@
...
-  );
+  const computedStopTime = useMemo(() => {
+    const duration = stopDuration ? `${secToMin(ISO8601Duration2sec(stopDuration))}` : '';
+    switch (stopType) {
+      case StdcmStopTypes.PASSAGE_TIME:
+        return '0';
+      case StdcmStopTypes.DRIVER_SWITCH:
+        return duration ?? '3';
+      default:
+        return duration ?? '0';
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: With l.22, `duration` will never be null or undefined so the `??` will never go in the right option.

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 7]
```diff
@@ -1,51 +1,54 @@
...
+  }, [pathStepStopTime]);
+
+  useEffect(() => {
+    setPathStepStopTime(computedStopTime);
+  }, [computedStopTime]);
 
   return (
-    stopType !== StdcmStopTypes.PASSAGE_TIME &&
-    stopType !== undefined && (
+    stopType !== StdcmStopTypes.PASSAGE_TIME && (
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx:47]: We need to keep the `stopType !== undefined` (or maybe `stopType &&` might be enough) otherwise when adding a new via we have this : 
image

File: front/src/applications/stdcmV2/components/StdcmInputVia.tsx [hunk 8]
```diff
@@ -1,51 +1,54 @@
...
-    if (isPassageTime && pathStepStopTime !== '0') {
-      newStopTime = '0';
-    }
-    if (newStopTime !== pathStepStopTime) {
-      setPathStepStopTime(newStopTime);
-      updatePathStepStopTime(newStopTime);
-    }
-  }, [pathStep.stopFor, stopType]);
+    updatePathStepStopTime(pathStepStopTime);
+  }, [pathStepStopTime]);
```
Comment (SharglutDev) [inline front/src/applications/stdcmV2/components/StdcmInputVia.tsx]: Do we really need this useEffect ?

**Review by Akctarus — APPROVED** [review]
Tested, thanks also for fixing the added bug :) apart @SharglutDev comments, LGTM

**Review by SharglutDev — COMMENTED** [review]
Thank you for the changes, everything looks good except this weird behavior in the store : 

https://github.com/user-attachments/assets/aaf0e395-ed31-4a67-ba94-62fa1f1ddd48

**Comment by SarahBellaha** [comment]
> Thank you for the changes, everything looks good except this weird behavior in the store :
> 
>  Enregistrement.de.l.ecran.2024-10-24.a.09.00.28.mov

This behaviour is due to the fact that there are two different ways of updating the pathStep informations. First we update its `stopType`, which is stored in a state, then we update the `stopTime` directly in the store, which then triggers an update of the `pathStep` in the store with the correct `stopType`.
We should change this method and update the pathStep directly in the store in both cases.
This will be done in another PR, as seen with @SharglutDev -> here's the [issue ticket](https://github.com/OpenRailAssociation/osrd/issues/9442).

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !
