### PR TITLE
front: fix cs code not required in railway manager modal 

### LINKED ISSUE #14410: Front-end does not make CS code field required
https://github.com/osrd-project/osrd-data-issues/issues/881

### PR DESCRIPTION
**Pull request by Synar**
Close [#14410](https://github.com/OpenRailAssociation/osrd/issues/14410)
Close [osrd-project/osrd-data-issues#881](https://github.com/osrd-project/osrd-data-issues/issues/881)

I aligned the behavior (wiggling when not filled) with the other existing required field on this page, although I'm curious why this is the only page with such a behavior..

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx [hunk 1]
```diff
@@ -413,7 +424,7 @@ const SendToRailwayManagerModal = ({
                 aria-invalid={pathTypeError}
               />
             </div>
-            <div className="cs-code">
+            <div className={`cs-code ${csCodeError ? 'wiggle' : ''}`}>
               <Input
```
Comment (SarahBellaha) [inline front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx:428]: You can also add the `required` arg on the `Input` component to mark the field as mandatory :) :arrow_down: 

Capture d’écran du 2025-12-15 13-53-52

**Review by Akctarus — APPROVED** [review]
Tested, LGTM, adding a `required` arg (as @SarahBellaha said) would be even better

File: front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx (hunk 1 above)
Comment (Synar) [reply front/src/applications/stdcm/components/StdcmResults/SendToRailwayManagerModal.tsx:428]: Oh I forgot to do this, good catch thanks!

**Review by SarahBellaha — APPROVED** [review]
Lgtm :)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested
