### PR TITLE
front: fix power restriction behavior 

### LINKED ISSUE #6639: Uncorrect axis cut in power restriction bar
### What happened?

When we enter a power restriction value in a part of the path and we save it, if we try to modify once again the train and we open power restriction bar, the axis of the bar is cut at the position where the power restriction was entered before.
image
image
image

### What did you expect to happen?

The axis of the power restrictions bar should be unchanged and it should  display the whole path 

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Create a train with a power restriction activated on a part of the path
3.  Modify this train and go to the power restriction bar

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 3acd113

### LINKED ISSUE #6783: Assert check fail for the power restriction bar
### What happened?

When we have several consecutive zones with the same power restriction (or none), we have an assert check error from the backend.
Capture d’écran 2024-02-28 à 10 59 14
Capture d’écran 2024-02-28 à 11 14 58

### What did you expect to happen?

We should be able to handle this case without having an error that prevents us from saving our modifications.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Create a train with the same power restriction on 2 consecutive parts of the path
3. Save

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: MacOs
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

4f7b93f

### LINKED ISSUE #6893: Power restriction not saved when creating/editing a train with some ranges without power restriction
### What happened?

I created a train from Paris Gare de Lyon to Dijon, and tried to add a power restriction code on only one range of the train (no power restriction code on the other ranges) : 

image

When I save the train, the payload does not contains the power restriction code, which was thus not saved.

### What did you expect to happen?

I expected the power restriction code to be saved

### How can we reproduce it (as minimally and precisely as possible)?

Follow the description

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

650963b

### PR DESCRIPTION
**Pull request by Akctarus**
Closes #6639 
closes #6783
closes #6893

### CODE REVIEW

**Review by SarahBellaha — COMMENTED** [review]
Tested and the issue #6639 is fixed.
However, while i was testing, i found another bug that can be adressed in the same PR (as discussed with @clarani  & @Akctarus ).
When we have several consecutive zones with the same power restriction (or none), we have an assert check error from the backend.
Capture d’écran 2024-02-28 à 10 59 14
Capture d’écran 2024-02-28 à 11 14 58

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts [hunk 1]
```diff
@@ -3,23 +3,37 @@ import type { Dispatch } from 'redux';
...
+        value: currentObj.value,
+      };
+      const previousObj = { ...mergedArray[mergedArray.length - 1] };
+      previousObj.end = mergedObj.end;
+      mergedArray[mergedArray.length - 1] = previousObj;
+      return mergedArray;
+    }
+    return mergedArray.concat(currentObj);
+  }, []);
+}
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: Nice job, some remarks on this function:
- rename it so it's more explicit: mergeConsistentIdenticalObjects -> mergeIdenticalNeighbours ? and maybe add a comment to explain what this function does
- rename the variables: data -> powerRestrictionRanges, currentObj -> currentRange, mergedObj -> mergedRange, previousObj -> previousRange
- use early return: if index === 0 or prevValue !== currentValue, directly return the array with the new value at the end
- use a variable to store the previous value : prevRange = result[result.length - 1] and use it rather than the previous element in array
- use the function replaceElementAtIndex from utils/array rather than modify mergedArray (l21). In js, we avoid modifying an existing object, it's better to create a new one
- the new previous object has only its end changing, so you can create it like this: 
  ```
      const newPreviousRange = {
        ...previousRange,
        end: currentObj.end,
      };
  ```

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: fixed !

**Review by SarahBellaha — APPROVED** [review]
Nice, lgtm :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts [hunk 2]
```diff
@@ -3,23 +3,48 @@ import type { Dispatch } from 'redux';
...
 import type { OsrdConfState } from 'reducers/osrdconf/consts';
+import { replaceElementAtIndex } from 'utils/array';
 import { kmhToMs } from 'utils/physics';
 import { time2sec } from 'utils/timeManipulation';
 
+// When two consecutive segments have the same power restriction code, they are merged into one. This prevents the back from returning an error.
+function mergeIdenticalNeighbours(powerRestrictionRanges: PowerRestrictionRange[]) {
+  return powerRestrictionRanges.reduce(
+    (mergedArray: PowerRestrictionRange[], currentRange, index, array) => {
+      if (index === 0 || currentRange.value !== array[index - 1].value) {
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: Here you can directly use powerRestrictionRanges
```suggestion
      if (index === 0 || currentRange.value !== powerRestrictionRanges[index - 1].value) {
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts [hunk 3]
```diff
@@ -3,23 +3,48 @@ import type { Dispatch } from 'redux';
...
+      const mergedRange = {
+        begin: prevRange.begin,
+        end: currentRange.end,
+        value: currentRange.value,
+      };
+
+      const newPreviousRange = {
+        ...prevRange,
+        end: mergedRange.end,
+      };
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: You can simplify like this
```suggestion
      const previousRange = mergedArray[mergedArray.length - 1];
      const newPreviousRange = {
        ...prevRange,
        end: currentRange.end,
      };
```

File: front/src/common/IntervalsDataViz/dataviz.tsx
Comment (clarani) [inline front/src/common/IntervalsDataViz/dataviz.tsx:1]: Nice, thanks :pray:

File: front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx [hunk 4]
```diff
@@ -15,6 +15,7 @@ type IntervalsEditorFormProps = {
   setData: (newData: IntervalItem[]) => void;
   setSelectedIntervalIndex: (selectedIntervalIndex: number) => void;
   totalLength: number;
+  defaultValue?: string;
```
Comment (clarani) [inline front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx]: Why do you authorize undefined ? I think it's better for now to make it required. Also, you can make it either a string or a number
```suggestion
  defaultValue: string | number;
```

File: front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx [hunk 5]
```diff
@@ -47,7 +49,10 @@ const IntervalsEditorCommonForm = ({
         context,
         false
       );
-      const fixedResults = fixLinearMetadataItems(result?.filter(notEmpty), totalLength);
+      const fixedResults = fixLinearMetadataItems(result?.filter(notEmpty), totalLength, {
```
Comment (clarani) [inline front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx]: Remove the ?
```suggestion
      const fixedResults = fixLinearMetadataItems(result.filter(notEmpty), totalLength, {
```

File: front/src/common/IntervalsEditor/IntervalsEditor.tsx [hunk 6]
```diff
@@ -315,6 +315,7 @@ const IntervalsEditor = (props: IntervalsEditorProps) => {
               setData={setData}
               setSelectedIntervalIndex={setSelected}
               totalLength={totalLength}
+              defaultValue={`${defaultValue}`}
```
Comment (clarani) [inline front/src/common/IntervalsEditor/IntervalsEditor.tsx]: Change the type and you can remove the cast to string :)
```suggestion
              defaultValue={defaultValue}
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx [hunk 7]
```diff
@@ -185,6 +187,13 @@ const PowerRestrictionsSelector = ({
     }
   }, [powerRestrictionRanges]);
 
+  const formattedIntervals = useMemo(
+    () => formatIntervals(formattedPathElectrificationRanges, powerRestrictionRanges),
+    [formattedPathElectrificationRanges, powerRestrictionRanges]
+  );
+
+  const [useFormattedIntervals, setUseFormattedIntervals] = useState(true);
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx]: You can replace all this code by a useEffect, it's simpler :+1: 
```suggestion
   useEffect(() => {
    const formattedPowerRestrictionRanges = formatIntervals(
      formattedPathElectrificationRanges,
      powerRestrictionRanges
    );
    console.log({ powerRestrictionRanges, formattedPowerRestrictionRanges });
    dispatch(updatePowerRestrictionRanges(formattedPowerRestrictionRanges));
  }, [formattedPathElectrificationRanges]);
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx [hunk 8]
```diff
@@ -196,12 +205,15 @@ const PowerRestrictionsSelector = ({
...
               additionalData={formattedPathElectrificationRanges}
               intervalType={INTERVAL_TYPES.SELECT}
-              data={powerRestrictionRanges}
+              data={useFormattedIntervals ? formattedIntervals : powerRestrictionRanges}
               defaultValue={NO_POWER_RESTRICTION}
               emptyValue={NO_POWER_RESTRICTION}
               operationalPoints={electrificationChangePoints}
               selectOptions={powerRestrictionOptions}
-              setData={editPowerRestrictionRanges}
+              setData={(data) => {
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx]: Keep this once you have added the useEffect
```suggestion
              setData={editPowerRestrictionRanges}
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts:1]: The name of the file is not the name of the function, can you rename it ? Also, precise that it is about power restrictions

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts [hunk 9]
```diff
@@ -0,0 +1,37 @@
+import type { PowerRestrictionRange } from 'applications/operationalStudies/consts';
+import type { RangedValue } from 'common/api/osrdEditoastApi';
+
+export default function formatIntervals(
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: Maybe add a comment to describe what this function does

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+  formattedPathElectrificationRanges.forEach((electrificationRange) => {
+    const overlappingRanges = powerRestrictionRanges.filter(
+      (range) => electrificationRange.end > range.begin && electrificationRange.begin < range.end
+    );
+
+    if (overlappingRanges.length === 0) {
+      formattedRanges.push({
+        begin: electrificationRange.begin,
+        end: electrificationRange.end,
+        value: 'NO_POWER_RESTRICTION',
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: Use the const which is defined in PowerRestrictionsSelector
```suggestion
        value: NO_POWER_RESTRICTION
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts:1]: Nice function !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatPowerRestrictionRanges.ts [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+      const mergedRange = {
+        begin: prevRange.begin,
+        end: currentRange.end,
+        value: currentRange.value,
+      };
+
+      const newPreviousRange = {
+        ...prevRange,
+        end: mergedRange.end,
+      };
```
Comment (clarani) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatPowerRestrictionRanges.ts]:
```suggestion
      const newPreviousRange = {
        ...prevRange,
        end: currentRange.end,
      };
```

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/commonConfBuilder.ts [hunk 12]
```diff
@@ -119,6 +119,35 @@ export default function commonConfBuilder() {
...
     ],
 
+    buildFormattedPathElectrificationRanges: (): RangedValue[] => [
+      { begin: 0, end: 10, value: '1500V' },
+      { begin: 10, end: 20, value: '25000V' },
+      { begin: 20, end: 25, value: '1500V' },
+    ],
+
+    buildFormattedPowerRestrictionRanges: (): PowerRestrictionRange[] => [
+      { begin: 0, end: 10, value: 'NO_POWER_RESTRICTION' },
```
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/__tests__/commonConfBuilder.ts]: Use the const defined in PowerRestrictionSelector
```suggestion
      { begin: 0, end: 10, value: NO_POWER_RESTRICTION },
```

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts
Comment (clarani) [inline front/src/reducers/osrdconf/osrdConfCommon/__tests__/utils.ts:1]: Nice test, thanks !

**Review by clarani — COMMENTED** [review]
Left some comments, but it's almost good for me

File: front/src/reducers/osrdconf/osrdConfCommon/__tests__/commonConfBuilder.ts (hunk 12 above)
Comment (Akctarus) [reply front/src/reducers/osrdconf/osrdConfCommon/__tests__/commonConfBuilder.ts]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts (hunk 2 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts (hunk 3 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatConf.ts]: fixed

File: front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx (hunk 4 above)
Comment (Akctarus) [reply front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx]: fixed ! ty

File: front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx (hunk 5 above)
Comment (Akctarus) [reply front/src/common/IntervalsEditor/IntervalsEditorCommonForm.tsx]: fixed

File: front/src/common/IntervalsEditor/IntervalsEditor.tsx (hunk 6 above)
Comment (Akctarus) [reply front/src/common/IntervalsEditor/IntervalsEditor.tsx]: nice ! fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts:1]: done !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts (hunk 9 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts (hunk 10 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatPowerRestrictionRanges.ts (hunk 11 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/formatPowerRestrictionRanges.ts]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx (hunk 8 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx (hunk 7 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/PowerRestrictionsSelector.tsx]: fixed

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts (hunk 10 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: I think you forgot this one !

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveParamSelectors.tsx
Comment (clarani) [inline front/src/modules/rollingStock/components/RollingStockEditor/CurveParamSelectors.tsx:1]: Why did you change that ? I think it's not related to our bug ? Same for the translations I think ?

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark: I left only 2 comments, I think it's ok for this time but we should avoid mixing unrelated changes :)

File: front/src/modules/rollingStock/components/RollingStockEditor/CurveParamSelectors.tsx
Comment (Akctarus) [reply front/src/modules/rollingStock/components/RollingStockEditor/CurveParamSelectors.tsx:1]: it was a mistake, I pushed on the wrong branch, thanks for seeing it

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts (hunk 10 above)
Comment (Akctarus) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/displayIntervals.ts]: done, there was a dependency cycle, but it was fixed by the creation of a consts file
