### PR TITLE
front: fix speed limit and lpv layer display

### LINKED ISSUE #4983: Speed limit with no composition code are all dark
### What happened?

All Speed limit with no composition code are black on the map.

2023-09-06-164225_954x839_scrot

### What did you expect to happen?

We expect to have different colors in connection with the speed.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map viewer (or somewhere with the map)
2. Display the speed limit with no composition code

### What operating system, browser and environment are you using?

- **Browser**: Chromium v105
- **OS**: Nixos v22.11
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

3e1b54cb

### LINKED ISSUE #5287: front: LPV are displayed without color
Image

### PR DESCRIPTION
**Pull request by SarahBellaha**
Close #4983 
Close #5287

### CODE REVIEW

File: front/src/applications/editor/components/LayersModal.tsx [hunk 1]
```diff
@@ -59,6 +57,8 @@ const LayersModal: FC<LayersModalProps> = ({
   const { layersSettings } = useSelector(getMap);
   const [selectedLayers, setSelectedLayers] = useState<Set<LayerType>>(initialLayers);
   const infraID = useSelector(getInfraID);
+  const DEFAULT_SPEED_LIMIT_TAG = t('map-settings:noSpeedLimitByTag');
```
Comment (clarani) [inline front/src/applications/editor/components/LayersModal.tsx]: You can useMemo it :)

File: front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx [hunk 2]
```diff
@@ -51,18 +52,20 @@ const FormatSwitch = ({ name, icon: IconComponent, color = '', disabled }: Forma
...
         })
       );
+    }
   };
 
   useEffect(() => {
-    if (tagsList) setSpeedLimitsTags([t('noSpeedLimitByTag').toString(), ...tagsList]);
+    if (tagsList) setSpeedLimitsTags([DEFAULT_SPEED_LIMIT_TAG, ...tagsList]);
     else setSpeedLimitsTags(undefined);
   }, [tagsList]);
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx]: You can replace this useEffect by a useMemo const
```suggestion
  const speedLimitsTags = useMemo(
    () => (tagsList ? [DEFAULT_SPEED_LIMIT_TAG, ...tagsList] : undefined),
    [tagsList]
  );
```

File: front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx [hunk 3]
```diff
@@ -51,18 +52,20 @@ const FormatSwitch = ({ name, icon: IconComponent, color = '', disabled }: Forma
     );
   };
 
-  const dispatchSetSpeedLimitsTags = (item?: string) => {
-    if (item)
+  const dispatchSetSpeedLimitsTags = (item?: string | null) => {
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx]: Can you change in SelectImproveSNCF the type of onChange => `onChange: (value: T) => void;` and then you can change the signature of this function:

```suggestion
  const dispatchSetSpeedLimitsTags = (item: string) => {
```

**Review by clarani — COMMENTED** [review]
Almost good for me, very nice fix !

File: front/src/applications/editor/components/LayersModal.tsx [hunk 4]
```diff
@@ -57,11 +57,14 @@ const LayersModal: FC<LayersModalProps> = ({
...
   const [selectedLayers, setSelectedLayers] = useState<Set<LayerType>>(initialLayers);
   const infraID = useSelector(getInfraID);
-  const DEFAULT_SPEED_LIMIT_TAG = t('map-settings:noSpeedLimitByTag');
 
   const { data: speedLimitTags } = osrdEditoastApi.endpoints.getInfraByIdSpeedLimitTags.useQuery({
     id: infraID as number,
   });
+  const DEFAULT_SPEED_LIMIT_TAG = useMemo(
+    () => t('map-settings:noSpeedLimitByTag'),
+    [speedLimitTags]
```
Comment (clarani) [inline front/src/applications/editor/components/LayersModal.tsx]:
```suggestion
    [t]
```

File: front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx [hunk 5]
```diff
@@ -1,4 +1,4 @@
-import React, { useEffect, useState } from 'react';
+import React, { useEffect, useMemo, useState } from 'react';
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx]: Linter warning

File: front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx [hunk 6]
```diff
@@ -41,7 +40,7 @@ const FormatSwitch = ({ name, icon: IconComponent, color = '', disabled }: Forma
     }
   );
 
-  const [speedLimitsTags, setSpeedLimitsTags] = useState<string[] | undefined>(undefined);
+  const DEFAULT_SPEED_LIMIT_TAG = useMemo(() => t('map-settings:noSpeedLimitByTag'), [tagsList]);
```
Comment (clarani) [inline front/src/common/Map/Settings/MapSettingsSpeedLimits.tsx]:
```suggestion
  const DEFAULT_SPEED_LIMIT_TAG = useMemo(() => t('map-settings:noSpeedLimitByTag'), [t]);
```

**Review by clarani — APPROVED** [review]
LGTM, only 3 small issues, but you can correct them and then squash your fixups :) :white_check_mark:

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:
