### PR TITLE
editoast: accept trigrams with 4 chars or more

### LINKED ISSUE #16212: editoast doesn't accept operational points with more than 3 characters
### What happened?

editoast fails to load infras which have at least one operational point with a trigram larger than 3 characters

```
  2026-04-13T08:23:43.542183Z ERROR editoast::error: [editoast:ModelError] an error occurred while querying the database: value too long for type character varying(3): disabled backtrace
```

example infra: [sava.json](https://github.com/user-attachments/files/26669755/sava.json)

### What did you expect to happen?

see https://github.com/OpenRailAssociation/osrd/pull/16209#discussion_r3071435118

tldr trigrams can have more than 3 characters

### How can we reproduce it (as minimally and precisely as possible)?

Load the infra above in the infra editor

### On which environments the bug occurs?

Dev (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

8b8044f0676d93a7cbd4ad28a901eb07bec00542

### PR DESCRIPTION
**Pull request by hhirtz**
in other countries trigrams can have more than three characters. For example the Deutsche Bahn has "trigrams" (soon to be "main_code"s in OSRD) of 2 to 5 characters:

https://www.dbinfrago.com/web/schienennetz/betrieb/allgemeine-betriebsinformationen/betriebsstellen-12592996

Here's a small-infra fork with unorthodox values for trigrams: https://github.com/user-attachments/files/26669755/sava.json

I don't think the front is fully ready for this change though. Should we merge this and fix the front later? e.g.

screen-20260413112827

even 5-char trigrams overflow into the name of the OP:

screen-20260413113017

Closes https://github.com/OpenRailAssociation/osrd/issues/16212

### CODE REVIEW

**Review by emersion — APPROVED** [review]
LGTM!

File: editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+ALTER TABLE search_operational_point
+ALTER COLUMN trigram TYPE varchar(255);
```
Comment (woshilapin) [inline editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql:2]: How about we use `TEXT` instead of `VARCHAR(255)`?

Comment (emersion) [reply editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql:2]: `VARCHAR(255)` has an upside: it enforces that the string size is reasonable. Something longer than 255 is either not a trigram (so erroring out lets the user know that something is wrong) or an abuse (a very big string to cause slowdowns in the whole app, although the threat model here won't make this a real issue).

Note, `VARCHAR` is used for many other fields in editoast.

Comment (hhirtz) [reply editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql:2]: agreed with emersion. for reference the long trigram with multiple sentences is only 128 chars (140 bytes because of emojis), so 255 is a reasonable limit i think.

Comment (woshilapin) [reply editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql:2]: The fact that it is used in other places of `editoast` is not necessarily a good discriminant (maybe we should change them). And  apart from the fact that the threat model is probably low, it does mean that we allow huge payload to go through `editoast` and only at the DB level, we check for the size. Shouldn't we do that much earlier (real question, not ironic one, I don't have much experience on that, what are usually the practices)?

Comment (hhirtz) [reply editoast/migrations/2026-04-13-091021-0000_trigram_arbitrary_length/up.sql:2]: We can also add a check upfront if needed.. or rely on a Web Application Firewall to do it, but editoast is not the only way to insert corrupt data into postgres. there's pg_restore, psql, other services talking directly to it... so also having a check at the database level is useful i think.

**Review by woshilapin — APPROVED** [review]
