### PR TITLE
front: fix grid margin component for list with 1 element

### LINKED ISSUE #2628: stdcm: front: Grid margin component offers a dropdown list with only 1 element
The grid margin component in stdcm goes as follows :

image

For the moment we only enable grid margin to be set as a fixed time in seconds, so the dropdown list should be removed, or at least disabled.

### PR DESCRIPTION
**Pull request by Yohh**
close #2628

### CODE REVIEW

**Review by alexandredamiron — DISMISSED** [review]

File: front/src/applications/osrd/components/Simulation/Allowances/StandardAllowanceDefault.js [hunk 1]
```diff
@@ -219,14 +220,28 @@ export default function StandardAllowanceDefault(props) {
...
+                options={allowanceTypes}
+                handleType={handleType}
+                value={value.value}
+                type={value.type}
+                sm
+              />
+            ) : (
+              <InputSNCF
+                id="standardAllowanceType"
+                label={allowanceTypes[0].label}
```
Comment (alexandredamiron) [inline front/src/applications/osrd/components/Simulation/Allowances/StandardAllowanceDefault.js]: Beware, allowanceTypes does not have a default value. This will throw an exception if allowanceTypes has a size of zero

Comment (Yohh) [reply front/src/applications/osrd/components/Simulation/Allowances/StandardAllowanceDefault.js]: not sure about the kind of display in case allowanceType is empty, but now it works

Comment (Yohh) [reply front/src/applications/osrd/components/Simulation/Allowances/StandardAllowanceDefault.js]: done

**Review by alexandredamiron — APPROVED** [review]
