### PR TITLE
front: fix reload timetable on import

### LINKED ISSUE #4899: front: import: after trainschedule calculations, timetable is not updated and remains empty
After trainschedule calculations, timetable is not updated and remains empty

Image

Linux / Firefox
OSRD a7bf4b66

### PR DESCRIPTION
**Pull request by clarani**
closes #4899

### CODE REVIEW

File: front/src/modules/trainschedule/components/Timetable/Timetable.tsx [hunk 1]
```diff
@@ -78,20 +69,60 @@ export default function Timetable({
...
+
+  const isTrainFiltered = (train: ScheduledTrain, debounce?: string): boolean => {
+    if (debounce) {
+      return (
+        !train.train_name.toLowerCase().includes(debouncedTerm.toLowerCase()) &&
+        !train.labels.join('').toLowerCase().includes(debouncedTerm.toLowerCase())
+      );
+    }
+    return false;
+  };
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/Timetable/Timetable.tsx]: Could this be done like that or the readability is bad ?
```suggestion
  const isTrainFiltered = (train: ScheduledTrain, debounce?: string): boolean => 
  !!debounce 
  && !train.train_name.toLowerCase().includes(debouncedTerm.toLowerCase()) 
  && !train.labels.join('').toLowerCase().includes(debouncedTerm.toLowerCase());
```

File: front/src/modules/trainschedule/components/Timetable/Timetable.tsx [hunk 2]
```diff
@@ -78,20 +69,60 @@ export default function Timetable({
...
   };
 
   const refreshTimeTable = async () => {
-    dispatch(updateReloadTimetable(true));
-    const currentTimetable = await getTimetableWithTrainSchedulesDetails({
-      id: timetableID as number,
-    }).unwrap();
-    getSimulationResults(currentTimetable);
+    refetchTimetable();
     dispatch(updateReloadTimetable(false));
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/Timetable/Timetable.tsx]: You can remove that line and use directly refetchTimetable() instead of refreshTimetable() every where in the component (and remove refreshTimetable function)

**Review by SharglutDev — COMMENTED** [review]
Insane refacto of Timetable.tsx, great job ! o// (wanted to drop the useLazyQuery for so long)

Not sure if you want to do that in this PR but now that you added `timetable` in  `postTrainSchedule` `invalidatesTags`, you can drop the dispatch of `updateReloadTimetable` in SubmitConfAdd file.

Just left one comment.
Tested in local and everything works great !

By the way, if you want to improve the rest of the application with another PR, now that you made this useQuery refacto you could add `timetable` on `invalidatesTags` on patch and both delete trainSchedule endpoints and remove `updateReloadTimetable` dispatch everywhere :)

**Review by nicolaswurtz — APPROVED** [review]

File: front/src/modules/trainschedule/components/Timetable/Timetable.tsx (hunk 1 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/Timetable/Timetable.tsx]: Argh, I think it not very readable :/ I would rather keep it like this, if you are fine with it

File: front/src/modules/trainschedule/components/Timetable/Timetable.tsx (hunk 2 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/Timetable/Timetable.tsx]: Done !

**Review by SharglutDev — APPROVED** [review]
Lgtm !

**Review by leovalais — APPROVED** [review]
