### PR TITLE
editoast: fix track range openapi conflict

### LINKED ISSUE #12730: editoast: conflicting `TrackRange` schemas in openapi.yaml
### What happened?

We have two TrackRange types:
* the schema
* the structure use with Core

They are both needed in the OpenAPI (models use the schema, but some API responses forward those from Core, eg: PathPropertiesInput). We either need the core definition to be named `CoreTrackRange` in the OpenAPI, or stop exposing `core_client::TrackRange` and perform a conversion step from the schema.

### What did you expect to happen?

not conflict

### How can we reproduce it (as minimally and precisely as possible)?

open code: 2 TrackRange
open open api: 1 TrackRange
oh no

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

dev

> [!NOTE]
> Minor severity since the Core TrackRange is currently the one that's use and it's a superset of `schema::TrackRange`. Also numeric types are converted to `number` in TS so it doesn't bother the frontend.

### PR DESCRIPTION
**Pull request by Wadjetz**
fix #12730
Rename core_client::pathfinding::TrackRange to CoreTrackRange and fix the frontend

- [x] Fix the conflict with simple rename solution

### CODE REVIEW

**Review by SharglutDev — APPROVED** [review]
Lgtm for front (not tested)

**Review by flomonster — APPROVED** [review]
LGTM

File: editoast/core_client/src/pathfinding.rs [hunk 1]
```diff
@@ -160,7 +160,8 @@ pub enum PathfindingNotFound {
 /// `begin` is always less than `end`.
 #[editoast_derive::openapi_schema]
 #[derive(Serialize, Deserialize, Clone, Debug, ToSchema, Hash, PartialEq, Eq)]
-pub struct TrackRange {
+#[schema(as = CoreTrackRange)]
+pub struct CoreTrackRange {
```
Comment (leovalais) [inline editoast/core_client/src/pathfinding.rs]:
```suggestion
pub struct TrackRange {
```

There's no need for a prefix, the crate name acts as it. In situations where there is a conflict or a possible confusion, let's just prefix it with the full path `core_client::TrackRange`? OpenAPI components do not have namespaces though, so the prefix's necessary there, like you did with `#[schema(as =`.

**Review by leovalais — CHANGES_REQUESTED** [review]
Thanks for the fix! Though only the OpenAPI definition really needs a name change, not the Rust type itself imo

File: editoast/core_client/src/pathfinding.rs (hunk 1 above)
Comment (Wadjetz) [reply editoast/core_client/src/pathfinding.rs]: @leovalais I made the changes

Comment (flomonster) [reply editoast/core_client/src/pathfinding.rs]: This change requires to use `#[schema(value_type = Vec<CoreTrackRange>)]`? If so, I'm not a fan, as it makes it easy to forget / error prone.

Comment (leovalais) [reply editoast/core_client/src/pathfinding.rs]: After discussing with @flomonster and @woshilapin, let's keep the `#[schema()]` if you're fine with it.

**Review by leovalais — APPROVED** [review]
Thanks for fixing this!

File: editoast/core_client/src/pathfinding.rs (hunk 1 above)
Comment (Wadjetz) [reply editoast/core_client/src/pathfinding.rs]: I'm good with the `#[schema()]` 👍
