### PR TITLE
front: fix project image not displayed in stdcm

### LINKED ISSUE #3952: front: project image in stdcm not displayed
### What happened?

In STDCM, the project list doesn't display the project image.

Capture d’écran du 2023-04-19 14-22-18

### What did you expect to happen?

The project images should be displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Load Projects

### What operating system, browser and environment are you using?

- **Browser**: Chromium
- **OS**: Ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

529575f6

### PR DESCRIPTION
**Pull request by SharglutDev**
close #3952

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Good

File: front/src/common/ScenarioExplorator/ScenarioExploratorProject2Image.tsx [hunk 1]
```diff
@@ -1,16 +1,15 @@
...
 export default function Project2Image({ project }: MiniCardsImageProps) {
   const [imageUrl, setImageUrl] = useState<string>();
 
   useMemo(async () => {
-    if (!project || !project.image_url) return;
+    if (!project || !project.image) return;
     try {
-      const image = await get(`${PROJECTS_URI}${project.id}/image/`, { responseType: 'blob' });
-      if (image) setImageUrl(URL.createObjectURL(image));
+      const blobImage = await getDocument(project.image as number);
```
Comment (Math-R) [inline front/src/common/ScenarioExplorator/ScenarioExploratorProject2Image.tsx:11]: If you cast it as number, shouldn't it be imageID in place of blobImage?

**Review by Math-R — CHANGES_REQUESTED** [review]

**Review by Math-R — APPROVED** [review]

**Comment by Math-R** [comment]
LGTM !
