### PR TITLE
core: stdcm: integrate step tracker into heuristic computation

### LINKED ISSUE #11285: core: stdcm: use `StepTracker` in `STDCMHeuristic`
Should have been part of https://github.com/OpenRailAssociation/osrd/issues/8974, requirement for overtakes. 

The heuristic relies on the number of steps on the path, which will become dynamic.

### LINKED ISSUE #11290: core: stdcm: requests take way longer than they should, including timeouts
### What happened?

We have an off-by-one issue with the stdcm heuristic, causing it to be effectively "turned off" during the last section of the path. This results in lots of timeouts and very slow computations.

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Run any kind of request on a large infra. Also the logged progress tracker is broken. 

### On which environments the bug occurs?

Recette (SNCF), Local, Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6188f9b5267087ea5a55db7b7ffe0de9c37f90b3

### PR DESCRIPTION
**Pull request by eckter**
Follow-up of https://github.com/OpenRailAssociation/osrd/pull/11286

Fix https://github.com/OpenRailAssociation/osrd/issues/11285

Fix https://github.com/OpenRailAssociation/osrd/issues/11290

Can be reviewed by commit:

1. Small refactoring to have a proper class instead of a typealias on a function type. No functional change but lots of code moving, can interfere when reading the diff all commits at once
2. Use `StepTracker` instead of raw number of passed steps as function input
3. Adapt unit tests

Because the new tests use an `InfraExplorer` directly, the previous bug would have been catched there (it was an "integration" bug between infra explorer / step tracker / heuristic).

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt [hunk 1]
```diff
@@ -20,12 +20,84 @@ import kotlin.math.min
...
+            )
+
+        val timeAfterStartOfLastBlock =
+            remainingTimeEstimations[expectedIndex][allBlocks.last()]
+                ?: return Double.POSITIVE_INFINITY
+
+        // Compute the time it takes from the current point until the start
+        // of the last block of the lookahead, then from that point the destination.
+        var timeUntilStartOfLastBlock = 0.0
+        for (j in 0 until allBlocks.size - 1) timeUntilStartOfLastBlock +=
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: Any way to change the format here? Either EoL or brackets?

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt [hunk 2]
```diff
@@ -71,35 +69,23 @@ data class STDCMAStarHeuristic(
...
-                // Move on to the next block
-                blockIndex++
-                currentOffset = Offset(0.meters)
-            }
+        val stepTrackerCopy = stepTracker.clone()
+        for (block in blocks) {
+            stepTrackerCopy.moveForward(block, Offset.zero(), blockInfra.getBlockLength(block))
         }
+        val nPlannedSteps =
+            stepTrackerCopy.getSeenSteps().take(stepTrackerCopy.nStepsExcludingLookahead).count {
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: Might be worth to add a `getReachedSteps()` in `StepTracker`.
-> `stepTrackerCopy.getReachedSteps().count { it.isPlanned }`

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt [hunk 3]
```diff
@@ -48,6 +48,7 @@ data class STDCMAStarHeuristic(
                 allBlocks.subList(0, allBlocks.size - 1),
                 stepTracker,
             )
+        if (expectedIndex >= remainingTimeEstimations.size) return 0.0
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt:51]: Should probably be in one of the previous commits.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt (hunk 1 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/11289/commits/b525d5556e33cb0c556478e735010b499a285bd8

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt (hunk 2 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/pull/11289/commits/1edeb4e15c8bbd4a9256b3fc5dfe80ddc5000191

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt (hunk 3 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt:51]: Fixed, but I couldn't do that with a fixup, I ammended the commits

**Review by Erashin — APPROVED** [review]

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt [hunk 4]
```diff
@@ -20,14 +20,71 @@ import kotlin.math.min
...
+        allBlocks.addAll(lookahead)
+
+        // We don't consider the time of the last lookahead block to avoid issues
+        // if it contains the destination, and we don't need it (the destination is
+        // already locked-in).
+
+        // Account for the steps that will be passed in the lookahead
+        val expectedIndex =
+            getExpectedStepIndex(
+                allBlocks.subList(0, allBlocks.size - 1),
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: nit:
```suggestion
                allBlocks.removeLast()
```

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/preprocessing/STDCMHeuristicTests.kt [hunk 5]
```diff
@@ -227,11 +219,25 @@ class STDCMHeuristicTests {
...
+                appendOnlyLinkedListOf(),
+                SpacingRequirementAutomaton(
+                    infra,
+                    infra.fullInfra().loadedSignalInfra,
+                    infra,
+                    infra.fullInfra().signalingSimulator,
+                    IncrementalRequirementEnvelopeAdapter(REALISTIC_FAST_TRAIN, null, false),
+                    infraExplorer.getIncrementalPath(),
+                ),
+                REALISTIC_FAST_TRAIN,
```
Comment (bougue-pe) [inline core/src/test/kotlin/fr/sncf/osrd/stdcm/preprocessing/STDCMHeuristicTests.kt]: Not sure that it matters, but I'm curious about the change from `STANDARD_TRAIN` to `REALISTIC_FAST_TRAIN`.

**Review by bougue-pe — APPROVED** [review]

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt (hunk 4 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/STDCMHeuristic.kt]: Fixed in https://github.com/OpenRailAssociation/osrd/commit/cefdaaf8289288725dfc6c096d5808ec96089ebf

Though I needed `.dropLast()` as I still need to return the value here and not just modify the list

File: core/src/test/kotlin/fr/sncf/osrd/stdcm/preprocessing/STDCMHeuristicTests.kt (hunk 5 above)
Comment (eckter) [reply core/src/test/kotlin/fr/sncf/osrd/stdcm/preprocessing/STDCMHeuristicTests.kt]: I had just picked the first one suggested by my IDE. But I've changed it to `STANDARD_TRAIN` for consistency in https://github.com/OpenRailAssociation/osrd/commit/99d5f7c6b2a10e45314909df1da68beaf75d9108
