### PR TITLE
front: fix capitalized text in stdcm table results

### LINKED ISSUE #9525: front: typo in simulation result
### What happened?

Image
"De" and "Réf" should not be capitalized (see mock-up)

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. go to STDCM
2. launch a simulation
3. go to the simulation result table

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

86ad640

### PR DESCRIPTION
**Pull request by Akctarus**
closes #9525

### CODE REVIEW

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested

**Review by SarahBellaha — APPROVED** [review]
LGTM

File: front/src/applications/stdcm/components/StdcmResults/StdcmResultsTable.tsx [hunk 1]
```diff
@@ -43,7 +44,7 @@ const StcdmResultsTable = ({
             <th>{t('passageStop')}</th>
             <th>{t('startStop')}</th>
             <th className="weight">{t('weight')}</th>
-            <th>{t('refEngine')}</th>
+            <th>{capitalizeFirstLetter(t('refEngine'))}</th>
```
Comment (emersion) [inline front/src/applications/stdcm/components/StdcmResults/StdcmResultsTable.tsx]: Instead of post-processing the translated strings, could we update the strings in the translation files instead?

Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResultsTable.tsx]: since it only used once, yes we can

File: front/src/styles/scss/applications/stdcm/_results.scss [hunk 2]
```diff
@@ -159,6 +159,9 @@
             padding-bottom: 0.313rem;
             vertical-align: middle;
           }
+          th:last-child {
+            text-transform: none;
```
Comment (emersion) [inline front/src/styles/scss/applications/stdcm/_results.scss:163]: I'd prefer not to have a special case for the only header which happens to have multiple words: in the future, if one of the other translations get updated with a string which contains multiple words, `text-transform: capitalize` will not do what we want.

So maybe we can drop `text-transform: capitalize` and always just capitalize everything the way we want in the translation files?

Comment (Akctarus) [reply front/src/styles/scss/applications/stdcm/_results.scss:163]: We use these translations in another file and we need them to be in lowercase there :(

Comment (emersion) [reply front/src/styles/scss/applications/stdcm/_results.scss:163]: Maybe we can use `text-transform: lowercase` for the other place where the translations are used?

It's always easier to go from capitalized to full lowercase then the reverse.

Comment (Akctarus) [reply front/src/styles/scss/applications/stdcm/_results.scss:163]: This will be done in a future PR refactor of the simulation sheet

File: front/src/applications/stdcm/components/StdcmResults/StdcmResultsTable.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResultsTable.tsx]: fixed

File: front/src/styles/scss/applications/stdcm/_results.scss (hunk 2 above)
Comment (emersion) [reply front/src/styles/scss/applications/stdcm/_results.scss:163]: Alright!

**Review by emersion — APPROVED** [review]
