### PR TITLE
front: fix empty pathstepitem in itinerary modal

### LINKED ISSUE #15412: Itinerary modal : path steps are not displayed in the form
### What happened?

When editing a train and switching to the new itinerary modal, the path steps are not displayed in the form : 

Image

### What did you expect to happen?

We should see them in the form

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Edit a train
3. Go on the new itinerary modal

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by RomainValls**
closes #15412

### CODE REVIEW

File: front/src/applications/operationalStudies/hooks/useOperationalPointSearch.ts [hunk 1]
```diff
@@ -47,7 +47,9 @@ export const useOperationalPointSearch = ({
   const getInputForStep = useCallback(
     (stepId: string) => {
       const isEditing = isEditingByStepId[stepId] ?? true;
-      return isEditing ? (draftByStepId[stepId] ?? '') : (displayByStepId[stepId] ?? '');
+      return isEditing
+        ? (draftByStepId[stepId] ?? undefined)
+        : (displayByStepId[stepId] ?? undefined);
```
Comment (Yohh) [inline front/src/applications/operationalStudies/hooks/useOperationalPointSearch.ts]:
```suggestion
      return isEditing
        ? (draftByStepId[stepId])
        : (displayByStepId[stepId]);
```

Comment (RomainValls) [reply front/src/applications/operationalStudies/hooks/useOperationalPointSearch.ts]: thanks !

**Review by Yohh — APPROVED** [review]

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank for the hot fix.

> [!NOTE]
> Could be nice to add a description in the commit for more context about that
