### PR TITLE
front: fix update coordinates when change ch code

### LINKED ISSUE #10310: front: stdcm: origin and destination markers are both at BV and on the wrong track
### What happened?

Tryied to look for a STDCM between BGB BV and BGB P1 but the map is showing both marker at the BV:
Image

And the result was this:
Image

### What did you expect to happen?

I'm expecting the markers to be on the right PR and on the right track once the result is found.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce description

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

fdfd8ac

### PR DESCRIPTION
**Pull request by kmer2016**
closes #10310

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx [hunk 1]
```diff
@@ -16,7 +16,8 @@ type StdcmOperationalPointProps = {
   disabled?: boolean;
 };
 
-type Option = StdcmPathStep['location'] & { label: string };
+type CIOption = StdcmPathStep['location'] & { label: string };
+type CHOption = { label: string; id: string; coordinates: [number, number] };
```
Comment (SarahBellaha) [inline front/src/applications/stdcm/components/StdcmForm/StdcmOperationalPoint.tsx:20]:
```suggestion
type CHOption = { label: string; id: string; coordinates: GeoJsonPointValue };
```
Can't we use this type ?

**Review by Math-R — APPROVED** [review]
lgtm =)
