### PR TITLE
front: use the colour of the exception in the get

### LINKED ISSUE #12981: paced train: space time chart: exception with category silo is still drawn with the model's color
### What happened?

I edited an occurence with a green train category but it's drawn in red like the rest of the occurence

Image

### What did you expect to happen?

I expected the occurence to be drawn in green 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario with this [timetable](https://github.com/user-attachments/files/22026190/timetable.22.json)
2. See that the occurence isn't drawn in green

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

d506352

### PR DESCRIPTION
**Pull request by theocrsb**
closes https://github.com/OpenRailAssociation/osrd/issues/12981

### CODE REVIEW

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/getPathStyle.ts [hunk 1]
```diff
@@ -30,8 +34,19 @@ const getPathStyle = (
...
-  const category = item?.category;
+
+  const occurrenceIndex = isOccurrenceId(train.id)
+    ? extractOccurrenceIndexFromOccurrenceId(train.id)
+    : null;
+
+  const match =
+    item && 'exceptions' in item
+      ? item.exceptions.find((ex) => ex.occurrence_index === occurrenceIndex)
+      : null;
```
Comment (SharglutDev) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/getPathStyle.ts]:
```suggestion
 const exception =
    item && isPacedTrainWithDetails(item)
      ? item.exceptions.find((ex) => ex.occurrence_index === occurrenceIndex)
      : null;
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thanks. You can close the comment when fixed.

**Review by achrafmohye — APPROVED** [review]
LGTM and tested thanks :)

File: front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/getPathStyle.ts [hunk 2]
```diff
@@ -30,8 +36,19 @@ const getPathStyle = (
...
+
+  const occurrenceIndex =
+    isOccurrenceId(train.id) && isIndexedOccurrenceId(train.id)
+      ? extractOccurrenceIndexFromOccurrenceId(train.id)
+      : null;
+
+  const exception =
+    item && isPacedTrainWithDetails(item)
+      ? item.exceptions.find((ex) => ex.occurrence_index === occurrenceIndex)
+      : null;
```
Comment (SharglutDev) [inline front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/getPathStyle.ts]: To handle added exceptions, you can just do this : 

```suggestion
  const exception =
    item && isPacedTrainWithDetails(item) && isOccurrenceId(train.id)
      ? findExceptionWithOccurrenceId(item?.exceptions, train.id)
      : null;
```

Comment (theocrsb) [reply front/src/modules/simulationResult/components/SpaceTimeChartWrapper/helpers/getPathStyle.ts]: You're right, it's done

**Review by SharglutDev — APPROVED** [review]
