### PR TITLE
front: fix stdcm maps synchro

### LINKED ISSUE #13064: front: stdcm: maps are in sync even though they shouldn't
### What happened?

https://github.com/user-attachments/assets/efb44e85-788e-49a4-9cfa-a0f64ca6edde

Moving either the results or the input map moves the other

### What did you expect to happen?

I expect the two maps to be independent (seen with @Arthur-Lefebvre)

### How can we reproduce it (as minimally and precisely as possible)?

1. Get a successful stdcm simulation
2. Trying moving either map

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

9486361

### PR DESCRIPTION
**Pull request by SharglutDev**
fix #13064

> [!NOTE]
> The issue refers only about viewport synchronization but ideally it would be preferable if all settings of maps would be independent but this requires a larger refacto and can be done in another PR

### CODE REVIEW

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx [hunk 1]
```diff
@@ -109,8 +109,8 @@ const StdcmConfig = ({
   const mapSettings = useMapSettings();
   const { updateMapSettings: updateMapSettingsAction } = useMapSettingsActions();
 
-  const updateMapSettings = (partialMapSettings: Partial<MapSettings>) => {
-    dispatch(updateMapSettingsAction(partialMapSettings));
+  const updateViewport = (viewport: Viewport) => {
+    dispatch(updateMapSettingsAction({ ...mapSettings, viewport }));
```
Comment (clarani) [inline front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: You can even use the action `updateViewport` instead of `updateMapSettings` !

File: front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx [hunk 2]
```diff
@@ -62,11 +62,16 @@ const StdcmResults = ({
...
   const retainedSimulationIndex = useSelector(getRetainedSimulationIndex);
+
   const mapSettings = useMapSettings();
   const { updateMapSettings: updateMapSettingsAction } = useMapSettingsActions();
 
+  // Keep local state of the viewport to keep stdcm config and stdcm results maps independent
+  const [stdcmResultsViewport, setStdcmResultsViewport] = useState<Viewport>(mapSettings.viewport);
+
   const updateViewport = (viewport: Viewport) => {
     dispatch(updateMapSettingsAction({ ...mapSettings, viewport }));
```
Comment (clarani) [inline front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: Maybe we don't need to update the viewport in the store ? Why not keep only the viewport in the state ?

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: Agreed. Not very important to keep the same viewport when refreshing.

But it's a larger refacto since it will affect other maps as well.

Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmResults/StdcmResults.tsx]: Ok so I removed the call to the store when updating the viewport for these 2 components.

Lets discuss with POs to see if it is relevant to completely remove `updateViewport` from the store (might still be interesting  in the infra editor) and create an enhancement if that is the case.

File: front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx (hunk 1 above)
Comment (SharglutDev) [reply front/src/applications/stdcm/components/StdcmForm/StdcmConfig.tsx]: See comment below

**Review by Math-R — APPROVED** [review]
lgtm, what about the pontential enhancement ?

**Comment by SharglutDev** [comment]
@Tguisnet what are your thoughts about the last closed comment ?

**Comment by Tguisnet** [comment]
I think `updateViewport` is still pretty cool in the infra editor (as I often refresh the page).

However, we currently have 0 people using the editor.
So in the case you need to remove it, go for it;
But if you don't need to remove it, I'll appreciate to keep it !
