### PR TITLE
editoast: second try for the simulax fix

### LINKED ISSUE #14987: simulax: missing last segment on OP projection of train arriving to a track offset
### What happened?

Following https://github.com/OpenRailAssociation/osrd/pull/14928

When a train schedule's destination is a track offset and the simulation doesn't respect their times, the last segment of the STD curve isn't shown if the OP it goes through isn't in the train schedule path:

Image

### What did you expect to happen?

We want to show it actually, like what's done for the track projection:

Image

### How can we reproduce it (as minimally and precisely as possible)?

Have a train schedule that:

- arrives at a track offset (not at an operational point)
- goes through an operational point between its last schedule and the track offset arrival, but doesn't have this OP in its input (it must go through it only because of pathfinding)
- has times the simulation cannot respect.

Or simply use this timetable: 

[timetable(5).json](https://github.com/user-attachments/files/25012666/timetable.5.json)

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

43f28cedef96b9acb966582d9fb373a888bf2c15

### LINKED ISSUE #14988: simulax: track and OP projections are different for trains that end on a track offset and do not respect their times
### What happened?

Following https://github.com/OpenRailAssociation/osrd/pull/14863 and https://github.com/OpenRailAssociation/osrd/pull/14928

Because we draw a line between the last scheduled point and the destination, when the destination is a track offset (and thus not shown on OP projection), the STD curve is different depending on the projection mode.

track projection:

Image

op projection (notice how it doesn't reach Mid East Station a bit earlier):

Image

### What did you expect to happen?

Both curves must have the same slope

### How can we reproduce it (as minimally and precisely as possible)?

- Have a train schedule go `A -> B` (where A and B are operational points)
- have another go from `A -> B -> C` where C is a track offset and isn't scheduled
- project on the first, shorter train
- switch between track projection and OP projection

Example timetable:

[timetable(6).json](https://github.com/user-attachments/files/25015151/timetable.6.json)

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

43f28cedef96b9acb966582d9fb373a888bf2c15

### LINKED ISSUE #14991: simulax: op and track projections are different for trains that end on a track offset with an arrival time and do not respect their time
### What happened?

Following https://github.com/OpenRailAssociation/osrd/pull/14863 and https://github.com/OpenRailAssociation/osrd/pull/14928

The OP and track projections of some invalid trains look different. This is the same case as https://github.com/OpenRailAssociation/osrd/issues/14988 except the track offset path item isn't scheduled (doesn't have an arrival time)

track projection:

Image

op projection:

Image

### What did you expect to happen?

Both curves for the "sorter late track offset.." train must have the same slope. The curve for the track projection must end at `13:05:00`.

### How can we reproduce it (as minimally and precisely as possible)?

- Have a train schedule go `A -> B -> C` where
    - A and B are operational points, 
    - C is a track offset
    - B isn't scheduled
- switch between track projection and OP projection

Example timetable: 

[timetable(7).json](https://github.com/user-attachments/files/25017626/timetable.7.json)

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

4a406dbf5daa0ee8b750e7c7bf5eb06d86a1d05e

### PR DESCRIPTION
**Pull request by hhirtz**
Day 69.
We believe it is actually the final try this time and that we will be able to ship and demo the feature. I don't have neither time nor an LLM to continue this message so this will end right here.

But the fix actually is to use a `space_time_curve` (instead of None as earlier). We use the same curve than for the track projection for invalid trains. Then we interpolate our way through `refs`. We don't take into account stops that are not scheduled, because those can end up causing the curve to go backwards after them (except the first one and the last one which can't). The rest follows the same behavior as `new_from_simulation`.

# Examples

two timetables to test on small_infra:
[timetable(9).json](https://github.com/user-attachments/files/25047846/timetable.9.json)
[timetable(10).json](https://github.com/user-attachments/files/25047847/timetable.10.json)

## Track projection

screen-20260203095846

## Inputs

screen-20260203095900

## OP projection

screen-20260203095904

Closes https://github.com/OpenRailAssociation/osrd/issues/14991
Closes https://github.com/OpenRailAssociation/osrd/issues/14988
Closes https://github.com/OpenRailAssociation/osrd/issues/14987

### CODE REVIEW

**Comment by MartinBourbier** [comment]
@hhirtz Can you provide the timetable you used to test please?

**Comment by hhirtz** [comment]
two timetables to test on small_infra:
[timetable(9).json](https://github.com/user-attachments/files/25047846/timetable.9.json)
[timetable(10).json](https://github.com/user-attachments/files/25047847/timetable.10.json)

**Review by MartinBourbier — APPROVED** [review]
LGTM 🦅 (tested)

**Review by aschantraine — APPROVED** [review]
LGTM (tested) !

File: editoast/src/views/projection.rs [hunk 1]
```diff
@@ -520,83 +520,80 @@ impl TrainToProjectOnOperationalPoint {
...
-        if last_scheduled_op_ref == &last_path_item_op_ref {
-            // The last operational point is already present
-            return input_only;
-        }
+        let last_path_item_id = &ts.path().last().unwrap().id;
+        let first_path_item_id = &ts.path().first().unwrap().id;
 
-        let stop_for = ts
+        // Contrary to the input-only projection, we only want to take into account all stops.
+        let stops_input: HashMap<_, _> = ts
```
Comment (woshilapin) [inline editoast/src/views/projection.rs:540]: Do we need to collect into a map here? I’m wondering if we could just do 1 entire iteration with something along these lines?

```rust
let refs = itertools::izip!(ts.schedule(), ts.path(), path.path_item_positions)
            .filter(|(schedule, _path_item, _path_item_positions)| {
                &schedule.at == last_path_item_id
                    || &schedule.at == first_path_item_id
                    || schedule.arrival.is_some()
            })
            .filter_map(
                |(schedule, path_item, path_item_positions)| match &path_item.location {
                    PathItemLocation::OperationalPointPartReference(op_ref) => {
                        let arrival_time =
                            space_time_curve.linear_interpolate_position(path_item_position);
                        Some(OperationalPointRefAndTime {
                            arrival_time,
                            stop_for: schedule.stop_for.map(chrono::TimeDelta::num_milliseconds).unwrap_or_default() as u64,
                            op_ref: op_ref.operational_point.clone(),
                        })
                    }
                    _ => None,
                },
            )
            .collect();
```

**Review by woshilapin — APPROVED** [review]
I did a few tests and didn’t notice weirdness.

File: editoast/src/views/projection.rs (hunk 1 above)
Comment (flomonster) [reply editoast/src/views/projection.rs:540]:
```rust
itertools::izip!(ts.schedule(), ts.path(), path.path_item_positions)
```

This does not work, schedule does not have the same number of elements as path, and they're not ordered.
The way to associate a schedule with a path step is using the `id` of the path step.

TLDR; With the current state of train schedule format, we have to use a map :cry:

Comment (woshilapin) [reply editoast/src/views/projection.rs:540]: Ah yes, then forget about it!
