### PR TITLE
front: fix decimals error for study budget

### LINKED ISSUE #8607: Selecting float budget gives unreadable error
### What happened?

https://github.com/user-attachments/assets/0509e2b0-7616-4a73-89c8-2ed5c4640010

### What did you expect to happen?

I expect the field to be highlighted in red, with a clear message stating that float numbers are forbidden

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to operational studies page
2. Open project creation form
3. Enter the name and a floating point budget
4. Click on save, witness

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

 1482e8c

### PR DESCRIPTION
**Pull request by Akctarus**
closes #8607

### CODE REVIEW

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 1]
```diff
@@ -413,7 +413,7 @@ const AddOrEditStudyModal = ({ editionMode, study, scenarios }: AddOrEditStudyMo
           <div className="col-lg-4">
             <InputSNCF
               id="studyInputBudget"
-              type="number"
+              type="text"
```
Comment (emersion) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Can we keep `number` still? This is useful for accessibility, on-screen keyboards, etc.

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 2]
```diff
@@ -432,12 +432,10 @@ const AddOrEditStudyModal = ({ editionMode, study, scenarios }: AddOrEditStudyMo
...
                   : ''
               }
-              onChange={(e) =>
-                handleStudyInputChange(
-                  'budget',
-                  e.target.value !== '' && +e.target.value >= 0 ? +e.target.value : null
-                )
-              }
+              onChange={(e) => {
+                const numericValue = e.target.value.replace(/\D/g, '');
```
Comment (emersion) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Seems like this ignores any non-digit character? Might be surprising to the user that part of what they typed is just discarded?

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: If we keep `number`, when we can still type letters and special characters, and if we save it, we have no budget.

Comment (emersion) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: But with `text` the user can also type letters and special characters? So we can keep `number`, and add some additional validation?

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 2 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: fixed

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: fixed

**Comment by emersion** [comment]
This looks much better! I have one remaining question: we already have some validation logic in `checkStudyFields()`. I think it would make sense to have a single spot where all of the validation is performed, instead of having half of it in one place and the other somewhere else?

One approach would be to add an extra condition to `checkStudyFields()` and change the existing error message to "not an integer between 0 and $max". Another approach would be to return an error string (or translation key) from `checkStudyFields()` instead of a `boolean`.

File: front/public/locales/en/operationalStudies/study.json [hunk 3]
```diff
@@ -47,6 +47,7 @@
   "confirmDeleteMessage_other": "Do you really want to delete the {{count}} scenarios?",
   "studyBudget": "Budget",
   "studyBudgetInvalid": "The budget for the study must not exceed 2147483647",
+  "studyBudgetNoDecimal": "The budget for the study must not be a decimal number",
```
Comment (emersion) [inline front/public/locales/en/operationalStudies/study.json]: This error message is a bit weird, because integers are decimal numbers. IOW, "42" is as good a decimal number as "-3.14".

Did you mean "fractional"? But then this doesn't convey that negative numbers are invalid.

I think "must be a positive integer" could do the trick?

Comment (Akctarus) [reply front/public/locales/en/operationalStudies/study.json]: Thank for your comments, fixed :)

**Comment by emersion** [comment]
Seems like there is a duplicate PR? https://github.com/OpenRailAssociation/osrd/pull/9663 seems identical.

File: front/public/locales/en/operationalStudies/study.json [hunk 4]
```diff
@@ -46,7 +46,7 @@
   "confirmDeleteMessage_one": "Do you really want to delete {{count}} scenario?",
   "confirmDeleteMessage_other": "Do you really want to delete the {{count}} scenarios?",
   "studyBudget": "Budget",
-  "studyBudgetInvalid": "The budget for the study must not exceed 2147483647",
+  "studyBudgetInvalid": "The study budget must be a positive integer, and must not exceed 2147483647 €.",
```
Comment (theocrsb) [inline front/public/locales/en/operationalStudies/study.json]:
```suggestion
  "studyBudgetInvalid": "The study budget must be a positive integer and must not exceed 2147483647 €",
```

File: front/public/locales/fr/operationalStudies/study.json [hunk 5]
```diff
@@ -45,7 +45,7 @@
     "byRecentDate": "Plus récents"
   },
   "studyBudget": "Budget",
-  "studyBudgetInvalid": "Le budget de l'étude ne doit pas dépasser 2147483647",
+  "studyBudgetInvalid": "Le budget de l'étude doit être un entier positif, et ne doit pas dépasser 2147483647 €",
```
Comment (theocrsb) [inline front/public/locales/fr/operationalStudies/study.json]:
```suggestion
  "studyBudgetInvalid": "Le budget de l'étude doit être un entier positif et ne doit pas dépasser 2147483647 €",
```

**Review by theocrsb — APPROVED** [review]
LGTM and tested :)

**Comment by Akctarus** [comment]
> Seems like there is a duplicate PR? #9663 seems identical.

#9663 is for project budget, this one is for study budget :)

**Review by emersion — APPROVED** [review]
My bad! LGTM :)
