### PR TITLE
front: fix rolling stock import

### LINKED ISSUE #13088: front: import/export rolling-stock is broken/too limited
### What happened?

When 📥  importing (front) a valid [ETCS RollingStock](https://github.com/OpenRailAssociation/osrd/blob/dev/tests/data/rolling_stocks/etcs_level2_rolling_stock.json) and ✅ directly submitting, import fails 💥 (added in https://github.com/OpenRailAssociation/osrd/pull/11917).

> This is because front's model doesn't contain all the fields of an editoast RollingStock and so doesn't forward them to editoast, in this case `etcs_brake_params` (that is required when the rolling-stock supports ETCS_LEVEL2 signaling).
Some other fields are probably missing and should also work.

This also prevents ✍️ text-editing of rolling-stocks, which is a valid workaround when front hasn't implemented all the fields.

Notes:
- the `locked` field that may be present in editoast's output should be ignored as it's not a RS property, it's a restriction of it's use in the app.
- as it works to first import RS directly to editoast (using editoast's CLI), it may be valid to:
  - load the file a bit differently in front, using the model that's output'ed (or input'ed) by editoast?
  - first import RS directly to editoast, then offer to edit it

### What did you expect to happen?

Expecting :

- [ ] ETCS RollingStock import 📥 + direct submit ✅  to work (and be a valid ETCS_LEVEL2 rolling-stock).
- [ ] import 📥  + direct submit ✅  > export 📤  of any valid RollingStock (including ETCS) should produce the same file (except sorting)
- [ ] editoast's import 🖥️  + export 📤 + import 📥 + direct submit ✅ should work and produce the same result in DB 💾 (expect metadata changes after edit, as it's mandatory to have a different name)

### How can we reproduce it (as minimally and precisely as possible)?

See previous sections to test locally.

### On which environments the bug occurs?

Dev (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

f4ccc4bedec9d97ee6fb6e60105da120267445f9

### PR DESCRIPTION
**Pull request by Wadjetz**
fix [#13088](https://github.com/OpenRailAssociation/osrd/issues/13088) and #13504

Move the “Import Rolling Stock” button to the front page.
Directly submit the imported file to the server, and if successful, select the imported rolling stock.
In case of failure, just display the error.

Screenshot 2025-10-07 at 10-06-35 OSRD

### CODE REVIEW

File: front/src/applications/rollingStockEditor/RollingStockEditorView.tsx [hunk 1]
```diff
@@ -143,7 +188,7 @@ const RollingStockEditor = () => {
               onClick={() => {
                 openModal(
                   <RollingStockEditorFormModal
-                    mainText={t('common.leaveEditionMode')}
+                    mainText={t('common.leaveEditionMode') + 'LOOOL'}
```
Comment (bougue-pe) [inline front/src/applications/rollingStockEditor/RollingStockEditorView.tsx]: This change should be removed.

**Review by bougue-pe — APPROVED** [review]
Did not review the front part.

✅ Tested the behavior OK from AC in https://github.com/OpenRailAssociation/osrd/issues/13088 (and bit more, like using them in etcs/small infra scenarii):
* `import > direct submit > export` has a small diff (after sorting):
  * ☑️ some fields are added (`locked`, `id`, `version`) but it's OK for now at least and doesn't prevent re-import
    EDIT: ✅ OK after additional filter.
  * ✅ null fields or empty lists are added (electrical_power_startup_time, etcs_brake_params, metadata, raise_pantograph_time, liveries).
  * ✅ for `fast_rolling_stock.json` the default_curve `max_efforts` has a rounding change (which is matching the db value when importing through CLI): 
    image

File: front/src/applications/rollingStockEditor/RollingStockEditorView.tsx (hunk 1 above)
Comment (Wadjetz) [reply front/src/applications/rollingStockEditor/RollingStockEditorView.tsx]: Oops, sorry, it slipped in — I’ll remove it.

File: front/src/applications/rollingStockEditor/components/RollingStockInformationPanel.tsx [hunk 2]
```diff
@@ -26,7 +26,14 @@ export default function RollingStockInformationPanel({
   const { t } = useTranslation();
 
   const exportRollingStock = () => {
-    const jsonString = JSON.stringify(rollingStock);
+    const {
+      id: _id,
+      locked: _locked,
+      version: _version,
+      metadata: _metadata,
```
Comment (bougue-pe) [inline front/src/applications/rollingStockEditor/components/RollingStockInformationPanel.tsx]: Sorry, I was mistaken in the main review comment (edited since): `metadata` is only added with "null" value if there is no modification to the RS (metadata is only created when modifying the name in my tests).

So it's better I guess to not filter it from output.
```suggestion
```

**Review by kmer2016 — APPROVED** [review]
Good job!
