### PR TITLE
front: fix none display when no study type in operational studies

### LINKED ISSUE #6655: `__None__` displayed in study description when `Type = __None__`
### What happened?

If the study i create has no specific type:
image

Then `__None__` will be displayed in the study card, and in its description:
image

image

### What did you expect to happen?

I'm excpecting nothing to be displayed if no type is specified.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a study without a specific type

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: stagin internal

### OSRD version (top right corner `Account` button > `Informations`)

218b6fb

### PR DESCRIPTION
**Pull request by RomainValls**
closes #6655

### CODE REVIEW

**Review by Akctarus — APPROVED** [review]
Tested, LGTM :)

**Review by SharglutDev — CHANGES_REQUESTED** [review]
You don't need to change anything in AddOrEditStudyModal.tsx. To solve the issue, you can just hide the study_type div if study_type === 'nothingSelected' in StudyCard.tsx and Study.tsx

Edit : as discussed with @RomainValls and @clarani, we are going to handle the issue by putting an empty string for the "none" study_type and see with the back-end if they can avoid letting the front send undefined or null for the study_type.

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 1]
```diff
@@ -256,15 +256,16 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
                       </div>
                     }
                     value={{
-                      id: currentStudy.study_type,
+                      id: currentStudy.study_type || '',
```
Comment (SharglutDev) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: You don't need this because an empty string is already falsy. 

Moreover, when selecting the "none" option, it currently gets 'nothingSelected' for the id (the e.target.value). To be consistent everywhere, we should have an id of empty string even for the selectoptions. You can start by replacing the StudyType like that : 


```
const study_types = [
  'nothingSelected',
  'timeTables',
  'flowRate',
  'parkSizing',
  'garageRequirement',
  'operationOrSizing',
  'operability',
  'strategicPlanning',
  'chartStability',
  'disturbanceTests',
] as const;

export type StudyType = typeof study_types;
```



```suggestion
                      id: currentStudy.study_type,
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for the changes, everything works great. Just one last comment for me.

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 2]
```diff
@@ -282,7 +283,7 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
                     }
                     value={{
                       id: currentStudy.state,
-                      label: t(`studyStates.${currentStudy.state || 'nothingSelected'}`).toString(),
+                      label: t(`studyStates.${currentStudy.state || undefined}`).toString(),
```
Comment (clarani) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: `currentStudy.state` is always defined, so you can remove the undefined :)
```suggestion
                      label: t(`studyStates.${currentStudy.state}`).toString(),
```

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 3]
```diff
@@ -256,15 +256,16 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
...
                       label: t(
                         `studyCategories.${currentStudy.study_type || 'nothingSelected'}`
                       ).toString(),
                     }}
                     options={studyCategoriesOptions}
-                    onChange={(e) =>
-                      handleStudyInputChange('study_type', e?.id as StudyForm['study_type'])
-                    }
+                    onChange={(e) => {
+                      const selectedType = e?.id === 'nothingSelected' ? '' : e?.id;
```
Comment (clarani) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: `e` is never undefined, but `id` can be undefined. It's better to test in this order:
- if `e.id` is not undefined and not equal to `'nothingSelected'`, then use `e.id`
- else return `''`

**Review by clarani — CHANGES_REQUESTED** [review]

File: front/src/modules/study/components/AddOrEditStudyModal.tsx (hunk 3 above)
Comment (SharglutDev) [reply front/src/modules/study/components/AddOrEditStudyModal.tsx]: With the new behavior, e.id equals either the studyType or an empty string (for the nothingSelected case) so I think we can totally remove this condition.

**Review by SharglutDev — APPROVED** [review]
Lgtm, good job !

To go further, I think we could, in another PR, do the same logic for the study_states by putting them in an array with `as const` and maybe we could reuse the createSelectOptions function for both states and types. 

What do you think @clarani ?

File: front/src/applications/operationalStudies/consts.ts [hunk 4]
```diff
@@ -110,21 +110,20 @@ export const STUDY_STATES = {
...
-  flowRate: 'flowRate',
-  parkSizing: 'parkSizing',
-  garageRequirement: 'garageRequirement',
-  operationOrSizing: 'operationOrSizing',
-  operability: 'operability',
-  strategicPlanning: 'strategicPlanning',
-  chartStability: 'chartStability',
-  disturbanceTests: 'disturbanceTests',
-};
+export const study_types = [
```
Comment (clarani) [inline front/src/applications/operationalStudies/consts.ts]: I think it's better to keep it in SCREAM_CASE :) 
```suggestion
export const STUDY_TYPES = [
```

**Review by clarani — APPROVED** [review]
:white_check_mark: LGTM, only a small comment :)

**Comment by clarani** [comment]
Yes agree with @SharglutDev for studyStates, we should create an issue for that :pray:
