### PR TITLE
Fix speed section length in MRSP

### LINKED ISSUE #862: Fix speed sections length in MRSP
Trains start accelerating when their head exits a low speed region. They are supposed to wait until their tail exits the region.

Constant speed phase need to continue until the tail leaves the low speed area, then the train can accelerate.

This implies making constant speed envelope parts longer and accelerating envelope parts start later.

### PR DESCRIPTION
**Pull request by axrolld**
Closes #862

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/envelope_sim_infra/MRSP.java [hunk 1]
```diff
@@ -51,6 +51,8 @@ public static Envelope from(List<TrackRangeView> ranges, RollingStock rollingSto
                 var interval = speedRange.getKey();
                 var begin = offset + interval.getBeginPosition();
                 var end = offset + interval.getEndPosition();
+                if (addRollingStockLength)
+                    end += rollingStock.length;
```
Comment (eckter) [inline core/src/main/java/fr/sncf/osrd/envelope_sim_infra/MRSP.java]: This change means that the MRSP envelope length could be larger than the path length. Same for any envelope built from the MRSP one. It doesn't have to be a problem, but it's something to keep in mind.

**Review by eckter — APPROVED** [review]
