### PR TITLE
core: stdcm: fix post-processing when arrival time is set

### LINKED ISSUE #9872: core: stdcm: array out of bounds in post-processing
### What happened?

```json
"error": {
        "status": 500,
        "type": "core:unknown_error",
        "context": {
            "message": "Index -1 out of bounds for length 1",
            "exception_type": "class java.lang.IndexOutOfBoundsException",
            "stack_trace": [
                "Preconditions.java:64",
                "Preconditions.java:70",
                "Preconditions.java:266",
                "Objects.java:361",
                "ArrayList.java:427",
                "STDCMPostProcessing.kt:184",
                "STDCMPostProcessing.kt:64",
                "STDCMPathfinding.kt:128",
                "STDCMPathfinding.kt:73",
                "STDCMEndpointV2.kt:99",
                "WorkerCommand.kt:249",
                "WorkerCommand.kt:303",
                "ThreadPoolExecutor.java:1136",
                "ThreadPoolExecutor.java:635",
                "Thread.java:840"
            ],
            "url": "/v2/stdcm"
        },
        "message": "An unknown exception was thrown"
    },
```

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

I have a payload that reproduces it on a private timetable

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

990c8fa9226a6783bf870bfd7716622fd686ce67

### PR DESCRIPTION
**Pull request by eckter**
We'd add too much delay to the departure time, resulting in inconsistencies. Includes a regression unit test. 

Fix https://github.com/OpenRailAssociation/osrd/issues/9872

Helps with https://github.com/OpenRailAssociation/osrd/issues/9023 as well, but it still happens, just much less often

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.kt [hunk 1]
```diff
@@ -233,6 +233,7 @@ class STDCMPostProcessing(private val graph: STDCMGraph) {
         mutableStopData: MutableList<StopTimeData>,
     ): Double {
         var maxTimeDiff = Double.POSITIVE_INFINITY
+        if (lastStopIndexBeforeNode == 0) maxTimeDiff = node.timeData.maxFirstDepartureDelaying
```
Comment (Erashin) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.kt]: Hmm. Isn't it always true then? Shouldn't we just init `maxTimeDiff` to `node.timeData.maxFirstDepartureDelaying`?

Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.kt]: It's true when the end time has been specified and there's no intermediate stop.

The alternative would be a ternary, but it's not a lot more readable. I don't mind either way.

Comment (Erashin) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/graph/STDCMPostProcessing.kt]: Nah let's keep it that way then.

**Review by Erashin — APPROVED** [review]

**Review by Erashin — APPROVED** [review]
