### PR TITLE
 front: fix map kinetic panning

### LINKED ISSUE #13313: Panning is blocked when the map is moving
### What happened?

https://github.com/user-attachments/assets/1f105203-2247-4ee8-959a-22bd43c7b288

When the map is moving, grabbing it to pan does not work.

### What did you expect to happen?

We should be able to pan even if the map is moving.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to map viewer (or any other page with a map)
2. Pan rapidly and try to pan again while it's moving.

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

065d07e

### PR DESCRIPTION
**Pull request by flomonster**
fix #13313

Review commits individually

> [!NOTE]
> This is an alternative of https://github.com/OpenRailAssociation/osrd/pull/13775 

When grabbing the map while kinetic panning, the map freezes. This was due to an updateViewportChange onMoveEnd.

Here I'm splitting the viewport change and router update. I'm updating the router only onIdle which makes sense from a user point of view.

> [!WARNING]
> I still have the issue with the editor map. Otherwise, all maps are fixed. 
> Fixing it on the editor map is quite difficult and is done in a follow-up PR: https://github.com/OpenRailAssociation/osrd/pull/15594

2026-03-0419-06-38-ezgif com-video-to-gif-converter

### CODE REVIEW

**Comment by theocrsb** [comment]
Thanks for this PR! The behavior works well on the map viewer, but the URL is not updated. I think this behavior could also be reflected on the map in the infrastructure editor.

**Comment by flomonster** [comment]
> Thanks for this PR! The behavior works well on the map viewer, but the URL is not updated. I think this behavior could also be reflected on the map in the infrastructure editor.

Actually, the URL updates `onIdle` so when the map stops moving. I will try to fix this also for the editor.

**Comment by sim51** [comment]
About the editor we don't care of the map state for the url.  We can have a `selection` as a url parameter, which will focus the map on the element on a page refresh. 

What I tested, on dev branch,  when I throw away the map, I can't pick it up again to continue the movement, the map freeze at the mouse click.  This is true for reference map, stdcm & editor.

On your branch, it's really better, and it's perfect on the reference map. 
On stdcm & editor, it is OK even if I have some freezes, but it's really better than before., and don't know how to make better.

So for me, it's good.

File: front/src/applications/editor/Map.tsx [hunk 1]
```diff
@@ -49,12 +49,6 @@ type MapProps<S extends CommonToolState = CommonToolState> = {
   infraID: number | undefined;
 };
 
-type MapState = {
```
Comment (sim51) [inline front/src/applications/editor/Map.tsx:52]: Why did you change it ?  It doesn't seem to be linked to the see (but perhaps I'm wrong) and impacts a lot your PR for the editor part.
But I tested the editor and it works. I'm just curious.

**Review by sim51 — APPROVED** [review]

**Review by theocrsb — APPROVED** [review]
Thanks, we can close this [PR](https://github.com/OpenRailAssociation/osrd/pull/13775)

File: front/src/applications/editor/Map.tsx (hunk 1 above)
Comment (flomonster) [reply front/src/applications/editor/Map.tsx:52]: Was not used, and I fixed an issue with the cursor while dragging.

**Review by hhirtz — COMMENTED** [review]
if you grab the map during kinetic panning, then launch another kinetic panning then grab the map during the panning, the map freezes?

**Review by hhirtz — APPROVED** [review]
it's really hard to reproduce, so

**Comment by flomonster** [comment]
Mmm it might not be 100% perfect. The follow-up PR will rewrite a bunch of this code and hopefully fix it entirely.

File: front/src/reducers/referenceMap/index.ts [hunk 2]
```diff
@@ -25,20 +26,22 @@ export const referenceMapSlice = createSlice({
...
+export function updateReferenceMapViewport(viewport: Partial<Viewport>) {
+  return (dispatch: Dispatch) => {
     dispatch(referenceMapSlice.actions.updateViewport(viewport));
+  };
+}
 
-    if (!updateRouter) return;
+export function syncReferenceMapRouterViewport(event: MapLibreEvent) {
+  return (dispatch: Dispatch) => {
+    void dispatch;
```
Comment (Math-R) [inline front/src/reducers/referenceMap/index.ts]:
```suggestion
  return (_dispatch: Dispatch) => {
```

Comment (flomonster) [reply front/src/reducers/referenceMap/index.ts]: Done

**Review by Math-R — APPROVED** [review]
Lgtm :)
