### PR TITLE
core: fix pathfinding

### LINKED ISSUE #1320: Pathfinding often fails
Running pathfinding requests on France often fails for paths that should work

### PR DESCRIPTION
**Pull request by eckter**
We had errors when the path starts or ends on the exact edge of a track because 0 length track ranges were not included in the path. This means we couldn't find the waypoint track in the path. We now include those track ranges.

### CODE REVIEW

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java [hunk 1]
```diff
@@ -85,35 +85,36 @@ public static List<PathWaypointResult> getWaypointsOnRoute(
...
-                    if (Math.abs(trackRangeOffset - truncatedRange.getLength()) < POSITION_EPSILON)
-                        trackRangeOffset = truncatedRange.getLength();
-                    if (Math.abs(trackRangeOffset) < POSITION_EPSILON)
-                        trackRangeOffset = 0;
-
-                    if (trackRangeOffset >= 0 && trackRangeOffset <= truncatedRange.getLength()) {
-                        var location = truncatedRange.offsetLocation(trackRangeOffset);
-                        waypoints.add(PathWaypointResult.userDefined(location, trackRangeOffset));
-                        waypointsOffsetsList.remove(i--); // Avoids duplicates on track transitions
+                if (truncatedRange != null) {
```
Comment (multun) [inline core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java:88]: can you use == null and continue instead?

**Review by multun — CHANGES_REQUESTED** [review]

File: core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java (hunk 1 above)
Comment (eckter) [reply core/src/main/java/fr/sncf/osrd/api/PathfindingResult.java:88]: The loop ends with `offset += range.getLength();` and we don't want to skip that

**Review by multun — APPROVED** [review]
