### PR TITLE
core: return error when allowance ranges are out of bounds

### LINKED ISSUE #4841: Backend crashes when allowance ranges are out of bounds
### What happened?

When provided with out of bound allowance ranges, the backend crashes in a hard to debug way

### What did you expect to happen?

at least a good error message

### How can we reproduce it (as minimally and precisely as possible)?

1. Provide a per-interval allowance, with allowance bounds outside of the train's path

It can only be done using the API, or exposed via a front-end bug

### What operating system, browser and environment are you using?

- **Browser**: Firefox v115
- **OS**: Nixos v23.05
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

2626967d61c8445e4cf7f6ed0d2f15429436e8e1

### PR DESCRIPTION
**Pull request by hamz2a**
closes #4841

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java [hunk 1]
```diff
@@ -156,6 +156,9 @@ private Envelope[] computeAllowanceRegion(Envelope envelopeRegion, EnvelopeSimCo
         var rangePercentages = new RangePercentage[ranges.size()];
         for (var i = 0; i < ranges.size(); i++) {
             var range = ranges.get(i);
+            if (range.beginPos < envelopeRegion.getBeginPos() || range.endPos > envelopeRegion.getEndPos()) {
+                throw new OSRDError(ErrorType.AllowanceRangeOutOfBounds);
+            }
```
Comment (eckter) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: I don't think this is the right place to do this.

We should check two things: that the ranges are contained within the allowance bounds, and that the allowance bounds are contained within the envelope. They should be done as soon as possible.

The first check should be done when initializing an `AbstractAllowanceWithRanges`. The constructor can call a new method that would check the inputs. 

The second one can't be checked without an input envelope, so it should be done at the start of `apply`.

Comment (hamz2a) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope_sim/allowances/AbstractAllowanceWithRanges.java]: Done.

**Review by eckter — APPROVED** [review]
