### PR TITLE
front: fix localStorage.setItem() in macro node store

### LINKED ISSUE #8477: NGE can't load if no entry is in nodeStore
### What happened?

If `nodeStore from `localStorage` is empty, NGE fails to load the microscopic timetable, and load the default netzgrafik from NGE instead.

This issue is critical because NGE can't be use in this case

image

### What did you expect to happen?

Initialize `nodeStore` if it's empty

### How can we reproduce it (as minimally and precisely as possible)?

1. Clear `localStorage`
2. Open Macroscopic

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by emersion**
JSON.stringify() will always return "{}" for a Map. Convert the Map to an array of entries before encoding these to JSON.

Closes: https://github.com/OpenRailAssociation/osrd/issues/8477

### CODE REVIEW

File: front/src/applications/operationalStudies/components/MacroEditor/nodeStore.ts [hunk 1]
```diff
@@ -14,7 +14,10 @@ const loadNodes = () => {
   let entries = [];
   const rawNodes = localStorage.getItem(NODES_LOCAL_STORAGE_KEY);
   if (rawNodes) {
-    entries = JSON.parse(rawNodes);
+    const parsedNodes = JSON.parse(rawNodes);
+    if (Array.isArray(parsedNodes)) {
+      entries = parsedNodes;
+    }
```
Comment (emersion) [inline front/src/applications/operationalStudies/components/MacroEditor/nodeStore.ts:24]: Can we log an error if it ends up not being an array? Just to let the dev know that we didn't actually load anything from the localStorage.

**Comment by emersion** [comment]
Your changes LGTM. Can you squash your two commits together?

**Comment by theocrsb** [comment]
Closes #8477

**Review by theocrsb — APPROVED** [review]
LGTM and tested

**Review by Uriel-Sautron — APPROVED** [review]
LGTM!! Tested

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark: not tested
