### PR TITLE
front: fix itinerary modal instantly writing the train header to the store

### LINKED ISSUE #15719: Itinerary modal - updating the header saves the new data in store
### What happened?

In the new itinerary modal, when updating one of the fields of the form header, the data is directly saved in the store.

https://github.com/user-attachments/assets/60bda09e-9a1c-42df-9dd8-ca1424fb8c05

As indirectly described in the part 0 of the ACs in the [main issue](https://github.com/osrd-project/osrd-confidential/issues/1166), clicking on the cancel button should cancel the changed made in the new modal.
But if the changes are directly saved in the store, there is no turning back.

### What did you expect to happen?

There should be a local state to keep the form changes and only when we submit the form, these changes are saved in the store and propagated to the old UI.

### How can we reproduce it (as minimally and precisely as possible)?

See the video (need redux dev tools extension) or go in the itineray modal, change the name, click on cancel at bottom left of the modal (which should cancel the changes) and see that the new name has been updated in the old UI.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

15330bb

### PR DESCRIPTION
**Pull request by MartinBourbier**
Introduces a `localName` in the modal that gets updated and is written to the store ONLY when submitting the form.

Closes https://github.com/OpenRailAssociation/osrd/issues/15719

Here is an example of the behaviour after the fix (focus on the updates of the `name`. For comparison, a non-functional example can be found in the original issue:

https://github.com/user-attachments/assets/24752581-f7e8-4f12-b521-2816a231b803

### CODE REVIEW

**Review by hhirtz — APPROVED** [review]
tested (this only fixes the bug for the train name as expected of course)

but it doesn't fix the issue for the rolling stock and category so i wouldn't close the linked issue

**Comment by MartinBourbier** [comment]
> tested (this only fixes the bug for the train name as expected of course)
> 
> but it doesn't fix the issue for the rolling stock and category so i wouldn't close the linked issue

Whoups. I will add it

**Review by ppitou — APPROVED** [review]
LGTM 🦅

**Review by hhirtz — APPROVED** [review]
tested, the fix applies on all properties in the header (train name, rolling stock, category, code compo)

no comment on the patch itself

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx [hunk 1]
```diff
@@ -85,23 +76,25 @@ const ItineraryModalFormHeader = ({
...
-    dispatch(updateCategory(rs.primary_category ? { main_category: rs.primary_category } : null));
+    onModalContextChange({
+      ...modalContext,
+      category: rs.primary_category ? { main_category: rs.primary_category } : undefined,
+      rollingStockId: rs.id,
+    });
   };
 
   // Composition code/speed limit by tag
   const speedLimitByTag = useSelector(getOperationalStudiesSpeedLimitByTag);
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx]:
```suggestion
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx [hunk 2]
```diff
@@ -177,7 +172,10 @@ const ItineraryModalFormHeader = ({
             value={speedLimitByTag || ''}
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx]:
```suggestion
            value={modalContext.speedLimitTag ?? ''}
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]
`speedLimitByTag` is read from the store in `ItineraryModalFormHeader` and used as the value of the composition code Select, but changes go into `modalContext`. These two are disconnected. After the user picks a new value, the store doesn't update, so the Select snaps back to the old value visually.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]:
```suggestion
    if (workerStatus !== 'READY' || !modalContext.rollingStockId || pathfindingSteps.length < 2) return;
```

Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]:
```suggestion
rollingStockId: modalContext.rollingStockId,
speedLimitTag: modalContext.speedLimitTag,
```

Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]:
```suggestion
  }, [workerStatus, modalContext.rollingStockId, modalContext.speedLimitTag, pathfindingSteps]);
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]
Bug: The pathfinding effect reads `rollingStockId` and `speedLimitTag` from the store, but this PR introduces `modalContext` as the local source of truth for these values. Two sources of truth for the same data guarantees desync. Any consumer of buffered state must read from the same place, otherwise the UI and the logic disagree silently.
Changing the train name won't show the bug since it's not a pathfinding input.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx [hunk 3]
```diff
@@ -187,9 +185,14 @@ const ItineraryModalFormHeader = ({
...
-            value={name}
-            title={name}
-            onChange={handleNameChange}
+            value={modalContext.name}
+            title={modalContext.name}
+            onChange={(e) =>
+              onModalContextChange({
+                ...modalContext,
+                name: e.target.value,
+              })
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx:191]: The name change propagates through `modalContext`, triggering a full re-render of `ItineraryModal` including path steps and map hooks. Feel free to fix it here if straightforward, otherwise tracked in https://github.com/OpenRailAssociation/osrd/issues/15853

**Review by kmer2016 — COMMENTED** [review]
pre-existing bug: Typing in the train name field causes the entire modal to re-render on every.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 4]
```diff
@@ -379,8 +398,12 @@ const ItineraryModal = ({
 
     if (compacted.length < 2) return;
 
+    dispatch(updateCategory(modalContext.category ?? null));
+    dispatch(updateRollingStockID(modalContext.rollingStockId));
+    dispatch(updateSpeedLimitByTag(modalContext.speedLimitTag ?? null));
+    dispatch(updateName(modalContext.name ?? ''));
     dispatch(updatePathSteps(compacted));
```
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Redux anti-pattern (pre-existing, to fix progressively): These 5 consecutive dispatches should ideally be a single action: that updates all fields atomically. Multiple setter dispatches trigger intermediate re-renders and make state transitions harder to trace.

See [Redux Style Guide about Model Actions as Events, Not Setters](https://redux.js.org/style-guide/#model-actions-as-events-not-setters).

When adding this action, don't forget to add unit tests for it (You can get inspiration from https://github.com/OpenRailAssociation/osrd/blob/8d7f5c04dbd87a6e1cede38a5f6fd13c0969fc79/front/src/reducers/osrdconf/operationalStudiesConf/__tests__/operationalStudiesConfReducer.spec.ts#L62

```suggestion
    dispatch( updateItineraryForm({ 
      name: modalContext.name ?? '',
      category: modalContext.category ?? null,
      rollingStockId: modalContext.rollingStockId,
      speedLimitTag: modalContext.speedLimitTag ?? null,
      pathSteps: compacted
    }) );
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 3 above)
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx:191]: I am not sure about how to fix this. I'm not a really good front dev yet so I would really appreciate it if you could give me more guidance on this. I can fix it in another PR

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 2 above)
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx]: Fixed in b1416070620abb0aac2ff614a252021c13d0a840

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Fixed in ed05b02d195b4fda44b57b0e15d2c453770db636

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx (hunk 4 above)
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Fixed in b1416070620abb0aac2ff614a252021c13d0a840

Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Also added a test in 0a9e90b60e1cbd4018f3856579632e532dc4d81d

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 2 above)
Comment (kmer2016) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx]: The commit b141607 doesn't seem to be pushed yet

File: front/src/reducers/osrdconf/operationalStudiesConf/trainSettingsReducer.ts [hunk 5]
```diff
@@ -64,6 +64,16 @@ const trainSettingsReducer = {
...
+    state: Draft<OperationalStudiesConfState>,
+    action: PayloadAction<ItineraryForm>
+  ) {
+    state.name = action.payload.name || state.name;
+    state.category = action.payload.category || state.category;
+    state.rollingStockID = action.payload.rollingStockId || state.rollingStockID;
+    state.speedLimitByTag = action.payload.speedLimitTag || state.speedLimitByTag;
+    state.pathSteps = action.payload.pathSteps;
+  },
 };
```
Comment (kmer2016) [inline front/src/reducers/osrdconf/operationalStudiesConf/trainSettingsReducer.ts:77]: The `||` fallback in here prevents clearing `category`, `rollingStockId` and `speedLimitByTag`` null || state.x` keeps the old value instead of clearing it.

`ItineraryForm` uses `null` where the store uses `undefined` (e.g. `rollingStockID?: number`). If the form type use the same store types, the reducer could just do direct assignments with no conditional logic:


```suggestion
  updateItineraryForm(
    state: Draft<OperationalStudiesConfState>,
    action: PayloadAction<ItineraryForm>
  ) {
    state.name = action.payload.name;
    state.category = action.payload.category;
    state.rollingStockID = action.payload.rollingStockId;
    state.speedLimitByTag = action.payload.speedLimitTag;
    state.pathSteps = action.payload.pathSteps;
  },
};
```

And the call site would become:

```typescript
updateItineraryForm({
  name: modalContext.name ?? '',
  category: modalContext.category ?? null,  // store uses null here
  rollingStockId: modalContext.rollingStockId,  // both undefined
  speedLimitTag: modalContext.speedLimitTag,    // both undefined
  pathSteps: compacted,
})
```

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 3 above)
Comment (kmer2016) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx:191]: Sure ! he re-render issue likely comes from `setModalContext` triggering a full re-render of `ItineraryModal` on every keystroke, which cascades to `ItineraryModalMap` even though the map doesn't depend on the name at all.

My intuition would be to wrap `ItineraryModalMap` with `React.memo`, but watch out: `IncompatibleConstraints` creates a new JSX reference on every render and would cancel out the memo, so you'd need to memoize it in the parent with `useMemo` too. 

We can keep this in a separate PR.

**Review by kmer2016 — CHANGES_REQUESTED** [review]

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 2 above)
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx]: Whoups my bad. This is the right one af701de3837e0f3052bff3c7af980644d0202a32

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 3 above)
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx:191]: Ok then I won't handle it in this PR

File: front/src/reducers/osrdconf/operationalStudiesConf/trainSettingsReducer.ts (hunk 5 above)
Comment (MartinBourbier) [reply front/src/reducers/osrdconf/operationalStudiesConf/trainSettingsReducer.ts:77]: Good point! Done in 7e474be96289111c2cc20fc5c5a8f5338c456a42

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx (hunk 3 above)
Comment (kmer2016) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModalFormHeader.tsx:191]: It's already fixed https://github.com/OpenRailAssociation/osrd/pull/15939 So you prabably need to rebase

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx
Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: When the user changes the rolling stock in the modal and then reverses the itinerary before submitting, `launchPathfinding` here doesn't receive a `rollingStockId`. It defaults to `currentRollingStockId` from the Redux store [usePathfinding.ts:243](https://github.com/OpenRailAssociation/osrd/blob/dev/front/src/modules/pathfinding/hooks/usePathfinding.ts#L243), which hasn't been updated yet since the modal only writes to the store on submit.

This means pathfinding runs with the old rolling stock.

```suggestion
    launchPathfinding(reversePathSteps(cPathSteps),  modalContext.rollingStockId);
```

**Review by kmer2016 — CHANGES_REQUESTED** [review]

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Fixed! I amended it directly without fixup to not waste time with the CI. You should be able to easily see the change with the github view

Comment (kmer2016) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: `isNameEmpty` reads from the Redux store via `useSelector(getName)`, but name is now handled locally in `modalContext`.

```suggestion
const isNameEmpty = !modalContext.name || modalContext.name.trim() === '';
```

**Review by kmer2016 — COMMENTED** [review]
**Rename `modalContext`**
`modalContext` can be confused with a [React Context.](https://react.dev/learn/passing-data-deeply-with-context#step-1-create-the-context) Consider renaming to `modalFormState` (or `localFormState`) to make it clear this is local component state.

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx
Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: This was done to avoid re-rendering the modal every time something is typed in the name field. Will this not introduce the bug again?

Comment (kmer2016) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Yes, it will re-introduce the re-render issue. But there's also a second bug from the rebase: isNameEmpty still reads from the Redux store via `useSelector(getName),` while name is now tracked locally in modalContext. So the submit guard checks a stale value, not what the user actually typed.

Since the strategy changed (local state instead of direct Redux writes), the fix for the name validation should change accordingly. This can be addressed in a separate PR since it's out of scope for this one.

Comment (MartinBourbier) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Done in 47cc2ab6b7846bc9be941581ce3d876e11a40886

**Review by kmer2016 — APPROVED** [review]
Good job!
