### PR TITLE
gateway: fix proxying of responses without a body

### LINKED ISSUE #11184: Parse error : malformed response error with DELETE ENDPOINT
### What happened?

Playwright's APIRequestContext is encountering an unexpected response format, leading to this error:
```
Error: apiRequestContext.delete: Parse Error: Expected HTTP/
    Call log:
      - → DELETE http://localhost:4000/api/projects/3
        - user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.16 Safari/537.36
        - accept: */*
        - accept-encoding: gzip,deflate,br
      - ← 204 No Content
        - access-control-allow-origin: *
        - vary: origin, access-control-request-method, access-control-request-headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
        - date: Mon, 03 Feb 2025 18:50:23 GMT


       at utils/api-setup.ts:103
```
Using `curl` I get this response :
```
 curl -i -X DELETE 'http://localhost:4000/api/projects/1'
HTTP/1.1 204 No Content
vary: origin, access-control-request-method, access-control-request-headers, Origin, Access-Control-Request-Method, Access-Control-Request-Headers
access-control-allow-origin: *
date: Mon, 03 Mar 2025 16:24:48 GMT
```
with `Postman` the `DELETE` is done but I receive an error :

image
```DELETE http://localhost:4000/api/projects/2
Error: Parse Error: Expected HTTP/
Request Headers
User-Agent: PostmanRuntime/7.43.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 489cd4a8-1016-400e-a81e-feeb1ea0d95f
Host: localhost:4000
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

it's mostly related to server response anomalies and Playwright's HTTP parsing strictness

### What did you expect to happen?

No parsing error 

### How can we reproduce it (as minimally and precisely as possible)?

1. Launch a DELETE request using Playwright API context or Postman

### On which environments the bug occurs?

Recette (SNCF), Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

7afc69b

### PR DESCRIPTION
**Pull request by multun**
Some HTTP responses do not and cannot have a body, which is most http clients translate as an empty body. If we attempt to stream an empty body with a response code which cannot have a body, actix does not raise an error and fails to add the transfer-encoding header, but still transmits the content, which is not HTTP compliant.

Do not attempt to stream the body when the backend response does not have one.

I found this chatting with @Synar

Fixes  #11184

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by Synar — APPROVED** [review]
Thanks for the help! <3

File: gateway/actix_proxy/src/lib.rs [hunk 1]
```diff
@@ -511,7 +511,16 @@ impl InnerProxyService {
             }
         }
 
-        Ok(response.streaming(back_response))
+        // a request has a body if it has a content-length or transfer-encoding (RFC 7231 section 4.3)
```
Comment (Khoyo) [inline gateway/actix_proxy/src/lib.rs]: I think you meant response, but this isn't true (for responses):

see rfc9112 section 6.3

> 8.  Otherwise, this is a response message without a declared message
       body length, so the message body length is determined by the
       number of octets received prior to the server closing the
       connection.

   > Since there is no way to distinguish a successfully completed,
   close-delimited message from a partially received message interrupted
   by network failure, a server SHOULD generate encoding or
   length-delimited messages whenever possible.  The close-delimiting
   feature exists primarily for backwards compatibility with HTTP/1.0.

While content length/transfer encoding are required for requests with bodies, they aren't for responses. AFAIK, the only responses which must not have a body are responses to HEAD, 1xx, 204 No Content, and 304 Not Modified.
(CONNECT request have their own things too but we aren't running a forward-proxy)

Comment (Synar) [reply gateway/actix_proxy/src/lib.rs]: Just having a set list of status code without body seemed a bit hardcoded to me, so I was curious how curl handled it in the error that motivated that pr in the first place and :

[http.c](https://github.com/curl/curl/blob/master/lib/http.c)
```C
k->http_bodyless = k->httpcode >= 100 && k->httpcode < 200;
  switch(k->httpcode) {
  case 304:
    /* (quote from RFC2616, section 10.3.5): The 304 response
     * MUST NOT contain a message-body, and thus is always
     * terminated by the first empty line after the header
     * fields.  */
    if(data->set.timecondition)
      data->info.timecond = TRUE;
    FALLTHROUGH();
  case 204:
    /* (quote from RFC2616, section 10.2.5): The server has
     * fulfilled the request but does not need to return an
     * entity-body ... The 204 response MUST NOT include a
     * message-body, and thus is always terminated by the first
     * empty line after the header fields. */
    k->size = 0;
    k->maxdownload = 0;
    k->http_bodyless = TRUE;
    break;
```
They are indeed iterating over the different status (and I didn't check but I assume HEAD is handled in a similar manner). So I suppose we can just do the same.

Comment (Khoyo) [reply gateway/actix_proxy/src/lib.rs]: It is hardcoded in the RFC text, and HTTP 1.1 isn't going to change meaningfully anytime soon :p (even though there were quotes to 3 separate RFCs that obsolete each others here...)

https://httpwg.org/specs/rfc9112.html#message.body.length

Comment (multun) [reply gateway/actix_proxy/src/lib.rs]: You're indeed both right, I'll fix it this evening. The RFC quote is from a guy on stack overflow, I should have checked

**Review by Synar — APPROVED** [review]

**Comment by Synar** [comment]
(Clippy has decided you should use the matches! macro btw if you did not see the pipeline fail)

**Review by flomonster — APPROVED** [review]
