### PR TITLE
front: fix some trigrams are not recognized

### LINKED ISSUE #10668: Some trigrams aren't recognized
### What happened?

In stdcm, when typing some existing trigrams the search endpoint doesn't return the corresponding operational point in the list (even though it works in operational studies with the rocket search).

Exemple of trigrams : 
- LE (Lille Flandres)
- DE (Dieppe)
- RN (Rouen rive droite)

### What did you expect to happen?

All trigrams should be recognized in stdcm

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm
2. Type one of these trigrams in the CI input

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by clarani**
closes #10668 

Since the search endpoint response is paginated, when the user searches a short string, the search endpoint will return some of the operational points which match either the trigram or the name. As the search endpoint response is not ordered by trigram first, we could miss some responses, and especially the operational points matching by trigram.

Now, if the user searches a short string, we will first get all the operational points matching the trigram and then the ones matching the name. This way, we won't miss the reponse by trigram anymore.

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
LGTM

**Review by theocrsb — APPROVED** [review]
LGTM and tested

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx [hunk 1]
```diff
@@ -36,46 +44,64 @@ export default function useSearchOperationalPoint({
...
+              ['search', ['name'], debouncedSearchTerm],
+              ['like', ['to_string', ['uic']], `%${debouncedSearchTerm}%`],
+            ],
+            ['=', ['infra_id'], infraID],
+            dpyToMasOperationalpointsFilter,
+          ],
+        },
+        pageSize: 101,
+      }).unwrap()) as SearchResultItemOperationalPoint[];
+      setSearchResults([...trigramResults, ...results]);
```
Comment (emersion) [inline front/src/common/Map/Search/useSearchOperationalPoint.tsx:104]: Do we need to de-duplicate results here? e.g. if both search queries return the same OP, it would appear twice in the list?

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you !

File: front/src/common/Map/Search/useSearchOperationalPoint.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/Map/Search/useSearchOperationalPoint.tsx:104]: We have a post-processing functions that filter the duplicates :) So I think it's ok like this
