### PR TITLE
fix RunningTime component

### LINKED ISSUE #4284: Maximum travel time in operational studies
### What happened?

When we add a new train we can see a "Maximum travel time" modal. This should only be seen in the STCM module.

2023-06-06-104112_1910x707_scrot

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Operational Studies
2. Create a project / study / scenario
3. Add a train

### What operating system, browser and environment are you using?

- **Browser**: Firefox 
- **OS**: Nixos v23.05
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

b61c9fe013477f775ee19eca5e552098a7d7a147

### PR DESCRIPTION
**Pull request by SarahBellaha**
Closes #4284

### CODE REVIEW

File: front/src/applications/operationalStudies/consts.ts [hunk 1]
```diff
@@ -174,6 +174,8 @@ export interface OsrdMultiConfState {
   stdcmConf: OsrdStdcmConfState;
 }
 
+export const runTimeCap = 43200;
```
Comment (alexandredamiron) [inline front/src/applications/operationalStudies/consts.ts]: Write the const in CAPITAL CASES

**Review by alexandredamiron — APPROVED** [review]
