### PR TITLE
core: stop filtering duplicate tracks during exploration

### LINKED ISSUE #11532: core: pathfinding request sometimes timeout on timetable imports
### What happened?

On basic import, some pathfinding take more than 3 minutes

### How can we reproduce it (as minimally and precisely as possible)?

It's hard to reproduce, but the logs indicate it happens at every timetable import.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

be7a277f4af28459e4abc63091327c64839b5b83

### PR DESCRIPTION
**Pull request by eckter**
Probably fix https://github.com/OpenRailAssociation/osrd/issues/11532, at least partially. It's difficult to reproduce that issue outside the daily timetable import, so we'll only know if it's actually fixed once merged. But it does improve pathfinding performances by quite a lot, especially with multithreading.

Change summary: we stop filtering paths with duplicated tracks during the exploration. We test this once during post-processing, **and report it as "no path found" when it happens.** Which is not *strictly speaking* true, but if the shortest path has loops, we can expect that there's something wrong with the data somewhere and that this isn't the expected path. 

Same goes for stdcm: we only run the check during post-processing, and we also report it as "no path found". This one is a clear improvement, as users don't like answers with crazy detours. 

## Benchmark

I have a folder of saved pathfinding payloads, most of them are here because they're way too slow. I ran them 5 times each on either version and averaged the results. Here's a comparaison:

Average per file (dev -> this branch, in seconds)

> 23.044 -> 13.447
> 13.064 -> 10.793
> 22.619 -> 11.974
> 0.003 -> 0.002
> 12.444 -> 10.042
> 4e-4 -> 2e-4
> 10.013 -> 0.603
> 16.602 -> 10.775
> 17.002 -> 13.620
> 22.725 -> 11.850
> 
> global average: 13.751 -> 8.310

The difference is pretty massive for requests that were painfully slow. For the ones that took a normal amount of time, it's still an improvement but less noticeable.

For STDCM the difference is even larger: for one specific request I have saved, I increased the timeout to 10 minutes. On dev, we reach the timeout with 750k nodes visited. Mostly because the RAM limit (16gb) is reached pretty early. With the change, a solution is found in 367s, with 1.8M visited nodes. 

(to be fair, the difference is that large because the filter may have been poorly parametrized)

## Effects on timetable imports

I can't give detailed data on this public PR, but the general idea is that a few trains imported as "schedule not honored" are now "no path found". The paths we used to find in those cases were clearly invalid. 

Using a less restrictive path as fallback in case of errors should work *better* than before, as the paths were clearly wrong but still counted as valid. 

Debbuging a specific import could be a little more tedious though, as there's nothing to display, not even a partially invalid path. But I've heard there are scripts that identify where the error is (in terms of waypoint index), so that should still work out.

### CODE REVIEW

File: core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt [hunk 1]
```diff
@@ -213,6 +215,33 @@ private fun computePaths(
...
+fun hasDuplicateTracks(infra: FullInfra, path: PathfindingResultId<Block>): Boolean {
+    val seenTracks = mutableSetOf<TrackSectionId>()
+    var lastTrack: TrackSectionId? = null
+    for (blockRange in path.ranges) {
+        val zonePaths = infra.blockInfra.getBlockZonePaths(blockRange.edge)
+        for (zonePath in zonePaths) {
+            val chunks = infra.rawInfra.getZonePathChunks(zonePath)
+            val tracks = chunks.map { infra.rawInfra.getTrackFromChunk(it.value) }
+            for (track in tracks) {
+                if (lastTrack == track) {
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt:231]: Can be resolved: in case of a short backtrack (same track), can't (couldn't) we get the breaks of OSRD but no detection here, so weird errors?

Just in case it triggers some (probably unrelated) thoughts.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/infra_exploration/InfraExplorer.kt [hunk 2]
```diff
@@ -161,7 +153,6 @@ private class InfraExplorerImpl(
     private var blocks: AppendOnlyLinkedList<BlockId>,
     private var routes: AppendOnlyLinkedList<RouteId>,
     private var blockRoutes: AppendOnlyMap<BlockId, RouteId>,
-    private var visitedTracks: AppendOnlySet<TrackSectionId>,
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/stdcm/infra_exploration/InfraExplorer.kt:164]: Can be resolved too: Did you ever try relying on a "simple" BooleanArray?
For France we are a little above 32k track-sections, so little above 4ko... (would probably require protections).

File: core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt [hunk 3]
```diff
@@ -134,7 +135,7 @@ class STDCMEndpoint(private val infraManager: InfraProvider) : Take {
                     Pathfinding.TIMEOUT,
                     temporarySpeedLimitManager,
                 )
-            if (path == null) {
+            if (path == null || hasDuplicateTracks(infra, path.blocks)) {
```
Comment (bougue-pe) [inline core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt:138]: Should we add some explicit test about that? (same for pathfinding).
Not sure it's worthy.

**Review by bougue-pe — APPROVED** [review]
LGTM, thanks!

**Review by Erashin — APPROVED** [review]

**Review by Khoyo — APPROVED** [review]

File: core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt (hunk 1 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/api/pathfinding/PathfindingBlocksEndpoint.kt:231]: Backtracks aren't really in scope here

What might trigger an error without being caught would be a single track that loops with itself. But I'd say it's too niche and unlikely to be a significant issue.

File: core/src/main/kotlin/fr/sncf/osrd/stdcm/infra_exploration/InfraExplorer.kt (hunk 2 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/stdcm/infra_exploration/InfraExplorer.kt:164]: It has been considered. But we need to copy the data across nodes (as we run an A* / parallel search). In that context 32k bits in't small.

If we needed to keep this constraint or if we ever want to add it back, I'd try to have a boolean array every ~100 nodes or so, where each node references the last array. And then a *much* smaller bloom filter (or similar) for the data added since then.

But it's easier to just drop the filter altogether.

File: core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt (hunk 3 above)
Comment (eckter) [reply core/src/main/kotlin/fr/sncf/osrd/api/stdcm/STDCMEndpoint.kt:138]: Ideally yes, but as the check is handled by the endpoint and not the underlying module, we'd need a full railjson infra with loops to test it. That would take a while.
