### PR TITLE
front: refacto import modal and clean button colors

### LINKED ISSUE #4900: front: import: when pathfinding fails, message should be in red
The message saying that pathfinding has failed should be in red color, as previously.

Image

OSRD Version a7bf4b66

### PR DESCRIPTION
**Pull request by clarani**
closes #4900

### CODE REVIEW

**Review by Yohh — APPROVED** [review]
:muscle:

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleModal.tsx [hunk 1]
```diff
@@ -319,19 +366,27 @@ const ImportTrainScheduleModal = ({
           {!infraId || !timetableId || !rollingStockID ? null : (
             <>
               <button
-                className={`btn btn-sm btn-block d-flex justify-content-between ${
-                  status.uicComplete ? 'btn-outline-success' : 'btn-primary'
-                }`}
+                className={cx('btn btn-sm btn-block d-flex justify-content-between', {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleModal.tsx]: Not the best case, but since the front meeting, should we isolate each of these class when using a `cx` ?
```suggestion
                className={cx('btn', 'btn-sm', 'btn-block', 'd-flex', 'justify-content-between', {
```

**Review by SharglutDev — COMMENTED** [review]
Lgtm, nice refacto :) Tested in local for different cases and everything works.
Just left one (annoying) comment

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleModal.tsx (hunk 1 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleModal.tsx]: Yes, well spotted, thanks !

**Review by SharglutDev — APPROVED** [review]

**Review by Math-R — APPROVED** [review]
lgtm
