### PR TITLE
front: fix secondary code attribution in round trips

### LINKED ISSUE #13031: NGE : node pairing with OSRD operational points does not work for round trips
### What happened?

1. I create two nodes in NGE : PLY and DN
2. I create a round trip between these two nodes 

Image

3. When nodes are created in NGE, they are mapped to the corresponding BV node, if possible. But here, I can see that when I refresh, the nodes are duplicated : PLY BV and DN BV are recognized for the forward service but not for the backward service (I can also see that in the itineraries in OSRD)

Image

Train PLY to DN : 

Image

Train DN to PLY : 

Image

### What did you expect to happen?

I expect the BV recognition to work for both services

### How can we reproduce it (as minimally and precisely as possible)?

Follow what's listed above

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8ff664b

### PR DESCRIPTION
**Pull request by RomainValls**
close #13031

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts [hunk 1]
```diff
@@ -414,8 +414,10 @@ const handleCreateTimetableItem = async (
     TRAINRUN_DIRECTIONS.BACKWARD
   );
 
-  await populateSecondaryCodesInPath(path, infraId, dispatch);
-
+  await Promise.all([
+    populateSecondaryCodesInPath(path, infraId, dispatch),
+    populateSecondaryCodesInPath(returnPath, infraId, dispatch),
+  ]);
```
Comment (Synar) [inline front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Thanks for the catch! This bug is mb, I did not realize populate mutated the path directly.

I'm not sure calling populate twice is the best option though, since we'll just do the same requests twice (as the path is the same, just reversed, and thus we'll search the same trigrams). Perhaps if it's not too complex we could cut populate in two functions, one that actually does the search, and the other that actually mutates the path using the search results?

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Suggested change:

```ts
await populateSecondaryCodesInPath([...path, ...returnPath], infraId, dispatch);
```

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Hm, I just realize that this doesn't make any difference, since `populateSecondaryCodesInPath()` sends one request per OP with a missing secondary code. 

[Here I believe emersion said this was not worth fixing and that he had a pr that would make this redundant anyway, but I accidentally erased his comment 👀]

**Review by emersion — APPROVED** [review]
Looks good! Can you squash these two commits together, ideally retaining attribution with a [`Co-authored-by`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) trailer, and keeping both `Signed-off-by` trailers?

File: front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts (hunk 1 above)
Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: Nooo I edited instead of replying, I don't know how to undo, sorry 😭

(Me being able to edit your comment is weird though)

Comment (emersion) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: I've restored the original comment :P (GitHub provides a diff view when opening the "edited" dropdown)

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: We can still cutback on the number of requests (by half) by separating the fetching from the populate. It's not a huge deal if we don't though.

Comment (Synar) [reply front/src/applications/operationalStudies/views/Scenario/components/MacroEditor/ngeToOsrd.ts]: > I've restored the original comment :P (GitHub provides a diff view when opening the "edited" dropdown)

I can't find a way to access it from the phone app 👀

**Review by Synar — APPROVED** [review]

**Review by emersion — APPROVED** [review]
