### PR TITLE
front: improve import view

### LINKED ISSUE #8115: Weird behavior and error messages importing train schedule files
### What happened?

Here is a list of weird behaviors when importing train schedules from files:

1. We cannot import a file if its extension is not `.json` even if it's a valid json file
2. If importing a valid json file like `{}` nothing happens (no errors are reported)
3. If we import an almost-valid file like this one [almost_valid.json](https://github.com/user-attachments/files/16283842/almost_valid.json). We have the following error message "All running time calculations have failed.". This is confusing since no running time calculation is performed. The file is just invalid.

### What did you expect to happen?

1. Being able to import json file with an invalid extension
2. Display an error like: "Malformed json file"
3. Change the error like: "Invalid train schedule file format"

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a scenario
2. Try to import files like describe above

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

580140d

### PR DESCRIPTION
**Pull request by clarani**
close #8115 

You can ask me some files to test the PR

### CODE REVIEW

File: front/src/common/uploadFileModal.tsx [hunk 1]
```diff
@@ -76,18 +32,12 @@ const UploadFileModal = ({ handleSubmit }: UploadFileModalProps) => {
             accept=".json,.xml,.railml"
```
Comment (SharglutDev) [inline front/src/common/uploadFileModal.tsx]: Shouldn't we add .txt ? This way I think we wouldn't have to select `all files` in the os window

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 2]
```diff
@@ -9,71 +9,40 @@ export const handleFileReadingError = (error: Error) => {
...
 ) => {
-  try {
-    const importedTrainSchedules: TrainScheduleBase[] = JSON.parse(fileContent);
-    if (importedTrainSchedules && importedTrainSchedules.length > 0) {
-      setTrainsJsonData(importedTrainSchedules);
-    }
-  } catch (error) {
-    handleJsonParsingError(error as Error, dispatch);
+  const importedTrainSchedules: TrainScheduleBase[] = JSON.parse(fileContent);
+  if (importedTrainSchedules && importedTrainSchedules.length > 0) {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: On the line above, we type `importedTrainSchedules: TrainScheduleBase[]` so we shouldn't have to check for that ?
```suggestion
  if (importedTrainSchedules.length > 0) {
```

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx [hunk 3]
```diff
@@ -104,7 +104,7 @@ const ImportTrainScheduleTrainsList = ({
       dispatch(
         setFailure({
           name: t('failure'),
-          message: t('status.calculatingTrainScheduleCompleteAllFailure', {
+          message: t('status.invalidTrainSchedules', {
             trainsList,
             count: trainsList.length,
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx]: The trad doesn't seem to take count into account ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 4]
```diff
@@ -9,71 +9,40 @@ export const handleFileReadingError = (error: Error) => {
...
+    dispatch(
+      setFailure({
+        name: t('errorMessages.error'),
+        message: t('errorMessages.errorEmptyJSON'),
+      })
+    );
   }
 };
 
 export const processXmlFile = async (
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:91]: Don't think it's related to your changes because the import technically works but after editing the rs for one of the train in the list I have this : 

Capture d’écran 2024-12-20 à 11 42 40

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 5]
```diff
@@ -9,71 +9,40 @@ export const handleFileReadingError = (error: Error) => {
...
-    }
-
-    const importedTrainSchedules = await parseRailML(xmlDoc);
-    if (importedTrainSchedules && importedTrainSchedules.length > 0) {
-      updateTrainSchedules(importedTrainSchedules);
-    }
-  } catch (error) {
-    handleXmlParsingError(error as Error, dispatch);
+  if (parserError.length > 0) {
+    throw new Error('Invalid XML');
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:101]: If the file is invalid we throw the error in console but the user doesn't see any message/notification. Wouldn't we want to display something ?
In `uploadFileModal.tsx`, it used to have an `errorInvalidXMLFormat` message displayed in the catch (not sure how it was suppose to be displayed).

Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:101]: If the json has a syntax error, we see "invalid XML" in console even though we sent a .json. Seems the wrong function is called.
Should we keep the file extensions condition like it was before ?

File: front/src/common/uploadFileModal.tsx (hunk 1 above)
Comment (clarani) [reply front/src/common/uploadFileModal.tsx]: Yes sure !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 2 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Yes I can add a check :)

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx (hunk 3 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx]: Done :+1:

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 5 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:101]: The goal of this ticket is to handle all types of files (try to parse it into json and xml even though it's not a .json or a .xml), so I can't really keep the file extensions condition like before :/
I added an early return if the extension is .json, is it enough for you ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 6]
```diff
@@ -9,71 +9,94 @@ export const handleFileReadingError = (error: Error) => {
...
-  console.error('Error parsing JSON:', error);
-  dispatch(
-    setFailure({
-      name: t('errorMessages.error'),
-      message: t('errorMessages.errorInvalidJSONFormat'),
-    })
-  );
-};
+const validateTrainSchedules = (
+  importedTrainSchedules: Record<string, unknown>[]
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: This should work to avoid many `any` in the function ?
```suggestion
  importedTrainSchedules: Partial<TrainScheduleBase>[]
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 7]
```diff
@@ -9,71 +9,94 @@ export const handleFileReadingError = (error: Error) => {
...
+  const isInvalidTrainSchedules = importedTrainSchedules.some((trainSchedule) => {
+    if (
+      ['constraint_distribution', 'path', 'rolling_stock_name', 'start_time', 'train_name'].some(
+        (key) => !(key in trainSchedule)
+      ) ||
+      !Array.isArray(trainSchedule.path)
+    ) {
+      return true;
+    }
+    const hasInvalidSteps = trainSchedule.path.some((step) => ['id'].some((key) => !(key in step)));
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Can't we do that instead ? (since we check only the `id` key)
```suggestion
    const hasInvalidSteps = trainSchedule.path.some((step) => !('id' in step));
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 8]
```diff
@@ -9,71 +9,94 @@ export const handleFileReadingError = (error: Error) => {
...
+): TrainScheduleBase[] | null => {
+  const isInvalidTrainSchedules = importedTrainSchedules.some((trainSchedule) => {
+    if (
+      ['constraint_distribution', 'path', 'rolling_stock_name', 'start_time', 'train_name'].some(
+        (key) => !(key in trainSchedule)
+      ) ||
+      !Array.isArray(trainSchedule.path)
+    ) {
+      return true;
+    }
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Might be safer (in case of misspell) to do that
```suggestion
    const compulsoryKeys: (keyof TrainScheduleBase)[] = [
      'constraint_distribution',
      'path',
      'rolling_stock_name',
      'start_time',
      'train_name',
    ];
    if (
      compulsoryKeys.some((key) => !(key in trainSchedule)) ||
      !Array.isArray(trainSchedule.path)
    ) {
      return true;
    }
```

File: front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx [hunk 9]
```diff
@@ -94,7 +94,7 @@ const ImportTrainScheduleTrainsList = ({
       dispatch(
         setSuccess({
           title: t('success'),
-          text: t('status.calculatingTrainScheduleCompleteAllSuccess', {
+          text: t('status.successfulImport', {
             trainsList,
             count: trainsList.length,
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/ImportTrainScheduleTrainsList.tsx]: For json imports, I think `trainList` will be empty (same for l.109)
```suggestion
            count: trainsList.length || trainsJsonData.length,
```

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 10]
```diff
@@ -9,71 +9,94 @@ export const handleFileReadingError = (error: Error) => {
...
-  dispatch(
-    setFailure({
-      name: t('errorMessages.error'),
-      message: t('errorMessages.errorInvalidJSONFormat'),
-    })
-  );
-};
+const validateTrainSchedules = (
+  importedTrainSchedules: Record<string, unknown>[]
+): TrainScheduleBase[] | null => {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Where do we return `null` in the function ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts [hunk 11]
```diff
@@ -9,71 +9,94 @@ export const handleFileReadingError = (error: Error) => {
...
+      );
+    }
+    return isJsonFile;
+  }
+
+  // validate the trainSchedules
   try {
-    const importedTrainSchedules: TrainScheduleBase[] = JSON.parse(fileContent);
+    const importedTrainSchedules = validateTrainSchedules(rawContent);
     if (importedTrainSchedules && importedTrainSchedules.length > 0) {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: If I understood correctly, if we miss a compulsory key in `rawContent`, we will throw an error (in `validateTrainSchedules`) so we will fallback in `catch` here with `errorInvalidFile`. 

So same thing as before, checking `if (importedTrainSchedules &&...` isn't needed since `validateTrainSchedules` will always return an array (empty or not) if we are still in the `try`.

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:101]: Still don't work if the json is in a .txt but it's kinda edgy so works for me :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 6 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Done :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 7 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Good catch, thanks !

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 8 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Done :+1:

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 10 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Done

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 11 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts]: Done

File: front/public/locales/fr/operationalStudies/importTrainSchedule.json [hunk 12]
```diff
@@ -28,9 +26,10 @@
...
-    "calculatingTrainScheduleCompleteAllSuccess_one": "Le train a été importé.",
-    "calculatingTrainScheduleCompleteAllSuccess": "Tous les trains ont été importés.",
-    "calculatingTrainScheduleCompleteAllFailure": "Tous les calculs de marche ont échoué."
+    "successfulImport_one": "Le train a été importé.",
+    "successfulImport": "Tous les trains ont été importés.",
+    "invalidTrainSchedules_one": "La circulation à importer n'est pas au bon format.",
+    "invalidTrainSchedules": "Les circulations à importer ne sont pas au bon format."
   },
   "success": "Opération réussie",
   "to": "Destination",
```
Comment (SharglutDev) [inline front/public/locales/fr/operationalStudies/importTrainSchedule.json:35]: The line below, if you could just do : `"trainsFound": "train(s) trouvé(s)"`

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job ! You can fix and resolve the last comments when done :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts (hunk 4 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/helpers/handleParseFiles.ts:91]: Here is the bug : https://github.com/OpenRailAssociation/osrd/issues/10219

File: front/public/locales/fr/operationalStudies/importTrainSchedule.json (hunk 12 above)
Comment (clarani) [reply front/public/locales/fr/operationalStudies/importTrainSchedule.json:35]: It's done :white_check_mark:
