### PR TITLE
core: fix time interpolation with an epsilon acceleration

### LINKED ISSUE #6072: STDCM assertion error sanity check on envelope part
### What happened?

Running STDCM can fail with an assertion error.

Core stack trace:
```
	at fr.sncf.osrd.envelope.part.EnvelopePart.runSanityChecks(EnvelopePart.java:164)
	at fr.sncf.osrd.envelope.part.EnvelopePart.slice(EnvelopePart.java:625)
	at fr.sncf.osrd.envelope.part.EnvelopePart.sliceEnd(EnvelopePart.java:512)
	at fr.sncf.osrd.envelope.Envelope.slice(Envelope.java:278)
	at fr.sncf.osrd.envelope.Envelope.slice(Envelope.java:257)
	at fr.sncf.osrd.envelope.OverlayEnvelopeBuilder.sliceBase(OverlayEnvelopeBuilder.java:82)
	at fr.sncf.osrd.envelope.OverlayEnvelopeBuilder.build(OverlayEnvelopeBuilder.java:92)
	at fr.sncf.osrd.envelope_sim.pipelines.MaxEffortEnvelope.addAccelerationAndConstantSpeedParts(MaxEffortEnvelope.java:100)
	at fr.sncf.osrd.envelope_sim.pipelines.MaxEffortEnvelope.from(MaxEffortEnvelope.java:135)
	at fr.sncf.osrd.stdcm.graph.STDCMSimulationsKt.simulateBlock-E0Rpq9g(STDCMSimulations.kt:127)
	at fr.sncf.osrd.stdcm.graph.STDCMSimulations.simulateBlock(STDCMSimulations.kt:53)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.getEnvelope(STDCMEdgeBuilder.kt:138)
	at fr.sncf.osrd.stdcm.graph.STDCMEdgeBuilder.makeAllEdges(STDCMEdgeBuilder.kt:111)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.kt:79)
	at fr.sncf.osrd.stdcm.graph.STDCMGraph.getAdjacentEdges(STDCMGraph.kt:21)
	at fr.sncf.osrd.graph.Pathfinding.runPathfinding(Pathfinding.kt:207)
	at fr.sncf.osrd.stdcm.graph.STDCMPathfindingKt.findPath(STDCMPathfinding.kt:80)
	at fr.sncf.osrd.api.stdcm.STDCMEndpoint.act(STDCMEndpoint.kt:74)
	at org.takes.facets.fork.FkRegex.lambda$new$0(FkRegex.java:153)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:217)
	at org.takes.facets.fork.FkChain.route(FkChain.java:72)
	at org.takes.facets.fork.TkFork.act(TkFork.java:98)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:84)
	at org.takes.facets.fallback.TkFallback.lambda$new$0(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkSlf4j.act(TkSlf4j.java:110)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$W
```

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Use France infra
2. Create a train from (PLY to VCE) using 27000US
3. Search of a STDCM with the same parameters

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local & Dev

### OSRD version (top right corner `Account` button > `Informations`)

e78edcf

### PR DESCRIPTION
**Pull request by eckter**
Fix #6072 

There are two underlying problems:

1. When slicing an envelope part with constant speed, the speed at the slice point may be different by an epsilon (we compute something akin to `sqrt(x²)`.
2. When interpolating a time step on a part with an epsilon acceleration, the result would be inaccurate (we divide by an epsilon and the error is exponential)

This PR fixes the second problem (with a unit test). The first one could be fixed as well but it adds more complexity, and we *should* be robust to epsilon diffs anyway.

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java [hunk 1]
```diff
@@ -43,7 +44,7 @@ public static double interpolateStepTime(
             double positionDelta
     ) {
         var acceleration = stepAcceleration(lastPos, nextPos, lastSpeed, nextSpeed);
-        if (acceleration == 0.0)
+        if (areSpeedsEqual(acceleration, 0.0))
```
Comment (Erashin) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: Add an `areAccelerationsEqual` with a corresponding acceleration epsilon, as it should be lower than the speed epsilon.

**Review by Erashin — CHANGES_REQUESTED** [review]

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java (hunk 1 above)
Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/EnvelopePhysics.java]: I've added a new function to keep the right semantic, but the epsilon can't be much lower, because we divide by the result any small value would be problematic.
We really should get rid of floats as soon as possible

**Review by Erashin — APPROVED** [review]
