### PR TITLE
front: manchette: display waypoints added with map click

### LINKED ISSUE #8174: front: display the via added by click on the map in the manchette
### What happened?

> When the train path doesn't cover at least two operational points, nothing is displayed. It's an edge case but it feels wrong

This is because the vias added by clicking on the map are not displayed on the chart. We should add them with the operational points.

### What did you expect to happen?

- [ ] the via added by clicking on the map are displayed
- [ ] if a train doesn't cover 2 operational points, the space time chart is displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario v2
2. Add a train by clicking on the map, set the origin and destination on the same track (try to choose a track without any op)
3. Visualize the results of the simulation: the space time chart is not displayed

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by SharglutDev**
fix #8174

### CODE REVIEW

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 1]
```diff
@@ -1,20 +1,34 @@
...
 ) => {
+  const { t } = useTranslation('simulation');
   const [operationalPoints, setOperationalPoints] = useState<
     NonNullable<PathProperties['operational_points']>
   >([]);
 
+  const { data: trainScheduleUsedForProjection } =
+    osrdEditoastApi.endpoints.getV2TrainScheduleById.useQuery(
+      {
+        id: trainIdUsedForProjection as number,
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Nit: in general I prefer to avoid `as` casts if possible, because it makes the compiler ignore any type mismatch. If `trainIdUsedForProjection` happens to be a `string` for instance because there is a mistake in the code, this cast would hide the issue because the type-checker would remain silent.

Here `trainIdUsedForProjection` is a `number | undefined` so we should be able to use `trainIdUsedForProjection!` instead of `trainIdUsedForProjection as number` to retain the type check.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 2]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
...
         const { operational_points } = await postPathProperties(pathPropertiesParams).unwrap();
 
-        setOperationalPoints(
-          operational_points as NonNullable<PathProperties['operational_points']>
-        );
+        let operationalPointsWithAllWaypoints = operational_points as NonNullable<
+          PathProperties['operational_points']
+        >;
+        // Check if there are vias added by map click and insert them in the operational points
+        if (trainScheduleUsedForProjection.path.some((step) => 'track' in step)) {
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Do we really need this `if`? The `forEach` already has a check to ignore steps which aren't track offsets no?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 3]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
...
+          trainScheduleUsedForProjection.path.forEach((step, i) => {
+            if ('track' in step) {
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: To avoid growing the indentation, an early return could be used:

```ts
if (!('track' in step)) {
  return;
}
```

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 4]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
...
+              const indexToInsert = operationalPointsWithAllWaypoints.findIndex(
+                (op) => op.position >= positionOnPath
+              );
+
+              const formattedStep: NonNullable<PathProperties['operational_points']>[number] = {
+                id: step.id,
+                extensions: {
+                  identifier: {
+                    name: t('requestedPoint', { count: indexToInsert }),
+                    uic: 0,
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hm. This sounds like a bit of an abuse of the `PathProperties.operational_points` type...

Would we be able to perform this conversion a bit later so that we're dealing with `PathStep` instead of this type? That way we wouldn't have to fake an OP object for something which isn't an OP?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 5]
```diff
@@ -1,20 +1,34 @@
...
   trainIdUsedForProjection?: number,
   infraId?: number
 ) => {
+  const { t } = useTranslation('simulation');
   const [operationalPoints, setOperationalPoints] = useState<
     NonNullable<PathProperties['operational_points']>
   >([]);
 
+  const { data: trainScheduleUsedForProjection } =
+    osrdEditoastApi.endpoints.getV2TrainScheduleById.useQuery(
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Instead of making a new query, should we take the train schedule object as input parameter of this hook? I think that would be simpler and less reliant on the rtk-query cache.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 6]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
         };
         const { operational_points } = await postPathProperties(pathPropertiesParams).unwrap();
 
-        setOperationalPoints(
-          operational_points as NonNullable<PathProperties['operational_points']>
-        );
+        let operationalPointsWithAllWaypoints = operational_points as NonNullable<
+          PathProperties['operational_points']
+        >;
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Orthogonal to this PR since it was like this in the original code, but: can't this cast be simplified to a `operational_points!`?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 7]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
...
+              const positionOnPath = pathfindingResult.path_item_positions[i];
+              const indexToInsert = operationalPointsWithAllWaypoints.findIndex(
+                (op) => op.position >= positionOnPath
+              );
+
+              const formattedStep: NonNullable<PathProperties['operational_points']>[number] = {
+                id: step.id,
+                extensions: {
+                  identifier: {
+                    name: t('requestedPoint', { count: indexToInsert }),
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: `indexToInsert` is a bit weird to display to the user IMHO, since:

- It's 0-based, so can result in "requested point 0", which is scary for non-programmers.
- It's not the index in the list of waypoints requested by the user, it's an index in the path properties ranges? Not exactly sure.

Maybe `i + 1` would be a tad more informative. But maybe "point on track XXX" would be even better?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 8]
```diff
@@ -40,13 +59,44 @@ const useGetProjectedTrainOperationalPoints = (
...
+          PathProperties['operational_points']
+        >;
+        // Check if there are vias added by map click and insert them in the operational points
+        if (trainScheduleUsedForProjection.path.some((step) => 'track' in step)) {
+          trainScheduleUsedForProjection.path.forEach((step, i) => {
+            if ('track' in step) {
+              const positionOnPath = pathfindingResult.path_item_positions[i];
+              const indexToInsert = operationalPointsWithAllWaypoints.findIndex(
+                (op) => op.position >= positionOnPath
+              );
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: What if the point on the map is the last one? We wouldn't find any OP whose position is greater than `positionOnPath` right? We should insert at the end of the list in that case I think?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: I used that syntax because it's the one we use in most of the app but I'm not specially attached to it, so I can change it :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 2 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: That was to avoid looping through all `trainSchedule.path` with the forEach if there isn't at least one step with `track` but you right it's probably overkill considering the size of the array.

Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: `some()` also loops on all elements, so it doesn't actually result in any performance benefit. (And yeah micro-optimizations blah blah blah)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 1 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Yeah. I'd really like to scan all of the frontend and drop any unnecessary cast that can be simplified.

For me as a reviewer, `as` is a red flag shouting "we think we're smarter than the compiler" and I always wonder if I'm really smarter :P (sometimes it's really necessary, sometimes not)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 3 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 4 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: I don't like that either. But `later` would be inside `Manchette` component in osrd-ui, we give that array directly to the component after performing this hook.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Yeah I thought it was a bit overkill too... The only other place where we have the data is when we fetch the batch trainSchedules in `ScenarioV2` component. I could make a `useMemo` watching for `trainIdUsedForProjection` and keeping track of the related `trainSchedules` and pass it to `SimulationResults` and then this custom hook.
What do you think ?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 6 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Oh yep good point

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 7 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Actually I discussed with @thibautsailly about that and he doesn't want to display the index among all ops but only from the "waypoint added by map click" list

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 8 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hmm good point. And if I create a train with an OD added by map click, I get a white screen. There is an issue in the space time chart. Do you have it too ?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 4 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Oh my. So, the bad news is that I now remember that ui-manchette just duplicates the editoast types as-is… And the good news is that the result of this function is only consumed by ui-manchette and nothing else (so no need to refactor a whole lot of OSRD files when we decide to change the return type), and that we've planned to refactor ui-manchette to stop doing this: https://github.com/osrd-project/osrd-confidential/issues/637

Let's leave it at that for now :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Totally agreed :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 5 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hm, don't we have the train schedule in `selectedTrainSchedule` in `SimulationResultsV2`? Or is this somehow sometimes not the same train as `trainIdUsedForProjection`? Or is there another reason to not use that one?

Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Yep it's not that easy :) The selectedTrainSchedule (green background) is not always the same than the one used for projection (blue square around the train on the left of the card)

Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Right that makes sense indeed…! If it's not too much of a hassle I'd indeed prefer to grab the projected train schedule from `trainSchedules` in `ScenarioV2` as you suggested since that'd save an HTTP request.

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 6 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 5 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 6 above)
Comment (emersion) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hm I don't see this change in the diff I think?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 8 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done, it also fixes the crash.

File: front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartHeader.tsx [hunk 9]
```diff
@@ -0,0 +1,18 @@
+import { KebabHorizontal } from '@osrd-project/ui-icons';
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartHeader.tsx]: Seems like this was added in this PR by mistake?

**Review by emersion — APPROVED** [review]
With that extraneous file removed, LGTM! Thanks for the fix!

**Comment by SharglutDev** [comment]
> With that extraneous file removed, LGTM! Thanks for the fix!

Yep my bad -_-

File: front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartHeader.tsx (hunk 9 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/SpaceTimeChartHeader.tsx]: Yep it comes from another PR, not sure how this file ended up here. I just amended the last commit :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 10]
```diff
@@ -30,7 +36,12 @@ const useGetProjectedTrainOperationalPoints = (
 
   useEffect(() => {
     const getOperationalPoints = async () => {
-      if (infraId && pathfindingResult && pathfindingResult.status === 'success') {
+      if (
+        infraId &&
+        trainScheduleUsedForProjection &&
+        pathfindingResult &&
+        pathfindingResult.status === 'success'
```
Comment (Math-R) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: you can combine those in `pathfindingResult?.status === 'success'`

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 11]
```diff
@@ -40,13 +51,51 @@ const useGetProjectedTrainOperationalPoints = (
         };
         const { operational_points } = await postPathProperties(pathPropertiesParams).unwrap();
```
Comment (Math-R) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: i think you can optimize operational_points set doing 

```
const { operational_points } = await postPathProperties({
        infraId,
        props: ['operational_points'],
      }).unwrap();
```

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 12]
```diff
@@ -40,13 +51,51 @@ const useGetProjectedTrainOperationalPoints = (
...
 
-        setOperationalPoints(
-          operational_points as NonNullable<PathProperties['operational_points']>
-        );
+        let operationalPointsWithAllWaypoints = operational_points!;
```
Comment (Math-R) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts:47]: Are you sure that `operational_points` can't be null or undefined ?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts [hunk 13]
```diff
@@ -40,13 +51,51 @@ const useGetProjectedTrainOperationalPoints = (
...
+            return;
+          }
+
+          operationalPointsWithAllWaypoints = addElementAtIndex(
+            operationalPointsWithAllWaypoints,
+            indexToInsert,
+            formattedStep
+          );
+
+          waypointCounter += 1;
```
Comment (emersion) [inline front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Something was bugging me about this code, originally I thought it was inconsequential so ignored it but during a shower I realized it might matter after all…

What if the last two waypoints are track offsets? In that case, we'd take the `push()` route, but we still want the `waypointCounter` to be incremented to avoid having these share the same number when presented to the user. So I think we should move this line up before `if (indexToInsert === -1)`?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 11 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Hmm we need also `pathPropertiesInput` for the request. I think it's more clearer to leave the object before and pass it to the endpoint. Is that ok for you ?

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 12 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts:47]: Yep. As long as we ask for a data (ops, curves...), the endpoint will return them (the pathfinding has already been done with the previous endpoint : pathfindingblocks)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 13 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Wow very nice shower inspiration, you were right ! Fixed :)

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 10 above)
Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Done

File: front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts (hunk 11 above)
Comment (Math-R) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Yes sorry the code was wrapped but still, if pathPropertiesParams is not to be reused, it's not useful. You should just put args in the request

Comment (SharglutDev) [reply front/src/modules/simulationResult/components/SpaceTimeChart/useGetProjectedTrainOperationalPoints.ts]: Ok done :)

**Review by Math-R — APPROVED** [review]
LGTM !
