### PR TITLE
fix infra selection area

### LINKED ISSUE #11693: Infrastructure selection is now painful – clickable area too small
### What happened?

When selecting an infrastructure  on the modal, the clickable zone has become extremely small

### What did you expect to happen?

The whole highlighted bar (minus the small “detail” button) should be selectable, as it was previously.  

Image

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Infra editor
2. Open the infra selector modal
3. Observe that only a very thin strip at the top is interactive

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

b3d9a4e

### PR DESCRIPTION
**Pull request by kmer2016**
fix https://github.com/OpenRailAssociation/osrd/issues/11693

### CODE REVIEW

**Review by SarahBellaha — APPROVED** [review]
LGTM :)

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx [hunk 1]
```diff
@@ -105,27 +105,30 @@ const InfraSelectorModalBodyStandard = ({
...
-                  </span>
-                )}
-              </button>
-              <GrantsManager
-                resourceId={infra.id}
-                resourceType="infra"
-                userGrant={userGrant!}
-                privilegesByGrant={grantTreeByResourceType.get('infra')}
-              />
+                <div className="infraslist-item-info-wrapper">
```
Comment (SharglutDev) [inline front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx]: nit: since we use the terms `main` and `footer` maybe we could use `header` instead of `wrapper` ? (just a personal opinion)
```suggestion
                <div className="infraslist-item-info-header">
```

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx [hunk 2]
```diff
@@ -105,27 +105,30 @@ const InfraSelectorModalBodyStandard = ({
...
             >
-              <button
+              <div
                 className="infraslist-item-choice-main"
-                type="button"
                 onClick={() => {
                   setInfraID(infra.id);
                 }}
+                tabIndex={0}
+                role="button"
```
Comment (SharglutDev) [inline front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx]: Did you make the change because eslint doesn't like button in a button ?

File: front/src/modules/infra/styles/_infraSelector.scss [hunk 3]
```diff
@@ -108,14 +108,18 @@
...
     .infraslist-item-choice-main {
-      padding: 0 4px;
-      display: flex;
-      align-items: center;
-      justify-content: space-between;
-      height: 32px;
-      width: inherit;
-      span {
+      width: 100%;
+      cursor: pointer;
```
Comment (SharglutDev) [inline front/src/modules/infra/styles/_infraSelector.scss]: I think it's not need if you use `role=button`
```suggestion
```

File: front/src/modules/infra/styles/_infraSelector.scss [hunk 4]
```diff
@@ -108,14 +108,18 @@
...
     }
     .infraslist-item-choice-main {
-      padding: 0 4px;
-      display: flex;
-      align-items: center;
-      justify-content: space-between;
-      height: 32px;
-      width: inherit;
-      span {
+      width: 100%;
```
Comment (SharglutDev) [inline front/src/modules/infra/styles/_infraSelector.scss]: Do we need this width and the other one ?

If not, we can probably remove the `infraslist-item-choice-main` class

**Review by SharglutDev — COMMENTED** [review]
Thanks for the fix ! Just small comments otherwise it works great :)

File: front/src/common/authorization/components/GrantsManager.tsx [hunk 5]
```diff
@@ -66,12 +61,14 @@ const GrantsManager = ({
         </button>
       </div>
       {displayGrantSection && (
-        <GrantsManagerSubjects
-          resourceId={resourceId}
-          resourceType={resourceType}
-          userGrant={userGrant}
-          privilegesByGrant={privilegesByGrant}
-        />
+        <div onClick={(e) => e.stopPropagation()} role="button" tabIndex={0}>
```
Comment (SarahBellaha) [inline front/src/common/authorization/components/GrantsManager.tsx]: You can move this in the `GrantsManagerSubjects` :)

**Review by SarahBellaha — APPROVED** [review]
LGTM, just left a tiny comment :)

File: front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx (hunk 2 above)
Comment (kmer2016) [reply front/src/modules/infra/components/InfraSelector/InfraSelectorModalBodyStandard.tsx]: Not only for ESLint - it's mainly because React throws this DOM nesting warning in the browser console:

"Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>"

This is invalid HTML structure and could cause accessibility issues.

image

**Review by SharglutDev — APPROVED** [review]
Not very important if it's painful to fix but on the zone below, I have a `cursor: pointer` but nothing happens when I click
Capture d’écran 2025-05-27 à 18 57 56
