### PR TITLE
core:  fix allowance space search discontinuities

### LINKED ISSUE #5400: core: mareco: search space discontinuity happen in rare cases
### What happened?

500 errors with a search space discontinuity

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

Reproduced in a regression test on this branch: https://github.com/osrd-project/osrd/pull/5399

### What operating system, browser and environment are you using?

- **OS**: ubuntu
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

20d6b64c4fa4abf947d8ee211d4907693fa67a2d

### PR DESCRIPTION
**Pull request by eckter**
Couple of coasting problems for Mareco allowances, creating discontinuities in the search space for a solution validating said allowance.
First discontinuity was due to `coastFromBeginning` not starting at the `startSpeed` found when `coastFromEnd` never reaches the envelope. The solutions would then always fluctuate between braking=>coasting and coasting=>braking, but never with any solution in the middle.
Second discontinuity was due to `EnvelopePart` not always having an `EnvelopeProfile` attribute, in this case, the `Braking` one: coasting opportunities were not found because of that (braking opportunities are found by firstly checking if said `EnvelopePart` has a `Braking` attribute). It is now compulsory.

Comparison between doubles played a small part in this: a PR will be arriving to use `areSpeedsEqual` everywhere (as long as I find all the comparisons).

### CODE REVIEW

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java [hunk 1]
```diff
@@ -111,11 +113,16 @@ public static EnvelopePart generateTimes(
...
             double[] speeds
     ) {
-        return new EnvelopePart(
-                new HashMap<>(),
+        var envelopeProfile = EnvelopeProfile.BRAKING;
+        if (areSpeedsEqual(speeds[0], speeds[speeds.length - 1])) {
+            envelopeProfile = EnvelopeProfile.CONSTANT_SPEED;
+        } else if (speeds[0] < speeds[speeds.length - 1]) {
+            envelopeProfile = EnvelopeProfile.ACCELERATING;
+        }
```
Comment (multun) [inline core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: This does not work reliably: what matters is whether the train is _trying_ to accelerate or hold speed, as it can be decelerating but not _braking_

**Review by multun — CHANGES_REQUESTED** [review]

File: core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java (hunk 1 above)
Comment (Erashin) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: Agreed. But there are too many cases to work with. This method is only used in unit tests, in cases where the EnvelopeProfile does not really matter, and will always fail without a default EnvelopeProfile. I could maybe move it into a static method in a TestHelper, would that be fine with you ?

Comment (eckter) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: This specific overload is only used in unit tests, I suggest we move it to a test helper class and keep this (approximate) logic there

Comment (multun) [reply core/envelope-sim/src/main/java/fr/sncf/osrd/envelope/part/EnvelopePart.java]: > I could maybe move it into a static method in a TestHelper, would that be fine with you ?

That would do it, thanks

**Review by eckter — COMMENTED** [review]
"PR authors can't approve their own PR", but LGTM (once the other discussion is resolved)

Good job for figuring this out

**Review by axrolld — APPROVED** [review]
Also kind of a co-author of this PR but i agree with the changes ! Great job and perseverance  ! 💪

**Review by multun — APPROVED** [review]
