### PR TITLE
front: fix train initial speed when updating a train

### LINKED ISSUE #4216: front: start speed changes when editing a train
### What happened?

Each time we edit a train, the start speed is divided by 3,6 without any user action

### What did you expect to happen?

The start speed should not change without user input

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Add a train with a 100km/h start speed
3. Edit the train and watch the start speed

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 113.0.5672.127 (Build officiel) (64 bits)
- **OS**: Windows 10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

4c97ff14

### PR DESCRIPTION
**Pull request by clarani**
close #4216

### CODE REVIEW

**Review by Wadjetz — APPROVED** [review]

**Review by woshilapin — APPROVED** [review]

File: front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx [hunk 1]
```diff
@@ -20,7 +20,6 @@ import { LAYER_GROUPS_ORDER, LAYERS } from 'config/layerOrder';
 
 import 'common/Map/Map.scss';
 import OperationalPoints from 'common/Map/Layers/OperationalPoints';
-import Platforms from 'common/Map/Layers/Platforms';
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx:23]: You have a warning
```suggestion
import { Platforms } from 'common/Map/Layers/Platforms';
```

**Review by SharglutDev — CHANGES_REQUESTED** [review]

File: front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx (hunk 1 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ImportTrainSchedule/Map.tsx:23]: Correct, thanks :pray:

**Review by SharglutDev — APPROVED** [review]

**Review by Math-R — APPROVED** [review]
