### PR TITLE
front: fix typos and translation

### LINKED ISSUE #5665: front: typos
### What happened?

image
"À"
image
"infrastructure"
image
"editor" > Éditeur d'infrastructure
image
"null" ?

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

cf screenshots

### What operating system, browser and environment are you using?

- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

8ad8eafd

### PR DESCRIPTION
**Pull request by Akctarus**
Closes #5665

### CODE REVIEW

File: front/src/common/Map/MapKey.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ const MapSettings = ({ closeMapKeyPopUp }: MapKeyProps) => {
         />
       </div>
       <div className="mapkey-text">
-        {`${key.text} ${key.current ? t(`map-key:${key.current}`) : null}`}
+        {`${key.text} ${key.current ? t(`map-key:${key.current}`) : ''}`}
```
Comment (clarani) [inline front/src/common/Map/MapKey.tsx]: :wink: 
```suggestion
        {`${key.text} ${key.current && t(`map-key:${key.current}`)}`}
```

**Review by clarani — APPROVED** [review]
LGTM, left only 1 small comment. You can resolve it by your own :)

File: front/src/common/Map/MapKey.tsx (hunk 1 above)
Comment (Akctarus) [reply front/src/common/Map/MapKey.tsx]: Ty ! fixed
