### PR TITLE
front: fix negative budget in project and study

### LINKED ISSUE #7268: Negative budget in project/Study
### What happened?

The field "Estimated budget" accept négatif value 
image
image

### What did you expect to happen?

The field "Estimated budget" accept only positif values

### How can we reproduce it (as minimally and precisely as possible)?

1- Go to Opertionnal studies
2- Click on create a project
3- Set the field "Estimated budget" with négatif value 

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: rec

### OSRD version (top right corner `Account` button > `Informations`)

b0b88cf

### PR DESCRIPTION
**Pull request by theocrsb**
close #7268 

to test this, try : 
- paste negative number in the field
- enter '-100' 
- decrement the input field bellow 0

### CODE REVIEW

File: front/src/modules/project/components/AddOrEditProjectModal.tsx [hunk 1]
```diff
@@ -385,7 +386,9 @@ export default function AddOrEditProjectModal({
                 </div>
               }
               value={
-                currentProject.budget !== undefined && currentProject.budget !== null
+                currentProject.budget !== undefined &&
+                currentProject.budget !== null &&
+                currentProject.budget > 0
```
Comment (emersion) [inline front/src/modules/project/components/AddOrEditProjectModal.tsx]: Do we want to accept `budget == 0` here? In other words, do we want to empty the form field if the user enters "0", or decrements the value down to 0?

While testing this, it sounds like the current behavior with this PR is better: 0 means "no budget", and the page displaying the study hides the budget in that case.

**Review by emersion — APPROVED** [review]
Tested and LGTM!

File: front/src/modules/project/components/AddOrEditProjectModal.tsx (hunk 1 above)
Comment (theocrsb) [reply front/src/modules/project/components/AddOrEditProjectModal.tsx]: I think this behavior is ok, but maybe we need to double check with a PO

Comment (Math-R) [reply front/src/modules/project/components/AddOrEditProjectModal.tsx]: `value={currentProject.budget > 0 ? currentProject.budget : ''}` it think do it this way is more simple cause if budget is udefined or null it will also return ''

File: front/src/modules/study/components/AddOrEditStudyModal.tsx [hunk 2]
```diff
@@ -407,7 +408,9 @@ export default function AddOrEditStudyModal({ editionMode, study }: Props) {
                 </div>
               }
               value={
-                currentStudy.budget !== undefined && currentStudy.budget !== null
+                currentStudy.budget !== undefined &&
+                currentStudy.budget !== null &&
+                currentStudy.budget > 0
```
Comment (Math-R) [inline front/src/modules/study/components/AddOrEditStudyModal.tsx]: Same as previous

File: front/src/modules/project/components/AddOrEditProjectModal.tsx (hunk 1 above)
Comment (theocrsb) [reply front/src/modules/project/components/AddOrEditProjectModal.tsx]: Tried but it doesn't work because budget can be null or undefined and then we can't make the '>0' check.
I added '>=0' because PO said the user wants the see 0 if he types 0

**Review by Math-R — APPROVED** [review]
lgtm

**Comment by theocrsb** [comment]
Just amended one last thing : check in the onChange if the value is >=0 (for the useCase when a user copy/paste a negative number)
