### PR TITLE
front: fix train selection after edition

### LINKED ISSUE #11338: When editing a train/service, the selected item changes and is the first train/occurrence of the scenario
### What happened?

I select a train or occurrence in the scenario (not the first one). Then I edit it. Then the edition is done but the selected item becomes the first train or occurrence in the scenario (chronologically speaking). It is confusing because it brings me to another train, with another path and so one.

https://github.com/user-attachments/assets/6ca8a4ef-ef2c-473d-b73c-b13a4b0e9893

### What did you expect to happen?

I expected to have still the same selected item not to be changed when I edit a train (which is not necessarily the selected item !)

### How can we reproduce it (as minimally and precisely as possible)?

As in the video 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

b42f78b

### PR DESCRIPTION
**Pull request by clarani**
closes #11338

### CODE REVIEW

File: front/src/modules/trainschedule/helpers/pacedTrain.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+/* eslint-disable import/prefer-default-export */
+import type { PacedTrain } from 'common/api/osrdEditoastApi';
+import { Duration } from 'utils/duration';
+
+export const getOccurrencesNb = (pacedTrain: PacedTrain) => {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/helpers/pacedTrain.ts]: We could use this new function in `useOccurrences` l.24 and `paced-train-sections` l.84 ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts [hunk 2]
```diff
@@ -101,10 +109,13 @@ const useUpdateTrainSchedule = (
           timetable_id: timetableId!,
           id: trainIdToEdit,
         };
+        const occurrenceCount = getOccurrencesNb(pacedTrain);
+        if (occurrenceCount > 1) {
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Why not `> 0` ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts [hunk 3]
```diff
@@ -101,10 +109,13 @@ const useUpdateTrainSchedule = (
...
+          trainIdToSelect = formatPacedTrainIdToOccurrenceId(trainIdToEdit, 0);
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Doesn't change much while we don't have exceptions but if I selected occurrence with index 2, after editing I'll always have the first occurrence selected (even if the interval or time window didn't change).

File: front/src/modules/trainschedule/helpers/pacedTrain.ts (hunk 1 above)
Comment (clarani) [reply front/src/modules/trainschedule/helpers/pacedTrain.ts]: Hum in `useOccurrences`, we manipulate `PacedTrainWithDetails` and not `PacedTrain`.
Same for `paced-train-sections`

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts (hunk 2 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Good catch

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts (hunk 3 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Yes but for the moment, we don't allow the user to edit an occurrence

File: front/src/modules/trainschedule/helpers/pacedTrain.ts (hunk 1 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/helpers/pacedTrain.ts]: Oh right, maybe we could change `getOccurrencesNb` to pass `paced` (`PacedTrain["paced"]` / `PacedTrainWithDetails["paced"]`) in it and not the whole paced train ?

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts (hunk 3 above)
Comment (SharglutDev) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Yes but we allow the user to select one, so it could start with occurrence 2 selected and end up with occurrence 1 selected. But sounds painful to handle now, we can keep it for exceptions (we could add this case in the ACs)

**Review by theocrsb — APPROVED** [review]
lgtm and tested

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts:1]: nit: we should at some point rename this file since it also handles paced trains

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts [hunk 4]
```diff
@@ -101,10 +111,18 @@ const useUpdateTrainSchedule = (
           timetable_id: timetableId!,
           id: trainIdToEdit,
         };
+
+        // if the selected train is an occurence of the edited paced train, keep it selected
```
Comment (SharglutDev) [inline front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]:
```suggestion
        // if the selected item is an occurrence of the edited paced train, keep it selected
```

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job ! You can resolve the last comments

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts:1]: Done :)

File: front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts (hunk 4 above)
Comment (clarani) [reply front/src/modules/trainschedule/components/ManageTrainSchedule/hooks/useUpdateTrainSchedule.ts]: Done !
