### PR TITLE
front: fix full modal re render when typing on train name field

### LINKED ISSUE #15853: Itinerary modal: typing in train name field causes full modal re-render
### What happened?

Typing in the train name field in the itinerary modal causes the entire modal component to re-render on every keystroke (path steps, map, all hooks). This results in a noticeable input lag.

### What did you expect to happen?

Typing in the name field should feel instant, with no perceptible lag.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open a scenario
2. Click "Add train schedule"
3. In the itinerary modal, type rapidly in the train name field
4. Observe the input lag
https://github.com/user-attachments/assets/cad8bd49-3801-429b-935c-65072935dcf1

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

 b2f224d

### PR DESCRIPTION
**Pull request by Akctarus**
closes #15853

### CODE REVIEW

File: front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx [hunk 1]
```diff
@@ -221,12 +221,14 @@ const ItineraryModal = ({
     }
   };
 
-  // RS name
-  const name = useSelector(getName);
+  // Use a boolean selector so typing doesn't re-render the whole modal on every keystroke.
+  // Re-renders only when the name transitions between empty and non-empty.
+  const isNameEmpty = useSelector((state: Parameters<typeof getName>[0]) => {
```
Comment (emersion) [inline front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: Nit: could we be explicit about the type we're manipulating here instead of grabbing it from `getName`?

Comment (Akctarus) [reply front/src/applications/operationalStudies/views/Scenario/components/ManageTimetableItem/Itinerary/ItineraryModal.tsx]: good catch, fixed in 1d30d46300d7edcf065f00540b7d8e2bf67ecd93

**Review by emersion — APPROVED** [review]
Nice!
